hal: gate_library_parser_liberty Class Reference
gate_library_parser_liberty Class Reference
Netlist
#include <gate_library_parser_liberty.h>
Public Member Functions
gate_library_parser_liberty (std::stringstream &stream)
~gate_library_parser_liberty ()=default
std::shared_ptr< gate_library > parse () override
Public Member Functions inherited from gate_library_parser
gate_library_parser (std::stringstream &stream)
virtual ~gate_library_parser ()=default
Constructor & Destructor Documentation
gate_library_parser_liberty()
gate_library_parser_liberty::gate_library_parser_liberty (std::stringstream & stream) explicit
Parameters
[in] stream - The string stream filled with gate library definition.
~gate_library_parser_liberty()
gate_library_parser_liberty::~gate_library_parser_liberty () default
Member Function Documentation
parse()
std::shared_ptr< gate_library > gate_library_parser_liberty::parse () override virtual
Deserializes a gate library in Liberty format from the internal string stream into a gate library object. In order to also support lookup tables (LUTs) the following extension is allowed:
lut(<function name>) { data_category = <category>; data_identifier = <identifier>; direction = <"ascending" or "descending">; }
<category> and <identifier> refer to the location where the LUT configuration string is stored, for example "generic" and "init". direction describes whether the least significant bit of the configuration is the output for inputs 000... (ascending) or 111... (descending).
Returns
The deserialized gate library.
Implements gate_library_parser.
References gate_type::combinatorial, token_stream::consume(), token_stream::END_OF_STREAM, token_stream::extract_until(), gate_type::ff, boolean_function::from_string(), boolean_function::get_variables(), gate_type::latch, token_stream::token_stream_exception::line_number, log_error, gate_type::lut, token_stream::token_stream_exception::message, and token::string.
The documentation for this class was generated from the following files:
netlist/gate_library/gate_library_parser/gate_library_parser_liberty.h
/home/runner/work/hal/hal/src/netlist/gate_library/gate_library_parser/gate_library_parser_liberty.cpp