hal: hal::event_controls Namespace Reference
hal::event_controls Namespace Reference
Functions
NETLIST_API void enable_all (bool flag)
Function Documentation
enable_all()
void hal::event_controls::enable_all (bool flag)
Enables/disables callbacks for all event handlers.
Enabled by default.
Parameters
[in] flag - True to enable, false to disable.
References hal::netlist_event_handler::enable(), hal::module_event_handler::enable(), hal::net_event_handler::enable(), and hal::gate_event_handler::enable().