hal: hal::GateTypeLut Class Reference
hal::GateTypeLut Class Reference
HAL Core » Netlist » Gate Library
#include <gate_type_lut.h>
Public Member Functions
GateTypeLut (const std::string &name)
~GateTypeLut () override=default
void add_output_from_init_string_pin (const std::string &pin_name)
std::unordered_set< std::string > get_output_from_init_string_pins () const
void set_config_data_category (const std::string &category)
std::string get_config_data_category () const
void set_config_data_identifier (const std::string &identifier)
std::string get_config_data_identifier () const
void set_config_data_ascending_order (bool ascending)
bool is_config_data_ascending_order () const
Public Member Functions inherited from hal::GateType
GateType (const std::string &name)
virtual ~GateType ()=default
u32 get_id () const
std::string get_name () const
BaseType get_base_type () const
std::string to_string () const
bool operator== (const GateType &other) const
bool operator!= (const GateType &other) const
void add_input_pin (std::string pin_name)
void add_input_pins (const std::vector< std::string > &pin_names)
std::vector< std::string > get_input_pins () const
void add_output_pin (std::string pin_name)
void add_output_pins (const std::vector< std::string > &pin_names)
std::vector< std::string > get_output_pins () const
void assign_input_pin_group (const std::string &group_name, const std::map< u32, std::string > &index_to_pin)
void assign_input_pin_groups (const std::unordered_map< std::string, std::map< u32, std::string >> &pin_groups)
std::unordered_map< std::string, std::map< u32, std::string > > get_input_pin_groups () const
void assign_output_pin_group (const std::string &group_name, const std::map< u32, std::string > &index_to_pin)
void assign_output_pin_groups (const std::unordered_map< std::string, std::map< u32, std::string >> &pin_groups)
std::unordered_map< std::string, std::map< u32, std::string > > get_output_pin_groups () const
void add_boolean_function (std::string name, BooleanFunction function)
void add_boolean_functions (const std::unordered_map< std::string, BooleanFunction > &functions)
std::unordered_map< std::string, BooleanFunction > get_boolean_functions () const
Additional Inherited Members
Public Types inherited from hal::GateType
enum BaseType { BaseType::combinatorial, BaseType::lut, BaseType::ff, BaseType::latch }
Detailed Description
A LUT gate type contains information about its internals such as input and output pins as well as its Boolean functions.
In addition to the standard gate type functionality, it provides the foundation to automatically read the initialization string of each LUT gate of the netlist and convert it to a Boolean function.
Constructor & Destructor Documentation
GateTypeLut()
hal::GateTypeLut::GateTypeLut (const std::string & name)
Construct a new LUT gate type by specifying its name.
Parameters
[in] name - The name of the LUT gate type.
References hal::GateType::lut.
~GateTypeLut()
hal::GateTypeLut::~GateTypeLut () override default
Member Function Documentation
add_output_from_init_string_pin()
void hal::GateTypeLut::add_output_from_init_string_pin (const std::string & pin_name)
Add an existing output pin to the collection of output pins that generate their output not from a Boolean function but an initialization string.
The pin has to be declared as an output pin beforehand.
Parameters
[in] pin_name - The name of the output pin to add.
References log_warning.
Referenced by hal::gate_type_lut_init().
get_output_from_init_string_pins()
std::unordered_set< std::string > hal::GateTypeLut::get_output_from_init_string_pins () const
Get the set of output pins that generate their output not from a Boolean function but an initialization string.
Returns
The set of output pin names.
Referenced by hal::gate_type_lut_init(), and hal::Gate::get_boolean_function().
set_config_data_category()
void hal::GateTypeLut::set_config_data_category (const std::string & category)
Set the data category in which to find the initialization string.
Parameters
[in] category - The data category.
Referenced by hal::gate_type_lut_init().
get_config_data_category()
std::string hal::GateTypeLut::get_config_data_category () const
Get the data category in which to find the initialization string.
Returns
The data category.
Referenced by hal::gate_type_lut_init().
set_config_data_identifier()
void hal::GateTypeLut::set_config_data_identifier (const std::string & identifier)
Set the data identifier used to specify the initialization string.
Parameters
[in] identifier - The data identifier.
Referenced by hal::gate_type_lut_init().
get_config_data_identifier()
std::string hal::GateTypeLut::get_config_data_identifier () const
Get the data identifier used to specify the initialization string.
Returns
The data identifier.
Referenced by hal::gate_type_lut_init().
set_config_data_ascending_order()
void hal::GateTypeLut::set_config_data_ascending_order (bool ascending)
Set the bit-order of the initialization string.
Parameters
[in] ascending - True if ascending bit-order, false otherwise.
Referenced by hal::gate_type_lut_init().
is_config_data_ascending_order()
bool hal::GateTypeLut::is_config_data_ascending_order () const
Get the bit-order of the initialization string.
Returns
True if ascending bit-order, false otherwise.
Referenced by hal::gate_type_lut_init().
The documentation for this class was generated from the following files:
hal_core/netlist/gate_library/gate_type/gate_type_lut.h
/home/runner/work/hal/hal/src/netlist/gate_library/gate_type/gate_type_lut.cpp