hal: token_stream Class Reference
token_stream Class Reference
#include <token_stream.h>
Classes
struct token_stream_exception
Public Member Functions
token_stream (const std::vector< std::string > &increase_level_tokens={"("}, const std::vector< std::string > &decrease_level_tokens={")"})
token_stream (const std::vector< token > &init, const std::vector< std::string > &increase_level_tokens={"("}, const std::vector< std::string > &decrease_level_tokens={")"})
token_stream (const token_stream &other)
token consume (u32 num=1)
bool consume (const std::string &expected, bool throw_on_error=false)
token consume_until (const std::string &match, u32 end=END_OF_STREAM, bool level_aware=true, bool throw_on_error=false)
token_stream extract_until (const std::string &match, u32 end=END_OF_STREAM, bool level_aware=true, bool throw_on_error=false)
token join_until (const std::string &match, const std::string &joiner, u32 end=END_OF_STREAM, bool level_aware=true, bool throw_on_error=false)
token join (const std::string &joiner)
token & peek (i32 offset=0)
const token & peek (i32 offset=0) const
token & at (u32 position)
const token & at (u32 position) const
u32 find_next (const std::string &match, u32 end=END_OF_STREAM, bool level_aware=true) const
u32 size () const
u32 consumed () const
u32 remaining () const
u32 position () const
void set_position (u32 p)
Static Public Attributes
static const u32 END_OF_STREAM = 0xFFFFFFFF
Constructor & Destructor Documentation
token_stream() [1/3]
token_stream::token_stream (const std::vector< std::string > & increase_level_tokens = {"("}, const std::vector< std::string > & decrease_level_tokens = {")"})
Constructor for an empty token stream. The increase-level and decrease-level tokens are used for level-aware iteration. If active, only tokens on level 0 are matched Example: consuming until "b" in 'a,(,b,),b,c' would consume 'a,(,b,)', if "(" and ")" are level increase/decrease tokens.
Parameters
[in] decrease_level_tokens - the tokens that mark the start of a new level, i.e., increase the level.
[in] increase_level_tokens - the tokens that mark the end of a level, i.e., decrease the level.
token_stream() [2/3]
token_stream::token_stream (const std::vector< token > & init, const std::vector< std::string > & increase_level_tokens = {"("}, const std::vector< std::string > & decrease_level_tokens = {")"})
Initialization constructor. The increase-level and decrease-level tokens are used for level-aware iteration. If active, only tokens on level 0 are matched Example: consuming until "b" in 'a,(,b,),b,c' would consume 'a,(,b,)', if "(" and ")" are level increase/decrease tokens.
Parameters
[in] init - a token vector to initialize with
[in] decrease_level_tokens - the tokens that mark the start of a new level, i.e., increase the level.
[in] increase_level_tokens - the tokens that mark the end of a level, i.e., decrease the level.
token_stream() [3/3]
token_stream::token_stream (const token_stream & other)
Copy constructor.
Parameters
[in] other - the token stream to copy
Member Function Documentation
consume() [1/2]
token token_stream::consume (u32 num = 1)
Consume the next token(s) in the stream. Advances the stream by the given number and returns the last consumed token.
Throws a std::out_of_range exception if more tokens are consumed than are available.
Parameters
[in] num - the amount of tokens to consume
Returns
The last consumed token.
References at().
Referenced by join(), join_until(), hdl_parser_verilog::parse(), and gate_library_parser_liberty::parse().
consume() [2/2]
bool token_stream::consume (const std::string & expected, bool throw_on_error = false)
Consume the next token in the stream if it matches the given expected value. If the token does not match, the stream is unchanged.
Parameters
[in] expected - the expected token
[in] throw_on_error - if true, throws an token_stream_exception instead of returning false
Returns
True, if the next token matches the expected string, false otherwise or if no more tokens are available.
References at(), size(), and token::string.
consume_until()
token token_stream::consume_until (const std::string & match, u32 end = END_OF_STREAM, bool level_aware = true, bool throw_on_error = false)
Consume the next tokens in the stream until a token matches a given string. This final token is not consumed, i.e., it is now the next token in the stream. Consumes until the given end position if no token matches the given string. Can be set to be level-aware with respect to the configured level-down and level-up tokens.
Parameters
[in] match - the string on which to end.
[in] end - the absolute position in the stream on which to stop, even if match was not found until this point.
[in] level_aware - if false, tokens are also matched if they are not at the top-level.
[in] throw_on_error - if true, throws an token_stream_exception instead of returning false
Returns
The last consumed token.
References at(), find_next(), and size().
Referenced by hdl_parser_verilog::parse().
extract_until()
token_stream token_stream::extract_until (const std::string & match, u32 end = END_OF_STREAM, bool level_aware = true, bool throw_on_error = false)
Consume the next tokens in the stream until a token matches the given string. This final token is not consumed, i.e., it is now the next token in the stream. All consumed tokens are returned as a new token stream. Consumes until the given end position if no token matches the given string, i.e., the entire rest of the stream is returned as a new stream. Can be set to be level-aware with respect to the configured level-down and level-up tokens.
Parameters
[in] match - the string on which to end.
[in] end - the absolute position in the stream on which to stop, even if match was not found until this point.
[in] level_aware - if false, tokens are also matched if they are not at the top-level.
[in] throw_on_error - if true, throws an token_stream_exception instead of returning false
Returns
All consumed tokens in a new token stream.
References END_OF_STREAM, find_next(), and size().
Referenced by hdl_parser_verilog::parse(), and gate_library_parser_liberty::parse().
join_until()
token token_stream::join_until (const std::string & match, const std::string & joiner, u32 end = END_OF_STREAM, bool level_aware = true, bool throw_on_error = false)
Consume the next tokens in the stream until a token matches the given string. This final token is not consumed, i.e., it is now the next token in the stream. The strings of all consumed tokens are joined with the given joiner string and returned as a new token. The returned token has the line number of the first consumed token. Joins until the given end position if no token matches the given string until that point. Can be set to be level-aware with respect to the configured level-down and level-up tokens.
Parameters
[in] match - the string on which to end.
[in] joiner - the string used to join consumed tokens.
[in] end - the absolute position in the stream on which to stop, even if match was not found until this point.
[in] level_aware - if false, tokens are also matched if they are not at the top-level.
[in] throw_on_error - if true, throws an token_stream_exception instead of returning false
Returns
The joined token.
References consume(), find_next(), remaining(), and size().
join()
token token_stream::join (const std::string & joiner)
Consume all remaining tokens in the stream. The strings of all consumed tokens are joined with the given joiner string and returned as a new token. The returned token has the line number of the first consumed token.
Parameters
[in] joiner - the string used to join consumed tokens.
Returns
The joined token.
References consume(), and remaining().
peek() [1/2]
token & token_stream::peek (i32 offset = 0)
Return a token at a relative position in the stream. Can access tokens that have already been consumed. Position 0 is the first element of the stream.
Throws a std::out_of_range exception if the position is not contained in the stream.
Parameters
[in] offset - the relative offset from the current position in the stream
Returns
The token at the queried position.
References at().
Referenced by hdl_parser_verilog::parse().
peek() [2/2]
const token & token_stream::peek (i32 offset = 0) const
Return a token at a relative position in the stream. Can access tokens that have already been consumed. Position 0 is the first element of the stream.
Throws a std::out_of_range exception if the position is not contained in the stream.
Parameters
[in] offset - the relative offset from the current position in the stream
Returns
The token at the queried position.
References at().
at() [1/2]
token & token_stream::at (u32 position)
Return a token at an absolute position in the stream. Can access tokens that have already been consumed. Position 0 is the first element of the stream.
Throws a std::out_of_range exception if the position is not contained in the stream.
Parameters
[in] position - the absolute position in the stream
Returns
The token at the queried position.
References position().
Referenced by consume(), consume_until(), find_next(), and peek().
at() [2/2]
const token & token_stream::at (u32 position) const
References position().
find_next()
u32 token_stream::find_next (const std::string & match, u32 end = END_OF_STREAM, bool level_aware = true) const
Get the absolute position in the stream of the next matching token. If no token is found until the given end position, this end position is returned. Can be set to be level-aware with respect to the configured level-down and level-up tokens.
Parameters
[in] match - the string to match
[in] end - the absolute position in the stream on which to stop, even if match was not found until this point.
[in] level_aware - if false, tokens are also matched if they are not at the top-level.
Returns
The token at the queried position, or END_OF_STREAM if not found.
References at(), core_utils::equals_ignore_case(), and size().
Referenced by consume_until(), extract_until(), and join_until().
size()
u32 token_stream::size () const
Get the total number of elements in the token stream, regardless of how many have been consumed.
Returns
The total size of the token stream.
Referenced by consume(), consume_until(), extract_until(), find_next(), join_until(), and remaining().
consumed()
u32 token_stream::consumed () const
Get the total number of consumed elements in the token stream.
Returns
The total number of consumed tokens.
Referenced by remaining().
remaining()
u32 token_stream::remaining () const
Get the total number of remaining elements in the token stream.
Returns
The number of remaining tokens.
References consumed(), and size().
Referenced by join(), join_until(), and hdl_parser_verilog::parse().
position()
u32 token_stream::position () const
Get the current absolute position in the token stream.
Returns
The current position.
Referenced by at().
set_position()
void token_stream::set_position (u32 p)
Set the current absolute position in the token stream.
Parameters
[in] p - the new position
Member Data Documentation
END_OF_STREAM
const u32 token_stream::END_OF_STREAM = 0xFFFFFFFF static
Referenced by extract_until(), hdl_parser_verilog::parse(), and gate_library_parser_liberty::parse().
The documentation for this class was generated from the following files:
core/token_stream.h
/home/runner/work/hal/hal/src/core/token_stream.cpp