hal: gate_library Class Reference
gate_library Class Reference
Netlist
#include <gate_library.h>
Public Member Functions
gate_library (const std::string &name)
~gate_library ()=default
std::string get_name () const
void add_gate_type (std::shared_ptr< const gate_type > gt)
const std::map< std::string, std::shared_ptr< const gate_type > > & get_gate_types ()
const std::map< std::string, std::shared_ptr< const gate_type > > & get_vcc_gate_types ()
const std::map< std::string, std::shared_ptr< const gate_type > > & get_gnd_gate_types ()
void add_include (const std::string &inc)
std::vector< std::string > get_includes () const
Detailed Description
Gate library class containing information about the gates contained in the library.
Constructor & Destructor Documentation
gate_library()
gate_library::gate_library (const std::string & name)
Constructor.
Parameters
[in] name - Name of the gate library.
~gate_library()
gate_library::~gate_library () default
Member Function Documentation
get_name()
std::string gate_library::get_name () const
Get the name of the library.
Returns
The name.
Referenced by PYBIND11_PLUGIN().
add_gate_type()
void gate_library::add_gate_type (std::shared_ptr< const gate_type > gt)
Add a gate type to the gate library.
Parameters
[in] gt - The gate type object.
Referenced by PYBIND11_PLUGIN().
get_gate_types()
const std::map< std::string, std::shared_ptr< const gate_type > > & gate_library::get_gate_types ()
Get all gate types of the library.
Returns
A map from gate type names to gate type objects.
Referenced by PYBIND11_PLUGIN().
get_vcc_gate_types()
const std::map< std::string, std::shared_ptr< const gate_type > > & gate_library::get_vcc_gate_types ()
Get all VCC gate types of the library.
Returns
A map from VCC gate type names to gate type objects.
Referenced by PYBIND11_PLUGIN().
get_gnd_gate_types()
const std::map< std::string, std::shared_ptr< const gate_type > > & gate_library::get_gnd_gate_types ()
Get all GND gate types of the library.
Returns
A map from GND gate type names to gate type objects.
Referenced by PYBIND11_PLUGIN().
add_include()
void gate_library::add_include (const std::string & inc)
Add a necessary includes of the gate library, e.g., VHDL libraries.
Parameters
[in] inc - The include to add.
Referenced by PYBIND11_PLUGIN().
get_includes()
std::vector< std::string > gate_library::get_includes () const
Get a vector of necessary includes of the gate library, e.g., VHDL libraries.
Returns
A vector of includes.
Referenced by PYBIND11_PLUGIN().
The documentation for this class was generated from the following files:
netlist/gate_library/gate_library.h
/home/runner/work/hal/hal/src/netlist/gate_library/gate_library.cpp