hal: hal::hdl_parser_manager Namespace Reference
hal::hdl_parser_manager Namespace Reference
HAL Core » Netlist » Netlist Parser
Typedefs
using ParserFactory = std::function< std::unique_ptr< HDLParser >()>
Functions
NETLIST_API ProgramOptions get_cli_options ()
NETLIST_API void register_parser (const std::string &name, const ParserFactory &parser_factory, const std::vector< std::string > &supported_file_extensions)
NETLIST_API void unregister_parser (const std::string &name)
NETLIST_API std::unique_ptr< Netlist > parse (const std::filesystem::path &file_name, const ProgramArguments &args)
NETLIST_API std::unique_ptr< Netlist > parse (const std::filesystem::path &file_name, const GateLibrary *gate_library=nullptr)
std::vector< std::unique_ptr< Netlist > > parse_all (const std::filesystem::path &file_name)
Typedef Documentation
ParserFactory
using hal::hdl_parser_manager::ParserFactory = typedef std::function<std::unique_ptr<HDLParser>()>
Function Documentation
get_cli_options()
ProgramOptions hal::hdl_parser_manager::get_cli_options ()
Returns the command line interface options of the hdl parser manager
Returns
The options.
register_parser()
void hal::hdl_parser_manager::register_parser (const std::string & name, const ParserFactory & parser_factory, const std::vector< std::string > & supported_file_extensions)
Registers a new HDL parser for a selection of file types. If parsers for some of the extensions already exist, they are not changed, only the new ones are registered.
Parameters
[in] name - The name of the parser.
[in] parser_factory - A factory function that constructs a new parser instance.
[in] supported_file_extensions - The file extensions this parser can process.
References log_info, log_warning, hal::utils::to_lower(), and hal::utils::trim().
unregister_parser()
void hal::hdl_parser_manager::unregister_parser (const std::string & name)
Unregisters a specific parser.
Parameters
[in] name - The name of the parser.
References log_info.
parse() [1/2]
std::unique_ptr< Netlist > hal::hdl_parser_manager::parse (const std::filesystem::path & file_name, const ProgramArguments & args)
Returns the netlist for the file and specified command line options.
Parameters
[in] file_name - The input file.
[in] args - The command line options.
Returns
The netlist representation of the hdl code or a nullpointer on error.
References hal::gate_library_manager::get_gate_library(), hal::ProgramArguments::get_parameter(), hal::ProgramArguments::is_option_set(), and log_error.
Referenced by hal::netlist_factory::load_netlist(), and hal::HDLParser::parse_and_instantiate().
parse() [2/2]
std::unique_ptr< Netlist > hal::hdl_parser_manager::parse (const std::filesystem::path & file_name, const GateLibrary * gate_library = nullptr)
Returns the netlist for a file, parsed with a defined gate library.
Parameters
[in] file_name - The input file.
[in] gate_library - The gate library used in the file.
Returns
The netlist representation of the hdl code or a nullpointer on error.
parse_all()
std::vector< std::unique_ptr< Netlist > > hal::hdl_parser_manager::parse_all (const std::filesystem::path & file_name)
Tries to match the HDL file with each of the preloaded gate libraries and returns a vector of netlist objects for which the matching was successful.
Parameters
[in] hdl_file - The netlist file.
Returns
A vector containing one netlist per matching gate library.
Referenced by hal::netlist_factory::load_netlists().