hal: library_loader Class Reference
library_loader Class Reference
HAL Core
#include <library_loader.h>
Public Member Functions
library_loader ()
~library_loader ()
bool load_library (const std::string &file_name)
std::string get_file_name () const
bool unload_library ()
lib_fn_ptr_t get_function (const std::string &function_name)
Constructor & Destructor Documentation
library_loader()
library_loader::library_loader ()
~library_loader()
library_loader::~library_loader ()
References unload_library().
Member Function Documentation
load_library()
bool library_loader::load_library (const std::string & file_name)
Loads a library.
Parameters
[in] file_name - Name of the library.
Returns
True on success.
References log_debug, and log_error.
Referenced by plugin_manager::load().
get_file_name()
std::string library_loader::get_file_name () const
Gets the file name of the loaded library.
Returns
The file name.
unload_library()
bool library_loader::unload_library ()
Unloads the library.
Returns
True on success.
References log_debug, and log_error.
Referenced by ~library_loader().
get_function()
lib_fn_ptr_t library_loader::get_function (const std::string & function_name)
Gets the function pointer to a function by name.
Parameters
[in] function_name - Name of the function.
Returns
The function pointer.
References log_debug, and log_error.
Referenced by plugin_manager::load().
The documentation for this class was generated from the following files:
core/library_loader.h
/home/runner/work/hal/hal/src/core/library_loader.cpp