hal: hal::Endpoint Class Reference
hal::Endpoint Class Reference
Netlist
#include <endpoint.h>
Public Member Functions
Endpoint (Gate *gate, const std::string &pin, Net *net, bool is_a_destination)
Endpoint ()
Endpoint (const Endpoint &)=default
Endpoint (Endpoint &&)=default
Endpoint & operator= (const Endpoint &)=default
Endpoint & operator= (Endpoint &&)=default
bool operator< (const Endpoint &rhs) const
bool operator== (const Endpoint &rhs) const
bool operator!= (const Endpoint &rhs) const
Gate * get_gate () const
const std::string & get_pin () const
Net * get_net () const
bool is_destination_pin () const
bool is_source_pin () const
Detailed Description
Endpoint data structure for (gate, pin) tuples
Constructor & Destructor Documentation
Endpoint() [1/4]
hal::Endpoint::Endpoint (Gate * gate, const std::string & pin, Net * net, bool is_a_destination)
Construct an endpoint object.
Parameters
[in] gate - The gate of the endpoint.
[in] pin - The pin of the endpoint.
[in] net - The net of the endpoint.
[in] is_a_destination - True if the endpoint is an output pin, false if it is an input pin.
Endpoint() [2/4]
hal::Endpoint::Endpoint ()
Endpoint() [3/4]
hal::Endpoint::Endpoint (const Endpoint &) default
Endpoint() [4/4]
hal::Endpoint::Endpoint (Endpoint &&) default
Member Function Documentation
operator=() [1/2]
Endpoint& hal::Endpoint::operator= (const Endpoint &) default
operator=() [2/2]
Endpoint& hal::Endpoint::operator= (Endpoint &&) default
operator<()
bool hal::Endpoint::operator< (const Endpoint & rhs) const
Standard "less than".
Required for searching through sets.
Parameters
[in] rhs - Compare target.
Returns
True if this is less than rhs.
operator==()
bool hal::Endpoint::operator== (const Endpoint & rhs) const
Standard "equals".
Required for searching through sets.
Parameters
[in] rhs - Compare target.
Returns
True if this is equal to rhs.
operator!=()
bool hal::Endpoint::operator!= (const Endpoint & rhs) const
Standard "unequal".
Parameters
[in] rhs - Compare target.
Returns
True if this is unequal to rhs.
get_gate()
Gate * hal::Endpoint::get_gate () const
Returns the gate of the endpoint.
Returns
The gate.
Referenced by hal::endpoint_init().
get_pin()
const std::string & hal::Endpoint::get_pin () const
Returns the pin of the endpoint.
Returns
The pin.
Referenced by hal::endpoint_init().
get_net()
Net * hal::Endpoint::get_net () const
Returns the net of the endpoint.
Returns
The net.
Referenced by hal::endpoint_init().
is_destination_pin()
bool hal::Endpoint::is_destination_pin () const
Checks whether the pin of the endpoint is a destination pin.
Returns
True, if the endpoint is an input pin.
Referenced by hal::endpoint_init(), and hal::Net::is_a_destination().
is_source_pin()
bool hal::Endpoint::is_source_pin () const
Checks whether the pin of the endpoint is a source pin.
Returns
True, if the endpoint is an output pin.
Referenced by hal::endpoint_init(), and hal::Net::is_a_source().
The documentation for this class was generated from the following files:
hal_core/netlist/endpoint.h
/home/runner/work/hal/hal/src/netlist/endpoint.cpp