/* Generated by Yosys 0.30+38 (git sha1 596da3f2a, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\top" *)
(* top =  1  *)
(* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.1-6.10" *)
module top(a, b, out);
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _000_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _001_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _002_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _003_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _004_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _005_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _006_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _007_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _008_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _009_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _010_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _011_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _012_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _013_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _014_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _015_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _016_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _017_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _018_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _019_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _020_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _021_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _022_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _023_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _024_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _025_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _026_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _027_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _028_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _029_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _030_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  wire _031_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _032_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _033_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _034_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _035_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _036_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _037_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _038_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _039_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _040_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _041_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _042_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _043_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _044_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _045_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _046_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _180_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _181_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _182_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _183_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _184_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _185_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _186_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _187_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _188_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _189_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _190_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _191_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _192_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _193_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _194_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _195_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _196_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _197_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _198_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _199_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _200_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _201_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _202_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _203_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _204_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _205_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _206_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _207_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _208_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _209_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _210_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _211_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  wire _212_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  wire [32:0] _213_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [32:0] _214_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:214.23-214.24" *)
  wire [32:0] _215_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _216_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _217_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _218_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _219_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _220_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _221_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _222_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _223_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _224_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _225_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _226_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _227_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _228_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _229_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _230_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _231_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _232_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _233_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _234_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _235_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _236_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _237_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _238_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _239_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _240_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _241_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _242_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _243_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _244_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _245_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _246_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _247_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _248_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _249_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _250_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _251_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _252_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _253_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _254_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _255_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _256_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _257_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _258_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _259_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _260_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _261_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _262_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _263_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _264_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _265_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _266_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _267_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _268_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _269_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _270_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _271_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _272_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _273_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _274_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _275_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _276_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _277_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _278_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _279_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _280_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _281_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _282_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _283_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _284_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _285_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _286_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _287_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _288_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _289_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _290_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _291_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _292_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _293_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _294_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _295_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _296_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _297_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _298_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _299_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _300_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _301_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _302_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _303_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _304_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _305_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _306_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _307_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _308_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _309_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _310_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _311_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _312_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _313_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _314_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _315_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _316_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _317_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _318_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _319_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _320_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _321_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _322_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _323_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:5.17-5.37|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _324_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:1.29-1.30" *)
  input [31:0] a;
  wire [31:0] a;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:2.29-2.30" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/addition_carry_sign_extened_32bit/addition_carry_sign_extened_32bit.v:3.30-3.33" *)
  output [32:0] out;
  wire [32:0] out;
  INV_X1 _325_ (
    .A(_038_),
    .ZN(_162_)
  );
  INV_X1 _326_ (
    .A(_016_),
    .ZN(_163_)
  );
  AND2_X1 _327_ (
    .A1(_003_),
    .A2(_035_),
    .ZN(_164_)
  );
  NAND2_X1 _328_ (
    .A1(_002_),
    .A2(_034_),
    .ZN(_165_)
  );
  NOR2_X1 _329_ (
    .A1(_002_),
    .A2(_034_),
    .ZN(_166_)
  );
  AND2_X1 _330_ (
    .A1(_001_),
    .A2(_033_),
    .ZN(_167_)
  );
  OR2_X1 _331_ (
    .A1(_001_),
    .A2(_033_),
    .ZN(_168_)
  );
  XNOR2_X1 _332_ (
    .A(_001_),
    .B(_033_),
    .ZN(_169_)
  );
  NAND2_X1 _333_ (
    .A1(_031_),
    .A2(_047_),
    .ZN(_170_)
  );
  NOR2_X1 _334_ (
    .A1(_031_),
    .A2(_047_),
    .ZN(_171_)
  );
  AND2_X1 _335_ (
    .A1(_030_),
    .A2(_046_),
    .ZN(_172_)
  );
  OR2_X1 _336_ (
    .A1(_030_),
    .A2(_046_),
    .ZN(_173_)
  );
  XNOR2_X1 _337_ (
    .A(_030_),
    .B(_046_),
    .ZN(_174_)
  );
  NAND2_X1 _338_ (
    .A1(_029_),
    .A2(_045_),
    .ZN(_175_)
  );
  NOR2_X1 _339_ (
    .A1(_029_),
    .A2(_045_),
    .ZN(_176_)
  );
  AND2_X1 _340_ (
    .A1(_028_),
    .A2(_044_),
    .ZN(_177_)
  );
  OR2_X1 _341_ (
    .A1(_028_),
    .A2(_044_),
    .ZN(_178_)
  );
  XNOR2_X1 _342_ (
    .A(_028_),
    .B(_044_),
    .ZN(_179_)
  );
  NAND2_X1 _343_ (
    .A1(_027_),
    .A2(_043_),
    .ZN(_048_)
  );
  AND2_X1 _344_ (
    .A1(_026_),
    .A2(_042_),
    .ZN(_049_)
  );
  NAND2_X1 _345_ (
    .A1(_025_),
    .A2(_041_),
    .ZN(_050_)
  );
  AND2_X1 _346_ (
    .A1(_022_),
    .A2(_040_),
    .ZN(_051_)
  );
  NAND2_X1 _347_ (
    .A1(_011_),
    .A2(_039_),
    .ZN(_052_)
  );
  NAND2_X1 _348_ (
    .A1(_000_),
    .A2(_032_),
    .ZN(_053_)
  );
  NOR2_X1 _349_ (
    .A1(_011_),
    .A2(_039_),
    .ZN(_054_)
  );
  XOR2_X1 _350_ (
    .A(_011_),
    .B(_039_),
    .Z(_055_)
  );
  OAI21_X1 _351_ (
    .A(_052_),
    .B1(_053_),
    .B2(_054_),
    .ZN(_056_)
  );
  OR2_X1 _352_ (
    .A1(_022_),
    .A2(_040_),
    .ZN(_057_)
  );
  XNOR2_X1 _353_ (
    .A(_022_),
    .B(_040_),
    .ZN(_058_)
  );
  AOI21_X1 _354_ (
    .A(_051_),
    .B1(_056_),
    .B2(_057_),
    .ZN(_059_)
  );
  NOR2_X1 _355_ (
    .A1(_025_),
    .A2(_041_),
    .ZN(_060_)
  );
  XOR2_X1 _356_ (
    .A(_025_),
    .B(_041_),
    .Z(_061_)
  );
  OAI21_X1 _357_ (
    .A(_050_),
    .B1(_059_),
    .B2(_060_),
    .ZN(_062_)
  );
  OR2_X1 _358_ (
    .A1(_026_),
    .A2(_042_),
    .ZN(_063_)
  );
  XNOR2_X1 _359_ (
    .A(_026_),
    .B(_042_),
    .ZN(_064_)
  );
  AOI21_X1 _360_ (
    .A(_049_),
    .B1(_062_),
    .B2(_063_),
    .ZN(_065_)
  );
  NOR2_X1 _361_ (
    .A1(_027_),
    .A2(_043_),
    .ZN(_066_)
  );
  XOR2_X1 _362_ (
    .A(_027_),
    .B(_043_),
    .Z(_067_)
  );
  OAI21_X1 _363_ (
    .A(_048_),
    .B1(_065_),
    .B2(_066_),
    .ZN(_068_)
  );
  AOI21_X1 _364_ (
    .A(_177_),
    .B1(_178_),
    .B2(_068_),
    .ZN(_069_)
  );
  OAI21_X1 _365_ (
    .A(_175_),
    .B1(_176_),
    .B2(_069_),
    .ZN(_070_)
  );
  AOI21_X1 _366_ (
    .A(_172_),
    .B1(_173_),
    .B2(_070_),
    .ZN(_071_)
  );
  OAI21_X1 _367_ (
    .A(_170_),
    .B1(_171_),
    .B2(_071_),
    .ZN(_072_)
  );
  AOI21_X1 _368_ (
    .A(_167_),
    .B1(_168_),
    .B2(_072_),
    .ZN(_073_)
  );
  OAI21_X1 _369_ (
    .A(_165_),
    .B1(_166_),
    .B2(_073_),
    .ZN(_074_)
  );
  OR2_X1 _370_ (
    .A1(_003_),
    .A2(_035_),
    .ZN(_075_)
  );
  XNOR2_X1 _371_ (
    .A(_003_),
    .B(_035_),
    .ZN(_076_)
  );
  AOI21_X1 _372_ (
    .A(_164_),
    .B1(_074_),
    .B2(_075_),
    .ZN(_077_)
  );
  NAND2_X1 _373_ (
    .A1(_004_),
    .A2(_036_),
    .ZN(_078_)
  );
  NOR2_X1 _374_ (
    .A1(_004_),
    .A2(_036_),
    .ZN(_079_)
  );
  XOR2_X1 _375_ (
    .A(_004_),
    .B(_036_),
    .Z(_080_)
  );
  XNOR2_X1 _376_ (
    .A(_077_),
    .B(_080_),
    .ZN(_184_)
  );
  OAI21_X1 _377_ (
    .A(_078_),
    .B1(_079_),
    .B2(_077_),
    .ZN(_081_)
  );
  AND2_X1 _378_ (
    .A1(_005_),
    .A2(_037_),
    .ZN(_082_)
  );
  OR2_X1 _379_ (
    .A1(_005_),
    .A2(_037_),
    .ZN(_083_)
  );
  XNOR2_X1 _380_ (
    .A(_005_),
    .B(_037_),
    .ZN(_084_)
  );
  XNOR2_X1 _381_ (
    .A(_081_),
    .B(_084_),
    .ZN(_185_)
  );
  AOI21_X1 _382_ (
    .A(_082_),
    .B1(_083_),
    .B2(_081_),
    .ZN(_085_)
  );
  NAND2_X1 _383_ (
    .A1(_006_),
    .A2(_038_),
    .ZN(_086_)
  );
  NOR2_X1 _384_ (
    .A1(_006_),
    .A2(_038_),
    .ZN(_087_)
  );
  XOR2_X1 _385_ (
    .A(_006_),
    .B(_038_),
    .Z(_088_)
  );
  XNOR2_X1 _386_ (
    .A(_085_),
    .B(_088_),
    .ZN(_186_)
  );
  OAI21_X1 _387_ (
    .A(_086_),
    .B1(_087_),
    .B2(_085_),
    .ZN(_089_)
  );
  AND2_X1 _388_ (
    .A1(_038_),
    .A2(_007_),
    .ZN(_090_)
  );
  XOR2_X1 _389_ (
    .A(_038_),
    .B(_007_),
    .Z(_091_)
  );
  XOR2_X1 _390_ (
    .A(_089_),
    .B(_091_),
    .Z(_187_)
  );
  AOI21_X1 _391_ (
    .A(_090_),
    .B1(_091_),
    .B2(_089_),
    .ZN(_092_)
  );
  XNOR2_X1 _392_ (
    .A(_038_),
    .B(_008_),
    .ZN(_093_)
  );
  INV_X1 _393_ (
    .A(_093_),
    .ZN(_094_)
  );
  XNOR2_X1 _394_ (
    .A(_092_),
    .B(_094_),
    .ZN(_188_)
  );
  NAND3_X1 _395_ (
    .A1(_089_),
    .A2(_091_),
    .A3(_094_),
    .ZN(_095_)
  );
  OAI21_X1 _396_ (
    .A(_038_),
    .B1(_007_),
    .B2(_008_),
    .ZN(_096_)
  );
  XNOR2_X1 _397_ (
    .A(_038_),
    .B(_009_),
    .ZN(_097_)
  );
  AOI21_X1 _398_ (
    .A(_097_),
    .B1(_096_),
    .B2(_095_),
    .ZN(_098_)
  );
  AND3_X1 _399_ (
    .A1(_095_),
    .A2(_096_),
    .A3(_097_),
    .ZN(_099_)
  );
  NOR2_X1 _400_ (
    .A1(_098_),
    .A2(_099_),
    .ZN(_189_)
  );
  AOI21_X1 _401_ (
    .A(_098_),
    .B1(_009_),
    .B2(_038_),
    .ZN(_100_)
  );
  XOR2_X1 _402_ (
    .A(_038_),
    .B(_010_),
    .Z(_101_)
  );
  INV_X1 _403_ (
    .A(_101_),
    .ZN(_102_)
  );
  XNOR2_X1 _404_ (
    .A(_100_),
    .B(_101_),
    .ZN(_190_)
  );
  NOR2_X1 _405_ (
    .A1(_097_),
    .A2(_102_),
    .ZN(_103_)
  );
  NAND4_X1 _406_ (
    .A1(_089_),
    .A2(_091_),
    .A3(_094_),
    .A4(_103_),
    .ZN(_104_)
  );
  NOR4_X1 _407_ (
    .A1(_007_),
    .A2(_008_),
    .A3(_009_),
    .A4(_010_),
    .ZN(_105_)
  );
  OR2_X1 _408_ (
    .A1(_162_),
    .A2(_105_),
    .ZN(_106_)
  );
  AND2_X1 _409_ (
    .A1(_104_),
    .A2(_106_),
    .ZN(_107_)
  );
  NAND2_X1 _410_ (
    .A1(_038_),
    .A2(_012_),
    .ZN(_108_)
  );
  OR2_X1 _411_ (
    .A1(_038_),
    .A2(_012_),
    .ZN(_109_)
  );
  NAND2_X1 _412_ (
    .A1(_108_),
    .A2(_109_),
    .ZN(_110_)
  );
  XOR2_X1 _413_ (
    .A(_107_),
    .B(_110_),
    .Z(_192_)
  );
  OAI21_X1 _414_ (
    .A(_108_),
    .B1(_110_),
    .B2(_107_),
    .ZN(_111_)
  );
  XOR2_X1 _415_ (
    .A(_038_),
    .B(_013_),
    .Z(_112_)
  );
  XOR2_X1 _416_ (
    .A(_111_),
    .B(_112_),
    .Z(_193_)
  );
  NAND3_X1 _417_ (
    .A1(_108_),
    .A2(_109_),
    .A3(_112_),
    .ZN(_113_)
  );
  OR2_X1 _418_ (
    .A1(_107_),
    .A2(_113_),
    .ZN(_114_)
  );
  OAI21_X1 _419_ (
    .A(_038_),
    .B1(_012_),
    .B2(_013_),
    .ZN(_115_)
  );
  NAND2_X1 _420_ (
    .A1(_114_),
    .A2(_115_),
    .ZN(_116_)
  );
  XNOR2_X1 _421_ (
    .A(_038_),
    .B(_014_),
    .ZN(_117_)
  );
  AOI21_X1 _422_ (
    .A(_117_),
    .B1(_115_),
    .B2(_114_),
    .ZN(_118_)
  );
  XNOR2_X1 _423_ (
    .A(_116_),
    .B(_117_),
    .ZN(_194_)
  );
  AOI21_X1 _424_ (
    .A(_118_),
    .B1(_014_),
    .B2(_038_),
    .ZN(_119_)
  );
  XNOR2_X1 _425_ (
    .A(_038_),
    .B(_015_),
    .ZN(_120_)
  );
  XOR2_X1 _426_ (
    .A(_119_),
    .B(_120_),
    .Z(_195_)
  );
  NOR4_X1 _427_ (
    .A1(_012_),
    .A2(_013_),
    .A3(_014_),
    .A4(_015_),
    .ZN(_121_)
  );
  NOR2_X1 _428_ (
    .A1(_162_),
    .A2(_121_),
    .ZN(_122_)
  );
  NOR2_X1 _429_ (
    .A1(_117_),
    .A2(_120_),
    .ZN(_123_)
  );
  INV_X1 _430_ (
    .A(_123_),
    .ZN(_124_)
  );
  AOI211_X1 _431_ (
    .A(_113_),
    .B(_124_),
    .C1(_104_),
    .C2(_106_),
    .ZN(_125_)
  );
  XOR2_X1 _432_ (
    .A(_038_),
    .B(_016_),
    .Z(_126_)
  );
  OAI21_X1 _433_ (
    .A(_126_),
    .B1(_125_),
    .B2(_122_),
    .ZN(_127_)
  );
  OR3_X1 _434_ (
    .A1(_122_),
    .A2(_125_),
    .A3(_126_),
    .ZN(_128_)
  );
  AND2_X1 _435_ (
    .A1(_127_),
    .A2(_128_),
    .ZN(_196_)
  );
  OAI21_X1 _436_ (
    .A(_127_),
    .B1(_163_),
    .B2(_162_),
    .ZN(_129_)
  );
  XNOR2_X1 _437_ (
    .A(_038_),
    .B(_017_),
    .ZN(_130_)
  );
  INV_X1 _438_ (
    .A(_130_),
    .ZN(_131_)
  );
  XNOR2_X1 _439_ (
    .A(_129_),
    .B(_130_),
    .ZN(_197_)
  );
  OAI211_X1 _440_ (
    .A(_126_),
    .B(_131_),
    .C1(_122_),
    .C2(_125_),
    .ZN(_132_)
  );
  OAI21_X1 _441_ (
    .A(_038_),
    .B1(_016_),
    .B2(_017_),
    .ZN(_133_)
  );
  XNOR2_X1 _442_ (
    .A(_038_),
    .B(_018_),
    .ZN(_134_)
  );
  INV_X1 _443_ (
    .A(_134_),
    .ZN(_135_)
  );
  AOI21_X1 _444_ (
    .A(_134_),
    .B1(_133_),
    .B2(_132_),
    .ZN(_136_)
  );
  NAND3_X1 _445_ (
    .A1(_132_),
    .A2(_133_),
    .A3(_134_),
    .ZN(_137_)
  );
  INV_X1 _446_ (
    .A(_137_),
    .ZN(_138_)
  );
  NOR2_X1 _447_ (
    .A1(_136_),
    .A2(_138_),
    .ZN(_198_)
  );
  AOI21_X1 _448_ (
    .A(_136_),
    .B1(_018_),
    .B2(_038_),
    .ZN(_139_)
  );
  XOR2_X1 _449_ (
    .A(_038_),
    .B(_019_),
    .Z(_140_)
  );
  XNOR2_X1 _450_ (
    .A(_139_),
    .B(_140_),
    .ZN(_199_)
  );
  NAND2_X1 _451_ (
    .A1(_135_),
    .A2(_140_),
    .ZN(_141_)
  );
  NOR4_X1 _452_ (
    .A1(_016_),
    .A2(_017_),
    .A3(_018_),
    .A4(_019_),
    .ZN(_142_)
  );
  OAI22_X1 _453_ (
    .A1(_132_),
    .A2(_141_),
    .B1(_142_),
    .B2(_162_),
    .ZN(_143_)
  );
  INV_X1 _454_ (
    .A(_143_),
    .ZN(_144_)
  );
  NAND2_X1 _455_ (
    .A1(_038_),
    .A2(_020_),
    .ZN(_145_)
  );
  XNOR2_X1 _456_ (
    .A(_038_),
    .B(_020_),
    .ZN(_146_)
  );
  XNOR2_X1 _457_ (
    .A(_143_),
    .B(_146_),
    .ZN(_200_)
  );
  OAI21_X1 _458_ (
    .A(_145_),
    .B1(_146_),
    .B2(_144_),
    .ZN(_147_)
  );
  XNOR2_X1 _459_ (
    .A(_038_),
    .B(_021_),
    .ZN(_148_)
  );
  XNOR2_X1 _460_ (
    .A(_147_),
    .B(_148_),
    .ZN(_201_)
  );
  NOR2_X1 _461_ (
    .A1(_146_),
    .A2(_148_),
    .ZN(_149_)
  );
  OR2_X1 _462_ (
    .A1(_020_),
    .A2(_021_),
    .ZN(_150_)
  );
  AOI22_X1 _463_ (
    .A1(_143_),
    .A2(_149_),
    .B1(_150_),
    .B2(_038_),
    .ZN(_151_)
  );
  NAND2_X1 _464_ (
    .A1(_038_),
    .A2(_023_),
    .ZN(_152_)
  );
  NOR2_X1 _465_ (
    .A1(_038_),
    .A2(_023_),
    .ZN(_153_)
  );
  XOR2_X1 _466_ (
    .A(_038_),
    .B(_023_),
    .Z(_154_)
  );
  XNOR2_X1 _467_ (
    .A(_151_),
    .B(_154_),
    .ZN(_203_)
  );
  OAI21_X1 _468_ (
    .A(_152_),
    .B1(_153_),
    .B2(_151_),
    .ZN(_155_)
  );
  XOR2_X1 _469_ (
    .A(_038_),
    .B(_024_),
    .Z(_156_)
  );
  XOR2_X1 _470_ (
    .A(_155_),
    .B(_156_),
    .Z(_204_)
  );
  XOR2_X1 _471_ (
    .A(_000_),
    .B(_032_),
    .Z(_180_)
  );
  NOR3_X1 _472_ (
    .A1(_023_),
    .A2(_024_),
    .A3(_150_),
    .ZN(_157_)
  );
  NAND3_X1 _473_ (
    .A1(_149_),
    .A2(_154_),
    .A3(_156_),
    .ZN(_158_)
  );
  OAI22_X1 _474_ (
    .A1(_162_),
    .A2(_157_),
    .B1(_158_),
    .B2(_144_),
    .ZN(_205_)
  );
  XNOR2_X1 _475_ (
    .A(_053_),
    .B(_055_),
    .ZN(_191_)
  );
  XNOR2_X1 _476_ (
    .A(_056_),
    .B(_058_),
    .ZN(_202_)
  );
  XNOR2_X1 _477_ (
    .A(_059_),
    .B(_061_),
    .ZN(_206_)
  );
  XNOR2_X1 _478_ (
    .A(_062_),
    .B(_064_),
    .ZN(_207_)
  );
  XNOR2_X1 _479_ (
    .A(_065_),
    .B(_067_),
    .ZN(_208_)
  );
  XNOR2_X1 _480_ (
    .A(_179_),
    .B(_068_),
    .ZN(_209_)
  );
  XOR2_X1 _481_ (
    .A(_029_),
    .B(_045_),
    .Z(_159_)
  );
  XNOR2_X1 _482_ (
    .A(_069_),
    .B(_159_),
    .ZN(_210_)
  );
  XNOR2_X1 _483_ (
    .A(_174_),
    .B(_070_),
    .ZN(_211_)
  );
  XOR2_X1 _484_ (
    .A(_031_),
    .B(_047_),
    .Z(_160_)
  );
  XNOR2_X1 _485_ (
    .A(_071_),
    .B(_160_),
    .ZN(_212_)
  );
  XNOR2_X1 _486_ (
    .A(_169_),
    .B(_072_),
    .ZN(_181_)
  );
  XOR2_X1 _487_ (
    .A(_002_),
    .B(_034_),
    .Z(_161_)
  );
  XNOR2_X1 _488_ (
    .A(_073_),
    .B(_161_),
    .ZN(_182_)
  );
  XNOR2_X1 _489_ (
    .A(_074_),
    .B(_076_),
    .ZN(_183_)
  );
  assign _213_[32:31] = { 1'h0, out[32] };
  assign { _214_[32], _214_[0] } = { 1'h0, out[0] };
  assign { _215_[32], _215_[0] } = { 1'h0, _213_[0] };
  assign out[13] = _184_;
  assign out[14] = _185_;
  assign out[15] = _186_;
  assign out[16] = _187_;
  assign out[17] = _188_;
  assign out[18] = _189_;
  assign out[19] = _190_;
  assign out[20] = _192_;
  assign out[21] = _193_;
  assign out[22] = _194_;
  assign out[23] = _195_;
  assign out[24] = _196_;
  assign out[25] = _197_;
  assign out[26] = _198_;
  assign out[27] = _199_;
  assign out[28] = _200_;
  assign out[29] = _201_;
  assign out[30] = _203_;
  assign out[31] = _204_;
  assign _000_ = a[0];
  assign _032_ = b[0];
  assign out[0] = _180_;
  assign _011_ = a[1];
  assign _039_ = b[1];
  assign _022_ = a[2];
  assign _040_ = b[2];
  assign _025_ = a[3];
  assign _041_ = b[3];
  assign _026_ = a[4];
  assign _042_ = b[4];
  assign _027_ = a[5];
  assign _043_ = b[5];
  assign _028_ = a[6];
  assign _044_ = b[6];
  assign _029_ = a[7];
  assign _045_ = b[7];
  assign _030_ = a[8];
  assign _046_ = b[8];
  assign _031_ = a[9];
  assign _047_ = b[9];
  assign _001_ = a[10];
  assign _033_ = b[10];
  assign _002_ = a[11];
  assign _034_ = b[11];
  assign _003_ = a[12];
  assign _035_ = b[12];
  assign _004_ = a[13];
  assign _036_ = b[13];
  assign _005_ = a[14];
  assign _037_ = b[14];
  assign _006_ = a[15];
  assign _038_ = b[15];
  assign _007_ = a[16];
  assign _008_ = a[17];
  assign _009_ = a[18];
  assign _010_ = a[19];
  assign _012_ = a[20];
  assign _013_ = a[21];
  assign _014_ = a[22];
  assign _015_ = a[23];
  assign _016_ = a[24];
  assign _017_ = a[25];
  assign _018_ = a[26];
  assign _019_ = a[27];
  assign _020_ = a[28];
  assign _021_ = a[29];
  assign _023_ = a[30];
  assign _024_ = a[31];
  assign out[32] = _205_;
  assign out[1] = _191_;
  assign out[2] = _202_;
  assign out[3] = _206_;
  assign out[4] = _207_;
  assign out[5] = _208_;
  assign out[6] = _209_;
  assign out[7] = _210_;
  assign out[8] = _211_;
  assign out[9] = _212_;
  assign out[10] = _181_;
  assign out[11] = _182_;
  assign out[12] = _183_;
endmodule
