/* Generated by Yosys 0.30+38 (git sha1 596da3f2a, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\top" *)
(* top =  1  *)
(* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.1-5.10" *)
module top(a, out);
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _000_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _001_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _002_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _003_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _004_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _005_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _006_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _007_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _008_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _009_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _010_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _011_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _012_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _013_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _014_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _015_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _016_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _017_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _018_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _019_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _020_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _021_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _022_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _023_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _024_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _025_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _026_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _027_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _028_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _029_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _030_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _071_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _072_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _073_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _074_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _075_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _076_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _077_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _078_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _079_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _080_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _081_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _082_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _083_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _084_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _085_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _086_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _087_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _088_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _089_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _090_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _091_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _092_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _093_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _094_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _095_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _096_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _097_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _098_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _099_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _100_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _101_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  wire _102_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "31" *)
  wire [31:0] _103_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _104_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _105_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _106_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _107_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _108_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _109_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _110_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _111_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _112_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _113_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _114_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _115_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _116_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _117_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _118_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _119_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _120_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _121_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _122_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _123_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _124_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:4.17-4.22|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _125_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:1.29-1.30" *)
  input [31:0] a;
  wire [31:0] a;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/counter_32bit/counter_32bit.v:2.30-2.33" *)
  output [31:0] out;
  wire [31:0] out;
  INV_X1 _126_ (
    .A(_000_),
    .ZN(_071_)
  );
  INV_X1 _127_ (
    .A(_004_),
    .ZN(_045_)
  );
  INV_X1 _128_ (
    .A(_005_),
    .ZN(_046_)
  );
  INV_X1 _129_ (
    .A(_006_),
    .ZN(_047_)
  );
  INV_X1 _130_ (
    .A(_010_),
    .ZN(_048_)
  );
  INV_X1 _131_ (
    .A(_012_),
    .ZN(_049_)
  );
  INV_X1 _132_ (
    .A(_013_),
    .ZN(_050_)
  );
  INV_X1 _133_ (
    .A(_017_),
    .ZN(_051_)
  );
  INV_X1 _134_ (
    .A(_018_),
    .ZN(_052_)
  );
  INV_X1 _135_ (
    .A(_019_),
    .ZN(_053_)
  );
  NAND2_X1 _136_ (
    .A1(_000_),
    .A2(_011_),
    .ZN(_054_)
  );
  NAND3_X1 _137_ (
    .A1(_000_),
    .A2(_011_),
    .A3(_022_),
    .ZN(_055_)
  );
  AND4_X1 _138_ (
    .A1(_000_),
    .A2(_011_),
    .A3(_025_),
    .A4(_022_),
    .ZN(_056_)
  );
  NAND2_X1 _139_ (
    .A1(_026_),
    .A2(_056_),
    .ZN(_057_)
  );
  NAND3_X1 _140_ (
    .A1(_027_),
    .A2(_026_),
    .A3(_056_),
    .ZN(_058_)
  );
  AND4_X1 _141_ (
    .A1(_027_),
    .A2(_026_),
    .A3(_028_),
    .A4(_056_),
    .ZN(_059_)
  );
  AND2_X1 _142_ (
    .A1(_029_),
    .A2(_059_),
    .ZN(_060_)
  );
  AND4_X1 _143_ (
    .A1(_029_),
    .A2(_031_),
    .A3(_030_),
    .A4(_059_),
    .ZN(_061_)
  );
  AND3_X1 _144_ (
    .A1(_002_),
    .A2(_001_),
    .A3(_061_),
    .ZN(_062_)
  );
  NAND4_X1 _145_ (
    .A1(_002_),
    .A2(_001_),
    .A3(_003_),
    .A4(_061_),
    .ZN(_063_)
  );
  NOR2_X1 _146_ (
    .A1(_045_),
    .A2(_063_),
    .ZN(_064_)
  );
  XNOR2_X1 _147_ (
    .A(_004_),
    .B(_063_),
    .ZN(_075_)
  );
  XNOR2_X1 _148_ (
    .A(_046_),
    .B(_064_),
    .ZN(_076_)
  );
  NOR4_X1 _149_ (
    .A1(_045_),
    .A2(_046_),
    .A3(_047_),
    .A4(_063_),
    .ZN(_065_)
  );
  AOI21_X1 _150_ (
    .A(_006_),
    .B1(_064_),
    .B2(_005_),
    .ZN(_066_)
  );
  NOR2_X1 _151_ (
    .A1(_065_),
    .A2(_066_),
    .ZN(_077_)
  );
  XOR2_X1 _152_ (
    .A(_007_),
    .B(_065_),
    .Z(_078_)
  );
  AND3_X1 _153_ (
    .A1(_007_),
    .A2(_008_),
    .A3(_065_),
    .ZN(_067_)
  );
  AOI21_X1 _154_ (
    .A(_008_),
    .B1(_065_),
    .B2(_007_),
    .ZN(_068_)
  );
  NOR2_X1 _155_ (
    .A1(_067_),
    .A2(_068_),
    .ZN(_079_)
  );
  NAND4_X1 _156_ (
    .A1(_007_),
    .A2(_008_),
    .A3(_009_),
    .A4(_065_),
    .ZN(_069_)
  );
  XOR2_X1 _157_ (
    .A(_009_),
    .B(_067_),
    .Z(_080_)
  );
  NOR2_X1 _158_ (
    .A1(_048_),
    .A2(_069_),
    .ZN(_070_)
  );
  XNOR2_X1 _159_ (
    .A(_010_),
    .B(_069_),
    .ZN(_081_)
  );
  XNOR2_X1 _160_ (
    .A(_049_),
    .B(_070_),
    .ZN(_083_)
  );
  NOR4_X1 _161_ (
    .A1(_048_),
    .A2(_049_),
    .A3(_050_),
    .A4(_069_),
    .ZN(_032_)
  );
  AOI21_X1 _162_ (
    .A(_013_),
    .B1(_070_),
    .B2(_012_),
    .ZN(_033_)
  );
  NOR2_X1 _163_ (
    .A1(_032_),
    .A2(_033_),
    .ZN(_084_)
  );
  XOR2_X1 _164_ (
    .A(_014_),
    .B(_032_),
    .Z(_085_)
  );
  AND3_X1 _165_ (
    .A1(_014_),
    .A2(_015_),
    .A3(_032_),
    .ZN(_034_)
  );
  AOI21_X1 _166_ (
    .A(_015_),
    .B1(_032_),
    .B2(_014_),
    .ZN(_035_)
  );
  NOR2_X1 _167_ (
    .A1(_034_),
    .A2(_035_),
    .ZN(_086_)
  );
  NAND4_X1 _168_ (
    .A1(_014_),
    .A2(_015_),
    .A3(_016_),
    .A4(_032_),
    .ZN(_036_)
  );
  XOR2_X1 _169_ (
    .A(_016_),
    .B(_034_),
    .Z(_087_)
  );
  NOR2_X1 _170_ (
    .A1(_051_),
    .A2(_036_),
    .ZN(_037_)
  );
  XNOR2_X1 _171_ (
    .A(_017_),
    .B(_036_),
    .ZN(_088_)
  );
  XNOR2_X1 _172_ (
    .A(_052_),
    .B(_037_),
    .ZN(_089_)
  );
  NOR4_X1 _173_ (
    .A1(_051_),
    .A2(_052_),
    .A3(_053_),
    .A4(_036_),
    .ZN(_038_)
  );
  AOI21_X1 _174_ (
    .A(_019_),
    .B1(_037_),
    .B2(_018_),
    .ZN(_039_)
  );
  NOR2_X1 _175_ (
    .A1(_038_),
    .A2(_039_),
    .ZN(_090_)
  );
  NAND2_X1 _176_ (
    .A1(_020_),
    .A2(_038_),
    .ZN(_040_)
  );
  XOR2_X1 _177_ (
    .A(_020_),
    .B(_038_),
    .Z(_091_)
  );
  NAND3_X1 _178_ (
    .A1(_020_),
    .A2(_021_),
    .A3(_038_),
    .ZN(_041_)
  );
  XNOR2_X1 _179_ (
    .A(_021_),
    .B(_040_),
    .ZN(_092_)
  );
  NAND4_X1 _180_ (
    .A1(_020_),
    .A2(_021_),
    .A3(_023_),
    .A4(_038_),
    .ZN(_042_)
  );
  XNOR2_X1 _181_ (
    .A(_023_),
    .B(_041_),
    .ZN(_094_)
  );
  XNOR2_X1 _182_ (
    .A(_024_),
    .B(_042_),
    .ZN(_095_)
  );
  XOR2_X1 _183_ (
    .A(_000_),
    .B(_011_),
    .Z(_082_)
  );
  XNOR2_X1 _184_ (
    .A(_022_),
    .B(_054_),
    .ZN(_093_)
  );
  XNOR2_X1 _185_ (
    .A(_025_),
    .B(_055_),
    .ZN(_096_)
  );
  XOR2_X1 _186_ (
    .A(_026_),
    .B(_056_),
    .Z(_097_)
  );
  XNOR2_X1 _187_ (
    .A(_027_),
    .B(_057_),
    .ZN(_098_)
  );
  XNOR2_X1 _188_ (
    .A(_028_),
    .B(_058_),
    .ZN(_099_)
  );
  XOR2_X1 _189_ (
    .A(_029_),
    .B(_059_),
    .Z(_100_)
  );
  XOR2_X1 _190_ (
    .A(_030_),
    .B(_060_),
    .Z(_101_)
  );
  AOI21_X1 _191_ (
    .A(_031_),
    .B1(_030_),
    .B2(_060_),
    .ZN(_043_)
  );
  NOR2_X1 _192_ (
    .A1(_061_),
    .A2(_043_),
    .ZN(_102_)
  );
  XOR2_X1 _193_ (
    .A(_001_),
    .B(_061_),
    .Z(_072_)
  );
  AOI21_X1 _194_ (
    .A(_002_),
    .B1(_001_),
    .B2(_061_),
    .ZN(_044_)
  );
  NOR2_X1 _195_ (
    .A1(_062_),
    .A2(_044_),
    .ZN(_073_)
  );
  XOR2_X1 _196_ (
    .A(_003_),
    .B(_062_),
    .Z(_074_)
  );
  assign _103_[0] = a[0];
  assign _000_ = a[0];
  assign out[0] = _071_;
  assign _004_ = a[13];
  assign out[13] = _075_;
  assign _005_ = a[14];
  assign out[14] = _076_;
  assign _006_ = a[15];
  assign out[15] = _077_;
  assign _007_ = a[16];
  assign out[16] = _078_;
  assign _008_ = a[17];
  assign out[17] = _079_;
  assign _009_ = a[18];
  assign out[18] = _080_;
  assign _010_ = a[19];
  assign out[19] = _081_;
  assign _012_ = a[20];
  assign out[20] = _083_;
  assign _013_ = a[21];
  assign out[21] = _084_;
  assign _014_ = a[22];
  assign out[22] = _085_;
  assign _015_ = a[23];
  assign out[23] = _086_;
  assign _016_ = a[24];
  assign out[24] = _087_;
  assign _017_ = a[25];
  assign out[25] = _088_;
  assign _018_ = a[26];
  assign out[26] = _089_;
  assign _019_ = a[27];
  assign out[27] = _090_;
  assign _020_ = a[28];
  assign out[28] = _091_;
  assign _021_ = a[29];
  assign out[29] = _092_;
  assign _023_ = a[30];
  assign out[30] = _094_;
  assign _024_ = a[31];
  assign out[31] = _095_;
  assign _011_ = a[1];
  assign _025_ = a[3];
  assign _022_ = a[2];
  assign _027_ = a[5];
  assign _026_ = a[4];
  assign _029_ = a[7];
  assign _028_ = a[6];
  assign _031_ = a[9];
  assign _030_ = a[8];
  assign _002_ = a[11];
  assign _001_ = a[10];
  assign _003_ = a[12];
  assign out[1] = _082_;
  assign out[2] = _093_;
  assign out[3] = _096_;
  assign out[4] = _097_;
  assign out[5] = _098_;
  assign out[6] = _099_;
  assign out[7] = _100_;
  assign out[8] = _101_;
  assign out[9] = _102_;
  assign out[10] = _072_;
  assign out[11] = _073_;
  assign out[12] = _074_;
endmodule
