/* Generated by Yosys 0.30+38 (git sha1 596da3f2a, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\top" *)
(* top =  1  *)
(* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.1-7.10" *)
module top(a, b, enable, out);
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _000_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _001_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _002_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _003_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _004_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _005_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _006_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _007_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _008_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _009_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _010_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _011_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _012_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _013_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _014_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _015_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _016_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _017_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _018_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _019_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _020_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _021_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _022_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _023_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _024_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _025_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _026_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _027_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _028_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _029_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _030_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  wire _031_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _032_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _033_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _034_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _035_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _036_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _037_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _038_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _039_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _040_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _041_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _042_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _043_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _044_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _045_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _046_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _047_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _048_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _049_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _050_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _051_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _052_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _053_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _054_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _055_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _056_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _057_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _058_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _059_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _060_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _061_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _062_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  wire _063_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:3.22-3.28" *)
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _238_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _239_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _240_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _241_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _242_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _243_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _244_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _245_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _246_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _247_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _248_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _249_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _250_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _251_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _252_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _253_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _254_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _255_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _256_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _257_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _258_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _259_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _260_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _261_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _262_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _263_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _264_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _265_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _266_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _267_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _268_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  wire _269_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:279.21-279.23" *)
  wire [31:0] _270_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "31" *)
  wire [31:0] _271_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _272_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _273_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:214.23-214.24" *)
  (* unused_bits = "31" *)
  wire [31:0] _274_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _275_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _276_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _277_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _278_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _279_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _280_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _281_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _282_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _283_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _284_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _285_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _286_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _287_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _288_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _289_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _290_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _291_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _292_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _293_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _294_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _295_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _296_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _297_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _298_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _299_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.19-240.41" *)
  wire _300_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _301_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _302_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _303_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _304_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _305_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _306_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _307_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _308_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _309_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _310_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _311_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _312_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _313_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _314_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _315_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _316_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _317_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _318_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _319_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _320_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _321_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:241.12-241.34" *)
  wire _322_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _323_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _324_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _325_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _326_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _327_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _328_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _329_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _330_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _331_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _332_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _333_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _334_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _335_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _336_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _337_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _338_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _339_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _340_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _341_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _342_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _343_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _344_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _345_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _346_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _347_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:248.19-248.41" *)
  wire _348_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _349_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _350_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _351_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _352_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _353_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _354_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _355_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _356_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _357_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _358_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _359_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _360_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _361_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _362_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _363_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _364_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _365_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _366_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _367_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _368_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _369_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:6.26-6.31|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:286.27-286.69|/home/alice/yosis/oss-cad-suite/lib/../share/yosys/techmap.v:240.12-240.41" *)
  wire _370_;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:1.29-1.30" *)
  input [31:0] a;
  wire [31:0] a;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:2.29-2.30" *)
  input [31:0] b;
  wire [31:0] b;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:3.22-3.28" *)
  input enable;
  wire enable;
  (* src = "/home/alice/hal/plugins/module_identification-main/pattern_lib/subtraction_enable_32bit/subtraction_enable_32bit.v:4.30-4.33" *)
  output [31:0] out;
  wire [31:0] out;
  INV_X1 _371_ (
    .A(_064_),
    .ZN(_236_)
  );
  INV_X1 _372_ (
    .A(_032_),
    .ZN(_237_)
  );
  INV_X1 _373_ (
    .A(_043_),
    .ZN(_065_)
  );
  INV_X1 _374_ (
    .A(_054_),
    .ZN(_066_)
  );
  INV_X1 _375_ (
    .A(_057_),
    .ZN(_067_)
  );
  INV_X1 _376_ (
    .A(_059_),
    .ZN(_068_)
  );
  INV_X1 _377_ (
    .A(_061_),
    .ZN(_069_)
  );
  INV_X1 _378_ (
    .A(_063_),
    .ZN(_070_)
  );
  INV_X1 _379_ (
    .A(_034_),
    .ZN(_071_)
  );
  INV_X1 _380_ (
    .A(_036_),
    .ZN(_072_)
  );
  INV_X1 _381_ (
    .A(_038_),
    .ZN(_073_)
  );
  INV_X1 _382_ (
    .A(_040_),
    .ZN(_074_)
  );
  INV_X1 _383_ (
    .A(_042_),
    .ZN(_075_)
  );
  INV_X1 _384_ (
    .A(_045_),
    .ZN(_076_)
  );
  INV_X1 _385_ (
    .A(_047_),
    .ZN(_077_)
  );
  INV_X1 _386_ (
    .A(_049_),
    .ZN(_078_)
  );
  INV_X1 _387_ (
    .A(_051_),
    .ZN(_079_)
  );
  INV_X1 _388_ (
    .A(_052_),
    .ZN(_080_)
  );
  INV_X1 _389_ (
    .A(_053_),
    .ZN(_081_)
  );
  INV_X1 _390_ (
    .A(_026_),
    .ZN(_082_)
  );
  INV_X1 _391_ (
    .A(_028_),
    .ZN(_083_)
  );
  INV_X1 _392_ (
    .A(_030_),
    .ZN(_084_)
  );
  INV_X1 _393_ (
    .A(_001_),
    .ZN(_085_)
  );
  INV_X1 _394_ (
    .A(_003_),
    .ZN(_086_)
  );
  INV_X1 _395_ (
    .A(_005_),
    .ZN(_087_)
  );
  INV_X1 _396_ (
    .A(_007_),
    .ZN(_088_)
  );
  INV_X1 _397_ (
    .A(_009_),
    .ZN(_089_)
  );
  INV_X1 _398_ (
    .A(_012_),
    .ZN(_090_)
  );
  INV_X1 _399_ (
    .A(_014_),
    .ZN(_091_)
  );
  INV_X1 _400_ (
    .A(_016_),
    .ZN(_092_)
  );
  INV_X1 _401_ (
    .A(_018_),
    .ZN(_093_)
  );
  INV_X1 _402_ (
    .A(_023_),
    .ZN(_094_)
  );
  NAND2_X1 _403_ (
    .A1(_073_),
    .A2(_006_),
    .ZN(_095_)
  );
  NOR2_X1 _404_ (
    .A1(_037_),
    .A2(_087_),
    .ZN(_096_)
  );
  XOR2_X1 _405_ (
    .A(_037_),
    .B(_005_),
    .Z(_097_)
  );
  NAND2_X1 _406_ (
    .A1(_072_),
    .A2(_004_),
    .ZN(_098_)
  );
  NOR2_X1 _407_ (
    .A1(_035_),
    .A2(_086_),
    .ZN(_099_)
  );
  XOR2_X1 _408_ (
    .A(_035_),
    .B(_003_),
    .Z(_100_)
  );
  NAND2_X1 _409_ (
    .A1(_071_),
    .A2(_002_),
    .ZN(_101_)
  );
  NOR2_X1 _410_ (
    .A1(_033_),
    .A2(_085_),
    .ZN(_102_)
  );
  XOR2_X1 _411_ (
    .A(_033_),
    .B(_001_),
    .Z(_103_)
  );
  NAND2_X1 _412_ (
    .A1(_070_),
    .A2(_031_),
    .ZN(_104_)
  );
  NOR2_X1 _413_ (
    .A1(_062_),
    .A2(_084_),
    .ZN(_105_)
  );
  XOR2_X1 _414_ (
    .A(_062_),
    .B(_030_),
    .Z(_106_)
  );
  NAND2_X1 _415_ (
    .A1(_069_),
    .A2(_029_),
    .ZN(_107_)
  );
  NOR2_X1 _416_ (
    .A1(_060_),
    .A2(_083_),
    .ZN(_108_)
  );
  XOR2_X1 _417_ (
    .A(_060_),
    .B(_028_),
    .Z(_109_)
  );
  NAND2_X1 _418_ (
    .A1(_068_),
    .A2(_027_),
    .ZN(_110_)
  );
  NOR2_X1 _419_ (
    .A1(_058_),
    .A2(_082_),
    .ZN(_111_)
  );
  NAND2_X1 _420_ (
    .A1(_067_),
    .A2(_025_),
    .ZN(_112_)
  );
  NAND2_X1 _421_ (
    .A1(_066_),
    .A2(_022_),
    .ZN(_113_)
  );
  INV_X1 _422_ (
    .A(_113_),
    .ZN(_114_)
  );
  NAND2_X1 _423_ (
    .A1(_065_),
    .A2(_011_),
    .ZN(_115_)
  );
  XNOR2_X1 _424_ (
    .A(_043_),
    .B(_011_),
    .ZN(_116_)
  );
  OAI21_X1 _425_ (
    .A(_116_),
    .B1(_000_),
    .B2(_237_),
    .ZN(_117_)
  );
  XOR2_X1 _426_ (
    .A(_054_),
    .B(_022_),
    .Z(_118_)
  );
  AOI21_X1 _427_ (
    .A(_118_),
    .B1(_117_),
    .B2(_115_),
    .ZN(_119_)
  );
  XOR2_X1 _428_ (
    .A(_057_),
    .B(_025_),
    .Z(_120_)
  );
  INV_X1 _429_ (
    .A(_120_),
    .ZN(_121_)
  );
  OAI21_X1 _430_ (
    .A(_121_),
    .B1(_119_),
    .B2(_114_),
    .ZN(_122_)
  );
  XOR2_X1 _431_ (
    .A(_058_),
    .B(_026_),
    .Z(_123_)
  );
  AOI21_X1 _432_ (
    .A(_123_),
    .B1(_122_),
    .B2(_112_),
    .ZN(_124_)
  );
  XOR2_X1 _433_ (
    .A(_059_),
    .B(_027_),
    .Z(_125_)
  );
  INV_X1 _434_ (
    .A(_125_),
    .ZN(_126_)
  );
  OAI21_X1 _435_ (
    .A(_126_),
    .B1(_124_),
    .B2(_111_),
    .ZN(_127_)
  );
  AOI21_X1 _436_ (
    .A(_109_),
    .B1(_110_),
    .B2(_127_),
    .ZN(_128_)
  );
  NOR2_X1 _437_ (
    .A1(_108_),
    .A2(_128_),
    .ZN(_129_)
  );
  OAI22_X1 _438_ (
    .A1(_069_),
    .A2(_029_),
    .B1(_108_),
    .B2(_128_),
    .ZN(_130_)
  );
  AOI21_X1 _439_ (
    .A(_106_),
    .B1(_107_),
    .B2(_130_),
    .ZN(_131_)
  );
  NOR2_X1 _440_ (
    .A1(_105_),
    .A2(_131_),
    .ZN(_132_)
  );
  OAI22_X1 _441_ (
    .A1(_070_),
    .A2(_031_),
    .B1(_105_),
    .B2(_131_),
    .ZN(_133_)
  );
  AOI21_X1 _442_ (
    .A(_103_),
    .B1(_104_),
    .B2(_133_),
    .ZN(_134_)
  );
  NOR2_X1 _443_ (
    .A1(_102_),
    .A2(_134_),
    .ZN(_135_)
  );
  OAI22_X1 _444_ (
    .A1(_071_),
    .A2(_002_),
    .B1(_102_),
    .B2(_134_),
    .ZN(_136_)
  );
  AOI21_X1 _445_ (
    .A(_100_),
    .B1(_101_),
    .B2(_136_),
    .ZN(_137_)
  );
  NOR2_X1 _446_ (
    .A1(_099_),
    .A2(_137_),
    .ZN(_138_)
  );
  OAI22_X1 _447_ (
    .A1(_072_),
    .A2(_004_),
    .B1(_099_),
    .B2(_137_),
    .ZN(_139_)
  );
  AOI21_X1 _448_ (
    .A(_097_),
    .B1(_098_),
    .B2(_139_),
    .ZN(_140_)
  );
  NOR2_X1 _449_ (
    .A1(_096_),
    .A2(_140_),
    .ZN(_141_)
  );
  OAI22_X1 _450_ (
    .A1(_073_),
    .A2(_006_),
    .B1(_096_),
    .B2(_140_),
    .ZN(_142_)
  );
  NOR2_X1 _451_ (
    .A1(_039_),
    .A2(_088_),
    .ZN(_143_)
  );
  XOR2_X1 _452_ (
    .A(_039_),
    .B(_007_),
    .Z(_144_)
  );
  AOI21_X1 _453_ (
    .A(_144_),
    .B1(_142_),
    .B2(_095_),
    .ZN(_145_)
  );
  AND3_X1 _454_ (
    .A1(_095_),
    .A2(_142_),
    .A3(_144_),
    .ZN(_146_)
  );
  NOR3_X1 _455_ (
    .A1(_236_),
    .A2(_145_),
    .A3(_146_),
    .ZN(_245_)
  );
  NOR2_X1 _456_ (
    .A1(_143_),
    .A2(_145_),
    .ZN(_147_)
  );
  NAND2_X1 _457_ (
    .A1(_074_),
    .A2(_008_),
    .ZN(_148_)
  );
  XOR2_X1 _458_ (
    .A(_040_),
    .B(_008_),
    .Z(_149_)
  );
  XNOR2_X1 _459_ (
    .A(_147_),
    .B(_149_),
    .ZN(_150_)
  );
  NOR2_X1 _460_ (
    .A1(_236_),
    .A2(_150_),
    .ZN(_246_)
  );
  OAI22_X1 _461_ (
    .A1(_074_),
    .A2(_008_),
    .B1(_143_),
    .B2(_145_),
    .ZN(_151_)
  );
  NOR2_X1 _462_ (
    .A1(_041_),
    .A2(_089_),
    .ZN(_152_)
  );
  XOR2_X1 _463_ (
    .A(_041_),
    .B(_009_),
    .Z(_153_)
  );
  AOI21_X1 _464_ (
    .A(_153_),
    .B1(_151_),
    .B2(_148_),
    .ZN(_154_)
  );
  AND3_X1 _465_ (
    .A1(_148_),
    .A2(_151_),
    .A3(_153_),
    .ZN(_155_)
  );
  NOR3_X1 _466_ (
    .A1(_236_),
    .A2(_154_),
    .A3(_155_),
    .ZN(_247_)
  );
  NOR2_X1 _467_ (
    .A1(_152_),
    .A2(_154_),
    .ZN(_156_)
  );
  NAND2_X1 _468_ (
    .A1(_075_),
    .A2(_010_),
    .ZN(_157_)
  );
  XOR2_X1 _469_ (
    .A(_042_),
    .B(_010_),
    .Z(_158_)
  );
  XNOR2_X1 _470_ (
    .A(_156_),
    .B(_158_),
    .ZN(_159_)
  );
  NOR2_X1 _471_ (
    .A1(_236_),
    .A2(_159_),
    .ZN(_248_)
  );
  OAI22_X1 _472_ (
    .A1(_075_),
    .A2(_010_),
    .B1(_152_),
    .B2(_154_),
    .ZN(_160_)
  );
  NOR2_X1 _473_ (
    .A1(_044_),
    .A2(_090_),
    .ZN(_161_)
  );
  XOR2_X1 _474_ (
    .A(_044_),
    .B(_012_),
    .Z(_162_)
  );
  AOI21_X1 _475_ (
    .A(_162_),
    .B1(_160_),
    .B2(_157_),
    .ZN(_163_)
  );
  AND3_X1 _476_ (
    .A1(_157_),
    .A2(_160_),
    .A3(_162_),
    .ZN(_164_)
  );
  NOR3_X1 _477_ (
    .A1(_236_),
    .A2(_163_),
    .A3(_164_),
    .ZN(_250_)
  );
  NOR2_X1 _478_ (
    .A1(_161_),
    .A2(_163_),
    .ZN(_165_)
  );
  NAND2_X1 _479_ (
    .A1(_076_),
    .A2(_013_),
    .ZN(_166_)
  );
  XOR2_X1 _480_ (
    .A(_045_),
    .B(_013_),
    .Z(_167_)
  );
  XNOR2_X1 _481_ (
    .A(_165_),
    .B(_167_),
    .ZN(_168_)
  );
  NOR2_X1 _482_ (
    .A1(_236_),
    .A2(_168_),
    .ZN(_251_)
  );
  OAI22_X1 _483_ (
    .A1(_076_),
    .A2(_013_),
    .B1(_161_),
    .B2(_163_),
    .ZN(_169_)
  );
  NOR2_X1 _484_ (
    .A1(_046_),
    .A2(_091_),
    .ZN(_170_)
  );
  XOR2_X1 _485_ (
    .A(_046_),
    .B(_014_),
    .Z(_171_)
  );
  AOI21_X1 _486_ (
    .A(_171_),
    .B1(_169_),
    .B2(_166_),
    .ZN(_172_)
  );
  AND3_X1 _487_ (
    .A1(_166_),
    .A2(_169_),
    .A3(_171_),
    .ZN(_173_)
  );
  NOR3_X1 _488_ (
    .A1(_236_),
    .A2(_172_),
    .A3(_173_),
    .ZN(_252_)
  );
  NOR2_X1 _489_ (
    .A1(_170_),
    .A2(_172_),
    .ZN(_174_)
  );
  NAND2_X1 _490_ (
    .A1(_077_),
    .A2(_015_),
    .ZN(_175_)
  );
  XOR2_X1 _491_ (
    .A(_047_),
    .B(_015_),
    .Z(_176_)
  );
  XNOR2_X1 _492_ (
    .A(_174_),
    .B(_176_),
    .ZN(_177_)
  );
  NOR2_X1 _493_ (
    .A1(_236_),
    .A2(_177_),
    .ZN(_253_)
  );
  OAI22_X1 _494_ (
    .A1(_077_),
    .A2(_015_),
    .B1(_170_),
    .B2(_172_),
    .ZN(_178_)
  );
  NOR2_X1 _495_ (
    .A1(_048_),
    .A2(_092_),
    .ZN(_179_)
  );
  XOR2_X1 _496_ (
    .A(_048_),
    .B(_016_),
    .Z(_180_)
  );
  AOI21_X1 _497_ (
    .A(_180_),
    .B1(_178_),
    .B2(_175_),
    .ZN(_181_)
  );
  AND3_X1 _498_ (
    .A1(_175_),
    .A2(_178_),
    .A3(_180_),
    .ZN(_182_)
  );
  NOR3_X1 _499_ (
    .A1(_236_),
    .A2(_181_),
    .A3(_182_),
    .ZN(_254_)
  );
  NAND2_X1 _500_ (
    .A1(_078_),
    .A2(_017_),
    .ZN(_183_)
  );
  XOR2_X1 _501_ (
    .A(_049_),
    .B(_017_),
    .Z(_184_)
  );
  INV_X1 _502_ (
    .A(_184_),
    .ZN(_185_)
  );
  OAI21_X1 _503_ (
    .A(_185_),
    .B1(_181_),
    .B2(_179_),
    .ZN(_186_)
  );
  OR3_X1 _504_ (
    .A1(_179_),
    .A2(_181_),
    .A3(_185_),
    .ZN(_187_)
  );
  AND3_X1 _505_ (
    .A1(_064_),
    .A2(_186_),
    .A3(_187_),
    .ZN(_255_)
  );
  NOR2_X1 _506_ (
    .A1(_050_),
    .A2(_093_),
    .ZN(_188_)
  );
  XOR2_X1 _507_ (
    .A(_050_),
    .B(_018_),
    .Z(_189_)
  );
  AOI21_X1 _508_ (
    .A(_189_),
    .B1(_186_),
    .B2(_183_),
    .ZN(_190_)
  );
  AND3_X1 _509_ (
    .A1(_183_),
    .A2(_186_),
    .A3(_189_),
    .ZN(_191_)
  );
  NOR3_X1 _510_ (
    .A1(_236_),
    .A2(_190_),
    .A3(_191_),
    .ZN(_256_)
  );
  NOR2_X1 _511_ (
    .A1(_188_),
    .A2(_190_),
    .ZN(_192_)
  );
  NAND2_X1 _512_ (
    .A1(_079_),
    .A2(_019_),
    .ZN(_193_)
  );
  XOR2_X1 _513_ (
    .A(_051_),
    .B(_019_),
    .Z(_194_)
  );
  XNOR2_X1 _514_ (
    .A(_192_),
    .B(_194_),
    .ZN(_195_)
  );
  NOR2_X1 _515_ (
    .A1(_236_),
    .A2(_195_),
    .ZN(_257_)
  );
  OAI22_X1 _516_ (
    .A1(_079_),
    .A2(_019_),
    .B1(_188_),
    .B2(_190_),
    .ZN(_196_)
  );
  NAND2_X1 _517_ (
    .A1(_080_),
    .A2(_020_),
    .ZN(_197_)
  );
  INV_X1 _518_ (
    .A(_197_),
    .ZN(_198_)
  );
  XOR2_X1 _519_ (
    .A(_052_),
    .B(_020_),
    .Z(_199_)
  );
  AOI21_X1 _520_ (
    .A(_199_),
    .B1(_196_),
    .B2(_193_),
    .ZN(_200_)
  );
  AND3_X1 _521_ (
    .A1(_193_),
    .A2(_196_),
    .A3(_199_),
    .ZN(_201_)
  );
  NOR3_X1 _522_ (
    .A1(_236_),
    .A2(_200_),
    .A3(_201_),
    .ZN(_258_)
  );
  NAND2_X1 _523_ (
    .A1(_081_),
    .A2(_021_),
    .ZN(_202_)
  );
  XOR2_X1 _524_ (
    .A(_053_),
    .B(_021_),
    .Z(_203_)
  );
  INV_X1 _525_ (
    .A(_203_),
    .ZN(_204_)
  );
  OAI21_X1 _526_ (
    .A(_204_),
    .B1(_200_),
    .B2(_198_),
    .ZN(_205_)
  );
  OR3_X1 _527_ (
    .A1(_198_),
    .A2(_200_),
    .A3(_204_),
    .ZN(_206_)
  );
  AND3_X1 _528_ (
    .A1(_064_),
    .A2(_205_),
    .A3(_206_),
    .ZN(_259_)
  );
  NOR2_X1 _529_ (
    .A1(_055_),
    .A2(_094_),
    .ZN(_207_)
  );
  XOR2_X1 _530_ (
    .A(_055_),
    .B(_023_),
    .Z(_208_)
  );
  AOI21_X1 _531_ (
    .A(_208_),
    .B1(_205_),
    .B2(_202_),
    .ZN(_209_)
  );
  AND3_X1 _532_ (
    .A1(_202_),
    .A2(_205_),
    .A3(_208_),
    .ZN(_210_)
  );
  NOR3_X1 _533_ (
    .A1(_236_),
    .A2(_209_),
    .A3(_210_),
    .ZN(_261_)
  );
  XOR2_X1 _534_ (
    .A(_056_),
    .B(_024_),
    .Z(_211_)
  );
  OAI21_X1 _535_ (
    .A(_211_),
    .B1(_209_),
    .B2(_207_),
    .ZN(_212_)
  );
  OR3_X1 _536_ (
    .A1(_207_),
    .A2(_209_),
    .A3(_211_),
    .ZN(_213_)
  );
  AOI21_X1 _537_ (
    .A(_236_),
    .B1(_212_),
    .B2(_213_),
    .ZN(_262_)
  );
  XNOR2_X1 _538_ (
    .A(_032_),
    .B(_000_),
    .ZN(_214_)
  );
  NOR2_X1 _539_ (
    .A1(_236_),
    .A2(_214_),
    .ZN(_238_)
  );
  NOR3_X1 _540_ (
    .A1(_237_),
    .A2(_000_),
    .A3(_116_),
    .ZN(_215_)
  );
  NAND2_X1 _541_ (
    .A1(_064_),
    .A2(_117_),
    .ZN(_216_)
  );
  NOR2_X1 _542_ (
    .A1(_215_),
    .A2(_216_),
    .ZN(_249_)
  );
  AND3_X1 _543_ (
    .A1(_115_),
    .A2(_117_),
    .A3(_118_),
    .ZN(_217_)
  );
  NOR3_X1 _544_ (
    .A1(_236_),
    .A2(_119_),
    .A3(_217_),
    .ZN(_260_)
  );
  OR3_X1 _545_ (
    .A1(_114_),
    .A2(_119_),
    .A3(_121_),
    .ZN(_218_)
  );
  AND3_X1 _546_ (
    .A1(_064_),
    .A2(_122_),
    .A3(_218_),
    .ZN(_263_)
  );
  AND3_X1 _547_ (
    .A1(_112_),
    .A2(_122_),
    .A3(_123_),
    .ZN(_219_)
  );
  NOR3_X1 _548_ (
    .A1(_236_),
    .A2(_124_),
    .A3(_219_),
    .ZN(_264_)
  );
  OR3_X1 _549_ (
    .A1(_111_),
    .A2(_124_),
    .A3(_126_),
    .ZN(_220_)
  );
  AND3_X1 _550_ (
    .A1(_064_),
    .A2(_127_),
    .A3(_220_),
    .ZN(_265_)
  );
  AND3_X1 _551_ (
    .A1(_109_),
    .A2(_110_),
    .A3(_127_),
    .ZN(_221_)
  );
  NOR3_X1 _552_ (
    .A1(_236_),
    .A2(_128_),
    .A3(_221_),
    .ZN(_266_)
  );
  XOR2_X1 _553_ (
    .A(_061_),
    .B(_029_),
    .Z(_222_)
  );
  XNOR2_X1 _554_ (
    .A(_129_),
    .B(_222_),
    .ZN(_223_)
  );
  NOR2_X1 _555_ (
    .A1(_236_),
    .A2(_223_),
    .ZN(_267_)
  );
  AND3_X1 _556_ (
    .A1(_106_),
    .A2(_107_),
    .A3(_130_),
    .ZN(_224_)
  );
  NOR3_X1 _557_ (
    .A1(_236_),
    .A2(_131_),
    .A3(_224_),
    .ZN(_268_)
  );
  XOR2_X1 _558_ (
    .A(_063_),
    .B(_031_),
    .Z(_225_)
  );
  XNOR2_X1 _559_ (
    .A(_132_),
    .B(_225_),
    .ZN(_226_)
  );
  NOR2_X1 _560_ (
    .A1(_236_),
    .A2(_226_),
    .ZN(_269_)
  );
  AND3_X1 _561_ (
    .A1(_103_),
    .A2(_104_),
    .A3(_133_),
    .ZN(_227_)
  );
  NOR3_X1 _562_ (
    .A1(_236_),
    .A2(_134_),
    .A3(_227_),
    .ZN(_239_)
  );
  XOR2_X1 _563_ (
    .A(_034_),
    .B(_002_),
    .Z(_228_)
  );
  XNOR2_X1 _564_ (
    .A(_135_),
    .B(_228_),
    .ZN(_229_)
  );
  NOR2_X1 _565_ (
    .A1(_236_),
    .A2(_229_),
    .ZN(_240_)
  );
  AND3_X1 _566_ (
    .A1(_100_),
    .A2(_101_),
    .A3(_136_),
    .ZN(_230_)
  );
  NOR3_X1 _567_ (
    .A1(_236_),
    .A2(_137_),
    .A3(_230_),
    .ZN(_241_)
  );
  XOR2_X1 _568_ (
    .A(_036_),
    .B(_004_),
    .Z(_231_)
  );
  XNOR2_X1 _569_ (
    .A(_138_),
    .B(_231_),
    .ZN(_232_)
  );
  NOR2_X1 _570_ (
    .A1(_236_),
    .A2(_232_),
    .ZN(_242_)
  );
  AND3_X1 _571_ (
    .A1(_097_),
    .A2(_098_),
    .A3(_139_),
    .ZN(_233_)
  );
  NOR3_X1 _572_ (
    .A1(_236_),
    .A2(_140_),
    .A3(_233_),
    .ZN(_243_)
  );
  XOR2_X1 _573_ (
    .A(_038_),
    .B(_006_),
    .Z(_234_)
  );
  XNOR2_X1 _574_ (
    .A(_141_),
    .B(_234_),
    .ZN(_235_)
  );
  NOR2_X1 _575_ (
    .A1(_236_),
    .A2(_235_),
    .ZN(_244_)
  );
  assign _064_ = enable;
  assign out[16] = _245_;
  assign out[17] = _246_;
  assign out[18] = _247_;
  assign out[19] = _248_;
  assign out[20] = _250_;
  assign out[21] = _251_;
  assign out[22] = _252_;
  assign out[23] = _253_;
  assign out[24] = _254_;
  assign out[25] = _255_;
  assign out[26] = _256_;
  assign out[27] = _257_;
  assign out[28] = _258_;
  assign out[29] = _259_;
  assign out[30] = _261_;
  assign out[31] = _262_;
  assign out[0] = _238_;
  assign out[1] = _249_;
  assign out[2] = _260_;
  assign out[3] = _263_;
  assign out[4] = _264_;
  assign out[5] = _265_;
  assign out[6] = _266_;
  assign out[7] = _267_;
  assign out[8] = _268_;
  assign out[9] = _269_;
  assign out[10] = _239_;
  assign out[11] = _240_;
  assign out[12] = _241_;
  assign out[13] = _242_;
  assign out[14] = _243_;
  assign out[15] = _244_;
  assign _032_ = b[0];
  assign _043_ = b[1];
  assign _054_ = b[2];
  assign _057_ = b[3];
  assign _058_ = b[4];
  assign _059_ = b[5];
  assign _060_ = b[6];
  assign _061_ = b[7];
  assign _062_ = b[8];
  assign _063_ = b[9];
  assign _033_ = b[10];
  assign _034_ = b[11];
  assign _035_ = b[12];
  assign _036_ = b[13];
  assign _037_ = b[14];
  assign _038_ = b[15];
  assign _039_ = b[16];
  assign _040_ = b[17];
  assign _041_ = b[18];
  assign _042_ = b[19];
  assign _044_ = b[20];
  assign _045_ = b[21];
  assign _046_ = b[22];
  assign _047_ = b[23];
  assign _048_ = b[24];
  assign _049_ = b[25];
  assign _050_ = b[26];
  assign _051_ = b[27];
  assign _052_ = b[28];
  assign _053_ = b[29];
  assign _055_ = b[30];
  assign _056_ = b[31];
  assign _000_ = a[0];
  assign _011_ = a[1];
  assign _022_ = a[2];
  assign _025_ = a[3];
  assign _026_ = a[4];
  assign _027_ = a[5];
  assign _028_ = a[6];
  assign _029_ = a[7];
  assign _030_ = a[8];
  assign _031_ = a[9];
  assign _001_ = a[10];
  assign _002_ = a[11];
  assign _003_ = a[12];
  assign _004_ = a[13];
  assign _005_ = a[14];
  assign _006_ = a[15];
  assign _007_ = a[16];
  assign _008_ = a[17];
  assign _009_ = a[18];
  assign _010_ = a[19];
  assign _012_ = a[20];
  assign _013_ = a[21];
  assign _014_ = a[22];
  assign _015_ = a[23];
  assign _016_ = a[24];
  assign _017_ = a[25];
  assign _018_ = a[26];
  assign _019_ = a[27];
  assign _020_ = a[28];
  assign _021_ = a[29];
  assign _023_ = a[30];
  assign _024_ = a[31];
endmodule
