hal: program_arguments Class Reference
program_arguments Class Reference
HAL Core
#include <program_arguments.h>
Public Member Functions
program_arguments (int argc, const char **argv)
program_arguments ()
~program_arguments ()=default
void get_original_arguments (int *argc, const char ***argv)
std::vector< std::string > get_set_options () const
bool is_option_set (const std::string &flag) const
void set_option (const std::string &flag, const std::vector< std::string > &parameters)
bool set_option (const std::string &flag, const std::set< std::string > &equivalent_flags, const std::vector< std::string > &parameters)
std::string get_parameter (const std::string &flag) const
std::vector< std::string > get_parameters (const std::string &flag) const
Constructor & Destructor Documentation
program_arguments() [1/2]
program_arguments::program_arguments (int argc, const char ** argv)
Constructor. Stores the command line arguments internally.
Parameters
[out] argc - Pointer to number of arguments.
[out] argv - Pointer to array of arguments.
program_arguments() [2/2]
program_arguments::program_arguments ()
Constructor. Stores no command line arguments internally.
~program_arguments()
program_arguments::~program_arguments () default
Member Function Documentation
get_original_arguments()
void program_arguments::get_original_arguments (int * argc, const char *** argv)
Copies the original command line arguments into the parameters.
Parameters
[out] argc - Pointer to number of arguments.
[out] argv - Pointer to array of arguments.
Referenced by plugin_python_shell::exec().
get_set_options()
std::vector< std::string > program_arguments::get_set_options () const
Returns all flags which were used to set options in the parsed arguments or programatically in order of appearance.
Returns
All used flags to set options.
is_option_set()
bool program_arguments::is_option_set (const std::string & flag) const
Checks whether an option was set.
Any flag of the option works, even if one of the other flags was actually used to set the option.
Parameters
[in] flag - A flag of the option.
Returns
True, if the user entered a flag for this option.
Referenced by log_manager::handle_options(), netlist_factory::load_netlist(), hdl_parser_dispatcher::parse(), and hdl_writer_dispatcher::write().
set_option() [1/2]
void program_arguments::set_option (const std::string & flag, const std::vector< std::string > & parameters)
Programatically set an option via a single flag and supply parameters.
Parameters
[in] flag - A flag of the option.
[in] parameters - The parameters for this flag.
Referenced by program_options::parse().
set_option() [2/2]
bool program_arguments::set_option (const std::string & flag, const std::set< std::string > & equivalent_flags, const std::vector< std::string > & parameters)
Programatically set an option (specifying a set of equivalent flags) and supply parameters.
Parameters
[in] flag - A single flag which is actually set.
[in] equivalent_flags - All flags for the same option.
[in] parameters - The parameters for this flag.
Returns
True, if the flags were not found in multiple disjunct options already.
References core_utils::join(), and log_error.
get_parameter()
std::string program_arguments::get_parameter (const std::string & flag) const
Returns the parameter of the option.
If the option expects more than one parameter, use get_parameters().
If the user did not supply a parameter, the default value is returned.
Parameters
[in] flag - A flag of the option. If the option was entered with multiple flags, any of these works.
Returns
The parameter for the option.
References get_parameters().
Referenced by log_manager::handle_options(), netlist_factory::load_netlist(), hdl_parser_dispatcher::parse(), and hdl_writer_dispatcher::write().
get_parameters()
std::vector< std::string > program_arguments::get_parameters (const std::string & flag) const
Returns the parameters of the option.
If the option expects only one parameter, use the shorthand get_parameter().
If the user did not supply (all) parameters, the default values are returned in those places.
Parameters
[in] flag - A flag of the option. If the option was entered with multiple flags, any of these works.
Returns
The parameters for the option.
References log_error.
Referenced by get_parameter().
The documentation for this class was generated from the following files:
core/program_arguments.h
/home/runner/work/hal/hal/src/core/program_arguments.cpp