hal: netlist Class Reference
netlist Class Reference
Netlist
#include <netlist.h>
Public Member Functions
netlist (std::shared_ptr< gate_library > library)
~netlist ()
std::shared_ptr< netlist > get_shared ()
u32 get_id () const
void set_id (const u32 id)
hal::path get_input_filename () const
void set_input_filename (const hal::path &input_filename)
std::string get_design_name () const
void set_design_name (const std::string &design_name)
std::string get_device_name () const
void set_device_name (const std::string &device_name)
std::shared_ptr< gate_library > get_gate_library () const
u32 get_unique_module_id ()
std::shared_ptr< module > create_module (const u32 id, const std::string &name, std::shared_ptr< module > parent, const std::vector< std::shared_ptr< gate >> &gates={})
std::shared_ptr< module > create_module (const std::string &name, std::shared_ptr< module > parent, const std::vector< std::shared_ptr< gate >> &gates={})
bool delete_module (const std::shared_ptr< module > module)
std::shared_ptr< module > get_top_module ()
std::shared_ptr< module > get_module_by_id (u32 id) const
std::set< std::shared_ptr< module > > get_modules () const
bool is_module_in_netlist (const std::shared_ptr< module > module) const
u32 get_unique_gate_id ()
std::shared_ptr< gate > create_gate (const u32 id, std::shared_ptr< const gate_type > gt, const std::string &name="", float x=-1, float y=-1)
std::shared_ptr< gate > create_gate (std::shared_ptr< const gate_type > gt, const std::string &name="", float x=-1, float y=-1)
bool delete_gate (std::shared_ptr< gate > gate)
bool is_gate_in_netlist (const std::shared_ptr< gate > gate) const
std::shared_ptr< gate > get_gate_by_id (const u32 gate_id) const
std::set< std::shared_ptr< gate > > get_gates (const std::function< bool(const std::shared_ptr< gate > &)> &filter=nullptr) const
bool mark_vcc_gate (const std::shared_ptr< gate > gate)
bool mark_gnd_gate (const std::shared_ptr< gate > gate)
bool unmark_vcc_gate (const std::shared_ptr< gate > gate)
bool unmark_gnd_gate (const std::shared_ptr< gate > gate)
bool is_vcc_gate (const std::shared_ptr< gate > gate) const
bool is_gnd_gate (const std::shared_ptr< gate > gate) const
std::set< std::shared_ptr< gate > > get_vcc_gates () const
std::set< std::shared_ptr< gate > > get_gnd_gates () const
u32 get_unique_net_id ()
std::shared_ptr< net > create_net (const u32 id, const std::string &name="")
std::shared_ptr< net > create_net (const std::string &name="")
bool delete_net (std::shared_ptr< net > n)
bool is_net_in_netlist (std::shared_ptr< net > const n) const
std::shared_ptr< net > get_net_by_id (u32 id) const
std::unordered_set< std::shared_ptr< net > > get_nets (const std::function< bool(const std::shared_ptr< net > &)> &filter=nullptr) const
bool mark_global_input_net (std::shared_ptr< net > const net)
bool mark_global_output_net (std::shared_ptr< net > const net)
bool unmark_global_input_net (std::shared_ptr< net > const net)
bool unmark_global_output_net (std::shared_ptr< net > const net)
bool is_global_input_net (std::shared_ptr< net > const net) const
bool is_global_output_net (std::shared_ptr< net > const net) const
std::set< std::shared_ptr< net > > get_global_input_nets () const
std::set< std::shared_ptr< net > > get_global_output_nets () const
Friends
class netlist_internal_manager
Detailed Description
Netlist class containing information about the netlist including its gates, modules, and nets, as well as the underlying gate library.
Constructor & Destructor Documentation
netlist()
netlist::netlist (std::shared_ptr< gate_library > library) explicit
Constructs a new netlist for a specific gate library.
Use the netlist_factory to create instances!
Parameters
[in] library - Shared pointer to gate library.
References create_module(), and netlist_internal_manager.
~netlist()
netlist::~netlist ()
Member Function Documentation
get_shared()
std::shared_ptr< netlist > netlist::get_shared ()
Return shared_ptr for the current netlist object
Returns
The shared ptr to netlist
Referenced by net::get_netlist(), and module::get_netlist().
get_id()
u32 netlist::get_id () const
Get the netlist id.
If not changed via set_id(), the id is zero.
Returns
The netlist's id.
Referenced by PYBIND11_PLUGIN().
set_id()
void netlist::set_id (const u32 id)
Sets the netlist id to a new value.
Parameters
[in] id - The new netlist id.
References netlist_event_handler::id_changed, and netlist_event_handler::notify().
Referenced by PYBIND11_PLUGIN().
get_input_filename()
hal::path netlist::get_input_filename () const
Get the file name of the input design.
Returns
The input file's name.
Referenced by PYBIND11_PLUGIN().
set_input_filename()
void netlist::set_input_filename (const hal::path & input_filename)
Set the file name of the input design.
Parameters
[in] input_filename - File name of the design.
References netlist_event_handler::input_filename_changed, and netlist_event_handler::notify().
Referenced by PYBIND11_PLUGIN().
get_design_name()
std::string netlist::get_design_name () const
Get the design name,
Returns
The design name.
Referenced by PYBIND11_PLUGIN().
set_design_name()
void netlist::set_design_name (const std::string & design_name)
Set the design name
Parameters
[in] design_name - New design name.
References netlist_event_handler::design_name_changed, and netlist_event_handler::notify().
Referenced by PYBIND11_PLUGIN().
get_device_name()
std::string netlist::get_device_name () const
Get the name of the hardware device if specified.
Returns
The target device name.
Referenced by PYBIND11_PLUGIN().
set_device_name()
void netlist::set_device_name (const std::string & device_name)
Set the name of the target hardware device.
Parameters
[in] device_name - Name of hardware device
References netlist_event_handler::device_name_changed, and netlist_event_handler::notify().
Referenced by PYBIND11_PLUGIN().
get_gate_library()
std::shared_ptr< gate_library > netlist::get_gate_library () const
Get the gate library associated with the netlist.
Returns
A pointer to the gate library.
Referenced by PYBIND11_PLUGIN().
get_unique_module_id()
u32 netlist::get_unique_module_id ()
Gets an unoccupied module id.
The value 0 is reserved and represents an invalid id.
Returns
An unoccupied unique id.
Referenced by create_module(), and PYBIND11_PLUGIN().
create_module() [1/2]
std::shared_ptr< module > netlist::create_module (const u32 id, const std::string & name, std::shared_ptr< module > parent, const std::vector< std::shared_ptr< gate >> & gates = {})
Creates and adds a new module to the netlist.
It is identifiable via its unique ID.
Parameters
[in] id - The unique ID != 0 for the new module.
[in] name - A name for the module.
[in] parent - The parent module.
[in] gates - Gates to assign to the new gate.
Returns
The new module on success, nullptr on error.
Referenced by create_module(), netlist(), and PYBIND11_PLUGIN().
create_module() [2/2]
std::shared_ptr< module > netlist::create_module (const std::string & name, std::shared_ptr< module > parent, const std::vector< std::shared_ptr< gate >> & gates = {})
Creates and adds a new module to the netlist.
It is identifiable via its unique ID which is automatically set to the next free ID.
Parameters
[in] name - A name for the module.
[in] parent - The parent module.
[in] gates - Gates to assign to the new gate.
Returns
The new module on success, nullptr on error.
References create_module(), and get_unique_module_id().
delete_module()
bool netlist::delete_module (const std::shared_ptr< module > module)
Removes and a module from the netlist.
Parameters
[in] module - module to remove.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
get_top_module()
std::shared_ptr< module > netlist::get_top_module ()
Get the top module of the netlist.
Returns
The top module.
Referenced by PYBIND11_PLUGIN().
get_module_by_id()
std::shared_ptr< module > netlist::get_module_by_id (u32 id) const
Get a module by its ID.
It does not matter at which depth the module is located.
Parameters
[in] id - the id of the desired module
Returns
The desired module.
References log_error.
Referenced by PYBIND11_PLUGIN().
get_modules()
std::set< std::shared_ptr< module > > netlist::get_modules () const
Get a set of all modules of the netlist including the top module.
Returns
The modules of the netlist.
Referenced by PYBIND11_PLUGIN().
is_module_in_netlist()
bool netlist::is_module_in_netlist (const std::shared_ptr< module > module) const
Checks whether a module is registered in the netlist.
Parameters
[in] module - The module to check.
Returns
True if the module is in netlist
Referenced by PYBIND11_PLUGIN().
get_unique_gate_id()
u32 netlist::get_unique_gate_id ()
Gets an unoccupied gate id.
The value 0 is reserved and represents an invalid id.
Returns
An unoccupied unique id.
Referenced by create_gate(), and PYBIND11_PLUGIN().
create_gate() [1/2]
std::shared_ptr< gate > netlist::create_gate (const u32 id, std::shared_ptr< const gate_type > gt, const std::string & name = "", float x = -1, float y = -1)
Creates and adds a new gate to the netlist.
It is identifiable via its unique ID.
Parameters
[in] id - The unique ID != 0 for the new gate.
[in] gt - The gate type.
[in] name - A name for the gate.
[in] x - The x-coordinate of the gate.
[in] y - The y-coordinate of the gate.
Returns
The new gate on success, nullptr on error.
Referenced by create_gate(), and PYBIND11_PLUGIN().
create_gate() [2/2]
std::shared_ptr< gate > netlist::create_gate (std::shared_ptr< const gate_type > gt, const std::string & name = "", float x = -1, float y = -1)
Creates and adds a new gate to the netlist.
It is identifiable via its unique ID which is automatically set to the next free ID.
Parameters
[in] gt - The gate type.
[in] name - A name for the gate.
[in] x - The x-coordinate of the gate.
[in] y - The y-coordinate of the gate.
Returns
The new gate on success, nullptr on error.
References create_gate(), and get_unique_gate_id().
delete_gate()
bool netlist::delete_gate (std::shared_ptr< gate > gate)
Removes a gate from the netlist.
Parameters
[in] gate - Pointer to the gate pointer.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
is_gate_in_netlist()
bool netlist::is_gate_in_netlist (const std::shared_ptr< gate > gate) const
Checks whether a gate is registered in the netlist.
Parameters
[in] gate - The gate to check.
Returns
True if the gate is in netlist
Referenced by mark_gnd_gate(), mark_vcc_gate(), PYBIND11_PLUGIN(), unmark_gnd_gate(), and unmark_vcc_gate().
get_gate_by_id()
std::shared_ptr< gate > netlist::get_gate_by_id (const u32 gate_id) const
Get a gate specified by id.
Parameters
[in] gate_id - The gate's id.
Returns
The gate or a nullptr.
Referenced by PYBIND11_PLUGIN().
get_gates()
std::set< std::shared_ptr< gate > > netlist::get_gates (const std::function< bool(const std::shared_ptr< gate > &)> & filter = nullptr) const
Get all gates of the netlist regardless of the module they are in.
You can filter the set before output with the optional parameters.
Parameters
[in] filter - Filter for the gates
Returns
A set of gates.
Referenced by PYBIND11_PLUGIN().
mark_vcc_gate()
bool netlist::mark_vcc_gate (const std::shared_ptr< gate > gate)
Mark a gate as a global vcc gate.
Parameters
[in] gate - The gate.
Returns
True on success.
References is_gate_in_netlist(), log_debug, netlist_event_handler::marked_global_vcc, and netlist_event_handler::notify().
Referenced by PYBIND11_PLUGIN().
mark_gnd_gate()
bool netlist::mark_gnd_gate (const std::shared_ptr< gate > gate)
Mark a gate as a global gnd gate.
Parameters
[in] gate - The negate.
Returns
True on success.
References is_gate_in_netlist(), log_debug, netlist_event_handler::marked_global_gnd, and netlist_event_handler::notify().
Referenced by PYBIND11_PLUGIN().
unmark_vcc_gate()
bool netlist::unmark_vcc_gate (const std::shared_ptr< gate > gate)
Unmark a global vcc gate.
Parameters
[in] gate - The gate.
Returns
True on success.
References is_gate_in_netlist(), log_debug, netlist_event_handler::notify(), and netlist_event_handler::unmarked_global_vcc.
Referenced by PYBIND11_PLUGIN().
unmark_gnd_gate()
bool netlist::unmark_gnd_gate (const std::shared_ptr< gate > gate)
Unmark a global gate.
Parameters
[in] gate - The new gate.
Returns
True on success.
References is_gate_in_netlist(), log_debug, netlist_event_handler::notify(), and netlist_event_handler::unmarked_global_gnd.
Referenced by PYBIND11_PLUGIN().
is_vcc_gate()
bool netlist::is_vcc_gate (const std::shared_ptr< gate > gate) const
Checks whether a gate is a global vcc gate.
Parameters
[in] gate - The gate to check.
Returns
True if the gate is a global vcc gate.
Referenced by PYBIND11_PLUGIN().
is_gnd_gate()
bool netlist::is_gnd_gate (const std::shared_ptr< gate > gate) const
Checks whether a gate is a global gnd gate.
Parameters
[in] gate - The gate to check.
Returns
True if the gate is a global gnd gate.
Referenced by PYBIND11_PLUGIN().
get_vcc_gates()
std::set< std::shared_ptr< gate > > netlist::get_vcc_gates () const
Get all global vcc gates.
Returns
A set of gates.
Referenced by PYBIND11_PLUGIN().
get_gnd_gates()
std::set< std::shared_ptr< gate > > netlist::get_gnd_gates () const
Get all global gnd gates.
Returns
A set of gates.
Referenced by PYBIND11_PLUGIN().
get_unique_net_id()
u32 netlist::get_unique_net_id ()
Gets an unoccupied net id.
The value 0 is reserved and represents an invalid id.
Returns
An unoccupied unique id.
Referenced by create_net(), and PYBIND11_PLUGIN().
create_net() [1/2]
std::shared_ptr< net > netlist::create_net (const u32 id, const std::string & name = "")
Creates and adds a new net to the netlist.
It is identifiable via its unique ID.
Parameters
[in] id - The unique ID != 0 for the new net.
[in] name - A name for the net.
Returns
The new net on success, nullptr on error.
Referenced by PYBIND11_PLUGIN().
create_net() [2/2]
std::shared_ptr< net > netlist::create_net (const std::string & name = "")
Creates and adds a new net to the netlist.
It is identifiable via its unique ID which is automatically set to the next free ID.
Parameters
[in] name - A name for the net.
Returns
The new net on success, nullptr on error.
References get_unique_net_id().
delete_net()
bool netlist::delete_net (std::shared_ptr< net > n)
Removes a net from the netlist.
Parameters
[in] n - Pointer to the net pointer.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
is_net_in_netlist()
bool netlist::is_net_in_netlist (std::shared_ptr< net > const n) const
Checks whether a net is registered in the netlist.
Parameters
[in] n - The net to check.
Returns
True if the net is in netlist
Referenced by mark_global_input_net(), mark_global_output_net(), PYBIND11_PLUGIN(), unmark_global_input_net(), and unmark_global_output_net().
get_net_by_id()
std::shared_ptr< net > netlist::get_net_by_id (u32 id) const
Get a net specified by id.
Parameters
[in] id - The net's id.
Returns
The net or a nullptr.
References log_error.
Referenced by PYBIND11_PLUGIN().
get_nets()
std::unordered_set< std::shared_ptr< net > > netlist::get_nets (const std::function< bool(const std::shared_ptr< net > &)> & filter = nullptr) const
Get all nets of the netlist regardless of the module they are in.
You can filter the set before output with the optional parameter.
Parameters
[in] filter - Filter for the nets
Returns
A set of nets.
Referenced by PYBIND11_PLUGIN().
mark_global_input_net()
bool netlist::mark_global_input_net (std::shared_ptr< net > const net)
Mark a net as a global input net.
Parameters
[in] net - The net.
Returns
True on success.
References is_net_in_netlist(), log_debug, log_error, netlist_event_handler::marked_global_input, and netlist_event_handler::notify().
Referenced by net::mark_global_input_net(), and PYBIND11_PLUGIN().
mark_global_output_net()
bool netlist::mark_global_output_net (std::shared_ptr< net > const net)
Mark a net as a global output net.
Parameters
[in] net - The net.
Returns
True on success.
References is_net_in_netlist(), log_debug, netlist_event_handler::marked_global_output, and netlist_event_handler::notify().
Referenced by net::mark_global_output_net(), and PYBIND11_PLUGIN().
unmark_global_input_net()
bool netlist::unmark_global_input_net (std::shared_ptr< net > const net)
Unmark a global input net.
Parameters
[in] net - The net.
Returns
True on success.
References is_net_in_netlist(), log_debug, netlist_event_handler::notify(), and netlist_event_handler::unmarked_global_input.
Referenced by PYBIND11_PLUGIN(), and net::unmark_global_input_net().
unmark_global_output_net()
bool netlist::unmark_global_output_net (std::shared_ptr< net > const net)
Unmark a global output net.
Parameters
[in] net - The net.
Returns
True on success.
References is_net_in_netlist(), log_debug, netlist_event_handler::notify(), and netlist_event_handler::unmarked_global_output.
Referenced by PYBIND11_PLUGIN(), and net::unmark_global_output_net().
is_global_input_net()
bool netlist::is_global_input_net (std::shared_ptr< net > const net) const
Checks whether a net is a global input net.
Parameters
[in] net - The net to check.
Returns
True if the net is a global input net.
Referenced by module::get_input_nets(), net::is_global_input_net(), and PYBIND11_PLUGIN().
is_global_output_net()
bool netlist::is_global_output_net (std::shared_ptr< net > const net) const
Checks whether a net is a global output net.
Parameters
[in] net - The net to check.
Returns
True if the net is a global output net.
Referenced by module::get_output_nets(), net::is_global_output_net(), and PYBIND11_PLUGIN().
get_global_input_nets()
std::set< std::shared_ptr< net > > netlist::get_global_input_nets () const
Get all global input nets.
Returns
A set of nets.
Referenced by PYBIND11_PLUGIN().
get_global_output_nets()
std::set< std::shared_ptr< net > > netlist::get_global_output_nets () const
Get all global output nets.
Returns
A set of nets.
Referenced by PYBIND11_PLUGIN().
Friends And Related Function Documentation
netlist_internal_manager
friend class netlist_internal_manager friend
Referenced by netlist().
The documentation for this class was generated from the following files:
netlist/netlist.h
/home/runner/work/hal/hal/src/netlist/netlist.cpp