hal: hal::HDLParserDispatcher Namespace Reference
hal::HDLParserDispatcher Namespace Reference
HDL Interfaces » HDL Parsers
Functions
ProgramOptions get_cli_options ()
std::set< std::string > get_gui_option ()
std::shared_ptr< Netlist > parse (const std::filesystem::path &file_name, const ProgramArguments &args)
std::shared_ptr< Netlist > parse (const std::shared_ptr< GateLibrary > &gate_library, const std::string &parser_name, const std::filesystem::path &file_name)
Function Documentation
get_cli_options()
ProgramOptions hal::HDLParserDispatcher::get_cli_options ()
Returns the command line interface options of the hdl parser dispatcher
Returns
The options.
References hal::ProgramOptions::add(), and hal::ProgramOptions::REQUIRED_PARAM.
get_gui_option()
std::set< std::string > hal::HDLParserDispatcher::get_gui_option ()
Returns the command language options for the parse() function.
Returns
The language options.
parse() [1/2]
std::shared_ptr< Netlist > hal::HDLParserDispatcher::parse (const std::filesystem::path & file_name, const ProgramArguments & args)
Returns the netlist for the file and specified command line options.
Parameters
[in] file_name - The input file.
[in] args - The command line options.
Returns
The netlist representation of the hdl code or a nullpointer on error.
References hal::gate_library_manager::get_gate_libraries(), hal::gate_library_manager::get_gate_library(), hal::ProgramArguments::get_parameter(), hal::ProgramArguments::is_option_set(), hal::gate_library_manager::load_all(), log_error, log_info, log_warning, and hal::core_utils::to_lower().
Referenced by hal::netlist_factory::load_netlist(), and hal::HDLParser< core_strings::CaseInsensitiveString >::parse_and_instantiate().
parse() [2/2]
std::shared_ptr< Netlist > hal::HDLParserDispatcher::parse (const std::shared_ptr< GateLibrary > & gate_library, const std::string & parser_name, const std::filesystem::path & file_name)
Returns the netlist for a file, parsed with a defined parser_name and gate library.
Parameters
[in] gate_library - The gate library used in the file.
[in] parser_name - The name of the parser to use, e.g. vhdl, verilog...
[in] file_name - The input file.
Returns
The netlist representation of the hdl code or a nullpointer on error.
References log_error.