hal: hal::net_event_handler Namespace Reference
hal::net_event_handler Namespace Reference
Enumerations
enum event {
created, removed, name_changed, src_added,
src_removed, dst_added, dst_removed
}
Functions
NETLIST_API void enable (bool flag)
NETLIST_API void notify (event ev, std::shared_ptr< Net > net, u32 associated_data=0xFFFFFFFF)
NETLIST_API void register_callback (const std::string &name, std::function< void(event e, std::shared_ptr< Net >, u32 associated_data)> function)
NETLIST_API void unregister_callback (const std::string &name)
void register_callback (const std::string &name, std::function< void(event, std::shared_ptr< Net >, u32)> function)
Enumeration Type Documentation
event
enum hal::net_event_handler::event
Enumerator
created
no associated_data
removed
no associated_data
name_changed
no associated_data
src_added
associated_data = id of src gate
src_removed
associated_data = id of src gate
dst_added
associated_data = id of dst gate
dst_removed
associated_data = id of dst gate
Function Documentation
enable()
void hal::net_event_handler::enable (bool flag)
Enables/disables callbacks for this handler.
Enabled by default.
Parameters
[in] flag - True to enable, false to disable.
Referenced by hal::event_controls::enable_all().
notify()
void hal::net_event_handler::notify (event ev, std::shared_ptr< Net > net, u32 associated_data = 0xFFFFFFFF)
Executes all registered callbacks.
Parameters
[in] ev - the event which occured.
[in] net - The affected object.
[in] associated_data - may have a meaning depending on the event type.
Referenced by hal::Net::set_name().
register_callback() [1/2]
NETLIST_API void hal::net_event_handler::register_callback (const std::string & name, std::function< void(event e, std::shared_ptr< Net >, u32 associated_data)> function)
Registers a callback function.
Parameters
[in] name - name of the callback, used for callback removal.
[in] function - The callback function.
Referenced by hal::event_log::initialize().
unregister_callback()
void hal::net_event_handler::unregister_callback (const std::string & name)
Removes a callback function.
Parameters
[in] name - name of the callback.
register_callback() [2/2]
void hal::net_event_handler::register_callback (const std::string & name, std::function< void(event, std::shared_ptr< Net >, u32)> function)