#pragma once

#include <string>

namespace hal
{
    const std::string get_yosys_helper_lib()
    {
        std::string yosys_helper_lib = "";
        yosys_helper_lib += "// GND\n";
        yosys_helper_lib += "module GND (G);\n";
        yosys_helper_lib += "output G;\n";
        yosys_helper_lib += "assign G = 1\'b0;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// VCC\n";
        yosys_helper_lib += "module VCC (P);\n";
        yosys_helper_lib += "output P;\n";
        yosys_helper_lib += "assign P = 1\'b1;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// BUF\n";
        yosys_helper_lib += "module HAL_BUF (A, O);\n";
        yosys_helper_lib += "input A;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// INV\n";
        yosys_helper_lib += "module HAL_INV (A, O);\n";
        yosys_helper_lib += "input A;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = ~A;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// AND2\n";
        yosys_helper_lib += "module HAL_AND2 (A, B, O);\n";
        yosys_helper_lib += "input A, B;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A & B;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// AND3\n";
        yosys_helper_lib += "module HAL_AND3 (A, B, C, O);\n";
        yosys_helper_lib += "input A, B, C;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A & B & C;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// AND4\n";
        yosys_helper_lib += "module HAL_AND4 (A, B, C, D, O);\n";
        yosys_helper_lib += "input A, B, C, D;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A & B & C & D;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// OR2\n";
        yosys_helper_lib += "module HAL_OR2 (A, B, O);\n";
        yosys_helper_lib += "input A, B;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A | B;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// OR3\n";
        yosys_helper_lib += "module HAL_OR3 (A, B, C, O);\n";
        yosys_helper_lib += "input A, B, C;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A | B | C;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// OR4\n";
        yosys_helper_lib += "module HAL_OR4 (A, B, C, D, O);\n";
        yosys_helper_lib += "input A, B, C, D;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A | B | C | D;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// XOR2\n";
        yosys_helper_lib += "module HAL_XOR2 (A, B, O);\n";
        yosys_helper_lib += "input A, B;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A ^ B;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// XOR3\n";
        yosys_helper_lib += "module HAL_XOR3 (A, B, C, O);\n";
        yosys_helper_lib += "input A, B, C;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A ^ B ^ C;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// XOR4\n";
        yosys_helper_lib += "module HAL_XOR4 (A, B, C, D, O);\n";
        yosys_helper_lib += "input A, B, C, D;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = A ^ B ^ C ^ D;\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// XNOR2\n";
        yosys_helper_lib += "module HAL_XNOR2 (A, B, O);\n";
        yosys_helper_lib += "input A, B;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = (! (A ^ B));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// XNOR3\n";
        yosys_helper_lib += "module HAL_XNOR3 (A, B, C, O);\n";
        yosys_helper_lib += "input A, B, C;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O =(! (A ^ (B ^ C)));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "// XNOR4\n";
        yosys_helper_lib += "module HAL_XNOR4 (A, B, C, D, O);\n";
        yosys_helper_lib += "input A, B, C, D;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = (! (A ^ (B ^ (C ^ D))));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "module HAL_MUX (A, B, S, O);\n";
        yosys_helper_lib += "input A, B, S;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = ((A & S) | (B & (! S)));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "module HAL_MUX3 (A, B, C, S1, S2, O);\n";
        yosys_helper_lib += "input A, B, C, S1, S2;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = ((A & S1) | (!S1 & ((B & S2) | (C & !S2))));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "module HAL_MUX4 (A, B, C, D, S1, S2, O);\n";
        yosys_helper_lib += "input A, B, C, D, S1, S2;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = ((A & S1 & S2) | (B & S1 & !S2) | (C & !S1 & S2) | (D & !S1 & !S2));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "module HAL_MUX5 (A, B, C, D, E, S1, S2, S3, O);\n";
        yosys_helper_lib += "input A, B, C, D, E, S1, S2, S3;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = ((~S1 & ~S2 & ~S3 & A) | (S1 & ~S2 & ~S3 & B) | (~S1 & S2 & ~S3 & C) | (~S1 & ~S2 & S3 & D) | (S1 & S2 & ~S3 & E));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "module HAL_MUX6 (A, B, C, D, E, F, S1, S2, S3, O);\n";
        yosys_helper_lib += "input A, B, C, D, E, F, S1, S2, S3;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = ((~S1 & ~S2 & ~S3 & A) | (S1 & ~S2 & ~S3 & B) | (~S1 & S2 & ~S3 & C) | (~S1 & ~S2 & S3 & D) | (S1 & S2 & ~S3 & E) | (S1 & ~S2 & S3 & F));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "module HAL_MUX7 (A, B, C, D, E, F, G, S1, S2, S3, O);\n";
        yosys_helper_lib += "input A, B, C, D, E, F, G, S1, S2, S3;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib +=
            "assign O = ((~S1 & ~S2 & ~S3 & A) | (S1 & ~S2 & ~S3 & B) | (~S1 & S2 & ~S3 & C) | (~S1 & ~S2 & S3 & D) | (S1 & S2 & ~S3 & E) | (S1 & ~S2 & S3 & F) | (S1 & S2 & S3 & G));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";
        yosys_helper_lib += "module HAL_MUX8 (A, B, C, D, E, F, G, H, S1, S2, S3, O);\n";
        yosys_helper_lib += "input A, B, C, D, E, F, G, H, S1, S2, S3;\n";
        yosys_helper_lib += "output O;\n";
        yosys_helper_lib += "assign O = ((~S1 & ~S2 & ~S3 & A) | (S1 & ~S2 & ~S3 & B) | (~S1 & S2 & ~S3 & C) | (~S1 & ~S2 & S3 & D) | (S1 & S2 & ~S3 & E) | (S1 & ~S2 & S3 & F) | (S1 & S2 & S3 & G) | "
                            "(H & S1 & S2 & S3));\n";
        yosys_helper_lib += "endmodule\n";
        yosys_helper_lib += "\n";

        return yosys_helper_lib;
    }
}    // namespace hal