hal: core_utils Namespace Reference
core_utils Namespace Reference
HAL Core
Classes
class directory_range
class recursive_directory_range
Functions
CORE_API bool ends_with (const std::string &s, const std::string &ending, bool ignore_case=false)
CORE_API bool starts_with (const std::string &s, const std::string &start, bool ignore_case=false)
CORE_API bool equals_ignore_case (const std::string &a, const std::string &b)
CORE_API bool is_integer (const std::string &s)
CORE_API bool is_floating_point (const std::string &s)
CORE_API std::vector< std::string > split (const std::string &s, const char delim, bool obey_brackets=false)
CORE_API std::string ltrim (const std::string &s, const char *to_remove=" \\)
CORE_API std::string rtrim (const std::string &s, const char *to_remove=" \\)
CORE_API std::string trim (const std::string &s, const char *to_remove=" \\)
CORE_API std::string replace (const std::string &str, const std::string &search, const std::string &replace)
template<typename T >
CORE_API std::string join (const std::string &joiner, const T &items)
CORE_API std::string to_upper (const std::string &s)
CORE_API std::string to_lower (const std::string &s)
CORE_API u32 num_of_occurrences (const std::string &str, const std::string &substr)
CORE_API bool file_exists (const std::string &filename)
CORE_API bool folder_exists_and_is_accessible (const hal::path &folder)
CORE_API hal::path which (const std::string &name, const std::string &path="")
CORE_API hal::path get_binary_directory ()
CORE_API hal::path get_base_directory ()
CORE_API hal::path get_library_directory ()
CORE_API hal::path get_share_directory ()
CORE_API hal::path get_user_share_directory ()
CORE_API hal::path get_config_directory ()
CORE_API hal::path get_user_config_directory ()
CORE_API hal::path get_default_log_directory (hal::path source_file="")
CORE_API std::vector< hal::path > get_gate_library_directories ()
CORE_API std::vector< hal::path > get_plugin_directories ()
CORE_API hal::path get_first_directory_exists (std::vector< hal::path > path_hints)
CORE_API hal::path get_file (std::string file_name, std::vector< hal::path > path_hints)
CORE_API std::string get_open_source_licenses ()
Function Documentation
ends_with()
bool core_utils::ends_with (const std::string & s, const std::string & ending, bool ignore_case = false)
Checks whether a string ends with another string.
Parameters
[in] s - The string to analyze.
[in] ending - The ending to check for.
[in] ignore_case - If true, ignores case while comparing.
Returns
True, if s ends with ending.
Referenced by hdl_parser_verilog::parse().
starts_with()
bool core_utils::starts_with (const std::string & s, const std::string & start, bool ignore_case = false)
Checks whether a string begins with another string.
Parameters
[in] s - The string to analyze.
[in] start - The beginning to check for.
[in] ignore_case - If true, ignores case while comparing.
Returns
True, if s begins with start.
Referenced by boolean_function::from_string(), and hdl_parser_verilog::parse().
equals_ignore_case()
bool core_utils::equals_ignore_case (const std::string & a, const std::string & b)
Checks whether two strings are equal while being case insensitive.
Parameters
[in] a - The first string to analyze.
[in] b - The second string to analyze.
Returns
True, if lowercase(a) == lowercase(b).
Referenced by token_stream::find_next(), and token::operator==().
is_integer()
bool core_utils::is_integer (const std::string & s)
Checks whether a string represents an integer.
Parameters
[in] s - The string to analyze.
Returns
True, if s contains an integer.
Referenced by hdl_parser_verilog::parse().
is_floating_point()
bool core_utils::is_floating_point (const std::string & s)
Checks whether a string represents a real number.
Parameters
[in] s - The string to analyze.
Returns
True, if s contains a real number.
Referenced by hdl_parser_verilog::parse().
split()
std::vector< std::string > core_utils::split (const std::string & s, const char delim, bool obey_brackets = false)
Splits a string into a vector of strings. The split delimiter can be specified. The delimiters are removed in the splitting process.
Parameters
[in] s - The string to split.
[in] delim - The delimiter, indicating where to split.
[in] obey_brackets - Flag to indicate whether brackets are obeyed.
Returns
The string parts.
Referenced by which().
ltrim()
std::string core_utils::ltrim (const std::string & s, const char * to_remove = " \t\r\n")
Removes any whitespace characters from the beginning of a string.
Parameters
[in] s - The string to trim.
[in] to_remove - All chars that should be removed.
Returns
The trimmed string.
rtrim()
std::string core_utils::rtrim (const std::string & s, const char * to_remove = " \t\r\n")
Removes any whitespace characters from the end of a string.
Parameters
[in] s - The string to trim.
[in] to_remove - All chars that should be removed.
Returns
The trimmed string.
trim()
std::string core_utils::trim (const std::string & s, const char * to_remove = " \t\r\n")
Removes any whitespace characters from the beginning and the end of a string.
Parameters
[in] s - The string to trim.
[in] to_remove - All chars that should be removed.
Returns
The trimmed string.
Referenced by program_options::add(), boolean_function::boolean_function(), boolean_function::from_string(), hdl_parser_verilog::parse(), module::set_name(), net::set_name(), and gate::set_name().
replace()
std::string core_utils::replace (const std::string & str, const std::string & search, const std::string & replace)
Replaces substring from begin to end of a string.
Parameters
[in] str - The string which is subject to replacement.
[in] search - The search substring which should be replaced.
[in] replace - The replacement string which replaces all occurrences of search.
Returns
String with replaced substring.
Referenced by hdl_parser_verilog::parse().
join()
template<typename T > CORE_API std::string core_utils::join (const std::string & joiner, const T & items)
Joins all elements of a vector with a joiner-string.
Parameters
[in] joiner - The string to put between the elements.
[in] items - The vector of elements to join.
Returns
The combined string.
References CORE_API, file_exists(), folder_exists_and_is_accessible(), get_base_directory(), get_binary_directory(), get_config_directory(), get_default_log_directory(), get_file(), get_first_directory_exists(), get_gate_library_directories(), get_library_directory(), get_open_source_licenses(), get_plugin_directories(), get_share_directory(), get_user_config_directory(), get_user_share_directory(), num_of_occurrences(), to_lower(), to_upper(), and which().
Referenced by program_options::get_options(), program_options::parse(), program_arguments::set_option(), and boolean_function::to_string().
to_upper()
std::string core_utils::to_upper (const std::string & s)
Convert a string to upper case.
Parameters
[in] s - The string to convert.
Returns
The converted string.
Referenced by join().
to_lower()
std::string core_utils::to_lower (const std::string & s)
Convert a string to lower case.
Parameters
[in] s - The string to convert.
Returns
The converted string.
Referenced by join(), and hdl_parser_verilog::parse().
num_of_occurrences()
u32 core_utils::num_of_occurrences (const std::string & str, const std::string & substr)
Counts number of substring occurrences in a string.
Parameters
[in] substr - Substring.
[in] str - String containing the substring.
Returns
The number of occurrences.
Referenced by join().
file_exists()
bool core_utils::file_exists (const std::string & filename)
Checks whether a file exists.
Parameters
[in] filename - The file to check.
Returns
True, if file exists
Referenced by join().
folder_exists_and_is_accessible()
bool core_utils::folder_exists_and_is_accessible (const hal::path & folder)
Checks whether a directory exists and access rights are available.
Parameters
[in] folder - The directory to check.
Returns
True, if folder exists and is accessible.
Referenced by join().
which()
hal::path core_utils::which (const std::string & name, const std::string & path = "")
Locate an executable in the given path environment
Parameters
[in] name - The executable name
[in] path - PATH to search (defaults to PATH environment variable)
Returns
path if executable is found else empty hal::path.
References split(), and UNUSED.
Referenced by get_base_directory(), and join().
get_binary_directory()
hal::path core_utils::get_binary_directory ()
Get the path to the executable of HAL.
Returns
The path.
Referenced by get_base_directory(), join(), and PYBIND11_PLUGIN().
get_base_directory()
hal::path core_utils::get_base_directory ()
Get the base path to the HAL installation.
Use Environment Variable HAL_BASE_PATH
If current executable is hal (not e.g. python3 interpreter) use it's path to determine base path.
Try to find hal executable in path and use its base path.
Returns
The path.
References die, get_binary_directory(), and which().
Referenced by get_config_directory(), get_library_directory(), get_share_directory(), join(), and PYBIND11_PLUGIN().
get_library_directory()
hal::path core_utils::get_library_directory ()
Get the path to the shared and static libraries of HAL.
Relative to the binary directory.
Returns
The path.
References get_base_directory(), and get_first_directory_exists().
Referenced by plugin_python_shell::exec(), get_plugin_directories(), join(), and PYBIND11_PLUGIN().
get_share_directory()
hal::path core_utils::get_share_directory ()
Get the path to the shared objects of HAL.
Relative to the binary directory.
Returns
The path.
References get_base_directory(), and get_first_directory_exists().
Referenced by get_gate_library_directories(), join(), and PYBIND11_PLUGIN().
get_user_share_directory()
hal::path core_utils::get_user_share_directory ()
Get the path to shared objects and files provided by the user.
home/.local/share for Unix
Returns
The path.
Referenced by get_default_log_directory(), get_gate_library_directories(), get_plugin_directories(), join(), and PYBIND11_PLUGIN().
get_config_directory()
hal::path core_utils::get_config_directory ()
Get the path to the read-only global configuration directory of HAL.
Relative to the binary directory.
Returns
The path.
References get_base_directory(), and get_first_directory_exists().
Referenced by join().
get_user_config_directory()
hal::path core_utils::get_user_config_directory ()
Get the path to the configuration directory of the user.
home/.config/hal for Unix
Returns
The path.
Referenced by join(), and PYBIND11_PLUGIN().
get_default_log_directory()
hal::path core_utils::get_default_log_directory (hal::path source_file = "")
Get the path to the default directory for log files.
If an hdl source file is provided, the function returns the parent directory, otherwise get_user_share_directory() / "log".
Parameters
[in] source_file - The hdl source file.
Returns
The path.
References get_user_share_directory().
Referenced by join(), and PYBIND11_PLUGIN().
get_gate_library_directories()
std::vector< hal::path > core_utils::get_gate_library_directories ()
Get the paths where gate libraries are searched.
Contains the share and user share directories.
Returns
A vector of paths.
References get_share_directory(), and get_user_share_directory().
Referenced by gate_library_manager::get_gate_library(), join(), gate_library_manager::load_all(), and PYBIND11_PLUGIN().
get_plugin_directories()
std::vector< hal::path > core_utils::get_plugin_directories ()
Get the paths where plugins are searched.
Contains the library and user share directories.
Returns
A vector of paths.
References get_library_directory(), and get_user_share_directory().
Referenced by join(), and PYBIND11_PLUGIN().
get_first_directory_exists()
hal::path core_utils::get_first_directory_exists (std::vector< hal::path > path_hints)
Returns the first directory of all path hints that exists.
Parameters
[in] path_hints - A vector of hints.
Returns
The first existing path. If none exists an empty string is returned.
Referenced by get_config_directory(), get_library_directory(), get_share_directory(), and join().
get_file()
hal::path core_utils::get_file (std::string file_name, std::vector< hal::path > path_hints)
Search in all paths provided by path hints (used in order) for a given filename.
Parameters
[in] file_name - The filename to search for.
[in] path_hints - A vector of hints.
Returns
The first to match. If none matches an empty string is returned.
Referenced by gate_library_manager::get_gate_library(), and join().
get_open_source_licenses()
std::string core_utils::get_open_source_licenses ()
Get all licenses of used OpenSource Projects.
Returns
All open source licenses;
Referenced by join().