hal: gate_type Class Reference
gate_type Class Reference
Netlist
#include <gate_type.h>
Public Types
enum base_type { base_type::combinatorial, base_type::lut, base_type::ff, base_type::latch }
Public Member Functions
gate_type (const std::string &name)
virtual ~gate_type ()=default
std::string to_string () const
bool operator== (const gate_type &other) const
bool operator!= (const gate_type &other) const
std::string get_name () const
base_type get_base_type () const
void add_input_pin (std::string input_pin)
void add_input_pins (const std::vector< std::string > &input_pins)
std::vector< std::string > get_input_pins () const
void add_output_pin (std::string output_pin)
void add_output_pins (const std::vector< std::string > &output_pins)
std::vector< std::string > get_output_pins () const
void add_boolean_function (std::string name, boolean_function bf)
std::unordered_map< std::string, boolean_function > get_boolean_functions () const
Friends
std::ostream & operator<< (std::ostream &os, const gate_type &gt)
Detailed Description
Gate type class containing information about the internals of a specific gate type.
Member Enumeration Documentation
base_type
enum gate_type::base_type strong
Enumerator
combinatorial
lut
ff
latch
Constructor & Destructor Documentation
gate_type()
gate_type::gate_type (const std::string & name)
Constructor for a gate type.
Parameters
[in] name - The name of the gate type.
References combinatorial.
~gate_type()
virtual gate_type::~gate_type () virtual default
Member Function Documentation
to_string()
std::string gate_type::to_string () const
Get a string describing the given gate type object.
Returns
A string describing the gate type.
Referenced by operator<<(), and PYBIND11_PLUGIN().
operator==()
bool gate_type::operator== (const gate_type & other) const
Test whether two gate type objects are equal.
Parameters
[in] other - Gate type object to compare to.
Returns
True when both gate type objects are equal, false otherwise.
References get_base_type(), get_boolean_functions(), get_input_pins(), get_name(), and get_output_pins().
operator!=()
bool gate_type::operator!= (const gate_type & other) const
Test whether two gate type objects are unequal.
Parameters
[in] other - Gate type object to compare to.
Returns
True when both gate type objects are unequal, false otherwise.
References UNUSED.
get_name()
std::string gate_type::get_name () const
Get the name of the gate type.
Returns
The name of the gate type.
Referenced by operator==(), and PYBIND11_PLUGIN().
get_base_type()
gate_type::base_type gate_type::get_base_type () const
Get the base type of the gate type. The base type can be either combinatorial, lut, ff, or latch.
Returns
The base type of the gate type.
Referenced by operator==(), and PYBIND11_PLUGIN().
add_input_pin()
void gate_type::add_input_pin (std::string input_pin)
Add an input pin to the gate type.
Parameters
[in] input_pin - The name of an input pin.
Referenced by PYBIND11_PLUGIN().
add_input_pins()
void gate_type::add_input_pins (const std::vector< std::string > & input_pins)
Add a vector of input pins to the gate type.
Parameters
[in] input_pins - A vector of names of input pins.
Referenced by PYBIND11_PLUGIN().
get_input_pins()
std::vector< std::string > gate_type::get_input_pins () const
Get a vector of input pins of the gate type.
Returns
A vector of input pins of the gate type.
Referenced by operator==(), and PYBIND11_PLUGIN().
add_output_pin()
void gate_type::add_output_pin (std::string output_pin)
Add an output pin to the gate type.
Parameters
[in] output_pin - The name of an output pin.
Referenced by PYBIND11_PLUGIN().
add_output_pins()
void gate_type::add_output_pins (const std::vector< std::string > & output_pins)
Add a vector of output pins to the gate type.
Parameters
[in] output_pins - A vector of names of output pins.
Referenced by PYBIND11_PLUGIN().
get_output_pins()
std::vector< std::string > gate_type::get_output_pins () const
Get a vector of output pins of the gate type.
Returns
A vector of output pins of the gate type..
Referenced by operator==(), and PYBIND11_PLUGIN().
add_boolean_function()
void gate_type::add_boolean_function (std::string name, boolean_function bf)
Add a boolean function with the specified name to the gate type.
Parameters
[in] name - The name of the boolean function.
[in] bf - A boolean function object.
Referenced by PYBIND11_PLUGIN().
get_boolean_functions()
std::unordered_map< std::string, boolean_function > gate_type::get_boolean_functions () const
Get a map containing the boolean functions of the gate type.
Returns
A map from function names to boolean functions.
Referenced by operator==(), and PYBIND11_PLUGIN().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const gate_type & gt) friend
Insert the gate type object to an output stream.
Parameters
[in] os - The output stream to insert the gate type object into.
[in] gt - The gate type object.
Returns
An output stream.
The documentation for this class was generated from the following files:
netlist/gate_library/gate_type/gate_type.h
/home/runner/work/hal/hal/src/netlist/gate_library/gate_type/gate_type.cpp