hal: i_base Class Reference
i_base Class Reference abstract
HAL Core
#include <interface_base.h>
Public Member Functions
i_base ()=default
virtual ~i_base ()=default
virtual void initialize ()
virtual std::string get_name () const =0
virtual std::string get_version () const =0
bool has_type (interface_type t) const
template<typename... Args>
void log (const Args &... args)
virtual std::set< std::string > get_dependencies () const
virtual void on_load () const
virtual void on_unload () const
virtual void initialize_logging () const
Constructor & Destructor Documentation
i_base()
i_base::i_base () default
~i_base()
virtual i_base::~i_base () virtual default
Member Function Documentation
initialize()
void i_base::initialize () virtual
Plugins utilize two phase construction. Always populate all members etc in the initialize function which is automatically called by plugin_manager::get_plugin_instance()
get_name()
virtual std::string i_base::get_name () const pure virtual
Get the name of the plugin.
Returns
Plugin name.
Implemented in plugin_python_shell.
Referenced by initialize_logging(), and PYBIND11_PLUGIN().
get_version()
virtual std::string i_base::get_version () const pure virtual
Get the version of the plugin.
Returns
Plugin version.
Implemented in plugin_python_shell.
Referenced by PYBIND11_PLUGIN().
has_type()
bool i_base::has_type (interface_type t) const
Check whether the plugin has a specific type.
Parameters
[in] t - the type to check
Returns
True, if the type is supported.
References base, cli, and interactive_ui.
log()
template<typename... Args> void i_base::log (const Args &... args) inline
Shorthand for fast text logging.
Parameters
[in] args - The format string, followed by values.
References log_info.
get_dependencies()
std::set< std::string > i_base::get_dependencies () const virtual
Get all plugin dependencies of this plugin.
Returns
A set of plugins that this plugin depends on.
on_load()
void i_base::on_load () const virtual
This function is automatically executed when the factory is loaded by the plugin manager
on_unload()
void i_base::on_unload () const virtual
This function is automatically executed when the factory is unloaded by the plugin manager
initialize_logging()
void i_base::initialize_logging () const virtual
Initializes the logging channel(s) of a plugin.
If not overwritten, a logging channel equal to the plugin name is created.
References log_manager::add_channel(), log_manager::create_file_sink(), log_manager::create_gui_sink(), log_manager::create_stdout_sink(), log_manager::get_instance(), and get_name().
The documentation for this class was generated from the following files:
core/interface_base.h
/home/runner/work/hal/hal/src/core/interface_base.cpp