hal: boolean_function Class Reference
boolean_function Class Reference
Netlist
#include <boolean_function.h>
Public Types
enum value { X = -1, ZERO = 0, ONE = 1 }
Public Member Functions
boolean_function ()
boolean_function (const std::string &variable_name)
boolean_function (value constant)
boolean_function substitute (const std::string &old_variable_name, const std::string &new_variable_name) const
boolean_function substitute (const std::string &variable_name, const boolean_function &function) const
value evaluate (const std::map< std::string, value > &inputs={}) const
value operator() (const std::map< std::string, value > &inputs={}) const
bool is_constant_one () const
bool is_constant_zero () const
bool is_empty () const
std::set< std::string > get_variables () const
std::string to_string () const
boolean_function operator & (const boolean_function &other) const
boolean_function operator| (const boolean_function &other) const
boolean_function operator^ (const boolean_function &other) const
boolean_function & operator &= (const boolean_function &other)
boolean_function & operator|= (const boolean_function &other)
boolean_function & operator^= (const boolean_function &other)
boolean_function operator! () const
bool operator== (const boolean_function &other) const
bool operator!= (const boolean_function &other) const
bool is_dnf () const
boolean_function to_dnf () const
std::vector< std::vector< std::pair< std::string, bool > > > get_dnf_clauses () const
boolean_function optimize () const
std::vector< value > get_truth_table (std::vector< std::string > ordered_variables={}, bool remove_unknown_variables=false) const
Static Public Member Functions
static std::string to_string (const value &v)
static boolean_function from_string (std::string expression, const std::vector< std::string > &variable_names={})
Friends
std::ostream & operator<< (std::ostream &os, const value &v)
std::ostream & operator<< (std::ostream &os, const boolean_function &f)
std::ostream & operator<< (std::ostream &os, const operation &op)
Detailed Description
Boolean function class.
Member Enumeration Documentation
value
enum boolean_function::value
Enumerator
X
ZERO
ONE
Constructor & Destructor Documentation
boolean_function() [1/3]
boolean_function::boolean_function ()
Constructor for an empty function. Evaluates to X (undefined). Combining a function with an empty function leaves the other one unchanged.
Referenced by from_string(), operator!=(), operator<<(), optimize(), and substitute().
boolean_function() [2/3]
boolean_function::boolean_function (const std::string & variable_name)
Constructor for a variable, usable in other functions. Variable name must not be empty.
Parameters
[in] variable_name - Name of the variable.
References core_utils::trim().
boolean_function() [3/3]
boolean_function::boolean_function (value constant)
Constructor for a constant, usable in other functions. The constant can be either X, Zero, or ONE.
Parameters
[in] constant - A constant value.
Member Function Documentation
to_string() [1/2]
std::string boolean_function::to_string (const value & v) static
Returns the value as a string.
Parameters
[in] v - the value.
Returns
A string describing the value.
Referenced by operator<<(), and PYBIND11_PLUGIN().
substitute() [1/2]
boolean_function boolean_function::substitute (const std::string & old_variable_name, const std::string & new_variable_name) const
Substitutes a variable with another variable (i.e., variable renaming). Applies to all instances of the variable in the function.
This is just a shorthand for the generic substitute function.
Parameters
[in] old_variable_name - The old variable to substitute
[in] new_variable_name - The new variable name
Returns
The new boolean function.
References boolean_function().
Referenced by PYBIND11_PLUGIN().
substitute() [2/2]
boolean_function boolean_function::substitute (const std::string & variable_name, const boolean_function & function) const
Substitutes a variable with another function (can again be a single variable). Applies to all instances of the variable in the function.
Parameters
[in] variable_name - The variable to substitute
[in] function - The function to take the place of the varible
Returns
The new boolean function.
evaluate()
boolean_function::value boolean_function::evaluate (const std::map< std::string, value > & inputs = {}) const
Evaluates the function on the given inputs and returns the result.
Parameters
[in] inputs - A map from variable names to values.
Returns
The value that the function evaluates to.
References X.
Referenced by get_truth_table(), operator()(), and PYBIND11_PLUGIN().
operator()()
boolean_function::value boolean_function::operator() (const std::map< std::string, value > & inputs = {}) const
Evaluates the function on the given inputs and returns the result.
Parameters
[in] inputs - A map from variable names to values.
Returns
The value that the function evaluates to.
References evaluate().
is_constant_one()
bool boolean_function::is_constant_one () const
Checks whether the function constantly outputs ONE.
Returns
True if function is constant ONE, false otherwise.
References ONE, and optimize().
Referenced by PYBIND11_PLUGIN().
is_constant_zero()
bool boolean_function::is_constant_zero () const
Checks whether the function constantly outputs ZERO.
Returns
True if function is constant ZERO, false otherwise.
References optimize(), and ZERO.
Referenced by PYBIND11_PLUGIN().
is_empty()
bool boolean_function::is_empty () const
Checks whether the function is empty.
Returns
True if function is empty, false otherwise.
Referenced by get_dnf_clauses(), operator!=(), operator<<(), operator==(), optimize(), PYBIND11_PLUGIN(), and to_string().
get_variables()
std::set< std::string > boolean_function::get_variables () const
Get all variable names used in this boolean function.
Returns
A set of all variable names.
Referenced by get_truth_table(), optimize(), gate_library_parser_liberty::parse(), and PYBIND11_PLUGIN().
from_string()
boolean_function boolean_function::from_string (std::string expression, const std::vector< std::string > & variable_names = {}) static
Parse a function from a string representation. Supported operators are NOT ("!", "'"), AND ("&", "*", " "), OR ("|", "+"), XOR ("^") and brackets ("(", ")"). Operator precedence is ! > & > ^ > |
Since, for example, '(' is interpreted as a new term, but might also be an intended part of a variable, a vector of known variable names can be supplied, which are extracted before parsing.
If there is an error during bracket matching, X is returned for that part.
Parameters
[in] expression - String containing a boolean function.
[in] variable_names - Names of variables to help resolve problematic functions
Returns
The boolean function extracted from the string.
References boolean_function(), ONE, core_utils::starts_with(), core_utils::trim(), X, and ZERO.
Referenced by gate_library_parser_liberty::parse(), and PYBIND11_PLUGIN().
to_string() [2/2]
std::string boolean_function::to_string () const
Returns the boolean function as a string.
Returns
A string describing the boolean function.
References is_empty(), and core_utils::join().
Referenced by get_dnf_clauses(), and operator<<().
operator &()
boolean_function boolean_function::operator& (const boolean_function & other) const
Combines two boolean functions using an AND operator.
Parameters
[in] other - the other function to combine with.
Returns
The combined boolean function.
Referenced by operator<<().
operator|()
boolean_function boolean_function::operator| (const boolean_function & other) const
Combines two boolean functions using an OR operator.
Parameters
[in] other - the other function to combine with.
Returns
The combined boolean function.
operator^()
boolean_function boolean_function::operator^ (const boolean_function & other) const
Combines two boolean functions using an XOR operator.
Parameters
[in] other - the other function to combine with.
Returns
The combined boolean function.
References operator &=().
operator &=()
boolean_function& boolean_function::operator&= (const boolean_function & other)
Combines two boolean functions using an AND operator in place.
Parameters
[in] other - the other function to combine with.
Returns
Self-reference.
Referenced by operator^().
operator|=()
boolean_function & boolean_function::operator|= (const boolean_function & other)
Combines two boolean functions using an OR operator in place.
Parameters
[in] other - the other function to combine with.
Returns
Self-reference.
operator^=()
boolean_function & boolean_function::operator^= (const boolean_function & other)
Combines two boolean functions using an XOR operator in place.
Parameters
[in] other - the other function to combine with.
Returns
Self-reference.
operator!()
boolean_function boolean_function::operator! () const
Negates the boolean function.
Returns
The negated boolean function.
References ONE, and ZERO.
operator==()
bool boolean_function::operator== (const boolean_function & other) const
Tests whether two boolean functions are equal.
Parameters
[in] other - Boolean function to compare to.
Returns
True when both boolean functions are equal, false otherwise.
References is_empty().
operator!=()
bool boolean_function::operator!= (const boolean_function & other) const
Tests whether two boolean functions are unequal.
Parameters
[in] other - Boolean function to compare to.
Returns
True when both boolean functions are unequal, false otherwise.
References boolean_function(), is_empty(), ONE, and ZERO.
is_dnf()
bool boolean_function::is_dnf () const
Tests whether the function is in DNF.
Returns
True if in DNF, false otherwise.
Referenced by PYBIND11_PLUGIN(), and to_dnf().
to_dnf()
boolean_function boolean_function::to_dnf () const
Gets the plain DNF representation of the function.
Returns
The DNF as a boolean function.
References is_dnf().
Referenced by get_dnf_clauses(), optimize(), and PYBIND11_PLUGIN().
get_dnf_clauses()
std::vector< std::vector< std::pair< std::string, bool > > > boolean_function::get_dnf_clauses () const
Gets the DNF clauses of the function. Useful for parsing into other formats etc.
Returns all clauses that are OR-ed together. Each clause is a vector of pairs <variable name, boolean value>. Example: [[("a", true), ("b", false)], [("c", true)]] -> (a & !b) | c
If the function is empty, this returns an empty vector.
Returns
The DNF clauses as a vector of vectors of pairs <string, bool>.
References is_empty(), to_dnf(), and to_string().
optimize()
boolean_function boolean_function::optimize () const
Optimizes the function by first converting it to DNF and then applying the Quine-McCluskey algorithm.
Returns
The optimized boolean function.
References boolean_function(), get_variables(), is_empty(), and to_dnf().
Referenced by gate::get_boolean_functions(), is_constant_one(), is_constant_zero(), and PYBIND11_PLUGIN().
get_truth_table()
std::vector< boolean_function::value > boolean_function::get_truth_table (std::vector< std::string > ordered_variables = {}, bool remove_unknown_variables = false) const
Get the truth table outputs of the function. WARNING: Exponential runtime in the number of variables!
Output is the vector of output values when walking the truth table in ascending order. The variable values are changed in order of appearance, i.e.: first_var second_var | output_vector_index 0 0 | 0 1 0 | 1 0 1 | 2 1 1 | 3
If ordered_variables is empty, all included variables are used and ordered alphabetically.
Parameters
[in] ordered_variables - Specific order in which the inputs shall be structured in the truth table.
[in] remove_unknown_variables - If true, all given variables that are not found in the function are removed from the truth table.
Returns
The vector of output values.
References evaluate(), and get_variables().
Referenced by gate::add_boolean_function(), and PYBIND11_PLUGIN().
Friends And Related Function Documentation
operator<< [1/3]
std::ostream& operator<< (std::ostream & os, const value & v) friend
ostream operator that forwards to_string of a value.
Parameters
[in] os - the stream to write to.
[in] v - the value.
Returns
A reference to os.
operator<< [2/3]
std::ostream& operator<< (std::ostream & os, const boolean_function & f) friend
ostream operator that forwards to_string of a boolean function.
Parameters
[in] os - the stream to write to.
[in] f - the function.
Returns
A reference to os.
operator<< [3/3]
std::ostream& operator<< (std::ostream & os, const operation & op) friend
The documentation for this class was generated from the following files:
netlist/boolean_function.h
/home/runner/work/hal/hal/src/netlist/boolean_function.cpp