hal: gate_library_manager Namespace Reference
gate_library_manager Namespace Reference
Netlist
Functions
NETLIST_API std::shared_ptr< gate_library > get_gate_library (const std::string &name)
NETLIST_API void load_all ()
NETLIST_API std::map< std::string, std::shared_ptr< gate_library > > get_gate_libraries ()
Function Documentation
get_gate_library()
std::shared_ptr< gate_library > gate_library_manager::get_gate_library (const std::string & name)
Get a gate library object by name.
Parameters
[in] name - Name of the gate library.
Returns
Pointer to the gate library object.
References core_utils::get_file(), core_utils::get_gate_library_directories(), plugin_manager::load(), and log_error.
Referenced by netlist_factory::create_netlist().
load_all()
void gate_library_manager::load_all ()
Loads all gate libraries which are available.
References core_utils::get_gate_library_directories(), plugin_manager::load(), and log_info.
get_gate_libraries()
std::map< std::string, std::shared_ptr< gate_library > > gate_library_manager::get_gate_libraries ()
Get all gate libraries together with the associated name.
Returns
A map from library name to pointer to the gate library object.
Referenced by hdl_parser_dispatcher::parse().