hal: data_container Class Reference
data_container Class Reference
Netlist
#include <data_container.h>
Public Member Functions
data_container ()=default
virtual ~data_container ()=default
bool set_data (const std::string &category, const std::string &key, const std::string &data_type, const std::string &value, const bool log_with_info_level=false)
bool delete_data (const std::string &category, const std::string &key, const bool log_with_info_level=false)
std::map< std::tuple< std::string, std::string >, std::tuple< std::string, std::string > > get_data () const
std::tuple< std::string, std::string > get_data_by_key (const std::string &category, const std::string &key) const
std::vector< std::tuple< std::string, std::string > > get_data_keys () const
Detailed Description
Data structure for custom data associations.
Constructor & Destructor Documentation
data_container()
data_container::data_container () default
constructor (= default)
~data_container()
virtual data_container::~data_container () virtual default
destructor (= default) Needs to be virtual to access interface in subclasses via python.
Member Function Documentation
set_data()
bool data_container::set_data (const std::string & category, const std::string & key, const std::string & data_type, const std::string & value, const bool log_with_info_level = false)
Sets a custom data entry.
If it does not exist yet, it is added.
Parameters
[in] category - Key category
[in] key - Data key
[in] data_type - Data type of value
[in] value - Data value
[in] log_with_info_level - Force explicit logging channel 'netlist' with log level info to trace GUI events (default = false)
Returns
True on success.
References log_debug, log_error, and log_info.
Referenced by gate::add_boolean_function(), hdl_parser_verilog::parse(), and PYBIND11_PLUGIN().
delete_data()
bool data_container::delete_data (const std::string & category, const std::string & key, const bool log_with_info_level = false)
Deletes custom data.
Parameters
[in] category - Category of key
[in] key - Data key
[in] log_with_info_level - Force explicit logging channel 'netlist' with log level info to trace GUI events (default = false)
Returns
True on success.
References log_debug, log_error, and log_info.
Referenced by PYBIND11_PLUGIN().
get_data()
std::map< std::tuple< std::string, std::string >, std::tuple< std::string, std::string > > data_container::get_data () const
Gets all stored data.
Returns
A map from ((1) category, (2) key) to ((1) type, (2) value)
Referenced by PYBIND11_PLUGIN().
get_data_by_key()
std::tuple< std::string, std::string > data_container::get_data_by_key (const std::string & category, const std::string & key) const
Gets data specified by key and category.
Parameters
[in] category - Category of key
[in] key - Data key
Returns
The tuple ((1) type, (2) value)
References log_debug, and log_error.
Referenced by gate::get_boolean_functions(), and PYBIND11_PLUGIN().
get_data_keys()
std::vector< std::tuple< std::string, std::string > > data_container::get_data_keys () const
Returns all data keys
Returns
A vector of tuples ((1) category, (2) key)
Referenced by PYBIND11_PLUGIN().
The documentation for this class was generated from the following files:
netlist/data_container.h
/home/runner/work/hal/hal/src/netlist/data_container.cpp