HAL: nlohmann::detail::lexer< BasicJsonType > Class Template Reference
nlohmann::detail::lexer< BasicJsonType > Class Template Reference
lexical analysis
#include <json.hpp>
Public Types
enum token_type {
token_type::uninitialized, token_type::literal_true, token_type::literal_false, token_type::literal_null,
token_type::value_string, token_type::value_unsigned, token_type::value_integer, token_type::value_float,
token_type::begin_array, token_type::begin_object, token_type::end_array, token_type::end_object,
token_type::name_separator, token_type::value_separator, token_type::parse_error, token_type::end_of_input,
token_type::literal_or_value
}
token types for the parser
Public Member Functions
lexer (detail::input_adapter_t &&adapter)
lexer (const lexer &)=delete
lexer (lexer &&)=delete
lexer & operator= (lexer &)=delete
lexer & operator= (lexer &&)=delete
~lexer ()=default
constexpr number_integer_t get_number_integer () const noexcept
return integer value
constexpr number_unsigned_t get_number_unsigned () const noexcept
return unsigned integer value
constexpr number_float_t get_number_float () const noexcept
return floating-point value
string_t & get_string ()
return current string value (implicitly resets the token; useful only once)
constexpr position_t get_position () const noexcept
return position of last read token
std::string get_token_string () const
constexpr const char * get_error_message () const noexcept
return syntax error message
bool skip_bom ()
skip the UTF-8 byte order mark
token_type scan ()
Static Public Member Functions
static const char * token_type_name (const token_type t) noexcept
return name of values of type token_type (only used for errors)
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::lexer< BasicJsonType >
lexical analysis
This class organizes the lexical analysis during JSON deserialization.
Definition at line 7161 of file json.hpp.
Member Enumeration Documentation
token_type
template<typename BasicJsonType > enum nlohmann::detail::lexer::token_type strong
token types for the parser
Enumerator
uninitialized
indicating the scanner is uninitialized
literal_true
the true literal
literal_false
the false literal
literal_null
the null literal
value_string
a string – use get_string() for actual value
value_unsigned
an unsigned integer – use get_number_unsigned() for actual value
value_integer
a signed integer – use get_number_integer() for actual value
value_float
an floating point number – use get_number_float() for actual value
begin_array
the character for array begin [
begin_object
the character for object begin {
end_array
the character for array end ]
end_object
the character for object end }
name_separator
the name separator :
value_separator
the value separator ,
parse_error
indicating a parse error
end_of_input
indicating the end of the input buffer
literal_or_value
a literal or the begin of a value (only for diagnostics)
Definition at line 7170 of file json.hpp.
Constructor & Destructor Documentation
lexer() [1/3]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::lexer (detail::input_adapter_t && adapter) inline explicit
Definition at line 7237 of file json.hpp.
lexer() [2/3]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::lexer (const lexer< BasicJsonType > &) delete
lexer() [3/3]
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::lexer (lexer< BasicJsonType > &&) delete
~lexer()
template<typename BasicJsonType > nlohmann::detail::lexer< BasicJsonType >::~lexer () default
Member Function Documentation
get_error_message()
template<typename BasicJsonType > constexpr const char* nlohmann::detail::lexer< BasicJsonType >::get_error_message () const inline constexpr noexcept
return syntax error message
Definition at line 8513 of file json.hpp.
get_number_float()
template<typename BasicJsonType > constexpr number_float_t nlohmann::detail::lexer< BasicJsonType >::get_number_float () const inline constexpr noexcept
return floating-point value
Definition at line 8464 of file json.hpp.
get_number_integer()
template<typename BasicJsonType > constexpr number_integer_t nlohmann::detail::lexer< BasicJsonType >::get_number_integer () const inline constexpr noexcept
return integer value
Definition at line 8452 of file json.hpp.
get_number_unsigned()
template<typename BasicJsonType > constexpr number_unsigned_t nlohmann::detail::lexer< BasicJsonType >::get_number_unsigned () const inline constexpr noexcept
return unsigned integer value
Definition at line 8458 of file json.hpp.
get_position()
template<typename BasicJsonType > constexpr position_t nlohmann::detail::lexer< BasicJsonType >::get_position () const inline constexpr noexcept
return position of last read token
Definition at line 8480 of file json.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType >::parse(), and nlohmann::detail::parser< BasicJsonType >::sax_parse().
get_string()
template<typename BasicJsonType > string_t& nlohmann::detail::lexer< BasicJsonType >::get_string () inline
return current string value (implicitly resets the token; useful only once)
Definition at line 8470 of file json.hpp.
get_token_string()
template<typename BasicJsonType > std::string nlohmann::detail::lexer< BasicJsonType >::get_token_string () const inline
return the last read token (for errors only). Will never contain EOF (an arbitrary value that is not a valid char value, often -1), because 255 may legitimately occur. May contain NUL, which should be escaped.
Definition at line 8488 of file json.hpp.
References and().
Referenced by nlohmann::detail::parser< BasicJsonType >::parse(), and nlohmann::detail::parser< BasicJsonType >::sax_parse().
operator=() [1/2]
template<typename BasicJsonType > lexer& nlohmann::detail::lexer< BasicJsonType >::operator= (lexer< BasicJsonType > &&) delete
operator=() [2/2]
template<typename BasicJsonType > lexer& nlohmann::detail::lexer< BasicJsonType >::operator= (lexer< BasicJsonType > &) delete
scan()
template<typename BasicJsonType > token_type nlohmann::detail::lexer< BasicJsonType >::scan () inline
Definition at line 8540 of file json.hpp.
References and(), nlohmann::detail::get(), and or.
skip_bom()
template<typename BasicJsonType > bool nlohmann::detail::lexer< BasicJsonType >::skip_bom () inline
skip the UTF-8 byte order mark
Returns
true iff there is no BOM or the correct BOM has been skipped
Definition at line 8526 of file json.hpp.
References and(), and nlohmann::detail::get().
token_type_name()
template<typename BasicJsonType > static const char* nlohmann::detail::lexer< BasicJsonType >::token_type_name (const token_type t) inline static noexcept
return name of values of type token_type (only used for errors)
Definition at line 7194 of file json.hpp.
References nlohmann::detail::lexer< BasicJsonType >::begin_array, nlohmann::detail::lexer< BasicJsonType >::begin_object, nlohmann::detail::lexer< BasicJsonType >::end_array, nlohmann::detail::lexer< BasicJsonType >::end_object, nlohmann::detail::lexer< BasicJsonType >::end_of_input, nlohmann::detail::lexer< BasicJsonType >::literal_false, nlohmann::detail::lexer< BasicJsonType >::literal_null, nlohmann::detail::lexer< BasicJsonType >::literal_or_value, nlohmann::detail::lexer< BasicJsonType >::literal_true, nlohmann::detail::lexer< BasicJsonType >::name_separator, nlohmann::detail::lexer< BasicJsonType >::parse_error, nlohmann::detail::lexer< BasicJsonType >::uninitialized, nlohmann::detail::lexer< BasicJsonType >::value_float, nlohmann::detail::lexer< BasicJsonType >::value_integer, nlohmann::detail::lexer< BasicJsonType >::value_separator, nlohmann::detail::lexer< BasicJsonType >::value_string, and nlohmann::detail::lexer< BasicJsonType >::value_unsigned.
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/plugins/dataflow_analysis/include/dataflow_analysis/output_generation/json.hpp