HAL: hal::UserActionObject Class Reference
hal::UserActionObject Class Reference
HAL Gui » User Actions
The UserActionObject class represents a single object used in UserAction.
#include <user_action_object.h>
Public Member Functions
UserActionObject (u32 i=0, UserActionObjectType::ObjectType t=UserActionObjectType::None)
u32 id () const
UserActionObjectType::ObjectType type () const
void writeToXml (QXmlStreamWriter &xmlOut) const
void readFromXml (QXmlStreamReader &xmlIn)
QString debugDump () const
Detailed Description
The UserActionObject class represents a single object used in UserAction.
An object is identified by unique id and type
Definition at line 78 of file user_action_object.h.
Constructor & Destructor Documentation
UserActionObject()
hal::UserActionObject::UserActionObject (u32 i = 0, UserActionObjectType::ObjectType t = UserActionObjectType::None) inline
Object constructor, without arguments object of type None gets constructed.
Parameters
i - The id.
t - The type.
Definition at line 87 of file user_action_object.h.
Member Function Documentation
debugDump()
QString hal::UserActionObject::debugDump () const
Short code for debugging purpose.
Returns
- The debug string.
Definition at line 97 of file user_action_object.cpp.
References QString::arg(), hal::UserActionObjectType::Grouping, and hal::UserActionObjectType::None.
Referenced by hal::UserAction::debugDump().
id()
u32 hal::UserActionObject::id () const inline
Get the object's id.
Returns
The id.
Definition at line 97 of file user_action_object.h.
Referenced by hal::NetlistRelay::addToModuleDialog(), hal::GuiApiClasses::View::createNewDirectory(), hal::ActionAddBooleanFunction::exec(), hal::ActionAddItemsToObject::exec(), hal::ActionCreateObject::exec(), hal::ActionDeleteObject::exec(), hal::ActionFoldModule::exec(), hal::ActionMoveItem::exec(), hal::ActionMoveNode::exec(), hal::ActionPingroup::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionRenameObject::exec(), hal::ActionSetObjectColor::exec(), hal::ActionSetObjectData::exec(), hal::ActionSetObjectType::exec(), hal::ActionSetSelectionFocus::exec(), hal::ActionUnfoldModule::exec(), hal::SelectionDetailsWidget::groupingUnassignActionFactory(), hal::ActionSetSelectionFocus::hasModifications(), hal::GuiApiClasses::View::isolateInNew(), hal::GuiApiClasses::View::isolateModuleToModulePathInNewView(), hal::GraphContextManager::openModuleInView(), hal::ActionSetSelectionFocus::setObject(), and hal::ActionUnfoldModule::setObject().
readFromXml()
void hal::UserActionObject::readFromXml (QXmlStreamReader & xmlIn)
Reads object member variables from xml attributes "id" and "type".
Parameters
xmlIn - The file to read from.
Definition at line 113 of file user_action_object.cpp.
References QXmlStreamReader::attributes(), QStringRef::isEmpty(), QStringRef::isNull(), QStringRef::toInt(), QStringRef::toString(), and QXmlStreamAttributes::value().
Referenced by hal::UserActionManager::getParsedAction(), and hal::UserAction::readParentObjectFromXml().
type()
UserActionObjectType::ObjectType hal::UserActionObject::type () const inline
Get the object's type.
Returns
The type.
Definition at line 107 of file user_action_object.h.
Referenced by hal::ActionAddItemsToObject::exec(), hal::ActionCreateObject::exec(), hal::ActionDeleteObject::exec(), hal::ActionFoldModule::exec(), hal::ActionMoveItem::exec(), hal::ActionMoveNode::exec(), hal::ActionPingroup::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionRenameObject::exec(), hal::ActionSetObjectColor::exec(), hal::ActionSetObjectData::exec(), hal::ActionSetObjectType::exec(), hal::ActionSetSelectionFocus::exec(), hal::ActionUnfoldModule::exec(), hal::SelectionDetailsWidget::groupingUnassignActionFactory(), hal::ActionSetSelectionFocus::hasModifications(), hal::ActionSetSelectionFocus::setObject(), hal::ActionUnfoldModule::setObject(), and hal::UserAction::writeParentObjectToXml().
writeToXml()
void hal::UserActionObject::writeToXml (QXmlStreamWriter & xmlOut) const
Persist object to xml attributes "id" and "type".
Parameters
xmlOut - The file to write to.
Definition at line 106 of file user_action_object.cpp.
References hal::UserActionObjectType::None, QString::number(), hal::UserActionObjectType::toString(), and QXmlStreamWriter::writeAttribute().
Referenced by hal::UserActionManager::setStopRecording(), and hal::UserAction::writeParentObjectToXml().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/user_action_object.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/user_action_object.cpp