HAL: hal::PinModel Class Reference
hal::PinModel Class Reference
#include <pin_model.h>
Signals
void editNewDone (QModelIndex index)
Public Member Functions
PinModel (QObject *parent=nullptr)
PinModel (QObject *parent, bool editable)
~PinModel ()
Qt::ItemFlags flags (const QModelIndex &index) const override
void setGate (GateType *gate)
void handleEditName (QModelIndex index, const QString &input)
void handleEditDirection (QModelIndex index, const QString &directionString)
void handleEditType (QModelIndex index, const QString &typeString)
void handleDeleteItem (QModelIndex index)
QList< PinItem * > getPinGroups () const
QList< PinItem * > getInputPins ()
QList< PinItem * > getOutputPins ()
Public Member Functions inherited from hal::BaseTreeModel
BaseTreeModel (QObject *parent=nullptr)
void setContent (QList< BaseTreeItem * > firstLevelItems)
virtual void clear ()
void setHeaderLabels (const QStringList &label)
QStringList headerLabels () const
QModelIndex getIndexFromItem (BaseTreeItem *item) const
BaseTreeItem * getItemFromIndex (QModelIndex index) const
BaseTreeItem * getRootItem () const
void insertChildItem (BaseTreeItem *childItem, BaseTreeItem *parentItem=nullptr, int row=-1)
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
virtual QModelIndex parent (const QModelIndex &index) const override
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const override
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const override
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
virtual QModelIndex sibling (int row, int column, const QModelIndex &index) const const
virtual bool hasChildren (const QModelIndex &parent) const const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role)
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const const
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
virtual QStringList mimeTypes () const const
virtual QMimeData * mimeData (const QModelIndexList &indexes) const const
virtual bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const const
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
virtual Qt::DropActions supportedDropActions () const const
virtual Qt::DropActions supportedDragActions () const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool insertRows (int row, int count, const QModelIndex &parent)
virtual bool insertColumns (int column, int count, const QModelIndex &parent)
virtual bool removeRows (int row, int count, const QModelIndex &parent)
virtual bool removeColumns (int column, int count, const QModelIndex &parent)
virtual bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual void fetchMore (const QModelIndex &parent)
virtual bool canFetchMore (const QModelIndex &parent) const const
virtual void sort (int column, Qt::SortOrder order)
virtual QModelIndex buddy (const QModelIndex &index) const const
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const
virtual QSize span (const QModelIndex &index) const const
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual bool submit ()
virtual void revert ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Attributes inherited from hal::BaseTreeModel
RootTreeItem * mRootItem
Properties inherited from QObject
objectName
Detailed Description
Definition at line 49 of file pin_model.h.
Constructor & Destructor Documentation
PinModel() [1/2]
hal::PinModel::PinModel (QObject * parent = nullptr) explicit
Definition at line 7 of file pin_model.cpp.
References hal::BaseTreeModel::setHeaderLabels().
PinModel() [2/2]
hal::PinModel::PinModel (QObject * parent, bool editable) explicit
Definition at line 18 of file pin_model.cpp.
References hal::BaseTreeModel::setHeaderLabels().
~PinModel()
hal::PinModel::~PinModel ()
Definition at line 27 of file pin_model.cpp.
References hal::BaseTreeModel::clear().
Member Function Documentation
editNewDone
void hal::PinModel::editNewDone (QModelIndex index) signal
Referenced by hal::GateLibraryTabPin::GateLibraryTabPin(), handleEditDirection(), and handleEditName().
flags()
Qt::ItemFlags hal::PinModel::flags (const QModelIndex & index) const override virtual
Returns the item flags for the given index.
Parameters
index - The model index to get the flags for
Returns
the item flags for the given index
Reimplemented from hal::BaseTreeModel.
Definition at line 32 of file pin_model.cpp.
References hal::BaseTreeModel::flags(), hal::BaseTreeModel::index(), QModelIndex::isValid(), Qt::ItemFlags, and Qt::ItemIsEditable.
getInputPins()
QList< PinItem * > hal::PinModel::getInputPins ()
Definition at line 746 of file pin_model.cpp.
References QList::append(), hal::BaseTreeItem::getChildren(), hal::PinItem::getDirection(), hal::PinItem::getItemType(), hal::inout, hal::input, hal::BaseTreeModel::mRootItem, hal::PinItem::Pin, and hal::PinItem::PinGroup.
Referenced by hal::BoolWizardPage::initializePage(), and hal::FlipFlopWizardPage::initializePage().
getOutputPins()
QList< PinItem * > hal::PinModel::getOutputPins ()
Definition at line 761 of file pin_model.cpp.
References QList::append(), hal::BaseTreeItem::getChildren(), hal::PinItem::getDirection(), hal::PinItem::getItemType(), hal::inout, hal::BaseTreeModel::mRootItem, hal::output, hal::PinItem::Pin, and hal::PinItem::PinGroup.
Referenced by hal::BoolWizardPage::initializePage().
getPinGroups()
QList< PinItem * > hal::PinModel::getPinGroups () const
Returns a List of PinGroup structures representing the pingroups of a GateType
Returns
List of PinGroup structures representing the pingroups of a GateType
Definition at line 649 of file pin_model.cpp.
References QList::append(), hal::BaseTreeItem::getChildren(), hal::PinItem::getItemType(), hal::BaseTreeModel::mRootItem, and hal::PinItem::PinGroup.
Referenced by hal::PinsWizardPage::getPingroups(), hal::GateLibraryWizard::getPingroups(), and handleEditType().
handleDeleteItem()
void hal::PinModel::handleDeleteItem (QModelIndex index)
Definition at line 661 of file pin_model.cpp.
References QAbstractItemModel::beginRemoveRows(), QAbstractItemModel::endRemoveRows(), hal::BaseTreeModel::getItemFromIndex(), hal::BaseTreeModel::getRootItem(), hal::BaseTreeModel::index(), hal::PinItem::InvalidPin, hal::PinItem::InvalidPinGroup, QModelIndex::isValid(), hal::PinItem::Pin, hal::PinItem::PinGroup, hal::BaseTreeItem::removeChild(), and type.
Referenced by hal::PinsWizardPage::handleDeleteClicked().
handleEditDirection()
void hal::PinModel::handleEditDirection (QModelIndex index, const QString & directionString)
should be called when the items direction is changed via the delegate
Parameters
index index of the PinItem
direction new direction
Definition at line 252 of file pin_model.cpp.
References QMessageBox::Abort, QMessageBox::AcceptRole, QMessageBox::addButton(), QString::arg(), QMessageBox::clickedButton(), QAbstractItemModel::dataChanged(), editNewDone(), QMessageBox::exec(), hal::PinItem::getDirection(), hal::PinItem::getDirectionAsText(), hal::PinItem::getItemType(), hal::BaseTreeModel::index(), QModelIndex::internalPointer(), hal::PinItem::InvalidPin, hal::PinItem::InvalidPinGroup, QModelIndex::isValid(), hal::none, hal::PinItem::Pin, hal::PinItem::PinGroup, QObject::Q_EMIT(), hal::PinItem::setDirection(), QMessageBox::setText(), QMessageBox::setWindowTitle(), QString::toStdString(), and QObject::tr().
handleEditName()
void hal::PinModel::handleEditName (QModelIndex index, const QString & input)
should be called when the items name is changed via the delegate
Parameters
index index of the PinItem
input new name
Definition at line 148 of file pin_model.cpp.
References QAbstractItemModel::beginInsertRows(), QAbstractItemModel::dataChanged(), editNewDone(), QAbstractItemModel::endInsertRows(), hal::PinItem::getDirection(), hal::PinItem::getItemType(), hal::PinItem::getPinType(), hal::PinItem::GroupCreator, hal::BaseTreeModel::index(), hal::input, QSet::insert(), QModelIndex::internalPointer(), hal::PinItem::InvalidPin, hal::PinItem::InvalidPinGroup, QModelIndex::isValid(), hal::none, QModelIndex::parent(), hal::PinItem::Pin, hal::PinItem::PinCreator, hal::PinItem::PinGroup, QObject::Q_EMIT(), hal::PinItem::setDirection(), hal::PinItem::setId(), hal::PinItem::setName(), and hal::PinItem::setType().
handleEditType()
void hal::PinModel::handleEditType (QModelIndex index, const QString & typeString)
should be called when the items type is changed via the delegate
Parameters
index index of the PinItem
type new type
Definition at line 308 of file pin_model.cpp.
References QAbstractItemModel::dataChanged(), hal::PinItem::getItemType(), getPinGroups(), hal::BaseTreeModel::index(), QModelIndex::internalPointer(), hal::PinItem::InvalidPin, hal::PinItem::InvalidPinGroup, QModelIndex::isValid(), hal::PinItem::Pin, hal::PinItem::PinGroup, QObject::Q_EMIT(), hal::PinItem::setType(), and QString::toStdString().
setGate()
void hal::PinModel::setGate (GateType * gate)
sets the gate from which the pins are to be displayed
Parameters
gate that have to be displayed
Definition at line 41 of file pin_model.cpp.
References QList::append(), hal::BaseTreeItem::appendChild(), QAbstractItemModel::beginResetModel(), hal::BaseTreeModel::clear(), QAbstractItemModel::endResetModel(), QString::fromStdString(), hal::GateType::get_pin_groups(), hal::PinItem::getDirection(), hal::PinItem::getName(), hal::PinItem::getPinType(), hal::PinItem::GroupCreator, QSet::insert(), hal::BaseTreeModel::mRootItem, hal::PinItem::Pin, hal::PinItem::PinCreator, hal::PinItem::PinGroup, hal::PinItem::setDirection(), hal::PinItem::setId(), hal::PinItem::setName(), and hal::PinItem::setType().
Referenced by hal::GateLibraryTabPin::update().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/pin_model/pin_model.h
/home/runner/work/hal/hal/plugins/gui/src/pin_model/pin_model.cpp