HAL: hal::GuiPluginDelegate Class Reference
hal::GuiPluginDelegate Class Reference
#include <gui_plugin_manager.h>
Signals
void buttonPressed (QModelIndex index)
Public Member Functions
GuiPluginDelegate (QObject *parent=nullptr)
~GuiPluginDelegate ()
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index) override
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const override
void updateQss (GuiPluginManager *gpm)
Public Member Functions inherited from QItemDelegate
QItemDelegate (QObject *parent)
virtual ~QItemDelegate ()
bool hasClipping () const const
void setClipping (bool clip)
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const const override
virtual void setEditorData (QWidget *editor, const QModelIndex &index) const const override
virtual void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const const override
virtual void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const const override
QItemEditorFactory * itemEditorFactory () const const
void setItemEditorFactory (QItemEditorFactory *factory)
Public Member Functions inherited from QAbstractItemDelegate
QAbstractItemDelegate (QObject *parent)
virtual ~QAbstractItemDelegate ()
virtual void destroyEditor (QWidget *editor, const QModelIndex &index) const const
virtual bool helpEvent (QHelpEvent *event, QAbstractItemView *view, const QStyleOptionViewItem &option, const QModelIndex &index)
void commitData (QWidget *editor)
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
void sizeHintChanged (const QModelIndex &index)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Friends
class GuiPluginManager
Additional Inherited Members
Public Types inherited from QAbstractItemDelegate
enum EndEditHint
Static Public Member Functions inherited from QAbstractItemDelegate
QString elidedText (const QFontMetrics &fontMetrics, int width, Qt::TextElideMode mode, const QString &text)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemDelegate
NoHint
EditNextItem
EditPreviousItem
SubmitModelCache
RevertModelCache
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QItemDelegate
virtual void drawDisplay (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect, const QString &text) const const
virtual void drawDecoration (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect, const QPixmap &pixmap) const const
virtual void drawFocus (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect) const const
virtual void drawCheck (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect, Qt::CheckState state) const const
void drawBackground (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const const
virtual bool eventFilter (QObject *editor, QEvent *event) override
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QItemDelegate
clipping
Properties inherited from QObject
objectName
Detailed Description
Definition at line 79 of file gui_plugin_manager.h.
Constructor & Destructor Documentation
GuiPluginDelegate()
hal::GuiPluginDelegate::GuiPluginDelegate (QObject * parent = nullptr)
Definition at line 833 of file gui_plugin_manager.cpp.
~GuiPluginDelegate()
hal::GuiPluginDelegate::~GuiPluginDelegate ()
Definition at line 854 of file gui_plugin_manager.cpp.
Member Function Documentation
buttonPressed
void hal::GuiPluginDelegate::buttonPressed (QModelIndex index) signal
Referenced by editorEvent(), and hal::GuiPluginManager::GuiPluginManager().
editorEvent()
bool hal::GuiPluginDelegate::editorEvent (QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) override virtual
Reimplemented from QItemDelegate.
Definition at line 926 of file gui_plugin_manager.cpp.
References buttonPressed(), QObject::event(), QEvent::MouseButtonPress, QEvent::MouseButtonRelease, QMouseEvent::pos(), QObject::Q_EMIT(), and QEvent::type().
paint()
void hal::GuiPluginDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override virtual
Reimplemented from QItemDelegate.
Definition at line 860 of file gui_plugin_manager.cpp.
References Qt::BackgroundRole, QStyle::CE_PushButton, QModelIndex::column(), hal::GuiPluginTable::data(), QStyle::drawControl(), QPainter::fillRect(), hal::gNetlist, hal::GuiPluginTable::hasCliExtension(), hal::GuiPluginTable::hasGuiExtension(), hal::GuiPluginTable::isHalGui(), hal::GuiPluginTable::isLoaded(), QModelIndex::isValid(), QColor::isValid(), QRect::left(), QModelIndex::model(), option(), Qt::red, QStyle::State_Enabled, QStyle::State_MouseOver, QStyle::State_Raised, QStyle::State_Sunken, QApplication::style(), QRect::top(), QVariant::value(), and QRect::width().
sizeHint()
QSize hal::GuiPluginDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const override virtual
Reimplemented from QItemDelegate.
Definition at line 921 of file gui_plugin_manager.cpp.
updateQss()
void hal::GuiPluginDelegate::updateQss (GuiPluginManager * gpm)
Definition at line 845 of file gui_plugin_manager.cpp.
References hal::GuiPluginManager::cliIconPath, hal::GuiPluginManager::cliIconStyle, hal::gui_utility::getStyledSvgIcon(), hal::GuiPluginManager::guiIconDisabledStyle, hal::GuiPluginManager::guiIconPath, hal::GuiPluginManager::guiIconStyle, hal::GuiPluginManager::loadIconPath, hal::GuiPluginManager::loadIconStyle, hal::GuiPluginManager::unloadIconPath, and hal::GuiPluginManager::unloadIconStyle.
Referenced by hal::GuiPluginManager::repolish().
Friends And Related Function Documentation
GuiPluginManager
friend class GuiPluginManager friend
Definition at line 82 of file gui_plugin_manager.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/plugin_relay/gui_plugin_manager.h
/home/runner/work/hal/hal/plugins/gui/src/plugin_relay/gui_plugin_manager.cpp