HAL: hal::CommonSuccessorPredecessor Class Reference
hal::CommonSuccessorPredecessor Class Reference
#include <common_successor_predecessor.h>
Public Member Functions
CommonSuccessorPredecessor (const QList< u32 > &gateIds, bool forw, int maxRound)
QSet< Gate * > result () const
Detailed Description
Definition at line 49 of file common_successor_predecessor.h.
Constructor & Destructor Documentation
CommonSuccessorPredecessor()
hal::CommonSuccessorPredecessor::CommonSuccessorPredecessor (const QList< u32 > & gateIds, bool forw, int maxRound)
Definition at line 46 of file common_successor_predecessor.cpp.
References test::g, hal::Netlist::get_gate_by_id(), hal::gNetlist, log_info, log_warning, hal::CommonSuccessorPredecessorGateQueue::mask(), and QList::size().
Member Function Documentation
result()
QSet< Gate * > hal::CommonSuccessorPredecessor::result () const
Definition at line 84 of file common_successor_predecessor.cpp.
References test::g, and QSet::insert().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/gui_utils/common_successor_predecessor.h
/home/runner/work/hal/hal/plugins/gui/src/gui_utils/common_successor_predecessor.cpp