HAL: hal::WaitToBeSeatedList Class Reference
hal::WaitToBeSeatedList Class Reference
HAL Gui » Graph Widget » Layouters
#include <wait_to_be_seated.h>
Public Member Functions
WaitToBeSeatedList ()
~WaitToBeSeatedList ()
void setLinks ()
const WaitToBeSeatedEntry * nextPlacement (const QPoint &pos)
const WaitToBeSeatedEntry * doPlacement (const QPoint &pos, WaitToBeSeatedEntry *wtse)
void add (WaitToBeSeatedEntry *wtse)
void dump () const
bool placementDone () const
Public Member Functions inherited from QList< WaitToBeSeatedEntry * >
QList ()
QList (const QList< T > &other)
QList (QList< T > &&other)
QList (std::initializer_list< T > args)
QList (InputIterator first, InputIterator last)
~QList ()
QList< T > & operator= (const QList< T > &other)
QList< T > & operator= (QList< T > &&other)
void swap (QList< T > &other)
void swap (int i, int j)
bool operator== (const QList< T > &other) const const
bool operator!= (const QList< T > &other) const const
int size () const const
bool isEmpty () const const
void clear ()
const T & at (int i) const const
const T & operator[] (int i) const const
T & operator[] (int i)
void reserve (int alloc)
void append (const T &value)
void append (const QList< T > &value)
void prepend (const T &value)
void insert (int i, const T &value)
QList::iterator insert (QList::iterator before, const T &value)
void replace (int i, const T &value)
void removeAt (int i)
int removeAll (const T &value)
bool removeOne (const T &value)
T takeAt (int i)
T takeFirst ()
T takeLast ()
void move (int from, int to)
void swapItemsAt (int i, int j)
int indexOf (const T &value, int from) const const
int lastIndexOf (const T &value, int from) const const
bool contains (const T &value) const const
int count (const T &value) const const
int count () const const
QList::iterator begin ()
QList::const_iterator begin () const const
QList::const_iterator cbegin () const const
QList::const_iterator constBegin () const const
QList::iterator end ()
QList::const_iterator end () const const
QList::const_iterator cend () const const
QList::const_iterator constEnd () const const
QList::reverse_iterator rbegin ()
QList::const_reverse_iterator rbegin () const const
QList::reverse_iterator rend ()
QList::const_reverse_iterator rend () const const
QList::const_reverse_iterator crbegin () const const
QList::const_reverse_iterator crend () const const
QList::iterator erase (QList::iterator pos)
QList::iterator erase (QList::iterator begin, QList::iterator end)
int length () const const
T & first ()
const T & first () const const
const T & constFirst () const const
T & last ()
const T & last () const const
const T & constLast () const const
void removeFirst ()
void removeLast ()
bool startsWith (const T &value) const const
bool endsWith (const T &value) const const
QList< T > mid (int pos, int length) const const
T value (int i) const const
T value (int i, const T &defaultValue) const const
void push_back (const T &value)
void push_front (const T &value)
T & front ()
const T & front () const const
T & back ()
const T & back () const const
void pop_front ()
void pop_back ()
bool empty () const const
QList< T > & operator+= (const QList< T > &other)
QList< T > & operator+= (const T &value)
QList< T > operator+ (const QList< T > &other) const const
QList< T > & operator<< (const T &value)
QList< T > & operator<< (const QList< T > &other)
QDataStream & operator<< (QDataStream &out, const QList< T > &list)
QVector< T > toVector () const const
QSet< T > toSet () const const
std::list< T > toStdList () const const
bool operator< (const QList< T > &lhs, const QList< T > &rhs)
bool operator<= (const QList< T > &lhs, const QList< T > &rhs)
bool operator> (const QList< T > &lhs, const QList< T > &rhs)
bool operator>= (const QList< T > &lhs, const QList< T > &rhs)
uint qHash (const QList< T > &key, uint seed)
QDataStream & operator>> (QDataStream &in, QList< T > &list)
Additional Inherited Members
Static Public Member Functions inherited from QList< WaitToBeSeatedEntry * >
QList< T > fromVector (const QVector< T > &vector)
QList< T > fromSet (const QSet< T > &set)
QList< T > fromStdList (const std::list< T > &list)
Public Attributes inherited from QList< WaitToBeSeatedEntry * >
typedef reverse_iterator
typedef const_reverse_iterator
typedef Iterator
typedef ConstIterator
typedef size_type
typedef value_type
typedef pointer
typedef const_pointer
typedef reference
typedef const_reference
typedef difference_type
Detailed Description
Definition at line 69 of file wait_to_be_seated.h.
Constructor & Destructor Documentation
WaitToBeSeatedList()
hal::WaitToBeSeatedList::WaitToBeSeatedList ()
Definition at line 107 of file wait_to_be_seated.cpp.
~WaitToBeSeatedList()
hal::WaitToBeSeatedList::~WaitToBeSeatedList ()
Definition at line 112 of file wait_to_be_seated.cpp.
Member Function Documentation
add()
void hal::WaitToBeSeatedList::add (WaitToBeSeatedEntry * wtse)
Definition at line 146 of file wait_to_be_seated.cpp.
References QList< WaitToBeSeatedEntry * >::append(), test_plugin::g, hal::Module::get_gates(), hal::Netlist::get_module_by_id(), hal::WaitToBeSeatedEntry::getId(), hal::gNetlist, and hal::WaitToBeSeatedEntry::isModule().
doPlacement()
const WaitToBeSeatedEntry * hal::WaitToBeSeatedList::doPlacement (const QPoint & pos, WaitToBeSeatedEntry * wtse)
Definition at line 208 of file wait_to_be_seated.cpp.
References QList::append().
Referenced by nextPlacement().
dump()
void hal::WaitToBeSeatedList::dump () const
Definition at line 222 of file wait_to_be_seated.cpp.
References hal::WaitToBeSeatedEntry::getId(), hal::WaitToBeSeatedEntry::isModule(), QTextStream::setFieldWidth(), hal::WaitToBeSeatedEntry::tagName(), and QIODevice::WriteOnly.
nextPlacement()
const WaitToBeSeatedEntry * hal::WaitToBeSeatedList::nextPlacement (const QPoint & pos)
Definition at line 164 of file wait_to_be_seated.cpp.
References doPlacement(), QList::isEmpty(), QMap::iterator::key(), placementDone(), QList::takeFirst(), QPoint::x(), and QPoint::y().
placementDone()
bool hal::WaitToBeSeatedList::placementDone () const inline
Definition at line 93 of file wait_to_be_seated.h.
References QSet::size(), and QList< WaitToBeSeatedEntry * >::size().
Referenced by nextPlacement().
setLinks()
void hal::WaitToBeSeatedList::setLinks ()
Definition at line 118 of file wait_to_be_seated.cpp.
References QList::append(), QList::begin(), hal::compareWaitToBeSeated(), QList::end(), QList< WaitToBeSeatedEntry * >::size(), and QList::size().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/wait_to_be_seated.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/wait_to_be_seated.cpp