HAL: hal::NetLayoutDirection Class Reference
hal::NetLayoutDirection Class Reference
HAL Gui » Graph Widget » Layouters
#include <net_layout_point.h>
Public Types
enum DirectionType {
Undefined = -1, Left = 0, Right = 1, Up = 2,
Down = 3, MaxDir = 4
}
Public Member Functions
NetLayoutDirection (DirectionType dir=Undefined)
NetLayoutDirection (int idir)
bool isHorizontal () const
int iHorizontal () const
bool isVertical () const
bool isNull () const
QPoint step (bool omitEndpoint=false) const
DirectionType direction () const
u32 toPattern () const
NetLayoutDirection operator++ (int)
NetLayoutDirection operator++ ()
int index () const
bool isLeft () const
bool isUp () const
bool isMax () const
bool operator== (const NetLayoutDirection &other) const
Detailed Description
Definition at line 47 of file net_layout_point.h.
Member Enumeration Documentation
DirectionType
enum hal::NetLayoutDirection::DirectionType
Enumerator
Undefined
Left
Right
Up
Down
MaxDir
Definition at line 50 of file net_layout_point.h.
Constructor & Destructor Documentation
NetLayoutDirection() [1/2]
hal::NetLayoutDirection::NetLayoutDirection (DirectionType dir = Undefined) inline
Definition at line 51 of file net_layout_point.h.
NetLayoutDirection() [2/2]
hal::NetLayoutDirection::NetLayoutDirection (int idir)
Definition at line 33 of file net_layout_point.cpp.
Member Function Documentation
direction()
DirectionType hal::NetLayoutDirection::direction () const inline
Definition at line 58 of file net_layout_point.h.
Referenced by hal::NetLayoutWire::NetLayoutWire().
iHorizontal()
int hal::NetLayoutDirection::iHorizontal () const inline
Definition at line 54 of file net_layout_point.h.
References index().
index()
int hal::NetLayoutDirection::index () const inline
Definition at line 62 of file net_layout_point.h.
Referenced by hal::NetLayoutJunctionNet::addEntry(), hal::NetLayoutJunctionRange::entryRange(), hal::NetLayoutJunctionEntries::id(), iHorizontal(), hal::NetLayoutJunctionNet::laneIndex(), and hal::NetLayoutWire::toString().
isHorizontal()
bool hal::NetLayoutDirection::isHorizontal () const inline
Definition at line 53 of file net_layout_point.h.
References Left, and Right.
Referenced by hal::NetLayoutWire::isHorizontal().
isLeft()
bool hal::NetLayoutDirection::isLeft () const inline
Definition at line 63 of file net_layout_point.h.
References Left.
isMax()
bool hal::NetLayoutDirection::isMax () const inline
Definition at line 65 of file net_layout_point.h.
References MaxDir.
Referenced by hal::NetLayoutJunctionEntries::dumpToFile(), hal::NetLayoutJunction::NetLayoutJunction(), hal::NetLayoutJunctionNet::NetLayoutJunctionNet(), hal::NetLayoutJunctionEntries::toString(), and hal::NetLayoutJunctionNet::toString().
isNull()
bool hal::NetLayoutDirection::isNull () const inline
Definition at line 56 of file net_layout_point.h.
References Undefined.
Referenced by hal::NetLayoutWire::graphicsFactory().
isUp()
bool hal::NetLayoutDirection::isUp () const inline
Definition at line 64 of file net_layout_point.h.
References Up.
isVertical()
bool hal::NetLayoutDirection::isVertical () const inline
Definition at line 55 of file net_layout_point.h.
References Down, and Up.
operator++() [1/2]
NetLayoutDirection hal::NetLayoutDirection::operator++ ()
Definition at line 50 of file net_layout_point.cpp.
operator++() [2/2]
NetLayoutDirection hal::NetLayoutDirection::operator++ (int)
Definition at line 43 of file net_layout_point.cpp.
operator==()
bool hal::NetLayoutDirection::operator== (const NetLayoutDirection & other) const inline
Definition at line 66 of file net_layout_point.h.
step()
QPoint hal::NetLayoutDirection::step (bool omitEndpoint = false) const
Definition at line 56 of file net_layout_point.cpp.
References Down, Left, Right, and Up.
Referenced by hal::NetLayoutWire::endPoint(), and hal::NetLayoutPoint::nextPoint().
toPattern()
u32 hal::NetLayoutDirection::toPattern () const inline
Definition at line 59 of file net_layout_point.h.
Referenced by hal::NetLayoutJunctionNet::addEntry().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/net_layout_point.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/net_layout_point.cpp