HAL: hal::VHDLParser Class Reference
hal::VHDLParser Class Reference
HAL Core » Netlist » Netlist Parser
#include <vhdl_parser.h>
Public Member Functions
VHDLParser ()=default
~VHDLParser ()=default
bool parse (const std::filesystem::path &file_path) override
std::unique_ptr< Netlist > instantiate (const GateLibrary *gate_library) override
Public Member Functions inherited from hal::NetlistParser
NetlistParser ()=default
virtual ~NetlistParser ()=default
std::unique_ptr< Netlist > parse_and_instantiate (const std::filesystem::path &file_path, const GateLibrary *gate_library)
Detailed Description
Definition at line 45 of file vhdl_parser.h.
Constructor & Destructor Documentation
VHDLParser()
hal::VHDLParser::VHDLParser () default
~VHDLParser()
hal::VHDLParser::~VHDLParser () default
Member Function Documentation
instantiate()
std::unique_ptr< Netlist > hal::VHDLParser::instantiate (const GateLibrary * gate_library) override virtual
Instantiate the parsed VHDL netlist using the specified gate library.
Parameters
[in] gate_library - The gate library.
Returns
A pointer to the resulting netlist.
Implements hal::NetlistParser.
Definition at line 169 of file vhdl_parser.cpp.
References hal::Net::add_source(), hal::Netlist::create_gate(), hal::Netlist::create_net(), hal::netlist_factory::create_netlist(), hal::Netlist::delete_net(), hal::Net::get_destinations(), hal::GateLibrary::get_gate_types(), hal::GateLibrary::get_gnd_gate_types(), hal::Netlist::get_gnd_gates(), hal::Net::get_name(), hal::Netlist::get_nets(), hal::Net::get_num_of_destinations(), hal::Net::get_num_of_sources(), hal::GateType::get_pins_of_direction(), hal::Netlist::get_unique_gate_id(), hal::GateLibrary::get_vcc_gate_types(), hal::Netlist::get_vcc_gates(), hal::Net::is_global_input_net(), hal::Net::is_global_output_net(), hal::Netlist::load_gate_locations_from_data(), log_error, hal::Netlist::mark_gnd_gate(), hal::Netlist::mark_vcc_gate(), hal::ShortestPath::net(), and hal::output.
parse()
bool hal::VHDLParser::parse (const std::filesystem::path & file_path) override virtual
Parse a VHDL netlist into an internal intermediate format.
Parameters
[in] file_path - Path to the VHDL netlist file.
Returns
True on success, false otherwise.
Implements hal::NetlistParser.
Definition at line 17 of file vhdl_parser.cpp.
References hal::TokenStream< T >::consume(), entity, hal::TokenStream< T >::extract_until(), and log_error.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/vhdl_parser/include/vhdl_parser/vhdl_parser.h
/home/runner/work/hal/hal/plugins/vhdl_parser/src/vhdl_parser.cpp