HAL: hal::SettingsItemDropdown Class Reference
hal::SettingsItemDropdown Class Reference
HAL Gui » Settings System
A SettingsItem that represents a dropdown menu.
#include <settings_item_dropdown.h>
Signals
void intChanged (int value)
Signals inherited from hal::SettingsItem
void valueChanged ()
Public Member Functions
SettingsItemDropdown (const QString &label, const QString &tag, int defVal, const QString &cat=QString(), const QString &desc=QString(), bool isGlobal=true)
virtual QVariant value () const override
virtual QVariant defaultValue () const override
virtual void setValue (const QVariant &v) override
virtual void setDefaultValue (const QVariant &dv) override
virtual SettingsWidget * editWidget (QWidget *parent=nullptr) override
virtual QVariant persistToSettings () const override
virtual void restoreFromSettings (const QVariant &val) override
const QStringList & valueNames () const
template<typename T >
void setValueNames ()
Public Member Functions inherited from hal::SettingsItem
SettingsItem (QObject *parent=nullptr)
virtual ~ SettingsItem ()
virtual bool isDefaultValue () const
virtual bool isGlobal () const
virtual QString label () const
virtual QString description () const
virtual QString tag () const
virtual QString category () const
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Attributes inherited from hal::SettingsItem
bool mIsGlobal
QString mLabel
QString mDescription
QString mTag
QString mCategory
Properties inherited from QObject
objectName
Detailed Description
A SettingsItem that represents a dropdown menu.
Definition at line 39 of file settings_item_dropdown.h.
Constructor & Destructor Documentation
SettingsItemDropdown()
hal::SettingsItemDropdown::SettingsItemDropdown (const QString & label, const QString & tag, int defVal, const QString & cat = QString(), const QString & desc = QString(), bool isGlobal = true)
The constructor.
Parameters
label - The label.
tag - The tag (key).
defVal - The default value.
cat - The category.
desc - The description.
isGlobal - The isGlobal flag.
Definition at line 8 of file settings_item_dropdown.cpp.
References hal::SettingsManager::instance(), hal::SettingsItem::isGlobal(), hal::SettingsItem::label(), hal::SettingsItem::mCategory, hal::SettingsItem::mDescription, hal::SettingsItem::mIsGlobal, hal::SettingsItem::mLabel, hal::SettingsItem::mTag, hal::SettingsManager::registerSetting(), and hal::SettingsItem::tag().
Member Function Documentation
defaultValue()
QVariant hal::SettingsItemDropdown::defaultValue () const override virtual
Get the default value.
Returns
The default value.
Implements hal::SettingsItem.
Definition at line 26 of file settings_item_dropdown.cpp.
editWidget()
SettingsWidget * hal::SettingsItemDropdown::editWidget (QWidget * parent = nullptr) override virtual
Get a corresponding SettingsWidget which holds a reference to the settings item.
Parameters
parent - The widget's soon to be parent.
Returns
A SettingsWidget able to modify the setting.
Implements hal::SettingsItem.
Definition at line 60 of file settings_item_dropdown.cpp.
References QObject::parent().
intChanged
void hal::SettingsItemDropdown::intChanged (int value) signal
Q_SIGNAL that is emitted when the value changes.
Parameters
value - The new value.
Referenced by hal::GraphContext::GraphContext(), hal::ContentManager::handleOpenDocument(), hal::PythonConsole::PythonConsole(), and setValue().
persistToSettings()
QVariant hal::SettingsItemDropdown::persistToSettings () const override virtual
Get the value of the item. See value().
Returns
The current value.
Reimplemented from hal::SettingsItem.
Definition at line 66 of file settings_item_dropdown.cpp.
References QList::at(), and QList::size().
restoreFromSettings()
void hal::SettingsItemDropdown::restoreFromSettings (const QVariant & val) override virtual
Sets the value of the settings to the given value.
Parameters
val - The value to set.
Reimplemented from hal::SettingsItem.
Definition at line 74 of file settings_item_dropdown.cpp.
References QString::isEmpty(), and QVariant::toString().
setDefaultValue()
void hal::SettingsItemDropdown::setDefaultValue (const QVariant & dv) override virtual
Sets the default value of the setting.
Parameters
dv - The default value.
Implements hal::SettingsItem.
Definition at line 31 of file settings_item_dropdown.cpp.
References QString::isEmpty(), setValue(), and QVariant::toString().
setValue()
void hal::SettingsItemDropdown::setValue (const QVariant & v) override virtual
Sets the value of the setting.
Parameters
v - The value to set.
Implements hal::SettingsItem.
Definition at line 47 of file settings_item_dropdown.cpp.
References intChanged(), QObject::Q_EMIT(), QVariant::toInt(), and hal::SettingsItem::valueChanged().
Referenced by setDefaultValue().
setValueNames()
template<typename T > void hal::SettingsItemDropdown::setValueNames () inline
Sets the values specified by the enumytype T.
Definition at line 79 of file settings_item_dropdown.h.
References QList::append(), QList::clear(), QMetaEnum::key(), and QMetaEnum::keyCount().
value()
QVariant hal::SettingsItemDropdown::value () const override virtual
Get the current value.
Returns
The current value.
Implements hal::SettingsItem.
Definition at line 21 of file settings_item_dropdown.cpp.
Referenced by hal::ContentManager::handleOpenDocument(), and hal::SettingsWidgetDropdown::SettingsWidgetDropdown().
valueNames()
const QStringList& hal::SettingsItemDropdown::valueNames () const inline
Get all values in the dropdown menu.
Returns
The values.
Definition at line 71 of file settings_item_dropdown.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/settings/settings_items/settings_item_dropdown.h
/home/runner/work/hal/hal/plugins/gui/src/settings/settings_items/settings_item_dropdown.cpp