HAL: hal::ActionReorderObject Class Reference
hal::ActionReorderObject Class Reference
HAL Gui » User Actions
Reorders an item within a container.
#include <action_reorder_object.h>
Public Member Functions
ActionReorderObject (const int newIndex=-1)
bool exec () override
QString tagname () const override
void writeToXml (QXmlStreamWriter &xmlOut) const override
void readFromXml (QXmlStreamReader &xmlIn) override
void addToHash (QCryptographicHash &cryptoHash) const override
Public Member Functions inherited from hal::UserAction
virtual ~UserAction ()
virtual UserActionObject object () const
virtual void setObject (const UserActionObject &obj)
virtual void setParentObject (const UserActionObject &obj)
virtual UserActionObject parentObject () const
int compoundOrder () const
void setCompoundOrder (int cmpord)
qint64 timeStamp () const
QString cryptographicHash (int recordNo) const
UserAction * undoAction () const
QString debugDump () const
void setObjectLock (bool lock)
void setParentObjectLock (bool lock)
bool hasProjectModified () const
Additional Inherited Members
Protected Member Functions inherited from hal::UserAction
UserAction ()
void writeParentObjectToXml (QXmlStreamWriter &xmlOut) const
void readParentObjectFromXml (QXmlStreamReader &xmlIn)
Static Protected Member Functions inherited from hal::UserAction
static QString setToText (const QSet< u32 > &set)
static QSet< u32 > setFromText (const QString &s)
Protected Attributes inherited from hal::UserAction
UserActionObject mObject
UserActionObject mParentObject
int mCompoundOrder
UserAction * mUndoAction
qint64 mTimeStamp
bool mObjectLock
bool mParentObjectLock
bool mProjectModified
Detailed Description
Reorders an item within a container.
Reorders an item (only pins are currently supported, pingroups are planned) to a new position. If the object's type is a pin or pingroup, the name is used to identify the object (configured by setPinOrPingroupIdentifier or correct Constructor). In this case, object's id is used to identify the corresponding module.
Definition at line 41 of file action_reorder_object.h.
Constructor & Destructor Documentation
ActionReorderObject()
hal::ActionReorderObject::ActionReorderObject (const int newIndex = -1)
Normal constructor (all purpose).
Parameters
newIndex - The new index.
Definition at line 20 of file action_reorder_object.cpp.
Referenced by exec().
Member Function Documentation
addToHash()
void hal::ActionReorderObject::addToHash (QCryptographicHash & cryptoHash) const override virtual
Overwritten user_action function.
Parameters
cryptoHash - The hash to add to.
Reimplemented from hal::UserAction.
Definition at line 114 of file action_reorder_object.cpp.
References QCryptographicHash::addData(), and QByteArray::number().
exec()
bool hal::ActionReorderObject::exec () override virtual
Overwritten user_action function.
Returns
True on success, False otherwise.
Reimplemented from hal::UserAction.
Definition at line 24 of file action_reorder_object.cpp.
References ActionReorderObject(), hal::UserAction::exec(), hal::BasePin< T >::get_group(), hal::Netlist::get_module_by_id(), hal::Module::get_pin_by_id(), hal::Module::get_pin_group_by_id(), hal::gNetlist, hal::UserActionObject::id(), hal::UserAction::mObject, hal::UserAction::mParentObject, hal::UserAction::mUndoAction, hal::UserActionObjectType::Pin, hal::UserActionObjectType::PinGroup, hal::UserAction::setObject(), hal::UserAction::setParentObject(), and hal::UserActionObject::type().
readFromXml()
void hal::ActionReorderObject::readFromXml (QXmlStreamReader & xmlIn) override virtual
Overwritten user_action function.
Parameters
xmlIn - The reader.
Reimplemented from hal::UserAction.
Definition at line 103 of file action_reorder_object.cpp.
References QXmlStreamReader::name(), QXmlStreamReader::readElementText(), QXmlStreamReader::readNextStartElement(), hal::UserAction::readParentObjectFromXml(), and QString::toInt().
tagname()
QString hal::ActionReorderObject::tagname () const override virtual
Overwritten user_action function.
Returns
The tag.
Implements hal::UserAction.
Definition at line 92 of file action_reorder_object.cpp.
References hal::ActionReorderObjectFactory::sFactory, and hal::UserActionFactory::tagname().
writeToXml()
void hal::ActionReorderObject::writeToXml (QXmlStreamWriter & xmlOut) const override virtual
Overwritten user_action function.
Parameters
xmlOut - The writer.
Reimplemented from hal::UserAction.
Definition at line 97 of file action_reorder_object.cpp.
References QString::number(), hal::UserAction::writeParentObjectToXml(), and QXmlStreamWriter::writeTextElement().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/action_reorder_object.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/action_reorder_object.cpp