HAL: hal::NetLayoutJunction Class Reference
hal::NetLayoutJunction Class Reference
HAL Gui » Graph Widget » Layouters
#include <net_layout_junction.h>
Public Types
enum mErrorT { StraightRouteError = -2, CornerRouteError = -1, Ok = 0 }
Public Member Functions
NetLayoutJunction (const NetLayoutJunctionEntries &entries)
~NetLayoutJunction ()
QRect rect () const
void dump () const
NetLayoutJunctionNet netById (u32 id) const
mErrorT lastError () const
Detailed Description
Definition at line 176 of file net_layout_junction.h.
Member Enumeration Documentation
mErrorT
enum hal::NetLayoutJunction::mErrorT
Enumerator
StraightRouteError
CornerRouteError
Ok
Definition at line 184 of file net_layout_junction.h.
Constructor & Destructor Documentation
NetLayoutJunction()
hal::NetLayoutJunction::NetLayoutJunction (const NetLayoutJunctionEntries & entries)
Definition at line 22 of file net_layout_junction.cpp.
References hal::NetLayoutJunctionEntries::id(), hal::NetLayoutDirection::isMax(), and hal::NetLayoutJunctionEntries::size().
~NetLayoutJunction()
hal::NetLayoutJunction::~NetLayoutJunction () inline
Definition at line 180 of file net_layout_junction.h.
Member Function Documentation
dump()
void hal::NetLayoutJunction::dump () const
Definition at line 225 of file net_layout_junction.cpp.
References hal::NetLayoutJunctionEntries::dump().
lastError()
mErrorT hal::NetLayoutJunction::lastError () const inline
Definition at line 185 of file net_layout_junction.h.
netById()
NetLayoutJunctionNet hal::NetLayoutJunction::netById (u32 id) const inline
Definition at line 183 of file net_layout_junction.h.
rect()
QRect hal::NetLayoutJunction::rect () const inline
Definition at line 181 of file net_layout_junction.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/net_layout_junction.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/net_layout_junction.cpp