HAL: hal::ModulePinsTreeItem Class Reference
hal::ModulePinsTreeItem Class Reference
#include <module_pins_tree_model.h>
Public Types
enum Type { None , Pin , Group }
Public Member Functions
ModulePinsTreeItem (Type itype, u32 id_, QString pinName, PinDirection dir, PinType ptype, int inx, QString netName=QString())
ModulePinsTreeItem ()
QVariant getData (int column) const override
void setData (QList< QVariant > data) override
void setDataAtColumn (int column, QVariant &data) override
void appendData (QVariant data) override
int getColumnCount () const override
void setItemType (Type tp)
Type itemType () const
QString name () const
void setName (const QString &nam)
void setPinType (PinType ptype)
void setPinDirection (PinDirection dir)
void setIndex (int inx)
u32 id () const
Public Member Functions inherited from hal::BaseTreeItem
BaseTreeItem ()
BaseTreeItem (QList< QVariant > columnData)
virtual ~BaseTreeItem ()
virtual BaseTreeItem * getParent () const
virtual void setParent (BaseTreeItem *parent)
virtual BaseTreeItem * getChild (int row) const
virtual QList< BaseTreeItem * > getChildren () const
virtual void appendChild (BaseTreeItem *child)
virtual void insertChild (int index, BaseTreeItem *child)
virtual BaseTreeItem * removeChildAtPos (int row)
virtual bool removeChild (BaseTreeItem *child)
virtual int getChildCount () const
virtual int getRowForChild (const BaseTreeItem *child) const
virtual int getOwnRow ()
Additional Inherited Members
Protected Attributes inherited from hal::BaseTreeItem
BaseTreeItem * mParent
QList< BaseTreeItem * > mChildren
Detailed Description
Definition at line 41 of file module_pins_tree_model.h.
Member Enumeration Documentation
Type
enum hal::ModulePinsTreeItem::Type
Enumerator
None
Pin
Group
Definition at line 44 of file module_pins_tree_model.h.
Constructor & Destructor Documentation
ModulePinsTreeItem() [1/2]
hal::ModulePinsTreeItem::ModulePinsTreeItem (Type itype, u32 id_, QString pinName, PinDirection dir, PinType ptype, int inx, QString netName = QString())
Definition at line 18 of file module_pins_tree_model.cpp.
ModulePinsTreeItem() [2/2]
hal::ModulePinsTreeItem::ModulePinsTreeItem () inline
Definition at line 58 of file module_pins_tree_model.h.
Member Function Documentation
appendData()
void hal::ModulePinsTreeItem::appendData (QVariant data) override virtual
Appends a new column to the item.
Parameters
data - The data of the new column.
Implements hal::BaseTreeItem.
Definition at line 74 of file module_pins_tree_model.cpp.
References hal::data.
getColumnCount()
int hal::ModulePinsTreeItem::getColumnCount () const override virtual
Get the number of currently stored column data.
Returns
The column count.
Implements hal::BaseTreeItem.
Definition at line 79 of file module_pins_tree_model.cpp.
getData()
QVariant hal::ModulePinsTreeItem::getData (int column) const override virtual
Get the data of a specific column (most in the form of a string).
Parameters
column - The requested column.
Returns
The data if within the column count. Empty QVariant otherwise.
Implements hal::BaseTreeItem.
Definition at line 22 of file module_pins_tree_model.cpp.
References hal::enum_to_string(), QString::fromStdString(), and Group.
Referenced by hal::ModulePinsTree::handleContextMenuRequested().
id()
u32 hal::ModulePinsTreeItem::id () const inline
Returns the pin-id if the item represents a pin or the pingroup-id if the item represents a pingroup.
Parameters
item - The item.
Returns
The pin- or pingroup-id.
Definition at line 79 of file module_pins_tree_model.h.
Referenced by hal::ModulePinsTreeModel::getNetFromItem(), hal::ModulePinsTree::handleContextMenuRequested(), hal::ModulePinsTreeModel::handleModulePortsChanged(), and hal::ModulePinsTreeModel::mimeData().
itemType()
Type hal::ModulePinsTreeItem::itemType () const inline
Definition at line 65 of file module_pins_tree_model.h.
Referenced by hal::ModulePinsTreeModel::dropMimeData(), hal::ModulePinsTreeModel::getNetFromItem(), hal::ModulePinsTree::handleContextMenuRequested(), and hal::ModulePinsTreeModel::mimeData().
name()
QString hal::ModulePinsTreeItem::name () const inline
Definition at line 66 of file module_pins_tree_model.h.
setData()
void hal::ModulePinsTreeItem::setData (QList< QVariant > data) override virtual
Sets the data for all columns.
Parameters
data - Each entry in the list represents one column.
Implements hal::BaseTreeItem.
Definition at line 42 of file module_pins_tree_model.cpp.
References hal::data.
setDataAtColumn()
void hal::ModulePinsTreeItem::setDataAtColumn (int column, QVariant & data) override virtual
Sets the data for a specified column. The index must be within already existing boundaries (for example, add dummy data beforehand).
Parameters
index - The column to set the new data.
data - The new column data.
Implements hal::BaseTreeItem.
Definition at line 52 of file module_pins_tree_model.cpp.
References hal::data.
setIndex()
void hal::ModulePinsTreeItem::setIndex (int inx) inline
Definition at line 70 of file module_pins_tree_model.h.
setItemType()
void hal::ModulePinsTreeItem::setItemType (Type tp) inline
Definition at line 64 of file module_pins_tree_model.h.
setName()
void hal::ModulePinsTreeItem::setName (const QString & nam) inline
Definition at line 67 of file module_pins_tree_model.h.
Referenced by hal::ModulePinsTreeModel::handleModulePortsChanged().
setPinDirection()
void hal::ModulePinsTreeItem::setPinDirection (PinDirection dir) inline
Definition at line 69 of file module_pins_tree_model.h.
Referenced by hal::ModulePinsTreeModel::handleModulePortsChanged().
setPinType()
void hal::ModulePinsTreeItem::setPinType (PinType ptype) inline
Definition at line 68 of file module_pins_tree_model.h.
Referenced by hal::ModulePinsTreeModel::handleModulePortsChanged().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/module_details_widget/module_pins_tree_model.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/module_details_widget/module_pins_tree_model.cpp