HAL: hal::PlacementHint Class Reference
hal::PlacementHint Class Reference
The PlacementHint class object provides hints for the layouter how new box objects are placed on a view. In standard mode placement is done using the most compact squere-like arrangement. Alternatively new box objects can be placed to the left or right to a node which serves as 'origin'.
#include <gui_def.h>
Public Types
enum PlacementModeType { Standard = 0 , PreferLeft = 1 , PreferRight = 2 , GridPosition = 3 }
The PlacementModeType enum either most compact arrangement (Standard) or to the left or right of given origin.
Public Member Functions
PlacementHint (PlacementModeType mod=Standard, const Node &orign=Node())
PlacementHint standard constructor.
PlacementHint (const GridPlacement &gridPlc)
PlacementHint constructor for grid placement.
PlacementModeType mode () const
mode getter for placement mode type
Node preferredOrigin () const
preferredOrigin getter for placement origin if any.
bool operator< (const PlacementHint &rhs) const
operator < provide an order structure for placement hints
bool operator== (const PlacementHint &rhs) const
operator == test whether two placement hints are equal
void addGridPosition (const Node &nd, const QPoint &p)
const QHash< Node, QPoint > & gridPosition () const
Detailed Description
The PlacementHint class object provides hints for the layouter how new box objects are placed on a view. In standard mode placement is done using the most compact squere-like arrangement. Alternatively new box objects can be placed to the left or right to a node which serves as 'origin'.
Definition at line 210 of file gui_def.h.
Member Enumeration Documentation
PlacementModeType
enum hal::PlacementHint::PlacementModeType
The PlacementModeType enum either most compact arrangement (Standard) or to the left or right of given origin.
Enumerator
Standard
PreferLeft
PreferRight
GridPosition
Definition at line 217 of file gui_def.h.
Constructor & Destructor Documentation
PlacementHint() [1/2]
hal::PlacementHint::PlacementHint (PlacementModeType mod = Standard, const Node & orign = Node()) inline
PlacementHint standard constructor.
Parameters
mod placement mode must be either Standard or PreferLeft or PreferRight
orign node to start from when PreferLeft or PreferRight are set
Definition at line 224 of file gui_def.h.
PlacementHint() [2/2]
hal::PlacementHint::PlacementHint (const GridPlacement & gridPlc) inline
PlacementHint constructor for grid placement.
Parameters
gridPlc Hash node to position
Definition at line 231 of file gui_def.h.
Member Function Documentation
addGridPosition()
void hal::PlacementHint::addGridPosition (const Node & nd, const QPoint & p) inline
Assigns a given node the given position. Stores it internally.
Parameters
nd - The node.
p - The position
Definition at line 278 of file gui_def.h.
References QHash::insert().
Referenced by hal::ActionFoldModule::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionUnfoldModule::exec(), hal::GraphContextManager::openNetEndpointsInView(), and hal::GraphContext::unfoldModule().
gridPosition()
const QHash<Node,QPoint>& hal::PlacementHint::gridPosition () const inline
Get the data structure containing the node - position assignments.
Returns
The QHash that maps nodes to positions.
Definition at line 288 of file gui_def.h.
Referenced by hal::StandardGraphLayouter::add(), and hal::ActionAddItemsToObject::writeToXml().
mode()
PlacementModeType hal::PlacementHint::mode () const inline
mode getter for placement mode type
Returns
either Standard or PreferLeft or PreferRight
Definition at line 238 of file gui_def.h.
Referenced by hal::GraphContext::add(), hal::StandardGraphLayouter::add(), hal::GraphContext::unfoldModule(), and hal::ActionAddItemsToObject::writeToXml().
operator<()
bool hal::PlacementHint::operator< (const PlacementHint & rhs) const inline
operator < provide an order structure for placement hints
Parameters
rhs the other placement hint to compare with
Returns
true if placement hint is 'smaller' according to test
Definition at line 253 of file gui_def.h.
operator==()
bool hal::PlacementHint::operator== (const PlacementHint & rhs) const inline
operator == test whether two placement hints are equal
Parameters
rhs the other placement hint to compare with
Returns
true if placement hints have same placement mode type and origin
Definition at line 267 of file gui_def.h.
preferredOrigin()
Node hal::PlacementHint::preferredOrigin () const inline
preferredOrigin getter for placement origin if any.
Returns
the Node object
It can be tested by preferredOrigin().isNull if no origin has been set.
Definition at line 246 of file gui_def.h.
Referenced by hal::StandardGraphLayouter::add(), and hal::ActionAddItemsToObject::writeToXml().
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/plugins/gui/include/gui/gui_def.h