HAL: hal::ModuleItem Class Reference
hal::ModuleItem Class Reference
HAL Gui
An item in the ModuleModel.
#include <module_item.h>
Public Types
enum TreeItemType { TreeItemType::Module, TreeItemType::Gate, TreeItemType::Net }
Public Member Functions
void setData (QList< QVariant > data) override
void setDataAtIndex (int index, QVariant &data) override
void appendData (QVariant data) override
int getColumnCount () const override
ModuleItem (const u32 id, const TreeItemType type=TreeItemType::Module)
void appendExistingChildIfAny (const QMap< u32, ModuleItem * > &moduleMap)
QVariant getData (int column) const override
int row () const
QString name () const
u32 id () const
bool highlighted () const
bool isToplevelItem () const
TreeItemType getType () const
void setName (const QString &name)
void setModuleType (const QString &moduleType)
void setHighlighted (const bool highlighted)
Public Member Functions inherited from hal::BaseTreeItem
BaseTreeItem ()
BaseTreeItem (QList< QVariant > columnData)
virtual ~BaseTreeItem ()
virtual BaseTreeItem * getParent () const
virtual void setParent (BaseTreeItem *parent)
virtual BaseTreeItem * getChild (int row) const
virtual QList< BaseTreeItem * > getChildren () const
virtual void appendChild (BaseTreeItem *child)
virtual void insertChild (int index, BaseTreeItem *child)
virtual BaseTreeItem * removeChildAtPos (int row)
virtual bool removeChild (BaseTreeItem *child)
virtual int getChildCount () const
virtual int getRowForChild (const BaseTreeItem *child) const
virtual int getOwnRow ()
Additional Inherited Members
Protected Attributes inherited from hal::BaseTreeItem
BaseTreeItem * mParent
QList< BaseTreeItem * > mChildren
Detailed Description
An item in the ModuleModel.
The ModuleItem is one item in the ModuleModel item model. It represents either a module, a gate or a net of the netlist.
Definition at line 45 of file module_item.h.
Member Enumeration Documentation
TreeItemType
enum hal::ModuleItem::TreeItemType strong
The possible types that a ModuleItem in the ModuleModel can have.
Enumerator
Module
Gate
Net
Definition at line 51 of file module_item.h.
Constructor & Destructor Documentation
ModuleItem()
hal::ModuleItem::ModuleItem (const u32 id, const TreeItemType type = TreeItemType::Module)
Constructor.
Parameters
id - The id of the netlist item this ModuleItem represents
type - The type of the netlist item
Definition at line 11 of file module_item.cpp.
References QString::fromStdString(), test_plugin::g, Gate, hal::Netlist::get_gate_by_id(), hal::Netlist::get_module_by_id(), hal::Module::get_name(), hal::Netlist::get_net_by_id(), hal::Module::get_type(), hal::gNetlist, Module, test::n, Net, and type.
Member Function Documentation
appendData()
void hal::ModuleItem::appendData (QVariant data) override virtual
Appends a new column to the item.
Parameters
data - The data of the new column.
Implements hal::BaseTreeItem.
Definition at line 156 of file module_item.cpp.
References hal::data.
appendExistingChildIfAny()
void hal::ModuleItem::appendExistingChildIfAny (const QMap< u32, ModuleItem * > & moduleMap)
Given a set of ModuleItems (in a map [id]->[ModuleItem]) this function adds each ModuleItem of this set as a new children if its underlying module is a submodule (child) of the underlying module of this ModuleItem.
Parameters
moduleMap - A map [id]->[ModuleItem] of children candidates
Definition at line 53 of file module_item.cpp.
References hal::BaseTreeItem::appendChild(), QMap::constEnd(), QMap::find(), hal::Netlist::get_module_by_id(), hal::Module::get_submodules(), hal::gNetlist, Module, and hal::BaseTreeItem::setParent().
getColumnCount()
int hal::ModuleItem::getColumnCount () const override virtual
Get the number of currently stored column data.
Returns
The column count.
Implements hal::BaseTreeItem.
Definition at line 151 of file module_item.cpp.
getData()
QVariant hal::ModuleItem::getData (int column) const override virtual
Gets the data of this item model item i.e. the name of this ModuleItem if column=1.
Parameters
column - The column to get the data for
Returns
the data in the specified column of this ModuleItem
Implements hal::BaseTreeItem.
Definition at line 81 of file module_item.cpp.
Referenced by hal::ModuleModel::data().
getType()
ModuleItem::TreeItemType hal::ModuleItem::getType () const
Gets the type of the netlist item this ModuleItem represents.
Returns
the ModuleItem type
Definition at line 137 of file module_item.cpp.
Referenced by hal::ModuleModel::data(), hal::ModuleWidget::handleCurrentChanged(), hal::ModuleWidget::handleItemDoubleClicked(), hal::ModuleWidget::handleTreeSelectionChanged(), hal::ModuleWidget::handleTreeViewContextMenuRequested(), and hal::ModuleProxyModel::lessThan().
highlighted()
bool hal::ModuleItem::highlighted () const
Checks if this ModuleItem is currently highlighted.
Returns
true if this ModuleItem is currently highlighted.
Definition at line 126 of file module_item.cpp.
Referenced by hal::ModuleModel::data(), and setHighlighted().
id()
u32 hal::ModuleItem::id () const
Gets the id of the netlist item this ModuleItem represents.
Returns
the module id
Definition at line 121 of file module_item.cpp.
Referenced by hal::ModuleModel::data(), hal::ModuleWidget::handleTreeSelectionChanged(), hal::ModuleWidget::handleTreeViewContextMenuRequested(), hal::ModuleModel::moduleAssignGate(), hal::ModuleModel::updateModuleParent(), and hal::ModuleModel::updateNetParent().
isToplevelItem()
bool hal::ModuleItem::isToplevelItem () const
Checks if this ModuleItem is direct child to mRootItem
Returns
Definition at line 131 of file module_item.cpp.
References hal::BaseTreeItem::mParent.
Referenced by hal::ModuleModel::moduleAssignGate(), and hal::ModuleModel::updateModuleParent().
name()
QString hal::ModuleItem::name () const
Gets the name of the netlist item this ModuleItem represents.
Returns
the netlist items name
Definition at line 116 of file module_item.cpp.
Referenced by setName().
row()
int hal::ModuleItem::row () const
Gets the index of this ModuleItem in the list of children ModuleItems of its parent.
Returns
the index in the parents ModuleItem children list
Definition at line 45 of file module_item.cpp.
References hal::BaseTreeItem::getParent(), and hal::BaseTreeItem::getRowForChild().
Referenced by hal::ModuleModel::updateModuleParent().
setData()
void hal::ModuleItem::setData (QList< QVariant > data) override virtual
Sets the data for all columns.
Parameters
data - Each entry in the list represents one column.
Implements hal::BaseTreeItem.
Definition at line 95 of file module_item.cpp.
References hal::data, Module, setModuleType(), and setName().
setDataAtIndex()
void hal::ModuleItem::setDataAtIndex (int index, QVariant & data) override virtual
Sets the data for a specified column. The index must be within already existing boundaries (for example, add dummy data beforehand).
Parameters
index - The column to set the new data.
data - The new column data.
Implements hal::BaseTreeItem.
Definition at line 102 of file module_item.cpp.
References hal::data, setModuleType(), and setName().
setHighlighted()
void hal::ModuleItem::setHighlighted (const bool highlighted)
Marks/Unmarks this ModuleItem as highlighted.
Parameters
highlighted - true if the ModuleItem should be marked as highlighted. false if the ModuleItem should be marked as NOT highlighted.
Definition at line 146 of file module_item.cpp.
References highlighted().
setModuleType()
void hal::ModuleItem::setModuleType (const QString & moduleType)
Set the module type name (gate types are immutable)
Parameters
moduleType
Definition at line 72 of file module_item.cpp.
References hal::Netlist::get_module_by_id(), hal::gNetlist, Module, hal::ShortestPath::module(), hal::Module::set_type(), and QString::toStdString().
Referenced by setData(), and setDataAtIndex().
setName()
void hal::ModuleItem::setName (const QString & name)
Sets the name of this ModuleItem (not the underlying module).
Parameters
name - The new name
Definition at line 141 of file module_item.cpp.
References name().
Referenced by setData(), setDataAtIndex(), hal::ModuleModel::updateGateName(), hal::ModuleModel::updateModuleName(), and hal::ModuleModel::updateNetName().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/module_model/module_item.h
/home/runner/work/hal/hal/plugins/gui/src/module_model/module_item.cpp