HAL: hal::CircleSeparatedNet Class Reference
hal::CircleSeparatedNet Class Reference
HAL Gui » Graph Widget » Visuals » Graphics Net
Used to display all nets which destinations are not in the current view.
#include <circle_separated_net.h>
Public Member Functions
CircleSeparatedNet (Net *n)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override
void addInput (const QPointF &scene_position) override
void addOutput (const QPointF &scene_position) override
qreal inputWidth () const override
qreal outputWidth () const override
Public Member Functions inherited from hal::SeparatedGraphicsNet
SeparatedGraphicsNet (Net *n)
virtual void finalize ()
Public Member Functions inherited from hal::GraphicsNet
GraphicsNet (Net *n)
QRectF boundingRect () const override
QPainterPath shape () const override
virtual void setVisuals (const Visuals &v)
Public Member Functions inherited from hal::GraphicsItem
GraphicsItem (const ItemType type, const u32 id)
ItemType itemType () const
u32 id () const
void setHightlight (bool hl)
Public Member Functions inherited from QGraphicsItem
QGraphicsItem (QGraphicsItem *parent)
virtual ~QGraphicsItem ()
QGraphicsScene * scene () const const
QGraphicsItem * parentItem () const const
QGraphicsItem * topLevelItem () const const
QGraphicsObject * parentObject () const const
QGraphicsWidget * parentWidget () const const
QGraphicsWidget * topLevelWidget () const const
QGraphicsWidget * window () const const
QGraphicsItem * panel () const const
void setParentItem (QGraphicsItem *newParent)
QList< QGraphicsItem * > children () const const
QList< QGraphicsItem * > childItems () const const
bool isWidget () const const
bool isWindow () const const
bool isPanel () const const
QGraphicsObject * toGraphicsObject ()
const QGraphicsObject * toGraphicsObject () const const
QGraphicsItemGroup * group () const const
void setGroup (QGraphicsItemGroup *group)
QGraphicsItem::GraphicsItemFlags flags () const const
void setFlag (QGraphicsItem::GraphicsItemFlag flag, bool enabled)
void setFlags (QGraphicsItem::GraphicsItemFlags flags)
QGraphicsItem::CacheMode cacheMode () const const
void setCacheMode (QGraphicsItem::CacheMode mode, const QSize &logicalCacheSize)
QGraphicsItem::PanelModality panelModality () const const
void setPanelModality (QGraphicsItem::PanelModality panelModality)
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel) const const
QString toolTip () const const
void setToolTip (const QString &toolTip)
QCursor cursor () const const
void setCursor (const QCursor &cursor)
bool hasCursor () const const
void unsetCursor ()
bool isVisible () const const
bool isVisibleTo (const QGraphicsItem *parent) const const
void setVisible (bool visible)
void hide ()
void show ()
bool isEnabled () const const
void setEnabled (bool enabled)
bool isSelected () const const
void setSelected (bool selected)
bool acceptDrops () const const
void setAcceptDrops (bool on)
qreal opacity () const const
qreal effectiveOpacity () const const
void setOpacity (qreal opacity)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
Qt::MouseButtons acceptedMouseButtons () const const
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
bool acceptsHoverEvents () const const
void setAcceptsHoverEvents (bool enabled)
bool acceptHoverEvents () const const
void setAcceptHoverEvents (bool enabled)
bool acceptTouchEvents () const const
void setAcceptTouchEvents (bool enabled)
bool filtersChildEvents () const const
void setFiltersChildEvents (bool enabled)
bool handlesChildEvents () const const
void setHandlesChildEvents (bool enabled)
bool isActive () const const
void setActive (bool active)
bool hasFocus () const const
void setFocus (Qt::FocusReason focusReason)
void clearFocus ()
QGraphicsItem * focusProxy () const const
void setFocusProxy (QGraphicsItem *item)
QGraphicsItem * focusItem () const const
void grabMouse ()
void ungrabMouse ()
void grabKeyboard ()
void ungrabKeyboard ()
QPointF pos () const const
qreal x () const const
void setX (qreal x)
qreal y () const const
void setY (qreal y)
QPointF scenePos () const const
void setPos (const QPointF &pos)
void setPos (qreal x, qreal y)
void moveBy (qreal dx, qreal dy)
void ensureVisible (const QRectF &rect, int xmargin, int ymargin)
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin, int ymargin)
QMatrix matrix () const const
QMatrix sceneMatrix () const const
void setMatrix (const QMatrix &matrix, bool combine)
void resetMatrix ()
QTransform transform () const const
QTransform sceneTransform () const const
QTransform deviceTransform (const QTransform &viewportTransform) const const
QTransform itemTransform (const QGraphicsItem *other, bool *ok) const const
void setTransform (const QTransform &matrix, bool combine)
void resetTransform ()
void rotate (qreal angle)
void scale (qreal sx, qreal sy)
void shear (qreal sh, qreal sv)
void translate (qreal dx, qreal dy)
void setRotation (qreal angle)
qreal rotation () const const
void setScale (qreal factor)
qreal scale () const const
QList< QGraphicsTransform * > transformations () const const
void setTransformations (const QList< QGraphicsTransform * > &transformations)
QPointF transformOriginPoint () const const
void setTransformOriginPoint (const QPointF &origin)
void setTransformOriginPoint (qreal x, qreal y)
virtual void advance (int phase)
qreal zValue () const const
void setZValue (qreal z)
void stackBefore (const QGraphicsItem *sibling)
QRectF childrenBoundingRect () const const
QRectF sceneBoundingRect () const const
bool isClipped () const const
QPainterPath clipPath () const const
virtual bool contains (const QPointF &point) const const
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode) const const
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode) const const
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode) const const
bool isObscured (const QRectF &rect) const const
bool isObscured (qreal x, qreal y, qreal w, qreal h) const const
virtual bool isObscuredBy (const QGraphicsItem *item) const const
virtual QPainterPath opaqueArea () const const
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const const
qreal boundingRegionGranularity () const const
void setBoundingRegionGranularity (qreal granularity)
void update (const QRectF &rect)
void update (qreal x, qreal y, qreal width, qreal height)
void scroll (qreal dx, qreal dy, const QRectF &rect)
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const const
QPointF mapToParent (const QPointF &point) const const
QPointF mapToScene (const QPointF &point) const const
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const const
QPolygonF mapToParent (const QRectF &rect) const const
QPolygonF mapToScene (const QRectF &rect) const const
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const const
QRectF mapRectToParent (const QRectF &rect) const const
QRectF mapRectToScene (const QRectF &rect) const const
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const const
QPolygonF mapToParent (const QPolygonF &polygon) const const
QPolygonF mapToScene (const QPolygonF &polygon) const const
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const const
QPainterPath mapToParent (const QPainterPath &path) const const
QPainterPath mapToScene (const QPainterPath &path) const const
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const const
QPointF mapFromParent (const QPointF &point) const const
QPointF mapFromScene (const QPointF &point) const const
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const const
QPolygonF mapFromParent (const QRectF &rect) const const
QPolygonF mapFromScene (const QRectF &rect) const const
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const const
QRectF mapRectFromParent (const QRectF &rect) const const
QRectF mapRectFromScene (const QRectF &rect) const const
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const const
QPolygonF mapFromParent (const QPolygonF &polygon) const const
QPolygonF mapFromScene (const QPolygonF &polygon) const const
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const const
QPainterPath mapFromParent (const QPainterPath &path) const const
QPainterPath mapFromScene (const QPainterPath &path) const const
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const const
QPointF mapToParent (qreal x, qreal y) const const
QPointF mapToScene (qreal x, qreal y) const const
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const const
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const const
QPointF mapFromParent (qreal x, qreal y) const const
QPointF mapFromScene (qreal x, qreal y) const const
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const const
bool isAncestorOf (const QGraphicsItem *child) const const
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const const
bool isUnderMouse () const const
QVariant data (int key) const const
void setData (int key, const QVariant &value)
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
virtual int type () const const
void installSceneEventFilter (QGraphicsItem *filterItem)
void removeSceneEventFilter (QGraphicsItem *filterItem)
T qgraphicsitem_cast (QGraphicsItem *item)
Static Public Member Functions
static void loadSettings ()
Static Public Member Functions inherited from hal::SeparatedGraphicsNet
static void updateAlpha ()
Static Public Member Functions inherited from hal::GraphicsNet
static void loadSettings ()
Static Public Member Functions inherited from hal::GraphicsItem
static void loadSettings ()
static void setLod (const qreal lod)
Additional Inherited Members
Public Types inherited from QGraphicsItem
enum GraphicsItemFlag
enum GraphicsItemChange
enum CacheMode
enum PanelModality
enum anonymous
Public Attributes inherited from QGraphicsItem
typedef GraphicsItemFlags
ItemIsMovable
ItemIsSelectable
ItemIsFocusable
ItemClipsToShape
ItemClipsChildrenToShape
ItemIgnoresTransformations
ItemIgnoresParentOpacity
ItemDoesntPropagateOpacityToChildren
ItemStacksBehindParent
ItemUsesExtendedStyleOption
ItemHasNoContents
ItemSendsGeometryChanges
ItemAcceptsInputMethod
ItemNegativeZStacksBehindParent
ItemIsPanel
ItemIsFocusScope
ItemSendsScenePositionChanges
ItemStopsClickFocusPropagation
ItemStopsFocusHandling
ItemContainsChildrenInShape
ItemPositionChange
ItemMatrixChange
ItemVisibleChange
ItemEnabledChange
ItemSelectedChange
ItemParentChange
ItemChildAddedChange
ItemChildRemovedChange
ItemTransformChange
ItemPositionHasChanged
ItemTransformHasChanged
ItemSceneChange
ItemVisibleHasChanged
ItemEnabledHasChanged
ItemSelectedHasChanged
ItemParentHasChanged
ItemSceneHasChanged
ItemCursorChange
ItemCursorHasChanged
ItemToolTipChange
ItemToolTipHasChanged
ItemFlagsChange
ItemFlagsHaveChanged
ItemZValueChange
ItemZValueHasChanged
ItemOpacityChange
ItemOpacityHasChanged
ItemScenePositionHasChanged
ItemRotationChange
ItemRotationHasChanged
ItemScaleChange
ItemScaleHasChanged
ItemTransformOriginPointChange
ItemTransformOriginPointHasChanged
NoCache
ItemCoordinateCache
DeviceCoordinateCache
NonModal
PanelModal
SceneModal
Type
UserType
Protected Member Functions inherited from hal::GraphicsItem
QColor penColor (QStyle::State state, const QColor &colorHint=QColor()) const
QColor selectionColor () const
QColor groupingColor () const
Protected Member Functions inherited from QGraphicsItem
void updateMicroFocus ()
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
virtual bool sceneEvent (QEvent *event)
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
virtual void inputMethodEvent (QInputMethodEvent *event)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
virtual QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
void prepareGeometryChange ()
Protected Attributes inherited from hal::SeparatedGraphicsNet
QVector< QPointF > mInputPositions
QVector< QPointF > mOutputPositions
Protected Attributes inherited from hal::GraphicsNet
QRectF mRect
QPainterPath mShape
Qt::PenStyle mPenStyle
bool mFillIcon
QColor mFillColor
Qt::BrushStyle mBrushStyle
Protected Attributes inherited from hal::GraphicsItem
ItemType mItemType
bool mHighlight
u32 mId
QColor mColor
Static Protected Attributes inherited from hal::SeparatedGraphicsNet
static qreal sAlpha
Static Protected Attributes inherited from hal::GraphicsNet
static qreal sLineWidth
static qreal sShapeWidth
static QPen sPen
static QBrush sBrush
Static Protected Attributes inherited from hal::GraphicsItem
static qreal sLod
static QColor sSelectionColor
static QColor sHighlightColor
Detailed Description
Used to display all nets which destinations are not in the current view.
A type of separated nets with circles as in- and output symbols. Currently unused.
Definition at line 38 of file circle_separated_net.h.
Constructor & Destructor Documentation
CircleSeparatedNet()
hal::CircleSeparatedNet::CircleSeparatedNet (Net * n)
Constructor.
Parameters
n - The underlying net
Definition at line 22 of file circle_separated_net.cpp.
Member Function Documentation
addInput()
void hal::CircleSeparatedNet::addInput (const QPointF & scene_position) override virtual
Add the an input pin as a destination of the CircleSeparatedNet
Parameters
scene_position - The scene position of the input pin
Implements hal::SeparatedGraphicsNet.
Definition at line 90 of file circle_separated_net.cpp.
References QPainterPath::addEllipse(), QVector::append(), QPainterPath::closeSubpath(), QPainterPath::lineTo(), QGraphicsItem::mapFromScene(), hal::SeparatedGraphicsNet::mInputPositions, QPainterPath::moveTo(), hal::GraphicsNet::mShape, QPointF::setX(), QPointF::setY(), hal::GraphicsNet::sShapeWidth, QPointF::x(), and QPointF::y().
addOutput()
void hal::CircleSeparatedNet::addOutput (const QPointF & scene_position) override virtual
Add the an output pin as a source of the CircleSeparatedNet
Parameters
scene_position - The scene position of the output pin
Implements hal::SeparatedGraphicsNet.
Definition at line 115 of file circle_separated_net.cpp.
References QPainterPath::addEllipse(), QVector::append(), QPainterPath::closeSubpath(), QPainterPath::lineTo(), QGraphicsItem::mapFromScene(), hal::SeparatedGraphicsNet::mOutputPositions, QPainterPath::moveTo(), hal::GraphicsNet::mShape, QPointF::setX(), QPointF::setY(), hal::GraphicsNet::sShapeWidth, QPointF::x(), and QPointF::y().
inputWidth()
qreal hal::CircleSeparatedNet::inputWidth () const override virtual
Get the width of one entire input (including the line and the circle) of the CircleSeparatedNet
Returns
the width of an input
Implements hal::SeparatedGraphicsNet.
Definition at line 140 of file circle_separated_net.cpp.
References hal::GraphicsNet::sLineWidth.
loadSettings()
void hal::CircleSeparatedNet::loadSettings () static
Loads the cosmetic setting that will be applied to all CircleSeparatedNets.
Definition at line 15 of file circle_separated_net.cpp.
Referenced by hal::style::debugUpdate().
outputWidth()
qreal hal::CircleSeparatedNet::outputWidth () const override virtual
Get the width of one entire output (including the line and the circle) of the CircleSeparatedNet
Returns
the width of an output
Implements hal::SeparatedGraphicsNet.
Definition at line 145 of file circle_separated_net.cpp.
References hal::GraphicsNet::sLineWidth.
paint()
void hal::CircleSeparatedNet::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) override virtual
Draws the CircleSeparatedNet in the scene.
Parameters
painter - The used QPainter
option - The styling options. Used to access the state (option->state).
widget - The widget to paint on
Implements QGraphicsItem.
Definition at line 26 of file circle_separated_net.cpp.
References QPainter::Antialiasing, QPainter::drawEllipse(), QPainter::drawLine(), QPainter::drawPath(), Qt::green, QPen::isCosmetic(), hal::GraphicsNet::mBrushStyle, hal::GraphicsNet::mFillIcon, hal::SeparatedGraphicsNet::mInputPositions, hal::SeparatedGraphicsNet::mOutputPositions, hal::GraphicsNet::mShape, Qt::NoBrush, option(), hal::GraphicsItem::penColor(), QPainter::renderHints(), hal::SeparatedGraphicsNet::sAlpha, hal::GraphicsNet::sBrush, QColor::setAlphaF(), QPainter::setBrush(), QBrush::setColor(), QPen::setColor(), QPen::setCosmetic(), QPainter::setPen(), QPainter::setRenderHint(), QBrush::setStyle(), QPen::setStyle(), hal::GraphicsItem::sLod, hal::GraphicsNet::sPen, QPen::style(), and hal::core_strings::to().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/items/nets/circle_separated_net.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/items/nets/circle_separated_net.cpp