HAL: hal::Action Class Reference
hal::Action Class Reference
HAL Gui
Provides an interface for triggerable functionality that can be inserted into widgets and also connected to shortcuts.
#include <action.h>
Public Slots
void setShortcut (const QKeySequence &shortcut)
Public Member Functions
Action (QObject *parent=nullptr)
Action (const QString &text, QObject *parent=nullptr)
Action (const QIcon &icon, const QString &text, QObject *parent=nullptr)
void setText (const QString &text)
void setToolTip (const QString &tooltip)
Public Member Functions inherited from QAction
QAction (QObject *parent)
QAction (const QString &text, QObject *parent)
QAction (const QIcon &icon, const QString &text, QObject *parent)
virtual ~QAction ()
void setActionGroup (QActionGroup *group)
QActionGroup * actionGroup () const const
void setIcon (const QIcon &icon)
QIcon icon () const const
void setText (const QString &text)
QString text () const const
void setIconText (const QString &text)
QString iconText () const const
void setToolTip (const QString &tip)
QString toolTip () const const
void setStatusTip (const QString &statusTip)
QString statusTip () const const
void setWhatsThis (const QString &what)
QString whatsThis () const const
void setPriority (QAction::Priority priority)
QAction::Priority priority () const const
QMenu * menu () const const
void setMenu (QMenu *menu)
void setSeparator (bool b)
bool isSeparator () const const
void setShortcut (const QKeySequence &shortcut)
QKeySequence shortcut () const const
void setShortcuts (const QList< QKeySequence > &shortcuts)
void setShortcuts (QKeySequence::StandardKey key)
QList< QKeySequence > shortcuts () const const
void setShortcutContext (Qt::ShortcutContext context)
Qt::ShortcutContext shortcutContext () const const
void setAutoRepeat (bool)
bool autoRepeat () const const
void setFont (const QFont &font)
QFont font () const const
void setCheckable (bool)
bool isCheckable () const const
QVariant data () const const
void setData (const QVariant &userData)
bool isChecked () const const
bool isEnabled () const const
bool isVisible () const const
void activate (QAction::ActionEvent event)
bool showStatusText (QWidget *widget)
void setMenuRole (QAction::MenuRole menuRole)
QAction::MenuRole menuRole () const const
void setIconVisibleInMenu (bool visible)
bool isIconVisibleInMenu () const const
void setShortcutVisibleInContextMenu (bool show)
bool isShortcutVisibleInContextMenu () const const
QWidget * parentWidget () const const
QList< QWidget * > associatedWidgets () const const
QList< QGraphicsWidget * > associatedGraphicsWidgets () const const
void trigger ()
void hover ()
void setChecked (bool)
void toggle ()
void setEnabled (bool)
void setDisabled (bool b)
void setVisible (bool)
void changed ()
void triggered (bool checked)
void hovered ()
void toggled (bool checked)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Public Types inherited from QAction
enum MenuRole
enum Priority
enum ActionEvent
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAction
NoRole
TextHeuristicRole
ApplicationSpecificRole
AboutQtRole
AboutRole
PreferencesRole
QuitRole
LowPriority
NormalPriority
HighPriority
Trigger
Hover
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QAction
virtual bool event (QEvent *e) override
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QAction
checkable
checked
enabled
icon
text
iconText
toolTip
statusTip
whatsThis
font
shortcut
shortcutContext
autoRepeat
visible
menuRole
iconVisibleInMenu
shortcutVisibleInContextMenu
priority
Properties inherited from QObject
objectName
Detailed Description
Provides an interface for triggerable functionality that can be inserted into widgets and also connected to shortcuts.
The Action class encapsulates the functionality of a button than can be put into menus and can can also be triggered via shortcuts. Common examples for actions are the "open" or "save" options in the top bar of the main widget as well as all icons in the python editor.
Definition at line 41 of file action.h.
Constructor & Destructor Documentation
Action() [1/3]
hal::Action::Action (QObject * parent = nullptr) explicit
The default constructor.
Parameters
parent - The action's parent.
Definition at line 5 of file action.cpp.
Action() [2/3]
hal::Action::Action (const QString & text, QObject * parent = nullptr) explicit
Second constructor where one can also set the descriptive text.
Parameters
text - The text.
parent - The action's parent.
Definition at line 10 of file action.cpp.
References setText(), and QAction::text.
Action() [3/3]
hal::Action::Action (const QIcon & icon, const QString & text, QObject * parent = nullptr) explicit
Third constructor where one can set the descriptive text as well as the displayed icon.
Parameters
icon - The displayed icon.
text - The descriptive text.
parent - The action's parent.
Definition at line 15 of file action.cpp.
References QAction::icon, QAction::setIcon(), setText(), and QAction::text.
Member Function Documentation
setShortcut
void hal::Action::setShortcut (const QKeySequence & shortcut) slot
Sets the shortcut with which one can trigger the action.
Parameters
shortcut - The shortcut.
Definition at line 27 of file action.cpp.
References QAction::setShortcut().
setText()
void hal::Action::setText (const QString & text)
Sets the descriptive text of the action.
Parameters
text - The text to set.
Definition at line 21 of file action.cpp.
References QAction::setText(), QAction::shortcut, and QAction::text.
Referenced by Action(), and hal::PythonEditor::PythonEditor().
setToolTip()
void hal::Action::setToolTip (const QString & tooltip)
Sets the tooltip of the action.
Parameters
tooltip - The tooltip
Definition at line 33 of file action.cpp.
References QAction::setToolTip().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/action/action.h
/home/runner/work/hal/hal/plugins/gui/src/action/action.cpp