HAL: hal::PluginRelay Class Reference
hal::PluginRelay Class Reference
HAL Gui
Forwards plugin related events from the core to the gui.
#include <plugin_relay.h>
Signals
void pluginLoaded (const QString &name, const QString &path)
void pluginUnloaded (const QString &name, const QString &path)
Public Member Functions
PluginRelay (QObject *parent=nullptr)
~PluginRelay ()
void pluginManagerCallback (bool is_load, const std::string &plugin_name, const std::string &plugin_path)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Forwards plugin related events from the core to the gui.
Definition at line 37 of file plugin_relay.h.
Constructor & Destructor Documentation
PluginRelay()
hal::PluginRelay::PluginRelay (QObject * parent = nullptr) explicit
The constructor. Connects to the core's plugin manager.
Parameters
parent - The relay's parent.
Definition at line 7 of file plugin_relay.cpp.
References hal::plugin_manager::add_model_changed_callback(), and pluginManagerCallback().
~PluginRelay()
hal::PluginRelay::~PluginRelay ()
The destructor. Removes the relay's connection from the core.
Definition at line 12 of file plugin_relay.cpp.
References hal::plugin_manager::remove_model_changed_callback().
Member Function Documentation
pluginLoaded
void hal::PluginRelay::pluginLoaded (const QString & name, const QString & path) signal
Q_SIGNAL that is emitted when a plugin is loaded.
Parameters
name - The plugin's name.
path - The plugin's path.
Referenced by pluginManagerCallback().
pluginManagerCallback()
void hal::PluginRelay::pluginManagerCallback (bool is_load, const std::string & plugin_name, const std::string & plugin_path)
Callback function that is connected to the core. Emits the appropriate signals.
Parameters
is_load - True if the plugin is loaded, False if unloaded.
plugin_name - The plugin's name.
plugin_path - The plugin's path.
Definition at line 17 of file plugin_relay.cpp.
References QString::fromStdString(), name, pluginLoaded(), pluginUnloaded(), and QObject::Q_EMIT().
Referenced by PluginRelay().
pluginUnloaded
void hal::PluginRelay::pluginUnloaded (const QString & name, const QString & path) signal
Q_SIGNAL that is emitted when a plugin is unloaded.
Parameters
name - The plugin's name.
path - The plugin's path.
Referenced by pluginManagerCallback().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/plugin_relay/plugin_relay.h
/home/runner/work/hal/hal/plugins/gui/src/plugin_relay/plugin_relay.cpp