HAL: hal::PinDelegate Class Reference
hal::PinDelegate Class Reference
#include <pin_delegate.h>
Public Member Functions
PinDelegate (QObject *parent=0)
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const override
void setEditorData (QWidget *editor, const QModelIndex &index) const override
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const override
void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const override
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
Public Member Functions inherited from QStyledItemDelegate
QStyledItemDelegate (QObject *parent)
virtual ~QStyledItemDelegate ()
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const const override
QItemEditorFactory * itemEditorFactory () const const
void setItemEditorFactory (QItemEditorFactory *factory)
virtual QString displayText (const QVariant &value, const QLocale &locale) const const
Public Member Functions inherited from QAbstractItemDelegate
QAbstractItemDelegate (QObject *parent)
virtual ~QAbstractItemDelegate ()
virtual void destroyEditor (QWidget *editor, const QModelIndex &index) const const
virtual bool helpEvent (QHelpEvent *event, QAbstractItemView *view, const QStyleOptionViewItem &option, const QModelIndex &index)
void commitData (QWidget *editor)
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
void sizeHintChanged (const QModelIndex &index)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Public Types inherited from QAbstractItemDelegate
enum EndEditHint
Static Public Member Functions inherited from QAbstractItemDelegate
QString elidedText (const QFontMetrics &fontMetrics, int width, Qt::TextElideMode mode, const QString &text)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemDelegate
NoHint
EditNextItem
EditPreviousItem
SubmitModelCache
RevertModelCache
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QStyledItemDelegate
virtual void initStyleOption (QStyleOptionViewItem *option, const QModelIndex &index) const const
virtual bool eventFilter (QObject *editor, QEvent *event) override
virtual bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index) override
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Definition at line 37 of file pin_delegate.h.
Constructor & Destructor Documentation
PinDelegate()
hal::PinDelegate::PinDelegate (QObject * parent = 0) explicit
Definition at line 18 of file pin_delegate.cpp.
Member Function Documentation
createEditor()
QWidget * hal::PinDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const override virtual
Reimplemented from QStyledItemDelegate.
Definition at line 23 of file pin_delegate.cpp.
References QModelIndex::column(), hal::PinItem::GroupCreator, QModelIndex::internalPointer(), QObject::parent(), hal::PinItem::PinCreator, and Qt::StrongFocus.
paint()
void hal::PinDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override virtual
Reimplemented from QStyledItemDelegate.
Definition at line 166 of file pin_delegate.cpp.
References Qt::darkRed, QPainter::fillRect(), QModelIndex::internalPointer(), hal::PinItem::InvalidPin, hal::PinItem::InvalidPinGroup, option(), and QStyledItemDelegate::paint().
setEditorData()
void hal::PinDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const override virtual
Reimplemented from QStyledItemDelegate.
Definition at line 83 of file pin_delegate.cpp.
References QModelIndex::column(), hal::PinItem::getItemType(), hal::PinItem::GroupCreator, QModelIndex::internalPointer(), hal::PinItem::InvalidPin, hal::PinItem::Pin, hal::PinItem::PinCreator, QComboBox::setCurrentText(), and QLineEdit::setText().
setModelData()
void hal::PinDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const override virtual
Reimplemented from QStyledItemDelegate.
Definition at line 120 of file pin_delegate.cpp.
References QModelIndex::column(), hal::PinItem::GroupCreator, QModelIndex::internalPointer(), QString::isEmpty(), and hal::PinItem::PinCreator.
updateEditorGeometry()
void hal::PinDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const override virtual
Reimplemented from QStyledItemDelegate.
Definition at line 160 of file pin_delegate.cpp.
References option(), and QWidget::setGeometry().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/pin_model/pin_delegate.h
/home/runner/work/hal/hal/plugins/gui/src/pin_model/pin_delegate.cpp