HAL: hal::GraphAlgorithmPlugin Class Reference
hal::GraphAlgorithmPlugin Class Reference
#include <plugin_graph_algorithm.h>
Public Member Functions
GraphAlgorithmPlugin ()=default
~GraphAlgorithmPlugin ()=default
std::string get_name () const override
std::string get_version () const override
std::map< int, std::set< Gate * > > get_communities (Netlist *const netlist)
std::map< int, std::set< Gate * > > get_communities_spinglass (Netlist *const netlist, u32 const spins)
std::map< int, std::set< Gate * > > get_communities_fast_greedy (Netlist *const netlist)
std::vector< std::vector< Gate * > > get_strongly_connected_components (Netlist *netlist)
std::vector< std::set< Gate * > > get_graph_cut (Netlist *const netlist, Gate *gate, const u32 depth=std::numeric_limits< u32 >::max(), const std::set< std::string > terminal_gate_type=std::set< std::string >())
std::map< int, Gate * > get_igraph_directed (Netlist *const netlist, igraph_t *igraph)
std::map< int, std::set< Gate * > > get_memberships_for_hal (igraph_t *graph, igraph_vector_t membership, std::map< int, Gate * > vertex_to_gate)
Public Member Functions inherited from hal::BasePluginInterface
BasePluginInterface ()
virtual ~BasePluginInterface ()
virtual void initialize ()
virtual std::string get_description () const
template<typename... Args>
void log (const Args &... args) const
virtual std::set< std::string > get_dependencies () const
virtual void on_load ()
virtual void on_unload ()
virtual void initialize_logging ()
virtual std::vector< AbstractExtensionInterface * > get_extensions () const
template<typename T >
T * get_first_extension () const
void delete_extension (AbstractExtensionInterface *aeif)
Additional Inherited Members
Protected Attributes inherited from hal::BasePluginInterface
std::vector< AbstractExtensionInterface * > m_extensions
Detailed Description
Definition at line 39 of file plugin_graph_algorithm.h.
Constructor & Destructor Documentation
GraphAlgorithmPlugin()
hal::GraphAlgorithmPlugin::GraphAlgorithmPlugin () default
constructor (= default)
~GraphAlgorithmPlugin()
hal::GraphAlgorithmPlugin::~GraphAlgorithmPlugin () default
destructor (= default)
Member Function Documentation
get_communities()
std::map< int, std::set< Gate * > > hal::GraphAlgorithmPlugin::get_communities (Netlist *const netlist)
Get a map of community IDs to communities. Each community is represented by a set of gates.
Parameters
[in] netlist - The netlist to operate on.
Returns
A map from community IDs to communities.
Definition at line 11 of file community_detection.cpp.
References hal::Netlist::delete_gate(), hal::Netlist::get_gate_by_id(), hal::Netlist::get_gates(), hal::Gate::get_id(), get_name(), hal::Netlist::get_nets(), log_error, and net.
Referenced by hal::PYBIND11_PLUGIN().
get_communities_fast_greedy()
std::map< int, std::set< Gate * > > hal::GraphAlgorithmPlugin::get_communities_fast_greedy (Netlist *const netlist)
Get a map of community IDs to communities running the fast greedy clustering algorithm from igraph. Each community is represented by a set of gates.
Parameters
[in] netlist - The netlist to operate on.
Returns
A map from community IDs to communities.
Definition at line 13 of file communities_fast_greedy.cpp.
References get_igraph_directed(), get_name(), and log_error.
Referenced by hal::PYBIND11_PLUGIN().
get_communities_spinglass()
std::map< int, std::set< Gate * > > hal::GraphAlgorithmPlugin::get_communities_spinglass (Netlist *const netlist, u32 const spins)
Get a map of community IDs to communities running the spinglass clustering algorithm. Each community is represented by a set of gates.
Parameters
[in] netlist - The netlist to operate on.
[in] spins - The number of spins.
Returns
A map from community IDs to communities.
Definition at line 13 of file communities_spinglass.cpp.
References hal::Netlist::get_gates(), get_igraph_directed(), get_memberships_for_hal(), get_name(), hal::Netlist::get_nets(), hal::BasePluginInterface::log(), log_error, and log_info.
Referenced by hal::PYBIND11_PLUGIN().
get_graph_cut()
std::vector< std::set< Gate * > > hal::GraphAlgorithmPlugin::get_graph_cut (Netlist *const netlist, Gate * gate, const u32 depth = std::numeric_limits<u32>::max(), const std::set< std::string > terminal_gate_type = std::set<std::string>())
Get a graph cut for a specific gate and depth. Further, a set of gates can be specified that limit the graph cut, i.e., flip-flops and memory cells.
The graph cut is returned as a vector of sets of gates with the vector's index representing the distance of each set to the starting point.
Parameters
[in] netlist - The netlist to operate on.
[in] gate - The gate that is the starting point for the graph cut.
[in] depth - The depth of the graph cut.
[in] terminal_gate_type - A set of gates at which to terminate the graph cut.
Returns
The graph cut as a vector of sets of gates.
Definition at line 8 of file graph_cut.cpp.
References test_plugin::g, get_name(), and log_error.
Referenced by hal::PYBIND11_PLUGIN().
get_igraph_directed()
std::map< int, Gate * > hal::GraphAlgorithmPlugin::get_igraph_directed (Netlist *const netlist, igraph_t * igraph)
Generates an directed graph, based on the current netlist. Each gate is transformed to a node, while each net is transformed to an edge. The function returns the mapping from igraph node ids to HAL gates. Note that for each global input and output dummy nodes are generated in the igraph representation.
Parameters
[in] netlist - The netlist to operate on.
Returns
map from igraph node id to HAL gate ID, to be able to match back any graph operations.
Definition at line 13 of file igraph.cpp.
References hal::Netlist::get_gates(), hal::Gate::get_id(), hal::Gate::get_name(), hal::Netlist::get_nets(), log_debug, log_error, and net.
Referenced by get_communities_fast_greedy(), get_communities_spinglass(), and get_strongly_connected_components().
get_memberships_for_hal()
std::map< int, std::set< Gate * > > hal::GraphAlgorithmPlugin::get_memberships_for_hal (igraph_t * graph, igraph_vector_t membership, std::map< int, Gate * > vertex_to_gate)
Uses the mapping provided by the the get_igraph_directed() function to generate sets of HAL gates that were generated by the clustering algorithms of igraph. The igraph membership vector contains the generated clusters from the igraph framework, which is used to generate the sets of gates in HAL. The sets are stored in a map with the regarding cluster ID from igraph, since these can contain information generated by the clustering algorithm.
Parameters
[in] graph - igraph graph object
[in] membership - membership vector
[in] vertex_to_gate - map from node ID in igraph to HAL gate
Returns
map from membership id to set of gates that have the membership.
Definition at line 133 of file igraph.cpp.
Referenced by get_communities_spinglass(), and get_strongly_connected_components().
get_name()
std::string hal::GraphAlgorithmPlugin::get_name () const override virtual
Get the name of the plugin.
Returns
The name of the plugin.
Implements hal::BasePluginInterface.
Definition at line 12 of file plugin_graph_algorithm.cpp.
Referenced by get_communities(), get_communities_fast_greedy(), get_communities_spinglass(), get_graph_cut(), get_strongly_connected_components(), and hal::PYBIND11_PLUGIN().
get_strongly_connected_components()
std::vector< std::vector< Gate * > > hal::GraphAlgorithmPlugin::get_strongly_connected_components (Netlist * netlist)
Get a map of community IDs to communities running the multilevel clustering algorithm from igraph. Each community is represented by a set of gates.
Parameters
[in] netlist - The netlist to operate on.
Returns
A map from community IDs to communities.
std::map<int, std::set<Gate*>> get_communities_multilevel(Netlist* netlist); other graph algorithm Get a vector of strongly connected components (SCC) with each SSC being represented by a vector of gates.
Parameters
[in] netlist - The netlist to operate on.
Returns
A vector of SCCs.
Definition at line 13 of file strongly_connected_components.cpp.
References get_igraph_directed(), get_memberships_for_hal(), get_name(), and log_error.
Referenced by hal::PYBIND11_PLUGIN().
get_version()
std::string hal::GraphAlgorithmPlugin::get_version () const override virtual
Get the version of the plugin.
Returns
The version of the plugin.
Implements hal::BasePluginInterface.
Definition at line 17 of file plugin_graph_algorithm.cpp.
Referenced by hal::PYBIND11_PLUGIN().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/graph_algorithm/include/graph_algorithm/plugin_graph_algorithm.h
/home/runner/work/hal/hal/plugins/graph_algorithm/src/clustering/communities_fast_greedy.cpp
/home/runner/work/hal/hal/plugins/graph_algorithm/src/clustering/communities_spinglass.cpp
/home/runner/work/hal/hal/plugins/graph_algorithm/src/clustering/community_detection.cpp
/home/runner/work/hal/hal/plugins/graph_algorithm/src/graph/graph_cut.cpp
/home/runner/work/hal/hal/plugins/graph_algorithm/src/graph/strongly_connected_components.cpp
/home/runner/work/hal/hal/plugins/graph_algorithm/src/igraph.cpp
/home/runner/work/hal/hal/plugins/graph_algorithm/src/plugin_graph_algorithm.cpp