HAL: hal::GraphNavigationWidget Class Reference
hal::GraphNavigationWidget Class Reference
#include <graph_navigation_widget.h>
Public Slots
void closeRequest ()
Signals
void navigationRequested (const Node &origin, const u32 via_net, const QSet< u32 > &to_gates, const QSet< u32 > &to_modules)
void closeRequested ()
void resetFocus ()
Public Member Functions
GraphNavigationWidget (bool onlyNavigate, QWidget *parent=nullptr)
void setup (SelectionRelay::Subfocus direction)
void setup (Node origin, Net *via_net, SelectionRelay::Subfocus dir)
SelectionRelay::Subfocus direction () const
bool isEmpty () const
bool hasBothWidgets () const
void toggleWidget ()
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
virtual void setVisible (bool visible)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
virtual QSize sizeHint () const const
virtual QSize minimumSizeHint () const const
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Protected Member Functions
void keyPressEvent (QKeyEvent *event) override
void focusInEvent (QFocusEvent *event) override
Protected Member Functions inherited from QWidget
virtual bool event (QEvent *event) override
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void paintEvent (QPaintEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void closeEvent (QCloseEvent *event)
virtual void contextMenuEvent (QContextMenuEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void dragEnterEvent (QDragEnterEvent *event)
virtual void dragMoveEvent (QDragMoveEvent *event)
virtual void dragLeaveEvent (QDragLeaveEvent *event)
virtual void dropEvent (QDropEvent *event)
virtual void showEvent (QShowEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual void changeEvent (QEvent *event)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
virtual void inputMethodEvent (QInputMethodEvent *event)
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
virtual bool focusNextPrevChild (bool next)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Friends
class GraphNavigationTableWidget
class GraphNavigationTreeWidget
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Detailed Description
The GraphNavigationWidget is a widget that appears whenever the user navigates from a pin with multiple navigation destinations. It wraps both an instance of GraphNavigationTableWidget (for destinations within the context) and an instance of GraphNavigationTreeWidget (for destinations outside the context).
The user can navigate in both navigation widgets to choose a destination.
Definition at line 151 of file graph_navigation_widget.h.
Constructor & Destructor Documentation
GraphNavigationWidget()
hal::GraphNavigationWidget::GraphNavigationWidget (bool onlyNavigate, QWidget * parent = nullptr)
Constructor.
If the onlyNavigate flag is set to true, this widget can not be used to add gates to the view. In this case only the GraphNavigationTableWidget will appear while navigating.
Parameters
onlyNavigate - Set to true if the widget should be used for navigation only.
parent - The parent widget (where to embed the navigation widget)
Definition at line 128 of file graph_navigation_widget.cpp.
References QShortcut::activated(), QTabWidget::addTab(), QGridLayout::addWidget(), QTableWidget::cellDoubleClicked(), closeRequest(), QObject::connect(), QAbstractItemView::ExtendedSelection, GraphNavigationTableWidget, GraphNavigationTreeWidget, QTreeView::header(), QWidget::hide(), QTableView::horizontalHeader(), QTreeWidget::itemDoubleClicked(), Qt::Key_Escape, Qt::Key_Tab, QAbstractItemView::SelectRows, QTreeWidget::setColumnCount(), QTableWidget::setColumnCount(), QWidget::setFocusPolicy(), QTreeWidget::setHeaderLabels(), QTableWidget::setHorizontalHeaderLabels(), QAbstractItemView::setSelectionBehavior(), QAbstractItemView::setSelectionMode(), QTableView::setShowGrid(), QHeaderView::setStretchLastSection(), QAbstractItemView::SingleSelection, toggleWidget(), and QTableView::verticalHeader().
Member Function Documentation
closeRequest
void hal::GraphNavigationWidget::closeRequest () slot
Closes the navigation widget.
Definition at line 190 of file graph_navigation_widget.cpp.
References closeRequested(), hal::SelectionRelay::None, QObject::Q_EMIT(), and resetFocus().
Referenced by GraphNavigationWidget(), hal::GraphNavigationTableWidget::keyPressEvent(), and hal::GraphNavigationTreeWidget::keyPressEvent().
closeRequested
void hal::GraphNavigationWidget::closeRequested () signal
This signal notifies that the navigation widget is about to be closed.
Referenced by closeRequest(), hal::GatePinTree::GatePinTree(), and hal::GraphWidget::GraphWidget().
direction()
SelectionRelay::Subfocus hal::GraphNavigationWidget::direction () const inline
Gets the direction to navigate along. The direction is set in the setup-function.
This function is internally used by both managed navigation widgets but should be irrelevant to other classes.
Returns
the current navigation direction
Definition at line 205 of file graph_navigation_widget.h.
Referenced by hal::GraphNavigationTableWidget::keyPressEvent(), hal::GraphNavigationTreeWidget::keyPressEvent(), and setup().
focusInEvent()
void hal::GraphNavigationWidget::focusInEvent (QFocusEvent * event) override protected virtual
Reimplemented from QWidget.
Definition at line 567 of file graph_navigation_widget.cpp.
References QAbstractItemView::clearSelection(), and QWidget::setFocus().
hasBothWidgets()
bool hal::GraphNavigationWidget::hasBothWidgets () const
Checks if both the GraphNavigationTableWidget and the GraphNavigationTreeWidget contain data to show.
Returns
true if both widgets contain data to show.
Definition at line 395 of file graph_navigation_widget.cpp.
Referenced by hal::GraphNavigationTableWidget::keyPressEvent(), hal::GraphNavigationTreeWidget::keyPressEvent(), and toggleWidget().
isEmpty()
bool hal::GraphNavigationWidget::isEmpty () const
Checks if the navigation widget is empty. It is considered empty if neither the GraphNavigationTableWidget nor the GraphNavigationTreeWidget contain data to show.
Returns
true if the navigation widget is considered empty.
Definition at line 422 of file graph_navigation_widget.cpp.
keyPressEvent()
void hal::GraphNavigationWidget::keyPressEvent (QKeyEvent * event) override protected virtual
Reimplemented from QWidget.
Definition at line 557 of file graph_navigation_widget.cpp.
References QKeyEvent::key(), Qt::Key_Tab, QWidget::keyPressEvent(), and toggleWidget().
navigationRequested
void hal::GraphNavigationWidget::navigationRequested (const Node & origin, const u32 via_net, const QSet< u32 > & to_gates, const QSet< u32 > & to_modules) signal
This signal is sent after the user has selected a navigation target (chosen in the GraphNavigationTableWidget) or gates and modules to add to the view (chosen in the GraphNavigationTreeWidget).
If he has chosen a navigation target:
If the target is a gate, to_gates will contain the one id of the target gate while to_modules will be empty.
If the target is a module, to_gates will be empty while to_modules will contain the one id of the target module.
If he has chosen gates and modules to add to the view:
The sets to_gates and to_modules will be filled with the ids of the chosen gates and modules.
Parameters
origin - The gate to navigate from
via_net - The net to navigate along
to_gates - The navigation target / The gates to add to the view
to_modules - The navigation target / The modules to add to the view
Referenced by hal::GatePinTree::GatePinTree(), and hal::GraphWidget::GraphWidget().
resetFocus
void hal::GraphNavigationWidget::resetFocus () signal
This signal notifies that the navigation widget is about to be closed.
Referenced by closeRequest().
setup() [1/2]
void hal::GraphNavigationWidget::setup (Node origin, Net * via_net, SelectionRelay::Subfocus dir)
Prepares the widget to be shown. Based on the passed origin node and its connected net, it searches for all valid navigation destinations in the given direction, i.e.:
search for destination endpoints if direction = SelectionRelay::Subfocus::Right
search for source endpoints if direction = SelectionRelay::Subfocus::Left
Both navigation widgets (GraphNavigationTableWidget and GraphNavigationTreeWidget) are filled up with these navigation destinations depending on whether they are in the current context or not.
After calling the setup-function one can call setFocus() to open and activate the navigation widget.
Parameters
origin - The gate to navigate from
via_net - The net to navigate along
dir - The direction to navigate
Definition at line 333 of file graph_navigation_widget.cpp.
setup() [2/2]
void hal::GraphNavigationWidget::setup (SelectionRelay::Subfocus direction)
Prepares the widget to be shown. Based on the current focus and subfocus of gSelectionRelay, it searches for all valid navigation destinations in the given direction, i.e.:
search for destination endpoints if direction = SelectionRelay::Subfocus::Right
search for source endpoints if direction = SelectionRelay::Subfocus::Left
Both navigation widgets (GraphNavigationTableWidget and GraphNavigationTreeWidget) are filled up with these navigation destinations depending on whether they are in the current context or not.
After calling the setup-function one can call setFocus() to open and activate the navigation widget.
Parameters
direction - The direction to navigate
Definition at line 341 of file graph_navigation_widget.cpp.
References direction(), hal::SelectionRelay::focusId(), hal::SelectionRelay::focusType(), test::g, hal::Node::Gate, hal::SelectionRelay::Gate, hal::Netlist::get_gate_by_id(), hal::Module::get_id(), hal::Netlist::get_module_by_id(), hal::Netlist::get_net_by_id(), hal::gNetlist, hal::gSelectionRelay, hal::Node::Module, hal::SelectionRelay::Module, and hal::SelectionRelay::Net.
toggleWidget()
void hal::GraphNavigationWidget::toggleWidget ()
Switches the focus within this widget from the GraphNavigationTableWidget to the GraphNavigationTreeWidget or the other way around.
Definition at line 400 of file graph_navigation_widget.cpp.
References QAbstractItemView::clearSelection(), QTabWidget::currentIndex, hal::GraphNavigationTreeWidget::firstIndex(), hasBothWidgets(), QTableView::selectRow(), QTableWidget::setCurrentCell(), QTabWidget::setCurrentIndex(), QAbstractItemView::setCurrentIndex(), and QWidget::setFocus().
Referenced by hal::GraphNavigationTreeWidget::event(), GraphNavigationWidget(), hal::GraphNavigationTableWidget::keyPressEvent(), hal::GraphNavigationTreeWidget::keyPressEvent(), and keyPressEvent().
Friends And Related Function Documentation
GraphNavigationTableWidget
friend class GraphNavigationTableWidget friend
Definition at line 155 of file graph_navigation_widget.h.
Referenced by GraphNavigationWidget().
GraphNavigationTreeWidget
friend class GraphNavigationTreeWidget friend
Definition at line 156 of file graph_navigation_widget.h.
Referenced by GraphNavigationWidget().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/graph_navigation_widget.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/graph_navigation_widget.cpp