HAL: hal::DetailsGeneralModelEntry Class Reference
hal::DetailsGeneralModelEntry Class Reference
HAL Gui » Utility Widgets » Selection Details Widget
Single entry in the GeneralDetailsModel.
#include <details_general_model.h>
Public Member Functions
DetailsGeneralModelEntry ()
DetailsGeneralModelEntry (const QString &label_, const QVariant &value_, const QString &python_=QString())
QVariant data (int iColumn) const
void setValue (const QString &v) const
void setObject (const UserActionObject &obj)
QString lcLabel () const
QString textValue () const
QString pythonGetter () const
bool canEditText () const
Detailed Description
Single entry in the GeneralDetailsModel.
The item class that is used by the DetailsGeneralModel to store and display its entries. It consists of a key(label) and a value string that are both displayed in the view. Furthermore this item class stores (if available) python code as a string to access it later (e.g. via a contextmenu).
Definition at line 49 of file details_general_model.h.
Constructor & Destructor Documentation
DetailsGeneralModelEntry() [1/2]
hal::DetailsGeneralModelEntry::DetailsGeneralModelEntry () inline
First constructor. Primarily used to create dummy content.
Definition at line 62 of file details_general_model.h.
DetailsGeneralModelEntry() [2/2]
hal::DetailsGeneralModelEntry::DetailsGeneralModelEntry (const QString & label_, const QVariant & value_, const QString & python_ = QString()) inline
Second constructor that is used for actual content of the model.
Parameters
label_ - The key part of the entry (usually displayed in the first column).
value_ - The value part of the entry (usually displayed in the second column).
python_ - The base python code to access the property (e.g. get_name)
Definition at line 70 of file details_general_model.h.
Member Function Documentation
canEditText()
bool hal::DetailsGeneralModelEntry::canEditText () const
Checks if the text can be edited.
Returns
True if it can be edited, False otherwise.
Definition at line 13 of file details_general_model.cpp.
References hal::UserActionObjectType::None, and hal::UserActionObject::type().
Referenced by hal::DetailsGeneralModel::contextMenuRequested().
data()
QVariant hal::DetailsGeneralModelEntry::data (int iColumn) const
Get the column specific data. (0 = label, 1 = value).
Parameters
iColumn - The column for the requested data.
Returns
The column specific data.
Definition at line 18 of file details_general_model.cpp.
References QString::arg().
lcLabel()
QString hal::DetailsGeneralModelEntry::lcLabel () const inline
Get the lower case version of the entry's key(label).
Returns
The lower case version of the key(label).
Definition at line 110 of file details_general_model.h.
References QString::toLower().
Referenced by hal::DetailsGeneralModel::contextMenuRequested(), hal::DetailsGeneralModel::editValueTriggered(), and setValue().
pythonGetter()
QString hal::DetailsGeneralModelEntry::pythonGetter () const inline
Returns the python getter code for the entry.
Returns
The python getter code.
Definition at line 124 of file details_general_model.h.
Referenced by hal::DetailsGeneralModel::contextMenuRequested(), and hal::DetailsGeneralModel::extractPythonTriggered().
setObject()
void hal::DetailsGeneralModelEntry::setObject (const UserActionObject & obj) inline
Sets the setter method for the entry (e.g. the set_name method of a module for the name entry).
Parameters
obj - The object value to be set.
Definition at line 103 of file details_general_model.h.
setValue()
void hal::DetailsGeneralModelEntry::setValue (const QString & v) const
Checks if a "setter method" for the entry is set so it can be modified. It is displayed in the contextmenu via "Change <property>" (e.g. the name).
Returns
True if entry has a setter method, false otherwise. Invokes the setter method for the given entry if a setter method is available.
Parameters
v - The new value to invoke the setter method with.
Definition at line 29 of file details_general_model.cpp.
References hal::ActionSetObjectType::exec(), hal::ActionRenameObject::exec(), lcLabel(), hal::UserActionObjectType::None, hal::UserAction::setObject(), and hal::UserActionObject::type().
Referenced by hal::DetailsGeneralModel::editValueTriggered().
textValue()
QString hal::DetailsGeneralModelEntry::textValue () const inline
Get the string version of the entry's value.
Returns
The string version of the entry's value.
Definition at line 117 of file details_general_model.h.
References QVariant::toString().
Referenced by hal::DetailsGeneralModel::editValueTriggered(), and hal::DetailsGeneralModel::extractRawTriggered().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/details_general_model.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/details_general_model.cpp