HAL: hal::NetLayoutWire Class Reference
hal::NetLayoutWire Class Reference
HAL Gui » Graph Widget » Layouters
#include <net_layout_point.h>
Public Types
enum WirePointType { SourcePoint , DestinationPoint }
Public Member Functions
NetLayoutWire (const NetLayoutPoint &p, const NetLayoutDirection &dir, bool isEnd)
QGraphicsLineItem * graphicsFactory () const
NetLayoutPoint endPoint (WirePointType pnt) const
bool isEndpoint () const
bool isHorizontal () const
bool operator== (const NetLayoutWire &other) const
QString toString () const
Detailed Description
Definition at line 94 of file net_layout_point.h.
Member Enumeration Documentation
WirePointType
enum hal::NetLayoutWire::WirePointType
Enumerator
SourcePoint
DestinationPoint
Definition at line 97 of file net_layout_point.h.
Constructor & Destructor Documentation
NetLayoutWire()
hal::NetLayoutWire::NetLayoutWire (const NetLayoutPoint & p, const NetLayoutDirection & dir, bool isEnd)
Definition at line 181 of file net_layout_point.cpp.
References hal::NetLayoutDirection::direction(), hal::NetLayoutDirection::Down, hal::NetLayoutDirection::Left, hal::NetLayoutPoint::nextPoint(), hal::NetLayoutDirection::Right, and hal::NetLayoutDirection::Up.
Member Function Documentation
endPoint()
NetLayoutPoint hal::NetLayoutWire::endPoint (WirePointType pnt) const
Definition at line 223 of file net_layout_point.cpp.
References SourcePoint, and hal::NetLayoutDirection::step().
Referenced by hal::NetLayoutConnection::add(), and hal::qHash().
graphicsFactory()
QGraphicsLineItem * hal::NetLayoutWire::graphicsFactory () const
Definition at line 212 of file net_layout_point.cpp.
References Qt::black, hal::NetLayoutDirection::isNull(), hal::NetLayoutPoint::nextPoint(), scenePoint(), and QGraphicsLineItem::setPen().
isEndpoint()
bool hal::NetLayoutWire::isEndpoint () const inline
Definition at line 102 of file net_layout_point.h.
isHorizontal()
bool hal::NetLayoutWire::isHorizontal () const inline
Definition at line 103 of file net_layout_point.h.
References hal::NetLayoutDirection::isHorizontal().
Referenced by hal::qHash().
operator==()
bool hal::NetLayoutWire::operator== (const NetLayoutWire & other) const
Definition at line 199 of file net_layout_point.cpp.
toString()
QString hal::NetLayoutWire::toString () const
Definition at line 206 of file net_layout_point.cpp.
References QString::arg(), hal::NetLayoutDirection::index(), QPoint::x(), and QPoint::y().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/net_layout_point.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/net_layout_point.cpp