HAL: hal::DataflowPlugin Class Reference
hal::DataflowPlugin Class Reference
Plugin interface for the dataflow analysis plugin (DANA).
#include <plugin_dataflow.h>
Public Member Functions
DataflowPlugin ()
Constructor for DataflowPlugin.
~DataflowPlugin ()=default
Default destructor for DataflowPlugin.
std::string get_name () const override
Get the name of the plugin.
std::string get_version () const override
Get the version of the plugin.
std::string get_description () const override
Get a short description of the plugin.
std::set< std::string > get_dependencies () const override
Get the plugin dependencies.
Public Member Functions inherited from hal::BasePluginInterface
BasePluginInterface ()=default
virtual ~BasePluginInterface ()
virtual void initialize ()
template<typename... Args>
void log (const Args &... args) const
virtual void on_load ()
virtual void on_unload ()
virtual void initialize_logging ()
virtual std::vector< AbstractExtensionInterface * > get_extensions () const
template<typename T >
T * get_first_extension () const
void delete_extension (AbstractExtensionInterface *aeif)
Additional Inherited Members
Protected Attributes inherited from hal::BasePluginInterface
std::vector< AbstractExtensionInterface * > m_extensions
Detailed Description
Plugin interface for the dataflow analysis plugin (DANA).
This class provides an interface to integrate the DANA tool as a plugin within the HAL framework.
Definition at line 113 of file plugin_dataflow.h.
Constructor & Destructor Documentation
DataflowPlugin()
hal::DataflowPlugin::DataflowPlugin ()
Constructor for DataflowPlugin.
Definition at line 39 of file plugin_dataflow.cpp.
References hal::BasePluginInterface::m_extensions.
~DataflowPlugin()
hal::DataflowPlugin::~DataflowPlugin () default
Default destructor for DataflowPlugin.
Member Function Documentation
get_dependencies()
std::set< std::string > hal::DataflowPlugin::get_dependencies () const override virtual
Get the plugin dependencies.
Returns
A set of plugin names that this plugin depends on.
Reimplemented from hal::BasePluginInterface.
Definition at line 34 of file plugin_dataflow.cpp.
get_description()
std::string hal::DataflowPlugin::get_description () const override virtual
Get a short description of the plugin.
Returns
The short description of the plugin.
Reimplemented from hal::BasePluginInterface.
Definition at line 29 of file plugin_dataflow.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_name()
std::string hal::DataflowPlugin::get_name () const override virtual
Get the name of the plugin.
Returns
The name of the plugin.
Implements hal::BasePluginInterface.
Definition at line 19 of file plugin_dataflow.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_version()
std::string hal::DataflowPlugin::get_version () const override virtual
Get the version of the plugin.
Returns
The version of the plugin.
Implements hal::BasePluginInterface.
Definition at line 24 of file plugin_dataflow.cpp.
Referenced by hal::PYBIND11_PLUGIN().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/dataflow_analysis/include/dataflow_analysis/plugin_dataflow.h
/home/runner/work/hal/hal/plugins/dataflow_analysis/src/plugin_dataflow.cpp