HAL: hal::SelectionTreeItemGate Class Reference
hal::SelectionTreeItemGate Class Reference
HAL Gui » Utility Widgets » Selection Details Widget
Tree item that represents a gate.
#include <selection_tree_item.h>
Public Member Functions
SelectionTreeItemGate (u32 id_)
virtual QVariant name () const
virtual const QIcon & icon () const
virtual void suppressedByFilterRecursion (QList< u32 > &modIds, QList< u32 > &gatIds, QList< u32 > &netIds, const QRegularExpression &regex) const
virtual QVariant boxType () const
Public Member Functions inherited from hal::SelectionTreeItem
SelectionTreeItem (TreeItemType t=NullItem, u32 id_=0)
virtual ~SelectionTreeItem ()
TreeItemType itemType () const
u32 id () const
SelectionTreeItem * parent () const
void setParent (SelectionTreeItem *p)
virtual int childCount () const
virtual SelectionTreeItem * child (int row) const
virtual QVariant data (int column) const
virtual bool match (const QRegularExpression &regex) const
bool isEqual (const SelectionTreeItem *sti) const
Additional Inherited Members
Public Types inherited from hal::SelectionTreeItem
enum TreeItemType {
NullItem, ModuleItem, GateItem, NetItem,
MaxItem
}
Protected Attributes inherited from hal::SelectionTreeItem
TreeItemType mItemType
u32 mId
SelectionTreeItem * mParent
Detailed Description
Tree item that represents a gate.
A subclass of the basic tree item class that represents a gate of the netlist. It implements the necessary commonly shared inherited functions as well as the gate specific function gateType().
Definition at line 305 of file selection_tree_item.h.
Constructor & Destructor Documentation
SelectionTreeItemGate()
hal::SelectionTreeItemGate::SelectionTreeItemGate (u32 id_)
The constructor.
Parameters
id_ - The item's id. It is the same id as the gate it represents.
Definition at line 153 of file selection_tree_item.cpp.
Member Function Documentation
boxType()
QVariant hal::SelectionTreeItemGate::boxType () const virtual
Get the name of the gate's type (e.g. LUT5 or FF).
Returns
The gate type (QString).
Reimplemented from hal::SelectionTreeItem.
Definition at line 170 of file selection_tree_item.cpp.
References QString::fromStdString(), hal::Netlist::get_gate_by_id(), hal::GateType::get_name(), hal::Gate::get_type(), hal::gNetlist, and hal::SelectionTreeItem::mId.
icon()
const QIcon & hal::SelectionTreeItemGate::icon () const virtual
Get the icon for a gate type item.
Returns
The gate specific icon.
Implements hal::SelectionTreeItem.
Definition at line 164 of file selection_tree_item.cpp.
name()
QVariant hal::SelectionTreeItemGate::name () const virtual
Get the name of the item. The name is usually the name of the underlying netlist item.
Returns
The item's name.
Implements hal::SelectionTreeItem.
Definition at line 157 of file selection_tree_item.cpp.
References QString::fromStdString(), hal::Netlist::get_gate_by_id(), hal::Gate::get_name(), hal::gNetlist, and hal::SelectionTreeItem::mId.
suppressedByFilterRecursion()
void hal::SelectionTreeItemGate::suppressedByFilterRecursion (QList< u32 > & modIds, QList< u32 > & gatIds, QList< u32 > & netIds, const QRegularExpression & regex) const virtual
Matches itself against the given regex. If no match was found it appends itself (its id) to the gatIds list.
Parameters
modIds - The list that contains the suppresed module-type items at the end.
gatIds - The list that contains the suppressed gate-type items at the end.
netIds - The list that contains the suppressed net-type items at the end.
regex - The regular expression to match the items against.
Implements hal::SelectionTreeItem.
Definition at line 177 of file selection_tree_item.cpp.
References QList::append(), hal::SelectionTreeItem::match(), and hal::SelectionTreeItem::mId.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/tree_navigation/selection_tree_item.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/tree_navigation/selection_tree_item.cpp