HAL: hal::ActionUnfoldModule Class Reference
hal::ActionUnfoldModule Class Reference
HAL Gui » User Actions
Unfolds a module.
#include <action_unfold_module.h>
Public Member Functions
ActionUnfoldModule (u32 moduleId=0)
QString tagname () const override
bool exec () override
void setContextId (u32 id)
void setObject (const UserActionObject &obj) override
void setPlacementHint (PlacementHint hint)
Public Member Functions inherited from hal::UserAction
virtual ~UserAction ()
virtual void writeToXml (QXmlStreamWriter &xmlOut) const
virtual void readFromXml (QXmlStreamReader &xmlIn)
virtual UserActionObject object () const
bool isWaitForReady () const
int compoundOrder () const
void setCompoundOrder (int cmpord)
qint64 timeStamp () const
QString cryptographicHash (int recordNo) const
virtual void addToHash (QCryptographicHash &cryptoHash) const
UserAction * undoAction () const
QString debugDump () const
void setObjectLock (bool lock)
Additional Inherited Members
Protected Member Functions inherited from hal::UserAction
UserAction ()
Static Protected Member Functions inherited from hal::UserAction
static QString setToText (const QSet< u32 > &set)
static QSet< u32 > setFromText (const QString &s)
Protected Attributes inherited from hal::UserAction
UserActionObject mObject
bool mWaitForReady
int mCompoundOrder
UserAction * mUndoAction
qint64 mTimeStamp
bool mObjectLock
Detailed Description
Unfolds a module.
Unfolds a module so that its content is shown in the GraphicsScene.
User Action: ActionFoldModule
Definition at line 40 of file action_unfold_module.h.
Constructor & Destructor Documentation
ActionUnfoldModule()
hal::ActionUnfoldModule::ActionUnfoldModule (u32 moduleId = 0)
Action constructor.
Parameters
moduleId - The id of the module to unfold.
Definition at line 27 of file action_unfold_module.cpp.
References hal::UserActionObjectType::Module, and setObject().
Member Function Documentation
exec()
bool hal::ActionUnfoldModule::exec () override virtual
Executes user interaction and returns true on success. Note: Each implementation of exec() must include a call to the exec() method of base class to store the UserAction object in history and to transfer its ownership.
Returns
True on success, False otherwise.
Reimplemented from hal::UserAction.
Definition at line 51 of file action_unfold_module.cpp.
References hal::PlacementHint::addGridPosition(), hal::UserAction::exec(), hal::gContentManager, hal::Module::get_gates(), hal::Netlist::get_module_by_id(), hal::Module::get_submodules(), hal::GraphContextManager::getContextById(), hal::ContentManager::getContextManagerWidget(), hal::ContextManagerWidget::getCurrentContext(), hal::GraphContext::getLayouter(), hal::gGraphContextManager, hal::gNetlist, hal::PlacementHint::GridPosition, hal::UserActionObject::id(), hal::UserAction::mObject, hal::UserActionObjectType::Module, hal::Node::Module, hal::UserAction::mUndoAction, hal::GraphLayouter::nodeToPositionMap(), hal::ActionFoldModule::setContextId(), hal::ActionFoldModule::setPlacementHint(), and hal::UserActionObject::type().
setContextId()
void hal::ActionUnfoldModule::setContextId (u32 id) inline
Sets the id of the context the module will be folded in.
Parameters
id - The context id
Definition at line 59 of file action_unfold_module.h.
Referenced by hal::ActionFoldModule::exec().
setObject()
void hal::ActionUnfoldModule::setObject (const UserActionObject & obj) override virtual
Setter for object argument of interaction.
Parameters
obj - The object.
Reimplemented from hal::UserAction.
Definition at line 34 of file action_unfold_module.cpp.
References hal::UserActionObjectType::Context, hal::UserActionObject::id(), hal::UserActionObjectType::Module, hal::UserActionObjectType::None, hal::UserAction::setObject(), and hal::UserActionObject::type().
Referenced by ActionUnfoldModule().
setPlacementHint()
void hal::ActionUnfoldModule::setPlacementHint (PlacementHint hint) inline
Configures the placement hints for the unfolded module.
Parameters
hint - The new placement hints.
Definition at line 67 of file action_unfold_module.h.
Referenced by hal::ActionFoldModule::exec().
tagname()
QString hal::ActionUnfoldModule::tagname () const override virtual
The xml tagname for the action is purely virtual and needs to be implemented in derived class.
Returns
The tagname.
Implements hal::UserAction.
Definition at line 22 of file action_unfold_module.cpp.
References hal::ActionUnfoldModuleFactory::sFactory, and hal::UserActionFactory::tagname().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/action_unfold_module.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/action_unfold_module.cpp