HAL: hal::PinChangedEventScope Class Reference
hal::PinChangedEventScope Class Reference
#include <pin_event.h>
Public Member Functions
PinChangedEventScope (Module *m)
~PinChangedEventScope ()
void send_events ()
Detailed Description
By creating an instance of this class a new scope gets created thus collecting events.
Definition at line 137 of file pin_event.h.
Constructor & Destructor Documentation
PinChangedEventScope()
hal::PinChangedEventScope::PinChangedEventScope (Module * m)
Constructor for scope instance incrementing scope count
Parameters
m The module comprising pins and pin groups
Definition at line 71 of file pin_event.cpp.
~PinChangedEventScope()
hal::PinChangedEventScope::~PinChangedEventScope ()
Destructor for scope instance decrementing scope count
Definition at line 81 of file pin_event.cpp.
Member Function Documentation
send_events()
void hal::PinChangedEventScope::send_events ()
Attempts to send all stacked events. Will do nothing if not issued from top-level scope.
Definition at line 94 of file pin_event.cpp.
Referenced by hal::Module::assign_pin_to_group(), hal::Module::create_pin_group(), and hal::Module::delete_pin_group().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/include/hal_core/netlist/gate_library/enums/pin_event.h
/home/runner/work/hal/hal/src/netlist/gate_library/enums/pin_event.cpp