HAL: hal::CommonSuccessorPredecessorGateQueue Class Reference
hal::CommonSuccessorPredecessorGateQueue Class Reference
#include <common_successor_predecessor.h>
Public Member Functions
CommonSuccessorPredecessorGateQueue (int i, Gate *g)
QList< Gate * > getNext (bool forward)
void setQueue (const QList< Gate * > &q)
int mask () const
QList< Gate * > waypoints (Gate *g) const
Detailed Description
Definition at line 37 of file common_successor_predecessor.h.
Constructor & Destructor Documentation
CommonSuccessorPredecessorGateQueue()
hal::CommonSuccessorPredecessorGateQueue::CommonSuccessorPredecessorGateQueue (int i, Gate * g)
Definition at line 11 of file common_successor_predecessor.cpp.
References test_plugin::g.
Member Function Documentation
getNext()
QList< Gate * > hal::CommonSuccessorPredecessorGateQueue::getNext (bool forward)
Definition at line 18 of file common_successor_predecessor.cpp.
References QList::append(), test_plugin::g, and hal::netlist_utils::get_next_gates().
mask()
int hal::CommonSuccessorPredecessorGateQueue::mask () const inline
Definition at line 47 of file common_successor_predecessor.h.
Referenced by hal::CommonSuccessorPredecessor::CommonSuccessorPredecessor().
setQueue()
void hal::CommonSuccessorPredecessorGateQueue::setQueue (const QList< Gate * > & q) inline
Definition at line 46 of file common_successor_predecessor.h.
waypoints()
QList< Gate * > hal::CommonSuccessorPredecessorGateQueue::waypoints (Gate * g) const
Definition at line 35 of file common_successor_predecessor.cpp.
References QList::append(), and test_plugin::g.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/gui_utils/common_successor_predecessor.h
/home/runner/work/hal/hal/plugins/gui/src/gui_utils/common_successor_predecessor.cpp