HAL: hal::ActionRenameObject Class Reference
hal::ActionRenameObject Class Reference
HAL Gui » User Actions
Renames an item.
#include <action_rename_object.h>
Public Member Functions
ActionRenameObject (const QString &name=QString())
bool exec () override
QString tagname () const override
void writeToXml (QXmlStreamWriter &xmlOut) const override
void readFromXml (QXmlStreamReader &xmlIn) override
void addToHash (QCryptographicHash &cryptoHash) const override
Public Member Functions inherited from hal::UserAction
virtual ~UserAction ()
virtual UserActionObject object () const
virtual void setObject (const UserActionObject &obj)
virtual void setParentObject (const UserActionObject &obj)
virtual UserActionObject parentObject () const
int compoundOrder () const
void setCompoundOrder (int cmpord)
qint64 timeStamp () const
QString cryptographicHash (int recordNo) const
UserAction * undoAction () const
QString debugDump () const
void setObjectLock (bool lock)
void setParentObjectLock (bool lock)
bool hasProjectModified () const
Additional Inherited Members
Protected Member Functions inherited from hal::UserAction
UserAction ()
void writeParentObjectToXml (QXmlStreamWriter &xmlOut) const
void readParentObjectFromXml (QXmlStreamReader &xmlIn)
Static Protected Member Functions inherited from hal::UserAction
static QString setToText (const QSet< u32 > &set)
static QSet< u32 > setFromText (const QString &s)
Protected Attributes inherited from hal::UserAction
UserActionObject mObject
UserActionObject mParentObject
int mCompoundOrder
UserAction * mUndoAction
qint64 mTimeStamp
bool mObjectLock
bool mParentObjectLock
bool mProjectModified
Detailed Description
Renames an item.
Assigns a new name to the UserActionObject's object. If the object is a pin or pingroup type the current name is used to identify the pin or group (configured by setPinOrPingroupIdentifier)
Undo Action: ActionRenameObject
Definition at line 41 of file action_rename_object.h.
Constructor & Destructor Documentation
ActionRenameObject()
hal::ActionRenameObject::ActionRenameObject (const QString & name = QString()) inline
Action constructor.
Parameters
name - The new name
Definition at line 51 of file action_rename_object.h.
Referenced by exec().
Member Function Documentation
addToHash()
void hal::ActionRenameObject::addToHash (QCryptographicHash & cryptoHash) const override virtual
Hook for derived classes to add parameter to cryptographic hash.
Parameters
cryptoHash - Additional hash data.
Reimplemented from hal::UserAction.
Definition at line 28 of file action_rename_object.cpp.
References QCryptographicHash::addData(), and QString::toUtf8().
exec()
bool hal::ActionRenameObject::exec () override virtual
Executes user interaction and returns true on success. Note: Each implementation of exec() must include a call to the exec() method of base class to store the UserAction object in history and to transfer its ownership.
Returns
True on success, False otherwise.
Reimplemented from hal::UserAction.
Definition at line 49 of file action_rename_object.cpp.
References ActionRenameObject(), hal::UserActionObjectType::Context, hal::UserAction::exec(), QString::fromStdString(), hal::UserActionObjectType::Gate, hal::gContentManager, hal::Netlist::get_gate_by_id(), hal::Netlist::get_module_by_id(), hal::Module::get_name(), hal::Gate::get_name(), hal::Netlist::get_net_by_id(), hal::Module::get_pin_by_id(), hal::Module::get_pin_group_by_id(), hal::GraphContextManager::getContextById(), hal::ContentManager::getGroupingManagerWidget(), hal::GroupingManagerWidget::getModel(), hal::gGraphContextManager, hal::gNetlist, hal::UserActionObjectType::Grouping, hal::UserActionObject::id(), hal::UserAction::mObject, hal::UserActionObjectType::Module, hal::UserAction::mParentObject, hal::UserAction::mUndoAction, hal::GraphContext::name(), hal::UserActionObjectType::Net, net, hal::UserActionObjectType::Pin, hal::UserActionObjectType::PinGroup, hal::GraphContextManager::renameGraphContextAction(), hal::GroupingTableModel::renameGrouping(), hal::Module::set_name(), hal::Gate::set_name(), hal::Module::set_pin_group_name(), hal::Module::set_pin_name(), hal::UserAction::setObject(), hal::UserAction::setParentObject(), QString::toStdString(), and hal::UserActionObject::type().
Referenced by hal::NetlistRelay::changeModuleName(), and hal::ModulePinsTree::handleContextMenuRequested().
readFromXml()
void hal::ActionRenameObject::readFromXml (QXmlStreamReader & xmlIn) override virtual
Reads user interaction as well as arguments from xml macro file.
Parameters
xmlIn - The xml reader.
Reimplemented from hal::UserAction.
Definition at line 39 of file action_rename_object.cpp.
References QXmlStreamReader::name(), QXmlStreamReader::readElementText(), QXmlStreamReader::readNextStartElement(), and hal::UserAction::readParentObjectFromXml().
tagname()
QString hal::ActionRenameObject::tagname () const override virtual
The xml tagname for the action is purely virtual and needs to be implemented in derived class.
Returns
The tagname.
Implements hal::UserAction.
Definition at line 23 of file action_rename_object.cpp.
References hal::ActionRenameObjectFactory::sFactory, and hal::UserActionFactory::tagname().
writeToXml()
void hal::ActionRenameObject::writeToXml (QXmlStreamWriter & xmlOut) const override virtual
Persist user interaction in xml macro file.
Parameters
xmlOut - The xml writer.
Reimplemented from hal::UserAction.
Definition at line 33 of file action_rename_object.cpp.
References hal::UserAction::writeParentObjectToXml(), and QXmlStreamWriter::writeTextElement().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/action_rename_object.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/action_rename_object.cpp