HAL: hal::GraphicsGate Class Reference
hal::GraphicsGate Class Reference
HAL Gui » Graph Widget » Visuals
Abstract base class for gates.
#include <graphics_gate.h>
Public Member Functions
GraphicsGate (Gate *g)
Public Member Functions inherited from hal::GraphicsNode
GraphicsNode (const ItemType type, const u32 id, const QString &name)
virtual QRectF boundingRect () const override
virtual QPainterPath shape () const override
virtual QPointF getInputScenePosition (const u32 mNetId, const QString &pin_type) const =0
virtual QPointF getOutputScenePosition (const u32 mNetId, const QString &pin_type) const =0
virtual QPointF endpointPositionByIndex (int index, bool isInput) const =0
virtual float yEndpointDistance () const =0
virtual float yTopPinDistance () const =0
int inputByNet (u32 netId) const
int outputByNet (u32 netId) const
QList< u32 > inputNets () const
QList< u32 > outputNets () const
virtual void setVisuals (const Visuals &v)
qreal width () const
qreal height () const
void set_name (const QString &name)
Public Member Functions inherited from hal::GraphicsItem
GraphicsItem (const ItemType type, const u32 id)
ItemType itemType () const
u32 id () const
void setHightlight (bool hl)
Public Member Functions inherited from QGraphicsItem
QGraphicsItem (QGraphicsItem *parent)
virtual ~QGraphicsItem ()
QGraphicsScene * scene () const const
QGraphicsItem * parentItem () const const
QGraphicsItem * topLevelItem () const const
QGraphicsObject * parentObject () const const
QGraphicsWidget * parentWidget () const const
QGraphicsWidget * topLevelWidget () const const
QGraphicsWidget * window () const const
QGraphicsItem * panel () const const
void setParentItem (QGraphicsItem *newParent)
QList< QGraphicsItem * > children () const const
QList< QGraphicsItem * > childItems () const const
bool isWidget () const const
bool isWindow () const const
bool isPanel () const const
QGraphicsObject * toGraphicsObject ()
const QGraphicsObject * toGraphicsObject () const const
QGraphicsItemGroup * group () const const
void setGroup (QGraphicsItemGroup *group)
QGraphicsItem::GraphicsItemFlags flags () const const
void setFlag (QGraphicsItem::GraphicsItemFlag flag, bool enabled)
void setFlags (QGraphicsItem::GraphicsItemFlags flags)
QGraphicsItem::CacheMode cacheMode () const const
void setCacheMode (QGraphicsItem::CacheMode mode, const QSize &logicalCacheSize)
QGraphicsItem::PanelModality panelModality () const const
void setPanelModality (QGraphicsItem::PanelModality panelModality)
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel) const const
QString toolTip () const const
void setToolTip (const QString &toolTip)
QCursor cursor () const const
void setCursor (const QCursor &cursor)
bool hasCursor () const const
void unsetCursor ()
bool isVisible () const const
bool isVisibleTo (const QGraphicsItem *parent) const const
void setVisible (bool visible)
void hide ()
void show ()
bool isEnabled () const const
void setEnabled (bool enabled)
bool isSelected () const const
void setSelected (bool selected)
bool acceptDrops () const const
void setAcceptDrops (bool on)
qreal opacity () const const
qreal effectiveOpacity () const const
void setOpacity (qreal opacity)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
Qt::MouseButtons acceptedMouseButtons () const const
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
bool acceptsHoverEvents () const const
void setAcceptsHoverEvents (bool enabled)
bool acceptHoverEvents () const const
void setAcceptHoverEvents (bool enabled)
bool acceptTouchEvents () const const
void setAcceptTouchEvents (bool enabled)
bool filtersChildEvents () const const
void setFiltersChildEvents (bool enabled)
bool handlesChildEvents () const const
void setHandlesChildEvents (bool enabled)
bool isActive () const const
void setActive (bool active)
bool hasFocus () const const
void setFocus (Qt::FocusReason focusReason)
void clearFocus ()
QGraphicsItem * focusProxy () const const
void setFocusProxy (QGraphicsItem *item)
QGraphicsItem * focusItem () const const
void grabMouse ()
void ungrabMouse ()
void grabKeyboard ()
void ungrabKeyboard ()
QPointF pos () const const
qreal x () const const
void setX (qreal x)
qreal y () const const
void setY (qreal y)
QPointF scenePos () const const
void setPos (const QPointF &pos)
void setPos (qreal x, qreal y)
void moveBy (qreal dx, qreal dy)
void ensureVisible (const QRectF &rect, int xmargin, int ymargin)
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin, int ymargin)
QMatrix matrix () const const
QMatrix sceneMatrix () const const
void setMatrix (const QMatrix &matrix, bool combine)
void resetMatrix ()
QTransform transform () const const
QTransform sceneTransform () const const
QTransform deviceTransform (const QTransform &viewportTransform) const const
QTransform itemTransform (const QGraphicsItem *other, bool *ok) const const
void setTransform (const QTransform &matrix, bool combine)
void resetTransform ()
void rotate (qreal angle)
void scale (qreal sx, qreal sy)
void shear (qreal sh, qreal sv)
void translate (qreal dx, qreal dy)
void setRotation (qreal angle)
qreal rotation () const const
void setScale (qreal factor)
qreal scale () const const
QList< QGraphicsTransform * > transformations () const const
void setTransformations (const QList< QGraphicsTransform * > &transformations)
QPointF transformOriginPoint () const const
void setTransformOriginPoint (const QPointF &origin)
void setTransformOriginPoint (qreal x, qreal y)
virtual void advance (int phase)
qreal zValue () const const
void setZValue (qreal z)
void stackBefore (const QGraphicsItem *sibling)
QRectF childrenBoundingRect () const const
QRectF sceneBoundingRect () const const
bool isClipped () const const
QPainterPath clipPath () const const
virtual bool contains (const QPointF &point) const const
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode) const const
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode) const const
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode) const const
bool isObscured (const QRectF &rect) const const
bool isObscured (qreal x, qreal y, qreal w, qreal h) const const
virtual bool isObscuredBy (const QGraphicsItem *item) const const
virtual QPainterPath opaqueArea () const const
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const const
qreal boundingRegionGranularity () const const
void setBoundingRegionGranularity (qreal granularity)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)=0
void update (const QRectF &rect)
void update (qreal x, qreal y, qreal width, qreal height)
void scroll (qreal dx, qreal dy, const QRectF &rect)
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const const
QPointF mapToParent (const QPointF &point) const const
QPointF mapToScene (const QPointF &point) const const
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const const
QPolygonF mapToParent (const QRectF &rect) const const
QPolygonF mapToScene (const QRectF &rect) const const
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const const
QRectF mapRectToParent (const QRectF &rect) const const
QRectF mapRectToScene (const QRectF &rect) const const
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const const
QPolygonF mapToParent (const QPolygonF &polygon) const const
QPolygonF mapToScene (const QPolygonF &polygon) const const
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const const
QPainterPath mapToParent (const QPainterPath &path) const const
QPainterPath mapToScene (const QPainterPath &path) const const
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const const
QPointF mapFromParent (const QPointF &point) const const
QPointF mapFromScene (const QPointF &point) const const
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const const
QPolygonF mapFromParent (const QRectF &rect) const const
QPolygonF mapFromScene (const QRectF &rect) const const
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const const
QRectF mapRectFromParent (const QRectF &rect) const const
QRectF mapRectFromScene (const QRectF &rect) const const
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const const
QPolygonF mapFromParent (const QPolygonF &polygon) const const
QPolygonF mapFromScene (const QPolygonF &polygon) const const
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const const
QPainterPath mapFromParent (const QPainterPath &path) const const
QPainterPath mapFromScene (const QPainterPath &path) const const
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const const
QPointF mapToParent (qreal x, qreal y) const const
QPointF mapToScene (qreal x, qreal y) const const
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const const
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const const
QPointF mapFromParent (qreal x, qreal y) const const
QPointF mapFromScene (qreal x, qreal y) const const
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const const
bool isAncestorOf (const QGraphicsItem *child) const const
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const const
bool isUnderMouse () const const
QVariant data (int key) const const
void setData (int key, const QVariant &value)
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
virtual int type () const const
void installSceneEventFilter (QGraphicsItem *filterItem)
void removeSceneEventFilter (QGraphicsItem *filterItem)
T qgraphicsitem_cast (QGraphicsItem *item)
Protected Attributes
Gate * mGate
QString mType
QVector< QString > mInputPins
QVector< QString > mOutputPins
Protected Attributes inherited from hal::GraphicsNode
QString mNodeText [3]
qreal mWidth
qreal mHeight
QMultiHash< u32, int > mInputByNet
QMultiHash< u32, int > mOutputByNet
Protected Attributes inherited from hal::GraphicsItem
ItemType mItemType
bool mHighlight
u32 mId
QColor mColor
Additional Inherited Members
Public Types inherited from QGraphicsItem
enum GraphicsItemFlag
enum GraphicsItemChange
enum CacheMode
enum PanelModality
enum anonymous
Static Public Member Functions inherited from hal::GraphicsItem
static void loadSettings ()
static void setLod (const qreal lod)
Public Attributes inherited from QGraphicsItem
typedef GraphicsItemFlags
ItemIsMovable
ItemIsSelectable
ItemIsFocusable
ItemClipsToShape
ItemClipsChildrenToShape
ItemIgnoresTransformations
ItemIgnoresParentOpacity
ItemDoesntPropagateOpacityToChildren
ItemStacksBehindParent
ItemUsesExtendedStyleOption
ItemHasNoContents
ItemSendsGeometryChanges
ItemAcceptsInputMethod
ItemNegativeZStacksBehindParent
ItemIsPanel
ItemIsFocusScope
ItemSendsScenePositionChanges
ItemStopsClickFocusPropagation
ItemStopsFocusHandling
ItemContainsChildrenInShape
ItemPositionChange
ItemMatrixChange
ItemVisibleChange
ItemEnabledChange
ItemSelectedChange
ItemParentChange
ItemChildAddedChange
ItemChildRemovedChange
ItemTransformChange
ItemPositionHasChanged
ItemTransformHasChanged
ItemSceneChange
ItemVisibleHasChanged
ItemEnabledHasChanged
ItemSelectedHasChanged
ItemParentHasChanged
ItemSceneHasChanged
ItemCursorChange
ItemCursorHasChanged
ItemToolTipChange
ItemToolTipHasChanged
ItemFlagsChange
ItemFlagsHaveChanged
ItemZValueChange
ItemZValueHasChanged
ItemOpacityChange
ItemOpacityHasChanged
ItemScenePositionHasChanged
ItemRotationChange
ItemRotationHasChanged
ItemScaleChange
ItemScaleHasChanged
ItemTransformOriginPointChange
ItemTransformOriginPointHasChanged
NoCache
ItemCoordinateCache
DeviceCoordinateCache
NonModal
PanelModal
SceneModal
Type
UserType
Protected Member Functions inherited from hal::GraphicsItem
QColor penColor (QStyle::State state, const QColor &colorHint=QColor()) const
QColor selectionColor () const
QColor groupingColor () const
Protected Member Functions inherited from QGraphicsItem
void updateMicroFocus ()
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
virtual bool sceneEvent (QEvent *event)
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
virtual void inputMethodEvent (QInputMethodEvent *event)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
virtual QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
void prepareGeometryChange ()
Static Protected Attributes inherited from hal::GraphicsItem
static qreal sLod
static QColor sSelectionColor
static QColor sHighlightColor
Detailed Description
Abstract base class for gates.
Abstract base class for GraphicsGates. Besides the functionality already provided by its superclass GraphicsNode it stores the list of input and output pin type names of the GraphicsGate as well as the typename of the GraphicsGate itself.
Definition at line 45 of file graphics_gate.h.
Constructor & Destructor Documentation
GraphicsGate()
hal::GraphicsGate::GraphicsGate (Gate * g)
Constructor.
Parameters
g - The underlying gate of the GraphicsGate
Definition at line 8 of file graphics_gate.cpp.
References QVector::append(), QString::fromStdString(), test::g, hal::Net::get_id(), hal::GateType::get_input_pins(), hal::GateType::get_name(), hal::GateType::get_output_pins(), QMultiHash::insert(), hal::GraphicsNode::mInputByNet, mInputPins, hal::GraphicsNode::mNodeText, hal::GraphicsNode::mOutputByNet, mOutputPins, and QVector::size().
Member Data Documentation
mGate
Gate* hal::GraphicsGate::mGate protected
Pointer to gate in hal core
Definition at line 60 of file graphics_gate.h.
mInputPins
QVector<QString> hal::GraphicsGate::mInputPins protected
The input pin type identifiers of the underlying gate (from top to bottom)
Definition at line 70 of file graphics_gate.h.
Referenced by hal::StandardGraphicsGate::getInputScenePosition(), GraphicsGate(), and hal::StandardGraphicsGate::paint().
mOutputPins
QVector<QString> hal::GraphicsGate::mOutputPins protected
The output pin type identifiers of the underlying gate (from top to bottom)
Definition at line 75 of file graphics_gate.h.
Referenced by hal::StandardGraphicsGate::getOutputScenePosition(), GraphicsGate(), and hal::StandardGraphicsGate::paint().
mType
QString hal::GraphicsGate::mType protected
The gate type of the underlying gate
Definition at line 65 of file graphics_gate.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/items/nodes/gates/graphics_gate.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/items/nodes/gates/graphics_gate.cpp