HAL: hal::UserAction Class Reference
hal::UserAction Class Reference abstract
HAL Gui » User Actions
The UserAction class is the abstract base class for user interactions.
#include <user_action.h>
Public Member Functions
virtual ~UserAction ()
virtual bool exec ()
virtual QString tagname () const =0
virtual void writeToXml (QXmlStreamWriter &xmlOut) const
virtual void readFromXml (QXmlStreamReader &xmlIn)
virtual UserActionObject object () const
virtual void setObject (const UserActionObject &obj)
virtual void setParentObject (const UserActionObject &obj)
virtual UserActionObject parentObject () const
int compoundOrder () const
void setCompoundOrder (int cmpord)
qint64 timeStamp () const
QString cryptographicHash (int recordNo) const
virtual void addToHash (QCryptographicHash &cryptoHash) const
UserAction * undoAction () const
QString debugDump () const
void setObjectLock (bool lock)
void setParentObjectLock (bool lock)
bool hasProjectModified () const
Protected Member Functions
UserAction ()
void writeParentObjectToXml (QXmlStreamWriter &xmlOut) const
void readParentObjectFromXml (QXmlStreamReader &xmlIn)
Static Protected Member Functions
static QString setToText (const QSet< u32 > &set)
static QSet< u32 > setFromText (const QString &s)
Protected Attributes
UserActionObject mObject
UserActionObject mParentObject
int mCompoundOrder
UserAction * mUndoAction
qint64 mTimeStamp
bool mObjectLock
bool mParentObjectLock
bool mProjectModified
Detailed Description
The UserAction class is the abstract base class for user interactions.
It is expected that the exec() method gets called eventually. The derived classes exec() method contains the implementation of the command. The exec function of the base class needs to be called as well in order to store the interaction in the user action managers history. At this point the user action manager is also supposed to take the ownership of an user action object.
While derived classes might contain additional arguments the member variable mObject holds a standard argument like a single gate or module. Aditionally a parent object can be given so that special types like pingroups can be associated and/or identified with the corresponding module.
If pointer to mUndoAction is set the interaction might be reversed using Ctrl-Z in a future version of hal
The mCompoundOrder number is the index of this action if part of an action compound. It can be used to identify actions which belong together and might be undone in a single step.
Definition at line 56 of file user_action.h.
Constructor & Destructor Documentation
~UserAction()
hal::UserAction::~UserAction () virtual
The destructor.
Definition at line 19 of file user_action.cpp.
References mUndoAction.
UserAction()
hal::UserAction::UserAction () protected
Definition at line 12 of file user_action.cpp.
Member Function Documentation
addToHash()
void hal::UserAction::addToHash (QCryptographicHash & cryptoHash) const virtual
Hook for derived classes to add parameter to cryptographic hash.
Parameters
cryptoHash - Additional hash data.
Reimplemented in hal::ActionAddItemsToObject, hal::ActionReorderObject, hal::ActionMoveNode, hal::ActionRemoveItemsFromObject, hal::ActionSetSelectionFocus, hal::ActionRenameObject, hal::ActionCreateObject, hal::ActionOpenNetlistFile, hal::ActionSetObjectColor, hal::ActionSetObjectType, hal::ActionAddBooleanFunction, and hal::ActionSetObjectData.
Definition at line 105 of file user_action.cpp.
Referenced by cryptographicHash().
compoundOrder()
int hal::UserAction::compoundOrder () const inline
Get the order number in action compound, -1 if not in compound.
Returns
The order number in action compount.
Definition at line 132 of file user_action.h.
References mCompoundOrder.
Referenced by hal::UserActionManager::setStopRecording(), and hal::UserActionManager::undoLastAction().
cryptographicHash()
QString hal::UserAction::cryptographicHash (int recordNo) const
Get the cryptographic hash to detect manipulations in xml macro file.
Parameters
recordNo - A nonce.
Returns
The hash.
Definition at line 45 of file user_action.cpp.
References QCryptographicHash::addData(), addToHash(), QString::fromUtf8(), mObject, mParentObject, mTimeStamp, QCryptographicHash::result(), QCryptographicHash::Sha256, tagname(), and QByteArray::toHex().
Referenced by hal::UserActionManager::setStopRecording().
debugDump()
QString hal::UserAction::debugDump () const
Dump action in debug window.
Returns
The debug string.
Definition at line 110 of file user_action.cpp.
References QString::arg(), hal::UserActionObject::debugDump(), mCompoundOrder, mObject, and tagname().
Referenced by hal::UserActionManager::addExecutedAction().
exec()
bool hal::UserAction::exec () virtual
Executes user interaction and returns true on success. Note: Each implementation of exec() must include a call to the exec() method of base class to store the UserAction object in history and to transfer its ownership.
Returns
True on success, False otherwise.
Reimplemented in hal::ActionMoveNode, hal::ActionAddItemsToObject, hal::ActionSetSelectionFocus, hal::ActionRemoveItemsFromObject, hal::ActionReorderObject, hal::ActionFoldModule, hal::ActionUnfoldModule, hal::ActionRenameObject, hal::ActionCreateObject, hal::ActionOpenNetlistFile, hal::ActionSetObjectColor, hal::ActionSetObjectType, hal::ActionAddBooleanFunction, hal::ActionDeleteObject, hal::UserActionCompound, and hal::ActionSetObjectData.
Definition at line 24 of file user_action.cpp.
References hal::UserActionManager::addExecutedAction(), hal::gFileStatusManager, hasProjectModified(), hal::UserActionManager::instance(), mTimeStamp, hal::FileStatusManager::netlistChanged(), and hal::UserActionManager::timeStamp().
Referenced by hal::ActionSetObjectData::exec(), hal::ActionDeleteObject::exec(), hal::ActionAddBooleanFunction::exec(), hal::ActionSetObjectType::exec(), hal::ActionSetObjectColor::exec(), hal::ActionCreateObject::exec(), hal::ActionOpenNetlistFile::exec(), hal::ActionRenameObject::exec(), hal::ActionUnfoldModule::exec(), hal::ActionReorderObject::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionSetSelectionFocus::exec(), hal::ActionAddItemsToObject::exec(), hal::ActionMoveNode::exec(), and hal::UserActionManager::playMacro().
hasProjectModified()
bool hal::UserAction::hasProjectModified () const inline
Executing this action will modify the project thus a warning pops up when leaving hal without saving.
Returns
True if executing the action will modify the project, false otherwise.
Definition at line 195 of file user_action.h.
References mProjectModified.
Referenced by exec().
object()
virtual UserActionObject hal::UserAction::object () const inline virtual
Getter for object argument of interaction.
Returns
The object argument.
Definition at line 102 of file user_action.h.
References mObject.
Referenced by hal::ModuleWidget::openModuleInView(), and hal::UserActionManager::setStopRecording().
parentObject()
virtual UserActionObject hal::UserAction::parentObject () const inline virtual
Getter for parent object argument.
Returns
The parent object argument.
Definition at line 125 of file user_action.h.
References mParentObject.
Referenced by hal::UserActionCompound::exec().
readFromXml()
void hal::UserAction::readFromXml (QXmlStreamReader & xmlIn) virtual
Reads user interaction as well as arguments from xml macro file.
Parameters
xmlIn - The xml reader.
Reimplemented in hal::ActionAddItemsToObject, hal::ActionMoveNode, hal::ActionReorderObject, hal::ActionRemoveItemsFromObject, hal::ActionSetSelectionFocus, hal::ActionRenameObject, hal::ActionCreateObject, hal::ActionOpenNetlistFile, hal::ActionSetObjectColor, hal::ActionSetObjectType, hal::ActionAddBooleanFunction, hal::UserActionCompound, and hal::ActionSetObjectData.
Definition at line 100 of file user_action.cpp.
Referenced by hal::UserActionManager::getParsedAction().
readParentObjectFromXml()
void hal::UserAction::readParentObjectFromXml (QXmlStreamReader & xmlIn) protected
Utility function that can be used to read the parent object if necessary. (Also does the checking)
Parameters
xmlIn - The reader.
Definition at line 86 of file user_action.cpp.
References mParentObject, QXmlStreamReader::name(), hal::UserActionObject::readFromXml(), and QXmlStreamReader::readNext().
Referenced by hal::ActionCreateObject::readFromXml(), hal::ActionRenameObject::readFromXml(), hal::ActionRemoveItemsFromObject::readFromXml(), hal::ActionReorderObject::readFromXml(), and hal::ActionAddItemsToObject::readFromXml().
setCompoundOrder()
void hal::UserAction::setCompoundOrder (int cmpord) inline
Setter for compoundOrder.
Parameters
cmpord - The new compound order.
Definition at line 139 of file user_action.h.
References mCompoundOrder.
Referenced by hal::UserActionCompound::addAction(), and hal::UserActionManager::getParsedAction().
setFromText()
QSet< u32 > hal::UserAction::setFromText (const QString & s) static protected
Definition at line 68 of file user_action.cpp.
References QSet::insert(), and QString::split().
Referenced by hal::ActionSetSelectionFocus::readFromXml(), hal::ActionRemoveItemsFromObject::readFromXml(), and hal::ActionAddItemsToObject::readFromXml().
setObject()
void hal::UserAction::setObject (const UserActionObject & obj) virtual
Setter for object argument of interaction.
Parameters
obj - The object.
Reimplemented in hal::ActionSetSelectionFocus, and hal::ActionUnfoldModule.
Definition at line 33 of file user_action.cpp.
References mObject, and mObjectLock.
Referenced by hal::ActionAddBooleanFunction::ActionAddBooleanFunction(), hal::ActionCreateObject::ActionCreateObject(), hal::ActionFoldModule::ActionFoldModule(), hal::NetlistRelay::addSelectionToModule(), hal::NetlistRelay::changeModuleColor(), hal::NetlistRelay::changeModuleName(), hal::NetlistRelay::changeModuleType(), hal::NetlistRelay::deleteModule(), hal::GraphGraphicsView::dropEvent(), hal::ModulePinsTreeModel::dropMimeData(), hal::ActionSetObjectData::exec(), hal::UserActionCompound::exec(), hal::ActionDeleteObject::exec(), hal::ActionSetObjectType::exec(), hal::ActionSetObjectColor::exec(), hal::ActionCreateObject::exec(), hal::ActionRenameObject::exec(), hal::ActionFoldModule::exec(), hal::ActionReorderObject::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionAddItemsToObject::exec(), hal::ActionMoveNode::exec(), hal::UserActionManager::getParsedAction(), hal::SelectionDetailsWidget::groupingUnassignActionFactory(), hal::ModulePinsTree::handleContextMenuRequested(), hal::AddToModuleReceiver::handleModulesPicked(), hal::SelectionDetailsWidget::selectionToGroupingAction(), hal::ActionUnfoldModule::setObject(), and hal::ActionSetSelectionFocus::setObject().
setObjectLock()
void hal::UserAction::setObjectLock (bool lock) inline
Refuse set object requests (e.g. in UserActionCompound)
Parameters
lock - Param to set the lock.
Definition at line 182 of file user_action.h.
References mObjectLock.
Referenced by hal::SelectionDetailsWidget::groupingUnassignActionFactory().
setParentObject()
void hal::UserAction::setParentObject (const UserActionObject & obj) virtual
Setter for parent object argument. Used to identify pins and pingroups in which case the parent obj must be the corresponding module.
Parameters
obj - The parent object.
Definition at line 39 of file user_action.cpp.
References mParentObject, and mParentObjectLock.
Referenced by hal::ModulePinsTreeModel::dropMimeData(), hal::UserActionCompound::exec(), hal::ActionDeleteObject::exec(), hal::ActionSetObjectType::exec(), hal::ActionCreateObject::exec(), hal::ActionRenameObject::exec(), hal::ActionReorderObject::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionAddItemsToObject::exec(), and hal::ModulePinsTree::handleContextMenuRequested().
setParentObjectLock()
void hal::UserAction::setParentObjectLock (bool lock) inline
Refuse set parent object requests (in case if needed)
Parameters
lock - Param to set parent lock.
Definition at line 189 of file user_action.h.
References mParentObjectLock.
setToText()
QString hal::UserAction::setToText (const QSet< u32 > & set) static protected
Definition at line 57 of file user_action.cpp.
References QString::isEmpty(), QString::number(), and set().
Referenced by hal::ActionSetSelectionFocus::addToHash(), hal::ActionRemoveItemsFromObject::addToHash(), hal::ActionAddItemsToObject::addToHash(), hal::ActionSetSelectionFocus::writeToXml(), hal::ActionRemoveItemsFromObject::writeToXml(), and hal::ActionAddItemsToObject::writeToXml().
tagname()
virtual QString hal::UserAction::tagname () const pure virtual
The xml tagname for the action is purely virtual and needs to be implemented in derived class.
Returns
The tagname.
Implemented in hal::ActionAddItemsToObject, hal::ActionMoveNode, hal::ActionReorderObject, hal::ActionRemoveItemsFromObject, hal::ActionSetSelectionFocus, hal::ActionRenameObject, hal::ActionCreateObject, hal::ActionFoldModule, hal::ActionUnfoldModule, hal::ActionOpenNetlistFile, hal::ActionSetObjectColor, hal::ActionSetObjectType, hal::ActionAddBooleanFunction, hal::ActionDeleteObject, hal::UserActionCompound, and hal::ActionSetObjectData.
Referenced by cryptographicHash(), debugDump(), hal::UserActionManager::playMacro(), and hal::UserActionManager::setStopRecording().
timeStamp()
qint64 hal::UserAction::timeStamp () const inline
Get the time stamp for execution time.
Returns
The time stamp.
Definition at line 146 of file user_action.h.
References mTimeStamp.
Referenced by hal::UserActionManager::setStopRecording().
undoAction()
UserAction* hal::UserAction::undoAction () const inline
Get the action to reverse last action (nullptr if action cant be undone).
Returns
The reverse action.
Definition at line 168 of file user_action.h.
References mUndoAction.
Referenced by hal::UserActionManager::undoLastAction().
writeParentObjectToXml()
void hal::UserAction::writeParentObjectToXml (QXmlStreamWriter & xmlOut) const protected
Utility function to write the parent object. (Also checks if it is even necessary)
Parameters
xmlOut - The writer.
Definition at line 76 of file user_action.cpp.
References mParentObject, hal::UserActionObjectType::None, hal::UserActionObject::type(), QXmlStreamWriter::writeEndElement(), QXmlStreamWriter::writeStartElement(), and hal::UserActionObject::writeToXml().
Referenced by hal::ActionCreateObject::writeToXml(), hal::ActionRenameObject::writeToXml(), hal::ActionRemoveItemsFromObject::writeToXml(), hal::ActionReorderObject::writeToXml(), and hal::ActionAddItemsToObject::writeToXml().
writeToXml()
void hal::UserAction::writeToXml (QXmlStreamWriter & xmlOut) const virtual
Persist user interaction in xml macro file.
Parameters
xmlOut - The xml writer.
Reimplemented in hal::ActionAddItemsToObject, hal::ActionMoveNode, hal::ActionReorderObject, hal::ActionRemoveItemsFromObject, hal::ActionSetSelectionFocus, hal::ActionRenameObject, hal::ActionCreateObject, hal::ActionOpenNetlistFile, hal::ActionSetObjectColor, hal::ActionSetObjectType, hal::ActionAddBooleanFunction, hal::UserActionCompound, and hal::ActionSetObjectData.
Definition at line 95 of file user_action.cpp.
Referenced by hal::UserActionManager::setStopRecording().
Member Data Documentation
mCompoundOrder
int hal::UserAction::mCompoundOrder protected
Definition at line 201 of file user_action.h.
Referenced by compoundOrder(), debugDump(), and setCompoundOrder().
mObject
UserActionObject hal::UserAction::mObject protected
Definition at line 199 of file user_action.h.
Referenced by hal::SelectionRelay::clear(), cryptographicHash(), debugDump(), hal::ActionSetObjectData::exec(), hal::ActionDeleteObject::exec(), hal::ActionAddBooleanFunction::exec(), hal::ActionSetObjectType::exec(), hal::ActionSetObjectColor::exec(), hal::ActionCreateObject::exec(), hal::ActionRenameObject::exec(), hal::ActionUnfoldModule::exec(), hal::ActionFoldModule::exec(), hal::ActionReorderObject::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionSetSelectionFocus::exec(), hal::ActionAddItemsToObject::exec(), hal::ActionMoveNode::exec(), hal::ActionSetSelectionFocus::hasModifications(), object(), and setObject().
mObjectLock
bool hal::UserAction::mObjectLock protected
Definition at line 204 of file user_action.h.
Referenced by setObject(), and setObjectLock().
mParentObject
UserActionObject hal::UserAction::mParentObject protected
Definition at line 200 of file user_action.h.
Referenced by cryptographicHash(), hal::ActionDeleteObject::exec(), hal::ActionSetObjectType::exec(), hal::ActionCreateObject::exec(), hal::ActionRenameObject::exec(), hal::ActionReorderObject::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionAddItemsToObject::exec(), parentObject(), readParentObjectFromXml(), setParentObject(), and writeParentObjectToXml().
mParentObjectLock
bool hal::UserAction::mParentObjectLock protected
Definition at line 205 of file user_action.h.
Referenced by setParentObject(), and setParentObjectLock().
mProjectModified
bool hal::UserAction::mProjectModified protected
Definition at line 206 of file user_action.h.
Referenced by hal::ActionOpenNetlistFile::ActionOpenNetlistFile(), and hasProjectModified().
mTimeStamp
qint64 hal::UserAction::mTimeStamp protected
Definition at line 203 of file user_action.h.
Referenced by cryptographicHash(), exec(), and timeStamp().
mUndoAction
UserAction* hal::UserAction::mUndoAction protected
Definition at line 202 of file user_action.h.
Referenced by hal::ActionSetObjectData::exec(), hal::ActionDeleteObject::exec(), hal::ActionAddBooleanFunction::exec(), hal::ActionSetObjectType::exec(), hal::ActionSetObjectColor::exec(), hal::ActionCreateObject::exec(), hal::ActionRenameObject::exec(), hal::ActionUnfoldModule::exec(), hal::ActionReorderObject::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionSetSelectionFocus::exec(), hal::ActionAddItemsToObject::exec(), hal::ActionMoveNode::exec(), undoAction(), and ~UserAction().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/user_action.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/user_action.cpp