HAL: hal::ChannelModel Class Reference
hal::ChannelModel Class Reference
HAL Gui » Logging System
Table model for log channels.
#include <channel_model.h>
Signals
void updated (spdlog::level::level_enum t, const std::string &logger_name, std::string const &msg)
Public Member Functions
~ChannelModel () override
ChannelItem * addChannel (const QString name)
void handleLogmanagerCallback (const spdlog::level::level_enum &t, const std::string &channel_name, const std::string &msg_text)
Overwritten model functions
QVariant data (const QModelIndex &index, int role) const override
Qt::ItemFlags flags (const QModelIndex &index) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
Public Member Functions inherited from QAbstractTableModel
QAbstractTableModel (QObject *parent)
virtual ~QAbstractTableModel ()
virtual QModelIndex sibling (int row, int column, const QModelIndex &idx) const const override
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
virtual QModelIndex parent (const QModelIndex &index) const const=0
virtual bool hasChildren (const QModelIndex &parent) const const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role)
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const const
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
virtual QStringList mimeTypes () const const
virtual QMimeData * mimeData (const QModelIndexList &indexes) const const
virtual bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const const
virtual Qt::DropActions supportedDropActions () const const
virtual Qt::DropActions supportedDragActions () const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool insertRows (int row, int count, const QModelIndex &parent)
virtual bool insertColumns (int column, int count, const QModelIndex &parent)
virtual bool removeRows (int row, int count, const QModelIndex &parent)
virtual bool removeColumns (int column, int count, const QModelIndex &parent)
virtual bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual void fetchMore (const QModelIndex &parent)
virtual bool canFetchMore (const QModelIndex &parent) const const
virtual void sort (int column, Qt::SortOrder order)
virtual QModelIndex buddy (const QModelIndex &index) const const
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const
virtual QSize span (const QModelIndex &index) const const
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual bool submit ()
virtual void revert ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static ChannelModel * instance ()
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Additional Inherited Members
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Table model for log channels.
This model handles incoming callbacks from the core's log manager. It creates new channels and updates existing ones and is realized through a singleton pattern. It is implemented as a standard Qt tablemodel overwriting the necessary functions. Please refer to the Qt documentation for further details as to how to implement models.
Definition at line 47 of file channel_model.h.
Constructor & Destructor Documentation
~ChannelModel()
hal::ChannelModel::~ChannelModel () override
The destructor. Removes callback.
Definition at line 19 of file channel_model.cpp.
References hal::LogManager::get_gui_callback(), and hal::LogManager::get_instance().
Member Function Documentation
addChannel()
ChannelItem * hal::ChannelModel::addChannel (const QString name)
Adds a new channel with the given name to its temporary channel list.
Parameters
name - The name of the soon to be channel.
Returns
The created channel item.
Definition at line 102 of file channel_model.cpp.
References QAbstractItemModel::beginInsertRows(), QAbstractItemModel::beginRemoveRows(), QAbstractItemModel::endInsertRows(), QAbstractItemModel::endRemoveRows(), MAX_TEMP_CHANNELS, and name.
Referenced by handleLogmanagerCallback().
columnCount()
int hal::ChannelModel::columnCount (const QModelIndex & parent = QModelIndex()) const override virtual
Implements QAbstractItemModel.
Definition at line 94 of file channel_model.cpp.
References QObject::parent().
data()
QVariant hal::ChannelModel::data (const QModelIndex & index, int role) const override virtual
Implements QAbstractItemModel.
Definition at line 30 of file channel_model.cpp.
References Qt::DisplayRole, index(), QModelIndex::internalPointer(), QModelIndex::isValid(), and hal::ChannelItem::name().
flags()
Qt::ItemFlags hal::ChannelModel::flags (const QModelIndex & index) const override virtual
Reimplemented from QAbstractTableModel.
Definition at line 42 of file channel_model.cpp.
References QAbstractItemModel::flags(), index(), and QModelIndex::isValid().
handleLogmanagerCallback()
void hal::ChannelModel::handleLogmanagerCallback (const spdlog::level::level_enum & t, const std::string & channel_name, const std::string & msg_text)
This function manages the callback from the logmanager. It is registered in the model's constructor and checks if the channel for the message already exists. If yes, the message is added to channel. If not, the channel is created.
Parameters
t - The type of the message (debug, error,...).
channel_name - The channel of the message.
msg_text - The message itselft.
Definition at line 131 of file channel_model.cpp.
References addChannel(), ALL_CHANNEL, hal::ChannelItem::appendEntry(), QList::contains(), QString::fromStdString(), QObject::Q_EMIT(), and updated().
Referenced by hal::LoggerWidget::handleCustomChannel().
headerData()
QVariant hal::ChannelModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override virtual
Reimplemented from QAbstractItemModel.
Definition at line 50 of file channel_model.cpp.
References Qt::DisplayRole, and Qt::Horizontal.
index()
QModelIndex hal::ChannelModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const override virtual
Reimplemented from QAbstractTableModel.
Definition at line 63 of file channel_model.cpp.
References QAbstractItemModel::createIndex(), QAbstractItemModel::hasIndex(), and QObject::parent().
Referenced by data(), flags(), and hal::LoggerWidget::handleCurrentFilterChanged().
instance()
ChannelModel * hal::ChannelModel::instance () static
Get the singleton instance of the model.
Returns
The channel model instance.
Definition at line 24 of file channel_model.cpp.
Referenced by hal::ChannelSelector::ChannelSelector(), hal::LoggerWidget::handleCurrentFilterChanged(), hal::LoggerWidget::handleCustomChannel(), hal::ChannelSelector::keyPressEvent(), and hal::LoggerWidget::LoggerWidget().
rowCount()
int hal::ChannelModel::rowCount (const QModelIndex & parent = QModelIndex()) const override virtual
Implements QAbstractItemModel.
Definition at line 86 of file channel_model.cpp.
References QObject::parent().
Referenced by hal::LoggerWidget::handleCurrentFilterChanged().
updated
void hal::ChannelModel::updated (spdlog::level::level_enum t, const std::string & logger_name, std::string const & msg) signal
This signal is emitted at the end of handleLogmanagerCallback (when a new message was received from the logmanager).
Parameters
t - The type of the message.
logger_name - The channel of the message.
msg - The message itself.
Referenced by handleLogmanagerCallback().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/channel_manager/channel_model.h
/home/runner/work/hal/hal/plugins/gui/src/channel_manager/channel_model.cpp