HAL: hal::JsonWriteArray Class Reference
hal::JsonWriteArray Class Reference
#include <json_write_document.h>
Public Member Functions
JsonWriteArray (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteArray ()
JsonWriteArray & operator<< (const std::string &txt)
JsonWriteArray & operator<< (int ivalue)
JsonWriteArray & add_array ()
JsonWriteObject & add_object ()
Public Member Functions inherited from hal::JsonWriteComplex
JsonWriteComplex (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteComplex ()
void close ()
Public Member Functions inherited from hal::JsonWriteData
JsonWriteData (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteData ()
JsonWriteData & operator= (const std::string &txt)
JsonWriteData & operator= (int ivalue)
JsonWriteData & operator= (double value)
JsonWriteData & operator= (uint64_t u64Value)
Protected Member Functions
virtual void finalize (JsonWriteComplex *cplx) override
Protected Member Functions inherited from hal::JsonWriteData
virtual rapidjson::Document::AllocatorType & allocator ()
Friends
class JsonWriteData
class JsonWriteDocument
Additional Inherited Members
Protected Attributes inherited from hal::JsonWriteComplex
std::vector< JsonWriteData * > mChildData
rapidjson::Value mRapidValue
Protected Attributes inherited from hal::JsonWriteData
std::string mTagname
JsonWriteComplex * mParent
Detailed Description
Definition at line 182 of file json_write_document.h.
Constructor & Destructor Documentation
JsonWriteArray()
hal::JsonWriteArray::JsonWriteArray (const std::string & tag, JsonWriteComplex * parent)
Constructor
Parameters
[in] tag JSON tag name
[in] parent Parent instance
Definition at line 127 of file json_write_document.cpp.
References hal::JsonWriteComplex::mRapidValue.
~JsonWriteArray()
virtual hal::JsonWriteArray::~JsonWriteArray () inline virtual
Definition at line 198 of file json_write_document.h.
Member Function Documentation
add_array()
JsonWriteArray & hal::JsonWriteArray::add_array ()
Add child array to array
Returns
The JSON array where the array was added
Definition at line 144 of file json_write_document.cpp.
References hal::JsonWriteComplex::JsonWriteArray, and hal::JsonWriteComplex::mChildData.
add_object()
JsonWriteObject & hal::JsonWriteArray::add_object ()
Add child array to array
Returns
The JSON array where the array was added
Definition at line 151 of file json_write_document.cpp.
References hal::JsonWriteComplex::JsonWriteObject, and hal::JsonWriteComplex::mChildData.
Referenced by hal::GroupingSerializer::serialize().
finalize()
void hal::JsonWriteArray::finalize (JsonWriteComplex * cplx) override protected virtual
Implements hal::JsonWriteComplex.
Definition at line 158 of file json_write_document.cpp.
References hal::JsonWriteData::allocator(), and hal::JsonWriteComplex::mRapidValue.
operator<<() [1/2]
JsonWriteArray & hal::JsonWriteArray::operator<< (const std::string & txt)
Operator to add unnamed text field to array
Parameters
[in] txt The text content
Returns
The JSON array where the text was added
Definition at line 132 of file json_write_document.cpp.
References hal::JsonWriteData::allocator(), and hal::JsonWriteComplex::mRapidValue.
operator<<() [2/2]
JsonWriteArray & hal::JsonWriteArray::operator<< (int ivalue)
Operator to add an integer value to array
Parameters
[in] ivalue The integer value
Returns
The JSON array where the integer value was added
Definition at line 138 of file json_write_document.cpp.
References hal::JsonWriteData::allocator(), and hal::JsonWriteComplex::mRapidValue.
Friends And Related Function Documentation
JsonWriteData
friend class JsonWriteData friend
Definition at line 184 of file json_write_document.h.
JsonWriteDocument
friend class JsonWriteDocument friend
Definition at line 185 of file json_write_document.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/include/hal_core/utilities/json_write_document.h
/home/runner/work/hal/hal/src/utilities/json_write_document.cpp