HAL: hal::GuiPluginTable Class Reference
hal::GuiPluginTable Class Reference
#include <gui_plugin_manager.h>
Public Slots
void handleButtonPressed (const QModelIndex &buttonIndex)
void handlePluginLoaded (const QString &pluginName, const QString &path)
void handlePluginUnloaded (const QString &pluginName, const QString &path)
void handleRefresh ()
Signals
void toggleEnableGuiContribution (QString pluginName)
void showCliOptions (QString pluginName, QString cliOptions)
Public Member Functions
GuiPluginTable (GuiPluginManager *parent=nullptr)
~GuiPluginTable ()
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
BasePluginInterface * load (const QString &pluginName, const QString &path) const
QStringList neededBy (const QString &pluginName)
void persist ()
bool isLoaded (const QModelIndex &index) const
GuiPluginEntry::GuiExtensionState guiExtensionState (const QModelIndex &index) const
void setGuiExtensionState (const QString &pluginName, GuiPluginEntry::GuiExtensionState state)
bool hasCliExtension (const QModelIndex &index) const
bool isHalGui (const QModelIndex &index) const
void loadFeature (FacExtensionInterface::Feature ft, const QString &extension=QString())
SupportedFileFormats listFacFeature (FacExtensionInterface::Feature ft) const
GuiPluginEntry * at (int irow) const
int addExternalPlugin (const QString &path)
void removeEntry (int irow)
Public Member Functions inherited from QAbstractTableModel
QAbstractTableModel (QObject *parent)
virtual ~QAbstractTableModel ()
virtual QModelIndex index (int row, int column, const QModelIndex &parent) const const override
virtual QModelIndex sibling (int row, int column, const QModelIndex &idx) const const override
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
virtual Qt::ItemFlags flags (const QModelIndex &index) const const override
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
virtual QModelIndex parent (const QModelIndex &index) const const=0
virtual bool hasChildren (const QModelIndex &parent) const const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role)
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const const
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
virtual QStringList mimeTypes () const const
virtual QMimeData * mimeData (const QModelIndexList &indexes) const const
virtual bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const const
virtual Qt::DropActions supportedDropActions () const const
virtual Qt::DropActions supportedDragActions () const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool insertRows (int row, int count, const QModelIndex &parent)
virtual bool insertColumns (int column, int count, const QModelIndex &parent)
virtual bool removeRows (int row, int count, const QModelIndex &parent)
virtual bool removeColumns (int column, int count, const QModelIndex &parent)
virtual bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual void fetchMore (const QModelIndex &parent)
virtual bool canFetchMore (const QModelIndex &parent) const const
virtual void sort (int column, Qt::SortOrder order)
virtual QModelIndex buddy (const QModelIndex &index) const const
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const
virtual QSize span (const QModelIndex &index) const const
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual bool submit ()
virtual void revert ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Definition at line 119 of file gui_plugin_manager.h.
Constructor & Destructor Documentation
GuiPluginTable()
hal::GuiPluginTable::GuiPluginTable (GuiPluginManager * parent = nullptr)
Definition at line 349 of file gui_plugin_manager.cpp.
~GuiPluginTable()
hal::GuiPluginTable::~GuiPluginTable ()
Definition at line 357 of file gui_plugin_manager.cpp.
Member Function Documentation
addExternalPlugin()
int hal::GuiPluginTable::addExternalPlugin (const QString & path)
Definition at line 540 of file gui_plugin_manager.cpp.
References QFileInfo::baseName(), QAbstractItemModel::beginInsertRows(), QAbstractItemModel::beginRemoveRows(), QAbstractItemModel::endInsertRows(), QAbstractItemModel::endRemoveRows(), QMap::insert(), load(), hal::GuiPluginEntry::mExternalPath, hal::GuiPluginEntry::mLoadState, hal::GuiPluginEntry::mName, test::n, persist(), QMap::remove(), hal::GuiPluginEntry::updateFromLoaded(), and hal::GuiPluginEntry::UserLoad.
Referenced by hal::GuiPluginManager::handleLoadExternalPlugin().
at()
GuiPluginEntry * hal::GuiPluginTable::at (int irow) const
Definition at line 785 of file gui_plugin_manager.cpp.
Referenced by hal::GuiPluginDelegate::paint().
columnCount()
int hal::GuiPluginTable::columnCount (const QModelIndex & parent = QModelIndex()) const override virtual
Implements QAbstractItemModel.
Definition at line 757 of file gui_plugin_manager.cpp.
Referenced by handleButtonPressed().
data()
QVariant hal::GuiPluginTable::data (const QModelIndex & index, int role = Qt::DisplayRole) const override virtual
Implements QAbstractItemModel.
Definition at line 851 of file gui_plugin_manager.cpp.
References Qt::BackgroundRole, QModelIndex::column(), hal::GuiPluginManager::defaultTextColor, Qt::DisplayRole, Qt::ForegroundRole, hal::GuiPluginManager::hilightBackgroundColor, hal::GuiPluginManager::hilightTextColor, QAbstractTableModel::index(), QModelIndex::row(), and QVariant::toBool().
Referenced by hal::GuiPluginDelegate::paint().
guiExtensionState()
GuiPluginEntry::GuiExtensionState hal::GuiPluginTable::guiExtensionState (const QModelIndex & index) const
Definition at line 881 of file gui_plugin_manager.cpp.
References QAbstractTableModel::index(), QModelIndex::row(), and hal::GuiPluginEntry::Unknown.
Referenced by hal::GuiPluginDelegate::paint().
handleButtonPressed
void hal::GuiPluginTable::handleButtonPressed (const QModelIndex & buttonIndex) slot
Definition at line 790 of file gui_plugin_manager.cpp.
References QString::arg(), QModelIndex::column(), columnCount(), QAbstractItemModel::dataChanged(), QAbstractTableModel::index(), QString::isEmpty(), QList::isEmpty(), hal::GuiPluginEntry::isLoaded(), QStringList::join(), hal::plugin_manager::load(), hal::GuiPluginEntry::mCliOptions, hal::GuiPluginEntry::mFilePath, hal::GuiPluginEntry::mLoadState, hal::GuiPluginEntry::mName, neededBy(), hal::GuiPluginEntry::NotLoaded, persist(), QObject::Q_EMIT(), QModelIndex::row(), showCliOptions(), toggleEnableGuiContribution(), QString::toStdString(), hal::plugin_manager::unload(), hal::GuiPluginEntry::UserLoad, and QMessageBox::warning().
Referenced by hal::GuiPluginManager::GuiPluginManager().
handlePluginLoaded
void hal::GuiPluginTable::handlePluginLoaded (const QString & pluginName, const QString & path) slot
Definition at line 570 of file gui_plugin_manager.cpp.
References hal::GuiPluginEntry::AutoLoad.
Referenced by hal::GuiPluginManager::GuiPluginManager().
handlePluginUnloaded
void hal::GuiPluginTable::handlePluginUnloaded (const QString & pluginName, const QString & path) slot
Definition at line 576 of file gui_plugin_manager.cpp.
References hal::GuiPluginEntry::NotLoaded.
Referenced by hal::GuiPluginManager::GuiPluginManager().
handleRefresh
void hal::GuiPluginTable::handleRefresh () slot
Definition at line 362 of file gui_plugin_manager.cpp.
References QAbstractItemModel::beginResetModel(), and QAbstractItemModel::endResetModel().
Referenced by hal::GuiPluginManager::GuiPluginManager().
hasCliExtension()
bool hal::GuiPluginTable::hasCliExtension (const QModelIndex & index) const
Definition at line 895 of file gui_plugin_manager.cpp.
References QAbstractTableModel::index(), and QModelIndex::row().
Referenced by hal::GuiPluginDelegate::paint().
headerData()
QVariant hal::GuiPluginTable::headerData (int section, Qt::Orientation orientation, int role) const override virtual
Reimplemented from QAbstractItemModel.
Definition at line 762 of file gui_plugin_manager.cpp.
References Qt::DisplayRole, QAbstractItemModel::headerData(), and Qt::Horizontal.
isHalGui()
bool hal::GuiPluginTable::isHalGui (const QModelIndex & index) const
Definition at line 875 of file gui_plugin_manager.cpp.
References QAbstractTableModel::index(), and QModelIndex::row().
Referenced by hal::GuiPluginDelegate::paint().
isLoaded()
bool hal::GuiPluginTable::isLoaded (const QModelIndex & index) const
Definition at line 901 of file gui_plugin_manager.cpp.
References QAbstractTableModel::index(), and QModelIndex::row().
Referenced by hal::GuiPluginDelegate::paint().
listFacFeature()
SupportedFileFormats hal::GuiPluginTable::listFacFeature (FacExtensionInterface::Feature ft) const
Definition at line 609 of file gui_plugin_manager.cpp.
References QMap::insert(), hal::GuiPluginEntry::mDescription, hal::GuiPluginEntry::mFeature, and hal::GuiPluginEntry::mFeatureArguments.
Referenced by hal::MainWindow::handleActionImportNetlist().
load()
BasePluginInterface * hal::GuiPluginTable::load (const QString & pluginName, const QString & path) const
Definition at line 691 of file gui_plugin_manager.cpp.
References hal::plugin_manager::get_plugin_instance(), hal::plugin_manager::load(), log_warning, and QString::toStdString().
Referenced by addExternalPlugin(), and loadFeature().
loadFeature()
void hal::GuiPluginTable::loadFeature (FacExtensionInterface::Feature ft, const QString & extension = QString())
Definition at line 668 of file gui_plugin_manager.cpp.
References QString::isEmpty(), hal::GuiPluginEntry::isLoaded(), load(), hal::GuiPluginEntry::mFeature, hal::GuiPluginEntry::mFeatureArguments, hal::GuiPluginEntry::mFilePath, hal::GuiPluginEntry::mName, and hal::GuiPluginEntry::updateFromLoaded().
Referenced by hal::FileManager::deprecatedOpenFile(), hal::MainWindow::handleActionImportNetlist(), hal::GatelibraryContentWidget::handleSaveAction(), hal::GatelibraryContentWidget::handleSaveAsAction(), hal::GateLibraryManager::initialize(), and hal::FileManager::openProject().
neededBy()
QStringList hal::GuiPluginTable::neededBy (const QString & pluginName)
Definition at line 907 of file gui_plugin_manager.cpp.
References QList::append(), hal::GuiPluginEntry::isLoaded(), hal::GuiPluginEntry::mDependencies, and hal::GuiPluginEntry::mName.
Referenced by handleButtonPressed().
persist()
void hal::GuiPluginTable::persist ()
Definition at line 703 of file gui_plugin_manager.cpp.
References QSettings::beginWriteArray(), QSettings::clear(), QSettings::endArray(), hal::GuiPluginEntry::persist(), QSettings::setArrayIndex(), and QSettings::sync().
Referenced by addExternalPlugin(), handleButtonPressed(), and setGuiExtensionState().
removeEntry()
void hal::GuiPluginTable::removeEntry (int irow)
rowCount()
int hal::GuiPluginTable::rowCount (const QModelIndex & parent = QModelIndex()) const override virtual
Implements QAbstractItemModel.
Definition at line 752 of file gui_plugin_manager.cpp.
setGuiExtensionState()
void hal::GuiPluginTable::setGuiExtensionState (const QString & pluginName, GuiPluginEntry::GuiExtensionState state)
Definition at line 887 of file gui_plugin_manager.cpp.
References persist(), hal::state, and QMap::value().
showCliOptions
void hal::GuiPluginTable::showCliOptions (QString pluginName, QString cliOptions) signal
Referenced by hal::GuiPluginManager::GuiPluginManager(), and handleButtonPressed().
toggleEnableGuiContribution
void hal::GuiPluginTable::toggleEnableGuiContribution (QString pluginName) signal
Referenced by hal::GuiPluginManager::GuiPluginManager(), and handleButtonPressed().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/plugin_relay/gui_plugin_manager.h
/home/runner/work/hal/hal/plugins/gui/src/plugin_relay/gui_plugin_manager.cpp