HAL: hal::ModulePinsTreeModel Class Reference
hal::ModulePinsTreeModel Class Reference
A model to represent the ports of a module.
#include <port_tree_model.h>
Public Types
enum itemType { itemType::portSingleBit = 0, itemType::portMultiBit = 1, itemType::pin = 2, itemType::group = 3 }
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Signals
void numberOfPortsChanged (const int newNumber)
Public Member Functions
ModulePinsTreeModel (QObject *parent=nullptr)
~ModulePinsTreeModel ()
Qt::ItemFlags flags (const QModelIndex &index) const override
QStringList mimeTypes () const override
QMimeData * mimeData (const QModelIndexList &indexes) const override
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const override
void clear () override
void setModule (Module *m)
Net * getNetFromItem (TreeItem *item)
int getRepresentedModuleId ()
itemType getTypeOfItem (TreeItem *item) const
int getIdOfItem (TreeItem *item) const
Event Handler Functions
void handleModulePortsChanged (Module *m)
Public Member Functions inherited from hal::BaseTreeModel
BaseTreeModel (QObject *parent=nullptr)
void setContent (QList< TreeItem * > firstLevelItems)
void setHeaderLabels (QList< QVariant > labels)
QModelIndex getIndexFromItem (TreeItem *item) const
TreeItem * getItemFromIndex (QModelIndex index) const
TreeItem * getRootItem () const
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
virtual QModelIndex parent (const QModelIndex &index) const override
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const override
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const override
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
virtual QModelIndex sibling (int row, int column, const QModelIndex &index) const const
virtual bool hasChildren (const QModelIndex &parent) const const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role)
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const const
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
virtual Qt::DropActions supportedDropActions () const const
virtual Qt::DropActions supportedDragActions () const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool insertRows (int row, int count, const QModelIndex &parent)
virtual bool insertColumns (int column, int count, const QModelIndex &parent)
virtual bool removeRows (int row, int count, const QModelIndex &parent)
virtual bool removeColumns (int column, int count, const QModelIndex &parent)
virtual bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual void fetchMore (const QModelIndex &parent)
virtual bool canFetchMore (const QModelIndex &parent) const const
virtual void sort (int column, Qt::SortOrder order)
virtual QModelIndex buddy (const QModelIndex &index) const const
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const
virtual QSize span (const QModelIndex &index) const const
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual bool submit ()
virtual void revert ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Attributes
const QString keyType = "type"
const QString keyId = "id"
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Static Public Attributes
static const int sNameColumn = 0
static const int sDirectionColumn = 1
static const int sTypeColumn = 2
static const int sNetColumn = 3
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Attributes inherited from hal::BaseTreeModel
TreeItem * mRootItem
Properties inherited from QObject
objectName
Detailed Description
A model to represent the ports of a module.
Definition at line 41 of file port_tree_model.h.
Member Enumeration Documentation
itemType
enum hal::ModulePinsTreeModel::itemType strong
Enumerator
portSingleBit
portMultiBit
pin
group
Definition at line 48 of file port_tree_model.h.
Constructor & Destructor Documentation
ModulePinsTreeModel()
hal::ModulePinsTreeModel::ModulePinsTreeModel (QObject * parent = nullptr)
The constructor.
Parameters
parent - THe model's parent.
Definition at line 22 of file port_tree_model.cpp.
References QObject::connect(), hal::Netlist::get_module_by_id(), hal::gNetlist, hal::gNetlistRelay, handleModulePortsChanged(), hal::NetlistRelay::modulePortsChanged(), hal::BaseTreeModel::setHeaderLabels(), and setModule().
~ModulePinsTreeModel()
hal::ModulePinsTreeModel::~ModulePinsTreeModel ()
The destructor.
Definition at line 34 of file port_tree_model.cpp.
References hal::BaseTreeModel::mRootItem.
Member Function Documentation
canDropMimeData()
bool hal::ModulePinsTreeModel::canDropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) const override virtual
Reimplemented from QAbstractItemModel.
Definition at line 273 of file port_tree_model.cpp.
References control::action, hal::BaseTreeModel::data(), hal::BaseTreeModel::getItemFromIndex(), getTypeOfItem(), group, id, QObject::parent(), pin, QIODevice::ReadOnly, and type.
clear()
void hal::ModulePinsTreeModel::clear () override virtual
Overwritten BaseTreeModel function.
Reimplemented from hal::BaseTreeModel.
Definition at line 325 of file port_tree_model.cpp.
References hal::BaseTreeModel::clear().
Referenced by hal::ModulePinsTree::removeContent(), and setModule().
dropMimeData()
bool hal::ModulePinsTreeModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) override virtual
Reimplemented from QAbstractItemModel.
Definition at line 91 of file port_tree_model.cpp.
References control::action, hal::BaseTreeModel::data(), hal::BaseTreeModel::getItemFromIndex(), id, QObject::parent(), QIODevice::ReadOnly, and type.
flags()
Qt::ItemFlags hal::ModulePinsTreeModel::flags (const QModelIndex & index) const override virtual
Overwritten Qt function that is necessary for the model. For further information pleaser refer to the Qt documentation.
Reimplemented from hal::BaseTreeModel.
Definition at line 39 of file port_tree_model.cpp.
References hal::BaseTreeModel::flags(), hal::BaseTreeModel::index(), Qt::ItemIsDragEnabled, and Qt::ItemIsDropEnabled.
getIdOfItem()
int hal::ModulePinsTreeModel::getIdOfItem (TreeItem * item) const
Returns the pin-id if the item represents a pin or the pingroup-id if the item represents a pingroup.
Parameters
item - The item.
Returns
The pin- or pingroup-id.
Definition at line 457 of file port_tree_model.cpp.
References hal::TreeItem::getAdditionalData(), keyId, and QVariant::toInt().
Referenced by getNetFromItem(), hal::ModulePinsTree::handleContextMenuRequested(), and mimeData().
getNetFromItem()
Net * hal::ModulePinsTreeModel::getNetFromItem (TreeItem * item)
Get the underlying net from an (port) item. If this model does not represent a module or an invalid (port) item is given a nullptr is returned.
Parameters
item - The (port) item.
Returns
The net or nullptr.
Definition at line 425 of file port_tree_model.cpp.
References hal::Netlist::get_module_by_id(), hal::Module::get_pin_by_id(), getIdOfItem(), getTypeOfItem(), hal::gNetlist, portMultiBit, and type.
Referenced by hal::ModulePinsTree::handleContextMenuRequested().
getRepresentedModuleId()
int hal::ModulePinsTreeModel::getRepresentedModuleId ()
Get the id of the module that is currently represented. If no module is represented, -1 is returned.
Returns
The module id.
Definition at line 447 of file port_tree_model.cpp.
Referenced by hal::ModulePinsTree::handleContextMenuRequested().
getTypeOfItem()
ModulePinsTreeModel::itemType hal::ModulePinsTreeModel::getTypeOfItem (TreeItem * item) const
Get the type (enum) of a given item.
Parameters
item - The item for which the type is requested.
Returns
The item's type.
Definition at line 452 of file port_tree_model.cpp.
References hal::TreeItem::getAdditionalData(), keyType, and QVariant::value().
Referenced by canDropMimeData(), getNetFromItem(), hal::ModulePinsTree::handleContextMenuRequested(), and mimeData().
handleModulePortsChanged()
void hal::ModulePinsTreeModel::handleModulePortsChanged (Module * m)
Definition at line 462 of file port_tree_model.cpp.
References hal::Module::get_id(), and setModule().
Referenced by ModulePinsTreeModel().
mimeData()
QMimeData * hal::ModulePinsTreeModel::mimeData (const QModelIndexList & indexes) const override virtual
Reimplemented from QAbstractItemModel.
Definition at line 76 of file port_tree_model.cpp.
References hal::BaseTreeModel::data(), getIdOfItem(), hal::BaseTreeModel::getItemFromIndex(), getTypeOfItem(), pin, sNameColumn, type, and QIODevice::WriteOnly.
mimeTypes()
QStringList hal::ModulePinsTreeModel::mimeTypes () const override virtual
Reimplemented from QAbstractItemModel.
Definition at line 69 of file port_tree_model.cpp.
numberOfPortsChanged
void hal::ModulePinsTreeModel::numberOfPortsChanged (const int newNumber) signal
Q_SIGNAL that is emitted when the number of the model's port changed. (Primarily used to update 'the' section header in the details widget)
Parameters
newNumber - The new port count.
Referenced by hal::ModulePinsTree::ModulePinsTree(), and setModule().
setModule()
void hal::ModulePinsTreeModel::setModule (Module * m)
Sets up the model to display the module's ports.
Parameters
m - The module for which to display the ports.
Definition at line 335 of file port_tree_model.cpp.
References hal::TreeItem::appendChild(), QAbstractItemModel::beginResetModel(), clear(), QAbstractItemModel::endResetModel(), hal::enum_to_string(), QString::fromStdString(), QVariant::fromValue(), hal::Module::get_id(), hal::Module::get_pin_groups(), hal::Module::get_pins(), group, keyId, keyType, hal::BaseTreeModel::mRootItem, numberOfPortsChanged(), pin, QObject::Q_EMIT(), and hal::TreeItem::setAdditionalData().
Referenced by handleModulePortsChanged(), ModulePinsTreeModel(), and hal::ModulePinsTree::setModule().
Member Data Documentation
keyId
const QString hal::ModulePinsTreeModel::keyId = "id"
Definition at line 131 of file port_tree_model.h.
Referenced by getIdOfItem(), and setModule().
keyType
const QString hal::ModulePinsTreeModel::keyType = "type"
Definition at line 130 of file port_tree_model.h.
Referenced by getTypeOfItem(), and setModule().
sDirectionColumn
const int hal::ModulePinsTreeModel::sDirectionColumn = 1 static
Definition at line 125 of file port_tree_model.h.
Referenced by hal::ModulePinsTree::handleContextMenuRequested().
sNameColumn
const int hal::ModulePinsTreeModel::sNameColumn = 0 static
Definition at line 124 of file port_tree_model.h.
Referenced by hal::ModulePinsTree::handleContextMenuRequested(), and mimeData().
sNetColumn
const int hal::ModulePinsTreeModel::sNetColumn = 3 static
Definition at line 127 of file port_tree_model.h.
sTypeColumn
const int hal::ModulePinsTreeModel::sTypeColumn = 2 static
Definition at line 126 of file port_tree_model.h.
Referenced by hal::ModulePinsTree::handleContextMenuRequested().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/module_details_widget/port_tree_model.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/module_details_widget/port_tree_model.cpp