HAL: hal::CommentManager Class Reference
hal::CommentManager Class Reference
#include <comment_manager.h>
Signals
void entryAboutToBeDeleted (CommentEntry *entry)
void entryAdded (CommentEntry *entry)
void entryModified (CommentEntry *entry)
Public Member Functions
CommentManager (QObject *parent=nullptr)
~CommentManager ()
bool restore ()
std::string serialize (Netlist *netlist, const std::filesystem::path &savedir, bool isAutosave) override
void deserialize (Netlist *netlist, const std::filesystem::path &loaddir) override
void clear ()
QList< CommentEntry * > getEntriesForNode (const Node &nd) const
bool contains (const Node &nd) const
void deleteComment (CommentEntry *entry)
void addComment (CommentEntry *entry)
void relayEntryModified (CommentEntry *entry)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from hal::ProjectSerializer
ProjectSerializer (const std::string &name)
virtual ~ProjectSerializer ()
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Attributes inherited from hal::ProjectSerializer
std::string m_name
Properties inherited from QObject
objectName
Detailed Description
Definition at line 36 of file comment_manager.h.
Constructor & Destructor Documentation
CommentManager()
hal::CommentManager::CommentManager (QObject * parent = nullptr)
Definition at line 11 of file comment_manager.cpp.
~CommentManager()
hal::CommentManager::~CommentManager ()
Definition at line 15 of file comment_manager.cpp.
References clear().
Member Function Documentation
addComment()
void hal::CommentManager::addComment (CommentEntry * entry)
Adds a new comment Entry.
Parameters
entry - The new entry.
Definition at line 133 of file comment_manager.cpp.
References entryAdded(), hal::CommentEntry::getNode(), and QObject::Q_EMIT().
clear()
void hal::CommentManager::clear ()
Cleanup and clear when netlist gets closed
Definition at line 100 of file comment_manager.cpp.
Referenced by ~CommentManager().
contains()
bool hal::CommentManager::contains (const Node & nd) const
Return whether or not comment entries for node exist.
Parameters
nd The node key for search.
Returns
True if at least a single entry exists, false otherwise
Definition at line 112 of file comment_manager.cpp.
deleteComment()
void hal::CommentManager::deleteComment (CommentEntry * entry)
Removes and deletes the given entry. Before deleting the comment, the entryAboutToBeDeleted is emmitted. (Perhaps return true on success instead of just void?)
Parameters
nd
entry
Definition at line 117 of file comment_manager.cpp.
References entryAboutToBeDeleted(), hal::CommentEntry::getNode(), and QObject::Q_EMIT().
deserialize()
void hal::CommentManager::deserialize (Netlist * netlist, const std::filesystem::path & loaddir) override virtual
ProjectSerializer callback when project gets loaded
Parameters
netlist The current netlist (unused)
loaddir The directory from which the file gets loaded
Implements hal::ProjectSerializer.
Definition at line 45 of file comment_manager.cpp.
References hal::ProjectManager::get_filename(), hal::ProjectManager::instance(), hal::ProjectSerializer::m_name, and test_multiple::netlist.
entryAboutToBeDeleted
void hal::CommentManager::entryAboutToBeDeleted (CommentEntry * entry) signal
This signal is emmitted just before the entry is deleted (from the deleteComment function).
Parameters
entry - The entry that will be deleted.
Referenced by hal::CommentWidget::CommentWidget(), deleteComment(), and hal::GraphLayouter::GraphLayouter().
entryAdded
void hal::CommentManager::entryAdded (CommentEntry * entry) signal
This signal is emmitted when a new entry is added to the CommentManager (from the addComment function).
Parameters
entry - The entry that was added.
Referenced by addComment(), hal::CommentWidget::CommentWidget(), and hal::GraphLayouter::GraphLayouter().
entryModified
void hal::CommentManager::entryModified (CommentEntry * entry) signal
This signal is emmited whenever an entry is modified. To emit this signal, the function relayEntryModifed must be called from the instance that modified the entry. Similiar as to the selectionModel.
Parameters
entry - The modified entry.
Referenced by hal::CommentWidget::CommentWidget(), hal::GraphLayouter::GraphLayouter(), and relayEntryModified().
getEntriesForNode()
QList< CommentEntry * > hal::CommentManager::getEntriesForNode (const Node & nd) const
Get list of entries for node sorted by creation date. Developer might want to sort criteria parameter eventually.
Parameters
nd The node key for search.
Returns
List of pointer to entries.
Definition at line 107 of file comment_manager.cpp.
relayEntryModified()
void hal::CommentManager::relayEntryModified (CommentEntry * entry)
This function must be called whenever an instance modifies an entry. Similiar as to the selectionModel.
Parameters
entry - The modified entry.
sender - The sender.
Definition at line 143 of file comment_manager.cpp.
References entryModified(), and QObject::Q_EMIT().
restore()
bool hal::CommentManager::restore ()
Call to restore
Returns
true if successful, false otherwise
Definition at line 53 of file comment_manager.cpp.
References hal::ProjectManager::get_filename(), hal::ProjectManager::get_project_directory(), hal::ProjectManager::instance(), and hal::ProjectSerializer::m_name.
serialize()
std::string hal::CommentManager::serialize (Netlist * netlist, const std::filesystem::path & savedir, bool isAutosave) override virtual
ProjectSerializer callback gets called upon save and autosave
Parameters
netlist The current netlist (unused)
savedir The directory to which the project gets persisted
isAutosave Whether save request was issued from autosave (unused)
Returns
relative filename where the comments were saved
Implements hal::ProjectSerializer.
Definition at line 20 of file comment_manager.cpp.
References QDir::absoluteFilePath(), QJsonArray::append(), QJsonDocument::Compact, QString::fromStdString(), test_multiple::netlist, QFile::open(), hal::CommentEntry::toJson(), QString::toStdString(), QIODevice::write(), and QIODevice::WriteOnly.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/comment_system/comment_manager.h
/home/runner/work/hal/hal/plugins/gui/src/comment_system/comment_manager.cpp