HAL: hal::BasePin< T > Class Template Reference
hal::BasePin< T > Class Template Reference
HAL Core » Pins
#include <base_pin.h>
Public Member Functions
virtual ~BasePin ()=default
bool operator== (const BasePin &other) const
bool operator!= (const BasePin &other) const
ssize_t get_hash () const
u32 get_id () const
void set_name (const std::string &name)
const std::string & get_name () const
void set_direction (PinDirection direction)
PinDirection get_direction () const
void set_type (PinType type)
PinType get_type () const
const std::pair< PinGroup< T > *, i32 > & get_group () const
Protected Member Functions
BasePin (const u32 id, const std::string &name, PinDirection direction, PinType type=PinType::none)
Protected Attributes
u32 m_id
std::string m_name
PinDirection m_direction
PinType m_type
std::pair< PinGroup< T > *, i32 > m_group = {nullptr, 0}
Detailed Description
template<class T>
class hal::BasePin< T >
Base class for gate and module pins.
Definition at line 44 of file base_pin.h.
Constructor & Destructor Documentation
~BasePin()
template<class T > virtual hal::BasePin< T >::~BasePin () virtual default
BasePin()
template<class T > hal::BasePin< T >::BasePin (const u32 id, const std::string & name, PinDirection direction, PinType type = PinType::none) inline protected
Construct a new pin from its name, direction, and type.
Parameters
[in] id - The ID of the pin.
[in] name - The pin name.
[in] direction - The direction of the pin.
[in] type - The type of the pin.
Definition at line 186 of file base_pin.h.
Member Function Documentation
get_direction()
template<class T > PinDirection hal::BasePin< T >::get_direction () const inline
Get the direction of the pin.
Returns
The direction of the pin.
Definition at line 128 of file base_pin.h.
Referenced by hal::Gate::get_fan_in_endpoint(), hal::Gate::get_fan_out_endpoint(), hal::GateType::get_input_pin_names(), hal::Module::get_input_pin_names(), hal::GateType::get_input_pins(), hal::Module::get_input_pins(), hal::GateType::get_output_pin_names(), hal::Module::get_output_pin_names(), hal::GateType::get_output_pins(), hal::Module::get_output_pins(), hal::Gate::get_predecessor(), hal::Gate::get_resolved_boolean_function(), hal::Gate::get_successor(), hal::BasePin< GatePin >::operator==(), and hal::Module::remove_pin_from_group().
get_group()
template<class T > const std::pair<PinGroup<T>*, i32>& hal::BasePin< T >::get_group () const inline
Get the group of the pin as well as the index of the pin within the group.
Returns
The group and the index of the pin.
Definition at line 158 of file base_pin.h.
Referenced by hal::GateType::assign_pin_to_group(), hal::Module::assign_pin_to_group(), hal::ActionReorderObject::exec(), hal::BasePin< GatePin >::operator==(), and hal::TEST_F().
get_hash()
template<class T > ssize_t hal::BasePin< T >::get_hash () const inline
Hash function for python binding.
Returns
Pybind11 compatible hash.
Definition at line 77 of file base_pin.h.
get_id()
template<class T > u32 hal::BasePin< T >::get_id () const inline
TODO test, pybind Get the ID of the pin. The ID is unique within an entity, e.g., a module or a gate type.
Returns
The ID of the pin.
Definition at line 88 of file base_pin.h.
Referenced by hal::GateType::assign_pin_to_group(), hal::Module::assign_pin_to_group(), hal::Module::move_pin_within_group(), hal::BasePin< GatePin >::operator==(), hal::Module::remove_pin_from_group(), hal::Module::set_pin_name(), and hal::Module::set_pin_type().
get_name()
template<class T > const std::string& hal::BasePin< T >::get_name () const inline
Get the name of the pin.
Returns
The name of the pin.
Definition at line 108 of file base_pin.h.
Referenced by hal::GateType::assign_pin_to_group(), hal::Module::assign_pin_to_group(), hal::NetlistModificationDecorator::connect_gates(), hal::Gate::get_boolean_function(), hal::GateType::get_boolean_function(), hal::Gate::get_boolean_functions(), hal::Gate::get_fan_in_endpoint(), hal::Gate::get_fan_out_endpoint(), hal::Gate::get_predecessor(), hal::Gate::get_resolved_boolean_function(), hal::Gate::get_successor(), hal::Module::move_pin_within_group(), hal::BasePin< GatePin >::operator==(), hal::netlist_utils::remove_buffers(), hal::Module::remove_pin_from_group(), hal::Module::set_pin_name(), hal::Module::set_pin_type(), and hal::TEST_F().
get_type()
template<class T > PinType hal::BasePin< T >::get_type () const inline
Get the type of the pin.
Returns
The type of the pin.
Definition at line 148 of file base_pin.h.
Referenced by hal::Gate::get_boolean_function(), hal::BasePin< GatePin >::operator==(), hal::Module::remove_pin_from_group(), and hal::Module::set_pin_type().
operator!=()
template<class T > bool hal::BasePin< T >::operator!= (const BasePin< T > & other) const inline
Check whether two pins are unequal.
Parameters
[in] other - The pin to compare against.
Returns
True if both pins are unequal, false otherwise.
Definition at line 67 of file base_pin.h.
operator==()
template<class T > bool hal::BasePin< T >::operator== (const BasePin< T > & other) const inline
Check whether two pins are equal.
Parameters
[in] other - The pin to compare against.
Returns
True if both pins are equal, false otherwise.
Definition at line 55 of file base_pin.h.
Referenced by hal::BasePin< GatePin >::operator!=(), and hal::ModulePin::operator==().
set_direction()
template<class T > void hal::BasePin< T >::set_direction (PinDirection direction) inline
Set the direction of the pin.
Parameters
[in] direction - The pin direction.
Definition at line 118 of file base_pin.h.
set_name()
template<class T > void hal::BasePin< T >::set_name (const std::string & name) inline
Set the name of the pin.
Parameters
[in] name - The name of the pin.
Definition at line 98 of file base_pin.h.
Referenced by hal::Module::set_pin_name().
set_type()
template<class T > void hal::BasePin< T >::set_type (PinType type) inline
Set the type of the pin.
Parameters
[in] type - The pin type.
Definition at line 138 of file base_pin.h.
Referenced by hal::Module::set_pin_type().
Member Data Documentation
m_direction
template<class T > PinDirection hal::BasePin< T >::m_direction protected
Definition at line 174 of file base_pin.h.
Referenced by hal::BasePin< GatePin >::get_direction(), hal::BasePin< GatePin >::operator==(), and hal::BasePin< GatePin >::set_direction().
m_group
template<class T > std::pair<PinGroup<T>*, i32> hal::BasePin< T >::m_group = {nullptr, 0} protected
Definition at line 176 of file base_pin.h.
Referenced by hal::BasePin< GatePin >::get_group(), and hal::BasePin< GatePin >::operator==().
m_id
template<class T > u32 hal::BasePin< T >::m_id protected
Definition at line 172 of file base_pin.h.
Referenced by hal::BasePin< GatePin >::get_id(), and hal::BasePin< GatePin >::operator==().
m_name
template<class T > std::string hal::BasePin< T >::m_name protected
Definition at line 173 of file base_pin.h.
Referenced by hal::BasePin< GatePin >::get_name(), hal::BasePin< GatePin >::operator==(), and hal::BasePin< GatePin >::set_name().
m_type
template<class T > PinType hal::BasePin< T >::m_type protected
Definition at line 175 of file base_pin.h.
Referenced by hal::BasePin< GatePin >::get_type(), hal::BasePin< GatePin >::operator==(), and hal::BasePin< GatePin >::set_type().
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/include/hal_core/netlist/pins/base_pin.h