HAL: hal::ModuleContextMenu Class Reference
hal::ModuleContextMenu Class Reference
#include <module_context_menu.h>
Static Public Member Functions
static void addModuleSubmenu (QMenu *contextMenu, u32 id)
static void addGateSubmenu (QMenu *contextMenu, u32 id)
static void addNetSubmenu (QMenu *contextMenu, u32 id)
static void addMultipleElementsSubmenu (QMenu *contextMenu, const QSet< u32 > &modules=QSet< u32 >(), const QSet< u32 > &gates=QSet< u32 >(), const QSet< u32 > &nets=QSet< u32 >())
Detailed Description
Definition at line 9 of file module_context_menu.h.
Member Function Documentation
addGateSubmenu()
void hal::ModuleContextMenu::addGateSubmenu (QMenu * contextMenu, u32 id) static
Adds general context menu actions for a specified gate.
Parameters
contextMenu - The QMenu to which the actions are added to.
id - The id of the gate on which the actions will operate.
Definition at line 114 of file module_context_menu.cpp.
References QMenu::addAction(), hal::SelectionRelay::addGate(), QMenu::addMenu(), QMenu::addSeparator(), hal::NetlistRelay::addToModuleDialog(), hal::GroupingManagerWidget::assignElementsToGroupingDialog(), hal::NetlistRelay::changeElementNameDialog(), QGuiApplication::clipboard(), QSet::contains(), hal::ActionSetSelectionFocus::exec(), QString::fromStdString(), hal::Node::Gate, hal::ModuleItem::Gate, hal::UserActionObjectType::Gate, hal::gContentManager, hal::Netlist::get_gate_by_id(), hal::Gate::get_grouping(), hal::Gate::get_name(), hal::GateType::get_name(), hal::Gate::get_type(), hal::ContentManager::getGraphTabWidget(), hal::ContentManager::getGroupingManagerWidget(), hal::gGraphContextManager, hal::gNetlist, hal::gNetlistRelay, hal::gSelectionRelay, hal::GraphTabWidget::handleGateFocus(), id, QString::number(), hal::SelectionRelay::numberSelectedNodes(), hal::GraphContextManager::openGateInView(), hal::PyCodeProvider::pyCodeGate(), hal::SelectionRelay::relaySelectionChanged(), hal::GroupingManagerWidget::removeElementsFromGrouping(), hal::SelectionRelay::selectedGates(), QAction::setDisabled(), QAction::setEnabled(), hal::ActionSetSelectionFocus::setObject(), and QClipboard::setText().
Referenced by hal::ModuleElementsTree::handleContextMenuRequested(), hal::NetEndpointTable::handleContextMenuRequested(), and hal::ModuleWidget::handleTreeViewContextMenuRequested().
addModuleSubmenu()
void hal::ModuleContextMenu::addModuleSubmenu (QMenu * contextMenu, u32 id) static
Adds general context menu actions for a specified module.
Parameters
contextMenu - The QMenu to which the actions are added to.
id - The id of the module on which the actions will operate.
Definition at line 17 of file module_context_menu.cpp.
References QMenu::addAction(), hal::NetlistRelay::addChildModuleDialog(), QMenu::addMenu(), hal::SelectionRelay::addModule(), QMenu::addSeparator(), hal::NetlistRelay::addToModuleDialog(), hal::GroupingManagerWidget::assignElementsToGroupingDialog(), hal::NetlistRelay::changeElementNameDialog(), hal::NetlistRelay::changeModuleColorDialog(), hal::NetlistRelay::changeModuleTypeDialog(), QGuiApplication::clipboard(), QSet::contains(), hal::NetlistRelay::deleteModule(), hal::ActionSetSelectionFocus::exec(), QString::fromStdString(), hal::gContentManager, hal::Module::get_grouping(), hal::Netlist::get_module_by_id(), hal::Module::get_name(), hal::Netlist::get_top_module(), hal::Module::get_type(), hal::ContentManager::getGraphTabWidget(), hal::ContentManager::getGroupingManagerWidget(), hal::gGraphContextManager, hal::gNetlist, hal::gNetlistRelay, hal::gSelectionRelay, hal::GraphTabWidget::handleModuleFocus(), id, hal::Node::Module, hal::ModuleItem::Module, hal::UserActionObjectType::Module, hal::ShortestPath::module(), QString::number(), hal::SelectionRelay::numberSelectedNodes(), hal::GraphContextManager::openModuleInView(), hal::PyCodeProvider::pyCodeModule(), hal::SelectionRelay::relaySelectionChanged(), hal::GroupingManagerWidget::removeElementsFromGrouping(), hal::SelectionRelay::selectedModules(), QAction::setDisabled(), QAction::setEnabled(), hal::ActionSetSelectionFocus::setObject(), and QClipboard::setText().
Referenced by hal::ModuleElementsTree::handleContextMenuRequested(), hal::NetModuleTable::handleContextMenuRequested(), and hal::ModuleWidget::handleTreeViewContextMenuRequested().
addMultipleElementsSubmenu()
void hal::ModuleContextMenu::addMultipleElementsSubmenu (QMenu * contextMenu, const QSet< u32 > & modules = QSet<u32>(), const QSet< u32 > & gates = QSet<u32>(), const QSet< u32 > & nets = QSet<u32>()) static
Adds general context menu actions for multiple specified netlist elements.
Parameters
contextMenu - The QMenu to which the actions are added to.
modules - QSet with ids of modules on which the actions will operate.
gates - QSet with ids of gates on which the actions will operate.
nets - QSet with ids of nets on which the actions will operate.
Definition at line 262 of file module_context_menu.cpp.
References QMenu::addAction(), QMenu::addSeparator(), hal::NetlistRelay::addToModuleDialog(), hal::gContentManager, hal::ContentManager::getGroupingManagerWidget(), hal::gNetlistRelay, hal::gSelectionRelay, hal::SelectionRelay::numberSelectedNodes(), and QAction::setDisabled().
addNetSubmenu()
void hal::ModuleContextMenu::addNetSubmenu (QMenu * contextMenu, u32 id) static
Adds general context menu actions for a specified net.
Parameters
contextMenu - The QMenu to which the actions are added to.
id - The id of the net on which the actions will operate.
Definition at line 192 of file module_context_menu.cpp.
References QMenu::addAction(), QMenu::addMenu(), hal::SelectionRelay::addNet(), QMenu::addSeparator(), hal::GroupingManagerWidget::assignElementsToGroupingDialog(), hal::NetlistRelay::changeElementNameDialog(), QGuiApplication::clipboard(), QSet::contains(), hal::ActionSetSelectionFocus::exec(), QString::fromStdString(), hal::gContentManager, hal::Netlist::get_net_by_id(), hal::ContentManager::getGraphTabWidget(), hal::ContentManager::getGroupingManagerWidget(), hal::gGraphContextManager, hal::gNetlist, hal::gNetlistRelay, hal::gSelectionRelay, hal::GraphTabWidget::handleNetFocus(), id, hal::ModuleItem::Net, hal::UserActionObjectType::Net, net, QString::number(), hal::GraphContextManager::openNetEndpointsInView(), hal::PyCodeProvider::pyCodeNet(), hal::SelectionRelay::relaySelectionChanged(), hal::GroupingManagerWidget::removeElementsFromGrouping(), hal::SelectionRelay::selectedNets(), QAction::setDisabled(), QAction::setEnabled(), hal::ActionSetSelectionFocus::setObject(), and QClipboard::setText().
Referenced by hal::ModuleElementsTree::handleContextMenuRequested(), and hal::ModuleWidget::handleTreeViewContextMenuRequested().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/module_context_menu/module_context_menu.h
/home/runner/work/hal/hal/plugins/gui/src/module_context_menu/module_context_menu.cpp