HAL: hal::ModuleShader Class Reference
hal::ModuleShader Class Reference final
HAL Gui » Graph Widget » Visuals
Specifically stores/updates visual information about a module and its items.
#include <module_shader.h>
Public Member Functions
ModuleShader (const GraphContext *const context)
void add (const QSet< u32 > modules, const QSet< u32 > gates, const QSet< u32 > nets) override
void remove (const QSet< u32 > modules, const QSet< u32 > gates, const QSet< u32 > nets) override
void update () override
Public Member Functions inherited from hal::GraphShader
GraphShader (const GraphContext *const context)
virtual ~GraphShader ()=default
const Shading & getShading ()
Static Public Member Functions
static void debugSetNetColor (const QColor &color)
Additional Inherited Members
Protected Attributes inherited from hal::GraphShader
const GraphContext *const mContext
Shading mShading
Detailed Description
Specifically stores/updates visual information about a module and its items.
Definition at line 36 of file module_shader.h.
Constructor & Destructor Documentation
ModuleShader()
hal::ModuleShader::ModuleShader (const GraphContext *const context) explicit
Definition at line 12 of file module_shader.cpp.
Member Function Documentation
add()
void hal::ModuleShader::add (const QSet< u32 > modules, const QSet< u32 > gates, const QSet< u32 > nets) override virtual
Implements hal::GraphShader.
Definition at line 22 of file module_shader.cpp.
debugSetNetColor()
void hal::ModuleShader::debugSetNetColor (const QColor & color) static
Definition at line 17 of file module_shader.cpp.
remove()
void hal::ModuleShader::remove (const QSet< u32 > modules, const QSet< u32 > gates, const QSet< u32 > nets) override virtual
Implements hal::GraphShader.
Definition at line 29 of file module_shader.cpp.
update()
void hal::ModuleShader::update () override virtual
Implements hal::GraphShader.
Definition at line 36 of file module_shader.cpp.
References test_plugin::g, hal::GraphContext::gates(), hal::Netlist::get_gate_by_id(), hal::Module::get_id(), hal::NetlistRelay::getModuleColor(), hal::gNetlist, hal::gNetlistRelay, hal::GraphShader::mContext, hal::GraphShader::Shading::mGateVisuals, hal::GraphicsNode::Visuals::mMainColor, hal::GraphShader::Shading::mNetVisuals, hal::GraphContext::modules(), hal::GraphShader::Shading::mOduleVisuals, hal::GraphShader::mShading, hal::GraphicsNode::Visuals::mVisible, hal::GraphContext::nets(), Qt::SolidLine, and Qt::SolidPattern.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/shaders/module_shader.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/shaders/module_shader.cpp