HAL: hal::DetailsTableUtilities Class Reference
hal::DetailsTableUtilities Class Reference
HAL Gui » Utility Widgets » Selection Details Widget
Helper class consisting of usefull details-related functions.
#include <details_table_utilities.h>
Static Public Member Functions
static QSize tableViewSize (const QTableView *table, int nrows, int ncols)
static QSize tableWidgetSize (const QTableWidget *table)
static void setDefaultTableStyle (QTableView *table)
Detailed Description
Helper class consisting of usefull details-related functions.
A utility class used to gather details-tables related helperfunctions.
Definition at line 41 of file details_table_utilities.h.
Member Function Documentation
setDefaultTableStyle()
void hal::DetailsTableUtilities::setDefaultTableStyle (QTableView * table) static
Sets some basic properties of the table that are the same for all of the them.
Parameters
table - The table for which to set the default properties.
Definition at line 29 of file details_table_utilities.cpp.
References Qt::CustomContextMenu, QSizePolicy::Expanding, QSizePolicy::Fixed, QWidget::hide(), QTableView::horizontalHeader(), QHeaderView::length(), Qt::NoFocus, QFrame::NoFrame, QTableView::resizeColumnToContents(), Qt::ScrollBarAlwaysOff, QWidget::setContextMenuPolicy(), QHeaderView::setDefaultSectionSize(), QWidget::setFocusPolicy(), QFrame::setFrameStyle(), QAbstractScrollArea::setHorizontalScrollBarPolicy(), QWidget::setMaximumHeight(), QTableView::setShowGrid(), QWidget::setSizePolicy(), QAbstractScrollArea::setVerticalScrollBarPolicy(), and QTableView::verticalHeader().
tableViewSize()
QSize hal::DetailsTableUtilities::tableViewSize (const QTableView * table, int nrows, int ncols) static
Calculates the "actual" width and height for the given table.
Parameters
table - The view for which to calculate the size.
nrows - The view's (model's) number of rows.
ncols - The view's (model's) number of columns.
Returns
The calculated size of the table.
Definition at line 13 of file details_table_utilities.cpp.
References QTableView::columnWidth(), QWidget::height, QTableView::horizontalHeader(), QTableView::rowHeight(), QTableView::verticalHeader(), and QWidget::width.
Referenced by tableWidgetSize().
tableWidgetSize()
QSize hal::DetailsTableUtilities::tableWidgetSize (const QTableWidget * table) static
Caluclates the "actual" width and height for the given table.
Parameters
table - The table for which to calculate the size.
Returns
The calculated size of the table.
Definition at line 8 of file details_table_utilities.cpp.
References QTableWidget::columnCount, QTableWidget::rowCount, and tableViewSize().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/details_table_utilities.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/details_table_utilities.cpp