HAL: hal::UserActionCompound Class Reference
hal::UserActionCompound Class Reference
HAL Gui » User Actions
#include <user_action_compound.h>
Public Member Functions
UserActionCompound ()
void addAction (UserAction *act)
QString tagname () const override
bool exec () override
void writeToXml (QXmlStreamWriter &xmlOut) const
void readFromXml (QXmlStreamReader &xmlIn)
void setUseCreatedObject ()
Public Member Functions inherited from hal::UserAction
virtual ~UserAction ()
virtual UserActionObject object () const
virtual void setObject (const UserActionObject &obj)
virtual void setParentObject (const UserActionObject &obj)
virtual UserActionObject parentObject () const
int compoundOrder () const
void setCompoundOrder (int cmpord)
qint64 timeStamp () const
QString cryptographicHash (int recordNo) const
virtual void addToHash (QCryptographicHash &cryptoHash) const
UserAction * undoAction () const
QString debugDump () const
void setObjectLock (bool lock)
void setParentObjectLock (bool lock)
bool hasProjectModified () const
Protected Attributes
QList< UserAction * > mActionList
bool mUseCreatedObject
Protected Attributes inherited from hal::UserAction
UserActionObject mObject
UserActionObject mParentObject
int mCompoundOrder
UserAction * mUndoAction
qint64 mTimeStamp
bool mObjectLock
bool mParentObjectLock
bool mProjectModified
Additional Inherited Members
Protected Member Functions inherited from hal::UserAction
UserAction ()
void writeParentObjectToXml (QXmlStreamWriter &xmlOut) const
void readParentObjectFromXml (QXmlStreamReader &xmlIn)
Static Protected Member Functions inherited from hal::UserAction
static QString setToText (const QSet< u32 > &set)
static QSet< u32 > setFromText (const QString &s)
Detailed Description
Definition at line 35 of file user_action_compound.h.
Constructor & Destructor Documentation
UserActionCompound()
hal::UserActionCompound::UserActionCompound ()
Definition at line 20 of file user_action_compound.cpp.
Member Function Documentation
addAction()
void hal::UserActionCompound::addAction (UserAction * act)
Definition at line 24 of file user_action_compound.cpp.
References mActionList, and hal::UserAction::setCompoundOrder().
Referenced by hal::ModulePinsTreeModel::dropMimeData(), hal::ActionDeleteObject::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionAddItemsToObject::exec(), hal::GraphGraphicsView::handleShortestPath(), hal::GroupingManagerWidget::newGroupingByDistance(), hal::GroupingManagerWidget::newGroupingSuccOrPred(), hal::ModuleWidget::openModuleInView(), and hal::SelectionDetailsWidget::selectionToGroupingAction().
exec()
bool hal::UserActionCompound::exec () override virtual
Executes user interaction and returns true on success. Note: Each implementation of exec() must include a call to the exec() method of base class to store the UserAction object in history and to transfer its ownership.
Returns
True on success, False otherwise.
Reimplemented from hal::UserAction.
Definition at line 30 of file user_action_compound.cpp.
References mActionList, mUseCreatedObject, hal::UserAction::parentObject(), hal::UserAction::setObject(), and hal::UserAction::setParentObject().
Referenced by hal::ModulePinsTreeModel::dropMimeData(), hal::GraphGraphicsView::handleShortestPath(), hal::GroupingManagerWidget::newGroupingByDistance(), hal::GroupingManagerWidget::newGroupingSuccOrPred(), hal::ModuleWidget::openModuleInView(), and hal::SelectionDetailsWidget::selectionToGroupingAction().
readFromXml()
void hal::UserActionCompound::readFromXml (QXmlStreamReader & xmlIn) virtual
Reads user interaction as well as arguments from xml macro file.
Parameters
xmlIn - The xml reader.
Reimplemented from hal::UserAction.
Definition at line 60 of file user_action_compound.cpp.
References QXmlStreamReader::atEnd(), QXmlStreamReader::attributes(), hal::UserActionManager::getParsedAction(), hal::UserActionManager::instance(), QXmlStreamReader::isEndElement(), QXmlStreamReader::isStartElement(), mActionList, mUseCreatedObject, QXmlStreamReader::name(), QXmlStreamReader::readNext(), and QXmlStreamAttributes::value().
setUseCreatedObject()
void hal::UserActionCompound::setUseCreatedObject () inline
Definition at line 44 of file user_action_compound.h.
References mUseCreatedObject.
Referenced by hal::ActionDeleteObject::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionAddItemsToObject::exec(), hal::GraphGraphicsView::handleShortestPath(), hal::GroupingManagerWidget::newGroupingByDistance(), hal::GroupingManagerWidget::newGroupingSuccOrPred(), hal::ModuleWidget::openModuleInView(), and hal::SelectionDetailsWidget::selectionToGroupingAction().
tagname()
QString hal::UserActionCompound::tagname () const override virtual
The xml tagname for the action is purely virtual and needs to be implemented in derived class.
Returns
The tagname.
Implements hal::UserAction.
Definition at line 15 of file user_action_compound.cpp.
References hal::UserActionCompoundFactory::sFactory, and hal::UserActionFactory::tagname().
writeToXml()
void hal::UserActionCompound::writeToXml (QXmlStreamWriter & xmlOut) const virtual
Persist user interaction in xml macro file.
Parameters
xmlOut - The xml writer.
Reimplemented from hal::UserAction.
Definition at line 51 of file user_action_compound.cpp.
References mActionList, mUseCreatedObject, QXmlStreamWriter::writeAttribute(), QXmlStreamWriter::writeEndElement(), and QXmlStreamWriter::writeStartElement().
Member Data Documentation
mActionList
QList<UserAction*> hal::UserActionCompound::mActionList protected
Definition at line 47 of file user_action_compound.h.
Referenced by addAction(), exec(), readFromXml(), and writeToXml().
mUseCreatedObject
bool hal::UserActionCompound::mUseCreatedObject protected
Definition at line 48 of file user_action_compound.h.
Referenced by exec(), readFromXml(), setUseCreatedObject(), and writeToXml().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/user_action_compound.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/user_action_compound.cpp