HAL: hal::LayoutLockerManager Class Reference
hal::LayoutLockerManager Class Reference
#include <layout_locker.h>
Public Member Functions
void addLock ()
void removeLock ()
bool canUpdate (GraphContext *ctx)
void removeWaitingContext (GraphContext *ctx)
Static Public Member Functions
static LayoutLockerManager * instance ()
Detailed Description
Definition at line 35 of file layout_locker.h.
Member Function Documentation
addLock()
void hal::LayoutLockerManager::addLock ()
Definition at line 18 of file layout_locker.cpp.
canUpdate()
bool hal::LayoutLockerManager::canUpdate (GraphContext * ctx)
Definition at line 38 of file layout_locker.cpp.
References hal::GraphContext::id().
instance()
LayoutLockerManager * hal::LayoutLockerManager::instance () static
Definition at line 12 of file layout_locker.cpp.
Referenced by hal::GraphContext::~GraphContext().
removeLock()
void hal::LayoutLockerManager::removeLock ()
Definition at line 23 of file layout_locker.cpp.
References hal::GraphContextManager::getContextById(), and hal::gGraphContextManager.
removeWaitingContext()
void hal::LayoutLockerManager::removeWaitingContext (GraphContext * ctx)
Definition at line 46 of file layout_locker.cpp.
References hal::GraphContext::id().
Referenced by hal::GraphContext::~GraphContext().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layout_locker.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layout_locker.cpp