HAL: hal::LayoutLocker Class Reference
hal::LayoutLocker Class Reference
#include <layout_locker.h>
Public Member Functions
LayoutLocker ()
~LayoutLocker ()
Detailed Description
Definition at line 50 of file layout_locker.h.
Constructor & Destructor Documentation
LayoutLocker()
hal::LayoutLocker::LayoutLocker ()
Definition at line 47 of file layout_locker.cpp.
References hal::LayoutLockerManager::addLock(), and hal::LayoutLockerManager::instance().
~LayoutLocker()
hal::LayoutLocker::~LayoutLocker ()
Definition at line 52 of file layout_locker.cpp.
References hal::LayoutLockerManager::instance(), and hal::LayoutLockerManager::removeLock().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layout_locker.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layout_locker.cpp