HAL: hal::dataflow::ProgressPrinter Class Reference
hal::dataflow::ProgressPrinter Class Reference
#include <progress_printer.h>
Public Member Functions
ProgressPrinter (u32 max_message_size=0)
void print_progress (float progress, const std::string &message="")
void clear ()
void reset ()
Detailed Description
Definition at line 34 of file progress_printer.h.
Constructor & Destructor Documentation
ProgressPrinter()
hal::dataflow::ProgressPrinter::ProgressPrinter (u32 max_message_size = 0)
Definition at line 16 of file progress_printer.cpp.
References reset().
Member Function Documentation
clear()
void hal::dataflow::ProgressPrinter::clear ()
Definition at line 103 of file progress_printer.cpp.
Referenced by hal::dataflow::pre_processing::identify_register_stages().
print_progress()
void hal::dataflow::ProgressPrinter::print_progress (float progress, const std::string & message = "")
Definition at line 31 of file progress_printer.cpp.
References message(), hal::output, hal::GuiExtensionDataflow::s_progress_indicator_function, and control::str.
Referenced by hal::dataflow::pre_processing::identify_register_stages().
reset()
void hal::dataflow::ProgressPrinter::reset ()
Definition at line 112 of file progress_printer.cpp.
Referenced by ProgressPrinter().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/dataflow_analysis/include/dataflow_analysis/utils/progress_printer.h
/home/runner/work/hal/hal/plugins/dataflow_analysis/src/utils/progress_printer.cpp