HAL: hal::ProjectJson Class Reference
hal::ProjectJson Class Reference
#include <project_json.h>
Public Types
enum Status {
Ok = 0, NotExisting = -1, CannotOpen = -2, ParseError = -3,
NetlistError = -4, GatelibError = -5
}
Public Member Functions
ProjectJson (const QString &filename)
Status status () const
QString netlistFilename () const
QString gateLibraryFilename () const
void setGateLibraryFilename (const QString &gl)
Detailed Description
Definition at line 33 of file project_json.h.
Member Enumeration Documentation
Status
enum hal::ProjectJson::Status
Enumerator
Ok
NotExisting
CannotOpen
ParseError
NetlistError
GatelibError
Definition at line 35 of file project_json.h.
Constructor & Destructor Documentation
ProjectJson()
hal::ProjectJson::ProjectJson (const QString & filename)
Definition at line 7 of file project_json.cpp.
References CannotOpen, QJsonObject::contains(), hal::ff, QJsonDocument::fromJson(), GatelibError, QString::isEmpty(), QJsonDocument::isObject(), NetlistError, QJsonParseError::NoError, QJsonDocument::object(), Ok, ParseError, QFileInfo::path(), and QIODevice::ReadOnly.
Member Function Documentation
gateLibraryFilename()
QString hal::ProjectJson::gateLibraryFilename () const inline
Definition at line 48 of file project_json.h.
Referenced by hal::ExportProjectDialog::exportProject(), and hal::FileManager::openProject().
netlistFilename()
QString hal::ProjectJson::netlistFilename () const inline
Definition at line 47 of file project_json.h.
setGateLibraryFilename()
void hal::ProjectJson::setGateLibraryFilename (const QString & gl)
Definition at line 52 of file project_json.cpp.
References QDir::absoluteFilePath(), QJsonDocument::Compact, QJsonObject::insert(), QJsonDocument::object(), of, QFile::remove(), QJsonObject::remove(), QJsonDocument::toJson(), and QIODevice::WriteOnly.
Referenced by hal::ExportProjectDialog::exportProject().
status()
Status hal::ProjectJson::status () const inline
Definition at line 46 of file project_json.h.
Referenced by hal::ExportProjectDialog::exportProject().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/file_manager/project_json.h
/home/runner/work/hal/hal/plugins/gui/src/file_manager/project_json.cpp