HAL: hal::JsonWriteObject Class Reference
hal::JsonWriteObject Class Reference
#include <json_write_document.h>
Public Member Functions
JsonWriteObject (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteObject ()
JsonWriteData & operator[] (const std::string &tag)
JsonWriteObject & add_object (const std::string &tag)
JsonWriteArray & add_array (const std::string &tag)
Public Member Functions inherited from hal::JsonWriteComplex
JsonWriteComplex (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteComplex ()
void close ()
Public Member Functions inherited from hal::JsonWriteData
JsonWriteData (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteData ()
JsonWriteData & operator= (const std::string &txt)
JsonWriteData & operator= (int ivalue)
JsonWriteData & operator= (double value)
JsonWriteData & operator= (uint64_t u64Value)
Protected Member Functions
virtual void add_member (rapidjson::Document::ValueType &&name, rapidjson::Document::ValueType &&value, rapidjson::Document::AllocatorType &allocator)
virtual void finalize (JsonWriteComplex *cplx) override
Protected Member Functions inherited from hal::JsonWriteData
virtual rapidjson::Document::AllocatorType & allocator ()
Friends
class JsonWriteData
class JsonWriteDocument
Additional Inherited Members
Protected Attributes inherited from hal::JsonWriteComplex
std::vector< JsonWriteData * > mChildData
rapidjson::Value mRapidValue
Protected Attributes inherited from hal::JsonWriteData
std::string mTagname
JsonWriteComplex * mParent
Detailed Description
Definition at line 135 of file json_write_document.h.
Constructor & Destructor Documentation
JsonWriteObject()
hal::JsonWriteObject::JsonWriteObject (const std::string & tag, JsonWriteComplex * parent)
Constructor
Parameters
[in] tag JSON tag name
[in] parent Parent instance
Definition at line 90 of file json_write_document.cpp.
References hal::JsonWriteComplex::mRapidValue.
~JsonWriteObject()
virtual hal::JsonWriteObject::~JsonWriteObject () inline virtual
Definition at line 155 of file json_write_document.h.
Member Function Documentation
add_array()
JsonWriteArray & hal::JsonWriteObject::add_array (const std::string & tag)
Add child array
Parameters
[in] tag The tag name for child array
Returns
The child array created by method
Definition at line 114 of file json_write_document.cpp.
References hal::JsonWriteComplex::JsonWriteArray, and hal::JsonWriteComplex::mChildData.
Referenced by hal::GroupingSerializer::serialize().
add_member()
void hal::JsonWriteObject::add_member (rapidjson::Document::ValueType && name, rapidjson::Document::ValueType && value, rapidjson::Document::AllocatorType & allocator) protected virtual
Reimplemented in hal::JsonWriteDocument.
Definition at line 95 of file json_write_document.cpp.
References hal::JsonWriteData::allocator(), hal::JsonWriteComplex::mRapidValue, and name.
Referenced by hal::JsonWriteData::operator=().
add_object()
JsonWriteObject & hal::JsonWriteObject::add_object (const std::string & tag)
Add complex child object
Parameters
[in] tag The tag name for child object
Returns
The child object created by method
Definition at line 107 of file json_write_document.cpp.
References hal::JsonWriteComplex::JsonWriteObject, and hal::JsonWriteComplex::mChildData.
finalize()
void hal::JsonWriteObject::finalize (JsonWriteComplex * cplx) override protected virtual
Implements hal::JsonWriteComplex.
Reimplemented in hal::JsonWriteDocument.
Definition at line 121 of file json_write_document.cpp.
References hal::JsonWriteData::allocator(), hal::JsonWriteComplex::mRapidValue, and hal::JsonWriteData::mTagname.
operator[]()
JsonWriteData & hal::JsonWriteObject::operator[] (const std::string & tag)
Bracket operator to assign named tag
Parameters
[in] tag The tag name
Returns
The assigned JSON data instance
Definition at line 100 of file json_write_document.cpp.
References JsonWriteData, and hal::JsonWriteComplex::mChildData.
Friends And Related Function Documentation
JsonWriteData
friend class JsonWriteData friend
Definition at line 137 of file json_write_document.h.
Referenced by operator[]().
JsonWriteDocument
friend class JsonWriteDocument friend
Definition at line 138 of file json_write_document.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/include/hal_core/utilities/json_write_document.h
/home/runner/work/hal/hal/src/utilities/json_write_document.cpp