HAL: hal::GateInfoTable Class Reference
hal::GateInfoTable Class Reference
#include <gate_info_table.h>
Public Member Functions
GateInfoTable (QWidget *parent=nullptr)
void setGate (Gate *gate)
Public Member Functions inherited from hal::GeneralTableWidget
GeneralTableWidget (QWidget *parent=nullptr)
Public Member Functions inherited from QTableWidget
QTableWidget (QWidget *parent)
QTableWidget (int rows, int columns, QWidget *parent)
virtual ~QTableWidget ()
void setRowCount (int rows)
int rowCount () const const
void setColumnCount (int columns)
int columnCount () const const
int row (const QTableWidgetItem *item) const const
int column (const QTableWidgetItem *item) const const
QTableWidgetItem * item (int row, int column) const const
void setItem (int row, int column, QTableWidgetItem *item)
QTableWidgetItem * takeItem (int row, int column)
QTableWidgetItem * verticalHeaderItem (int row) const const
void setVerticalHeaderItem (int row, QTableWidgetItem *item)
QTableWidgetItem * takeVerticalHeaderItem (int row)
QTableWidgetItem * horizontalHeaderItem (int column) const const
void setHorizontalHeaderItem (int column, QTableWidgetItem *item)
QTableWidgetItem * takeHorizontalHeaderItem (int column)
void setVerticalHeaderLabels (const QStringList &labels)
void setHorizontalHeaderLabels (const QStringList &labels)
int currentRow () const const
int currentColumn () const const
QTableWidgetItem * currentItem () const const
void setCurrentItem (QTableWidgetItem *item)
void setCurrentItem (QTableWidgetItem *item, QItemSelectionModel::SelectionFlags command)
void setCurrentCell (int row, int column)
void setCurrentCell (int row, int column, QItemSelectionModel::SelectionFlags command)
void sortItems (int column, Qt::SortOrder order)
void editItem (QTableWidgetItem *item)
void openPersistentEditor (QTableWidgetItem *item)
void closePersistentEditor (QTableWidgetItem *item)
bool isPersistentEditorOpen (QTableWidgetItem *item) const const
QWidget * cellWidget (int row, int column) const const
void setCellWidget (int row, int column, QWidget *widget)
void removeCellWidget (int row, int column)
bool isItemSelected (const QTableWidgetItem *item) const const
void setItemSelected (const QTableWidgetItem *item, bool select)
void setRangeSelected (const QTableWidgetSelectionRange &range, bool select)
QList< QTableWidgetSelectionRange > selectedRanges () const const
QList< QTableWidgetItem * > selectedItems () const const
QList< QTableWidgetItem * > findItems (const QString &text, Qt::MatchFlags flags) const const
int visualRow (int logicalRow) const const
int visualColumn (int logicalColumn) const const
QTableWidgetItem * itemAt (const QPoint &point) const const
QTableWidgetItem * itemAt (int ax, int ay) const const
QRect visualItemRect (const QTableWidgetItem *item) const const
const QTableWidgetItem * itemPrototype () const const
void setItemPrototype (const QTableWidgetItem *item)
void scrollToItem (const QTableWidgetItem *item, QAbstractItemView::ScrollHint hint)
void insertRow (int row)
void insertColumn (int column)
void removeRow (int row)
void removeColumn (int column)
void clear ()
void clearContents ()
void itemPressed (QTableWidgetItem *item)
void itemClicked (QTableWidgetItem *item)
void itemDoubleClicked (QTableWidgetItem *item)
void itemActivated (QTableWidgetItem *item)
void itemEntered (QTableWidgetItem *item)
void itemChanged (QTableWidgetItem *item)
void currentItemChanged (QTableWidgetItem *current, QTableWidgetItem *previous)
void itemSelectionChanged ()
void cellPressed (int row, int column)
void cellClicked (int row, int column)
void cellDoubleClicked (int row, int column)
void cellActivated (int row, int column)
void cellEntered (int row, int column)
void cellChanged (int row, int column)
void currentCellChanged (int currentRow, int currentColumn, int previousRow, int previousColumn)
Public Member Functions inherited from QTableView
QTableView (QWidget *parent)
virtual ~QTableView ()
virtual void setModel (QAbstractItemModel *model) override
virtual void setRootIndex (const QModelIndex &index) override
virtual void setSelectionModel (QItemSelectionModel *selectionModel) override
QHeaderView * horizontalHeader () const const
QHeaderView * verticalHeader () const const
void setHorizontalHeader (QHeaderView *header)
void setVerticalHeader (QHeaderView *header)
int rowViewportPosition (int row) const const
int rowAt (int y) const const
void setRowHeight (int row, int height)
int rowHeight (int row) const const
int columnViewportPosition (int column) const const
int columnAt (int x) const const
void setColumnWidth (int column, int width)
int columnWidth (int column) const const
bool isRowHidden (int row) const const
void setRowHidden (int row, bool hide)
bool isColumnHidden (int column) const const
void setColumnHidden (int column, bool hide)
void setSortingEnabled (bool enable)
bool isSortingEnabled () const const
bool showGrid () const const
Qt::PenStyle gridStyle () const const
void setGridStyle (Qt::PenStyle style)
void setWordWrap (bool on)
bool wordWrap () const const
void setCornerButtonEnabled (bool enable)
bool isCornerButtonEnabled () const const
virtual QModelIndex indexAt (const QPoint &pos) const const override
void setSpan (int row, int column, int rowSpanCount, int columnSpanCount)
int rowSpan (int row, int column) const const
int columnSpan (int row, int column) const const
void clearSpans ()
void selectRow (int row)
void selectColumn (int column)
void hideRow (int row)
void hideColumn (int column)
void showRow (int row)
void showColumn (int column)
void resizeRowToContents (int row)
void resizeRowsToContents ()
void resizeColumnToContents (int column)
void resizeColumnsToContents ()
void sortByColumn (int column)
void sortByColumn (int column, Qt::SortOrder order)
void setShowGrid (bool show)
Public Member Functions inherited from QAbstractItemView
QAbstractItemView (QWidget *parent)
virtual ~QAbstractItemView ()
QAbstractItemModel * model () const const
QItemSelectionModel * selectionModel () const const
void setItemDelegate (QAbstractItemDelegate *delegate)
QAbstractItemDelegate * itemDelegate () const const
void setSelectionMode (QAbstractItemView::SelectionMode mode)
QAbstractItemView::SelectionMode selectionMode () const const
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
QAbstractItemView::SelectionBehavior selectionBehavior () const const
QModelIndex currentIndex () const const
QModelIndex rootIndex () const const
void setEditTriggers (QAbstractItemView::EditTriggers triggers)
QAbstractItemView::EditTriggers editTriggers () const const
void setVerticalScrollMode (QAbstractItemView::ScrollMode mode)
QAbstractItemView::ScrollMode verticalScrollMode () const const
void resetVerticalScrollMode ()
void setHorizontalScrollMode (QAbstractItemView::ScrollMode mode)
QAbstractItemView::ScrollMode horizontalScrollMode () const const
void resetHorizontalScrollMode ()
void setAutoScroll (bool enable)
bool hasAutoScroll () const const
void setAutoScrollMargin (int margin)
int autoScrollMargin () const const
void setTabKeyNavigation (bool enable)
bool tabKeyNavigation () const const
void setDropIndicatorShown (bool enable)
bool showDropIndicator () const const
void setDragEnabled (bool enable)
bool dragEnabled () const const
void setDragDropOverwriteMode (bool overwrite)
bool dragDropOverwriteMode () const const
void setDragDropMode (QAbstractItemView::DragDropMode behavior)
QAbstractItemView::DragDropMode dragDropMode () const const
void setDefaultDropAction (Qt::DropAction dropAction)
Qt::DropAction defaultDropAction () const const
void setAlternatingRowColors (bool enable)
bool alternatingRowColors () const const
void setIconSize (const QSize &size)
QSize iconSize () const const
void setTextElideMode (Qt::TextElideMode mode)
Qt::TextElideMode textElideMode () const const
virtual void keyboardSearch (const QString &search)
virtual QRect visualRect (const QModelIndex &index) const const=0
virtual void scrollTo (const QModelIndex &index, QAbstractItemView::ScrollHint hint)=0
QSize sizeHintForIndex (const QModelIndex &index) const const
void openPersistentEditor (const QModelIndex &index)
void closePersistentEditor (const QModelIndex &index)
bool isPersistentEditorOpen (const QModelIndex &index) const const
void setIndexWidget (const QModelIndex &index, QWidget *widget)
QWidget * indexWidget (const QModelIndex &index) const const
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
QAbstractItemDelegate * itemDelegateForRow (int row) const const
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
QAbstractItemDelegate * itemDelegateForColumn (int column) const const
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const override
virtual void reset ()
virtual void selectAll ()
void edit (const QModelIndex &index)
void clearSelection ()
void setCurrentIndex (const QModelIndex &index)
void scrollToTop ()
void scrollToBottom ()
void update (const QModelIndex &index)
void pressed (const QModelIndex &index)
void clicked (const QModelIndex &index)
void doubleClicked (const QModelIndex &index)
void activated (const QModelIndex &index)
void entered (const QModelIndex &index)
void viewportEntered ()
void iconSizeChanged (const QSize &size)
Public Member Functions inherited from QAbstractScrollArea
QAbstractScrollArea (QWidget *parent)
virtual ~QAbstractScrollArea ()
Qt::ScrollBarPolicy verticalScrollBarPolicy () const const
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
QScrollBar * verticalScrollBar () const const
void setVerticalScrollBar (QScrollBar *scrollBar)
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const const
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
QScrollBar * horizontalScrollBar () const const
void setHorizontalScrollBar (QScrollBar *scrollBar)
QWidget * cornerWidget () const const
void setCornerWidget (QWidget *widget)
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
QWidget * viewport () const const
void setViewport (QWidget *widget)
QSize maximumViewportSize () const const
virtual QSize minimumSizeHint () const const override
virtual QSize sizeHint () const const override
virtual void setupViewport (QWidget *viewport)
QAbstractScrollArea::SizeAdjustPolicy sizeAdjustPolicy () const const
void setSizeAdjustPolicy (QAbstractScrollArea::SizeAdjustPolicy policy)
Public Member Functions inherited from QFrame
QFrame (QWidget *parent, Qt::WindowFlags f)
virtual ~QFrame ()
int frameStyle () const const
void setFrameStyle (int style)
int frameWidth () const const
QFrame::Shape frameShape () const const
void setFrameShape (QFrame::Shape)
QFrame::Shadow frameShadow () const const
void setFrameShadow (QFrame::Shadow)
int lineWidth () const const
void setLineWidth (int)
int midLineWidth () const const
void setMidLineWidth (int)
QRect frameRect () const const
void setFrameRect (const QRect &)
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
virtual void setVisible (bool visible)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Additional Inherited Members
Public Types inherited from QAbstractItemView
enum SelectionMode
enum SelectionBehavior
enum ScrollHint
enum EditTrigger
enum ScrollMode
enum DragDropMode
enum CursorAction
enum State
enum DropIndicatorPosition
Public Types inherited from QAbstractScrollArea
enum SizeAdjustPolicy
Public Types inherited from QFrame
enum Shape
enum Shadow
enum StyleMask
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemView
typedef EditTriggers
NoSelection
SingleSelection
MultiSelection
ExtendedSelection
ContiguousSelection
SelectItems
SelectRows
SelectColumns
EnsureVisible
PositionAtTop
PositionAtBottom
PositionAtCenter
NoEditTriggers
CurrentChanged
DoubleClicked
SelectedClicked
EditKeyPressed
AnyKeyPressed
AllEditTriggers
ScrollPerItem
ScrollPerPixel
NoDragDrop
DragOnly
DropOnly
DragDrop
InternalMove
MoveUp
MoveDown
MoveLeft
MoveRight
MoveHome
MoveEnd
MovePageUp
MovePageDown
MoveNext
MovePrevious
NoState
DraggingState
DragSelectingState
EditingState
ExpandingState
CollapsingState
AnimatingState
OnItem
AboveItem
BelowItem
OnViewport
Public Attributes inherited from QAbstractScrollArea
AdjustIgnored
AdjustToContentsOnFirstShow
AdjustToContents
Public Attributes inherited from QFrame
NoFrame
Box
Panel
WinPanel
HLine
VLine
StyledPanel
Plain
Raised
Sunken
Shadow_Mask
Shape_Mask
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Protected Member Functions inherited from hal::GeneralTableWidget
void setRow (const QString &key, const QString &val, QMenu *contextMenu=nullptr, std::function< void()> doubleClickAction=nullptr)
void copyToClipboard (const QString &text) const
void adjustSize ()
Protected Member Functions inherited from QTableWidget
virtual bool event (QEvent *e) override
virtual QStringList mimeTypes () const const
virtual QMimeData * mimeData (const QList< QTableWidgetItem * > items) const const
virtual bool dropMimeData (int row, int column, const QMimeData *data, Qt::DropAction action)
virtual Qt::DropActions supportedDropActions () const const
QList< QTableWidgetItem * > items (const QMimeData *data) const const
QModelIndex indexFromItem (const QTableWidgetItem *item) const const
QTableWidgetItem * itemFromIndex (const QModelIndex &index) const const
virtual void dropEvent (QDropEvent *event) override
Protected Member Functions inherited from QTableView
void rowMoved (int row, int oldIndex, int newIndex)
void columnMoved (int column, int oldIndex, int newIndex)
void rowResized (int row, int oldHeight, int newHeight)
void columnResized (int column, int oldWidth, int newWidth)
void rowCountChanged (int oldCount, int newCount)
void columnCountChanged (int oldCount, int newCount)
virtual QStyleOptionViewItem viewOptions () const const override
virtual void paintEvent (QPaintEvent *event) override
virtual void timerEvent (QTimerEvent *event) override
virtual int horizontalOffset () const const override
virtual int verticalOffset () const const override
virtual QModelIndex moveCursor (QAbstractItemView::CursorAction cursorAction, Qt::KeyboardModifiers modifiers) override
virtual void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags flags) override
virtual QModelIndexList selectedIndexes () const const override
virtual void updateGeometries () override
virtual QSize viewportSizeHint () const const override
virtual int sizeHintForRow (int row) const const override
virtual int sizeHintForColumn (int column) const const override
virtual bool isIndexHidden (const QModelIndex &index) const const override
virtual void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected) override
virtual void currentChanged (const QModelIndex &current, const QModelIndex &previous) override
Protected Member Functions inherited from QAbstractItemView
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
virtual void rowsInserted (const QModelIndex &parent, int start, int end)
virtual void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
virtual void commitData (QWidget *editor)
virtual void editorDestroyed (QObject *editor)
void setHorizontalStepsPerItem (int steps)
int horizontalStepsPerItem () const const
void setVerticalStepsPerItem (int steps)
int verticalStepsPerItem () const const
virtual QRegion visualRegionForSelection (const QItemSelection &selection) const const=0
virtual bool edit (const QModelIndex &index, QAbstractItemView::EditTrigger trigger, QEvent *event)
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event) const const
virtual void startDrag (Qt::DropActions supportedActions)
QAbstractItemView::State state () const const
void setState (QAbstractItemView::State state)
void scheduleDelayedItemsLayout ()
void executeDelayedItemsLayout ()
void setDirtyRegion (const QRegion &region)
void scrollDirtyRegion (int dx, int dy)
QPoint dirtyRegionOffset () const const
virtual bool focusNextPrevChild (bool next) override
virtual bool viewportEvent (QEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void mouseDoubleClickEvent (QMouseEvent *event) override
virtual void dragEnterEvent (QDragEnterEvent *event) override
virtual void dragMoveEvent (QDragMoveEvent *event) override
virtual void dragLeaveEvent (QDragLeaveEvent *event) override
virtual void focusInEvent (QFocusEvent *event) override
virtual void focusOutEvent (QFocusEvent *event) override
virtual void keyPressEvent (QKeyEvent *event) override
virtual void resizeEvent (QResizeEvent *event) override
virtual void inputMethodEvent (QInputMethodEvent *event) override
virtual bool eventFilter (QObject *object, QEvent *event) override
QAbstractItemView::DropIndicatorPosition dropIndicatorPosition () const const
Protected Member Functions inherited from QAbstractScrollArea
void setViewportMargins (int left, int top, int right, int bottom)
void setViewportMargins (const QMargins &margins)
QMargins viewportMargins () const const
virtual void wheelEvent (QWheelEvent *e) override
virtual void contextMenuEvent (QContextMenuEvent *e) override
virtual void scrollContentsBy (int dx, int dy)
Protected Member Functions inherited from QFrame
virtual void changeEvent (QEvent *ev) override
void initStyleOption (QStyleOptionFrame *option) const const
Protected Member Functions inherited from QWidget
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void closeEvent (QCloseEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void showEvent (QShowEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Properties inherited from QTableWidget
rowCount
columnCount
Properties inherited from QTableView
showGrid
gridStyle
sortingEnabled
wordWrap
cornerButtonEnabled
Properties inherited from QAbstractItemView
autoScroll
autoScrollMargin
editTriggers
tabKeyNavigation
showDropIndicator
dragEnabled
dragDropOverwriteMode
dragDropMode
defaultDropAction
alternatingRowColors
selectionMode
selectionBehavior
iconSize
textElideMode
verticalScrollMode
horizontalScrollMode
Properties inherited from QAbstractScrollArea
verticalScrollBarPolicy
horizontalScrollBarPolicy
sizeAdjustPolicy
Properties inherited from QFrame
frameShape
frameShadow
lineWidth
midLineWidth
frameWidth
frameRect
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Detailed Description
Definition at line 35 of file gate_info_table.h.
Constructor & Destructor Documentation
GateInfoTable()
hal::GateInfoTable::GateInfoTable (QWidget * parent = nullptr)
The constructor.
Parameters
parent - The widget's parent.
Definition at line 25 of file gate_info_table.cpp.
References QMenu::addAction(), QMenu::addSection(), QObject::connect(), hal::NetlistRelay::gateLocationChanged(), hal::NetlistRelay::gateNameChanged(), hal::NetlistRelay::gateRemoved(), hal::gNetlistRelay, hal::NetlistRelay::moduleGateAssigned(), and hal::NetlistRelay::moduleNameChanged().
Member Function Documentation
setGate()
void hal::GateInfoTable::setGate (Gate * gate)
Updates the table with the data of the gate.
Parameters
gate - The gate.
Definition at line 72 of file gate_info_table.cpp.
References hal::GeneralTableWidget::adjustSize(), hal::gNetlist, hal::Netlist::is_gate_in_netlist(), and hal::GeneralTableWidget::setRow().
Referenced by hal::GateDetailsTabWidget::setGate().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/gate_details_widget/gate_info_table.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/gate_details_widget/gate_info_table.cpp