HAL: hal::SelectionDetailsWidget Class Reference
hal::SelectionDetailsWidget Class Reference
HAL Gui » Utility Widgets » Selection Details Widget
Container for all specific details widgets.
#include <selection_details_widget.h>
Public Slots
void handleSelectionUpdate (void *sender)
void handleTreeSelection (const ModuleItem *sti)
QList< QShortcut * > createShortcuts () override
Public Slots inherited from hal::ContentWidget
void remove ()
void detach ()
void reattach ()
void open ()
void close ()
void handleSearchKeysequenceChanged (QKeySequence seq)
virtual void restoreFromProject ()
Public Slots inherited from hal::Widget
void hide ()
void show ()
Signals
void triggerHighlight (QVector< const ModuleItem * > highlight)
void focusGateClicked (u32 gateId)
void focusNetClicked (u32 netId)
void focusModuleClicked (u32 moduleId)
Signals inherited from hal::ContentWidget
void removed ()
void detached ()
void reattached ()
void opened ()
void closed ()
void name_changed (const QString &name)
Signals inherited from hal::Widget
void parentSetTo (QWidget *parent)
void hidden ()
void shown ()
Public Member Functions
SelectionDetailsWidget (QWidget *parent=nullptr)
virtual void setupToolbar (Toolbar *toolbar) override
void selectionToGroupingAction (const QString &existingGrpName=QString())
UserAction * groupingUnassignActionFactory (const UserActionObject &obj) const
SelectionTreeView * selectionTreeView ()
Q_PROPERTY Functions
QString disabledIconStyle () const
QString searchIconPath () const
QString searchIconStyle () const
QString searchActiveIconStyle () const
QString toGroupingIconPath () const
QString toGroupingIconStyle () const
QString toModuleIconPath () const
QString toModuleIconStyle () const
void setDisabledIconStyle (const QString &style)
void setSearchIconPath (const QString &path)
void setSearchIconStyle (const QString &style)
void setSearchActiveIconStyle (const QString &style)
void setToGroupingIconPath (const QString &path)
void setToGroupingIconStyle (const QString &style)
void setToModuleIconPath (const QString &path)
void setToModuleIconStyle (const QString &style)
Public Member Functions inherited from hal::ContentWidget
ContentWidget (QString name, QWidget *parent=nullptr)
virtual QList< QShortcut * > createShortcuts ()
void repolish ()
QString name ()
QIcon icon ()
void setAnchor (ContentAnchor *anchor)
void setIcon (QIcon icon)
void set_name (const QString &name)
QString iconStyle ()
QString iconPath ()
void setIconStyle (const QString &style)
void setIconPath (const QString &path)
Public Member Functions inherited from hal::Widget
Widget (QWidget *parent=nullptr)
void setParent (QWidget *parent)
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
virtual void setVisible (bool visible)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
virtual QSize sizeHint () const const
virtual QSize minimumSizeHint () const const
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Properties
QString disabledIconStyle
QString searchIconPath
QString searchIconStyle
QString searchActiveIconStyle
QString toGroupingIconPath
QString toGroupingIconStyle
QString toModuleIconPath
QString toModuleIconStyle
Properties inherited from hal::ContentWidget
QString iconStyle
QString iconPath
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Protected Member Functions inherited from QWidget
virtual bool event (QEvent *event) override
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void paintEvent (QPaintEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void contextMenuEvent (QContextMenuEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void dragEnterEvent (QDragEnterEvent *event)
virtual void dragMoveEvent (QDragMoveEvent *event)
virtual void dragLeaveEvent (QDragLeaveEvent *event)
virtual void dropEvent (QDropEvent *event)
virtual void showEvent (QShowEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual void changeEvent (QEvent *event)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
virtual void inputMethodEvent (QInputMethodEvent *event)
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
virtual bool focusNextPrevChild (bool next)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Protected Attributes inherited from hal::ContentWidget
QVBoxLayout * mContentLayout
QAction * mSearchAction
QShortcut * mSearchShortcut
QKeySequence mSearchKeysequence
Detailed Description
Container for all specific details widgets.
The SelectionDetailsWidget class is primarily a container used to display on the left side the complete selection as a tree (via a treeview) and on the right side the specific details of a single item chosen from the complete selection (via a stackedwidget containing the specific-details-widgets). This class manages which specific widget to display and provides usefull actions such as adding the current selection to a grouping.
Definition at line 61 of file selection_details_widget.h.
Constructor & Destructor Documentation
SelectionDetailsWidget()
hal::SelectionDetailsWidget::SelectionDetailsWidget (QWidget * parent = nullptr)
The default constructor. Initialization of every child-widget and its connections happens here.
Parameters
parent - The widget's parent.
Definition at line 58 of file selection_details_widget.cpp.
References QBoxLayout::addWidget(), QStackedWidget::addWidget(), QObject::connect(), QWidget::ensurePolished(), QSizePolicy::Expanding, hal::SelectionTreeView::focusItemClicked(), hal::SearchProxyModel::getColumnNames(), hal::gui_utility::getStyledSvgIcon(), hal::gSelectionRelay, handleSelectionUpdate(), handleTreeSelection(), QWidget::hide(), Qt::Horizontal, hal::SelectionTreeView::itemDoubleClicked(), hal::ContentWidget::mContentLayout, hal::ContentWidget::mSearchAction, QWidget::QWidget(), hal::SelectionRelay::registerSender(), hal::SelectionRelay::selectionChanged(), QLabel::setAlignment(), hal::Searchbar::setColumnNames(), QLayout::setContentsMargins(), QStackedWidget::setCurrentWidget(), QAction::setDisabled(), QAction::setIcon(), QWidget::setMinimumWidth(), QTreeView::setModel(), QWidget::setSizePolicy(), QSortFilterProxyModel::setSourceModel(), QBoxLayout::setSpacing(), QLabel::setText(), QAction::setToolTip(), QLabel::setWordWrap(), hal::SelectionTreeProxyModel::startSearch(), QAction::triggered(), hal::Searchbar::triggerNewSearch(), and hal::SelectionTreeView::triggerSelection().
Member Function Documentation
createShortcuts
QList< QShortcut * > hal::SelectionDetailsWidget::createShortcuts () override slot
Overriden function of the ContentWidget. Sets up all shortcuts and returns them.
Returns
The List of shortcuts.
Definition at line 488 of file selection_details_widget.cpp.
References QShortcut::activated(), QList::append(), QObject::connect(), hal::ContentWidget::mSearchAction, hal::ContentWidget::mSearchKeysequence, hal::ContentWidget::mSearchShortcut, and QAction::trigger().
disabledIconStyle()
QString hal::SelectionDetailsWidget::disabledIconStyle () const
Q_PROPERTY READ function for the "disabled"-icon style.
Returns
The "disabled" icon style.
focusGateClicked
void hal::SelectionDetailsWidget::focusGateClicked (u32 gateId) signal
Q_SIGNAL that is emitted when a gate-type item in the treeview is double clicked (or single clicked if it was in the focus to begin with).
Parameters
gateId - The id of the clicked gate item.
Referenced by hal::ContentManager::handleOpenDocument().
focusModuleClicked
void hal::SelectionDetailsWidget::focusModuleClicked (u32 moduleId) signal
Q_SIGNAL that is emitted when a module-type item in the treeview is double clicked (or single clicked if it was in the focus to begin with).
Parameters
moduleId - The id of the clicked module item.
Referenced by hal::ContentManager::handleOpenDocument().
focusNetClicked
void hal::SelectionDetailsWidget::focusNetClicked (u32 netId) signal
Q_SIGNAL that is emitted when a net-type item in the treeview is double clicked (or single clicked if it was in the focus to begin with).
Parameters
netId - The id of the clicked net item.
Referenced by hal::ContentManager::handleOpenDocument().
groupingUnassignActionFactory()
UserAction * hal::SelectionDetailsWidget::groupingUnassignActionFactory (const UserActionObject & obj) const
Returns a UserAction to undo an assignment defined by the given UserActionObject.
Parameters
obj - The object containing the assign action.
Returns
The resulting unassign action.
Definition at line 239 of file selection_details_widget.cpp.
References hal::UserActionObjectType::Gate, hal::Netlist::get_gate_by_id(), hal::Module::get_grouping(), hal::Gate::get_grouping(), hal::Grouping::get_id(), hal::Gate::get_id(), hal::Module::get_id(), hal::Netlist::get_module_by_id(), hal::Netlist::get_net_by_id(), hal::gNetlist, hal::UserActionObjectType::Grouping, hal::UserActionObject::id(), QSet::insert(), hal::UserActionObjectType::Module, hal::UserActionObjectType::Net, net, hal::UserAction::setObject(), hal::UserAction::setObjectLock(), and hal::UserActionObject::type().
Referenced by selectionToGroupingAction().
handleSelectionUpdate
void hal::SelectionDetailsWidget::handleSelectionUpdate (void * sender) slot
A function that is called when the selection is changed (external). It sets up the widget anew, e.g. populates the treeview and sets up the icons (disabled or enabled style).
Parameters
sender - The object that triggered the change.
Definition at line 354 of file selection_details_widget.cpp.
References QVector::append(), QList::at(), hal::Searchbar::clear(), hal::ModuleItem::Gate, hal::gContentManager, hal::Searchbar::getCurrentText(), hal::ContentManager::getGraphTabWidget(), hal::gui_utility::getStyledSvgIcon(), hal::gSelectionRelay, QString::isEmpty(), hal::SelectionTreeProxyModel::isGraphicsBusy(), hal::GraphTabWidget::isSelectMode(), hal::SelectionTreeView::itemFromIndex(), QAbstractItemView::model(), hal::ModuleItem::Module, hal::ModuleItem::Net, hal::SelectionRelay::numberSelectedGates(), hal::SelectionRelay::numberSelectedItems(), hal::SelectionRelay::numberSelectedModules(), hal::SelectionRelay::numberSelectedNets(), hal::SelectionRelay::numberSelectedNodes(), hal::SelectionTreeView::populate(), QObject::Q_EMIT(), hal::SelectionRelay::selectedGatesList(), hal::SelectionRelay::selectedModulesList(), hal::SelectionRelay::selectedNetsList(), QObject::sender(), QAction::setDisabled(), QAction::setEnabled(), QAction::setIcon(), QTreeView::setModel(), and triggerHighlight().
Referenced by SelectionDetailsWidget().
handleTreeSelection
void hal::SelectionDetailsWidget::handleTreeSelection (const ModuleItem * sti) slot
A function that is called when the selection of the treeview is changed (single-selection). Responsible to set the specific-details-widget and emits the triggerHighlight signal.
Parameters
sti - The selected item.
Definition at line 430 of file selection_details_widget.cpp.
References QVector::append(), QObject::Q_EMIT(), and triggerHighlight().
Referenced by SelectionDetailsWidget().
searchActiveIconStyle()
QString hal::SelectionDetailsWidget::searchActiveIconStyle () const
Q_PROPERTY READ function for the "search active"-icon style.
Returns
The "search activate" icon style.
searchIconPath()
QString hal::SelectionDetailsWidget::searchIconPath () const
Q_PROPERTY READ function for the "search"-icon path.
Returns
The "search" icon path.
searchIconStyle()
QString hal::SelectionDetailsWidget::searchIconStyle () const
Q_PROPERTY READ function for the "search"-icon style.
Returns
The "disabled" icon style.
selectionToGroupingAction()
void hal::SelectionDetailsWidget::selectionToGroupingAction (const QString & existingGrpName = QString())
Adds the current selection to the given grouping. The selection is cleared afterwards.
Definition at line 273 of file selection_details_widget.cpp.
References hal::UserActionCompound::addAction(), hal::UserActionCompound::exec(), hal::ModuleItem::Gate, hal::gContentManager, hal::Grouping::get_id(), hal::ContentManager::getGroupingManagerWidget(), hal::ModuleItem::getType(), hal::UserActionObjectType::Grouping, groupingUnassignActionFactory(), hal::gSelectionRelay, hal::ModuleItem::id(), QSortFilterProxyModel::index(), QSet::insert(), QString::isEmpty(), QSortFilterProxyModel::mapToSource(), hal::ModuleItem::Module, hal::ModuleItem::Net, QSortFilterProxyModel::rowCount(), hal::UserAction::setObject(), hal::UserActionCompound::setUseCreatedObject(), QAbstractProxyModel::sourceModel, and hal::SelectionRelay::toUserActionObject().
selectionTreeView()
SelectionTreeView * hal::SelectionDetailsWidget::selectionTreeView ()
Get the tree view that displays the current selection.
Returns
The tree view.
Definition at line 544 of file selection_details_widget.cpp.
Referenced by hal::ContentManager::handleOpenDocument().
setDisabledIconStyle()
void hal::SelectionDetailsWidget::setDisabledIconStyle (const QString & style)
Q_PROPERTY WRITE function for the "disabled"-icon style.
Parameters
style - The new style.
Definition at line 554 of file selection_details_widget.cpp.
References QWidget::style().
setSearchActiveIconStyle()
void hal::SelectionDetailsWidget::setSearchActiveIconStyle (const QString & style)
Q_PROPERTY WRITE function for the "search active"-icon style.
Parameters
style - The new style.
Definition at line 584 of file selection_details_widget.cpp.
References QWidget::style().
setSearchIconPath()
void hal::SelectionDetailsWidget::setSearchIconPath (const QString & path)
Q_PROPERTY WRITE function for the "search"-icon path.
Parameters
path - The new path.
Definition at line 574 of file selection_details_widget.cpp.
setSearchIconStyle()
void hal::SelectionDetailsWidget::setSearchIconStyle (const QString & style)
Q_PROPERTY WRITE function for the "search"-icon style.
Parameters
style - The new style.
Definition at line 579 of file selection_details_widget.cpp.
References QWidget::style().
setToGroupingIconPath()
void hal::SelectionDetailsWidget::setToGroupingIconPath (const QString & path)
Q_PROPERTY WRITE function for the "to grouping"-icon path.
Parameters
path - The new path.
Definition at line 599 of file selection_details_widget.cpp.
setToGroupingIconStyle()
void hal::SelectionDetailsWidget::setToGroupingIconStyle (const QString & style)
Q_PROPERTY WRITE function for the "to grouping"-icon style.
Parameters
style - The new style.
Definition at line 604 of file selection_details_widget.cpp.
References QWidget::style().
setToModuleIconPath()
void hal::SelectionDetailsWidget::setToModuleIconPath (const QString & path)
Q_PROPERTY WRITE function for the "to module"-icon path.
Parameters
path - The new path.
Definition at line 619 of file selection_details_widget.cpp.
setToModuleIconStyle()
void hal::SelectionDetailsWidget::setToModuleIconStyle (const QString & style)
Q_PROPERTY WRITE function for the "to module"-icon style.
Parameters
style - The new style.
Definition at line 624 of file selection_details_widget.cpp.
References QWidget::style().
setupToolbar()
void hal::SelectionDetailsWidget::setupToolbar (Toolbar * toolbar) override virtual
Overrides the ContentWidget's setupToolbar method. Adds its specific actions to the given toolbar so it can be displayed in the ContentFrame.
Parameters
toolbar - The toolbar to which the actions are added.
Reimplemented from hal::ContentWidget.
Definition at line 537 of file selection_details_widget.cpp.
References QToolBar::addAction(), and hal::ContentWidget::mSearchAction.
toGroupingIconPath()
QString hal::SelectionDetailsWidget::toGroupingIconPath () const
Q_PROPERTY READ function for the "to grouping"-icon path.
Returns
The "to grouping" icon path.
toGroupingIconStyle()
QString hal::SelectionDetailsWidget::toGroupingIconStyle () const
Q_PROPERTY READ function for the "to grouping"-icon style.
Returns
The "to grouping" icon style.
toModuleIconPath()
QString hal::SelectionDetailsWidget::toModuleIconPath () const
Q_PROPERTY READ function for the "to module"-icon path.
Returns
The "to module" icon path.
toModuleIconStyle()
QString hal::SelectionDetailsWidget::toModuleIconStyle () const
Q_PROPERTY READ function for the "to module"-icon style.
Returns
The "to module" icon style.
triggerHighlight
void hal::SelectionDetailsWidget::triggerHighlight (QVector< const ModuleItem * > highlight) signal
Q_SIGNAL that is emitted when the selection within the treeview changes.
Parameters
highlight - The items to highlight (that were selected in the view).
Referenced by hal::GraphLayouter::GraphLayouter(), handleSelectionUpdate(), and handleTreeSelection().
Property Documentation
disabledIconStyle
QString hal::SelectionDetailsWidget::disabledIconStyle read write
Definition at line 64 of file selection_details_widget.h.
searchActiveIconStyle
QString hal::SelectionDetailsWidget::searchActiveIconStyle read write
Definition at line 67 of file selection_details_widget.h.
searchIconPath
QString hal::SelectionDetailsWidget::searchIconPath read write
Definition at line 65 of file selection_details_widget.h.
searchIconStyle
QString hal::SelectionDetailsWidget::searchIconStyle read write
Definition at line 66 of file selection_details_widget.h.
toGroupingIconPath
QString hal::SelectionDetailsWidget::toGroupingIconPath read write
Definition at line 68 of file selection_details_widget.h.
toGroupingIconStyle
QString hal::SelectionDetailsWidget::toGroupingIconStyle read write
Definition at line 69 of file selection_details_widget.h.
toModuleIconPath
QString hal::SelectionDetailsWidget::toModuleIconPath read write
Definition at line 70 of file selection_details_widget.h.
toModuleIconStyle
QString hal::SelectionDetailsWidget::toModuleIconStyle read write
Definition at line 71 of file selection_details_widget.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/selection_details_widget.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/selection_details_widget.cpp