HAL: hal::ActionAddItemsToObject Class Reference
hal::ActionAddItemsToObject Class Reference
HAL Gui » User Actions
Adds an item to a module or grouping.
#include <action_add_items_to_object.h>
Public Member Functions
ActionAddItemsToObject (const QSet< u32 > &mods=QSet< u32 >(), const QSet< u32 > &gats=QSet< u32 >(), const QSet< u32 > &nets=QSet< u32 >(), const QSet< u32 > &pins=QSet< u32 >())
bool exec () override
void setPlacementHint (PlacementHint hint)
void setUsedInCreateContext ()
QString tagname () const override
void writeToXml (QXmlStreamWriter &xmlOut) const override
void readFromXml (QXmlStreamReader &xmlIn) override
void addToHash (QCryptographicHash &cryptoHash) const override
Public Member Functions inherited from hal::UserAction
virtual ~UserAction ()
virtual UserActionObject object () const
virtual void setObject (const UserActionObject &obj)
virtual void setParentObject (const UserActionObject &obj)
virtual UserActionObject parentObject () const
int compoundOrder () const
void setCompoundOrder (int cmpord)
qint64 timeStamp () const
QString cryptographicHash (int recordNo) const
UserAction * undoAction () const
QString debugDump () const
void setObjectLock (bool lock)
void setParentObjectLock (bool lock)
bool hasProjectModified () const
Additional Inherited Members
Protected Member Functions inherited from hal::UserAction
UserAction ()
void writeParentObjectToXml (QXmlStreamWriter &xmlOut) const
void readParentObjectFromXml (QXmlStreamReader &xmlIn)
Static Protected Member Functions inherited from hal::UserAction
static QString setToText (const QSet< u32 > &set)
static QSet< u32 > setFromText (const QString &s)
Protected Attributes inherited from hal::UserAction
UserActionObject mObject
UserActionObject mParentObject
int mCompoundOrder
UserAction * mUndoAction
qint64 mTimeStamp
bool mObjectLock
bool mParentObjectLock
bool mProjectModified
Detailed Description
Adds an item to a module or grouping.
Adds Modules, Gates, or Nets to the UserActionObject which must exist and must be of type Module or Grouping.
Undo Action: ActionDeleteObject
Definition at line 41 of file action_add_items_to_object.h.
Constructor & Destructor Documentation
ActionAddItemsToObject()
hal::ActionAddItemsToObject::ActionAddItemsToObject (const QSet< u32 > & mods = QSet<u32>(), const QSet< u32 > & gats = QSet<u32>(), const QSet< u32 > & nets = QSet<u32>(), const QSet< u32 > & pins = QSet<u32>()) inline
Action constructor.
Parameters
mods - The ids of the modules to add
gats - The ids of the gates to add
nets - The ids of the nets to add
pins - The ids of the pins to add
Definition at line 61 of file action_add_items_to_object.h.
Referenced by exec().
Member Function Documentation
addToHash()
void hal::ActionAddItemsToObject::addToHash (QCryptographicHash & cryptoHash) const override virtual
Hook for derived classes to add parameter to cryptographic hash.
Parameters
cryptoHash - Additional hash data.
Reimplemented from hal::UserAction.
Definition at line 30 of file action_add_items_to_object.cpp.
References QCryptographicHash::addData(), and hal::UserAction::setToText().
exec()
bool hal::ActionAddItemsToObject::exec () override virtual
Executes user interaction and returns true on success. Note: Each implementation of exec() must include a call to the exec() method of base class to store the UserAction object in history and to transfer its ownership.
Returns
True on success, False otherwise.
Reimplemented from hal::UserAction.
Definition at line 88 of file action_add_items_to_object.cpp.
References ActionAddItemsToObject(), hal::GraphContext::add(), hal::UserActionCompound::addAction(), hal::Grouping::assign_gate_by_id(), hal::Module::assign_gates(), hal::Grouping::assign_module_by_id(), hal::Grouping::assign_net_by_id(), QHash::begin(), hal::GraphContext::beginChange(), QHash::constBegin(), QHash::constEnd(), hal::UserActionObjectType::Context, QSet::empty(), QHash::end(), hal::GraphContext::endChange(), hal::UserAction::exec(), QString::fromStdString(), test::g, hal::Netlist::get_gate_by_id(), hal::Netlist::get_grouping_by_id(), hal::Module::get_id(), hal::Netlist::get_module_by_id(), hal::Module::get_parent_module(), hal::Module::get_pin_group_by_id(), hal::GraphContextManager::getContextById(), hal::gGraphContextManager, hal::gNetlist, hal::UserActionObjectType::Grouping, hal::UserActionObject::id(), QHash::insert(), QHash::isEmpty(), QHash::keys(), hal::UserAction::mObject, hal::UserActionObjectType::Module, hal::UserAction::mParentObject, hal::UserAction::mUndoAction, hal::UserActionObjectType::PinGroup, hal::Module::set_parent_module(), hal::UserAction::setObject(), hal::UserAction::setParentObject(), hal::UserActionCompound::setUseCreatedObject(), QHash::size(), hal::UserActionObject::type(), and QHash::value().
Referenced by hal::NetlistRelay::addSelectionToModule(), hal::ModulePinsTreeModel::dropMimeData(), hal::ModulePinsTree::handleContextMenuRequested(), and hal::AddToModuleReceiver::handleModulesPicked().
readFromXml()
void hal::ActionAddItemsToObject::readFromXml (QXmlStreamReader & xmlIn) override virtual
Reads user interaction as well as arguments from xml macro file.
Parameters
xmlIn - The xml reader.
Reimplemented from hal::UserAction.
Definition at line 64 of file action_add_items_to_object.cpp.
References QXmlStreamReader::attributes(), QXmlStreamReader::name(), hal::PlacementHint::PreferLeft, hal::PlacementHint::PreferRight, QXmlStreamReader::readElementText(), QXmlStreamReader::readNextStartElement(), hal::UserAction::readParentObjectFromXml(), hal::UserAction::setFromText(), QXmlStreamReader::skipCurrentElement(), QStringRef::toInt(), hal::UserActionObjectType::toNodeType(), QStringRef::toString(), and QXmlStreamAttributes::value().
setPlacementHint()
void hal::ActionAddItemsToObject::setPlacementHint (PlacementHint hint) inline
Sets the placement hints that are used to layout the added items.
Parameters
hint - The new placement hint
Definition at line 76 of file action_add_items_to_object.h.
Referenced by hal::ActionRemoveItemsFromObject::exec().
setUsedInCreateContext()
void hal::ActionAddItemsToObject::setUsedInCreateContext () inline
Must be called when adding pins to a pingroup and the pingroup was created in the same compound action. Sets a flag so that the undo action does not delete the source pingroup.
Definition at line 83 of file action_add_items_to_object.h.
tagname()
QString hal::ActionAddItemsToObject::tagname () const override virtual
The xml tagname for the action is purely virtual and needs to be implemented in derived class.
Returns
The tagname.
Implements hal::UserAction.
Definition at line 25 of file action_add_items_to_object.cpp.
References hal::ActionAddItemsToObjectFactory::sFactory, and hal::UserActionFactory::tagname().
writeToXml()
void hal::ActionAddItemsToObject::writeToXml (QXmlStreamWriter & xmlOut) const override virtual
Persist user interaction in xml macro file.
Parameters
xmlOut - The xml writer.
Reimplemented from hal::UserAction.
Definition at line 42 of file action_add_items_to_object.cpp.
References hal::UserActionObjectType::fromNodeType(), hal::Node::id(), QSet::isEmpty(), hal::PlacementHint::mode(), QString::number(), hal::PlacementHint::PreferLeft, hal::PlacementHint::preferredOrigin(), hal::UserAction::setToText(), hal::PlacementHint::Standard, hal::UserActionObjectType::toString(), hal::Node::type(), QXmlStreamWriter::writeAttribute(), QXmlStreamWriter::writeEndElement(), hal::UserAction::writeParentObjectToXml(), QXmlStreamWriter::writeStartElement(), and QXmlStreamWriter::writeTextElement().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/action_add_items_to_object.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/action_add_items_to_object.cpp