HAL: hal::SimulatorTest Class Reference
hal::SimulatorTest Class Reference
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
bool cmp_sim_data (const Simulation &vcd_sim, const Simulation &hal_sim)
Simulation parse_vcd (Netlist *netlist, const std::string vcdfile, bool normalize_to_nanoseconds)
void set_16_bit_net_vector (NetlistSimulator *sim, std::vector< Net * > nets, uint16_t number)
Detailed Description
Definition at line 42 of file simulator_test.cpp.
Member Function Documentation
cmp_sim_data()
bool hal::SimulatorTest::cmp_sim_data (const Simulation & vcd_sim, const Simulation & hal_sim) inline protected
Definition at line 58 of file simulator_test.cpp.
References g, hal::Simulation::get_events(), hal::Net::get_id(), hal::Net::get_name(), hal::Net::get_sources(), hal::ShortestPath::net(), and nlohmann::to_string().
parse_vcd()
Simulation hal::SimulatorTest::parse_vcd (Netlist * netlist, const std::string vcdfile, bool normalize_to_nanoseconds) inline protected
Definition at line 242 of file simulator_test.cpp.
References hal::Simulation::add_event(), hal::Event::affected_net, hal::Net::get_name(), hal::ShortestPath::net(), test_multiple::netlist, hal::Event::new_value, hal::utils::starts_with(), hal::Event::time, hal::utils::to_lower(), and hal::utils::trim().
set_16_bit_net_vector()
void hal::SimulatorTest::set_16_bit_net_vector (NetlistSimulator * sim, std::vector< Net * > nets, uint16_t number) inline protected
Definition at line 345 of file simulator_test.cpp.
References hal::NetlistSimulator::set_input().
SetUp()
virtual void hal::SimulatorTest::SetUp () inline protected virtual
Definition at line 44 of file simulator_test.cpp.
References hal::gate_library_manager::get_gate_library(), and hal::plugin_manager::load_all_plugins().
TearDown()
virtual void hal::SimulatorTest::TearDown () inline protected virtual
Definition at line 52 of file simulator_test.cpp.
References hal::plugin_manager::unload_all_plugins().
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/plugins/netlist_simulator/test/simulator_test.cpp