HAL: hal::ShadowEffect Class Reference
hal::ShadowEffect Class Reference
HAL Gui » Graph Widget » Visuals
Creates a shadow effect around QObjects.
#include <shadow_effect.h>
Public Member Functions
ShadowEffect (QObject *parent=nullptr)
void draw (QPainter *painter)
QRectF boundingRectFor (const QRectF &rect) const
void setDistance (qreal distance)
qreal distance () const
void setBlurRadius (qreal blurRadius)
qreal blurRadius () const
void setColor (const QColor &color)
QColor color () const
Public Member Functions inherited from QGraphicsEffect
QGraphicsEffect (QObject *parent)
virtual ~QGraphicsEffect ()
QRectF boundingRect () const const
bool isEnabled () const const
void setEnabled (bool enable)
void update ()
void enabledChanged (bool enabled)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Public Types inherited from QGraphicsEffect
enum ChangeFlag
enum PixmapPadMode
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QGraphicsEffect
typedef ChangeFlags
SourceAttached
SourceDetached
SourceBoundingRectChanged
SourceInvalidated
NoPad
PadToTransparentBorder
PadToEffectiveBoundingRect
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QGraphicsEffect
virtual void sourceChanged (QGraphicsEffect::ChangeFlags flags)
void updateBoundingRect ()
bool sourceIsPixmap () const const
QRectF sourceBoundingRect (Qt::CoordinateSystem system) const const
void drawSource (QPainter *painter)
QPixmap sourcePixmap (Qt::CoordinateSystem system, QPoint *offset, QGraphicsEffect::PixmapPadMode mode) const const
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QGraphicsEffect
enabled
Properties inherited from QObject
objectName
Detailed Description
Creates a shadow effect around QObjects.
The ShadowEffect is a graphics effect that simulates a small shadow around the outline of the object it is applied on.
Definition at line 40 of file shadow_effect.h.
Constructor & Destructor Documentation
ShadowEffect()
hal::ShadowEffect::ShadowEffect (QObject * parent = nullptr) explicit
Constructor.
Parameters
parent - The parent widget.
Definition at line 11 of file shadow_effect.cpp.
Member Function Documentation
blurRadius()
qreal hal::ShadowEffect::blurRadius () const inline
Gets the blur radius ths is used to draw the shadow.
Returns
the blur radius.
Definition at line 105 of file shadow_effect.h.
Referenced by boundingRectFor(), draw(), and setBlurRadius().
boundingRectFor()
QRectF hal::ShadowEffect::boundingRectFor (const QRectF & rect) const virtual
Returns the effective bounding rectangle for this effect given the bounding rectangle of the object it is applied on.
Parameters
rect - The bounding rectangle this effect should be applied on
Returns
The bounding rectangle of the effect.
Reimplemented from QGraphicsEffect.
Definition at line 72 of file shadow_effect.cpp.
References QRectF::adjusted(), blurRadius(), distance(), and QRectF::united().
color()
QColor hal::ShadowEffect::color () const inline
Gets the color of the shadow.
Returns
the color of the shadow.
Definition at line 125 of file shadow_effect.h.
Referenced by draw(), and setColor().
distance()
qreal hal::ShadowEffect::distance () const inline
Gets the distance of the shadow, i.e. how far from the edges of the object it is drawn.
Returns
the distance of the shadow effect
Definition at line 84 of file shadow_effect.h.
Referenced by boundingRectFor(), draw(), and setDistance().
draw()
void hal::ShadowEffect::draw (QPainter * painter) virtual
Draws the effect.
Parameters
painter - The used painter
Implements QGraphicsEffect.
Definition at line 15 of file shadow_effect.cpp.
References QPainter::begin(), blurRadius(), color(), QPainter::CompositionMode_Source, QPainter::CompositionMode_SourceIn, Qt::DeviceCoordinates, distance(), QPainter::drawImage(), QPainter::drawPixmap(), QGraphicsEffect::drawSource(), QPainter::end(), QImage::fill(), QPainter::fillRect(), QImage::Format_ARGB32_Premultiplied, QSize::height(), QPixmap::isNull(), QGraphicsEffect::PadToEffectiveBoundingRect, qt_blurImage(), QImage::rect(), QPixmap::scaled(), QPainter::setCompositionMode(), QPainter::setWorldTransform(), QImage::size(), QPixmap::size(), QGraphicsEffect::sourcePixmap(), QSize::width(), and QPainter::worldTransform().
setBlurRadius()
void hal::ShadowEffect::setBlurRadius (qreal blurRadius) inline
Customizes the blur radius that is used to draw the shadow.
Parameters
blurRadius - The blur radius
Definition at line 94 of file shadow_effect.h.
References blurRadius(), and QGraphicsEffect::updateBoundingRect().
setColor()
void hal::ShadowEffect::setColor (const QColor & color) inline
Customizes the color of the shadow.
Parameters
color - The color of the shadow.
Definition at line 115 of file shadow_effect.h.
References color().
setDistance()
void hal::ShadowEffect::setDistance (qreal distance) inline
Customizes how far from the edges of the object the shadow should be drawn.
Parameters
distance - The new distance
Definition at line 73 of file shadow_effect.h.
References distance(), and QGraphicsEffect::updateBoundingRect().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graphics_effects/shadow_effect.h
/home/runner/work/hal/hal/plugins/gui/src/graphics_effects/shadow_effect.cpp