HAL: hal::PluginModel Class Reference
hal::PluginModel Class Reference
HAL Gui » Unused
#include <plugin_model.h>
Public Slots
void handleLoadPlugin (QString name, QString path)
void handleUnloadPlugin (QString name, QString path)
void handleRunPluginTriggered (const QModelIndex &index)
Signals
void loadPlugin (QString name, QString path)
void unloadPlugin (QString name, QString path)
void runPlugin (const QString &name)
Public Member Functions
PluginModel (QObject *parent=nullptr)
~PluginModel ()
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
QModelIndex parent (const QModelIndex &child) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild) override
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
Qt::DropActions supportedDropActions () const override
Qt::ItemFlags flags (const QModelIndex &index) const override
bool setData (const QModelIndex &index, const QVariant &value, int role) override
bool isValidIndex (const QModelIndex &idx)
void pluginManagerCallback (bool is_load, std::string const &plugin_name, std::string const &plugin_path)
void requestLoadPlugin (const QString &name, const QString &path)
void requestUnloadPlugin (QModelIndexList idx)
const QList< PluginItem > getPluginList ()
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
virtual QModelIndex sibling (int row, int column, const QModelIndex &index) const const
virtual bool hasChildren (const QModelIndex &parent) const const
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const const
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
virtual QStringList mimeTypes () const const
virtual QMimeData * mimeData (const QModelIndexList &indexes) const const
virtual bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const const
virtual Qt::DropActions supportedDragActions () const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool insertRows (int row, int count, const QModelIndex &parent)
virtual bool insertColumns (int column, int count, const QModelIndex &parent)
virtual bool removeRows (int row, int count, const QModelIndex &parent)
virtual bool removeColumns (int column, int count, const QModelIndex &parent)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual void fetchMore (const QModelIndex &parent)
virtual bool canFetchMore (const QModelIndex &parent) const const
virtual void sort (int column, Qt::SortOrder order)
virtual QModelIndex buddy (const QModelIndex &index) const const
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const
virtual QSize span (const QModelIndex &index) const const
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual bool submit ()
virtual void revert ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Definition at line 37 of file plugin_model.h.
Constructor & Destructor Documentation
PluginModel()
hal::PluginModel::PluginModel (QObject * parent = nullptr) explicit
Definition at line 13 of file plugin_model.cpp.
References hal::plugin_manager::add_model_changed_callback(), QList::append(), QObject::connect(), hal::PluginItem::getColumnDescription(), handleLoadPlugin(), handleUnloadPlugin(), loadPlugin(), pluginManagerCallback(), and unloadPlugin().
~PluginModel()
hal::PluginModel::~PluginModel ()
Definition at line 26 of file plugin_model.cpp.
References hal::plugin_manager::remove_model_changed_callback().
Member Function Documentation
columnCount()
int hal::PluginModel::columnCount (const QModelIndex & parent = QModelIndex()) const override virtual
Implements QAbstractItemModel.
Definition at line 49 of file plugin_model.cpp.
References QList::count(), and QObject::parent().
Referenced by headerData(), index(), and setData().
data()
QVariant hal::PluginModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override virtual
Implements QAbstractItemModel.
Definition at line 75 of file plugin_model.cpp.
References QModelIndex::column(), Qt::DisplayRole, Qt::EditRole, index(), QModelIndex::isValid(), hal::PluginItem::mName, hal::PluginItem::mPath, hal::PluginItem::Name, hal::PluginItem::Path, and QModelIndex::row().
Referenced by dropMimeData().
dropMimeData()
bool hal::PluginModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) override virtual
Reimplemented from QAbstractItemModel.
Definition at line 207 of file plugin_model.cpp.
References QList::append(), QList::at(), QDataStream::atEnd(), QList::contains(), data(), QList::length(), Qt::MoveAction, QAbstractItemModel::moveRow(), QObject::parent(), and QIODevice::ReadOnly.
flags()
Qt::ItemFlags hal::PluginModel::flags (const QModelIndex & index) const override virtual
Reimplemented from QAbstractItemModel.
Definition at line 109 of file plugin_model.cpp.
References QAbstractItemModel::flags(), index(), QModelIndex::isValid(), Qt::ItemFlags, Qt::ItemIsDragEnabled, Qt::ItemIsDropEnabled, Qt::ItemIsEnabled, and Qt::ItemIsSelectable.
getPluginList()
const QList< PluginItem > hal::PluginModel::getPluginList ()
Definition at line 254 of file plugin_model.cpp.
handleLoadPlugin
void hal::PluginModel::handleLoadPlugin (QString name, QString path) slot
Definition at line 153 of file plugin_model.cpp.
References QAbstractItemModel::beginInsertRows(), QAbstractItemModel::endInsertRows(), rowCount(), and QString::toStdString().
Referenced by PluginModel().
handleRunPluginTriggered
void hal::PluginModel::handleRunPluginTriggered (const QModelIndex & index) slot
Definition at line 259 of file plugin_model.cpp.
References index(), QModelIndex::isValid(), QObject::Q_EMIT(), QModelIndex::row(), and runPlugin().
Referenced by hal::PluginManagerWidget::setPluginModel().
handleUnloadPlugin
void hal::PluginModel::handleUnloadPlugin (QString name, QString path) slot
Definition at line 165 of file plugin_model.cpp.
References QAbstractItemModel::beginRemoveRows(), QAbstractItemModel::endRemoveRows(), and index().
Referenced by PluginModel().
headerData()
QVariant hal::PluginModel::headerData (int section, Qt::Orientation orientation, int role) const override virtual
Reimplemented from QAbstractItemModel.
Definition at line 96 of file plugin_model.cpp.
References QList::at(), columnCount(), Qt::DisplayRole, Qt::Horizontal, and rowCount().
index()
QModelIndex hal::PluginModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const override virtual
Implements QAbstractItemModel.
Definition at line 57 of file plugin_model.cpp.
References columnCount(), QAbstractItemModel::createIndex(), QObject::parent(), and rowCount().
Referenced by data(), flags(), handleRunPluginTriggered(), handleUnloadPlugin(), isValidIndex(), and setData().
isValidIndex()
bool hal::PluginModel::isValidIndex (const QModelIndex & idx)
Definition at line 31 of file plugin_model.cpp.
References QModelIndex::column(), index(), QModelIndex::isValid(), and QModelIndex::row().
loadPlugin
void hal::PluginModel::loadPlugin (QString name, QString path) signal
Referenced by pluginManagerCallback(), and PluginModel().
moveRows()
bool hal::PluginModel::moveRows (const QModelIndex & sourceParent, int sourceRow, int count, const QModelIndex & destinationParent, int destinationChild) override virtual
Reimplemented from QAbstractItemModel.
Definition at line 188 of file plugin_model.cpp.
References QAbstractItemModel::beginMoveRows(), and QAbstractItemModel::endMoveRows().
parent()
QModelIndex hal::PluginModel::parent (const QModelIndex & child) const override virtual
Implements QAbstractItemModel.
Definition at line 68 of file plugin_model.cpp.
pluginManagerCallback()
void hal::PluginModel::pluginManagerCallback (bool is_load, std::string const & plugin_name, std::string const & plugin_path)
Definition at line 143 of file plugin_model.cpp.
References QString::fromStdString(), loadPlugin(), QObject::Q_EMIT(), and unloadPlugin().
Referenced by PluginModel().
requestLoadPlugin()
void hal::PluginModel::requestLoadPlugin (const QString & name, const QString & path)
Definition at line 238 of file plugin_model.cpp.
References QByteArray::constData(), hal::plugin_manager::load(), and QString::toLocal8Bit().
requestUnloadPlugin()
void hal::PluginModel::requestUnloadPlugin (QModelIndexList idx)
Definition at line 245 of file plugin_model.cpp.
References hal::plugin_manager::unload().
rowCount()
int hal::PluginModel::rowCount (const QModelIndex & parent = QModelIndex()) const override virtual
Implements QAbstractItemModel.
Definition at line 41 of file plugin_model.cpp.
References QObject::parent().
Referenced by handleLoadPlugin(), headerData(), index(), and setData().
runPlugin
void hal::PluginModel::runPlugin (const QString & name) signal
Referenced by hal::ContentManager::handleOpenDocument(), and handleRunPluginTriggered().
setData()
bool hal::PluginModel::setData (const QModelIndex & index, const QVariant & value, int role) override virtual
Reimplemented from QAbstractItemModel.
Definition at line 119 of file plugin_model.cpp.
References QModelIndex::column(), columnCount(), QAbstractItemModel::dataChanged(), Qt::EditRole, index(), QModelIndex::isValid(), hal::PluginItem::mName, hal::PluginItem::mPath, hal::PluginItem::Name, hal::PluginItem::Path, QObject::Q_EMIT(), QModelIndex::row(), rowCount(), and QVariant::toString().
supportedDropActions()
Qt::DropActions hal::PluginModel::supportedDropActions () const override virtual
Reimplemented from QAbstractItemModel.
Definition at line 183 of file plugin_model.cpp.
References Qt::MoveAction.
unloadPlugin
void hal::PluginModel::unloadPlugin (QString name, QString path) signal
Referenced by pluginManagerCallback(), and PluginModel().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/plugin_manager/plugin_model.h
/home/runner/work/hal/hal/plugins/gui/src/plugin_manager/plugin_model.cpp