HAL: hal::ContentManager Class Reference
hal::ContentManager Class Reference
HAL Gui
Manages all ContentWidgets.
#include <content_manager.h>
Public Slots
void handleOpenDocument (const QString &fileName)
Public Member Functions
ContentManager (MainWindow *parent)
~ContentManager ()
void deleteContent ()
PythonEditor * getPythonEditorWidget ()
GraphTabWidget * getGraphTabWidget ()
Get hal's graph tab widget.
ContextManagerWidget * getContextManagerWidget ()
SelectionDetailsWidget * getSelectionDetailsWidget ()
GroupingManagerWidget * getGroupingManagerWidget ()
ModuleWidget * getModuleWidget ()
void setWindowTitle (const QString &filename)
void addExternalWidget (ContentFactory *factory)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Attributes
static SettingsItemKeybind * sSettingSearch
static SettingsItemKeybind * sSettingDeleteItem
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Manages all ContentWidgets.
The ContentManager class manages the creation and deletion of hal's subwidgets such as the python editor or the selection details widget. There should only be one content manager at any time.
Definition at line 91 of file content_manager.h.
Constructor & Destructor Documentation
ContentManager()
hal::ContentManager::ContentManager (MainWindow * parent) explicit
The constructor of the class. The content manager's parent is the MainwWndow of hal. The MainWindow must be known to the content manager so it can place the subwidgets in it.
Parameters
parent - The content manager's parent.
Definition at line 89 of file content_manager.cpp.
References QObject::connect(), hal::FileManager::fileOpened(), hal::FileManager::get_instance(), and handleOpenDocument().
~ContentManager()
hal::ContentManager::~ContentManager ()
Definition at line 101 of file content_manager.cpp.
Member Function Documentation
addExternalWidget()
void hal::ContentManager::addExternalWidget (ContentFactory * factory)
Definition at line 277 of file content_manager.cpp.
References hal::MainWindow::addContent(), hal::ContentFactory::contentFactory(), hal::ContentWidget::open(), hal::ContentWidget::restoreFromProject(), and hal::right.
Referenced by handleOpenDocument().
deleteContent()
void hal::ContentManager::deleteContent ()
Deletes all subwidgets created by the manager. Used when closing a file.
Definition at line 105 of file content_manager.cpp.
getContextManagerWidget()
ContextManagerWidget * hal::ContentManager::getContextManagerWidget ()
Get hal's context manager.
Returns
The context manager.
Definition at line 146 of file content_manager.cpp.
Referenced by hal::ActionFoldModule::exec(), hal::ActionUnfoldModule::exec(), hal::GraphGraphicsView::handleRemoveFromView(), hal::GraphTabWidget::handleTabChanged(), hal::SelectionTreeView::isolateInNewViewAction(), and hal::ModuleWidget::openModuleInView().
getGraphTabWidget()
GraphTabWidget * hal::ContentManager::getGraphTabWidget ()
Get hal's graph tab widget.
Returns
The graph tab widget.
Definition at line 126 of file content_manager.cpp.
Referenced by hal::GateSelectPicker::GateSelectPicker(), hal::NetEndpointTable::handleContextMenuRequested(), hal::ModuleElementsTree::handleContextMenuRequested(), hal::AddToModuleReceiver::handleModulesPicked(), hal::SelectionDetailsWidget::handleSelectionUpdate(), hal::ModuleWidget::handleTreeViewContextMenuRequested(), hal::ModuleSelectPicker::ModuleSelectPicker(), hal::GateSelectPicker::terminatePicker(), hal::ModuleSelectPicker::terminatePicker(), and hal::GraphContext::writeToFile().
getGroupingManagerWidget()
GroupingManagerWidget * hal::ContentManager::getGroupingManagerWidget ()
Get hal's grouping manager.
Returns
The grouping manager.
Definition at line 136 of file content_manager.cpp.
Referenced by hal::GraphicsScene::connectAll(), hal::GraphicsScene::disconnectAll(), hal::ActionDeleteObject::exec(), hal::ActionSetObjectColor::exec(), hal::ActionCreateObject::exec(), hal::ActionRenameObject::exec(), hal::GraphicsItem::groupingColor(), hal::GroupingsOfItemModel::GroupingsOfItemModel(), hal::StandardGraphicsGate::paint(), hal::SelectionDetailsWidget::selectionToGroupingAction(), and hal::GroupingColorSerializer::serialize().
getModuleWidget()
ModuleWidget * hal::ContentManager::getModuleWidget ()
Get hal's module tree widget.
Returns
module tree widget
Definition at line 141 of file content_manager.cpp.
getPythonEditorWidget()
PythonEditor * hal::ContentManager::getPythonEditorWidget ()
Get hal's python editor.
Returns
The python editor.
Definition at line 121 of file content_manager.cpp.
Referenced by hal::PythonSerializer::serialize(), and hal::PythonSerializer::serialize_control().
getSelectionDetailsWidget()
SelectionDetailsWidget * hal::ContentManager::getSelectionDetailsWidget ()
Get hal's selection details widget.
Returns
The selection details widget.
Definition at line 131 of file content_manager.cpp.
Referenced by hal::GraphLayouter::GraphLayouter().
handleOpenDocument
void hal::ContentManager::handleOpenDocument (const QString & fileName) slot
This function is called when a file is opened (connected to a signal that is emitted by the file manager). It creates the necessary subwidgets and places them in the mainwindow.
Parameters
fileName - The name of the opened file.
Definition at line 151 of file content_manager.cpp.
References hal::MainWindow::addContent(), addExternalWidget(), hal::bottom, hal::center, QObject::connect(), hal::SelectionDetailsWidget::focusGateClicked(), hal::SelectionDetailsWidget::focusModuleClicked(), hal::SelectionDetailsWidget::focusNetClicked(), hal::GuiPluginManager::getGuiExtensions(), hal::GroupingManagerWidget::getProxyModel(), hal::gGraphContextManager, hal::gNetlist, hal::GraphTabWidget::handleGateFocus(), hal::GraphTabWidget::handleModuleFocus(), hal::GraphTabWidget::handleNetFocus(), hal::ContextManagerWidget::handleOpenContextClicked(), hal::ContentWidget::handleSearchKeysequenceChanged(), hal::ExternalContent::instance(), hal::SettingsItemDropdown::intChanged(), hal::SettingsItemKeybind::keySequenceChanged(), hal::left, hal::ContentWidget::open(), hal::ModuleWidget::proxyModel(), hal::GraphContextSerializer::restore(), hal::GraphContextManager::restoreFromFile(), hal::right, hal::GraphContextSerializer::selectedContext(), hal::SelectionDetailsWidget::selectionTreeView(), hal::ContextManagerWidget::selectViewContext(), setWindowTitle(), sSettingSearch, QVariant::toInt(), QVariant::toString(), hal::SettingsItemDropdown::value(), and hal::SettingsItemKeybind::value().
Referenced by ContentManager().
setWindowTitle()
void hal::ContentManager::setWindowTitle (const QString & filename)
Set main window title.
Parameters
filename name of netlist filename.
Definition at line 297 of file content_manager.cpp.
References QString::fromStdString(), QWidget::setWindowTitle(), and QString::toStdString().
Referenced by handleOpenDocument(), hal::MainWindow::handleSaveAsTriggered(), and hal::MainWindow::handleSaveTriggered().
Member Data Documentation
sSettingDeleteItem
SettingsItemKeybind * hal::ContentManager::sSettingDeleteItem static
Definition at line 171 of file content_manager.h.
Referenced by hal::ContextManagerWidget::ContextManagerWidget(), hal::GroupingManagerWidget::GroupingManagerWidget(), and hal::ModuleWidget::ModuleWidget().
sSettingSearch
SettingsItemKeybind * hal::ContentManager::sSettingSearch static
Definition at line 170 of file content_manager.h.
Referenced by hal::GateDialog::GateDialog(), hal::GroupingDialog::GroupingDialog(), handleOpenDocument(), and hal::ModuleDialog::ModuleDialog().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/content_manager/content_manager.h
/home/runner/work/hal/hal/plugins/gui/src/content_manager/content_manager.cpp