HAL: hal::ContentWidget Class Reference
hal::ContentWidget Class Reference
HAL Gui
Abstract class for Widgets within HAL's ContentArea.
#include <content_widget.h>
Public Slots
void remove ()
void detach ()
void reattach ()
void open ()
void close ()
void handleSearchKeysequenceChanged (QKeySequence seq)
virtual void restoreFromProject ()
Public Slots inherited from hal::Widget
void hide ()
void show ()
Signals
void removed ()
void detached ()
void reattached ()
void opened ()
void closed ()
void name_changed (const QString &name)
Signals inherited from hal::Widget
void parentSetTo (QWidget *parent)
void hidden ()
void shown ()
Public Member Functions
ContentWidget (QString name, QWidget *parent=nullptr)
virtual void setupToolbar (Toolbar *Toolbar)
virtual QList< QShortcut * > createShortcuts ()
void repolish ()
QString name ()
QIcon icon ()
void setAnchor (ContentAnchor *anchor)
void setIcon (QIcon icon)
void set_name (const QString &name)
Q_PROPERTY READ Functions
QString iconStyle ()
QString iconPath ()
Q_PROPERTY WRITE Functions
void setIconStyle (const QString &style)
void setIconPath (const QString &path)
Public Member Functions inherited from hal::Widget
Widget (QWidget *parent=nullptr)
void setParent (QWidget *parent)
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
virtual void setVisible (bool visible)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
virtual QSize sizeHint () const const
virtual QSize minimumSizeHint () const const
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Protected Attributes
QVBoxLayout * mContentLayout
QAction * mSearchAction
QShortcut * mSearchShortcut
QKeySequence mSearchKeysequence
Properties
QString iconStyle
QString iconPath
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Protected Member Functions inherited from QWidget
virtual bool event (QEvent *event) override
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void paintEvent (QPaintEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void contextMenuEvent (QContextMenuEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void dragEnterEvent (QDragEnterEvent *event)
virtual void dragMoveEvent (QDragMoveEvent *event)
virtual void dragLeaveEvent (QDragLeaveEvent *event)
virtual void dropEvent (QDropEvent *event)
virtual void showEvent (QShowEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual void changeEvent (QEvent *event)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
virtual void inputMethodEvent (QInputMethodEvent *event)
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
virtual bool focusNextPrevChild (bool next)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Detailed Description
Abstract class for Widgets within HAL's ContentArea.
The ContentWidget class is the base class that has to be derived from in order to be put in hal's ContentArea. It provides the necessary interface for the docking system as well as functions that can be overwritten to configure its shortcuts and toolbar.
Definition at line 49 of file content_widget.h.
Constructor & Destructor Documentation
ContentWidget()
hal::ContentWidget::ContentWidget (QString name, QWidget * parent = nullptr) explicit
The constructor.
Parameters
name - The in the top left corner displayed name.
parent - The widget's parent.
Definition at line 13 of file content_widget.cpp.
References QIcon::addFile(), QSizePolicy::Expanding, mContentLayout, name(), QIcon::Normal, QIcon::Off, QLayout::setContentsMargins(), setIcon(), QWidget::setLayout(), QWidget::setMinimumSize(), QWidget::setSizePolicy(), QBoxLayout::setSpacing(), and QWidget::setWindowTitle().
Member Function Documentation
close
void hal::ContentWidget::close () slot
Closes (hides) the widget in its anchor (related to the docking system).
Definition at line 65 of file content_widget.cpp.
References hal::ContentAnchor::close(), closed(), and QObject::Q_EMIT().
Referenced by hal::DockButton::handleClicked(), and hal::DockBar::mouseMoveEvent().
closed
void hal::ContentWidget::closed () signal
Q_SIGNAL that is emitted when the widget is closed (hidden in the anchor) (related to the docking system).
Referenced by close().
createShortcuts()
QList< QShortcut * > hal::ContentWidget::createShortcuts () virtual
A virtual function that can be overwritten by the actual widget to create the widget's keyboard shortcuts. Shortcuts are created and managed with the help of the keybind manager.
Returns
The List of (created) QShortcuts.
Reimplemented in hal::PythonEditor, hal::PythonConsoleWidget, hal::ModuleWidget, hal::GroupingManagerWidget, and hal::GraphTabWidget.
Definition at line 104 of file content_widget.cpp.
Referenced by hal::ContentFrame::ContentFrame(), and hal::TabWidget::open().
detach
void hal::ContentWidget::detach () slot
Detaches the widget from its anchor (related to the docking system).
Definition at line 38 of file content_widget.cpp.
References hal::ContentAnchor::detach(), detached(), and QObject::Q_EMIT().
Referenced by hal::ContentFrame::detachWidget().
detached
void hal::ContentWidget::detached () signal
Q_SIGNAL that is emitted when the widget is detached from its anchor (related to the docking system).
Referenced by detach().
handleSearchKeysequenceChanged
void hal::ContentWidget::handleSearchKeysequenceChanged (QKeySequence seq) slot
Q_SLOT to handle that the settings for the search key sequence (default: 'Ctrl+F') has been changed. Configures the new search key sequence for the ContentWidget.
Parameters
seq - The new search key sequence
Definition at line 148 of file content_widget.cpp.
References mSearchKeysequence, mSearchShortcut, and QShortcut::setKey().
Referenced by hal::ContentManager::handleOpenDocument().
icon()
QIcon hal::ContentWidget::icon ()
Get the loaded and processed icon that can be set in the stylesheet.
Returns
The icon.
Definition at line 81 of file content_widget.cpp.
Referenced by hal::DockButton::DockButton(), and setIcon().
iconPath()
QString hal::ContentWidget::iconPath ()
Necessary function used by qt's property system. Refer to Qt's documentation to learn more.
Returns
The icon's path.
iconStyle()
QString hal::ContentWidget::iconStyle ()
Necessary function used by qt's property system. Refer to Qt's documentation to learn more.
Returns
The style descrition needed when processing the icon.
name()
QString hal::ContentWidget::name ()
Get the widget's displayed name (actually displayed within the ContentFrame's area).
Returns
The name.
Definition at line 76 of file content_widget.cpp.
Referenced by hal::ContentLayoutArea::addContent(), hal::GraphTabWidget::addTab(), hal::ContentFrame::ContentFrame(), ContentWidget(), hal::DockButton::DockButton(), hal::ModuleWidget::ModuleWidget(), hal::ModuleWidget::openModuleInView(), and set_name().
name_changed
void hal::ContentWidget::name_changed (const QString & name) signal
Q_SIGNAL that is emitted when the widget's name is changed after calling setName().
Parameters
name - The new name.
Referenced by hal::ContentFrame::ContentFrame(), and set_name().
open
void hal::ContentWidget::open () slot
Opens (displays) the widget in its anchor (related to the docking system).
Definition at line 56 of file content_widget.cpp.
References hal::ContentAnchor::open(), opened(), and QObject::Q_EMIT().
Referenced by hal::ContentManager::addExternalWidget(), hal::DockButton::handleClicked(), and hal::ContentManager::handleOpenDocument().
opened
void hal::ContentWidget::opened () signal
Q_SIGNAL that is emitted when the widget is opened (displayed in the anchor) (related to the docking system).
Referenced by open().
reattach
void hal::ContentWidget::reattach () slot
Reattaches the widget to its anchor (related to the docking system).
Definition at line 47 of file content_widget.cpp.
References QObject::Q_EMIT(), hal::ContentAnchor::reattach(), and reattached().
Referenced by hal::ContentFrame::reattachWidget().
reattached
void hal::ContentWidget::reattached () signal
Q_SIGNAL that is emitted when the widget is reattached to its anchor (related to the docking system).
Referenced by reattach().
remove
void hal::ContentWidget::remove () slot
Removes the widget from its anchor (related to the docking system).
Definition at line 29 of file content_widget.cpp.
References QObject::Q_EMIT(), hal::ContentAnchor::remove(), and removed().
Referenced by hal::DockBar::dropEvent().
removed
void hal::ContentWidget::removed () signal
Q_SIGNAL that is emitted when the widget is removed from its anchor (related to the docking system).
Referenced by remove().
repolish()
void hal::ContentWidget::repolish ()
Reapplies the current Stylesheet by using the QStyle's unpolish and polish functions. It is necessary because certain aspects of a widgets are not automatically set and rendered just by calling setStylesheet() when switched to a new one (for example when a new theme wants to be applied at runtime).
Definition at line 109 of file content_widget.cpp.
References QStyle::polish(), QWidget::style(), and QStyle::unpolish().
Referenced by setIconPath(), and setIconStyle().
restoreFromProject
virtual void hal::ContentWidget::restoreFromProject () inline virtual slot
Derived classes might want to restore content from project directory.
Definition at line 233 of file content_widget.h.
Referenced by hal::ContentManager::addExternalWidget().
set_name()
void hal::ContentWidget::set_name (const QString & name)
Sets the displayed name of the widget. Usefull when the name changes during runtime (e.g. when the content widget consists of multiple layered sub widget and each has its own "subname").
Parameters
name - The new name.
Definition at line 96 of file content_widget.cpp.
References name(), name_changed(), and QObject::Q_EMIT().
setAnchor()
void hal::ContentWidget::setAnchor (ContentAnchor * anchor)
Sets the anchor of the content widget. This function is used by the docking system.
Parameters
anchor - The anchor.
Definition at line 86 of file content_widget.cpp.
Referenced by hal::TabWidget::add(), hal::SplitterAnchor::add(), hal::TabWidget::remove(), and hal::SplitterAnchor::remove().
setIcon()
void hal::ContentWidget::setIcon (QIcon icon)
Sets the icon of the widget.
Parameters
icon - The icon.
Definition at line 91 of file content_widget.cpp.
References icon().
Referenced by ContentWidget().
setIconPath()
void hal::ContentWidget::setIconPath (const QString & path)
Necessary function used by qt's property system. Refer to Qt's documentation to learn more.
Parameters
path - The icon's path.
Definition at line 139 of file content_widget.cpp.
References repolish().
setIconStyle()
void hal::ContentWidget::setIconStyle (const QString & style)
Necessary function used by qt's property system. Refer to Qt's documentation to learn more.
Parameters
style - The style description of the icon.
Definition at line 130 of file content_widget.cpp.
References repolish(), and QWidget::style().
setupToolbar()
void hal::ContentWidget::setupToolbar (Toolbar * Toolbar) virtual
A virtual function that can be overwritten by the actual widget to configure its toolbar (add actions to it and connect them). It is called by the wrapper class ContentFrame that actually displays the toolbar.
Parameters
Toolbar - The toolbar to add actions to.
Reimplemented in hal::SelectionDetailsWidget, hal::PythonEditor, hal::PythonConsoleWidget, hal::ModuleWidget, hal::LoggerWidget, hal::GroupingManagerWidget, and hal::ContextManagerWidget.
Definition at line 102 of file content_widget.cpp.
Referenced by hal::ContentFrame::ContentFrame(), and hal::TabWidget::open().
Member Data Documentation
mContentLayout
QVBoxLayout* hal::ContentWidget::mContentLayout protected
Definition at line 247 of file content_widget.h.
Referenced by ContentWidget(), hal::ContextManagerWidget::ContextManagerWidget(), hal::GraphTabWidget::GraphTabWidget(), hal::GraphWidget::GraphWidget(), hal::GroupingManagerWidget::GroupingManagerWidget(), hal::LoggerWidget::LoggerWidget(), hal::ModuleWidget::ModuleWidget(), hal::PythonConsoleWidget::PythonConsoleWidget(), hal::PythonEditor::PythonEditor(), and hal::SelectionDetailsWidget::SelectionDetailsWidget().
mSearchAction
QAction* hal::ContentWidget::mSearchAction protected
Definition at line 248 of file content_widget.h.
Referenced by hal::ContextManagerWidget::ContextManagerWidget(), hal::GroupingManagerWidget::createShortcuts(), hal::ModuleWidget::createShortcuts(), hal::PythonEditor::createShortcuts(), hal::SelectionDetailsWidget::createShortcuts(), hal::ContextManagerWidget::enableSearchbar(), hal::GroupingManagerWidget::enableSearchbar(), hal::GroupingManagerWidget::GroupingManagerWidget(), hal::PythonEditor::handleCurrentTabChanged(), hal::PythonEditor::handleSearchbarTextEdited(), hal::ModuleWidget::ModuleWidget(), hal::PythonEditor::PythonEditor(), hal::SelectionDetailsWidget::SelectionDetailsWidget(), hal::PythonEditor::setToolbarButtonsEnabled(), hal::ContextManagerWidget::setupToolbar(), hal::GroupingManagerWidget::setupToolbar(), hal::ModuleWidget::setupToolbar(), hal::PythonEditor::setupToolbar(), hal::SelectionDetailsWidget::setupToolbar(), hal::ModuleWidget::toggleSearchbar(), hal::PythonEditor::toggleSearchbar(), hal::ContextManagerWidget::updateSearchIcon(), hal::ModuleWidget::updateSearchIcon(), and hal::PythonEditor::updateSearchIcon().
mSearchKeysequence
QKeySequence hal::ContentWidget::mSearchKeysequence protected
Definition at line 250 of file content_widget.h.
Referenced by hal::GroupingManagerWidget::createShortcuts(), hal::ModuleWidget::createShortcuts(), hal::PythonEditor::createShortcuts(), hal::SelectionDetailsWidget::createShortcuts(), and handleSearchKeysequenceChanged().
mSearchShortcut
QShortcut* hal::ContentWidget::mSearchShortcut protected
Definition at line 249 of file content_widget.h.
Referenced by hal::GroupingManagerWidget::createShortcuts(), hal::ModuleWidget::createShortcuts(), hal::PythonEditor::createShortcuts(), hal::SelectionDetailsWidget::createShortcuts(), and handleSearchKeysequenceChanged().
Property Documentation
iconPath
QString hal::ContentWidget::iconPath read write
Definition at line 1 of file content_widget.h.
Referenced by hal::GroupingManagerWidget::handleCurrentChanged(), and hal::PythonEditor::handleCurrentTabChanged().
iconStyle
QString hal::ContentWidget::iconStyle read write
Definition at line 1 of file content_widget.h.
Referenced by hal::ContextManagerWidget::enableSearchbar(), hal::GroupingManagerWidget::enableSearchbar(), hal::GroupingManagerWidget::handleCurrentChanged(), and hal::PythonEditor::handleCurrentTabChanged().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/content_widget/content_widget.h
/home/runner/work/hal/hal/plugins/gui/src/content_widget/content_widget.cpp