HAL: hal::MainWindow Class Reference
hal::MainWindow Class Reference
HAL Gui
The top level widget.
#include <main_window.h>
Public Types
enum StyleSheetOption { Dark , Light }
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Public Member Functions
Q_ENUM (StyleSheetOption) explicit MainWindow(QWidget *parent
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
virtual void setVisible (bool visible)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
virtual QSize sizeHint () const const
virtual QSize minimumSizeHint () const const
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Properties
QString halIconPath
QString halIconStyle
QString openFileIconPath
QString openFileIconStyle
QString quitIconPath
QString quitIconStyle
QString settingsIconPath
QString settingsIconStyle
QString pluginsIconPath
QString pluginsIconStyle
QString undoIconPath
QString undoIconStyle
QString disabledIconStyle
QString neGateIconPath
QString neGateIconStyle
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Q_PROPERTY Functions
static SettingsItemDropdown * sSettingStyle = nullptr
QString halIconPath () const
QString halIconStyle () const
QString openFileIconPath () const
QString openFileIconStyle () const
QString quitIconPath () const
QString quitIconStyle () const
QString settingsIconPath () const
QString settingsIconStyle () const
QString pluginsIconPath () const
QString pluginsIconStyle () const
QString undoIconPath () const
QString undoIconStyle () const
QString disabledIconStyle () const
QString neGateIconPath () const
QString neGateIconStyle () const
void setHalIconPath (const QString &path)
void setHalIconStyle (const QString &style)
void setOpenFileIconPath (const QString &path)
void setOpenFileIconStyle (const QString &style)
void setQuitIconPath (const QString &path)
void setQuitIconStyle (const QString &style)
void setScheduleIconPath (const QString &path)
void setScheduleIconStyle (const QString &style)
void setRunIconPath (const QString &path)
void setRunIconStyle (const QString &style)
void setContentIconPath (const QString &path)
void setContentIconStyle (const QString &style)
void setSettingsIconPath (const QString &path)
void setSettingsIconStyle (const QString &style)
void setPluginsIconPath (const QString &path)
void setPluginsIconStyle (const QString &style)
void setUndoIconPath (const QString &path)
void setUndoIconStyle (const QString &style)
void setDisabledIconStyle (const QString &style)
void setNeGateIconPath (const QString &path)
void setNeGateIconStyle (const QString &style)
void addContent (ContentWidget *widget, int index, content_anchor anchor)
void removeContent (ContentWidget *widget)
void clear ()
void onActionQuitTriggered ()
void onActionCloseDocumentTriggered ()
void openSettings ()
void closeSettings ()
void closeGateLibraryManager ()
void openPluginManager ()
void closePluginManager ()
void handleActionNew ()
void handleActionImportNetlist ()
void handleActionOpenProject ()
void handleFileOpened (const QString &fileName)
void handleProjectOpened (const QString &projDir, const QString &fileName)
void handleSaveTriggered ()
void handleSaveAsTriggered ()
void handleActionCloseFile ()
void handleActionStartRecording ()
void handleActionStopRecording ()
void handleActionPlayMacro ()
void handleActionUndo ()
void handleActionAbout ()
void handleActionExport ()
void handleActionGatelibraryManager ()
void enableUndo (bool enable=true)
void reloadStylsheet (int istyle)
Additional Inherited Members
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Protected Member Functions inherited from QWidget
virtual bool event (QEvent *event) override
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void paintEvent (QPaintEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void contextMenuEvent (QContextMenuEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void dragEnterEvent (QDragEnterEvent *event)
virtual void dragMoveEvent (QDragMoveEvent *event)
virtual void dragLeaveEvent (QDragLeaveEvent *event)
virtual void dropEvent (QDropEvent *event)
virtual void showEvent (QShowEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual void changeEvent (QEvent *event)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
virtual void inputMethodEvent (QInputMethodEvent *event)
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
virtual bool focusNextPrevChild (bool next)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Detailed Description
The top level widget.
One widget to rule them all,
one widget to create them,
One widget to bring them all
and in the dark theme bind them.
Definition at line 64 of file main_window.h.
Member Enumeration Documentation
StyleSheetOption
enum hal::MainWindow::StyleSheetOption
Enumerator
Dark
Light
Definition at line 85 of file main_window.h.
Member Function Documentation
addContent()
void hal::MainWindow::addContent (ContentWidget * widget, int index, content_anchor anchor)
Add a content widget to the layout area.
Parameters
widget - The content widget to add
index - The position index within the anchor, the widget should be put in
anchor - The anchor, the widget should be assigned to
Definition at line 503 of file main_window.cpp.
Referenced by hal::ContentManager::addExternalWidget(), and hal::ContentManager::handleOpenDocument().
clear()
void hal::MainWindow::clear ()
Definition at line 514 of file main_window.cpp.
closeGateLibraryManager
void hal::MainWindow::closeGateLibraryManager () slot
Q_SLOT to close the Gatelibrary menu.
Definition at line 554 of file main_window.cpp.
closePluginManager
void hal::MainWindow::closePluginManager () slot
Q_SLOT to close the PluginManager menu.
Definition at line 584 of file main_window.cpp.
closeSettings
void hal::MainWindow::closeSettings () slot
Q_SLOT to close the settings menu.
Definition at line 544 of file main_window.cpp.
disabledIconStyle()
QString hal::MainWindow::disabledIconStyle () const
Definition at line 424 of file main_window.cpp.
enableUndo
void hal::MainWindow::enableUndo (bool enable = true) slot
Definition at line 912 of file main_window.cpp.
References hal::enable, and hal::gui_utility::getStyledSvgIcon().
halIconPath()
QString hal::MainWindow::halIconPath () const
Q_PROPERTY READ function for the hal icon path.
Returns
the hal icon path
Definition at line 355 of file main_window.cpp.
halIconStyle()
QString hal::MainWindow::halIconStyle () const
Q_PROPERTY READ function for the hal icon style.
Returns
the hal icon style
Definition at line 360 of file main_window.cpp.
handleActionAbout
void hal::MainWindow::handleActionAbout () slot
Q_SLOT to show information about hal version and license
Definition at line 901 of file main_window.cpp.
References QDialog::exec().
handleActionCloseFile
void hal::MainWindow::handleActionCloseFile () slot
Q_SLOT to provide a logic for the close action. (Currently unused)
Definition at line 919 of file main_window.cpp.
Referenced by hal::FileActions::setup().
handleActionExport
void hal::MainWindow::handleActionExport () slot
Q_SLOT to export netlist to file. Exporter will be determined by file extension
Definition at line 709 of file main_window.cpp.
References QAction::data(), hal::ExportRegisteredFormat::exportNetlist(), hal::gNetlist, QVariant::isNull(), hal::ExportRegisteredFormat::queryFilename(), and QVariant::toStringList().
handleActionGatelibraryManager
void hal::MainWindow::handleActionGatelibraryManager () slot
Q_SLOT to export netlist to file. Exporter will be determined by file extension
Definition at line 721 of file main_window.cpp.
References QMessageBox::AcceptRole, QMessageBox::addButton(), QMessageBox::Cancel, QMessageBox::clickedButton(), QMessageBox::exec(), hal::gFileStatusManager, hal::gNetlist, hal::FileStatusManager::isGatelibModified(), QMessageBox::Open, QMessageBox::setText(), QWidget::setToolTip(), and QMessageBox::setWindowTitle().
Referenced by hal::FileActions::setup().
handleActionImportNetlist
void hal::MainWindow::handleActionImportNetlist () slot
Q_SLOT to import a netlist. Asks the user for the .hal/.vhdl/.v file to open.
Definition at line 648 of file main_window.cpp.
References QSettings::contains(), QDir::currentPath(), QMessageBox::exec(), hal::ActionOpenNetlistFile::exec(), QFileDialog::getOpenFileName(), hal::gGuiState, hal::gNetlist, hal::gPluginRelay, QString::isEmpty(), QString::isNull(), hal::GuiPluginTable::listFacFeature(), hal::GuiPluginTable::loadFeature(), hal::PluginRelay::mGuiPluginTable, hal::MSG_PROJECT_ALREADY_OPEN, QMessageBox::Ok, QMessageBox::setDefaultButton(), QMessageBox::setInformativeText(), QMessageBox::setStandardButtons(), QWidget::setStyleSheet(), QMessageBox::setText(), QSettings::setValue(), QFileInfo::suffix(), hal::SupportedFileFormats::toFileDialog(), QVariant::toString(), and QSettings::value().
handleActionNew
void hal::MainWindow::handleActionNew () slot
Q_SLOT to create a new empty netlist. Asks the user for the gate_library. Emits FileManager::fileOpened() on success.
Definition at line 599 of file main_window.cpp.
References QMessageBox::exec(), hal::ActionOpenNetlistFile::exec(), hal::gNetlist, hal::MSG_PROJECT_ALREADY_OPEN, QMessageBox::Ok, QMessageBox::setDefaultButton(), QMessageBox::setInformativeText(), QMessageBox::setStandardButtons(), QWidget::setStyleSheet(), and QMessageBox::setText().
Referenced by hal::FileActions::setup().
handleActionOpenProject
void hal::MainWindow::handleActionOpenProject () slot
Q_SLOT to open a hal project located in project directory.
Definition at line 617 of file main_window.cpp.
References QDialog::Accepted, QList::at(), QDir::currentPath(), QDialog::exec(), QMessageBox::exec(), hal::ActionOpenNetlistFile::exec(), hal::gNetlist, QString::isEmpty(), hal::MSG_PROJECT_ALREADY_OPEN, QMessageBox::Ok, QFileDialog::selectedFiles(), QMessageBox::setDefaultButton(), QMessageBox::setInformativeText(), QMessageBox::setStandardButtons(), QWidget::setStyleSheet(), QMessageBox::setText(), QList::size(), QFileInfo::suffix(), and QMessageBox::warning().
Referenced by hal::FileActions::setup().
handleActionPlayMacro
void hal::MainWindow::handleActionPlayMacro () slot
Q_SLOT to play recorded macro. Will query for XML file name.
Definition at line 894 of file main_window.cpp.
References QFileDialog::getOpenFileName(), and QString::isEmpty().
handleActionStartRecording
void hal::MainWindow::handleActionStartRecording () slot
Q_SLOT to start macro recording. Internally only a marker is set since user interactions are recorded anyhow.
Definition at line 857 of file main_window.cpp.
handleActionStopRecording
void hal::MainWindow::handleActionStopRecording () slot
Q_SLOT to end macro recording saving user interactions to XML file
Definition at line 865 of file main_window.cpp.
References QMessageBox::Cancel, QString::contains(), QFileDialog::getSaveFileName(), hal::UserActionManager::hasRecorded(), QString::isEmpty(), QMessageBox::Retry, and hal::UserActionManager::setStopRecording().
handleActionUndo
void hal::MainWindow::handleActionUndo () slot
Q_SLOT to undo last interaction if it can be undone
Definition at line 907 of file main_window.cpp.
handleFileOpened
void hal::MainWindow::handleFileOpened (const QString & fileName) slot
Q_SLOT to switch to the layout area after a file was opened (or a new one was created).
Parameters
fileName
Definition at line 695 of file main_window.cpp.
References hal::gPythonContext.
handleProjectOpened
void hal::MainWindow::handleProjectOpened (const QString & projDir, const QString & fileName) slot
Q_SLOT to switch to the layout area after a project was opened (or a new one was created).
Parameters
projDir - the project directory
fileName - the netlist file
Definition at line 687 of file main_window.cpp.
handleSaveAsTriggered
void hal::MainWindow::handleSaveAsTriggered () slot
Q_SLOT to save the current project as a new .hal file. Will query for new name. call to FileManager::emitSaveTriggered().
Definition at line 787 of file main_window.cpp.
References hal::gContentManager, QString::isEmpty(), and hal::ContentManager::setWindowTitle().
Referenced by hal::FileActions::setup().
handleSaveTriggered
void hal::MainWindow::handleSaveTriggered () slot
Q_SLOT to save the current project as a .hal file. call to FileManager::emitSaveTriggered().
Definition at line 794 of file main_window.cpp.
References QString::fromStdString(), hal::gContentManager, hal::ProjectManager::get_project_directory(), hal::ProjectManager::get_project_status(), and hal::ContentManager::setWindowTitle().
Referenced by hal::FileActions::setup().
neGateIconPath()
QString hal::MainWindow::neGateIconPath () const
Definition at line 415 of file main_window.cpp.
neGateIconStyle()
QString hal::MainWindow::neGateIconStyle () const
Definition at line 419 of file main_window.cpp.
onActionCloseDocumentTriggered
void hal::MainWindow::onActionCloseDocumentTriggered () slot
Q_SLOT to close the current document. It is called after the file manager closed the file.
Definition at line 526 of file main_window.cpp.
onActionQuitTriggered
void hal::MainWindow::onActionQuitTriggered () slot
Q_SLOT to quit the program.
Definition at line 925 of file main_window.cpp.
openFileIconPath()
QString hal::MainWindow::openFileIconPath () const
Q_PROPERTY READ function for the 'Open File'-icon path.
Returns
the 'Open File'-icon path
Definition at line 365 of file main_window.cpp.
openFileIconStyle()
QString hal::MainWindow::openFileIconStyle () const
Q_PROPERTY READ function for the 'Open File'-icon style.
Returns
the 'Open File'-icon style
Definition at line 370 of file main_window.cpp.
openPluginManager
void hal::MainWindow::openPluginManager () slot
Q_SLOT to open (toggle to the) PluginManager menu.
Definition at line 564 of file main_window.cpp.
References hal::gFileStatusManager, and hal::FileStatusManager::isGatelibModified().
openSettings
void hal::MainWindow::openSettings () slot
Q_SLOT to open (toggle to the) settings menu.
Definition at line 531 of file main_window.cpp.
References hal::gFileStatusManager, and hal::FileStatusManager::isGatelibModified().
pluginsIconPath()
QString hal::MainWindow::pluginsIconPath () const
Q_PROPERTY READ function for the 'plugins'-icon path.
Returns
the 'plugins'-icon path
Definition at line 395 of file main_window.cpp.
pluginsIconStyle()
QString hal::MainWindow::pluginsIconStyle () const
Q_PROPERTY READ function for the 'plugins'-icon style.
Returns
the 'plugins'-icon style
Definition at line 400 of file main_window.cpp.
Q_ENUM()
hal::MainWindow::Q_ENUM (StyleSheetOption)
The Constructor.
Parameters
parent - The parent widget
quitIconPath()
QString hal::MainWindow::quitIconPath () const
Q_PROPERTY READ function for the 'Quit HAL session'-icon path.
Returns
the 'Quit HAL session'-icon path
Definition at line 375 of file main_window.cpp.
quitIconStyle()
QString hal::MainWindow::quitIconStyle () const
Q_PROPERTY READ function for the 'Quit HAL session'-icon style.
Returns
the 'Quit HAL session'-icon style
Definition at line 380 of file main_window.cpp.
reloadStylsheet
void hal::MainWindow::reloadStylsheet (int istyle) slot
Definition at line 335 of file main_window.cpp.
References QFile::open(), QIODevice::readAll(), and QIODevice::ReadOnly.
removeContent()
void hal::MainWindow::removeContent (ContentWidget * widget)
Remove a content widget from the layout area.
Parameters
widget - The content widget to remove
Definition at line 508 of file main_window.cpp.
setContentIconPath()
void hal::MainWindow::setContentIconPath (const QString & path)
Q_PROPERTY WRITE function for the 'Duplicate'-icon path.
Parameters
path - The new path
setContentIconStyle()
void hal::MainWindow::setContentIconStyle (const QString & style)
Q_PROPERTY WRITE function for the 'Duplicate'-icon style.
Parameters
style - The new style
setDisabledIconStyle()
void hal::MainWindow::setDisabledIconStyle (const QString & style)
Definition at line 498 of file main_window.cpp.
setHalIconPath()
void hal::MainWindow::setHalIconPath (const QString & path)
Q_PROPERTY WRITE function for the hal icon path.
Parameters
path - The new path
Definition at line 429 of file main_window.cpp.
setHalIconStyle()
void hal::MainWindow::setHalIconStyle (const QString & style)
Q_PROPERTY WRITE function for the hal icon style.
Parameters
style - The new style
Definition at line 434 of file main_window.cpp.
setNeGateIconPath()
void hal::MainWindow::setNeGateIconPath (const QString & path)
Definition at line 489 of file main_window.cpp.
setNeGateIconStyle()
void hal::MainWindow::setNeGateIconStyle (const QString & style)
Definition at line 493 of file main_window.cpp.
setOpenFileIconPath()
void hal::MainWindow::setOpenFileIconPath (const QString & path)
Q_PROPERTY WRITE function for the 'Open File'-icon path.
Parameters
path - The new path
Definition at line 439 of file main_window.cpp.
setOpenFileIconStyle()
void hal::MainWindow::setOpenFileIconStyle (const QString & style)
Q_PROPERTY WRITE function for the 'Open File'-icon style.
Parameters
style - The new style
Definition at line 444 of file main_window.cpp.
setPluginsIconPath()
void hal::MainWindow::setPluginsIconPath (const QString & path)
Q_PROPERTY WRITE function for the 'Plugins'-icon path.
Parameters
path - The new path
Definition at line 469 of file main_window.cpp.
setPluginsIconStyle()
void hal::MainWindow::setPluginsIconStyle (const QString & style)
Q_PROPERTY WRITE function for the 'Plugins'-icon style.
Parameters
style - The new style
Definition at line 474 of file main_window.cpp.
setQuitIconPath()
void hal::MainWindow::setQuitIconPath (const QString & path)
Q_PROPERTY WRITE function for the 'Quit HAL session'-icon path.
Parameters
path - The new path
Definition at line 449 of file main_window.cpp.
setQuitIconStyle()
void hal::MainWindow::setQuitIconStyle (const QString & style)
Q_PROPERTY WRITE function for the 'Quit HAL session'-icon style.
Parameters
style - The new style
Definition at line 454 of file main_window.cpp.
setRunIconPath()
void hal::MainWindow::setRunIconPath (const QString & path)
Q_PROPERTY WRITE function for the 'Run Script'-icon path.
Parameters
path - The new path
setRunIconStyle()
void hal::MainWindow::setRunIconStyle (const QString & style)
Q_PROPERTY WRITE function for the 'Duplicate'-icon path.
Parameters
style - The new style
setScheduleIconPath()
void hal::MainWindow::setScheduleIconPath (const QString & path)
Q_PROPERTY WRITE function for the 'Schedule'-icon path.
Parameters
path - The new path
setScheduleIconStyle()
void hal::MainWindow::setScheduleIconStyle (const QString & style)
Q_PROPERTY WRITE function for the 'Schedule'-icon style.
Parameters
style - The new style
setSettingsIconPath()
void hal::MainWindow::setSettingsIconPath (const QString & path)
Q_PROPERTY WRITE function for the 'Settings'-icon path.
Parameters
path - The new path
Definition at line 459 of file main_window.cpp.
setSettingsIconStyle()
void hal::MainWindow::setSettingsIconStyle (const QString & style)
Q_PROPERTY WRITE function for the 'Settings'-icon style.
Parameters
style - The new style
Definition at line 464 of file main_window.cpp.
settingsIconPath()
QString hal::MainWindow::settingsIconPath () const
Q_PROPERTY READ function for the 'Settings'-icon path.
Returns
the 'Settings'-icon path
Definition at line 385 of file main_window.cpp.
settingsIconStyle()
QString hal::MainWindow::settingsIconStyle () const
Q_PROPERTY READ function for the 'Settings'-icon style.
Returns
the 'Settings'-icon style
Definition at line 390 of file main_window.cpp.
setUndoIconPath()
void hal::MainWindow::setUndoIconPath (const QString & path)
Definition at line 479 of file main_window.cpp.
setUndoIconStyle()
void hal::MainWindow::setUndoIconStyle (const QString & style)
Definition at line 484 of file main_window.cpp.
undoIconPath()
QString hal::MainWindow::undoIconPath () const
Definition at line 405 of file main_window.cpp.
undoIconStyle()
QString hal::MainWindow::undoIconStyle () const
Definition at line 410 of file main_window.cpp.
Member Data Documentation
sSettingStyle
SettingsItemDropdown * hal::MainWindow::sSettingStyle = nullptr static
Definition at line 302 of file main_window.h.
Referenced by hal::GraphContext::GraphContext(), and hal::PythonConsole::PythonConsole().
Property Documentation
disabledIconStyle
QString hal::MainWindow::disabledIconStyle read write
Definition at line 1 of file main_window.h.
halIconPath
QString hal::MainWindow::halIconPath read write
Definition at line 1 of file main_window.h.
halIconStyle
QString hal::MainWindow::halIconStyle read write
Definition at line 1 of file main_window.h.
neGateIconPath
QString hal::MainWindow::neGateIconPath read write
Definition at line 1 of file main_window.h.
neGateIconStyle
QString hal::MainWindow::neGateIconStyle read write
Definition at line 1 of file main_window.h.
openFileIconPath
QString hal::MainWindow::openFileIconPath read write
Definition at line 1 of file main_window.h.
openFileIconStyle
QString hal::MainWindow::openFileIconStyle read write
Definition at line 1 of file main_window.h.
pluginsIconPath
QString hal::MainWindow::pluginsIconPath read write
Definition at line 1 of file main_window.h.
pluginsIconStyle
QString hal::MainWindow::pluginsIconStyle read write
Definition at line 1 of file main_window.h.
quitIconPath
QString hal::MainWindow::quitIconPath read write
Definition at line 1 of file main_window.h.
quitIconStyle
QString hal::MainWindow::quitIconStyle read write
Definition at line 1 of file main_window.h.
settingsIconPath
QString hal::MainWindow::settingsIconPath read write
Definition at line 1 of file main_window.h.
settingsIconStyle
QString hal::MainWindow::settingsIconStyle read write
Definition at line 1 of file main_window.h.
undoIconPath
QString hal::MainWindow::undoIconPath read write
Definition at line 1 of file main_window.h.
undoIconStyle
QString hal::MainWindow::undoIconStyle read write
Definition at line 1 of file main_window.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/main_window/main_window.h
/home/runner/work/hal/hal/plugins/gui/src/main_window/main_window.cpp