HAL: hal::GateSelectHistory Class Reference
hal::GateSelectHistory Class Reference
The GateSelectHistory class singleton comprises a list of user selected modules.
#include <gate_select_model.h>
Public Member Functions
void add (u32 id)
Public Member Functions inherited from QList< u32 >
QList ()
QList (const QList< T > &other)
QList (QList< T > &&other)
QList (std::initializer_list< T > args)
QList (InputIterator first, InputIterator last)
~QList ()
QList< T > & operator= (const QList< T > &other)
QList< T > & operator= (QList< T > &&other)
void swap (QList< T > &other)
void swap (int i, int j)
bool operator== (const QList< T > &other) const const
bool operator!= (const QList< T > &other) const const
int size () const const
bool isEmpty () const const
void clear ()
const T & at (int i) const const
const T & operator[] (int i) const const
T & operator[] (int i)
void reserve (int alloc)
void append (const T &value)
void append (const QList< T > &value)
void prepend (const T &value)
void insert (int i, const T &value)
QList::iterator insert (QList::iterator before, const T &value)
void replace (int i, const T &value)
void removeAt (int i)
int removeAll (const T &value)
bool removeOne (const T &value)
T takeAt (int i)
T takeFirst ()
T takeLast ()
void move (int from, int to)
void swapItemsAt (int i, int j)
int indexOf (const T &value, int from) const const
int lastIndexOf (const T &value, int from) const const
bool contains (const T &value) const const
int count (const T &value) const const
int count () const const
QList::iterator begin ()
QList::const_iterator begin () const const
QList::const_iterator cbegin () const const
QList::const_iterator constBegin () const const
QList::iterator end ()
QList::const_iterator end () const const
QList::const_iterator cend () const const
QList::const_iterator constEnd () const const
QList::reverse_iterator rbegin ()
QList::const_reverse_iterator rbegin () const const
QList::reverse_iterator rend ()
QList::const_reverse_iterator rend () const const
QList::const_reverse_iterator crbegin () const const
QList::const_reverse_iterator crend () const const
QList::iterator erase (QList::iterator pos)
QList::iterator erase (QList::iterator begin, QList::iterator end)
int length () const const
T & first ()
const T & first () const const
const T & constFirst () const const
T & last ()
const T & last () const const
const T & constLast () const const
void removeFirst ()
void removeLast ()
bool startsWith (const T &value) const const
bool endsWith (const T &value) const const
QList< T > mid (int pos, int length) const const
T value (int i) const const
T value (int i, const T &defaultValue) const const
void push_back (const T &value)
void push_front (const T &value)
T & front ()
const T & front () const const
T & back ()
const T & back () const const
void pop_front ()
void pop_back ()
bool empty () const const
QList< T > & operator+= (const QList< T > &other)
QList< T > & operator+= (const T &value)
QList< T > operator+ (const QList< T > &other) const const
QList< T > & operator<< (const T &value)
QList< T > & operator<< (const QList< T > &other)
QDataStream & operator<< (QDataStream &out, const QList< T > &list)
QVector< T > toVector () const const
QSet< T > toSet () const const
std::list< T > toStdList () const const
bool operator< (const QList< T > &lhs, const QList< T > &rhs)
bool operator<= (const QList< T > &lhs, const QList< T > &rhs)
bool operator> (const QList< T > &lhs, const QList< T > &rhs)
bool operator>= (const QList< T > &lhs, const QList< T > &rhs)
uint qHash (const QList< T > &key, uint seed)
QDataStream & operator>> (QDataStream &in, QList< T > &list)
Static Public Member Functions
static GateSelectHistory * instance ()
Static Public Member Functions inherited from QList< u32 >
QList< T > fromVector (const QVector< T > &vector)
QList< T > fromSet (const QSet< T > &set)
QList< T > fromStdList (const std::list< T > &list)
Additional Inherited Members
Public Attributes inherited from QList< u32 >
typedef reverse_iterator
typedef const_reverse_iterator
typedef Iterator
typedef ConstIterator
typedef size_type
typedef value_type
typedef pointer
typedef const_pointer
typedef reference
typedef const_reference
typedef difference_type
Detailed Description
The GateSelectHistory class singleton comprises a list of user selected modules.
Definition at line 145 of file gate_select_model.h.
Member Function Documentation
add()
void hal::GateSelectHistory::add (u32 id)
Definition at line 30 of file gate_select_model.cpp.
References QList< u32 >::prepend(), and QList< u32 >::removeAll().
Referenced by hal::GateDialog::accept().
instance()
GateSelectHistory * hal::GateSelectHistory::instance () static
Definition at line 23 of file gate_select_model.cpp.
Referenced by hal::GateDialog::accept(), hal::GateDialog::GateDialog(), and hal::GateSelectModel::GateSelectModel().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/module_dialog/gate_select_model.h
/home/runner/work/hal/hal/plugins/gui/src/module_dialog/gate_select_model.cpp