HAL: hal::GraphLayouter Class Reference
hal::GraphLayouter Class Reference abstract
HAL Gui » Graph Widget » Layouters
Base class for all specific layouters.
#include <graph_layouter.h>
Public Member Functions
GraphLayouter (GraphContext *context, QObject *parent=nullptr)
~GraphLayouter ()
virtual QString name () const =0
virtual QString mDescription () const =0
virtual void add (const QSet< u32 > modules, const QSet< u32 > gates, const QSet< u32 > nets, PlacementHint placement=PlacementHint())=0
virtual void remove (const QSet< u32 > modules, const QSet< u32 > gates, const QSet< u32 > nets)=0
void layout ()
void alternateLayout ()
GraphicsScene * scene () const
const QMap< Node, QPoint > nodeToPositionMap () const
const QMap< QPoint, Node > positionToNodeMap () const
QPoint gridPointByItem (GraphicsNode *item) const
void dumpNodePositions (const QPoint &search) const
void setNodePosition (const Node &n, const QPoint &p)
void swapNodePositions (const Node &n1, const Node &n2)
void removeNodeFromMaps (const Node &n)
int minXIndex () const
int minYIndex () const
bool done () const
bool optimizeNetLayoutEnabled ()
void setOptimizeNetLayoutEnabled (bool enbabled)
QVector< qreal > xValues () const
QVector< qreal > yValues () const
qreal maxNodeWidth () const
qreal maxNodeHeight () const
qreal defaultGridWidth () const
qreal defaultGridHeight () const
qreal gridXposition (int ix) const
qreal gridYposition (int iy) const
const NodeBoxes & boxes () const
void prepareRollback ()
bool canRollback () const
bool rollback ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Attributes
GraphicsScene * mScene
GraphContext * mParentContext
QMap< Node, QPoint > mNodeToPositionMap
QMap< QPoint, Node > mPositionToNodeMap
QMap< Node, QPoint > mNodeToPositionRollback
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Base class for all specific layouters.
The abstract parent class for all graph layouters. The graph layouter is responsible for building up the scene using the information given in the passed GraphContext. It places the respective GraphicItems for the given gates and modules in positions that are calculated intelligently considering their order, connections and dimensions. Afterwards, the paths of GraphicsNet objects will be computed to visualize the nets between gates/modules.
If the GraphContext changes later on (e.g. gates/modules are added/removed), the GraphLayouter has the task to apply the changes in the scene.
Definition at line 74 of file graph_layouter.h.
Constructor & Destructor Documentation
GraphLayouter()
hal::GraphLayouter::GraphLayouter (GraphContext * context, QObject * parent = nullptr) explicit
Constructor.
Parameters
context - The GraphContext the layouter works on
parent - The parent QObject
Definition at line 44 of file graph_layouter.cpp.
References QObject::connect(), hal::CommentManager::entryAboutToBeDeleted(), hal::CommentManager::entryAdded(), hal::CommentManager::entryModified(), hal::gCommentManager, hal::gContentManager, hal::ContentManager::getSelectionDetailsWidget(), hal::GraphicsScene::handleHighlight(), mScene, and hal::SelectionDetailsWidget::triggerHighlight().
~GraphLayouter()
hal::GraphLayouter::~GraphLayouter ()
Destructor.
Definition at line 56 of file graph_layouter.cpp.
References QObject::deleteLater(), and mScene.
Member Function Documentation
add()
virtual void hal::GraphLayouter::add (const QSet< u32 > modules, const QSet< u32 > gates, const QSet< u32 > nets, PlacementHint placement = PlacementHint()) pure virtual
Implemented in hal::PhysicalGraphLayouter, and hal::StandardGraphLayouter.
alternateLayout()
void hal::GraphLayouter::alternateLayout ()
Definition at line 206 of file graph_layouter.cpp.
References defaultGridHeight(), defaultGridWidth(), hal::GraphicsScene::handleExternSelectionChanged(), hal::GraphContext::layoutProgress(), hal::GraphicsScene::moveNetsToBackground(), mParentContext, mScene, xValues(), and yValues().
Referenced by layout().
boxes()
const NodeBoxes& hal::GraphLayouter::boxes () const inline
Definition at line 325 of file graph_layouter.h.
Referenced by hal::ActionMoveNode::exec(), hal::GraphContext::getNetDestination(), hal::GraphContext::getNetSource(), hal::GraphGraphicsView::handleShortestPath(), and hal::GraphContext::writeToFile().
canRollback()
bool hal::GraphLayouter::canRollback () const
Definition at line 277 of file graph_layouter.cpp.
References mNodeToPositionRollback.
Referenced by rollback(), and hal::GraphWidget::showProgress().
defaultGridHeight()
qreal hal::GraphLayouter::defaultGridHeight () const
Definition at line 179 of file graph_layouter.cpp.
Referenced by alternateLayout(), gridYposition(), and layout().
defaultGridWidth()
qreal hal::GraphLayouter::defaultGridWidth () const
Definition at line 174 of file graph_layouter.cpp.
Referenced by alternateLayout(), gridXposition(), and layout().
done()
bool hal::GraphLayouter::done () const
Definition at line 149 of file graph_layouter.cpp.
Referenced by hal::GraphWidget::storeViewport().
dumpNodePositions()
void hal::GraphLayouter::dumpNodePositions (const QPoint & search) const
Definition at line 71 of file graph_layouter.cpp.
References QTextStream::AlignRight, hal::Node::Module, mPositionToNodeMap, QTextStream::setFieldAlignment(), QTextStream::setFieldWidth(), QIODevice::WriteOnly, QPoint::x(), and QPoint::y().
gridPointByItem()
QPoint hal::GraphLayouter::gridPointByItem (GraphicsNode * item) const
Definition at line 128 of file graph_layouter.cpp.
References hal::NodeBoxes::boxForItem(), hal::NodeBox::x(), and hal::NodeBox::y().
gridXposition()
qreal hal::GraphLayouter::gridXposition (int ix) const
Definition at line 184 of file graph_layouter.cpp.
References defaultGridWidth(), QVector::isEmpty(), QVector::last(), and QVector::size().
gridYposition()
qreal hal::GraphLayouter::gridYposition (int iy) const
Definition at line 195 of file graph_layouter.cpp.
References defaultGridHeight(), QVector::isEmpty(), QVector::last(), and QVector::size().
layout()
void hal::GraphLayouter::layout ()
Does the actual layout process.
Definition at line 236 of file graph_layouter.cpp.
References alternateLayout(), defaultGridHeight(), defaultGridWidth(), hal::GraphicsScene::deleteAllItems(), QElapsedTimer::elapsed(), hal::GraphicsScene::handleExternSelectionChanged(), hal::GraphicsScene::moveNetsToBackground(), mScene, QElapsedTimer::start(), xValues(), and yValues().
Referenced by hal::GraphContext::abortLayout().
maxNodeHeight()
qreal hal::GraphLayouter::maxNodeHeight () const
Definition at line 169 of file graph_layouter.cpp.
maxNodeWidth()
qreal hal::GraphLayouter::maxNodeWidth () const
Definition at line 164 of file graph_layouter.cpp.
mDescription()
virtual QString hal::GraphLayouter::mDescription () const pure virtual
Gets an inforaml description of the layouter.
Returns
the description of the layouter.
Implemented in hal::PhysicalGraphLayouter, and hal::StandardGraphLayouter.
minXIndex()
int hal::GraphLayouter::minXIndex () const
Definition at line 139 of file graph_layouter.cpp.
minYIndex()
int hal::GraphLayouter::minYIndex () const
Definition at line 144 of file graph_layouter.cpp.
name()
virtual QString hal::GraphLayouter::name () const pure virtual
Gets the name of the layouter.
Returns
the name of the layouter.
Implemented in hal::PhysicalGraphLayouter, and hal::StandardGraphLayouter.
nodeToPositionMap()
const QMap< Node, QPoint > hal::GraphLayouter::nodeToPositionMap () const
Definition at line 66 of file graph_layouter.cpp.
References mNodeToPositionMap.
Referenced by hal::GraphContext::abortLayout(), hal::ActionUnfoldModule::exec(), hal::ActionFoldModule::exec(), hal::ActionRemoveItemsFromObject::exec(), and hal::GraphContext::unfoldModule().
optimizeNetLayoutEnabled()
bool hal::GraphLayouter::optimizeNetLayoutEnabled ()
Definition at line 2868 of file graph_layouter.cpp.
positionToNodeMap()
const QMap< QPoint, Node > hal::GraphLayouter::positionToNodeMap () const
Definition at line 84 of file graph_layouter.cpp.
References mPositionToNodeMap.
Referenced by hal::GraphContext::moveNodeAction().
prepareRollback()
void hal::GraphLayouter::prepareRollback ()
Definition at line 271 of file graph_layouter.cpp.
References mNodeToPositionMap, and mNodeToPositionRollback.
Referenced by hal::GraphContext::unfoldModule().
remove()
virtual void hal::GraphLayouter::remove (const QSet< u32 > modules, const QSet< u32 > gates, const QSet< u32 > nets) pure virtual
Implemented in hal::PhysicalGraphLayouter, and hal::StandardGraphLayouter.
removeNodeFromMaps()
void hal::GraphLayouter::removeNodeFromMaps (const Node & n)
Definition at line 118 of file graph_layouter.cpp.
References mNodeToPositionMap, and mPositionToNodeMap.
Referenced by hal::PhysicalGraphLayouter::remove(), and hal::StandardGraphLayouter::remove().
rollback()
bool hal::GraphLayouter::rollback ()
Definition at line 282 of file graph_layouter.cpp.
References canRollback(), mNodeToPositionMap, mNodeToPositionRollback, and mPositionToNodeMap.
Referenced by hal::GraphContext::abortLayout().
scene()
GraphicsScene * hal::GraphLayouter::scene () const
Gets the GraphicsScene the layouter works on.
Returns
the GraphicScene.
Definition at line 61 of file graph_layouter.cpp.
References mScene.
Referenced by hal::GraphContext::scene().
setNodePosition()
void hal::GraphLayouter::setNodePosition (const Node & n, const QPoint & p)
Definition at line 89 of file graph_layouter.cpp.
References mNodeToPositionMap, and mPositionToNodeMap.
Referenced by hal::GraphContext::moveNodeAction(), and hal::GraphContext::readFromFile().
setOptimizeNetLayoutEnabled()
void hal::GraphLayouter::setOptimizeNetLayoutEnabled (bool enbabled)
Definition at line 2873 of file graph_layouter.cpp.
Referenced by hal::GraphContextManager::getDefaultLayouter().
swapNodePositions()
void hal::GraphLayouter::swapNodePositions (const Node & n1, const Node & n2)
Definition at line 103 of file graph_layouter.cpp.
References mNodeToPositionMap, and mPositionToNodeMap.
xValues()
QVector< qreal > hal::GraphLayouter::xValues () const
Definition at line 154 of file graph_layouter.cpp.
Referenced by alternateLayout(), and layout().
yValues()
QVector< qreal > hal::GraphLayouter::yValues () const
Definition at line 159 of file graph_layouter.cpp.
Referenced by alternateLayout(), and layout().
Member Data Documentation
mNodeToPositionMap
QMap<Node, QPoint> hal::GraphLayouter::mNodeToPositionMap protected
Definition at line 337 of file graph_layouter.h.
Referenced by nodeToPositionMap(), prepareRollback(), removeNodeFromMaps(), rollback(), setNodePosition(), and swapNodePositions().
mNodeToPositionRollback
QMap<Node, QPoint> hal::GraphLayouter::mNodeToPositionRollback protected
Definition at line 339 of file graph_layouter.h.
Referenced by canRollback(), prepareRollback(), and rollback().
mParentContext
GraphContext* hal::GraphLayouter::mParentContext protected
Definition at line 336 of file graph_layouter.h.
Referenced by alternateLayout().
mPositionToNodeMap
QMap<QPoint, Node> hal::GraphLayouter::mPositionToNodeMap protected
Definition at line 338 of file graph_layouter.h.
Referenced by dumpNodePositions(), positionToNodeMap(), removeNodeFromMaps(), rollback(), setNodePosition(), and swapNodePositions().
mScene
GraphicsScene* hal::GraphLayouter::mScene protected
Definition at line 335 of file graph_layouter.h.
Referenced by alternateLayout(), GraphLayouter(), layout(), scene(), and ~GraphLayouter().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/graph_layouter.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/graph_layouter.cpp