HAL: hal::SearchOptions Class Reference
hal::SearchOptions Class Reference
#include <searchoptions.h>
Public Member Functions
SearchOptions ()
SearchOptions (int code)
void setOptions (bool exactMatch, bool caseSensitive, bool regEx, QList< int > columns)
int toInt () const
bool isExactMatch () const
bool isCaseSensitive () const
bool isRegularExpression () const
const QList< int > & getColumns () const
Static Public Member Functions
static int toInt (bool exactMatch, bool caseSensitive, bool regEx, QList< int > columns)
Detailed Description
Definition at line 31 of file searchoptions.h.
Constructor & Destructor Documentation
SearchOptions() [1/2]
hal::SearchOptions::SearchOptions ()
Definition at line 7 of file searchoptions.cpp.
SearchOptions() [2/2]
hal::SearchOptions::SearchOptions (int code)
Definition at line 16 of file searchoptions.cpp.
References QList::append(), and code.
Member Function Documentation
getColumns()
const QList< int > & hal::SearchOptions::getColumns () const
Definition at line 94 of file searchoptions.cpp.
Referenced by hal::SearchProxyModel::checkRow(), and hal::SearchOptionsDialog::setOptions().
isCaseSensitive()
bool hal::SearchOptions::isCaseSensitive () const
Definition at line 84 of file searchoptions.cpp.
Referenced by hal::Searchbar::addFlags(), hal::Searchbar::filterApplied(), hal::PythonEditor::getFindFlags(), hal::SearchableLabel::handleSearchChanged(), hal::SearchProxyModel::isMatching(), hal::LoggerWidget::isMatching(), hal::MainSettingsWidget::isMatching(), hal::CommentItem::search(), hal::CodeEditor::search(), and hal::SearchOptionsDialog::setOptions().
isExactMatch()
bool hal::SearchOptions::isExactMatch () const
Definition at line 79 of file searchoptions.cpp.
Referenced by hal::Searchbar::addFlags(), hal::Searchbar::filterApplied(), hal::PythonEditor::getFindFlags(), hal::SearchableLabel::handleSearchChanged(), hal::SearchProxyModel::isMatching(), hal::LoggerWidget::isMatching(), hal::MainSettingsWidget::isMatching(), hal::CommentItem::search(), hal::CodeEditor::search(), and hal::SearchOptionsDialog::setOptions().
isRegularExpression()
bool hal::SearchOptions::isRegularExpression () const
Definition at line 89 of file searchoptions.cpp.
Referenced by hal::SearchableLabel::handleSearchChanged(), hal::SearchProxyModel::isMatching(), hal::LoggerWidget::isMatching(), hal::MainSettingsWidget::isMatching(), hal::CommentItem::search(), hal::CodeEditor::search(), and hal::SearchOptionsDialog::setOptions().
setOptions()
void hal::SearchOptions::setOptions (bool exactMatch, bool caseSensitive, bool regEx, QList< int > columns)
Definition at line 71 of file searchoptions.cpp.
Referenced by hal::SearchOptionsDialog::getOptions().
toInt() [1/2]
int hal::SearchOptions::toInt () const
Definition at line 33 of file searchoptions.cpp.
References QList::empty(), and QList::length().
Referenced by hal::SearchOptionsDialog::emitOptions(), hal::Searchbar::handleReturnPressed(), hal::Searchbar::handleSearchOptionsDialog(), hal::Searchbar::handleTextEdited(), and hal::CommentItem::search().
toInt() [2/2]
int hal::SearchOptions::toInt (bool exactMatch, bool caseSensitive, bool regEx, QList< int > columns) static
Definition at line 52 of file searchoptions.cpp.
References QList::empty(), and QList::length().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/searchbar/searchoptions.h
/home/runner/work/hal/hal/plugins/gui/src/searchbar/searchoptions.cpp