HAL: hal::ExportProjectDialog Class Reference
hal::ExportProjectDialog Class Reference
#include <export_project_dialog.h>
Public Types
enum ExportStatus {
Ok = 0, ErrorCreateTempDir = -1, ErrorCopy = -2, ErrorPrepare = -3,
ErrorCompress = -4, NoExport = -99
}
Public Types inherited from QFileDialog
enum ViewMode
enum FileMode
enum AcceptMode
enum DialogLabel
enum Option
Public Types inherited from QDialog
enum DialogCode
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Public Member Functions
ExportProjectDialog (QWidget *parent=nullptr)
bool success () const
void exportProject ()
Public Member Functions inherited from QFileDialog
QFileDialog (QWidget *parent, Qt::WindowFlags flags)
QFileDialog (QWidget *parent, const QString &caption, const QString &directory, const QString &filter)
virtual ~QFileDialog ()
void setDirectory (const QString &directory)
void setDirectory (const QDir &directory)
QDir directory () const const
void setDirectoryUrl (const QUrl &directory)
QUrl directoryUrl () const const
void selectFile (const QString &filename)
QStringList selectedFiles () const const
void selectUrl (const QUrl &url)
QList< QUrl > selectedUrls () const const
void setNameFilterDetailsVisible (bool enabled)
bool isNameFilterDetailsVisible () const const
void setNameFilter (const QString &filter)
void setNameFilters (const QStringList &filters)
QStringList nameFilters () const const
void selectNameFilter (const QString &filter)
QString selectedMimeTypeFilter () const const
QString selectedNameFilter () const const
void setMimeTypeFilters (const QStringList &filters)
QStringList mimeTypeFilters () const const
void selectMimeTypeFilter (const QString &filter)
QDir::Filters filter () const const
void setFilter (QDir::Filters filters)
void setViewMode (QFileDialog::ViewMode mode)
QFileDialog::ViewMode viewMode () const const
void setFileMode (QFileDialog::FileMode mode)
QFileDialog::FileMode fileMode () const const
void setAcceptMode (QFileDialog::AcceptMode mode)
QFileDialog::AcceptMode acceptMode () const const
void setReadOnly (bool enabled)
bool isReadOnly () const const
void setResolveSymlinks (bool enabled)
bool resolveSymlinks () const const
void setSidebarUrls (const QList< QUrl > &urls)
QList< QUrl > sidebarUrls () const const
QByteArray saveState () const const
bool restoreState (const QByteArray &state)
void setConfirmOverwrite (bool enabled)
bool confirmOverwrite () const const
void setDefaultSuffix (const QString &suffix)
QString defaultSuffix () const const
void setHistory (const QStringList &paths)
QStringList history () const const
void setItemDelegate (QAbstractItemDelegate *delegate)
QAbstractItemDelegate * itemDelegate () const const
void setIconProvider (QFileIconProvider *provider)
QFileIconProvider * iconProvider () const const
void setLabelText (QFileDialog::DialogLabel label, const QString &text)
QString labelText (QFileDialog::DialogLabel label) const const
void setSupportedSchemes (const QStringList &schemes)
QStringList supportedSchemes () const const
void setProxyModel (QAbstractProxyModel *proxyModel)
QAbstractProxyModel * proxyModel () const const
void setOption (QFileDialog::Option option, bool on)
bool testOption (QFileDialog::Option option) const const
void setOptions (QFileDialog::Options options)
QFileDialog::Options options () const const
void open (QObject *receiver, const char *member)
virtual void setVisible (bool visible) override
void fileSelected (const QString &file)
void filesSelected (const QStringList &selected)
void currentChanged (const QString &path)
void directoryEntered (const QString &directory)
void urlSelected (const QUrl &url)
void urlsSelected (const QList< QUrl > &urls)
void currentUrlChanged (const QUrl &url)
void directoryUrlEntered (const QUrl &directory)
void filterSelected (const QString &filter)
Public Member Functions inherited from QDialog
QDialog (QWidget *parent, Qt::WindowFlags f)
virtual ~QDialog ()
int result () const const
void setOrientation (Qt::Orientation orientation)
Qt::Orientation orientation () const const
void setExtension (QWidget *extension)
QWidget * extension () const const
virtual QSize sizeHint () const const override
virtual QSize minimumSizeHint () const const override
void setSizeGripEnabled (bool)
bool isSizeGripEnabled () const const
void setModal (bool modal)
void setResult (int i)
void finished (int result)
void accepted ()
void rejected ()
virtual void open ()
virtual int exec ()
virtual void reject ()
void showExtension (bool showIt)
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Additional Inherited Members
Static Public Member Functions inherited from QFileDialog
QString getOpenFileName (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options)
QUrl getOpenFileUrl (QWidget *parent, const QString &caption, const QUrl &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options, const QStringList &supportedSchemes)
QString getSaveFileName (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options)
QUrl getSaveFileUrl (QWidget *parent, const QString &caption, const QUrl &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options, const QStringList &supportedSchemes)
QString getExistingDirectory (QWidget *parent, const QString &caption, const QString &dir, QFileDialog::Options options)
QUrl getExistingDirectoryUrl (QWidget *parent, const QString &caption, const QUrl &dir, QFileDialog::Options options, const QStringList &supportedSchemes)
QStringList getOpenFileNames (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options)
QList< QUrl > getOpenFileUrls (QWidget *parent, const QString &caption, const QUrl &dir, const QString &filter, QString *selectedFilter, QFileDialog::Options options, const QStringList &supportedSchemes)
void getOpenFileContent (const QString &nameFilter, const std::function< void(const QString &, const QByteArray &)> &fileOpenCompleted)
void saveFileContent (const QByteArray &fileContent, const QString &fileNameHint)
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QFileDialog
typedef Options
Detail
List
AnyFile
ExistingFile
Directory
ExistingFiles
DirectoryOnly
AcceptOpen
AcceptSave
LookIn
FileName
FileType
Accept
Reject
ShowDirsOnly
DontResolveSymlinks
DontConfirmOverwrite
DontUseSheet
DontUseNativeDialog
ReadOnly
HideNameFilterDetails
DontUseCustomDirectoryIcons
Public Attributes inherited from QDialog
Rejected
Accepted
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Protected Member Functions inherited from QFileDialog
virtual void done (int result) override
virtual void accept () override
virtual void changeEvent (QEvent *e) override
Protected Member Functions inherited from QDialog
virtual void keyPressEvent (QKeyEvent *e) override
virtual void closeEvent (QCloseEvent *e) override
virtual void showEvent (QShowEvent *event) override
virtual void resizeEvent (QResizeEvent *) override
virtual void contextMenuEvent (QContextMenuEvent *e) override
virtual bool eventFilter (QObject *o, QEvent *e) override
Protected Member Functions inherited from QWidget
virtual bool event (QEvent *event) override
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void paintEvent (QPaintEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void dragEnterEvent (QDragEnterEvent *event)
virtual void dragMoveEvent (QDragMoveEvent *event)
virtual void dragLeaveEvent (QDragLeaveEvent *event)
virtual void dropEvent (QDropEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
virtual void inputMethodEvent (QInputMethodEvent *event)
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
virtual bool focusNextPrevChild (bool next)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Properties inherited from QFileDialog
viewMode
fileMode
acceptMode
defaultSuffix
readOnly
confirmOverwrite
resolveSymlinks
nameFilterDetailsVisible
options
supportedSchemes
Properties inherited from QDialog
sizeGripEnabled
modal
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Detailed Description
Definition at line 32 of file export_project_dialog.h.
Member Enumeration Documentation
ExportStatus
enum hal::ExportProjectDialog::ExportStatus
Enumerator
Ok
ErrorCreateTempDir
ErrorCopy
ErrorPrepare
ErrorCompress
NoExport
Definition at line 37 of file export_project_dialog.h.
Constructor & Destructor Documentation
ExportProjectDialog()
hal::ExportProjectDialog::ExportProjectDialog (QWidget * parent = nullptr)
Definition at line 19 of file export_project_dialog.cpp.
References QFileDialog::AcceptSave, QFileInfo::baseName(), QFileDialog::FileName, QFileDialog::FileType, QString::fromStdString(), hal::ProjectManager::instance(), QString::replace(), QFileDialog::selectFile(), QFileDialog::setAcceptMode(), QFileDialog::setDefaultSuffix(), QFileDialog::setLabelText(), QWidget::setWindowTitle(), and QString::simplified().
Member Function Documentation
exportProject()
void hal::ExportProjectDialog::exportProject ()
Definition at line 33 of file export_project_dialog.cpp.
References QDir::absoluteFilePath(), QFileInfo::absoluteFilePath(), QList::append(), QList::at(), QFile::copy(), QDir::Dirs, ErrorCompress, ErrorCopy, ErrorCreateTempDir, ErrorPrepare, QDirIterator::fileInfo(), QFileInfo::fileName(), QDir::Files, QString::fromStdString(), hal::ProjectJson::gateLibraryFilename(), QDirIterator::hasNext(), QDir::Hidden, hal::ProjectManager::instance(), QFileInfo::isAbsolute(), QFileInfo::isDir(), QFileInfo::isFile(), QTemporaryDir::isValid(), log_warning, QDirIterator::next(), QDir::NoDotAndDotDot, QDir::NoSymLinks, hal::ProjectJson::Ok, Ok, QTemporaryDir::path(), QDir::Readable, QString::remove(), QFileDialog::selectedFiles(), hal::ProjectJson::setGateLibraryFilename(), QString::size(), QString::startsWith(), hal::ProjectJson::status(), QDirIterator::Subdirectories, QDir::temp(), and QString::toStdString().
success()
bool hal::ExportProjectDialog::success () const inline
Definition at line 46 of file export_project_dialog.h.
References Ok.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/export/export_project_dialog.h
/home/runner/work/hal/hal/plugins/gui/src/export/export_project_dialog.cpp