HAL: hal::JsonWriteDocument Class Reference
hal::JsonWriteDocument Class Reference
#include <json_write_document.h>
Public Member Functions
JsonWriteDocument ()
virtual ~JsonWriteDocument ()
bool serialize (const std::string &filename)
void dump ()
Public Member Functions inherited from hal::JsonWriteObject
JsonWriteObject (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteObject ()
JsonWriteData & operator[] (const std::string &tag)
JsonWriteObject & add_object (const std::string &tag)
JsonWriteArray & add_array (const std::string &tag)
Public Member Functions inherited from hal::JsonWriteComplex
JsonWriteComplex (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteComplex ()
void close ()
Public Member Functions inherited from hal::JsonWriteData
JsonWriteData (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteData ()
JsonWriteData & operator= (const std::string &txt)
JsonWriteData & operator= (int ivalue)
JsonWriteData & operator= (double value)
JsonWriteData & operator= (uint64_t u64Value)
Protected Member Functions
virtual rapidjson::Document::AllocatorType & allocator () override
virtual void finalize (JsonWriteComplex *cplx) override
virtual void add_member (rapidjson::Document::ValueType &&name, rapidjson::Document::ValueType &&value, rapidjson::Document::AllocatorType &allocator) override
void dump (rapidjson::Value &parent)
Protected Attributes
rapidjson::Document mRapidDocument
Protected Attributes inherited from hal::JsonWriteComplex
std::vector< JsonWriteData * > mChildData
rapidjson::Value mRapidValue
Protected Attributes inherited from hal::JsonWriteData
std::string mTagname
JsonWriteComplex * mParent
Friends
class JsonWriteData
Detailed Description
Definition at line 231 of file json_write_document.h.
Constructor & Destructor Documentation
JsonWriteDocument()
hal::JsonWriteDocument::JsonWriteDocument ()
Definition at line 164 of file json_write_document.cpp.
References mRapidDocument.
~JsonWriteDocument()
virtual hal::JsonWriteDocument::~JsonWriteDocument () inline virtual
Definition at line 247 of file json_write_document.h.
Member Function Documentation
add_member()
void hal::JsonWriteDocument::add_member (rapidjson::Document::ValueType && name, rapidjson::Document::ValueType && value, rapidjson::Document::AllocatorType & allocator) override protected virtual
Reimplemented from hal::JsonWriteObject.
Definition at line 179 of file json_write_document.cpp.
References allocator(), mRapidDocument, and name.
allocator()
rapidjson::Document::AllocatorType & hal::JsonWriteDocument::allocator () override protected virtual
Reimplemented from hal::JsonWriteData.
Definition at line 169 of file json_write_document.cpp.
References mRapidDocument.
Referenced by add_member(), hal::JsonWriteData::allocator(), and finalize().
dump() [1/2]
void hal::JsonWriteDocument::dump ()
Dump content for debugging purpose
Definition at line 202 of file json_write_document.cpp.
References mRapidDocument.
dump() [2/2]
void hal::JsonWriteDocument::dump (rapidjson::Value & parent) protected
Definition at line 207 of file json_write_document.cpp.
References UNUSED.
finalize()
void hal::JsonWriteDocument::finalize (JsonWriteComplex * cplx) override protected virtual
Reimplemented from hal::JsonWriteObject.
Definition at line 174 of file json_write_document.cpp.
References allocator(), mRapidDocument, hal::JsonWriteComplex::mRapidValue, and hal::JsonWriteData::mTagname.
serialize()
bool hal::JsonWriteDocument::serialize (const std::string & filename)
Serialize to file method
Parameters
[in] filename The output filename
Returns
true if successful, false otherwise
Definition at line 184 of file json_write_document.cpp.
References mRapidDocument, and of.
Referenced by hal::GroupingSerializer::serialize().
Friends And Related Function Documentation
JsonWriteData
friend class JsonWriteData friend
Definition at line 233 of file json_write_document.h.
Member Data Documentation
mRapidDocument
rapidjson::Document hal::JsonWriteDocument::mRapidDocument protected
Definition at line 236 of file json_write_document.h.
Referenced by add_member(), allocator(), dump(), finalize(), JsonWriteDocument(), and serialize().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/include/hal_core/utilities/json_write_document.h
/home/runner/work/hal/hal/src/utilities/json_write_document.cpp