HAL: hal::NetLayoutJunctionWireIntersection Class Reference
hal::NetLayoutJunctionWireIntersection Class Reference
HAL Gui
#include <net_layout_junction.h>
Public Types
enum PlacementType { Normal, Verify, Endpoint }
Public Member Functions
NetLayoutJunctionWireIntersection (bool valid=false, int x_=0, int y_=0)
bool isValid () const
QGraphicsEllipseItem * graphicsFactory (u32 netId) const
Public Member Functions inherited from QPoint
QPoint ()
QPoint (int xpos, int ypos)
bool isNull () const const
int x () const const
int y () const const
void setX (int x)
void setY (int y)
int manhattanLength () const const
QPoint transposed () const const
int & rx ()
int & ry ()
QPoint & operator+= (const QPoint &point)
QPoint & operator-= (const QPoint &point)
QPoint & operator*= (float factor)
QPoint & operator*= (double factor)
QPoint & operator*= (int factor)
QPoint & operator/= (qreal divisor)
CGPoint toCGPoint () const const
bool operator== (const QPoint &p1, const QPoint &p2)
bool operator!= (const QPoint &p1, const QPoint &p2)
const QPoint operator+ (const QPoint &p1, const QPoint &p2)
const QPoint operator- (const QPoint &p1, const QPoint &p2)
const QPoint operator* (const QPoint &point, float factor)
const QPoint operator* (const QPoint &point, double factor)
const QPoint operator* (const QPoint &point, int factor)
const QPoint operator* (float factor, const QPoint &point)
const QPoint operator* (double factor, const QPoint &point)
const QPoint operator* (int factor, const QPoint &point)
const QPoint operator+ (const QPoint &point)
const QPoint operator- (const QPoint &point)
const QPoint operator/ (const QPoint &point, qreal divisor)
QDataStream & operator<< (QDataStream &stream, const QPoint &point)
QDataStream & operator>> (QDataStream &stream, QPoint &point)
Additional Inherited Members
Static Public Member Functions inherited from QPoint
int dotProduct (const QPoint &p1, const QPoint &p2)
Detailed Description
Definition at line 48 of file net_layout_junction.h.
Member Enumeration Documentation
PlacementType
enum hal::NetLayoutJunctionWireIntersection::PlacementType
Enumerator
Normal
Verify
Endpoint
Definition at line 54 of file net_layout_junction.h.
Constructor & Destructor Documentation
NetLayoutJunctionWireIntersection()
hal::NetLayoutJunctionWireIntersection::NetLayoutJunctionWireIntersection (bool valid = false, int x_ = 0, int y_ = 0) inline
Definition at line 52 of file net_layout_junction.h.
Member Function Documentation
graphicsFactory()
QGraphicsEllipseItem * hal::NetLayoutJunctionWireIntersection::graphicsFactory (u32 netId) const
Definition at line 688 of file net_layout_junction.cpp.
References colorFromId(), QAbstractGraphicsShapeItem::setBrush(), hal::NetLayoutJunctionRange::sSceneDelta, hal::NetLayoutJunctionRange::sSceneFirst, QPoint::x(), and QPoint::y().
isValid()
bool hal::NetLayoutJunctionWireIntersection::isValid () const inline
Definition at line 55 of file net_layout_junction.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/net_layout_junction.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/net_layout_junction.cpp