HAL: hal::ActionSetSelectionFocus Class Reference
hal::ActionSetSelectionFocus Class Reference
HAL Gui » User Actions
Set the selection and focus.
#include <action_set_selection_focus.h>
Public Member Functions
ActionSetSelectionFocus ()
QString tagname () const override
void writeToXml (QXmlStreamWriter &xmlOut) const override
void readFromXml (QXmlStreamReader &xmlIn) override
bool exec () override
void addToHash (QCryptographicHash &cryptoHash) const override
bool hasModifications () const
void setObject (const UserActionObject &obj) override
Public Member Functions inherited from hal::UserAction
virtual ~UserAction ()
virtual UserActionObject object () const
bool isWaitForReady () const
int compoundOrder () const
void setCompoundOrder (int cmpord)
qint64 timeStamp () const
QString cryptographicHash (int recordNo) const
UserAction * undoAction () const
QString debugDump () const
void setObjectLock (bool lock)
Friends
class SelectionRelay
Additional Inherited Members
Protected Member Functions inherited from hal::UserAction
UserAction ()
Static Protected Member Functions inherited from hal::UserAction
static QString setToText (const QSet< u32 > &set)
static QSet< u32 > setFromText (const QString &s)
Protected Attributes inherited from hal::UserAction
UserActionObject mObject
bool mWaitForReady
int mCompoundOrder
UserAction * mUndoAction
qint64 mTimeStamp
bool mObjectLock
Detailed Description
Set the selection and focus.
Sets the current selection and focus. The internal parameter are set directly by the SelectionRelay.
Undo Action: SetSelectionFocus
Definition at line 38 of file action_set_selection_focus.h.
Constructor & Destructor Documentation
ActionSetSelectionFocus()
hal::ActionSetSelectionFocus::ActionSetSelectionFocus () inline
Action constructor.
Definition at line 53 of file action_set_selection_focus.h.
Referenced by exec().
Member Function Documentation
addToHash()
void hal::ActionSetSelectionFocus::addToHash (QCryptographicHash & cryptoHash) const override virtual
Hook for derived classes to add parameter to cryptographic hash.
Parameters
cryptoHash - Additional hash data.
Reimplemented from hal::UserAction.
Definition at line 21 of file action_set_selection_focus.cpp.
References QCryptographicHash::addData(), and hal::UserAction::setToText().
exec()
bool hal::ActionSetSelectionFocus::exec () override virtual
Executes user interaction and returns true on success. Note: Each implementation of exec() must include a call to the exec() method of base class to store the UserAction object in history and to transfer its ownership.
Returns
True on success, False otherwise.
Reimplemented from hal::UserAction.
Definition at line 115 of file action_set_selection_focus.cpp.
References hal::SelectionRelay::actionSetSelected(), ActionSetSelectionFocus(), hal::UserAction::exec(), hal::SelectionRelay::focusId(), hal::SelectionRelay::focusType(), hal::UserActionObjectType::fromSelectionType(), hal::gSelectionRelay, hal::UserActionObject::id(), hal::UserAction::mObject, hal::UserAction::mUndoAction, hal::SelectionRelay::selectedGates(), hal::SelectionRelay::selectedModules(), hal::SelectionRelay::selectedNets(), hal::SelectionRelay::setFocusDirect(), hal::SelectionRelay::subfocus(), hal::SelectionRelay::subfocusIndex(), hal::UserActionObjectType::toSelectionType(), and hal::UserActionObject::type().
hasModifications()
bool hal::ActionSetSelectionFocus::hasModifications () const
Checks if the new selection/focus of this action differs from the current selection/focus.
Returns
true iff the selection/focus differs from the current one.
Definition at line 82 of file action_set_selection_focus.cpp.
References hal::SelectionRelay::focusId(), hal::SelectionRelay::focusType(), hal::UserActionObjectType::fromSelectionType(), hal::gSelectionRelay, hal::UserActionObject::id(), hal::UserAction::mObject, hal::SelectionRelay::selectedGates(), hal::SelectionRelay::selectedModules(), hal::SelectionRelay::selectedNets(), hal::SelectionRelay::subfocus(), hal::SelectionRelay::subfocusIndex(), and hal::UserActionObject::type().
readFromXml()
void hal::ActionSetSelectionFocus::readFromXml (QXmlStreamReader & xmlIn) override virtual
Reads user interaction as well as arguments from xml macro file.
Parameters
xmlIn - The xml reader.
Reimplemented from hal::UserAction.
Definition at line 54 of file action_set_selection_focus.cpp.
References QXmlStreamReader::attributes(), QStringRef::isEmpty(), QStringRef::isNull(), hal::SelectionRelay::Left, QXmlStreamReader::name(), QXmlStreamReader::readElementText(), QXmlStreamReader::readNextStartElement(), hal::SelectionRelay::Right, hal::UserAction::setFromText(), QStringRef::toInt(), and QXmlStreamAttributes::value().
setObject()
void hal::ActionSetSelectionFocus::setObject (const UserActionObject & obj) override virtual
Setter for object argument of interaction.
Parameters
obj - The object.
Reimplemented from hal::UserAction.
Definition at line 95 of file action_set_selection_focus.cpp.
References hal::UserActionObjectType::Gate, hal::UserActionObject::id(), QSet::insert(), hal::UserActionObjectType::Module, hal::UserActionObjectType::Net, hal::UserAction::setObject(), and hal::UserActionObject::type().
Referenced by hal::SelectionRelay::setFocus().
tagname()
QString hal::ActionSetSelectionFocus::tagname () const override virtual
The xml tagname for the action is purely virtual and needs to be implemented in derived class.
Returns
The tagname.
Implements hal::UserAction.
Definition at line 16 of file action_set_selection_focus.cpp.
References hal::ActionSetSelectionFocusFactory::sFactory, and hal::UserActionFactory::tagname().
writeToXml()
void hal::ActionSetSelectionFocus::writeToXml (QXmlStreamWriter & xmlOut) const override virtual
Persist user interaction in xml macro file.
Parameters
xmlOut - The xml writer.
Reimplemented from hal::UserAction.
Definition at line 33 of file action_set_selection_focus.cpp.
References QSet::isEmpty(), hal::SelectionRelay::Left, QString::number(), hal::SelectionRelay::Right, hal::UserAction::setToText(), QXmlStreamWriter::writeAttribute(), and QXmlStreamWriter::writeTextElement().
Friends And Related Function Documentation
SelectionRelay
friend class SelectionRelay friend
Definition at line 40 of file action_set_selection_focus.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/action_set_selection_focus.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/action_set_selection_focus.cpp