HAL: hal::BaseTreeItem Class Reference
hal::BaseTreeItem Class Reference abstract
(Future) Base class for all tree models related to the details widget.
#include <base_tree_item.h>
Public Member Functions
BaseTreeItem ()
BaseTreeItem (QList< QVariant > columnData)
virtual ~BaseTreeItem ()
virtual QVariant getData (int column) const =0
virtual void setData (QList< QVariant > data)=0
virtual void setDataAtColumn (int column, QVariant &data)=0
virtual void appendData (QVariant data)=0
virtual BaseTreeItem * getParent () const
virtual void setParent (BaseTreeItem *parent)
virtual BaseTreeItem * getChild (int row) const
virtual QList< BaseTreeItem * > getChildren () const
virtual void appendChild (BaseTreeItem *child)
virtual void insertChild (int index, BaseTreeItem *child)
virtual BaseTreeItem * removeChildAtPos (int row)
virtual bool removeChild (BaseTreeItem *child)
virtual int getChildCount () const
virtual int getColumnCount () const =0
virtual int getRowForChild (const BaseTreeItem *child) const
virtual int getOwnRow ()
Protected Attributes
BaseTreeItem * mParent
QList< BaseTreeItem * > mChildren
Detailed Description
(Future) Base class for all tree models related to the details widget.
This class functions as a generic data container for all tree models.
Definition at line 40 of file base_tree_item.h.
Constructor & Destructor Documentation
BaseTreeItem() [1/2]
hal::BaseTreeItem::BaseTreeItem ()
The constructor.
Definition at line 6 of file base_tree_item.cpp.
BaseTreeItem() [2/2]
hal::BaseTreeItem::BaseTreeItem (QList< QVariant > columnData)
Second constructor to immediately assign column data.
Parameters
columnData - The item's data.
~BaseTreeItem()
hal::BaseTreeItem::~BaseTreeItem () virtual
The destructor.
Definition at line 12 of file base_tree_item.cpp.
References mChildren.
Member Function Documentation
appendChild()
void hal::BaseTreeItem::appendChild (BaseTreeItem * child) virtual
Appends a child.
Parameters
child - The child to append.
Definition at line 39 of file base_tree_item.cpp.
References mChildren, and setParent().
Referenced by hal::ContextTreeModel::addContext(), hal::ContextTreeModel::addDirectory(), hal::ModuleItem::appendExistingChildIfAny(), hal::ModuleModel::createChildItem(), hal::ModuleModel::populateFromGatelist(), hal::ModuleModel::populateTree(), hal::BaseTreeModel::setContent(), hal::GatePinsTreeModel::setGate(), hal::PinModel::setGate(), hal::ModulePinsTreeModel::setModule(), and hal::ModuleModel::updateModuleParent().
appendData()
virtual void hal::BaseTreeItem::appendData (QVariant data) pure virtual
Appends a new column to the item.
Parameters
data - The data of the new column.
Implemented in hal::ModulePinsTreeItem, hal::GatePinsTreeItem, hal::PinItem, hal::ModuleItem, hal::ContextTreeItem, and hal::RootTreeItem.
getChild()
BaseTreeItem * hal::BaseTreeItem::getChild (int row) const virtual
Get the child of a specific row.
Parameters
row - The requested row.
Returns
The child if within bounds. Nullptr otherwise.
Definition at line 29 of file base_tree_item.cpp.
References mChildren.
Referenced by hal::BaseTreeModel::index().
getChildCount()
int hal::BaseTreeItem::getChildCount () const virtual
Get the number of children.
Returns
The number of children.
Definition at line 75 of file base_tree_item.cpp.
References mChildren.
Referenced by hal::ContextTreeModel::addContext(), hal::ContextTreeModel::addDirectory(), hal::BaseTreeModel::clear(), hal::ModuleModel::createChildItem(), hal::ActionDeleteObject::exec(), hal::ModulePinsTreeModel::getNetFromItem(), hal::BaseTreeModel::insertChildItem(), hal::ModuleModel::removeChildItem(), hal::BaseTreeModel::rowCount(), and hal::ModuleModel::updateModuleParent().
getChildren()
QList< BaseTreeItem * > hal::BaseTreeItem::getChildren () const virtual
Get the list of all children.
Returns
The list of children.
Definition at line 34 of file base_tree_item.cpp.
References mChildren.
Referenced by hal::ContextTreeModel::getChildContextsOf(), hal::ContextTreeModel::getChildDirectoriesOf(), hal::PinModel::getInputPins(), hal::PinModel::getOutputPins(), hal::PinModel::getPinGroups(), hal::GatePinTree::handleContextMenuRequested(), hal::ModulePinsTreeModel::handleModulePortsChanged(), hal::FlipFlopWizardPage::initializePage(), hal::PinsWizardPage::isComplete(), hal::ModuleModel::removeChildItem(), and hal::ContextTreeModel::removeDirectory().
getColumnCount()
virtual int hal::BaseTreeItem::getColumnCount () const pure virtual
Get the number of currently stored column data.
Returns
The column count.
Implemented in hal::ModulePinsTreeItem, hal::GatePinsTreeItem, hal::PinItem, hal::ModuleItem, hal::ContextTreeItem, and hal::RootTreeItem.
getData()
virtual QVariant hal::BaseTreeItem::getData (int column) const pure virtual
Get the data of a specific column (most in the form of a string).
Parameters
column - The requested column.
Returns
The data if within the column count. Empty QVariant otherwise.
Implemented in hal::ModulePinsTreeItem, hal::GatePinsTreeItem, hal::PinItem, hal::ModuleItem, hal::ContextTreeItem, and hal::RootTreeItem.
Referenced by hal::BaseTreeModel::data().
getOwnRow()
int hal::BaseTreeItem::getOwnRow () virtual
Convenience method to get the row of this item within the parent's list. If the item has no parent, -1 is returned.
Returns
The row of this item if it has a parent, -1 otherwise.
Definition at line 94 of file base_tree_item.cpp.
References getRowForChild(), and mParent.
Referenced by hal::ModulePinsTreeModel::canDropMimeData(), hal::ModuleModel::removeChildItem(), and hal::ModuleModel::updateModuleParent().
getParent()
BaseTreeItem * hal::BaseTreeItem::getParent () const virtual
Get the item's parent.
Returns
The parent.
Definition at line 19 of file base_tree_item.cpp.
References mParent.
Referenced by hal::ContextProxyModel::canDropMimeData(), hal::ModulePinsTreeModel::dropMimeData(), hal::ActionMoveItem::exec(), hal::BaseTreeModel::getIndexFromItem(), hal::GraphContextManager::getParentId(), hal::GraphContextManager::handleSaveTriggered(), hal::ContextProxyModel::mimeData(), hal::ModuleModel::mimeData(), hal::ModuleModel::moduleAssignGate(), hal::GuiApiClasses::View::moveDirectory(), hal::ContextTreeModel::moveItem(), hal::GuiApiClasses::View::moveView(), hal::BaseTreeModel::parent(), hal::ContextTreeModel::removeContext(), hal::ContextTreeModel::removeDirectory(), hal::ModuleModel::removeGate(), hal::ModuleModel::removeModule(), hal::ModuleModel::removeNet(), hal::ContextTreeItem::row(), hal::PinItem::row(), hal::ContextTreeModel::setCurrentDirectory(), hal::ModuleModel::updateModuleParent(), and hal::ModuleModel::updateNetParent().
getRowForChild()
int hal::BaseTreeItem::getRowForChild (const BaseTreeItem * child) const virtual
Convenience method to get the row for a given item. If the item is not a child of this item, -1 is returned.
Parameters
child - The child for which the row is requested.
Returns
The row if the item is a child, -1 otherwise.
Definition at line 80 of file base_tree_item.cpp.
References mChildren.
Referenced by hal::BaseTreeModel::getIndexFromItem(), getOwnRow(), hal::ContextTreeItem::row(), and hal::PinItem::row().
insertChild()
void hal::BaseTreeItem::insertChild (int index, BaseTreeItem * child) virtual
Inserts a child at the given index. If the index exceeds the amount of children, the new child is appended.
Parameters
index - The position at which to insert.
child - The child to insert.
Definition at line 45 of file base_tree_item.cpp.
References mChildren, and setParent().
Referenced by hal::BaseTreeModel::insertChildItem().
removeChild()
bool hal::BaseTreeItem::removeChild (BaseTreeItem * child) virtual
Removes the given item and returns True if removing was successful or False if the given item was no child.
Parameters
child - The child to remove.
Returns
True on success, False otherwise.
Definition at line 63 of file base_tree_item.cpp.
References mChildren.
Referenced by hal::PinModel::handleDeleteItem(), hal::ContextTreeModel::moveItem(), hal::ModuleModel::removeChildItem(), and hal::ModuleModel::updateModuleParent().
removeChildAtPos()
BaseTreeItem * hal::BaseTreeItem::removeChildAtPos (int row) virtual
Removes the child at the given row and returns it.
Parameters
row - The row from which to remove the child.
Returns
The removed child. Nullptr if row was out of bounds.
Definition at line 51 of file base_tree_item.cpp.
References mChildren.
Referenced by hal::BaseTreeModel::clear().
setData()
virtual void hal::BaseTreeItem::setData (QList< QVariant > data) pure virtual
Sets the data for all columns.
Parameters
data - Each entry in the list represents one column.
Implemented in hal::ModulePinsTreeItem, hal::GatePinsTreeItem, hal::PinItem, hal::ModuleItem, hal::ContextTreeItem, and hal::RootTreeItem.
setDataAtColumn()
virtual void hal::BaseTreeItem::setDataAtColumn (int column, QVariant & data) pure virtual
Sets the data for a specified column. The index must be within already existing boundaries (for example, add dummy data beforehand).
Parameters
index - The column to set the new data.
data - The new column data.
Implemented in hal::ModulePinsTreeItem, hal::GatePinsTreeItem, hal::PinItem, hal::ModuleItem, hal::ContextTreeItem, and hal::RootTreeItem.
setParent()
void hal::BaseTreeItem::setParent (BaseTreeItem * parent) virtual
Sets the item's parent.
Parameters
parent - The parent.
Definition at line 24 of file base_tree_item.cpp.
References mParent.
Referenced by appendChild(), hal::ModuleItem::appendExistingChildIfAny(), and insertChild().
Member Data Documentation
mChildren
QList<BaseTreeItem*> hal::BaseTreeItem::mChildren protected
Definition at line 194 of file base_tree_item.h.
Referenced by appendChild(), getChild(), getChildCount(), getChildren(), getRowForChild(), insertChild(), removeChild(), removeChildAtPos(), and ~BaseTreeItem().
mParent
BaseTreeItem* hal::BaseTreeItem::mParent protected
Definition at line 193 of file base_tree_item.h.
Referenced by getOwnRow(), getParent(), hal::ModuleItem::isToplevelItem(), and setParent().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/basic_tree_model/base_tree_item.h
/home/runner/work/hal/hal/plugins/gui/src/basic_tree_model/base_tree_item.cpp