HAL: hal::ChannelItem Class Reference
hal::ChannelItem Class Reference
HAL Gui » Logging System
This class represents a channel in the channel model. It primarily holds the channel name and its entries.
#include <channel_item.h>
Public Member Functions
ChannelItem (QString name)
const QString name () const
const QList< ChannelEntry * > * getEntries () const
QReadWriteLock * getLock ()
void appendEntry (ChannelEntry *entry)
Detailed Description
This class represents a channel in the channel model. It primarily holds the channel name and its entries.
Definition at line 66 of file channel_item.h.
Constructor & Destructor Documentation
ChannelItem()
hal::ChannelItem::ChannelItem (QString name)
The constructor
Parameters
name - The name of the channel.
Definition at line 7 of file channel_item.cpp.
Member Function Documentation
appendEntry()
void hal::ChannelItem::appendEntry (ChannelEntry * entry)
Append a given entry to the end of the message list. If the list's size exceeds the maximum number of allowed entries, the first entry in the list is removed.
Parameters
entry - The entry to append to the list.
Definition at line 27 of file channel_item.cpp.
References MAX_CHANNEL_ENTIRES.
Referenced by hal::ChannelModel::handleLogmanagerCallback().
getEntries()
const QList< ChannelEntry * > * hal::ChannelItem::getEntries () const
Get the List of all buffered messages.
Returns
The List that contains the channel entries.
Definition at line 17 of file channel_item.cpp.
Referenced by hal::LoggerWidget::handleCurrentFilterChanged().
getLock()
QReadWriteLock * hal::ChannelItem::getLock ()
Get the lock of the channel.
Returns
The channel's lock.
Definition at line 22 of file channel_item.cpp.
Referenced by hal::LoggerWidget::handleCurrentFilterChanged().
name()
const QString hal::ChannelItem::name () const
Get the channel's name.
Returns
The name of the channel.
Definition at line 12 of file channel_item.cpp.
Referenced by hal::ChannelModel::data(), and hal::LoggerWidget::handleCurrentFilterChanged().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/channel_manager/channel_item.h
/home/runner/work/hal/hal/plugins/gui/src/channel_manager/channel_item.cpp