HAL: hal::ContextTableModel Class Reference
hal::ContextTableModel Class Reference
HAL Gui » Utility Widgets » Context Manager Widget
Base model for the ContextManagerWidget to manage GraphContexts.
#include <context_table_model.h>
Public Member Functions
ContextTableModel (QObject *parent=nullptr)
void addContext (GraphContext *context)
void removeContext (GraphContext *context)
GraphContext * getContext (const QModelIndex &index) const
QModelIndex getIndex (GraphContext *context) const
void beginInsertContext (GraphContext *context)
void endInsertContext ()
void beginRemoveContext (GraphContext *context)
void endRemoveContext ()
void clear ()
const QVector< GraphContext * > & list () const
Overwritten model functions
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &inddex, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
Public Member Functions inherited from QAbstractTableModel
QAbstractTableModel (QObject *parent)
virtual ~QAbstractTableModel ()
virtual QModelIndex index (int row, int column, const QModelIndex &parent) const const override
virtual QModelIndex sibling (int row, int column, const QModelIndex &idx) const const override
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
virtual Qt::ItemFlags flags (const QModelIndex &index) const const override
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
virtual QModelIndex parent (const QModelIndex &index) const const=0
virtual bool hasChildren (const QModelIndex &parent) const const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role)
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const const
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
virtual QStringList mimeTypes () const const
virtual QMimeData * mimeData (const QModelIndexList &indexes) const const
virtual bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const const
virtual Qt::DropActions supportedDropActions () const const
virtual Qt::DropActions supportedDragActions () const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool insertRows (int row, int count, const QModelIndex &parent)
virtual bool insertColumns (int column, int count, const QModelIndex &parent)
virtual bool removeRows (int row, int count, const QModelIndex &parent)
virtual bool removeColumns (int column, int count, const QModelIndex &parent)
virtual bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual void fetchMore (const QModelIndex &parent)
virtual bool canFetchMore (const QModelIndex &parent) const const
virtual void sort (int column, Qt::SortOrder order)
virtual QModelIndex buddy (const QModelIndex &index) const const
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const
virtual QSize span (const QModelIndex &index) const const
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual bool submit ()
virtual void revert ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Base model for the ContextManagerWidget to manage GraphContexts.
The ContextTableModel implements a standard table model to manage the GraphContexts that are created/deleted/modified by the user. It provides the neccessary interface for the ContextManagerWidget to store and display the data. For specific information on how to implement a table model, refer to qt's QAbstractTableModel class and its examples.
Definition at line 44 of file context_table_model.h.
Constructor & Destructor Documentation
ContextTableModel()
hal::ContextTableModel::ContextTableModel (QObject * parent = nullptr)
The constructor.
Parameters
parent - The widget's parent.
Definition at line 7 of file context_table_model.cpp.
Member Function Documentation
addContext()
void hal::ContextTableModel::addContext (GraphContext * context)
Adds a given GraphContext to the model.
Parameters
context - The context to add.
Definition at line 115 of file context_table_model.cpp.
References QObject::connect(), and hal::GraphContext::dataChanged().
Referenced by hal::GraphContextManager::createNewContext(), and hal::GraphContextManager::restoreFromFile().
beginInsertContext()
void hal::ContextTableModel::beginInsertContext (GraphContext * context)
Begins a row insert operation. Parameter is not used.
Parameters
context - Not used.
Definition at line 83 of file context_table_model.cpp.
References QAbstractItemModel::beginInsertRows().
Referenced by hal::GraphContextManager::createNewContext(), and hal::GraphContextManager::restoreFromFile().
beginRemoveContext()
void hal::ContextTableModel::beginRemoveContext (GraphContext * context)
Begins a remove row operation. The given context is removed.
Parameters
context - The context to remove.
Definition at line 95 of file context_table_model.cpp.
References QAbstractItemModel::beginRemoveRows().
Referenced by hal::GraphContextManager::deleteGraphContext().
clear()
void hal::ContextTableModel::clear ()
Resets the model (removes all GraphContexts).
Definition at line 106 of file context_table_model.cpp.
References QAbstractItemModel::beginResetModel(), and QAbstractItemModel::endResetModel().
Referenced by hal::GraphContextManager::clear().
columnCount()
int hal::ContextTableModel::columnCount (const QModelIndex & parent = QModelIndex()) const override virtual
Implements QAbstractItemModel.
Definition at line 18 of file context_table_model.cpp.
References QObject::parent().
data()
QVariant hal::ContextTableModel::data (const QModelIndex & inddex, int role = Qt::DisplayRole) const override virtual
Implements QAbstractItemModel.
Definition at line 25 of file context_table_model.cpp.
References QModelIndex::column(), Qt::DisplayRole, hal::GraphContext::getNameWithDirtyState(), hal::GraphContext::getTimestamp(), QAbstractTableModel::index(), QModelIndex::isValid(), QModelIndex::row(), Qt::SystemLocaleShortDate, QDateTime::toString(), and Qt::UserRole.
endInsertContext()
void hal::ContextTableModel::endInsertContext ()
Ends a row insert operation.
Definition at line 90 of file context_table_model.cpp.
References QAbstractItemModel::endInsertRows().
Referenced by hal::GraphContextManager::createNewContext(), and hal::GraphContextManager::restoreFromFile().
endRemoveContext()
void hal::ContextTableModel::endRemoveContext ()
Ends a remove row operation.
Definition at line 101 of file context_table_model.cpp.
References QAbstractItemModel::endRemoveRows().
Referenced by hal::GraphContextManager::deleteGraphContext().
getContext()
GraphContext * hal::ContextTableModel::getContext (const QModelIndex & index) const
Get the GraphContext from a given index.
Parameters
index - The index of the requested GraphContext.
Returns
The requested GraphContext.
Definition at line 142 of file context_table_model.cpp.
References QAbstractTableModel::index(), and QModelIndex::row().
Referenced by hal::ContextManagerWidget::getCurrentContext().
getIndex()
QModelIndex hal::ContextTableModel::getIndex (GraphContext * context) const
Converts a given GraphContext into its corresponding index.
Parameters
context - The context to convert.
Returns
The resulting index.
Definition at line 147 of file context_table_model.cpp.
References QAbstractItemModel::createIndex().
Referenced by hal::ContextManagerWidget::selectViewContext().
headerData()
QVariant hal::ContextTableModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override virtual
Reimplemented from QAbstractItemModel.
Definition at line 61 of file context_table_model.cpp.
References Qt::DisplayRole, Qt::Horizontal, and Qt::Vertical.
list()
const QVector<GraphContext*>& hal::ContextTableModel::list () const inline
Get all GraphContexts of the model.
Returns
A vector of all GraphContexts.
Definition at line 129 of file context_table_model.h.
Referenced by hal::GraphContextManager::clear(), hal::GraphContextManager::contextWithNameExists(), hal::GraphContextManager::getCleanContext(), hal::GraphContextManager::getContextByExclusiveModuleId(), hal::GraphContextManager::getContextById(), hal::GraphContextManager::getContexts(), hal::GraphContextManager::handleGateNameChanged(), hal::GraphContextManager::handleGateRemoved(), hal::GraphContextManager::handleMarkedGlobalInput(), hal::GraphContextManager::handleMarkedGlobalOutput(), hal::GraphContextManager::handleModuleColorChanged(), hal::GraphContextManager::handleModuleCreated(), hal::GraphContextManager::handleModuleGateAssigned(), hal::GraphContextManager::handleModuleGateRemoved(), hal::GraphContextManager::handleModuleNameChanged(), hal::GraphContextManager::handleModulePortsChanged(), hal::GraphContextManager::handleModuleRemoved(), hal::GraphContextManager::handleModuleSubmoduleAdded(), hal::GraphContextManager::handleModuleSubmoduleRemoved(), hal::GraphContextManager::handleModuleTypeChanged(), hal::GraphContextManager::handleNetDestinationAdded(), hal::GraphContextManager::handleNetDestinationRemoved(), hal::GraphContextManager::handleNetNameChanged(), hal::GraphContextManager::handleNetRemoved(), hal::GraphContextManager::handleNetSourceAdded(), hal::GraphContextManager::handleNetSourceRemoved(), hal::GraphContextManager::handleSaveTriggered(), hal::GraphContextManager::handleUnmarkedGlobalInput(), and hal::GraphContextManager::handleUnmarkedGlobalOutput().
removeContext()
void hal::ContextTableModel::removeContext (GraphContext * context)
Removes a given GraphContext from the model.
Parameters
context - The context to remove.
Definition at line 121 of file context_table_model.cpp.
Referenced by hal::GraphContextManager::deleteGraphContext().
rowCount()
int hal::ContextTableModel::rowCount (const QModelIndex & parent = QModelIndex()) const override virtual
Implements QAbstractItemModel.
Definition at line 11 of file context_table_model.cpp.
References QObject::parent().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/context_manager_widget/models/context_table_model.h
/home/runner/work/hal/hal/plugins/gui/src/context_manager_widget/models/context_table_model.cpp