HAL: hal::ContentAnchor Class Reference
hal::ContentAnchor Class Reference abstract
HAL Gui » Docking System
An abstract class that provides the interface for specific anchors (see SplitterAnchor or TabWidget).
#include <content_anchor.h>
Public Member Functions
virtual void add (ContentWidget *widget, int index)=0
virtual void remove (ContentWidget *widget)=0
virtual ContentFrame * detach (ContentWidget *widget)=0
virtual void reattach (ContentWidget *widget)=0
virtual void open (ContentWidget *widget)=0
virtual void close (ContentWidget *widget)=0
virtual ~ContentAnchor ()
virtual int count () const
void saveState () const
Protected Attributes
DockBar * mDockBar
ContentLayout::Position mAnchorPosition
Detailed Description
An abstract class that provides the interface for specific anchors (see SplitterAnchor or TabWidget).
Definition at line 53 of file content_anchor.h.
Constructor & Destructor Documentation
~ContentAnchor()
virtual hal::ContentAnchor::~ContentAnchor () inline virtual
Destructor
Definition at line 108 of file content_anchor.h.
Member Function Documentation
add()
virtual void hal::ContentAnchor::add (ContentWidget * widget, int index) pure virtual
Adds a given ContentWidget to the anchor.
Parameters
widget - The widget to add.
index - The position.
Implemented in hal::SplitterAnchor, and hal::TabWidget.
Referenced by hal::DockBar::dropEvent().
close()
virtual void hal::ContentAnchor::close (ContentWidget * widget) pure virtual
Closes a given widget.
Parameters
widget - The widget to close.
Implemented in hal::SplitterAnchor, and hal::TabWidget.
Referenced by hal::ContentWidget::close().
count()
int hal::ContentAnchor::count () const virtual
Returns the number of widgets / buttons as of mDockBar->count()
Definition at line 8 of file content_anchor.cpp.
References hal::DockBar::count(), and mDockBar.
Referenced by hal::ContentLayoutArea::addContent().
detach()
virtual ContentFrame* hal::ContentAnchor::detach (ContentWidget * widget) pure virtual
Detaches a given widget from the anchor.
Parameters
widget - The widget to detach.
Returns
the enclosing frame of the detached widget
Implemented in hal::SplitterAnchor, and hal::TabWidget.
Referenced by hal::ContentWidget::detach().
open()
virtual void hal::ContentAnchor::open (ContentWidget * widget) pure virtual
Displays a given widget in the achor's corresponding area.
Parameters
widget - The widget to open.
Implemented in hal::SplitterAnchor, and hal::TabWidget.
Referenced by hal::ContentWidget::open().
reattach()
virtual void hal::ContentAnchor::reattach (ContentWidget * widget) pure virtual
Reattaches a given widget to the anchor.
Parameters
widget - The widget to reattach.
Implemented in hal::SplitterAnchor, and hal::TabWidget.
Referenced by hal::ContentWidget::reattach().
remove()
virtual void hal::ContentAnchor::remove (ContentWidget * widget) pure virtual
Removes a given widget from the anchor.
Parameters
widget - The widget to remove.
Implemented in hal::SplitterAnchor, and hal::TabWidget.
Referenced by hal::ContentWidget::remove().
saveState()
void hal::ContentAnchor::saveState () const
Save state of widgets using anchor tag
Definition at line 13 of file content_anchor.cpp.
References QList::append(), hal::DockBar::count(), hal::SettingsManager::instance(), mAnchorPosition, mDockBar, hal::DockBar::widgetAt(), and hal::SettingsManager::widgetsSaveGeometry().
Referenced by hal::ContentLayoutArea::saveState().
Member Data Documentation
mAnchorPosition
ContentLayout::Position hal::ContentAnchor::mAnchorPosition protected
Definition at line 58 of file content_anchor.h.
Referenced by saveState(), hal::SplitterAnchor::SplitterAnchor(), and hal::TabWidget::TabWidget().
mDockBar
DockBar* hal::ContentAnchor::mDockBar protected
Definition at line 57 of file content_anchor.h.
Referenced by hal::TabWidget::add(), hal::SplitterAnchor::add(), hal::SplitterAnchor::clear(), hal::TabWidget::clear(), hal::TabWidget::close(), hal::SplitterAnchor::close(), count(), hal::TabWidget::detach(), hal::SplitterAnchor::detach(), hal::TabWidget::handleDragEnd(), hal::TabWidget::handleNoCurrentWidget(), hal::TabWidget::open(), hal::SplitterAnchor::open(), hal::TabWidget::reattach(), hal::SplitterAnchor::reattach(), hal::TabWidget::remove(), hal::SplitterAnchor::remove(), saveState(), hal::SplitterAnchor::SplitterAnchor(), and hal::TabWidget::TabWidget().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/content_anchor/content_anchor.h
/home/runner/work/hal/hal/plugins/gui/src/content_anchor/content_anchor.cpp