HAL: hal::ModuleSelectExclude Class Reference
hal::ModuleSelectExclude Class Reference
The ModuleSelectExclude class is used to determine which modules can't be selected.
#include <module_select_model.h>
Public Member Functions
ModuleSelectExclude ()
bool isAccepted (u32 modId) const
void append (QSet< u32 > mod_ids)
QString selectionToString () const
selectionToString function is used to generate selection as text for message box
QSet< u32 > modules () const
QSet< u32 > gates () const
Detailed Description
The ModuleSelectExclude class is used to determine which modules can't be selected.
Member variables are the gates and modules currently selected and a set of non-selectable modules. The 'blacklisted' modules are identical with a selected one, or a (grand?-)child, or a direct parent.
Definition at line 71 of file module_select_model.h.
Constructor & Destructor Documentation
ModuleSelectExclude()
hal::ModuleSelectExclude::ModuleSelectExclude ()
Definition at line 205 of file module_select_model.cpp.
References hal::gSelectionRelay, hal::SelectionRelay::selectedGatesList(), and hal::SelectionRelay::selectedModulesList().
Member Function Documentation
append()
void hal::ModuleSelectExclude::append (QSet< u32 > mod_ids) inline
Definition at line 79 of file module_select_model.h.
Referenced by hal::ModuleSelectModel::excludeModulesById().
gates()
QSet<u32> hal::ModuleSelectExclude::gates () const inline
Definition at line 86 of file module_select_model.h.
References QSet::fromList().
Referenced by hal::AddToModuleReceiver::handleModulesPicked().
isAccepted()
bool hal::ModuleSelectExclude::isAccepted (u32 modId) const inline
Definition at line 77 of file module_select_model.h.
References QSet::contains().
Referenced by hal::ModuleSelectModel::appendEntries(), hal::ModuleSelectPicker::handleSelectionChanged(), and hal::ModuleDialog::handleTableSelection().
modules()
QSet<u32> hal::ModuleSelectExclude::modules () const inline
Definition at line 85 of file module_select_model.h.
References QSet::fromList().
Referenced by hal::AddToModuleReceiver::handleModulesPicked().
selectionToString()
QString hal::ModuleSelectExclude::selectionToString () const
selectionToString function is used to generate selection as text for message box
Returns
selected items as formatted string
Definition at line 211 of file module_select_model.cpp.
References QString::arg(), test_plugin::g, hal::Netlist::get_gate_by_id(), hal::Module::get_id(), hal::Netlist::get_module_by_id(), hal::Module::get_name(), hal::gNetlist, QString::isEmpty(), QList::isEmpty(), and QList::size().
Referenced by hal::AddToModuleReceiver::handleModulesPicked().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/module_dialog/module_select_model.h
/home/runner/work/hal/hal/plugins/gui/src/module_dialog/module_select_model.cpp