HAL: hal::Node Class Reference
hal::Node Class Reference
HAL Gui
The Node class object represents a module or a gate.
#include <gui_def.h>
Public Types
enum NodeType { None, Module, Gate }
Public Member Functions
Node (u32 i=0, NodeType t=None)
NodeType type () const
type getter for type information
u32 id () const
id getter for ID information
bool isNull () const
isNull test for null-Node object typically returned from functions
bool isGate () const
isGate test whether node is a gate
bool isModule () const
isModule test wheter node is a module
bool operator< (const Node &rhs) const
operator < to provide an ordering scheme for maps and ordered lists
bool operator== (const Node &rhs) const
operator == to test whether two nodes are equal
bool operator!= (const Node &rhs) const
operator != to test whether two nodes are not equal
Detailed Description
The Node class object represents a module or a gate.
The Node class has two private members, the Id and the type which is of type Module or Gate. Node objects can be compared, used as Hash keys or returned by functions. For the latter case there is a null-Node object (type==None) to be returned if the function failed to find an appropriate node.
Definition at line 57 of file gui_def.h.
Member Enumeration Documentation
NodeType
enum hal::Node::NodeType
Enumerator
None
Module
Gate
Definition at line 60 of file gui_def.h.
Constructor & Destructor Documentation
Node()
hal::Node::Node (u32 i = 0, NodeType t = None) inline
Definition at line 62 of file gui_def.h.
Member Function Documentation
id()
u32 hal::Node::id () const inline
id getter for ID information
Returns
ID as unsigned integer
Definition at line 74 of file gui_def.h.
Referenced by hal::CoordinateFromData::fromNode(), hal::WaitToBeSeatedEntry::getId(), hal::NodeBox::id(), hal::WaitToBeSeatedEntry::isModule(), hal::qHash(), and hal::ActionAddItemsToObject::writeToXml().
isGate()
bool hal::Node::isGate () const inline
isGate test whether node is a gate
Returns
true if node is a gate
Definition at line 86 of file gui_def.h.
References Gate.
Referenced by hal::NodeBoxes::addBox().
isModule()
bool hal::Node::isModule () const inline
isModule test wheter node is a module
Returns
true if node is a module
Definition at line 92 of file gui_def.h.
References Module.
Referenced by hal::NodeBoxes::addBox(), and hal::WaitToBeSeatedEntry::isModule().
isNull()
bool hal::Node::isNull () const inline
isNull test for null-Node object typically returned from functions
Returns
true if node is null
Definition at line 80 of file gui_def.h.
References None.
operator!=()
bool hal::Node::operator!= (const Node & rhs) const inline
operator != to test whether two nodes are not equal
Parameters
rhs the other Node to be compared with
Returns
true if nodes have either different type or different ID
Definition at line 123 of file gui_def.h.
operator<()
bool hal::Node::operator< (const Node & rhs) const inline
operator < to provide an ordering scheme for maps and ordered lists
Parameters
rhs the other Node to be compared with
Returns
true if node is 'smaller' according to test
Definition at line 99 of file gui_def.h.
operator==()
bool hal::Node::operator== (const Node & rhs) const inline
operator == to test whether two nodes are equal
Parameters
rhs the other Node to be compared with
Returns
true if nodes are of same type and have same ID
Definition at line 113 of file gui_def.h.
type()
NodeType hal::Node::type () const inline
type getter for type information
Returns
Module or Gate or None for null-Node
Definition at line 68 of file gui_def.h.
Referenced by hal::CoordinateFromData::fromNode(), hal::qHash(), hal::NodeBox::type(), and hal::ActionAddItemsToObject::writeToXml().
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/plugins/gui/include/gui/gui_def.h