HAL: hal::CoordinateFromDataMap Class Reference
hal::CoordinateFromDataMap Class Reference
HAL Gui » Graph Widget » Layouters
Utility class that stores the nodes that contained existing x and y coordinates.
#include <coordinate_from_data.h>
Public Member Functions
CoordinateFromDataMap (const QSet< u32 > &modules, const QSet< u32 > &gates)
bool good () const
void simplify ()
void clear ()
bool isPlacementComplete () const
const QSet< u32 > & placedGates () const
const QSet< u32 > & placedModules () const
Public Member Functions inherited from QHash< hal::Node, CoordinateFromData >
QHash ()
QHash (std::initializer_list< std::pair< Key, T > > list)
QHash (const QHash< K, V > &other)
QHash (QHash< K, V > &&other)
QHash (InputIterator begin, InputIterator end)
~QHash ()
QHash< K, V > & operator= (const QHash< K, V > &other)
QHash< K, V > & operator= (QHash< K, V > &&other)
void swap (QHash< K, V > &other)
bool operator== (const QHash< K, V > &other) const const
bool operator!= (const QHash< K, V > &other) const const
int size () const const
bool isEmpty () const const
int capacity () const const
void reserve (int size)
void squeeze ()
void clear ()
int remove (const Key &key)
T take (const Key &key)
bool contains (const Key &key) const const
const Key key (const T &value) const const
const Key key (const T &value, const Key &defaultKey) const const
const T value (const Key &key) const const
const T value (const Key &key, const T &defaultValue) const const
T & operator[] (const Key &key)
const T operator[] (const Key &key) const const
QList< Key > keys () const const
QList< Key > keys (const T &value) const const
QList< T > values () const const
QList< T > values (const Key &key) const const
QList< Key > uniqueKeys () const const
int count (const Key &key) const const
int count () const const
QHash::iterator begin ()
QHash::const_iterator begin () const const
QHash::const_iterator cbegin () const const
QHash::const_iterator constBegin () const const
QHash::iterator end ()
QHash::const_iterator end () const const
QHash::const_iterator cend () const const
QHash::const_iterator constEnd () const const
QHash::key_iterator keyBegin () const const
QHash::key_iterator keyEnd () const const
QHash::key_value_iterator keyValueBegin ()
QHash::const_key_value_iterator keyValueBegin () const const
QHash::key_value_iterator keyValueEnd ()
QHash::const_key_value_iterator keyValueEnd () const const
QHash::const_key_value_iterator constKeyValueBegin () const const
QHash::const_key_value_iterator constKeyValueEnd () const const
QPair< QHash::iterator, QHash::iterator > equal_range (const Key &key)
QPair< QHash::const_iterator, QHash::const_iterator > equal_range (const Key &key) const const
QHash::iterator erase (QHash::iterator pos)
QHash::iterator erase (QHash::const_iterator pos)
QHash::iterator find (const Key &key)
QHash::const_iterator find (const Key &key) const const
QHash::const_iterator constFind (const Key &key) const const
QHash::iterator insert (const Key &key, const T &value)
void insert (const QHash< K, V > &other)
QHash::iterator insertMulti (const Key &key, const T &value)
QHash< K, V > & unite (const QHash< K, V > &other)
bool empty () const const
uint qHash (const QUrl &url, uint seed)
uint qHash (const QDateTime &key, uint seed)
uint qHash (const QDate &key, uint seed)
uint qHash (const QTime &key, uint seed)
uint qHash (const QPair< T1, T2 > &key, uint seed)
uint qHash (const std::pair< T1, T2 > &key, uint seed)
uint qHash (char key, uint seed)
uint qHash (uchar key, uint seed)
uint qHash (signed char key, uint seed)
uint qHash (ushort key, uint seed)
uint qHash (short key, uint seed)
uint qHash (uint key, uint seed)
uint qHash (int key, uint seed)
uint qHash (ulong key, uint seed)
uint qHash (long key, uint seed)
uint qHash (quint64 key, uint seed)
uint qHash (qint64 key, uint seed)
uint qHash (float key, uint seed)
uint qHash (double key, uint seed)
uint qHash (long double key, uint seed)
uint qHash (const QChar key, uint seed)
uint qHash (const QByteArray &key, uint seed)
uint qHash (const QBitArray &key, uint seed)
uint qHash (const QString &key, uint seed)
uint qHash (const QStringRef &key, uint seed)
uint qHash (QLatin1String key, uint seed)
uint qHash (const T *key, uint seed)
uint qHash (const QHash< Key, T > &key, uint seed)
uint qHash (const QSet< T > &key, uint seed)
uint qHash (const QVersionNumber &key, uint seed)
int qGlobalQHashSeed ()
void qSetGlobalQHashSeed (int newSeed)
uint qHashRange (InputIterator first, InputIterator last, uint seed)
uint qHashRangeCommutative (InputIterator first, InputIterator last, uint seed)
uint qHashBits (const void *p, size_t len, uint seed)
QDataStream & operator<< (QDataStream &out, const QHash< Key, T > &hash)
QDataStream & operator>> (QDataStream &in, QHash< Key, T > &hash)
Additional Inherited Members
Public Attributes inherited from QHash< hal::Node, CoordinateFromData >
typedef const_key_value_iterator
typedef key_value_iterator
typedef Iterator
typedef ConstIterator
typedef mapped_type
typedef key_type
typedef difference_type
typedef size_type
Detailed Description
Utility class that stores the nodes that contained existing x and y coordinates.
Definition at line 62 of file coordinate_from_data.h.
Constructor & Destructor Documentation
CoordinateFromDataMap()
hal::CoordinateFromDataMap::CoordinateFromDataMap (const QSet< u32 > & modules, const QSet< u32 > & gates)
Definition at line 65 of file coordinate_from_data.cpp.
References hal::CoordinateFromData::fromNode(), hal::Node::Gate, QSet::insert(), hal::CoordinateFromData::isUndefined(), and hal::Node::Module.
Member Function Documentation
clear()
void hal::CoordinateFromDataMap::clear ()
Definition at line 103 of file coordinate_from_data.cpp.
References QHash::clear(), and QSet::clear().
good()
bool hal::CoordinateFromDataMap::good () const
Definition at line 144 of file coordinate_from_data.cpp.
References QSet::isEmpty(), and log_info.
isPlacementComplete()
bool hal::CoordinateFromDataMap::isPlacementComplete () const
Definition at line 113 of file coordinate_from_data.cpp.
placedGates()
const QSet<u32>& hal::CoordinateFromDataMap::placedGates () const inline
Definition at line 70 of file coordinate_from_data.h.
placedModules()
const QSet<u32>& hal::CoordinateFromDataMap::placedModules () const inline
Definition at line 71 of file coordinate_from_data.h.
simplify()
void hal::CoordinateFromDataMap::simplify ()
Definition at line 118 of file coordinate_from_data.cpp.
References QMap::begin(), QHash< hal::Node, CoordinateFromData >::begin(), QMap::end(), QHash< hal::Node, CoordinateFromData >::end(), QMap::value(), QHash< hal::Node, CoordinateFromData >::values(), QPoint::x(), and QPoint::y().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/coordinate_from_data.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/coordinate_from_data.cpp