HAL: hal::PythonConsole Class Reference
hal::PythonConsole Class Reference
HAL Gui » Python » Python Console
An interactable python console.
#include <python_console.h>
Public Types
enum PromptType { Standard, Compound, Input }
Public Types inherited from QTextEdit
enum LineWrapMode
enum AutoFormattingFlag
Public Types inherited from QAbstractScrollArea
enum SizeAdjustPolicy
Public Types inherited from QFrame
enum Shape
enum Shadow
enum StyleMask
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Public Slots
void handleThreadFinished ()
Signals
void inputReceived (QString input)
Public Member Functions
PythonConsole (QWidget *parent=nullptr)
~PythonConsole ()
virtual void handleStdout (const QString &output) override
virtual void handleError (const QString &output) override
virtual void clear () override
void displayPrompt ()
void interpretCommand ()
QString getCurrentCommand ()
void replaceCurrentCommand (const QString &new_command)
void appendToCurrentCommand (const QString &new_command)
bool selectionEditable ()
void handleUpKeyPressed ()
void handleDownKeyPressed ()
void handleTabKeyPressed ()
void insertAtEnd (const QString &text, QColor textColor)
void setInputMode (bool state)
PythonConsoleAbortThread * abortThreadWidget ()
Public Member Functions inherited from QTextEdit
QTextEdit (QWidget *parent)
QTextEdit (const QString &text, QWidget *parent)
virtual ~QTextEdit ()
void setDocument (QTextDocument *document)
QTextDocument * document () const const
void setPlaceholderText (const QString &placeholderText)
QString placeholderText () const const
void setTextCursor (const QTextCursor &cursor)
QTextCursor textCursor () const const
bool isReadOnly () const const
void setReadOnly (bool ro)
void setTextInteractionFlags (Qt::TextInteractionFlags flags)
Qt::TextInteractionFlags textInteractionFlags () const const
qreal fontPointSize () const const
QString fontFamily () const const
int fontWeight () const const
bool fontUnderline () const const
bool fontItalic () const const
QColor textColor () const const
QColor textBackgroundColor () const const
QFont currentFont () const const
Qt::Alignment alignment () const const
void mergeCurrentCharFormat (const QTextCharFormat &modifier)
void setCurrentCharFormat (const QTextCharFormat &format)
QTextCharFormat currentCharFormat () const const
QTextEdit::AutoFormatting autoFormatting () const const
void setAutoFormatting (QTextEdit::AutoFormatting features)
bool tabChangesFocus () const const
void setTabChangesFocus (bool b)
void setDocumentTitle (const QString &title)
QString documentTitle () const const
bool isUndoRedoEnabled () const const
void setUndoRedoEnabled (bool enable)
QTextEdit::LineWrapMode lineWrapMode () const const
void setLineWrapMode (QTextEdit::LineWrapMode mode)
int lineWrapColumnOrWidth () const const
void setLineWrapColumnOrWidth (int w)
QTextOption::WrapMode wordWrapMode () const const
void setWordWrapMode (QTextOption::WrapMode policy)
bool find (const QString &exp, QTextDocument::FindFlags options)
bool find (const QRegExp &exp, QTextDocument::FindFlags options)
bool find (const QRegularExpression &exp, QTextDocument::FindFlags options)
QString toPlainText () const const
QString toHtml () const const
QString toMarkdown (QTextDocument::MarkdownFeatures features) const const
void ensureCursorVisible ()
virtual QVariant loadResource (int type, const QUrl &name)
QMenu * createStandardContextMenu ()
QMenu * createStandardContextMenu (const QPoint &position)
QTextCursor cursorForPosition (const QPoint &pos) const const
QRect cursorRect (const QTextCursor &cursor) const const
QRect cursorRect () const const
QString anchorAt (const QPoint &pos) const const
bool overwriteMode () const const
void setOverwriteMode (bool overwrite)
int tabStopWidth () const const
void setTabStopWidth (int width)
qreal tabStopDistance () const const
void setTabStopDistance (qreal distance)
int cursorWidth () const const
void setCursorWidth (int width)
bool acceptRichText () const const
void setAcceptRichText (bool accept)
void setExtraSelections (const QList< QTextEdit::ExtraSelection > &selections)
QList< QTextEdit::ExtraSelection > extraSelections () const const
void moveCursor (QTextCursor::MoveOperation operation, QTextCursor::MoveMode mode)
bool canPaste () const const
void print (QPagedPaintDevice *printer) const const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery property) const const override
void setFontPointSize (qreal s)
void setFontFamily (const QString &fontFamily)
void setFontWeight (int weight)
void setFontUnderline (bool underline)
void setFontItalic (bool italic)
void setTextColor (const QColor &c)
void setTextBackgroundColor (const QColor &c)
void setCurrentFont (const QFont &f)
void setAlignment (Qt::Alignment a)
void setPlainText (const QString &text)
void setHtml (const QString &text)
void setMarkdown (const QString &markdown)
void setText (const QString &text)
void cut ()
void copy ()
void paste ()
void undo ()
void redo ()
void clear ()
void selectAll ()
void insertPlainText (const QString &text)
void insertHtml (const QString &text)
void append (const QString &text)
void scrollToAnchor (const QString &name)
void zoomIn (int range)
void zoomOut (int range)
void textChanged ()
void undoAvailable (bool available)
void redoAvailable (bool available)
void currentCharFormatChanged (const QTextCharFormat &f)
void copyAvailable (bool yes)
void selectionChanged ()
void cursorPositionChanged ()
Public Member Functions inherited from QAbstractScrollArea
QAbstractScrollArea (QWidget *parent)
virtual ~QAbstractScrollArea ()
Qt::ScrollBarPolicy verticalScrollBarPolicy () const const
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
QScrollBar * verticalScrollBar () const const
void setVerticalScrollBar (QScrollBar *scrollBar)
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const const
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
QScrollBar * horizontalScrollBar () const const
void setHorizontalScrollBar (QScrollBar *scrollBar)
QWidget * cornerWidget () const const
void setCornerWidget (QWidget *widget)
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
QWidget * viewport () const const
void setViewport (QWidget *widget)
QSize maximumViewportSize () const const
virtual QSize minimumSizeHint () const const override
virtual QSize sizeHint () const const override
virtual void setupViewport (QWidget *viewport)
QAbstractScrollArea::SizeAdjustPolicy sizeAdjustPolicy () const const
void setSizeAdjustPolicy (QAbstractScrollArea::SizeAdjustPolicy policy)
Public Member Functions inherited from QFrame
QFrame (QWidget *parent, Qt::WindowFlags f)
virtual ~QFrame ()
int frameStyle () const const
void setFrameStyle (int style)
int frameWidth () const const
QFrame::Shape frameShape () const const
void setFrameShape (QFrame::Shape)
QFrame::Shadow frameShadow () const const
void setFrameShadow (QFrame::Shadow)
int lineWidth () const const
void setLineWidth (int)
int midLineWidth () const const
void setMidLineWidth (int)
QRect frameRect () const const
void setFrameRect (const QRect &)
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
virtual void setVisible (bool visible)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Protected Member Functions
void keyPressEvent (QKeyEvent *e) override
void mousePressEvent (QMouseEvent *event) override
Protected Member Functions inherited from QTextEdit
virtual void keyReleaseEvent (QKeyEvent *e) override
virtual void resizeEvent (QResizeEvent *e) override
virtual void paintEvent (QPaintEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *e) override
virtual void mouseReleaseEvent (QMouseEvent *e) override
virtual void mouseDoubleClickEvent (QMouseEvent *e) override
virtual bool focusNextPrevChild (bool next) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void dragEnterEvent (QDragEnterEvent *e) override
virtual void dragLeaveEvent (QDragLeaveEvent *e) override
virtual void dragMoveEvent (QDragMoveEvent *e) override
virtual void dropEvent (QDropEvent *e) override
virtual void focusInEvent (QFocusEvent *e) override
virtual void focusOutEvent (QFocusEvent *e) override
virtual void showEvent (QShowEvent *) override
virtual void changeEvent (QEvent *e) override
virtual void wheelEvent (QWheelEvent *e) override
virtual QMimeData * createMimeDataFromSelection () const const
virtual bool canInsertFromMimeData (const QMimeData *source) const const
virtual void insertFromMimeData (const QMimeData *source)
virtual void inputMethodEvent (QInputMethodEvent *e) override
virtual void scrollContentsBy (int dx, int dy) override
Protected Member Functions inherited from QAbstractScrollArea
void setViewportMargins (int left, int top, int right, int bottom)
void setViewportMargins (const QMargins &margins)
QMargins viewportMargins () const const
virtual bool event (QEvent *event) override
virtual bool viewportEvent (QEvent *event)
virtual QSize viewportSizeHint () const const
Protected Member Functions inherited from QFrame
void initStyleOption (QStyleOptionFrame *option) const const
Protected Member Functions inherited from QWidget
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void closeEvent (QCloseEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Additional Inherited Members
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QTextEdit
typedef AutoFormatting
NoWrap
WidgetWidth
FixedPixelWidth
FixedColumnWidth
AutoNone
AutoBulletList
AutoAll
Public Attributes inherited from QAbstractScrollArea
AdjustIgnored
AdjustToContentsOnFirstShow
AdjustToContents
Public Attributes inherited from QFrame
NoFrame
Box
Panel
WinPanel
HLine
VLine
StyledPanel
Plain
Raised
Sunken
Shadow_Mask
Shape_Mask
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Properties inherited from QTextEdit
autoFormatting
tabChangesFocus
documentTitle
undoRedoEnabled
lineWrapMode
wordWrapMode
lineWrapColumnOrWidth
readOnly
markdown
html
plainText
overwriteMode
tabStopWidth
tabStopDistance
acceptRichText
cursorWidth
textInteractionFlags
document
placeholderText
Properties inherited from QAbstractScrollArea
verticalScrollBarPolicy
horizontalScrollBarPolicy
sizeAdjustPolicy
Properties inherited from QFrame
frameShape
frameShadow
lineWidth
midLineWidth
frameWidth
frameRect
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Detailed Description
An interactable python console.
A widget that represents a simple python console with various features that most python consoles provide.
Definition at line 64 of file python_console.h.
Member Enumeration Documentation
PromptType
enum hal::PythonConsole::PromptType
Enumerator
Standard
Compound
Input
Definition at line 75 of file python_console.h.
Constructor & Destructor Documentation
PythonConsole()
hal::PythonConsole::PythonConsole (QWidget * parent = nullptr)
Constructor.
Definition at line 19 of file python_console.cpp.
References QObject::connect(), displayPrompt(), QTextEdit::document, QTextEdit::ensureCursorVisible(), hal::gPythonContext, hal::SettingsItemDropdown::intChanged(), QFrame::NoFrame, QFrame::setFrameStyle(), QTextEdit::setUndoRedoEnabled(), and hal::MainWindow::sSettingStyle.
~PythonConsole()
hal::PythonConsole::~PythonConsole ()
Definition at line 38 of file python_console.cpp.
References hal::gPythonContext.
Member Function Documentation
abortThreadWidget()
PythonConsoleAbortThread * hal::PythonConsole::abortThreadWidget ()
Definition at line 465 of file python_console.cpp.
Referenced by hal::PythonConsoleWidget::PythonConsoleWidget().
appendToCurrentCommand()
void hal::PythonConsole::appendToCurrentCommand (const QString & new_command)
Append the recently types python command with a string. (Used for auto-completion)
Parameters
new_command - The string that should be appended.
Definition at line 348 of file python_console.cpp.
References QWidget::cursor, QTextCursor::End, and QTextEdit::textCursor().
Referenced by handleTabKeyPressed().
clear()
void hal::PythonConsole::clear () override virtual
Clears the console.
Implements hal::PythonContextSubscriber.
Definition at line 240 of file python_console.cpp.
References QTextEdit::clear().
displayPrompt()
void hal::PythonConsole::displayPrompt ()
Used to display the editors content within the QTextEdit.
Definition at line 253 of file python_console.cpp.
References Compound, QWidget::cursor, QTextEdit::document, QTextCursor::End, QTextCursor::EndOfLine, Input, hal::PythonConsoleQssAdapter::instance(), QString::length(), QTextCursor::position(), QTextFormat::setForeground(), QTextEdit::setTextCursor(), Standard, and QTextEdit::textCursor().
Referenced by handleTabKeyPressed(), interpretCommand(), and PythonConsole().
getCurrentCommand()
QString hal::PythonConsole::getCurrentCommand ()
Get the recently types python command (of the current line).
Returns
the current command as a string.
Definition at line 328 of file python_console.cpp.
References control::command, QWidget::cursor, QTextCursor::End, QTextCursor::KeepAnchor, and QTextEdit::textCursor().
Referenced by handleTabKeyPressed(), handleUpKeyPressed(), and interpretCommand().
handleDownKeyPressed()
void hal::PythonConsole::handleDownKeyPressed ()
Handles presses of KEY_DOWN. Used to jump forward in history.
Definition at line 389 of file python_console.cpp.
References QString::fromStdString(), and replaceCurrentCommand().
Referenced by keyPressEvent().
handleError()
void hal::PythonConsole::handleError (const QString & output) override virtual
Prints forwarded error output messages.
Parameters
output - The forwarded output string.
Implements hal::PythonContextSubscriber.
Definition at line 232 of file python_console.cpp.
References QString::endsWith(), insertAtEnd(), hal::PythonConsoleQssAdapter::instance(), and hal::output.
handleStdout()
void hal::PythonConsole::handleStdout (const QString & output) override virtual
Prints forwarded standard output messages.
Parameters
output - The forwarded output string.
Implements hal::PythonContextSubscriber.
Definition at line 227 of file python_console.cpp.
References insertAtEnd(), hal::PythonConsoleQssAdapter::instance(), and hal::output.
Referenced by handleTabKeyPressed().
handleTabKeyPressed()
void hal::PythonConsole::handleTabKeyPressed ()
Handles presses of TAB. Used to indent or auto-complete the current command.
Definition at line 410 of file python_console.cpp.
References appendToCurrentCommand(), Compound, displayPrompt(), QString::fromStdString(), getCurrentCommand(), hal::gPythonContext, handleStdout(), Input, QTextEdit::insertPlainText(), QString::isEmpty(), log_info, QString::mid(), replaceCurrentCommand(), QString::size(), Standard, and QString::toStdString().
Referenced by keyPressEvent().
handleThreadFinished
void hal::PythonConsole::handleThreadFinished () slot
Definition at line 288 of file python_console.cpp.
References hal::PythonConsoleAbortThread::stop().
handleUpKeyPressed()
void hal::PythonConsole::handleUpKeyPressed ()
Handles presses of KEY_UP. Used to jump back in history.
Definition at line 362 of file python_console.cpp.
References QString::fromStdString(), getCurrentCommand(), and replaceCurrentCommand().
Referenced by keyPressEvent().
inputReceived
void hal::PythonConsole::inputReceived (QString input) signal
insertAtEnd()
void hal::PythonConsole::insertAtEnd (const QString & text, QColor textColor)
Append the console with a text of a certain color.
Parameters
text - The appended text.
textColor - The color of the appended text.
Definition at line 220 of file python_console.cpp.
References QTextCursor::End, QTextEdit::insertPlainText(), QTextEdit::moveCursor(), QTextEdit::setTextColor(), and QTextEdit::textColor().
Referenced by handleError(), and handleStdout().
interpretCommand()
void hal::PythonConsole::interpretCommand ()
Process the recently typed python command after pressing ENTER/RETURN. If the command is within (or starts) a compound statement (for example a 'for'-loop), the command is appended to the current compound input. Else, the command (or the finished compound) is interpreted and executed.
Definition at line 293 of file python_console.cpp.
References Compound, QWidget::cursor, displayPrompt(), QTextCursor::End, getCurrentCommand(), hal::gPythonContext, hal::input, Standard, hal::PythonConsoleAbortThread::start(), and QTextEdit::textCursor().
Referenced by keyPressEvent().
keyPressEvent()
void hal::PythonConsole::keyPressEvent (QKeyEvent * e) override protected virtual
Overrides QTextEdit::keyPressEvent. It is used to handle the following (default) inputs:
Ctrl+C: Copy
Ctrl+X: Cut
ENTER/RETURN: Interpret the written python command
BACKSPACE: Backspace
KEY_UP: Get the previous command from the history
KEY_DOWN: Get the next command from the history
TAB: Indent or autofill
Parameters
e - The key event.
Reimplemented from QTextEdit.
Definition at line 74 of file python_console.cpp.
References QEvent::accept(), Qt::ControlModifier, QKeySequence::Copy, QTextEdit::copy(), QWidget::cursor, QKeySequence::Cut, QTextCursor::End, handleDownKeyPressed(), handleTabKeyPressed(), handleUpKeyPressed(), interpretCommand(), QKeyEvent::key(), Qt::Key_Backspace, Qt::Key_Control, Qt::Key_Down, Qt::Key_End, Qt::Key_Enter, Qt::Key_Home, Qt::Key_Left, Qt::Key_Return, Qt::Key_Right, Qt::Key_Tab, Qt::Key_Up, QTextEdit::keyPressEvent(), QKeyEvent::matches(), QKeyEvent::modifiers(), QTextCursor::MoveAnchor, QTextEdit::moveCursor(), QTextEdit::setTextCursor(), and QTextEdit::textCursor().
mousePressEvent()
void hal::PythonConsole::mousePressEvent (QMouseEvent * event) override protected virtual
Overrides QTextEdit::mouseEvent.
Parameters
event - The mouse event
Reimplemented from QTextEdit.
Definition at line 205 of file python_console.cpp.
References QAbstractScrollArea::event(), and QTextEdit::mousePressEvent().
replaceCurrentCommand()
void hal::PythonConsole::replaceCurrentCommand (const QString & new_command)
Replace the recently types python command with another one. (Used e.g. for navigating in the history)
Parameters
new_command - The new command.
Definition at line 340 of file python_console.cpp.
References QWidget::cursor, QTextCursor::End, QTextCursor::KeepAnchor, and QTextEdit::textCursor().
Referenced by handleDownKeyPressed(), handleTabKeyPressed(), and handleUpKeyPressed().
selectionEditable()
bool hal::PythonConsole::selectionEditable ()
Currently unused.
Returns
false
Definition at line 355 of file python_console.cpp.
References QWidget::cursor, QTextEdit::document, and QTextEdit::textCursor().
setInputMode()
void hal::PythonConsole::setInputMode (bool state)
Set input mode on or off. In input mode input for running script is expected.
Parameters
state - true=on, false=off
Definition at line 245 of file python_console.cpp.
References Input, Standard, and hal::state.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/python/python_console.h
/home/runner/work/hal/hal/plugins/gui/src/python/python_console.cpp