HAL: hal::NetLayoutConnectionMetric Class Reference
hal::NetLayoutConnectionMetric Class Reference
HAL Gui » Graph Widget » Layouters
#include <net_layout_point.h>
Public Member Functions
NetLayoutConnectionMetric ()
~NetLayoutConnectionMetric ()
void clearAll ()
Public Member Functions inherited from QMap< NetLayoutMetric, NetLayoutConnection * >
QMap ()
QMap (std::initializer_list< std::pair< Key, T > > list)
QMap (const QMap< Key, T > &other)
QMap (QMap< Key, T > &&other)
QMap (const typename std::map< Key, T > &other)
~QMap ()
QMap< Key, T > & operator= (const QMap< Key, T > &other)
QMap< Key, T > & operator= (QMap< Key, T > &&other)
void swap (QMap< Key, T > &other)
std::map< Key, T > toStdMap () const const
bool operator== (const QMap< Key, T > &other) const const
bool operator!= (const QMap< Key, T > &other) const const
int size () const const
bool isEmpty () const const
void clear ()
int remove (const Key &key)
T take (const Key &key)
bool contains (const Key &key) const const
const Key key (const T &value, const Key &defaultKey) const const
const T value (const Key &key, const T &defaultValue) const const
T & operator[] (const Key &key)
const T operator[] (const Key &key) const const
QList< Key > keys () const const
QList< Key > keys (const T &value) const const
QList< T > values () const const
QList< T > values (const Key &key) const const
QList< Key > uniqueKeys () const const
int count (const Key &key) const const
int count () const const
const Key & firstKey () const const
const Key & lastKey () const const
T & first ()
const T & first () const const
T & last ()
const T & last () const const
QMap::iterator begin ()
QMap::const_iterator begin () const const
QMap::const_iterator constBegin () const const
QMap::const_iterator cbegin () const const
QMap::iterator end ()
QMap::const_iterator end () const const
QMap::const_iterator constEnd () const const
QMap::const_iterator cend () const const
QMap::key_iterator keyBegin () const const
QMap::key_iterator keyEnd () const const
QMap::key_value_iterator keyValueBegin ()
QMap::const_key_value_iterator keyValueBegin () const const
QMap::key_value_iterator keyValueEnd ()
QMap::const_key_value_iterator keyValueEnd () const const
QMap::const_key_value_iterator constKeyValueBegin () const const
QMap::const_key_value_iterator constKeyValueEnd () const const
QMap::iterator erase (QMap::iterator pos)
QMap::iterator find (const Key &key)
QMap::const_iterator find (const Key &key) const const
QMap::const_iterator constFind (const Key &key) const const
QMap::iterator lowerBound (const Key &key)
QMap::const_iterator lowerBound (const Key &key) const const
QMap::iterator upperBound (const Key &key)
QMap::const_iterator upperBound (const Key &key) const const
QMap::iterator insert (const Key &key, const T &value)
QMap::iterator insert (QMap::const_iterator pos, const Key &key, const T &value)
void insert (const QMap< Key, T > &map)
QMap::iterator insertMulti (const Key &key, const T &value)
QMap::iterator insertMulti (QMap::const_iterator pos, const Key &key, const T &value)
QMap< Key, T > & unite (const QMap< Key, T > &other)
bool empty () const const
QPair< QMap::iterator, QMap::iterator > equal_range (const Key &key)
QPair< QMap::const_iterator, QMap::const_iterator > equal_range (const Key &key) const const
QDataStream & operator<< (QDataStream &out, const QMap< Key, T > &map)
QDataStream & operator>> (QDataStream &in, QMap< Key, T > &map)
Additional Inherited Members
Public Attributes inherited from QMap< NetLayoutMetric, NetLayoutConnection * >
typedef const_key_value_iterator
typedef key_value_iterator
typedef Iterator
typedef ConstIterator
typedef key_type
typedef mapped_type
typedef difference_type
typedef size_type
Detailed Description
Definition at line 166 of file net_layout_point.h.
Constructor & Destructor Documentation
NetLayoutConnectionMetric()
hal::NetLayoutConnectionMetric::NetLayoutConnectionMetric () inline
Definition at line 169 of file net_layout_point.h.
~NetLayoutConnectionMetric()
hal::NetLayoutConnectionMetric::~NetLayoutConnectionMetric ()
Definition at line 441 of file net_layout_point.cpp.
References clearAll().
Member Function Documentation
clearAll()
void hal::NetLayoutConnectionMetric::clearAll ()
Definition at line 446 of file net_layout_point.cpp.
References QMap< NetLayoutMetric, NetLayoutConnection * >::clear(), and QMap< NetLayoutMetric, NetLayoutConnection * >::values().
Referenced by ~NetLayoutConnectionMetric().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/net_layout_point.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/net_layout_point.cpp