HAL: hal::ModuleColorManager Class Reference
hal::ModuleColorManager Class Reference
#include <module_color_manager.h>
Signals
void moduleColorChanged (u32 id) const
Public Member Functions
ModuleColorManager (QObject *parent=nullptr)
QColor moduleColor (u32 id) const
QColor setModuleColor (u32 id, const QColor &col)
QColor setRandomColor (u32 id)
void removeColor (u32 id)
QMap< u32, QColor > getColorMap () const
void clear ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Manages the module colors which will be assigned either by an "random" algorithm or manually by user. Quotes around "random" indicate it is not random at all, it is some homemade spinning around in HSV color circle.
Definition at line 40 of file module_color_manager.h.
Constructor & Destructor Documentation
ModuleColorManager()
hal::ModuleColorManager::ModuleColorManager (QObject * parent = nullptr)
Definition at line 16 of file module_color_manager.cpp.
References setModuleColor().
Member Function Documentation
clear()
void hal::ModuleColorManager::clear ()
Definition at line 22 of file module_color_manager.cpp.
References QMap::clear().
getColorMap()
QMap< u32, QColor > hal::ModuleColorManager::getColorMap () const
Getter for map of all module colores
Returns
The map of all module colores
Definition at line 61 of file module_color_manager.cpp.
moduleColor()
QColor hal::ModuleColorManager::moduleColor (u32 id) const
Gets the module color of a module of a specific id.
Parameters
id - The module id of the module to get the color for
Returns
the color of the module
Definition at line 27 of file module_color_manager.cpp.
References QMap::value().
Referenced by hal::ActionDeleteObject::exec(), and hal::NetlistRelay::getModuleColor().
moduleColorChanged
void hal::ModuleColorManager::moduleColorChanged (u32 id) const signal
Q_SIGNAL to notify that the color of a module has been changed.
Parameters
id - Id of the module with the changed color
Referenced by hal::ModuleDetailsTabWidget::ModuleDetailsTabWidget(), hal::SelectionTreeView::SelectionTreeView(), and setModuleColor().
removeColor()
void hal::ModuleColorManager::removeColor (u32 id)
Removes the color that belongs to the given id.
Parameters
id - The module id for which to remove the color.
Definition at line 66 of file module_color_manager.cpp.
References QMap::remove().
setModuleColor()
QColor hal::ModuleColorManager::setModuleColor (u32 id, const QColor & col)
Changes the color of a module.
Parameters
id - The id of the module
col - The new color
Returns
the old color of the module (used to create an undo action easier)
Definition at line 32 of file module_color_manager.cpp.
References id, moduleColorChanged(), QObject::Q_EMIT(), and QMap::value().
Referenced by hal::ActionSetObjectColor::exec(), and ModuleColorManager().
setRandomColor()
QColor hal::ModuleColorManager::setRandomColor (u32 id)
Changes the color of a module to a random color.
Parameters
id - The id of the module
Returns
the old color of the module (used to create an undo action easier)
Definition at line 54 of file module_color_manager.cpp.
References QMap::insert(), and QMap::value().
Referenced by hal::NetlistRelay::debugHandleFileOpened().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/module_model/module_color_manager.h
/home/runner/work/hal/hal/plugins/gui/src/module_model/module_color_manager.cpp