HAL: hal::NodeDragShadow Class Reference
hal::NodeDragShadow Class Reference
HAL Gui » Graph Widget » Visuals
An item that is drawn when a node is dragged through the scene.
#include <node_drag_shadow.h>
Public Types
enum DragCue { DragCue::Movable = 0, DragCue::Swappable = 1, DragCue::Rejected = 2 }
Public Types inherited from QGraphicsItem
enum GraphicsItemFlag
enum GraphicsItemChange
enum CacheMode
enum PanelModality
enum anonymous
Public Member Functions
NodeDragShadow ()
void start (const QPointF &posF, const QSizeF &sizeF)
void stop ()
qreal width () const
qreal height () const
QSizeF size () const
void setWidth (const qreal width)
void setHeight (const qreal height)
void setVisualCue (const DragCue cue)
Public Member Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItem *parent)
virtual ~QGraphicsObject ()
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void parentChanged ()
void opacityChanged ()
void visibleChanged ()
void enabledChanged ()
void xChanged ()
void yChanged ()
void zChanged ()
void rotationChanged ()
void scaleChanged ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QGraphicsItem
QGraphicsItem (QGraphicsItem *parent)
virtual ~QGraphicsItem ()
QGraphicsScene * scene () const const
QGraphicsItem * parentItem () const const
QGraphicsItem * topLevelItem () const const
QGraphicsObject * parentObject () const const
QGraphicsWidget * parentWidget () const const
QGraphicsWidget * topLevelWidget () const const
QGraphicsWidget * window () const const
QGraphicsItem * panel () const const
void setParentItem (QGraphicsItem *newParent)
QList< QGraphicsItem * > children () const const
QList< QGraphicsItem * > childItems () const const
bool isWidget () const const
bool isWindow () const const
bool isPanel () const const
QGraphicsObject * toGraphicsObject ()
const QGraphicsObject * toGraphicsObject () const const
QGraphicsItemGroup * group () const const
void setGroup (QGraphicsItemGroup *group)
QGraphicsItem::GraphicsItemFlags flags () const const
void setFlag (QGraphicsItem::GraphicsItemFlag flag, bool enabled)
void setFlags (QGraphicsItem::GraphicsItemFlags flags)
QGraphicsItem::CacheMode cacheMode () const const
void setCacheMode (QGraphicsItem::CacheMode mode, const QSize &logicalCacheSize)
QGraphicsItem::PanelModality panelModality () const const
void setPanelModality (QGraphicsItem::PanelModality panelModality)
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel) const const
QString toolTip () const const
void setToolTip (const QString &toolTip)
QCursor cursor () const const
void setCursor (const QCursor &cursor)
bool hasCursor () const const
void unsetCursor ()
bool isVisible () const const
bool isVisibleTo (const QGraphicsItem *parent) const const
void setVisible (bool visible)
void hide ()
void show ()
bool isEnabled () const const
void setEnabled (bool enabled)
bool isSelected () const const
void setSelected (bool selected)
bool acceptDrops () const const
void setAcceptDrops (bool on)
qreal opacity () const const
qreal effectiveOpacity () const const
void setOpacity (qreal opacity)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
Qt::MouseButtons acceptedMouseButtons () const const
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
bool acceptsHoverEvents () const const
void setAcceptsHoverEvents (bool enabled)
bool acceptHoverEvents () const const
void setAcceptHoverEvents (bool enabled)
bool acceptTouchEvents () const const
void setAcceptTouchEvents (bool enabled)
bool filtersChildEvents () const const
void setFiltersChildEvents (bool enabled)
bool handlesChildEvents () const const
void setHandlesChildEvents (bool enabled)
bool isActive () const const
void setActive (bool active)
bool hasFocus () const const
void setFocus (Qt::FocusReason focusReason)
void clearFocus ()
QGraphicsItem * focusProxy () const const
void setFocusProxy (QGraphicsItem *item)
QGraphicsItem * focusItem () const const
void grabMouse ()
void ungrabMouse ()
void grabKeyboard ()
void ungrabKeyboard ()
QPointF pos () const const
qreal x () const const
void setX (qreal x)
qreal y () const const
void setY (qreal y)
QPointF scenePos () const const
void setPos (const QPointF &pos)
void setPos (qreal x, qreal y)
void moveBy (qreal dx, qreal dy)
void ensureVisible (const QRectF &rect, int xmargin, int ymargin)
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin, int ymargin)
QMatrix matrix () const const
QMatrix sceneMatrix () const const
void setMatrix (const QMatrix &matrix, bool combine)
void resetMatrix ()
QTransform transform () const const
QTransform sceneTransform () const const
QTransform deviceTransform (const QTransform &viewportTransform) const const
QTransform itemTransform (const QGraphicsItem *other, bool *ok) const const
void setTransform (const QTransform &matrix, bool combine)
void resetTransform ()
void rotate (qreal angle)
void scale (qreal sx, qreal sy)
void shear (qreal sh, qreal sv)
void translate (qreal dx, qreal dy)
void setRotation (qreal angle)
qreal rotation () const const
void setScale (qreal factor)
qreal scale () const const
QList< QGraphicsTransform * > transformations () const const
void setTransformations (const QList< QGraphicsTransform * > &transformations)
QPointF transformOriginPoint () const const
void setTransformOriginPoint (const QPointF &origin)
void setTransformOriginPoint (qreal x, qreal y)
virtual void advance (int phase)
qreal zValue () const const
void setZValue (qreal z)
void stackBefore (const QGraphicsItem *sibling)
QRectF childrenBoundingRect () const const
QRectF sceneBoundingRect () const const
bool isClipped () const const
QPainterPath clipPath () const const
virtual bool contains (const QPointF &point) const const
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode) const const
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode) const const
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode) const const
bool isObscured (const QRectF &rect) const const
bool isObscured (qreal x, qreal y, qreal w, qreal h) const const
virtual bool isObscuredBy (const QGraphicsItem *item) const const
virtual QPainterPath opaqueArea () const const
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const const
qreal boundingRegionGranularity () const const
void setBoundingRegionGranularity (qreal granularity)
void update (const QRectF &rect)
void update (qreal x, qreal y, qreal width, qreal height)
void scroll (qreal dx, qreal dy, const QRectF &rect)
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const const
QPointF mapToParent (const QPointF &point) const const
QPointF mapToScene (const QPointF &point) const const
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const const
QPolygonF mapToParent (const QRectF &rect) const const
QPolygonF mapToScene (const QRectF &rect) const const
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const const
QRectF mapRectToParent (const QRectF &rect) const const
QRectF mapRectToScene (const QRectF &rect) const const
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const const
QPolygonF mapToParent (const QPolygonF &polygon) const const
QPolygonF mapToScene (const QPolygonF &polygon) const const
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const const
QPainterPath mapToParent (const QPainterPath &path) const const
QPainterPath mapToScene (const QPainterPath &path) const const
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const const
QPointF mapFromParent (const QPointF &point) const const
QPointF mapFromScene (const QPointF &point) const const
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const const
QPolygonF mapFromParent (const QRectF &rect) const const
QPolygonF mapFromScene (const QRectF &rect) const const
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const const
QRectF mapRectFromParent (const QRectF &rect) const const
QRectF mapRectFromScene (const QRectF &rect) const const
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const const
QPolygonF mapFromParent (const QPolygonF &polygon) const const
QPolygonF mapFromScene (const QPolygonF &polygon) const const
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const const
QPainterPath mapFromParent (const QPainterPath &path) const const
QPainterPath mapFromScene (const QPainterPath &path) const const
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const const
QPointF mapToParent (qreal x, qreal y) const const
QPointF mapToScene (qreal x, qreal y) const const
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const const
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const const
QPointF mapFromParent (qreal x, qreal y) const const
QPointF mapFromScene (qreal x, qreal y) const const
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const const
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const const
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const const
bool isAncestorOf (const QGraphicsItem *child) const const
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const const
bool isUnderMouse () const const
QVariant data (int key) const const
void setData (int key, const QVariant &value)
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
virtual int type () const const
void installSceneEventFilter (QGraphicsItem *filterItem)
void removeSceneEventFilter (QGraphicsItem *filterItem)
T qgraphicsitem_cast (QGraphicsItem *item)
Static Public Member Functions
static void setLod (const qreal lod)
static void loadSettings ()
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QRectF boundingRect () const override
QPainterPath shape () const override
Protected Member Functions inherited from QGraphicsObject
void updateMicroFocus ()
virtual bool event (QEvent *ev) override
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QGraphicsItem
void updateMicroFocus ()
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
virtual bool sceneEvent (QEvent *event)
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
virtual void inputMethodEvent (QInputMethodEvent *event)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
virtual QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
void prepareGeometryChange ()
Additional Inherited Members
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QGraphicsItem
typedef GraphicsItemFlags
ItemIsMovable
ItemIsSelectable
ItemIsFocusable
ItemClipsToShape
ItemClipsChildrenToShape
ItemIgnoresTransformations
ItemIgnoresParentOpacity
ItemDoesntPropagateOpacityToChildren
ItemStacksBehindParent
ItemUsesExtendedStyleOption
ItemHasNoContents
ItemSendsGeometryChanges
ItemAcceptsInputMethod
ItemNegativeZStacksBehindParent
ItemIsPanel
ItemIsFocusScope
ItemSendsScenePositionChanges
ItemStopsClickFocusPropagation
ItemStopsFocusHandling
ItemContainsChildrenInShape
ItemPositionChange
ItemMatrixChange
ItemVisibleChange
ItemEnabledChange
ItemSelectedChange
ItemParentChange
ItemChildAddedChange
ItemChildRemovedChange
ItemTransformChange
ItemPositionHasChanged
ItemTransformHasChanged
ItemSceneChange
ItemVisibleHasChanged
ItemEnabledHasChanged
ItemSelectedHasChanged
ItemParentHasChanged
ItemSceneHasChanged
ItemCursorChange
ItemCursorHasChanged
ItemToolTipChange
ItemToolTipHasChanged
ItemFlagsChange
ItemFlagsHaveChanged
ItemZValueChange
ItemZValueHasChanged
ItemOpacityChange
ItemOpacityHasChanged
ItemScenePositionHasChanged
ItemRotationChange
ItemRotationHasChanged
ItemScaleChange
ItemScaleHasChanged
ItemTransformOriginPointChange
ItemTransformOriginPointHasChanged
NoCache
ItemCoordinateCache
DeviceCoordinateCache
NonModal
PanelModal
SceneModal
Type
UserType
Properties inherited from QGraphicsObject
parent
opacity
enabled
visible
pos
x
y
z
rotation
scale
transformOriginPoint
effect
Properties inherited from QObject
objectName
Detailed Description
An item that is drawn when a node is dragged through the scene.
Definition at line 36 of file node_drag_shadow.h.
Member Enumeration Documentation
DragCue
enum hal::NodeDragShadow::DragCue strong
Enumerator
Movable
Swappable
Rejected
Definition at line 41 of file node_drag_shadow.h.
Constructor & Destructor Documentation
NodeDragShadow()
hal::NodeDragShadow::NodeDragShadow ()
Definition at line 39 of file node_drag_shadow.cpp.
References QGraphicsItem::hide(), and QGraphicsItem::setAcceptedMouseButtons().
Member Function Documentation
boundingRect()
QRectF hal::NodeDragShadow::boundingRect () const override protected virtual
Implements QGraphicsItem.
Definition at line 121 of file node_drag_shadow.cpp.
height()
qreal hal::NodeDragShadow::height () const
Definition at line 67 of file node_drag_shadow.cpp.
Referenced by setHeight().
loadSettings()
void hal::NodeDragShadow::loadSettings () static
Definition at line 21 of file node_drag_shadow.cpp.
References Qt::MiterJoin, Movable, Rejected, QPen::setCosmetic(), QPen::setJoinStyle(), and Swappable.
Referenced by hal::style::debugUpdate().
paint()
void hal::NodeDragShadow::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override protected virtual
Implements QGraphicsItem.
Definition at line 98 of file node_drag_shadow.cpp.
References QPainter::drawRect(), QPainter::fillRect(), option(), QPen::setColor(), and QPainter::setPen().
setHeight()
void hal::NodeDragShadow::setHeight (const qreal height)
Definition at line 82 of file node_drag_shadow.cpp.
References height().
Referenced by start().
setLod()
void hal::NodeDragShadow::setLod (const qreal lod) static
Definition at line 87 of file node_drag_shadow.cpp.
Referenced by hal::GraphGraphicsView::paintEvent().
setVisualCue()
void hal::NodeDragShadow::setVisualCue (const DragCue cue)
Definition at line 92 of file node_drag_shadow.cpp.
References QGraphicsItem::update().
Referenced by hal::GraphicsScene::moveDragShadow(), and hal::GraphicsScene::startDragShadow().
setWidth()
void hal::NodeDragShadow::setWidth (const qreal width)
Definition at line 77 of file node_drag_shadow.cpp.
References width().
Referenced by start().
shape()
QPainterPath hal::NodeDragShadow::shape () const override protected virtual
Reimplemented from QGraphicsItem.
Definition at line 126 of file node_drag_shadow.cpp.
References QPainterPath::addRect().
size()
QSizeF hal::NodeDragShadow::size () const
Definition at line 72 of file node_drag_shadow.cpp.
start()
void hal::NodeDragShadow::start (const QPointF & posF, const QSizeF & sizeF)
Definition at line 48 of file node_drag_shadow.cpp.
References QSizeF::height(), setHeight(), QGraphicsItem::setPos(), setWidth(), QGraphicsItem::setZValue(), QGraphicsItem::show(), and QSizeF::width().
Referenced by hal::GraphicsScene::startDragShadow().
stop()
void hal::NodeDragShadow::stop ()
Definition at line 57 of file node_drag_shadow.cpp.
References QGraphicsItem::hide().
Referenced by hal::GraphicsScene::stopDragShadow().
width()
qreal hal::NodeDragShadow::width () const
Definition at line 62 of file node_drag_shadow.cpp.
Referenced by setWidth().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/items/utility_items/node_drag_shadow.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/items/utility_items/node_drag_shadow.cpp