HAL: hal::LUTComponent Class Reference
hal::LUTComponent Class Reference
#include <lut_component.h>
Public Member Functions
LUTComponent (std::unique_ptr< GateTypeComponent > component, bool init_ascending)
ComponentType get_type () const override
std::vector< GateTypeComponent * > get_components (const std::function< bool(const GateTypeComponent *)> &filter=nullptr) const override
bool is_init_ascending () const
void set_init_ascending (bool init_ascending=true)
Public Member Functions inherited from hal::GateTypeComponent
virtual ~GateTypeComponent ()=default
template<typename T >
T * convert_to ()
template<typename T >
const T * convert_to () const
GateTypeComponent * get_component (const std::function< bool(const GateTypeComponent *)> &filter=nullptr) const
template<typename T >
T * get_component_as (const std::function< bool(const GateTypeComponent *)> &filter=nullptr)
Static Public Member Functions
static bool is_class_of (const GateTypeComponent *component)
Static Public Member Functions inherited from hal::GateTypeComponent
static std::unique_ptr< GateTypeComponent > create_lut_component (std::unique_ptr< GateTypeComponent > component, bool init_ascending)
static std::unique_ptr< GateTypeComponent > create_ff_component (std::unique_ptr< GateTypeComponent > component, const BooleanFunction &next_state_bf, const BooleanFunction &clock_bf)
static std::unique_ptr< GateTypeComponent > create_latch_component (std::unique_ptr< GateTypeComponent > component)
static std::unique_ptr< GateTypeComponent > create_ram_component (std::unique_ptr< GateTypeComponent > component, const u32 bit_size)
static std::unique_ptr< GateTypeComponent > create_mac_component ()
static std::unique_ptr< GateTypeComponent > create_init_component (const std::string &init_category, const std::vector< std::string > &init_identifiers)
static std::unique_ptr< GateTypeComponent > create_state_component (std::unique_ptr< GateTypeComponent > component, const std::string &state_identifier, const std::string &neg_state_identifier)
static std::unique_ptr< GateTypeComponent > create_ram_port_component (std::unique_ptr< GateTypeComponent > component, const std::string &data_group, const std::string &addr_group, const BooleanFunction &clock_bf, const BooleanFunction &enable_bf, bool is_write)
Additional Inherited Members
Public Types inherited from hal::GateTypeComponent
enum ComponentType {
ComponentType::lut, ComponentType::ff, ComponentType::latch, ComponentType::ram,
ComponentType::mac, ComponentType::init, ComponentType::state, ComponentType::ram_port
}
Detailed Description
Definition at line 32 of file lut_component.h.
Constructor & Destructor Documentation
LUTComponent()
hal::LUTComponent::LUTComponent (std::unique_ptr< GateTypeComponent > component, bool init_ascending)
Construct a new LUTComponent with given child component and bit-order.
Parameters
[in] component - Another component to be added as a child component.
[in] init_ascending - True if ascending bit-order, false otherwise.
Definition at line 5 of file lut_component.cpp.
Member Function Documentation
get_components()
std::vector< GateTypeComponent * > hal::LUTComponent::get_components (const std::function< bool(const GateTypeComponent *)> & filter = nullptr) const override virtual
Get the sub-components of the gate type component. A user-defined filter may be applied to the result vector, but is disabled by default.
Parameters
[in] filter - The user-defined filter function applied to all candidate components.
Returns
The sub-components of the gate type component.
Implements hal::GateTypeComponent.
Definition at line 19 of file lut_component.cpp.
get_type()
LUTComponent::ComponentType hal::LUTComponent::get_type () const override virtual
Get the type of the gate type component.
Returns
The type of the gate type component.
Implements hal::GateTypeComponent.
Definition at line 9 of file lut_component.cpp.
is_class_of()
bool hal::LUTComponent::is_class_of (const GateTypeComponent * component) static
Check whether a component is a LUTComponent.
Parameters
[in] component - The component to check.
Returns
True if component is a LUTComponent, false otherwise.
Definition at line 14 of file lut_component.cpp.
References hal::GateTypeComponent::get_type().
Referenced by hal::gate_type_components_init().
is_init_ascending()
bool hal::LUTComponent::is_init_ascending () const
Get the bit-order of the initialization string.
Returns
True if ascending bit-order, false otherwise.
Definition at line 42 of file lut_component.cpp.
Referenced by hal::Gate::add_boolean_function(), and hal::gate_type_components_init().
set_init_ascending()
void hal::LUTComponent::set_init_ascending (bool init_ascending = true)
Set the bit-order of the initialization string.
Parameters
[in] init_ascending - True if ascending bit-order, false otherwise.
Definition at line 47 of file lut_component.cpp.
References ascending.
Referenced by hal::gate_type_components_init().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/include/hal_core/netlist/gate_library/gate_type_component/lut_component.h
/home/runner/work/hal/hal/src/netlist/gate_library/gate_type_component/lut_component.cpp