HAL: hal::SolveFsmPlugin Class Reference
hal::SolveFsmPlugin Class Reference
#include <plugin_solve_fsm.h>
Public Member Functions
std::string get_name () const override
std::string get_version () const override
void initialize () override
Public Member Functions inherited from hal::BasePluginInterface
BasePluginInterface ()=default
virtual ~BasePluginInterface ()
virtual std::string get_description () const
virtual std::set< std::string > get_dependencies () const
template<typename... Args>
void log (const Args &... args) const
virtual void on_load ()
virtual void on_unload ()
virtual void initialize_logging ()
virtual std::vector< AbstractExtensionInterface * > get_extensions () const
template<typename T >
T * get_first_extension () const
void delete_extension (AbstractExtensionInterface *aeif)
Static Public Member Functions
static Result< std::map< u64, std::map< u64, BooleanFunction > > > solve_fsm (Netlist *nl, const std::vector< Gate * > &state_reg, const std::vector< Gate * > &transition_logic, const std::map< Gate *, bool > &initial_state={}, const std::string &graph_path="", const u32 timeout=600000)
static Result< std::map< u64, std::map< u64, BooleanFunction > > > solve_fsm_brute_force (Netlist *nl, const std::vector< Gate * > &state_reg, const std::vector< Gate * > &transition_logic, const std::string &graph_path="")
static Result< std::string > generate_dot_graph (const std::vector< Gate * > &state_reg, const std::map< u64, std::map< u64, BooleanFunction >> &transitions, const std::string &graph_path="", const u32 max_condition_length=128, const u32 base=10)
Additional Inherited Members
Protected Attributes inherited from hal::BasePluginInterface
std::vector< AbstractExtensionInterface * > m_extensions
Detailed Description
Definition at line 42 of file plugin_solve_fsm.h.
Member Function Documentation
generate_dot_graph()
Result< std::string > hal::SolveFsmPlugin::generate_dot_graph (const std::vector< Gate * > & state_reg, const std::map< u64, std::map< u64, BooleanFunction >> & transitions, const std::string & graph_path = "", const u32 max_condition_length = 128, const u32 base = 10) static
Generates the state graph of a finite state machine from the transitions of that fsm.
Parameters
[in] state_reg - Vector contianing the state registers.
[in] transitions - Transitions of the fsm given as a map from origin state to all possible successor states and the corresponding condition.
[in] graph_path - Path where the transition state graph in dot format is saved.
[in] max_condition_length - The maximum character length that is printed for boolean functions representing the conditions.
[in] base - The base with that the states are formatted and printed.
Returns
A string representing the dot graph.
Definition at line 557 of file plugin_solve_fsm.cpp.
References ERR, test_plugin::graph_path, and OK.
Referenced by hal::PYBIND11_PLUGIN(), solve_fsm(), and solve_fsm_brute_force().
get_name()
std::string hal::SolveFsmPlugin::get_name () const override virtual
Get the name of the plugin.
Returns
The name of the plugin.
Implements hal::BasePluginInterface.
Definition at line 34 of file plugin_solve_fsm.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_version()
std::string hal::SolveFsmPlugin::get_version () const override virtual
Get the version of the plugin.
Returns
The version of the plugin.
Implements hal::BasePluginInterface.
Definition at line 39 of file plugin_solve_fsm.cpp.
Referenced by hal::PYBIND11_PLUGIN().
initialize()
void hal::SolveFsmPlugin::initialize () override virtual
Plugins utilize two phase construction. Always populate all members etc in the initialize function which is automatically called by plugin_manager::get_plugin_instance()
Reimplemented from hal::BasePluginInterface.
Definition at line 44 of file plugin_solve_fsm.cpp.
solve_fsm()
Result< std::map< u64, std::map< u64, BooleanFunction > > > hal::SolveFsmPlugin::solve_fsm (Netlist * nl, const std::vector< Gate * > & state_reg, const std::vector< Gate * > & transition_logic, const std::map< Gate *, bool > & initial_state = {}, const std::string & graph_path = "", const u32 timeout = 600000) static
Generates the state graph of a finite state machine and returns a mapping from each state to a all its possible transitions. The transitions are another mapping from all the possible successor states to the corresponding condition under which the transition is taken. This function uses an SMT solver to find all possible successors and afterwards computes the necessary conditions.
Parameters
[in] nl - Pointer to the netlist.
[in] state_reg - A vector containing all the gates of the fsm representing the state register.
[in] transition_logic - A vector containing all the gates of the fsm representing the transition_logic.
[in] initial_state - A mapping from the state registers to their initial value. If omitted the intial state will be set to 0.
[in] graph_path - Path where the transition state graph in dot format is saved.
[in] timeout - Timeout value for the sat solvers. Defaults to 600000 ms.
Returns
A mapping from each state to all its possible transitions.
Definition at line 405 of file plugin_solve_fsm.cpp.
References hal::BooleanFunction::clone(), hal::BooleanFunction::Concat(), hal::BooleanFunction::Const(), hal::BooleanFunction::Eq(), ERR, ERR_APPEND, generate_dot_graph(), hal::BooleanFunctionNetDecorator::get_boolean_variable(), test_plugin::graph_path, test_plugin::initial_state, test::n, hal::BooleanFunction::Not(), OK, hal::SMT::Solver::query(), test_plugin::timeout, hal::BooleanFunction::to_u64(), hal::SMT::Solver::with_constraint(), hal::SMT::QueryConfig::with_model_generation(), and hal::SMT::QueryConfig::with_timeout().
Referenced by hal::PYBIND11_PLUGIN().
solve_fsm_brute_force()
Result< std::map< u64, std::map< u64, BooleanFunction > > > hal::SolveFsmPlugin::solve_fsm_brute_force (Netlist * nl, const std::vector< Gate * > & state_reg, const std::vector< Gate * > & transition_logic, const std::string & graph_path = "") static
Generates the state graph of a finite state machine and returns a mapping from each state to a all its possible transitions. The transitions are another mapping from all the possible successor states to the corresponding condition under which the transition is taken. This function uses a burte force search to find all possible successors and afterwards computes the necessary conditions.
Parameters
[in] nl - Pointer to the netlist.
[in] state_reg - A vector containing all the gates of the fsm representing the state register.
[in] transition_logic - A vector containing all the gates of the fsm representing the transition_logic.
[in] graph_path - Path where the transition state graph in dot format is saved.
Returns
A mapping from each state to all its possible transitions.
Definition at line 309 of file plugin_solve_fsm.cpp.
References hal::BooleanFunction::Concat(), hal::BooleanFunction::Const(), ERR, ERR_APPEND, generate_dot_graph(), hal::BooleanFunctionNetDecorator::get_boolean_variable_name(), test_plugin::graph_path, OK, hal::BooleanFunction::size(), hal::state, hal::BooleanFunction::substitute(), hal::BooleanFunction::to_u64(), and hal::utils::to_vector().
Referenced by hal::PYBIND11_PLUGIN().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/solve_fsm/include/solve_fsm/plugin_solve_fsm.h
/home/runner/work/hal/hal/plugins/solve_fsm/src/plugin_solve_fsm.cpp