HAL: hal::GuiPluginEntry Class Reference
hal::GuiPluginEntry Class Reference
#include <gui_plugin_manager.h>
Public Types
enum LoadState { NotAPlugin , NotLoaded , AutoLoad , UserLoad }
enum GuiExtensionState { Unknown , NotAnExtension , Disabled , Enabled }
Public Member Functions
GuiPluginEntry (const QFileInfo &info)
GuiPluginEntry (const QSettings *settings)
QVariant data (int icol) const
QString name () const
void persist (QSettings *settings) const
bool requestLoad () const
bool isLoaded () const
bool isPlugin () const
void updateFromLoaded (const BasePluginInterface *bpif, bool isUser, const QDateTime &modified=QDateTime())
bool isFileFound () const
void setFileFound (bool fnd)
GuiExtensionState enforceGuiExtensionState (GuiExtensionInterface *geif) const
Public Attributes
enum hal::GuiPluginEntry::LoadState mLoadState
QString mName
QString mVersion
QString mDescription
QString mFilePath
QString mExternalPath
QDateTime mFileModified
QStringList mDependencies
FacExtensionInterface::Feature mFeature
QStringList mFeatureArguments
bool mUserInterface
enum hal::GuiPluginEntry::GuiExtensionState mGuiExtensionState
QString mCliOptions
bool mFileFound
Friends
class GuiPluginTable
Detailed Description
Definition at line 51 of file gui_plugin_manager.h.
Member Enumeration Documentation
GuiExtensionState
enum hal::GuiPluginEntry::GuiExtensionState
Enumerator
Unknown
NotAnExtension
Disabled
Enabled
Definition at line 66 of file gui_plugin_manager.h.
LoadState
enum hal::GuiPluginEntry::LoadState
Enumerator
NotAPlugin
NotLoaded
AutoLoad
UserLoad
Definition at line 55 of file gui_plugin_manager.h.
Constructor & Destructor Documentation
GuiPluginEntry() [1/2]
hal::GuiPluginEntry::GuiPluginEntry (const QFileInfo & info)
Definition at line 926 of file gui_plugin_manager.cpp.
GuiPluginEntry() [2/2]
hal::GuiPluginEntry::GuiPluginEntry (const QSettings * settings)
Definition at line 1004 of file gui_plugin_manager.cpp.
References QString::fromStdString(), hal::plugin_manager::get_plugin_path(), mCliOptions, mDependencies, mDescription, mExternalPath, mFeature, mFeatureArguments, mFileModified, mFilePath, mGuiExtensionState, mLoadState, mName, mUserInterface, mVersion, QVariant::toBool(), QVariant::toDateTime(), QVariant::toInt(), QString::toStdString(), QVariant::toString(), QVariant::toStringList(), and QSettings::value().
Member Function Documentation
data()
QVariant hal::GuiPluginEntry::data (int icol) const
Definition at line 936 of file gui_plugin_manager.cpp.
References hal::FacExtensionInterface::FacGatelibParser, hal::FacExtensionInterface::FacGatelibWriter, hal::FacExtensionInterface::FacNetlistParser, hal::FacExtensionInterface::FacNetlistWriter, QFileInfo::fileName(), QString::isEmpty(), isLoaded(), QStringList::join(), mCliOptions, mDependencies, mDescription, mExternalPath, mFeature, mFeatureArguments, mFileModified, mFilePath, mGuiExtensionState, mLoadState, mName, mUserInterface, and QDateTime::toString().
enforceGuiExtensionState()
GuiPluginEntry::GuiExtensionState hal::GuiPluginEntry::enforceGuiExtensionState (GuiExtensionInterface * geif) const
Definition at line 969 of file gui_plugin_manager.cpp.
References Disabled, Enabled, hal::GuiExtensionInterface::is_contribution_enabled(), mGuiExtensionState, NotAnExtension, and hal::GuiExtensionInterface::set_contribution_enabled().
Referenced by updateFromLoaded().
isFileFound()
bool hal::GuiPluginEntry::isFileFound () const inline
Definition at line 80 of file gui_plugin_manager.h.
References mFileFound.
isLoaded()
bool hal::GuiPluginEntry::isLoaded () const inline
Definition at line 77 of file gui_plugin_manager.h.
References AutoLoad, mLoadState, and UserLoad.
Referenced by data(), hal::GuiPluginTable::handleButtonPressed(), hal::GuiPluginTable::loadFeature(), and hal::GuiPluginTable::neededBy().
isPlugin()
bool hal::GuiPluginEntry::isPlugin () const inline
Definition at line 78 of file gui_plugin_manager.h.
References mLoadState, and NotAPlugin.
name()
QString hal::GuiPluginEntry::name () const inline
Definition at line 74 of file gui_plugin_manager.h.
References mName.
Referenced by hal::GuiPluginDelegate::paint().
persist()
void hal::GuiPluginEntry::persist (QSettings * settings) const
Definition at line 988 of file gui_plugin_manager.cpp.
References mCliOptions, mDependencies, mDescription, mExternalPath, mFeature, mFeatureArguments, mFileModified, mGuiExtensionState, mLoadState, mName, mUserInterface, mVersion, and QSettings::setValue().
Referenced by hal::GuiPluginTable::persist().
requestLoad()
bool hal::GuiPluginEntry::requestLoad () const inline
Definition at line 76 of file gui_plugin_manager.h.
References mLoadState, and UserLoad.
setFileFound()
void hal::GuiPluginEntry::setFileFound (bool fnd) inline
Definition at line 81 of file gui_plugin_manager.h.
References mFileFound.
updateFromLoaded()
void hal::GuiPluginEntry::updateFromLoaded (const BasePluginInterface * bpif, bool isUser, const QDateTime & modified = QDateTime())
Definition at line 1022 of file gui_plugin_manager.cpp.
References QList::append(), AutoLoad, QList::clear(), QString::clear(), enforceGuiExtensionState(), QString::fromStdString(), hal::CliExtensionInterface::get_cli_options(), hal::BasePluginInterface::get_dependencies(), hal::BasePluginInterface::get_description(), hal::BasePluginInterface::get_extensions(), hal::BasePluginInterface::get_name(), hal::ProgramOptions::get_options_string(), hal::plugin_manager::get_plugin_features(), hal::BasePluginInterface::get_version(), QDateTime::isValid(), mCliOptions, mDependencies, mDescription, mFeature, mFeatureArguments, mFileModified, mGuiExtensionState, mLoadState, mName, mUserInterface, mVersion, NotAnExtension, Unknown, and UserLoad.
Referenced by hal::GuiPluginTable::addExternalPlugin(), and hal::GuiPluginTable::loadFeature().
Friends And Related Function Documentation
GuiPluginTable
friend class GuiPluginTable friend
Definition at line 54 of file gui_plugin_manager.h.
Member Data Documentation
mCliOptions
QString hal::GuiPluginEntry::mCliOptions
Definition at line 67 of file gui_plugin_manager.h.
Referenced by data(), GuiPluginEntry(), hal::GuiPluginTable::handleButtonPressed(), persist(), and updateFromLoaded().
mDependencies
QStringList hal::GuiPluginEntry::mDependencies
Definition at line 62 of file gui_plugin_manager.h.
Referenced by data(), GuiPluginEntry(), hal::GuiPluginTable::neededBy(), persist(), and updateFromLoaded().
mDescription
QString hal::GuiPluginEntry::mDescription
Definition at line 58 of file gui_plugin_manager.h.
Referenced by data(), GuiPluginEntry(), hal::GuiPluginTable::listFacFeature(), persist(), and updateFromLoaded().
mExternalPath
QString hal::GuiPluginEntry::mExternalPath
Definition at line 60 of file gui_plugin_manager.h.
Referenced by hal::GuiPluginTable::addExternalPlugin(), data(), GuiPluginEntry(), and persist().
mFeature
FacExtensionInterface::Feature hal::GuiPluginEntry::mFeature
Definition at line 63 of file gui_plugin_manager.h.
Referenced by data(), GuiPluginEntry(), hal::GuiPluginTable::listFacFeature(), hal::GuiPluginTable::loadFeature(), persist(), and updateFromLoaded().
mFeatureArguments
QStringList hal::GuiPluginEntry::mFeatureArguments
Definition at line 64 of file gui_plugin_manager.h.
Referenced by data(), GuiPluginEntry(), hal::GuiPluginTable::listFacFeature(), hal::GuiPluginTable::loadFeature(), persist(), and updateFromLoaded().
mFileFound
bool hal::GuiPluginEntry::mFileFound
Definition at line 68 of file gui_plugin_manager.h.
Referenced by isFileFound(), and setFileFound().
mFileModified
QDateTime hal::GuiPluginEntry::mFileModified
Definition at line 61 of file gui_plugin_manager.h.
Referenced by data(), GuiPluginEntry(), persist(), and updateFromLoaded().
mFilePath
QString hal::GuiPluginEntry::mFilePath
Definition at line 59 of file gui_plugin_manager.h.
Referenced by data(), GuiPluginEntry(), hal::GuiPluginTable::handleButtonPressed(), and hal::GuiPluginTable::loadFeature().
mGuiExtensionState
enum hal::GuiPluginEntry::GuiExtensionState hal::GuiPluginEntry::mGuiExtensionState
Referenced by data(), enforceGuiExtensionState(), GuiPluginEntry(), persist(), and updateFromLoaded().
mLoadState
enum hal::GuiPluginEntry::LoadState hal::GuiPluginEntry::mLoadState
Referenced by hal::GuiPluginTable::addExternalPlugin(), data(), GuiPluginEntry(), hal::GuiPluginTable::handleButtonPressed(), isLoaded(), isPlugin(), persist(), requestLoad(), and updateFromLoaded().
mName
QString hal::GuiPluginEntry::mName
Definition at line 56 of file gui_plugin_manager.h.
Referenced by hal::GuiPluginTable::addExternalPlugin(), data(), GuiPluginEntry(), hal::GuiPluginTable::handleButtonPressed(), hal::GuiPluginTable::loadFeature(), name(), hal::GuiPluginTable::neededBy(), persist(), and updateFromLoaded().
mUserInterface
bool hal::GuiPluginEntry::mUserInterface
Definition at line 65 of file gui_plugin_manager.h.
Referenced by data(), GuiPluginEntry(), persist(), and updateFromLoaded().
mVersion
QString hal::GuiPluginEntry::mVersion
Definition at line 57 of file gui_plugin_manager.h.
Referenced by GuiPluginEntry(), persist(), and updateFromLoaded().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/plugin_relay/gui_plugin_manager.h
/home/runner/work/hal/hal/plugins/gui/src/plugin_relay/gui_plugin_manager.cpp