HAL: subprocess::detail::Communication Class Reference
subprocess::detail::Communication Class Reference
#include <process.h>
Public Member Functions
Communication (Streams *stream)
void operator= (const Communication &)=delete
int send (const char *msg, size_t length)
int send (const std::vector< char > &msg)
std::pair< OutBuffer, ErrBuffer > communicate (const char *msg, size_t length)
std::pair< OutBuffer, ErrBuffer > communicate (const std::vector< char > &msg)
void set_out_buf_cap (size_t cap)
void set_err_buf_cap (size_t cap)
Detailed Description
A helper class to Streams. This takes care of management of communicating with the child process with the means of the correct file descriptor.
Definition at line 1051 of file process.h.
Constructor & Destructor Documentation
Communication()
subprocess::detail::Communication::Communication (Streams * stream) inline
Definition at line 1054 of file process.h.
Member Function Documentation
communicate() [1/2]
std::pair< OutBuffer, ErrBuffer > subprocess::detail::Communication::communicate (const char * msg, size_t length) inline
Definition at line 1856 of file process.h.
References subprocess::Buffer::add_cap(), subprocess::Buffer::buf, subprocess::detail::Streams::error(), subprocess::detail::Streams::error_, subprocess::detail::Streams::input(), subprocess::detail::Streams::input_, subprocess::Buffer::length, subprocess::detail::Streams::output(), and subprocess::detail::Streams::output_.
Referenced by communicate(), and subprocess::detail::Streams::communicate().
communicate() [2/2]
std::pair<OutBuffer, ErrBuffer> subprocess::detail::Communication::communicate (const std::vector< char > & msg) inline
Definition at line 1062 of file process.h.
References communicate().
operator=()
void subprocess::detail::Communication::operator= (const Communication &) delete
send() [1/2]
int subprocess::detail::Communication::send (const char * msg, size_t length) inline
Definition at line 1844 of file process.h.
References subprocess::detail::Streams::input().
Referenced by send(), and subprocess::detail::Streams::send().
send() [2/2]
int subprocess::detail::Communication::send (const std::vector< char > & msg) inline
Definition at line 1850 of file process.h.
References send().
set_err_buf_cap()
void subprocess::detail::Communication::set_err_buf_cap (size_t cap) inline
Definition at line 1066 of file process.h.
Referenced by subprocess::detail::Streams::set_err_buf_cap().
set_out_buf_cap()
void subprocess::detail::Communication::set_out_buf_cap (size_t cap) inline
Definition at line 1065 of file process.h.
Referenced by subprocess::detail::Streams::set_out_buf_cap().
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/include/hal_core/utilities/process.h