HAL: hal::PyCodeProvider Class Reference
hal::PyCodeProvider Class Reference
#include <py_code_provider.h>
Static Public Member Functions
static QString pyCodeGate (u32 gateId)
static QString pyCodeGateId (u32 gateId)
static QString pyCodeGateName (u32 gateId)
static QString pyCodeGateType (u32 gateId)
static QString pyCodeGateTypePinByName (u32 gateId, QString pin)
static QString pyCodeGateTypePinDirection (u32 gateId, QString pin)
static QString pyCodeGateTypePinType (u32 gateId, QString pin)
static QString pyCodeGateInputPins (u32 gateId)
static QString pyCodeGateOutputPins (u32 gateId)
static QString pyCodeProperties (u32 gateId)
static QString pyCodeGateLocation (u32 gateId)
static QString pyCodeGateModule (u32 gateId)
static QString pyCodeGateBooleanFunction (u32 gateId, QString booleanFunctionName)
static QString pyCodeGateAsyncSetResetBehavior (u32 gateId)
static QString pyCodeGateData (u32 gateId, QString category, QString key)
static QString pyCodeGateDataMap (u32 gateId)
static QString pyCodeStateComp (u32 gateId)
static QString pyCodeStateCompPosState (u32 gateId)
static QString pyCodeStateCompNegState (u32 gateId)
static QString pyCodeFFComp (u32 gateId)
static QString pyCodeFFCompClockFunc (u32 gateId)
static QString pyCodeFFCompNextStateFunc (u32 gateId)
static QString pyCodeFFCompAsyncSetFunc (u32 gateId)
static QString pyCodeFFCompAsyncResetFunc (u32 gateId)
static QString pyCodeFFCompSetResetBehav (u32 gateId)
static QString pyCodeLatchComp (u32 gateId)
static QString pyCodeLatchCompEnableFunc (u32 gateId)
static QString pyCodeLatchCompDataInFunc (u32 gateId)
static QString pyCodeLatchCompAsyncSetFunc (u32 gateId)
static QString pyCodeLatchCompAsyncResetFunc (u32 gateId)
static QString pyCodeLatchCompSetResetBehav (u32 gateId)
static QString pyCodeNet (u32 netId)
static QString pyCodeNetId (u32 netId)
static QString pyCodeNetName (u32 netId)
static QString pyCodeNetType (u32 netId)
static QString pyCodeNetSources (u32 netId)
static QString pyCodeNetDestinations (u32 netId)
static QString pyCodeNetData (u32 netId, QString category, QString key)
static QString pyCodeNetDataMap (u32 netId)
static QString pyCodeModule (u32 moduleId)
static QString pyCodeModuleId (u32 moduleId)
static QString pyCodeModuleName (u32 moduleId)
static QString pyCodeModuleType (u32 moduleId)
static QString pyCodeModuleModule (u32 moduleId)
static QString pyCodeModuleSubmodules (u32 moduleId)
static QString pyCodeModuleGates (u32 moduleId, bool recursively=false)
static QString pyCodeModuleNets (u32 moduleId)
static QString pyCodeModuleInputNets (u32 moduleId)
static QString pyCodeModuleOutputNets (u32 moduleId)
static QString pyCodeModuleInputPins (u32 moduleId)
static QString pyCodeModuleOutputPins (u32 moduleId)
static QString pyCodeModuleInternalNets (u32 moduleId)
static QString pyCodeModuleIsTopModule (u32 moduleId)
static QString pyCodeModuleData (u32 moduleId, QString category, QString key)
static QString pyCodeModuleDataMap (u32 moduleId)
static QString pyCodeModulePinGroup (u32 moduleId, u32 groupId)
static QString pyCodeModulePinGroups (u32 moduleId)
static QString pyCodeModulePinGroupName (u32 moduleId, u32 groupId)
static QString pyCodeModulePinById (u32 moduleId, u32 pinId)
static QString pyCodeModulePinName (u32 moduleId, u32 pinId)
static QString pyCodeModulePinDirection (u32 moduleId, u32 pinId)
static QString pyCodeModulePinType (u32 moduleId, u32 pinId)
static QString pyCodeModulePins (u32 moduleId)
static QString pyCodeGrouping (u32 groupingId)
static QString pyCodeGroupingName (u32 groupingId)
static QString pyCodeGroupingId (u32 groupingId)
Detailed Description
Definition at line 34 of file py_code_provider.h.
Member Function Documentation
pyCodeFFComp()
QString hal::PyCodeProvider::pyCodeFFComp (u32 gateId) static
Definition at line 124 of file py_code_provider.cpp.
References pyCodeGateType().
Referenced by pyCodeFFCompAsyncResetFunc(), pyCodeFFCompAsyncSetFunc(), pyCodeFFCompClockFunc(), pyCodeFFCompNextStateFunc(), and pyCodeFFCompSetResetBehav().
pyCodeFFCompAsyncResetFunc()
QString hal::PyCodeProvider::pyCodeFFCompAsyncResetFunc (u32 gateId) static
Definition at line 144 of file py_code_provider.cpp.
References pyCodeFFComp().
Referenced by hal::FFComponentEntry::getPythonCode().
pyCodeFFCompAsyncSetFunc()
QString hal::PyCodeProvider::pyCodeFFCompAsyncSetFunc (u32 gateId) static
Definition at line 139 of file py_code_provider.cpp.
References pyCodeFFComp().
Referenced by hal::FFComponentEntry::getPythonCode().
pyCodeFFCompClockFunc()
QString hal::PyCodeProvider::pyCodeFFCompClockFunc (u32 gateId) static
Definition at line 129 of file py_code_provider.cpp.
References pyCodeFFComp().
Referenced by hal::FFComponentEntry::getPythonCode().
pyCodeFFCompNextStateFunc()
QString hal::PyCodeProvider::pyCodeFFCompNextStateFunc (u32 gateId) static
Definition at line 134 of file py_code_provider.cpp.
References pyCodeFFComp().
Referenced by hal::FFComponentEntry::getPythonCode().
pyCodeFFCompSetResetBehav()
QString hal::PyCodeProvider::pyCodeFFCompSetResetBehav (u32 gateId) static
Definition at line 149 of file py_code_provider.cpp.
References pyCodeFFComp().
Referenced by hal::FFComponentEntry::getPythonCode().
pyCodeGate()
QString hal::PyCodeProvider::pyCodeGate (u32 gateId) static
Definition at line 23 of file py_code_provider.cpp.
References QString::arg().
Referenced by hal::ModuleElementsTree::handleContextMenuRequested().
pyCodeGateAsyncSetResetBehavior()
QString hal::PyCodeProvider::pyCodeGateAsyncSetResetBehavior (u32 gateId) static
Definition at line 85 of file py_code_provider.cpp.
References QString::arg(), hal::GateType::get_component_as(), hal::Netlist::get_gate_by_id(), hal::Gate::get_type(), hal::gNetlist, and pyCodeGateType().
pyCodeGateBooleanFunction()
QString hal::PyCodeProvider::pyCodeGateBooleanFunction (u32 gateId, QString booleanFunctionName) static
Definition at line 78 of file py_code_provider.cpp.
References QString::arg().
Referenced by hal::BooleanFunctionEntry::getPythonCode().
pyCodeGateData()
QString hal::PyCodeProvider::pyCodeGateData (u32 gateId, QString category, QString key) static
Definition at line 205 of file py_code_provider.cpp.
References QString::arg().
pyCodeGateDataMap()
QString hal::PyCodeProvider::pyCodeGateDataMap (u32 gateId) static
Definition at line 103 of file py_code_provider.cpp.
pyCodeGateId()
QString hal::PyCodeProvider::pyCodeGateId (u32 gateId) static
Definition at line 28 of file py_code_provider.cpp.
pyCodeGateInputPins()
QString hal::PyCodeProvider::pyCodeGateInputPins (u32 gateId) static
Definition at line 64 of file py_code_provider.cpp.
References pyCodeGateType().
pyCodeGateLocation()
QString hal::PyCodeProvider::pyCodeGateLocation (u32 gateId) static
Definition at line 191 of file py_code_provider.cpp.
pyCodeGateModule()
QString hal::PyCodeProvider::pyCodeGateModule (u32 gateId) static
Definition at line 198 of file py_code_provider.cpp.
pyCodeGateName()
QString hal::PyCodeProvider::pyCodeGateName (u32 gateId) static
Definition at line 35 of file py_code_provider.cpp.
pyCodeGateOutputPins()
QString hal::PyCodeProvider::pyCodeGateOutputPins (u32 gateId) static
Definition at line 71 of file py_code_provider.cpp.
References pyCodeGateType().
pyCodeGateType()
QString hal::PyCodeProvider::pyCodeGateType (u32 gateId) static
Definition at line 42 of file py_code_provider.cpp.
Referenced by pyCodeFFComp(), pyCodeGateAsyncSetResetBehavior(), pyCodeGateInputPins(), pyCodeGateOutputPins(), pyCodeGateTypePinByName(), pyCodeLatchComp(), and pyCodeStateComp().
pyCodeGateTypePinByName()
QString hal::PyCodeProvider::pyCodeGateTypePinByName (u32 gateId, QString pin) static
Definition at line 49 of file py_code_provider.cpp.
References QString::arg(), and pyCodeGateType().
Referenced by pyCodeGateTypePinDirection(), and pyCodeGateTypePinType().
pyCodeGateTypePinDirection()
QString hal::PyCodeProvider::pyCodeGateTypePinDirection (u32 gateId, QString pin) static
Definition at line 54 of file py_code_provider.cpp.
References pyCodeGateTypePinByName().
pyCodeGateTypePinType()
QString hal::PyCodeProvider::pyCodeGateTypePinType (u32 gateId, QString pin) static
Definition at line 59 of file py_code_provider.cpp.
References pyCodeGateTypePinByName().
pyCodeGrouping()
QString hal::PyCodeProvider::pyCodeGrouping (u32 groupingId) static
Definition at line 434 of file py_code_provider.cpp.
References QString::arg().
pyCodeGroupingId()
QString hal::PyCodeProvider::pyCodeGroupingId (u32 groupingId) static
Definition at line 446 of file py_code_provider.cpp.
pyCodeGroupingName()
QString hal::PyCodeProvider::pyCodeGroupingName (u32 groupingId) static
Definition at line 439 of file py_code_provider.cpp.
pyCodeLatchComp()
QString hal::PyCodeProvider::pyCodeLatchComp (u32 gateId) static
Definition at line 154 of file py_code_provider.cpp.
References pyCodeGateType().
Referenced by pyCodeLatchCompAsyncResetFunc(), pyCodeLatchCompAsyncSetFunc(), pyCodeLatchCompDataInFunc(), pyCodeLatchCompEnableFunc(), and pyCodeLatchCompSetResetBehav().
pyCodeLatchCompAsyncResetFunc()
QString hal::PyCodeProvider::pyCodeLatchCompAsyncResetFunc (u32 gateId) static
Definition at line 174 of file py_code_provider.cpp.
References pyCodeLatchComp().
Referenced by hal::LatchComponentEntry::getPythonCode().
pyCodeLatchCompAsyncSetFunc()
QString hal::PyCodeProvider::pyCodeLatchCompAsyncSetFunc (u32 gateId) static
Definition at line 169 of file py_code_provider.cpp.
References pyCodeLatchComp().
Referenced by hal::LatchComponentEntry::getPythonCode().
pyCodeLatchCompDataInFunc()
QString hal::PyCodeProvider::pyCodeLatchCompDataInFunc (u32 gateId) static
Definition at line 164 of file py_code_provider.cpp.
References pyCodeLatchComp().
Referenced by hal::LatchComponentEntry::getPythonCode().
pyCodeLatchCompEnableFunc()
QString hal::PyCodeProvider::pyCodeLatchCompEnableFunc (u32 gateId) static
Definition at line 159 of file py_code_provider.cpp.
References pyCodeLatchComp().
Referenced by hal::LatchComponentEntry::getPythonCode().
pyCodeLatchCompSetResetBehav()
QString hal::PyCodeProvider::pyCodeLatchCompSetResetBehav (u32 gateId) static
Definition at line 179 of file py_code_provider.cpp.
References pyCodeLatchComp().
Referenced by hal::LatchComponentEntry::getPythonCode().
pyCodeModule()
QString hal::PyCodeProvider::pyCodeModule (u32 moduleId) static
Definition at line 276 of file py_code_provider.cpp.
References QString::arg().
Referenced by hal::NetModuleTable::handleContextMenuRequested(), and hal::ModuleElementsTree::handleContextMenuRequested().
pyCodeModuleData()
QString hal::PyCodeProvider::pyCodeModuleData (u32 moduleId, QString category, QString key) static
Definition at line 373 of file py_code_provider.cpp.
References QString::arg().
pyCodeModuleDataMap()
QString hal::PyCodeProvider::pyCodeModuleDataMap (u32 moduleId) static
Definition at line 380 of file py_code_provider.cpp.
pyCodeModuleGates()
QString hal::PyCodeProvider::pyCodeModuleGates (u32 moduleId, bool recursively = false) static
Definition at line 317 of file py_code_provider.cpp.
References QString::arg(), and QString::number().
pyCodeModuleId()
QString hal::PyCodeProvider::pyCodeModuleId (u32 moduleId) static
Definition at line 281 of file py_code_provider.cpp.
pyCodeModuleInputNets()
QString hal::PyCodeProvider::pyCodeModuleInputNets (u32 moduleId) static
Definition at line 331 of file py_code_provider.cpp.
pyCodeModuleInputPins()
QString hal::PyCodeProvider::pyCodeModuleInputPins (u32 moduleId) static
Definition at line 345 of file py_code_provider.cpp.
pyCodeModuleInternalNets()
QString hal::PyCodeProvider::pyCodeModuleInternalNets (u32 moduleId) static
Definition at line 359 of file py_code_provider.cpp.
pyCodeModuleIsTopModule()
QString hal::PyCodeProvider::pyCodeModuleIsTopModule (u32 moduleId) static
Definition at line 366 of file py_code_provider.cpp.
pyCodeModuleModule()
QString hal::PyCodeProvider::pyCodeModuleModule (u32 moduleId) static
Definition at line 303 of file py_code_provider.cpp.
pyCodeModuleName()
QString hal::PyCodeProvider::pyCodeModuleName (u32 moduleId) static
Definition at line 288 of file py_code_provider.cpp.
pyCodeModuleNets()
QString hal::PyCodeProvider::pyCodeModuleNets (u32 moduleId) static
Definition at line 324 of file py_code_provider.cpp.
pyCodeModuleOutputNets()
QString hal::PyCodeProvider::pyCodeModuleOutputNets (u32 moduleId) static
Definition at line 338 of file py_code_provider.cpp.
pyCodeModuleOutputPins()
QString hal::PyCodeProvider::pyCodeModuleOutputPins (u32 moduleId) static
Definition at line 352 of file py_code_provider.cpp.
pyCodeModulePinById()
QString hal::PyCodeProvider::pyCodeModulePinById (u32 moduleId, u32 pinId) static
Definition at line 405 of file py_code_provider.cpp.
References QString::arg().
Referenced by hal::NetModuleTable::handleContextMenuRequested(), hal::ModulePinsTree::handleContextMenuRequested(), pyCodeModulePinDirection(), pyCodeModulePinName(), and pyCodeModulePinType().
pyCodeModulePinDirection()
QString hal::PyCodeProvider::pyCodeModulePinDirection (u32 moduleId, u32 pinId) static
Definition at line 417 of file py_code_provider.cpp.
References pyCodeModulePinById().
pyCodeModulePinGroup()
QString hal::PyCodeProvider::pyCodeModulePinGroup (u32 moduleId, u32 groupId) static
Definition at line 386 of file py_code_provider.cpp.
References QString::arg().
Referenced by hal::ModulePinsTree::handleContextMenuRequested(), and pyCodeModulePinGroupName().
pyCodeModulePinGroupName()
QString hal::PyCodeProvider::pyCodeModulePinGroupName (u32 moduleId, u32 groupId) static
Definition at line 400 of file py_code_provider.cpp.
References pyCodeModulePinGroup().
pyCodeModulePinGroups()
QString hal::PyCodeProvider::pyCodeModulePinGroups (u32 moduleId) static
Definition at line 393 of file py_code_provider.cpp.
pyCodeModulePinName()
QString hal::PyCodeProvider::pyCodeModulePinName (u32 moduleId, u32 pinId) static
Definition at line 412 of file py_code_provider.cpp.
References pyCodeModulePinById().
pyCodeModulePins()
QString hal::PyCodeProvider::pyCodeModulePins (u32 moduleId) static
Definition at line 427 of file py_code_provider.cpp.
pyCodeModulePinType()
QString hal::PyCodeProvider::pyCodeModulePinType (u32 moduleId, u32 pinId) static
Definition at line 422 of file py_code_provider.cpp.
References pyCodeModulePinById().
pyCodeModuleSubmodules()
QString hal::PyCodeProvider::pyCodeModuleSubmodules (u32 moduleId) static
Definition at line 310 of file py_code_provider.cpp.
pyCodeModuleType()
QString hal::PyCodeProvider::pyCodeModuleType (u32 moduleId) static
Definition at line 295 of file py_code_provider.cpp.
pyCodeNet()
QString hal::PyCodeProvider::pyCodeNet (u32 netId) static
Definition at line 212 of file py_code_provider.cpp.
References QString::arg().
pyCodeNetData()
QString hal::PyCodeProvider::pyCodeNetData (u32 netId, QString category, QString key) static
Definition at line 263 of file py_code_provider.cpp.
References QString::arg().
pyCodeNetDataMap()
QString hal::PyCodeProvider::pyCodeNetDataMap (u32 netId) static
Definition at line 270 of file py_code_provider.cpp.
pyCodeNetDestinations()
QString hal::PyCodeProvider::pyCodeNetDestinations (u32 netId) static
Definition at line 256 of file py_code_provider.cpp.
pyCodeNetId()
QString hal::PyCodeProvider::pyCodeNetId (u32 netId) static
Definition at line 217 of file py_code_provider.cpp.
pyCodeNetName()
QString hal::PyCodeProvider::pyCodeNetName (u32 netId) static
Definition at line 224 of file py_code_provider.cpp.
pyCodeNetSources()
QString hal::PyCodeProvider::pyCodeNetSources (u32 netId) static
Definition at line 249 of file py_code_provider.cpp.
pyCodeNetType()
QString hal::PyCodeProvider::pyCodeNetType (u32 netId) static
Definition at line 231 of file py_code_provider.cpp.
References QString::arg().
pyCodeProperties()
QString hal::PyCodeProvider::pyCodeProperties (u32 gateId) static
Definition at line 184 of file py_code_provider.cpp.
pyCodeStateComp()
QString hal::PyCodeProvider::pyCodeStateComp (u32 gateId) static
Definition at line 109 of file py_code_provider.cpp.
References pyCodeGateType().
Referenced by pyCodeStateCompNegState(), and pyCodeStateCompPosState().
pyCodeStateCompNegState()
QString hal::PyCodeProvider::pyCodeStateCompNegState (u32 gateId) static
Definition at line 119 of file py_code_provider.cpp.
References pyCodeStateComp().
Referenced by hal::StateComponentEntry::getPythonCode().
pyCodeStateCompPosState()
QString hal::PyCodeProvider::pyCodeStateCompPosState (u32 gateId) static
Definition at line 114 of file py_code_provider.cpp.
References pyCodeStateComp().
Referenced by hal::StateComponentEntry::getPythonCode().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/python/py_code_provider.h
/home/runner/work/hal/hal/plugins/gui/src/python/py_code_provider.cpp