HAL: hal::GuiExtensionInterface Class Reference
hal::GuiExtensionInterface Class Reference
#include <gui_extension_interface.h>
Public Member Functions
GuiExtensionInterface (const std::string &toplabel=std::string())
virtual ~GuiExtensionInterface ()
virtual std::vector< PluginParameter > get_parameter () const
virtual void set_parameter (const std::vector< PluginParameter > &params)
virtual void register_progress_indicator (std::function< void(int, const std::string &)> pif)
virtual std::vector< ContextMenuContribution > get_context_contribution (const Netlist *nl, const std::vector< u32 > &mods, const std::vector< u32 > &gats, const std::vector< u32 > &nets)
virtual void execute_function (std::string tag, Netlist *nl, const std::vector< u32 > &mods, const std::vector< u32 > &gats, const std::vector< u32 > &nets)
virtual void netlist_loaded (Netlist *nl)
virtual void netlist_about_to_close (Netlist *nl)
bool is_contribution_enabled () const
void set_contribution_enabled (bool enabled)
std::string contribution_top_label () const
Public Member Functions inherited from hal::AbstractExtensionInterface
AbstractExtensionInterface ()
virtual ~AbstractExtensionInterface ()
Detailed Description
Definition at line 46 of file gui_extension_interface.h.
Constructor & Destructor Documentation
GuiExtensionInterface()
hal::GuiExtensionInterface::GuiExtensionInterface (const std::string & toplabel = std::string()) inline
Definition at line 51 of file gui_extension_interface.h.
~GuiExtensionInterface()
virtual hal::GuiExtensionInterface::~GuiExtensionInterface () inline virtual
Definition at line 54 of file gui_extension_interface.h.
Member Function Documentation
contribution_top_label()
std::string hal::GuiExtensionInterface::contribution_top_label () const inline
Get top label for context menu contributions. If empty the plugin name will show as top label.
Returns
The label or empty if no label different from plugin name was provided for constructor.
Definition at line 134 of file gui_extension_interface.h.
Referenced by hal::GuiPluginManager::addPluginActions(), and hal::GuiPluginManager::addPluginSubmenus().
execute_function()
void hal::GuiExtensionInterface::execute_function (std::string tag, Netlist * nl, const std::vector< u32 > & mods, const std::vector< u32 > & gats, const std::vector< u32 > & nets) virtual
Call from GUI to execute function. This function gets called when user selected a plugin contribution (see get_context_contribution) in context menu of GUI graphical netlist view or when user clicked a push button in contributed plugin menu
Parameters
[in] tag - The function tagname (unique identifier)
[in] nl - The current netlist in GUI
[in] mods - List of selected modules
[in] gats - List of selected gates
[in] nets - List of selected nets
Reimplemented in hal::GuiExtensionDataflow.
Definition at line 18 of file gui_extension_interface.cpp.
Referenced by hal::PluginParameterDialog::accept().
get_context_contribution()
std::vector< ContextMenuContribution > hal::GuiExtensionInterface::get_context_contribution (const Netlist * nl, const std::vector< u32 > & mods, const std::vector< u32 > & gats, const std::vector< u32 > & nets) virtual
Contribution to context menu. This function gets called when a context menu in GUI graphical netlist view pops up. Plugins that want to add their own entries in context menu will return one ContextMenuContribution record per entry line.
Parameters
[in] nl - The current netlist in GUI
[in] mods - List of selected modules
[in] gats - List of selected gates
[in] nets - List of selected nets
Returns
Definition at line 10 of file gui_extension_interface.cpp.
Referenced by hal::GuiPluginManager::addPluginSubmenus().
get_parameter()
std::vector< PluginParameter > hal::GuiExtensionInterface::get_parameter () const virtual
Get list of configurable parameter
Returns
List of configurable parameter
Reimplemented in hal::GuiExtensionDataflow.
Definition at line 4 of file gui_extension_interface.cpp.
Referenced by hal::GuiPluginManager::addPluginActions().
is_contribution_enabled()
bool hal::GuiExtensionInterface::is_contribution_enabled () const inline
Check whether context menu contributions are enabled for this plugin
Returns
True if enabled, false otherwise
Definition at line 122 of file gui_extension_interface.h.
Referenced by hal::GuiPluginManager::addPluginActions(), hal::GuiPluginManager::addPluginSubmenus(), hal::GuiPluginEntry::enforceGuiExtensionState(), and hal::GuiPluginDelegate::paint().
netlist_about_to_close()
void hal::GuiExtensionInterface::netlist_about_to_close (Netlist * nl) virtual
Netlist about to close in GUI.
Parameters
[in] nl - The netlist.
Definition at line 27 of file gui_extension_interface.cpp.
netlist_loaded()
void hal::GuiExtensionInterface::netlist_loaded (Netlist * nl) virtual
Netlist loaded in GUI.
Parameters
[in] nl - The netlist.
Definition at line 25 of file gui_extension_interface.cpp.
Referenced by hal::GuiPluginManager::addPluginSubmenus().
register_progress_indicator()
void hal::GuiExtensionInterface::register_progress_indicator (std::function< void(int, const std::string &)> pif) virtual
Register function to indicate work progress when busy
Parameters
[in] pif - Progress Indicator Function to register
Reimplemented in hal::GuiExtensionDataflow.
Definition at line 6 of file gui_extension_interface.cpp.
set_contribution_enabled()
void hal::GuiExtensionInterface::set_contribution_enabled (bool enabled) inline
Set flag whether context menu contributions are enabled for this plugin
Parameters
[in] enabled - New value for context menu contribution flag
Definition at line 128 of file gui_extension_interface.h.
Referenced by hal::GuiPluginEntry::enforceGuiExtensionState().
set_parameter()
void hal::GuiExtensionInterface::set_parameter (const std::vector< PluginParameter > & params) virtual
Set values for configurable parameter
Parameters
[in] params - List of configurable parameter with values
Reimplemented in hal::GuiExtensionDataflow.
Definition at line 8 of file gui_extension_interface.cpp.
Referenced by hal::PluginParameterDialog::accept(), and hal::dataflow::Result::open_dot_in_viewer().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/include/hal_core/plugin_system/gui_extension_interface.h
/home/runner/work/hal/hal/src/plugin_system/gui_extension_interface.cpp