HAL: hal::WaitToBeSeatedEntry Class Reference
hal::WaitToBeSeatedEntry Class Reference
HAL Gui » Graph Widget » Layouters
#include <wait_to_be_seated.h>
Public Member Functions
WaitToBeSeatedEntry (Node::NodeType t=Node::Module, u32 id=0)
Node getNode () const
u32 getId () const
QString tagName () const
bool isModule () const
double distance (const QPoint &pos, double defaultDistance) const
Static Public Member Functions
static int distance (const QPoint &source, const QPoint &pos)
Friends
class WaitToBeSeatedList
class WaitToBeSeatedWaiting
Detailed Description
Definition at line 42 of file wait_to_be_seated.h.
Constructor & Destructor Documentation
WaitToBeSeatedEntry()
hal::WaitToBeSeatedEntry::WaitToBeSeatedEntry (Node::NodeType t = Node::Module, u32 id = 0)
Definition at line 14 of file wait_to_be_seated.cpp.
Member Function Documentation
distance() [1/2]
double hal::WaitToBeSeatedEntry::distance (const QPoint & pos, double defaultDistance) const
Definition at line 71 of file wait_to_be_seated.cpp.
References getId(), and source.
distance() [2/2]
int hal::WaitToBeSeatedEntry::distance (const QPoint & source, const QPoint & pos) static
Definition at line 92 of file wait_to_be_seated.cpp.
References source, QPoint::x(), and QPoint::y().
getId()
u32 hal::WaitToBeSeatedEntry::getId () const inline
Definition at line 57 of file wait_to_be_seated.h.
References hal::Node::id().
Referenced by hal::WaitToBeSeatedList::add(), hal::compareWaitToBeSeated(), distance(), hal::WaitToBeSeatedList::dump(), and tagName().
getNode()
Node hal::WaitToBeSeatedEntry::getNode () const inline
Definition at line 56 of file wait_to_be_seated.h.
isModule()
bool hal::WaitToBeSeatedEntry::isModule () const
Definition at line 60 of file wait_to_be_seated.cpp.
References hal::Node::id(), and hal::Node::isModule().
Referenced by hal::WaitToBeSeatedList::add(), hal::WaitToBeSeatedList::dump(), and tagName().
tagName()
QString hal::WaitToBeSeatedEntry::tagName () const
Definition at line 55 of file wait_to_be_seated.cpp.
References QString::arg(), getId(), and isModule().
Referenced by hal::WaitToBeSeatedList::dump().
Friends And Related Function Documentation
WaitToBeSeatedList
friend class WaitToBeSeatedList friend
Definition at line 44 of file wait_to_be_seated.h.
WaitToBeSeatedWaiting
friend class WaitToBeSeatedWaiting friend
Definition at line 45 of file wait_to_be_seated.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/wait_to_be_seated.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/wait_to_be_seated.cpp