HAL: hal::CodeEditor Class Reference
hal::CodeEditor Class Reference
HAL Gui » Python » Python Editor
A plain text edit widget that is intended for editing code.
#include <code_editor.h>
Public Slots
void search (const QString &string, QTextDocument::FindFlags options=QTextDocument::FindFlags())
void toggleLineNumbers ()
void toggleMinimap ()
void setFontSize (int pt)
Public Member Functions
CodeEditor (QWidget *parent=nullptr)
virtual bool eventFilter (QObject *object, QEvent *event) override
void lineNumberAreaPaintEvent (QPaintEvent *event)
void minimapPaintEvent (QPaintEvent *event)
int lineNumberAreaWidth ()
int minimapWidth ()
int first_visible_block ()
void centerOnLine (const int number)
void handleWheelEvent (QWheelEvent *event)
CodeEditorMinimap * minimap ()
void setLineNumberEnabled (bool enabled)
void setHighlightCurrentLineEnabled (bool enabled)
void setLineWrapEnabled (bool enabled)
void setMinimapEnabled (bool enabled)
Q_PROPERTY READ Functions
QFont lineNumberFont () const
QColor lineNumberColor () const
QColor lineNumberBackground () const
QColor lineNumberHighlightColor () const
QColor lineNumberHighlightBackground () const
QColor currentLineBackground () const
Q_PROPERTY WRITE Functions
void setLineNumberFont (const QFont &font)
void setLineNumberColor (QColor &color)
void setLineNumberBackground (QColor &color)
void setLineNumberHighlightColor (QColor &color)
void setLineNumberHighlightBackground (QColor &color)
void setCurrentLineBackground (QColor &color)
Public Member Functions inherited from QPlainTextEdit
QPlainTextEdit (QWidget *parent)
QPlainTextEdit (const QString &text, QWidget *parent)
virtual ~QPlainTextEdit ()
void setDocument (QTextDocument *document)
QTextDocument * document () const const
void setPlaceholderText (const QString &placeholderText)
QString placeholderText () const const
void setTextCursor (const QTextCursor &cursor)
QTextCursor textCursor () const const
bool isReadOnly () const const
void setReadOnly (bool ro)
void setTextInteractionFlags (Qt::TextInteractionFlags flags)
Qt::TextInteractionFlags textInteractionFlags () const const
void mergeCurrentCharFormat (const QTextCharFormat &modifier)
void setCurrentCharFormat (const QTextCharFormat &format)
QTextCharFormat currentCharFormat () const const
bool tabChangesFocus () const const
void setTabChangesFocus (bool b)
void setDocumentTitle (const QString &title)
QString documentTitle () const const
bool isUndoRedoEnabled () const const
void setUndoRedoEnabled (bool enable)
void setMaximumBlockCount (int maximum)
int maximumBlockCount () const const
QPlainTextEdit::LineWrapMode lineWrapMode () const const
void setLineWrapMode (QPlainTextEdit::LineWrapMode mode)
QTextOption::WrapMode wordWrapMode () const const
void setWordWrapMode (QTextOption::WrapMode policy)
void setBackgroundVisible (bool visible)
bool backgroundVisible () const const
void setCenterOnScroll (bool enabled)
bool centerOnScroll () const const
bool find (const QString &exp, QTextDocument::FindFlags options)
bool find (const QRegExp &exp, QTextDocument::FindFlags options)
bool find (const QRegularExpression &exp, QTextDocument::FindFlags options)
QString toPlainText () const const
void ensureCursorVisible ()
virtual QVariant loadResource (int type, const QUrl &name)
QMenu * createStandardContextMenu ()
QMenu * createStandardContextMenu (const QPoint &position)
QTextCursor cursorForPosition (const QPoint &pos) const const
QRect cursorRect (const QTextCursor &cursor) const const
QRect cursorRect () const const
QString anchorAt (const QPoint &pos) const const
bool overwriteMode () const const
void setOverwriteMode (bool overwrite)
int tabStopWidth () const const
void setTabStopWidth (int width)
qreal tabStopDistance () const const
void setTabStopDistance (qreal distance)
int cursorWidth () const const
void setCursorWidth (int width)
void setExtraSelections (const QList< QTextEdit::ExtraSelection > &selections)
QList< QTextEdit::ExtraSelection > extraSelections () const const
void moveCursor (QTextCursor::MoveOperation operation, QTextCursor::MoveMode mode)
bool canPaste () const const
void print (QPagedPaintDevice *printer) const const
int blockCount () const const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery property) const const override
void setPlainText (const QString &text)
void cut ()
void copy ()
void paste ()
void undo ()
void redo ()
void clear ()
void selectAll ()
void insertPlainText (const QString &text)
void appendPlainText (const QString &text)
void appendHtml (const QString &html)
void centerCursor ()
void zoomIn (int range)
void zoomOut (int range)
void textChanged ()
void undoAvailable (bool available)
void redoAvailable (bool available)
void copyAvailable (bool yes)
void selectionChanged ()
void cursorPositionChanged ()
void updateRequest (const QRect &rect, int dy)
void blockCountChanged (int newBlockCount)
void modificationChanged (bool changed)
Public Member Functions inherited from QAbstractScrollArea
QAbstractScrollArea (QWidget *parent)
virtual ~QAbstractScrollArea ()
Qt::ScrollBarPolicy verticalScrollBarPolicy () const const
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
QScrollBar * verticalScrollBar () const const
void setVerticalScrollBar (QScrollBar *scrollBar)
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const const
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
QScrollBar * horizontalScrollBar () const const
void setHorizontalScrollBar (QScrollBar *scrollBar)
QWidget * cornerWidget () const const
void setCornerWidget (QWidget *widget)
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
QWidget * viewport () const const
void setViewport (QWidget *widget)
QSize maximumViewportSize () const const
virtual QSize minimumSizeHint () const const override
virtual QSize sizeHint () const const override
virtual void setupViewport (QWidget *viewport)
QAbstractScrollArea::SizeAdjustPolicy sizeAdjustPolicy () const const
void setSizeAdjustPolicy (QAbstractScrollArea::SizeAdjustPolicy policy)
Public Member Functions inherited from QFrame
QFrame (QWidget *parent, Qt::WindowFlags f)
virtual ~QFrame ()
int frameStyle () const const
void setFrameStyle (int style)
int frameWidth () const const
QFrame::Shape frameShape () const const
void setFrameShape (QFrame::Shape)
QFrame::Shadow frameShadow () const const
void setFrameShadow (QFrame::Shadow)
int lineWidth () const const
void setLineWidth (int)
int midLineWidth () const const
void setMidLineWidth (int)
QRect frameRect () const const
void setFrameRect (const QRect &)
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
virtual void setVisible (bool visible)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Protected Member Functions
virtual void resizeEvent (QResizeEvent *event) override
Protected Member Functions inherited from QPlainTextEdit
virtual void keyPressEvent (QKeyEvent *e) override
virtual void keyReleaseEvent (QKeyEvent *e) override
virtual void paintEvent (QPaintEvent *e) override
virtual void mousePressEvent (QMouseEvent *e) override
virtual void mouseMoveEvent (QMouseEvent *e) override
virtual void mouseReleaseEvent (QMouseEvent *e) override
virtual void mouseDoubleClickEvent (QMouseEvent *e) override
virtual bool focusNextPrevChild (bool next) override
virtual void contextMenuEvent (QContextMenuEvent *event) override
virtual void dragEnterEvent (QDragEnterEvent *e) override
virtual void dragLeaveEvent (QDragLeaveEvent *e) override
virtual void dragMoveEvent (QDragMoveEvent *e) override
virtual void dropEvent (QDropEvent *e) override
virtual void focusInEvent (QFocusEvent *e) override
virtual void focusOutEvent (QFocusEvent *e) override
virtual void showEvent (QShowEvent *) override
virtual void changeEvent (QEvent *e) override
virtual void wheelEvent (QWheelEvent *e) override
virtual QMimeData * createMimeDataFromSelection () const const
virtual bool canInsertFromMimeData (const QMimeData *source) const const
virtual void insertFromMimeData (const QMimeData *source)
virtual void inputMethodEvent (QInputMethodEvent *e) override
virtual void scrollContentsBy (int dx, int dy) override
QTextBlock firstVisibleBlock () const const
QPointF contentOffset () const const
QRectF blockBoundingRect (const QTextBlock &block) const const
QRectF blockBoundingGeometry (const QTextBlock &block) const const
QAbstractTextDocumentLayout::PaintContext getPaintContext () const const
Protected Member Functions inherited from QAbstractScrollArea
void setViewportMargins (int left, int top, int right, int bottom)
void setViewportMargins (const QMargins &margins)
QMargins viewportMargins () const const
virtual bool event (QEvent *event) override
virtual bool viewportEvent (QEvent *event)
virtual QSize viewportSizeHint () const const
Protected Member Functions inherited from QFrame
void initStyleOption (QStyleOptionFrame *option) const const
Protected Member Functions inherited from QWidget
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void closeEvent (QCloseEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Properties
QFont lineNumberFont
QColor lineNumberColor
QColor lineNumberBackground
QColor lineNumberHighlightColor
QColor lineNumberHighlightBackground
QColor currentLineBackground
Properties inherited from QPlainTextEdit
tabChangesFocus
documentTitle
undoRedoEnabled
lineWrapMode
wordWrapMode
readOnly
plainText
overwriteMode
tabStopWidth
tabStopDistance
cursorWidth
textInteractionFlags
blockCount
maximumBlockCount
backgroundVisible
centerOnScroll
placeholderText
Properties inherited from QAbstractScrollArea
verticalScrollBarPolicy
horizontalScrollBarPolicy
sizeAdjustPolicy
Properties inherited from QFrame
frameShape
frameShadow
lineWidth
midLineWidth
frameWidth
frameRect
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Additional Inherited Members
Public Types inherited from QPlainTextEdit
enum LineWrapMode
Public Types inherited from QAbstractScrollArea
enum SizeAdjustPolicy
Public Types inherited from QFrame
enum Shape
enum Shadow
enum StyleMask
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QPlainTextEdit
NoWrap
WidgetWidth
Public Attributes inherited from QAbstractScrollArea
AdjustIgnored
AdjustToContentsOnFirstShow
AdjustToContents
Public Attributes inherited from QFrame
NoFrame
Box
Panel
WinPanel
HLine
VLine
StyledPanel
Plain
Raised
Sunken
Shadow_Mask
Shape_Mask
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Detailed Description
A plain text edit widget that is intended for editing code.
Therefore it has numbered lines and provides a code minimap for easier navigation in larger files. Moreover it supports a search function to mark all occurrences of a specified string.
Definition at line 48 of file code_editor.h.
Constructor & Destructor Documentation
CodeEditor()
hal::CodeEditor::CodeEditor (QWidget * parent = nullptr) explicit
Constructor.
Parameters
parent - The parent widget
Definition at line 17 of file code_editor.cpp.
References QPlainTextEdit::blockCountChanged(), QObject::connect(), QPlainTextEdit::cursorPositionChanged(), QPlainTextEdit::document(), QWidget::ensurePolished(), QAbstractScrollArea::horizontalScrollBar(), QObject::installEventFilter(), Qt::NoContextMenu, QFrame::NoFrame, QPlainTextEdit::NoWrap, hal::CodeEditorMinimap::scrollbar(), QWidget::setContextMenuPolicy(), QTextDocument::setDocumentMargin(), QVariantAnimation::setDuration(), QFrame::setFrameStyle(), QPlainTextEdit::setLineWrapMode(), hal::CodeEditorScrollbar::setMinimapScrollbar(), hal::MinimapScrollbar::setScrollbar(), QAbstractScrollArea::setVerticalScrollBar(), QPlainTextEdit::updateRequest(), and QPlainTextEdit::WidgetWidth.
Member Function Documentation
centerOnLine()
void hal::CodeEditor::centerOnLine (const int number)
Scrolls to the specified line number using a scroll animation.
Parameters
number - The number to scroll to
Definition at line 235 of file code_editor.cpp.
References QPlainTextEdit::document(), QTextDocument::lineCount(), QAbstractAnimation::Running, QVariantAnimation::setEndValue(), QVariantAnimation::setStartValue(), QAbstractAnimation::start(), QAbstractAnimation::state, QAbstractAnimation::stop(), and QAbstractScrollArea::verticalScrollBar().
Referenced by hal::CodeEditorMinimap::mousePressEvent().
currentLineBackground()
QColor hal::CodeEditor::currentLineBackground () const
eventFilter()
bool hal::CodeEditor::eventFilter (QObject * object, QEvent * event) override virtual
Captures the mouse scroll event to zoom in and out via CTRL+SCROLL UP/DOWN.
Parameters
object - The object this filter is applied on.
event - The event to filter
Returns
true if the event is handled by this filter and shouldn't be processed any further by the target object. Returns false to pass the event to the target object.
Reimplemented from QObject.
Definition at line 56 of file code_editor.cpp.
References Qt::ControlModifier, QWheelEvent::delta(), QAbstractScrollArea::event(), QInputEvent::modifiers(), QEvent::Wheel, QPlainTextEdit::zoomIn(), and QPlainTextEdit::zoomOut().
first_visible_block()
int hal::CodeEditor::first_visible_block ()
Returns the index of the first visible block.
Returns
the index of the first visible block
Definition at line 230 of file code_editor.cpp.
References QTextBlock::blockNumber(), and QPlainTextEdit::firstVisibleBlock().
Referenced by hal::CodeEditorMinimap::paintEvent().
handleWheelEvent()
void hal::CodeEditor::handleWheelEvent (QWheelEvent * event)
This function can be used to pass a wheel event to the code editor. It is necessary for widgets that are associated with the code editor but are not part of it (e.g. the line number area or the minimap).
Parameters
event - The wheel event to pass to the code editor
Definition at line 257 of file code_editor.cpp.
References QAbstractScrollArea::event(), and QPlainTextEdit::wheelEvent().
Referenced by hal::LineNumberArea::wheelEvent(), and hal::CodeEditorMinimap::wheelEvent().
lineNumberAreaPaintEvent()
void hal::CodeEditor::lineNumberAreaPaintEvent (QPaintEvent * event)
Paint event handler to paint the line numbers. This function is called when an paint event of the line number area occurs. It draws the necessary line numbers in the line number area.
Parameters
event - The paint event
Definition at line 77 of file code_editor.cpp.
References Qt::AlignRight, Qt::AlignVCenter, QPlainTextEdit::blockBoundingGeometry(), QTextBlock::blockNumber(), hal::bottom, QPlainTextEdit::contentOffset(), QPainter::drawText(), QPlainTextEdit::firstVisibleBlock(), QRectF::height(), QWidget::height, QTextBlock::isValid(), QTextBlock::isVisible(), QTextBlock::next(), QString::number(), hal::LineNumberArea::rightOffset, QPen::setColor(), QPainter::setFont(), QPainter::setPen(), QRectF::top(), QRectF::translated(), and QWidget::width.
Referenced by hal::LineNumberArea::paintEvent().
lineNumberAreaWidth()
int hal::CodeEditor::lineNumberAreaWidth ()
Gets the width of area where the line numbers are drawn.
Returns
the line number area width.
Definition at line 113 of file code_editor.cpp.
References QPlainTextEdit::blockCount, hal::LineNumberArea::leftOffset, QString::number(), hal::LineNumberArea::rightOffset, and QFontMetrics::width().
lineNumberBackground()
QColor hal::CodeEditor::lineNumberBackground () const
lineNumberColor()
QColor hal::CodeEditor::lineNumberColor () const
lineNumberFont()
QFont hal::CodeEditor::lineNumberFont () const
lineNumberHighlightBackground()
QColor hal::CodeEditor::lineNumberHighlightBackground () const
lineNumberHighlightColor()
QColor hal::CodeEditor::lineNumberHighlightColor () const
minimap()
CodeEditorMinimap * hal::CodeEditor::minimap ()
Accesses the code editors minimap.
Returns
the code editors minimap.
Definition at line 262 of file code_editor.cpp.
Referenced by hal::PythonEditor::handleActionNewTab().
minimapPaintEvent()
void hal::CodeEditor::minimapPaintEvent (QPaintEvent * event)
Paint event handler to paint the line numbers.
Parameters
event - The paint event
Definition at line 106 of file code_editor.cpp.
References QAbstractScrollArea::event().
minimapWidth()
int hal::CodeEditor::minimapWidth ()
Gets the width of the minimap.
Returns
the width of the minimap.
Definition at line 120 of file code_editor.cpp.
resizeEvent()
void hal::CodeEditor::resizeEvent (QResizeEvent * event) override protected virtual
Captures the resize event to adjust the slider size of the minimap.
Parameters
event - The resize event
Reimplemented from QPlainTextEdit.
Definition at line 125 of file code_editor.cpp.
References hal::CodeEditorMinimap::adjustSliderHeight(), QPlainTextEdit::blockBoundingGeometry(), QPlainTextEdit::document(), QAbstractScrollArea::event(), QRectF::height(), QWidget::height, QPlainTextEdit::resizeEvent(), and QAbstractScrollArea::viewport().
search
void hal::CodeEditor::search (const QString & string, QTextDocument::FindFlags options = QTextDocument::FindFlags()) slot
Marks all occurrences of the specified string in the code editor.
Parameters
string - The string to mark
options - Optional QTextDocument::FindFlags (e.g. "FindCaseSensitively" or "FindWholeWords")
Definition at line 199 of file code_editor.cpp.
References QPlainTextEdit::extraSelections(), QPlainTextEdit::find(), QPlainTextEdit::moveCursor(), QPlainTextEdit::setExtraSelections(), QTextCursor::Start, and QPlainTextEdit::textCursor().
Referenced by hal::PythonEditor::handleCurrentTabChanged().
setCurrentLineBackground()
void hal::CodeEditor::setCurrentLineBackground (QColor & color)
Definition at line 322 of file code_editor.cpp.
setFontSize
void hal::CodeEditor::setFontSize (int pt) slot
Configures the font size of the code editor.
Parameters
pt - The new font size
Definition at line 250 of file code_editor.cpp.
References QWidget::font, and QWidget::setFont().
Referenced by hal::PythonEditor::handleActionNewTab().
setHighlightCurrentLineEnabled()
void hal::CodeEditor::setHighlightCurrentLineEnabled (bool enabled)
Enables or disables the highlight of the current line.
Parameters
enabled - True to enable, False to disable.
Definition at line 361 of file code_editor.cpp.
References QObject::connect(), QPlainTextEdit::cursorPositionChanged(), QObject::disconnect(), and QWidget::enabled.
Referenced by hal::PythonEditor::handleActionNewTab().
setLineNumberBackground()
void hal::CodeEditor::setLineNumberBackground (QColor & color)
Definition at line 307 of file code_editor.cpp.
setLineNumberColor()
void hal::CodeEditor::setLineNumberColor (QColor & color)
Definition at line 302 of file code_editor.cpp.
setLineNumberEnabled()
void hal::CodeEditor::setLineNumberEnabled (bool enabled)
Enables or disables the line numbers.
Parameters
enabled - True to enable, False to disable.
Definition at line 355 of file code_editor.cpp.
References QWidget::enabled.
Referenced by hal::PythonEditor::handleActionNewTab().
setLineNumberFont()
void hal::CodeEditor::setLineNumberFont (const QFont & font)
Definition at line 297 of file code_editor.cpp.
References QWidget::font.
setLineNumberHighlightBackground()
void hal::CodeEditor::setLineNumberHighlightBackground (QColor & color)
Definition at line 317 of file code_editor.cpp.
setLineNumberHighlightColor()
void hal::CodeEditor::setLineNumberHighlightColor (QColor & color)
Definition at line 312 of file code_editor.cpp.
setLineWrapEnabled()
void hal::CodeEditor::setLineWrapEnabled (bool enabled)
Enables or disables the linewrap.
Parameters
enabled - True to enable, False to disable.
Definition at line 379 of file code_editor.cpp.
References QWidget::enabled, QPlainTextEdit::NoWrap, QPlainTextEdit::setLineWrapMode(), and QPlainTextEdit::WidgetWidth.
Referenced by hal::PythonEditor::handleActionNewTab().
setMinimapEnabled()
void hal::CodeEditor::setMinimapEnabled (bool enabled)
Enables or disables the minimap.
Parameters
enabled - True to enable, False to disable.
Definition at line 386 of file code_editor.cpp.
References QWidget::enabled.
Referenced by hal::PythonEditor::handleActionNewTab().
toggleLineNumbers
void hal::CodeEditor::toggleLineNumbers () slot
Shows/Hides the line numbers at the left side of the code editor.
Definition at line 218 of file code_editor.cpp.
toggleMinimap
void hal::CodeEditor::toggleMinimap () slot
Shows/Hides the minimap of the code editor.
Definition at line 224 of file code_editor.cpp.
Property Documentation
currentLineBackground
QColor hal::CodeEditor::currentLineBackground read write
Definition at line 56 of file code_editor.h.
lineNumberBackground
QColor hal::CodeEditor::lineNumberBackground read write
Definition at line 53 of file code_editor.h.
lineNumberColor
QColor hal::CodeEditor::lineNumberColor read write
Definition at line 52 of file code_editor.h.
lineNumberFont
QFont hal::CodeEditor::lineNumberFont read write
Definition at line 51 of file code_editor.h.
lineNumberHighlightBackground
QColor hal::CodeEditor::lineNumberHighlightBackground read write
Definition at line 55 of file code_editor.h.
lineNumberHighlightColor
QColor hal::CodeEditor::lineNumberHighlightColor read write
Definition at line 54 of file code_editor.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/code_editor/code_editor.h
/home/runner/work/hal/hal/plugins/gui/src/code_editor/code_editor.cpp