HAL: hal::plugin_dataflow Class Reference
hal::plugin_dataflow Class Reference
#include <plugin_dataflow.h>
Public Member Functions
plugin_dataflow ()=default
~plugin_dataflow ()=default
std::string get_name () const override
std::string get_version () const override
ProgramOptions get_cli_options () const override
bool handle_cli_call (Netlist *nl, ProgramArguments &args) override
std::vector< std::vector< Gate * > > execute (Netlist *nl, std::string path, const std::vector< u32 > sizes, bool draw_graph, bool create_modules=false, bool register_stage_identification=false, std::vector< std::vector< u32 >> known_groups={}, u32 bad_group_size=7)
std::vector< PluginParameter > get_parameter () const override
void set_parameter (Netlist *nl, const std::vector< PluginParameter > &params) override
virtual void register_progress_indicator (std::function< void(int, const std::string &)> pif) override
Public Member Functions inherited from hal::CLIPluginInterface
CLIPluginInterface ()=default
virtual ~CLIPluginInterface ()=default
Public Member Functions inherited from hal::BasePluginInterface
BasePluginInterface ()=default
virtual ~BasePluginInterface ()=default
virtual void initialize ()
bool has_type (PluginInterfaceType t) const
template<typename... Args>
void log (const Args &... args) const
virtual std::set< std::string > get_dependencies () const
virtual void on_load ()
virtual void on_unload ()
virtual void initialize_logging ()
Static Public Attributes
static std::function< void(int, const std::string &)> s_progress_indicator_function = nullptr
Detailed Description
Definition at line 38 of file plugin_dataflow.h.
Constructor & Destructor Documentation
plugin_dataflow()
hal::plugin_dataflow::plugin_dataflow () default
~plugin_dataflow()
hal::plugin_dataflow::~plugin_dataflow () default
Member Function Documentation
execute()
std::vector< std::vector< Gate * > > hal::plugin_dataflow::execute (Netlist * nl, std::string path, const std::vector< u32 > sizes, bool draw_graph, bool create_modules = false, bool register_stage_identification = false, std::vector< std::vector< u32 >> known_groups = {}, u32 bad_group_size = 7)
Definition at line 187 of file plugin_dataflow.cpp.
References hal::dataflow::evaluation::Configuration::bad_group_size, hal::Netlist::copy(), hal::dataflow::dot_graph::create_graph(), hal::dataflow::state_to_module::create_modules(), hal::dataflow::state_to_module::create_sets(), hal::Netlist::get_design_name(), hal::utils::join(), hal::BasePluginInterface::log(), log_error, log_info, log_warning, hal::dataflow::processing::Configuration::num_threads, hal::dataflow::processing::Configuration::pass_layers, hal::dataflow::evaluation::Configuration::prioritized_sizes, hal::dataflow::processing::run(), hal::dataflow::pre_processing::run(), hal::dataflow::evaluation::run(), s_progress_indicator_function, hal::dataflow::json_output::save_state_to_json(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::size(), nlohmann::to_string(), and hal::dataflow::textual_output::write_register_output().
Referenced by handle_cli_call(), hal::PYBIND11_PLUGIN(), and set_parameter().
get_cli_options()
ProgramOptions hal::plugin_dataflow::get_cli_options () const override virtual
interface implementation: i_cli
Implements hal::CLIPluginInterface.
Definition at line 52 of file plugin_dataflow.cpp.
References hal::ProgramOptions::add().
get_name()
std::string hal::plugin_dataflow::get_name () const override virtual
Get the name of the plugin.
Returns
The name of the plugin.
Implements hal::BasePluginInterface.
Definition at line 42 of file plugin_dataflow.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_parameter()
std::vector< PluginParameter > hal::plugin_dataflow::get_parameter () const override virtual
Get list of configurable parameter
Returns
list of parameter
Reimplemented from hal::BasePluginInterface.
Definition at line 114 of file plugin_dataflow.cpp.
References hal::PluginParameter::Boolean, hal::PluginParameter::ExistingDir, hal::PluginParameter::Integer, hal::PluginParameter::PushButton, and hal::PluginParameter::String.
get_version()
std::string hal::plugin_dataflow::get_version () const override virtual
Get the version of the plugin.
Returns
The version of the plugin.
Implements hal::BasePluginInterface.
Definition at line 47 of file plugin_dataflow.cpp.
Referenced by hal::PYBIND11_PLUGIN().
handle_cli_call()
bool hal::plugin_dataflow::handle_cli_call (Netlist * nl, ProgramArguments & args) override virtual
interface implementation: i_cli
Implements hal::CLIPluginInterface.
Definition at line 67 of file plugin_dataflow.cpp.
References control::args, execute(), log_error, and UNUSED.
register_progress_indicator()
void hal::plugin_dataflow::register_progress_indicator (std::function< void(int, const std::string &)> pif) override virtual
Register function to indicate work progress when busy
Parameters
pif Progress Indicator Function to register
Reimplemented from hal::BasePluginInterface.
Definition at line 357 of file plugin_dataflow.cpp.
References s_progress_indicator_function.
set_parameter()
void hal::plugin_dataflow::set_parameter (Netlist * nl, const std::vector< PluginParameter > & params) override virtual
Set configurable parameter to values
Parameters
params The parameter with values
Reimplemented from hal::BasePluginInterface.
Definition at line 128 of file plugin_dataflow.cpp.
References hal::dataflow::state_to_module::create_modules(), execute(), and log_warning.
Member Data Documentation
s_progress_indicator_function
std::function< void(int, const std::string &)> hal::plugin_dataflow::s_progress_indicator_function = nullptr static
Definition at line 96 of file plugin_dataflow.h.
Referenced by execute(), hal::dataflow::ProgressPrinter::print_progress(), and register_progress_indicator().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/dataflow_analysis/include/dataflow_analysis/plugin_dataflow.h
/home/runner/work/hal/hal/plugins/dataflow_analysis/src/plugin_dataflow.cpp