HAL: hal::ModuleSelectEntry Class Reference
hal::ModuleSelectEntry Class Reference
The ModuleSelectEntry class comprises a single entry of the module selection table.
#include <module_select_model.h>
Public Member Functions
ModuleSelectEntry (Module *m)
QVariant data (int icol) const
data returns data from requested column
QColor color () const
u32 id () const
Detailed Description
The ModuleSelectEntry class comprises a single entry of the module selection table.
Definition at line 47 of file module_select_model.h.
Constructor & Destructor Documentation
ModuleSelectEntry()
hal::ModuleSelectEntry::ModuleSelectEntry (Module * m)
Definition at line 40 of file module_select_model.cpp.
References QString::fromStdString(), hal::Module::get_id(), hal::Module::get_name(), hal::Module::get_type(), hal::NetlistRelay::getModuleColor(), and hal::gNetlistRelay.
Member Function Documentation
color()
QColor hal::ModuleSelectEntry::color () const inline
Definition at line 62 of file module_select_model.h.
Referenced by hal::ModuleSelectModel::data().
data()
QVariant hal::ModuleSelectEntry::data (int icol) const
data returns data from requested column
Parameters
icol column number (0, 1, 2, 3)
Returns
0=module color 1=Id 2=name 3=type
Definition at line 48 of file module_select_model.cpp.
Referenced by hal::ModuleSelectModel::data().
id()
u32 hal::ModuleSelectEntry::id () const inline
Definition at line 63 of file module_select_model.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/module_dialog/module_select_model.h
/home/runner/work/hal/hal/plugins/gui/src/module_dialog/module_select_model.cpp