HAL: hal::NetlistSimulator Class Reference
hal::NetlistSimulator Class Reference
#include <netlist_simulator.h>
Public Member Functions
void add_gates (const std::vector< Gate * > &gates)
void add_clock_frequency (const Net *clock_net, u64 frequency, bool start_at_zero=true)
void add_clock_period (const Net *clock_net, u64 period, bool start_at_zero=true)
const std::unordered_set< Gate * > & get_gates () const
const std::vector< const Net * > & get_input_nets () const
const std::vector< const Net * > & get_output_nets () const
void set_input (const Net *net, BooleanFunction::Value value)
void initialize_sequential_gates (const std::function< bool(const Gate *)> &filter=nullptr)
void initialize_sequential_gates (BooleanFunction::Value value, const std::function< bool(const Gate *)> &filter=nullptr)
void load_initial_values (BooleanFunction::Value value)
void load_initial_values_from_netlist ()
void initialize ()
void simulate (u64 picoseconds)
void reset ()
void set_simulation_state (const Simulation &state)
const Simulation & get_simulation_state () const
void set_iteration_timeout (u64 iterations)
u64 get_simulation_timeout () const
bool generate_vcd (const std::filesystem::path &path, u32 start_time, u32 end_time, std::set< const Net * > nets={}) const
Friends
class NetlistSimulatorPlugin
Detailed Description
Definition at line 37 of file netlist_simulator.h.
Member Function Documentation
add_clock_frequency()
void hal::NetlistSimulator::add_clock_frequency (const Net * clock_net, u64 frequency, bool start_at_zero = true)
Specify a net that carries the clock signal and set the clock frequency in hertz. This function can only be called before the simulation has been initialized.
Parameters
[in] clock_net - The net that carries the clock signal.
[in] frequency - The clock frequency in hertz.
[in] start_at_zero - Initial clock state is 0 if true, 1 otherwise.
Definition at line 41 of file netlist_simulator.cpp.
References add_clock_period(), and log_error.
Referenced by hal::PYBIND11_PLUGIN().
add_clock_period()
void hal::NetlistSimulator::add_clock_period (const Net * clock_net, u64 period, bool start_at_zero = true)
Specify a net that carries the clock signal and set the clock period in picoseconds. This function can only be called before the simulation has been initialized.
Parameters
[in] clock_net - The net that carries the clock signal.
[in] period - The clock period from rising edge to rising edge in picoseconds.
[in] start_at_zero - Initial clock state is 0 if true, 1 otherwise.
Definition at line 55 of file netlist_simulator.cpp.
References log_error.
Referenced by add_clock_frequency(), and hal::PYBIND11_PLUGIN().
add_gates()
void hal::NetlistSimulator::add_gates (const std::vector< Gate * > & gates)
Add gates to the simulation set that contains all gates that are considered during simulation. This function can only be called before the simulation has been initialized.
Parameters
[in] gates - The gates to add.
Definition at line 25 of file netlist_simulator.cpp.
References log_error.
Referenced by hal::PYBIND11_PLUGIN().
generate_vcd()
bool hal::NetlistSimulator::generate_vcd (const std::filesystem::path & path, u32 start_time, u32 end_time, std::set< const Net * > nets = {}) const
Generates the a VCD file for parts the simulated netlist.
Parameters
[in] path - The path to the VCD file.
[in] start_time - Start of the timeframe to write to the file (in picoseconds).
[in] end_time - End of the timeframe to write to the file (in picoseconds).
[in] nets - Nets to include in the VCD file.
Returns
True if the file gerneration was successful, false otherwise.
Definition at line 663 of file netlist_simulator.cpp.
References hal::Simulation::get_events(), hal::Net::get_id(), hal::Net::get_name(), log_error, and hal::ShortestPath::net().
Referenced by hal::PYBIND11_PLUGIN().
get_gates()
const std::unordered_set< Gate * > & hal::NetlistSimulator::get_gates () const
Get all gates that are in the simulation set.
Returns
The simulation set.
Definition at line 72 of file netlist_simulator.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_input_nets()
const std::vector< const Net * > & hal::NetlistSimulator::get_input_nets () const
Get all nets that are considered inputs, i.e., not driven by a gate in the simulation set or global inputs.
Returns
The input nets.
Definition at line 77 of file netlist_simulator.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_output_nets()
const std::vector< const Net * > & hal::NetlistSimulator::get_output_nets () const
Get all output nets of gates in the simulation set that have a destination outside of the set or that are global outputs.
Returns
The output nets.
Definition at line 82 of file netlist_simulator.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_simulation_state()
const Simulation & hal::NetlistSimulator::get_simulation_state () const
Get the current simulation state.
Returns
The current simulation state.
Definition at line 266 of file netlist_simulator.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_simulation_timeout()
u64 hal::NetlistSimulator::get_simulation_timeout () const
Get the current iteration timeout value.
Returns
The iteration timeout.
Definition at line 336 of file netlist_simulator.cpp.
Referenced by hal::PYBIND11_PLUGIN().
initialize()
void hal::NetlistSimulator::initialize ()
Initialize the simulation. No additional gates or clocks can be added after this point.
Definition at line 344 of file netlist_simulator.cpp.
References hal::Event::affected_net, hal::combinational, hal::ff, g, hal::Net::get_destinations(), log_error, measure_block_time, hal::ShortestPath::net(), hal::Event::new_value, hal::ram, and hal::Event::time.
Referenced by hal::PYBIND11_PLUGIN(), and simulate().
initialize_sequential_gates() [1/2]
void hal::NetlistSimulator::initialize_sequential_gates (BooleanFunction::Value value, const std::function< bool(const Gate *)> & filter = nullptr)
Configure the sequential gates matching the (optional) user-defined filter condition with the specified value. Schedules the respective gates for initialization, the actual configuration is applied during initialization of the simulator. This function can only be called before the simulation has started.
Parameters
[in] value - The value to initialize the selected gates with.
[in] filter - The optional filter to be applied before initialization.
Definition at line 123 of file netlist_simulator.cpp.
References log_error.
initialize_sequential_gates() [2/2]
void hal::NetlistSimulator::initialize_sequential_gates (const std::function< bool(const Gate *)> & filter = nullptr)
Configure the sequential gates matching the (optional) user-defined filter condition with initialization data specified within the netlist. Schedules the respective gates for initialization, the actual configuration is applied during initialization of the simulator. This function can only be called before the simulation has started.
Parameters
[in] filter - The optional filter to be applied before initialization.
Definition at line 110 of file netlist_simulator.cpp.
References log_error.
Referenced by hal::PYBIND11_PLUGIN().
load_initial_values()
void hal::NetlistSimulator::load_initial_values (BooleanFunction::Value value)
Deprecated:
DEPRECATED
Load the specified initial value into the current state of all sequential elements.
Parameters
[in] value - The initial value to load.
Definition at line 136 of file netlist_simulator.cpp.
References hal::Event::affected_net, hal::ff, hal::GateType::get_pin_types(), hal::neg_state, hal::Event::new_value, hal::state, hal::Event::time, and hal::simulation_utils::toggle().
Referenced by hal::PYBIND11_PLUGIN().
load_initial_values_from_netlist()
void hal::NetlistSimulator::load_initial_values_from_netlist ()
Deprecated:
DEPRECATED
Load the initial value specified within the netlist file into the current state of all sequential elements. This is especially relevant for FPGA netlists, since these may provide initial values to load on startup.
Definition at line 174 of file netlist_simulator.cpp.
References hal::Event::affected_net, hal::ff, hal::InitComponent::get_init_category(), hal::InitComponent::get_init_identifiers(), hal::GateType::get_name(), hal::GateType::get_pin_types(), hal::InitComponent::get_type(), hal::GateTypeComponent::init, log_error, hal::neg_state, hal::Event::new_value, hal::state, hal::Event::time, and hal::simulation_utils::toggle().
Referenced by hal::PYBIND11_PLUGIN().
reset()
void hal::NetlistSimulator::reset ()
Reset the simulator state, i.e., treat all signals as unknown. Does not remove gates/nets from the simulation set.
Definition at line 252 of file netlist_simulator.cpp.
Referenced by hal::PYBIND11_PLUGIN().
set_input()
void hal::NetlistSimulator::set_input (const Net * net, BooleanFunction::Value value)
Set the signal for a specific wire to control input signals between simulation cycles.
Parameters
[in] net - The net to set a signal value for.
[in] value - The value to set.
Definition at line 87 of file netlist_simulator.cpp.
References hal::Event::affected_net, log_error, hal::ShortestPath::net(), hal::Event::new_value, and hal::Event::time.
Referenced by hal::PYBIND11_PLUGIN(), and hal::SimulatorTest::set_16_bit_net_vector().
set_iteration_timeout()
void hal::NetlistSimulator::set_iteration_timeout (u64 iterations)
Set the iteration timeout, i.e., the maximum number of events processed for a single point in time. Useful to abort in case of infinite loops. A value of 0 disables the timeout.
Parameters
[in] iterations - The iteration timeout.
Definition at line 331 of file netlist_simulator.cpp.
Referenced by hal::PYBIND11_PLUGIN().
set_simulation_state()
void hal::NetlistSimulator::set_simulation_state (const Simulation & state)
Set the simulator state, i.e., net signals, to a given state. Does not influence gates/nets added to the simulation set.
Parameters
[in] state - The state to apply.
Definition at line 261 of file netlist_simulator.cpp.
References hal::state.
Referenced by hal::PYBIND11_PLUGIN().
simulate()
void hal::NetlistSimulator::simulate (u64 picoseconds)
Simulate for a specific period, advancing the internal state. Automatically initializes the simulation if 'initialize' has not yet been called. Use 'set_input' to control specific signals.
Parameters
[in] picoseconds - The duration to simulate.
Definition at line 240 of file netlist_simulator.cpp.
References initialize().
Referenced by hal::PYBIND11_PLUGIN().
Friends And Related Function Documentation
NetlistSimulatorPlugin
friend class NetlistSimulatorPlugin friend
Definition at line 197 of file netlist_simulator.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/netlist_simulator/include/netlist_simulator/netlist_simulator.h
/home/runner/work/hal/hal/plugins/netlist_simulator/src/netlist_simulator.cpp