HAL: hal::SelectionDetailsIconProvider Class Reference
hal::SelectionDetailsIconProvider Class Reference
#include <selection_details_icon_provider.h>
Public Types
enum IconCategory { ModuleIcon = -1, GateIcon = -2, NetIcon = -3 }
enum IconSize { NoIcon, SmallIcon, BigIcon }
Public Member Functions
Q_ENUM(IconSize) private Q_SLOTS void handleModuleColorChanged (u32 id)
const QIcon * getIcon (IconCategory catg, u32 itemId)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static SelectionDetailsIconProvider * instance ()
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Static Public Attributes
static SettingsItemDropdown * sIconSizeSetting = nullptr
Additional Inherited Members
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Definition at line 38 of file selection_details_icon_provider.h.
Member Enumeration Documentation
IconCategory
enum hal::SelectionDetailsIconProvider::IconCategory
Enumerator
ModuleIcon
GateIcon
NetIcon
Definition at line 45 of file selection_details_icon_provider.h.
IconSize
enum hal::SelectionDetailsIconProvider::IconSize
Enumerator
NoIcon
SmallIcon
BigIcon
Definition at line 46 of file selection_details_icon_provider.h.
Member Function Documentation
getIcon()
const QIcon * hal::SelectionDetailsIconProvider::getIcon (IconCategory catg, u32 itemId)
Definition at line 88 of file selection_details_icon_provider.cpp.
References QHash::end(), QHash::find(), test_plugin::g, GateIcon, hal::Netlist::get_gate_by_id(), hal::NetlistRelay::getModuleColor(), hal::gui_utility::getStyledSvgIcon(), hal::gNetlist, hal::gNetlistRelay, QColor::HexRgb, QColor::isValid(), ModuleIcon, QColor::name(), QHash::value(), and QHash::iterator::value().
handleModuleColorChanged()
void hal::SelectionDetailsIconProvider::handleModuleColorChanged (u32 id)
Definition at line 48 of file selection_details_icon_provider.cpp.
References QHash::end(), QHash::find(), hal::NetlistRelay::getModuleColor(), hal::gui_utility::getStyledSvgIcon(), hal::gNetlistRelay, QColor::HexRgb, id, QColor::name(), and QHash::iterator::value().
instance()
SelectionDetailsIconProvider * hal::SelectionDetailsIconProvider::instance () static
Definition at line 33 of file selection_details_icon_provider.cpp.
References hal::gNetlistRelay.
Referenced by hal::ModuleModel::data(), hal::SelectionTreeItemModule::icon(), hal::SelectionTreeItemGate::icon(), hal::SelectionTreeItemNet::icon(), and hal::DetailsTabWidget::setIcon().
Member Data Documentation
sIconSizeSetting
SettingsItemDropdown * hal::SelectionDetailsIconProvider::sIconSizeSetting = nullptr static
Definition at line 61 of file selection_details_icon_provider.h.
Referenced by hal::DetailsTabWidget::setIcon().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/selection_details_icon_provider.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/selection_details_icon_provider.cpp