HAL: hal::UserActionManager Class Reference
hal::UserActionManager Class Reference
HAL Gui » User Actions
Handles and manages user actions related proccesses.
#include <user_action_manager.h>
Public Slots
void handleSettingDumpActionChanged (bool wantDump)
Signals
void canUndoLastAction (bool yesWeCan)
Public Member Functions
void addExecutedAction (UserAction *act)
void registerFactory (UserActionFactory *fac)
void setStartRecording ()
void setStopRecording (const QString &macroFilename)
void playMacro (const QString &macroFilename)
bool isRecording () const
bool hasRecorded () const
void clearWaitCount ()
UserAction * getParsedAction (QXmlStreamReader &xmlIn) const
qint64 timeStamp () const
void undoLastAction ()
void crashDump (int sig)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static UserActionManager * instance ()
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Additional Inherited Members
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Handles and manages user actions related proccesses.
The UserActionManager class manages everything related to user actions such as saving and recording actions. It is implemented as a singleton pattern.
Definition at line 49 of file user_action_manager.h.
Member Function Documentation
addExecutedAction()
void hal::UserActionManager::addExecutedAction (UserAction * act)
Add executed action to history list.
Parameters
act - The action.
Definition at line 44 of file user_action_manager.cpp.
References hal::UserAction::debugDump(), QTextCursor::End, QPlainTextEdit::insertPlainText(), QPlainTextEdit::moveCursor(), QWidget::show(), QVariant::toBool(), and hal::SettingsItemCheckbox::value().
Referenced by hal::UserAction::exec().
canUndoLastAction
void hal::UserActionManager::canUndoLastAction (bool yesWeCan) signal
Q_SIGNAL that is emitted when undoLastAction() is called. The parameter is set to true if the last action could be undone.
Parameters
yesWeCan - True if last action could be undone.
clearWaitCount()
void hal::UserActionManager::clearWaitCount () inline
Resets wait flag issued from action.
Definition at line 112 of file user_action_manager.h.
Referenced by hal::GraphContext::GraphContext().
crashDump()
void hal::UserActionManager::crashDump (int sig)
Dumps actions from beginning.
Parameters
sig - Part of the macro file name.
Definition at line 68 of file user_action_manager.cpp.
References setStopRecording().
getParsedAction()
UserAction * hal::UserActionManager::getParsedAction (QXmlStreamReader & xmlIn) const
Creates UserAction instance for next command found by xml parser.
Parameters
xmlIn - The xml reader.
Returns
The next UserAction.
Definition at line 164 of file user_action_manager.cpp.
References QXmlStreamReader::attributes(), QStringRef::isEmpty(), QStringRef::isNull(), QXmlStreamReader::name(), hal::UserActionFactory::newAction(), hal::UserAction::readFromXml(), hal::UserActionObject::readFromXml(), hal::UserAction::setCompoundOrder(), hal::UserAction::setObject(), QStringRef::toInt(), QStringRef::toString(), and QXmlStreamAttributes::value().
Referenced by playMacro(), and hal::UserActionCompound::readFromXml().
handleSettingDumpActionChanged
void hal::UserActionManager::handleSettingDumpActionChanged (bool wantDump) slot
Deletes current dumpAction if parameter is set to true.
Parameters
wantDump - Decides if current dumpAction is to be deleted.
Definition at line 35 of file user_action_manager.cpp.
References QObject::deleteLater().
hasRecorded()
bool hal::UserActionManager::hasRecorded () const
Tests whether actions are currently recorded and at least one command has been executed
Returns
True if there are recorded and executed actions, False otherwise.
Definition at line 189 of file user_action_manager.cpp.
References isRecording().
Referenced by hal::MainWindow::handleActionStopRecording().
instance()
UserActionManager * hal::UserActionManager::instance () static
Get the singleton instance.
Returns
The singleton instance.
Definition at line 204 of file user_action_manager.cpp.
Referenced by hal::UserAction::exec(), hal::GraphContext::GraphContext(), hal::MainWindow::handleActionPlayMacro(), hal::MainWindow::handleActionStartRecording(), hal::MainWindow::handleActionStopRecording(), hal::MainWindow::handleActionUndo(), hal::UserActionCompound::readFromXml(), and hal::UserActionFactory::UserActionFactory().
isRecording()
bool hal::UserActionManager::isRecording () const
Tests whether actions are currently recorded.
Returns
True if it is currently recording, False otherwise.
Definition at line 194 of file user_action_manager.cpp.
Referenced by hasRecorded().
playMacro()
void hal::UserActionManager::playMacro (const QString & macroFilename)
Executes macro from file.
Parameters
macroFilename - The file name.
Definition at line 109 of file user_action_manager.cpp.
References QXmlStreamReader::atEnd(), hal::UserAction::exec(), hal::ff, getParsedAction(), QXmlStreamReader::hasError(), QXmlStreamReader::isEndElement(), QXmlStreamReader::isStartElement(), hal::UserAction::isWaitForReady(), log_warning, QThread::msleep(), QXmlStreamReader::name(), QCoreApplication::processEvents(), QXmlStreamReader::readNext(), QIODevice::ReadOnly, hal::UserAction::tagname(), and QString::toStdString().
Referenced by hal::MainWindow::handleActionPlayMacro().
registerFactory()
void hal::UserActionManager::registerFactory (UserActionFactory * fac)
Registers a new action factory.
Parameters
fac - The factory.
Definition at line 199 of file user_action_manager.cpp.
References hal::UserActionFactory::tagname().
Referenced by hal::UserActionFactory::UserActionFactory().
setStartRecording()
void hal::UserActionManager::setStartRecording ()
Sets a start marker for macro recording.
Definition at line 63 of file user_action_manager.cpp.
Referenced by hal::MainWindow::handleActionStartRecording().
setStopRecording()
void hal::UserActionManager::setStopRecording (const QString & macroFilename)
Stops macro recording and write commands to xml file.
Parameters
macroFilename - The file name.
Definition at line 75 of file user_action_manager.cpp.
References hal::UserAction::compoundOrder(), hal::UserAction::cryptographicHash(), QString::isEmpty(), QString::number(), hal::UserAction::object(), of, QXmlStreamWriter::setAutoFormatting(), hal::UserAction::tagname(), hal::UserAction::timeStamp(), QXmlStreamWriter::writeAttribute(), QXmlStreamWriter::writeEndDocument(), QXmlStreamWriter::writeEndElement(), QIODevice::WriteOnly, QXmlStreamWriter::writeStartDocument(), QXmlStreamWriter::writeStartElement(), hal::UserAction::writeToXml(), and hal::UserActionObject::writeToXml().
Referenced by crashDump(), and hal::MainWindow::handleActionStopRecording().
timeStamp()
qint64 hal::UserActionManager::timeStamp () const inline
Get the elapsed time in milliseconds since GUI start.
Returns
The elapsed time.
Definition at line 128 of file user_action_manager.h.
References QElapsedTimer::elapsed().
Referenced by hal::UserAction::exec().
undoLastAction()
void hal::UserActionManager::undoLastAction ()
Undo last action.
Definition at line 229 of file user_action_manager.cpp.
References QList::append(), hal::UserAction::compoundOrder(), and hal::UserAction::undoAction().
Referenced by hal::MainWindow::handleActionUndo().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/user_action_manager.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/user_action_manager.cpp