HAL: hal::SelectionTreeItem Class Reference
hal::SelectionTreeItem Class Reference abstract
HAL Gui » Utility Widgets » Selection Details Widget
Basic item for the SelectionTreeModel.
#include <selection_tree_item.h>
Public Types
enum TreeItemType {
NullItem, ModuleItem, GateItem, NetItem,
MaxItem
}
Public Member Functions
SelectionTreeItem (TreeItemType t=NullItem, u32 id_=0)
virtual ~SelectionTreeItem ()
TreeItemType itemType () const
u32 id () const
SelectionTreeItem * parent () const
void setParent (SelectionTreeItem *p)
virtual int childCount () const
virtual SelectionTreeItem * child (int row) const
virtual QVariant data (int column) const
virtual QVariant name () const =0
virtual QIcon icon () const =0
virtual QVariant boxType () const
virtual bool match (const QRegularExpression &regex) const
virtual void suppressedByFilterRecursion (QList< u32 > &modIds, QList< u32 > &gatIds, QList< u32 > &netIds, const QRegularExpression &regex) const =0
bool isEqual (const SelectionTreeItem *sti) const
Protected Attributes
TreeItemType mItemType
u32 mId
SelectionTreeItem * mParent
Detailed Description
Basic item for the SelectionTreeModel.
The basic tree item class for the SelectionTreeModel. It is the base class for every other subitem (except for SelectionTreeItemRoot) as it provides all commonly shared and necessary functions for the model and related events.
Definition at line 46 of file selection_tree_item.h.
Member Enumeration Documentation
TreeItemType
enum hal::SelectionTreeItem::TreeItemType
An enum that defines all possible types a tree item can take with the exception of the NullItem and MaxItem type. These types are convenient type used in the model and the graphics scene (NullItem is used for the root item of the model). The type be accessed via the itemType() method.
Enumerator
NullItem
ModuleItem
GateItem
NetItem
MaxItem
Definition at line 56 of file selection_tree_item.h.
Constructor & Destructor Documentation
SelectionTreeItem()
hal::SelectionTreeItem::SelectionTreeItem (SelectionTreeItem::TreeItemType t = NullItem, u32 id_ = 0)
The constructor.
Parameters
t - The type based on the netlist item type it represents.
id_ The id of the item. It usually is the same as the underlying netlist item.
Definition at line 7 of file selection_tree_item.cpp.
~SelectionTreeItem()
hal::SelectionTreeItem::~SelectionTreeItem () virtual
The destructor.
Definition at line 11 of file selection_tree_item.cpp.
Member Function Documentation
boxType()
QVariant hal::SelectionTreeItem::boxType () const virtual
Returns the appropriate type of either a gate or module (not a net). Must be implemented in the subclass.
Returns
The name of the type.
Reimplemented in hal::SelectionTreeItemGate, and hal::SelectionTreeItemModule.
Definition at line 55 of file selection_tree_item.cpp.
Referenced by data(), and match().
child()
SelectionTreeItem * hal::SelectionTreeItem::child (int row) const virtual
Get the child from the given row.
Parameters
row - The row for which the child is requested.
Returns
The child for the given row. If the row is not in the childCount range, a nullptr is returned.
Reimplemented in hal::SelectionTreeItemModule.
Definition at line 39 of file selection_tree_item.cpp.
Referenced by hal::SelectionTreeModel::index(), and hal::SelectionTreeModel::indexFromItem().
childCount()
int hal::SelectionTreeItem::childCount () const virtual
Get the number of child item (the items to which this item is the direct ancestor in the tree).
Returns
The number of children.
Reimplemented in hal::SelectionTreeItemModule.
Definition at line 34 of file selection_tree_item.cpp.
Referenced by hal::SelectionTreeModel::indexFromItem(), and hal::SelectionTreeModel::rowCount().
data()
QVariant hal::SelectionTreeItem::data (int column) const virtual
Get the data for the specified column.
Parameters
column - The column for which the data is requested.
Returns
The data. If the column > 2, an empty QVariant is returned.
Definition at line 45 of file selection_tree_item.cpp.
References boxType(), mId, and name().
Referenced by hal::SelectionTreeModel::data().
icon()
virtual QIcon hal::SelectionTreeItem::icon () const pure virtual
Get the icon for either the module, gate, or net item. Must be implemented by the specific subclass.
Returns
The subclasse's specific icon.
Implemented in hal::SelectionTreeItemNet, hal::SelectionTreeItemGate, and hal::SelectionTreeItemModule.
Referenced by hal::SelectionTreeModel::data().
id()
u32 hal::SelectionTreeItem::id () const
Get the item's id.
Returns
The id.
Definition at line 19 of file selection_tree_item.cpp.
References mId.
Referenced by hal::SelectionDetailsWidget::selectionToGroupingAction().
isEqual()
bool hal::SelectionTreeItem::isEqual (const SelectionTreeItem * sti) const
Definition at line 68 of file selection_tree_item.cpp.
References mId, and mItemType.
itemType()
SelectionTreeItem::TreeItemType hal::SelectionTreeItem::itemType () const
Get the item's type.
Returns
The type.
Definition at line 14 of file selection_tree_item.cpp.
References mItemType.
Referenced by hal::SelectionDetailsWidget::selectionToGroupingAction().
match()
bool hal::SelectionTreeItem::match (const QRegularExpression & regex) const virtual
Matches the given regex against the name, id, and in case if the the item is a gate type, the gate type. If the item is a module type, the children are also matched against.
Parameters
regex - The regex to match against the item.
Returns
True if a match in either of the categories was found. False otherwise.
Reimplemented in hal::SelectionTreeItemModule.
Definition at line 60 of file selection_tree_item.cpp.
References boxType(), QRegularExpressionMatch::hasMatch(), QRegularExpression::isValid(), QRegularExpression::match(), mId, name(), and QString::number().
Referenced by hal::SelectionTreeItemModule::match(), hal::SelectionTreeItemGate::suppressedByFilterRecursion(), and hal::SelectionTreeItemNet::suppressedByFilterRecursion().
name()
virtual QVariant hal::SelectionTreeItem::name () const pure virtual
Get the name of the item. The name is usually the name of the underlying netlist item. Must be implemented in the subclasse(s).
Returns
The item's name.
Implemented in hal::SelectionTreeItemNet, hal::SelectionTreeItemGate, and hal::SelectionTreeItemModule.
Referenced by data(), and match().
parent()
SelectionTreeItem * hal::SelectionTreeItem::parent () const
Get the item's parent (the direct ancestor in the tree).
Returns
The parent.
Definition at line 24 of file selection_tree_item.cpp.
References mParent.
Referenced by hal::SelectionTreeModel::indexFromItem(), and hal::SelectionTreeModel::parent().
setParent()
void hal::SelectionTreeItem::setParent (SelectionTreeItem * p)
Sets the parent (direct ancestor in the tree) of the item.
Parameters
p - The parent.
Definition at line 29 of file selection_tree_item.cpp.
References mParent.
Referenced by hal::SelectionTreeItemModule::addChild().
suppressedByFilterRecursion()
virtual void hal::SelectionTreeItem::suppressedByFilterRecursion (QList< u32 > & modIds, QList< u32 > & gatIds, QList< u32 > & netIds, const QRegularExpression & regex) const pure virtual
A function that fills the modIds, gateIds, and netIds lists with the respective ids if the called selection-tree-item subclass does not match the given regex (and in thus suppressed, meaning should not be displayed). Must be implemented by the specific subclass since a module-type item must call this function of its children. A gate- or net-type item simply adds itself to the list (or not).
Parameters
modIds - The list that contains the suppresed module-type items at the end.
gatIds - The list that contains the suppressed gate-type items at the end.
netIds - The list that contains the suppressed net-type items at the end.
regex - The regular expression to match the items against.
Implemented in hal::SelectionTreeItemNet, hal::SelectionTreeItemGate, and hal::SelectionTreeItemModule.
Member Data Documentation
mId
u32 hal::SelectionTreeItem::mId protected
Definition at line 177 of file selection_tree_item.h.
Referenced by hal::SelectionTreeItemModule::boxType(), hal::SelectionTreeItemGate::boxType(), data(), hal::SelectionTreeItemModule::icon(), hal::SelectionTreeItemGate::icon(), hal::SelectionTreeItemNet::icon(), id(), isEqual(), match(), hal::SelectionTreeItemModule::name(), hal::SelectionTreeItemGate::name(), hal::SelectionTreeItemNet::name(), hal::SelectionTreeItemModule::suppressedByFilterRecursion(), hal::SelectionTreeItemGate::suppressedByFilterRecursion(), and hal::SelectionTreeItemNet::suppressedByFilterRecursion().
mItemType
TreeItemType hal::SelectionTreeItem::mItemType protected
Definition at line 176 of file selection_tree_item.h.
Referenced by isEqual(), and itemType().
mParent
SelectionTreeItem* hal::SelectionTreeItem::mParent protected
Definition at line 178 of file selection_tree_item.h.
Referenced by parent(), and setParent().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/tree_navigation/selection_tree_item.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/tree_navigation/selection_tree_item.cpp