HAL: hal::GuiExtensionDataflow Class Reference
hal::GuiExtensionDataflow Class Reference
#include <plugin_dataflow.h>
Public Member Functions
GuiExtensionDataflow ()=default
Default constructor for GuiExtensionDataflow.
std::vector< PluginParameter > get_parameter () const override
Get a vector of configurable parameters.
void set_parameter (const std::vector< PluginParameter > &params) override
Set values for a vector of configurable parameters.
void execute_function (std::string tag, Netlist *nl, const std::vector< u32 > &mods, const std::vector< u32 > &gats, const std::vector< u32 > &nets) override
Execute the plugin on the given netlist.
virtual void register_progress_indicator (std::function< void(int, const std::string &)> pif) override
Public Member Functions inherited from hal::GuiExtensionInterface
GuiExtensionInterface ()
virtual ~GuiExtensionInterface ()
virtual std::vector< ContextMenuContribution > get_context_contribution (const Netlist *nl, const std::vector< u32 > &mods, const std::vector< u32 > &gats, const std::vector< u32 > &nets)
virtual void netlist_loaded (Netlist *nl)
virtual void netlist_about_to_close (Netlist *nl)
Public Member Functions inherited from hal::AbstractExtensionInterface
AbstractExtensionInterface ()
virtual ~AbstractExtensionInterface ()
Static Public Attributes
static std::function< void(int, const std::string &)> s_progress_indicator_function = nullptr
Detailed Description
Definition at line 53 of file plugin_dataflow.h.
Constructor & Destructor Documentation
GuiExtensionDataflow()
hal::GuiExtensionDataflow::GuiExtensionDataflow () default
Default constructor for GuiExtensionDataflow.
Member Function Documentation
execute_function()
void hal::GuiExtensionDataflow::execute_function (std::string tag, Netlist * nl, const std::vector< u32 > & mods, const std::vector< u32 > & gats, const std::vector< u32 > & nets) override virtual
Execute the plugin on the given netlist.
All parameters but the netlist are ignored.
Parameters
[in] tag - A tag (ignored).
[in] nl - The netlist to operate on.
[in] mods - Module IDs (ignored).
[in] gats - Gate IDs (ignored).
[in] nets - Net IDs (ignored).
Reimplemented from hal::GuiExtensionInterface.
Definition at line 167 of file plugin_dataflow.cpp.
References hal::dataflow::analyze(), hal::clock, hal::enable, hal::ff, log_error, log_warning, hal::reset, s_progress_indicator_function, hal::set, UNUSED, hal::dataflow::Configuration::with_control_pin_types(), hal::dataflow::Configuration::with_expected_sizes(), hal::dataflow::Configuration::with_min_group_size(), and hal::dataflow::Configuration::with_stage_identification().
get_parameter()
std::vector< PluginParameter > hal::GuiExtensionDataflow::get_parameter () const override virtual
Get a vector of configurable parameters.
Returns
The vector of parameters.
Reimplemented from hal::GuiExtensionInterface.
Definition at line 109 of file plugin_dataflow.cpp.
References hal::PluginParameter::Boolean, hal::PluginParameter::ExistingDir, hal::PluginParameter::Integer, hal::PluginParameter::PushButton, and hal::PluginParameter::String.
register_progress_indicator()
void hal::GuiExtensionDataflow::register_progress_indicator (std::function< void(int, const std::string &)> pif) override virtual
Register function to indicate work progress when busy
Parameters
pif Progress Indicator Function to register
Reimplemented from hal::GuiExtensionInterface.
Definition at line 232 of file plugin_dataflow.cpp.
References s_progress_indicator_function.
set_parameter()
void hal::GuiExtensionDataflow::set_parameter (const std::vector< PluginParameter > & params) override virtual
Set values for a vector of configurable parameters.
Parameters
[in] params - The parameters including their values.
Reimplemented from hal::GuiExtensionInterface.
Definition at line 123 of file plugin_dataflow.cpp.
Member Data Documentation
s_progress_indicator_function
std::function< void(int, const std::string &)> hal::GuiExtensionDataflow::s_progress_indicator_function = nullptr static
Definition at line 104 of file plugin_dataflow.h.
Referenced by execute_function(), hal::dataflow::ProgressPrinter::print_progress(), and register_progress_indicator().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/dataflow_analysis/include/dataflow_analysis/plugin_dataflow.h
/home/runner/work/hal/hal/plugins/dataflow_analysis/src/plugin_dataflow.cpp