HAL: hal::NetlistElementsTreeModel Class Reference
hal::NetlistElementsTreeModel Class Reference
HAL Gui » Utility Widgets » Selection Details Widget
A model to display arbitrary elements of the netlist.
#include <netlist_elements_tree_model.h>
Public Types
enum itemType { itemType::module = 0, itemType::gate = 1, itemType::net = 2 }
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Signals
void numberOfSubmodulesChanged (const int newNumber)
Public Member Functions
NetlistElementsTreeModel (QObject *parent=nullptr)
~NetlistElementsTreeModel ()
void clear () override
void setContent (QList< int > modIds, QList< int > gateIds, QList< int > netIds, bool displayModulesRecursive=true, bool showGatesInSubmods=true, bool showNetsInSubmods=true)
void setModule (Module *mod, bool showGates=true, bool showNets=true, bool displayModulesRecursive=true)
itemType getTypeOfItem (TreeItem *item) const
int getRepresentedIdOfItem (TreeItem *item) const
Overwritten model functions
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
Event Handler Functions
void gateNameChanged (Gate *g)
void gateRemoved (Gate *g)
void netNameChanged (Net *n)
void netRemoved (Net *n)
void moduleNameChanged (Module *m)
void moduleTypeChanged (Module *m)
void moduleSubmoduleRemoved (Module *m, int removed_module)
void moduleGateAssigned (Module *m, int assigned_gate)
void moduleGateRemoved (Module *m, int removed_gate)
void moduleSubmoduleAdded (Module *m, int added_module)
Public Member Functions inherited from hal::BaseTreeModel
BaseTreeModel (QObject *parent=nullptr)
void setContent (QList< TreeItem * > firstLevelItems)
void setHeaderLabels (QList< QVariant > labels)
QModelIndex getIndexFromItem (TreeItem *item) const
TreeItem * getItemFromIndex (QModelIndex index) const
TreeItem * getRootItem () const
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
virtual QModelIndex parent (const QModelIndex &index) const override
virtual Qt::ItemFlags flags (const QModelIndex &index) const override
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const override
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const override
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
virtual QModelIndex sibling (int row, int column, const QModelIndex &index) const const
virtual bool hasChildren (const QModelIndex &parent) const const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role)
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const const
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
virtual QStringList mimeTypes () const const
virtual QMimeData * mimeData (const QModelIndexList &indexes) const const
virtual bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const const
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
virtual Qt::DropActions supportedDropActions () const const
virtual Qt::DropActions supportedDragActions () const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool insertRows (int row, int count, const QModelIndex &parent)
virtual bool insertColumns (int column, int count, const QModelIndex &parent)
virtual bool removeRows (int row, int count, const QModelIndex &parent)
virtual bool removeColumns (int column, int count, const QModelIndex &parent)
virtual bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual void fetchMore (const QModelIndex &parent)
virtual bool canFetchMore (const QModelIndex &parent) const const
virtual void sort (int column, Qt::SortOrder order)
virtual QModelIndex buddy (const QModelIndex &index) const const
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const
virtual QSize span (const QModelIndex &index) const const
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual bool submit ()
virtual void revert ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Attributes
const QString keyItemType = "type"
const QString keyRepresentedID = "id"
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Static Public Attributes
static const int sNameColumn = 0
static const int sIdColumn = 1
static const int sTypeColumn = 2
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Attributes inherited from hal::BaseTreeModel
TreeItem * mRootItem
Properties inherited from QObject
objectName
Detailed Description
A model to display arbitrary elements of the netlist.
Definition at line 44 of file netlist_elements_tree_model.h.
Member Enumeration Documentation
itemType
enum hal::NetlistElementsTreeModel::itemType strong
Enumerator
module
gate
net
Definition at line 50 of file netlist_elements_tree_model.h.
Constructor & Destructor Documentation
NetlistElementsTreeModel()
hal::NetlistElementsTreeModel::NetlistElementsTreeModel (QObject * parent = nullptr)
The constructor.
Parameters
parent - The model's parent.
Definition at line 12 of file netlist_elements_tree_model.cpp.
References QObject::connect(), gateNameChanged(), hal::NetlistRelay::gateNameChanged(), gateRemoved(), hal::NetlistRelay::gateRemoved(), hal::gNetlistRelay, moduleGateAssigned(), hal::NetlistRelay::moduleGateAssigned(), moduleGateRemoved(), hal::NetlistRelay::moduleGateRemoved(), moduleNameChanged(), hal::NetlistRelay::moduleNameChanged(), moduleSubmoduleAdded(), hal::NetlistRelay::moduleSubmoduleAdded(), moduleSubmoduleRemoved(), hal::NetlistRelay::moduleSubmoduleRemoved(), moduleTypeChanged(), hal::NetlistRelay::moduleTypeChanged(), netRemoved(), hal::NetlistRelay::netRemoved(), Qt::QueuedConnection, and hal::BaseTreeModel::setHeaderLabels().
~NetlistElementsTreeModel()
hal::NetlistElementsTreeModel::~NetlistElementsTreeModel ()
The destructor.
Definition at line 31 of file netlist_elements_tree_model.cpp.
References hal::BaseTreeModel::mRootItem.
Member Function Documentation
clear()
void hal::NetlistElementsTreeModel::clear () override virtual
Overwritten clear function to reset this model's specific structures.
Reimplemented from hal::BaseTreeModel.
Definition at line 52 of file netlist_elements_tree_model.cpp.
References hal::BaseTreeModel::clear().
Referenced by moduleSubmoduleRemoved(), and setContent().
data()
QVariant hal::NetlistElementsTreeModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override virtual
Overwritten Qt function that is necessary for the model. For further information pleaser refer to the Qt documentation.
Reimplemented from hal::BaseTreeModel.
Definition at line 36 of file netlist_elements_tree_model.cpp.
References QModelIndex::column(), hal::BaseTreeModel::data(), Qt::DecorationRole, hal::BaseTreeModel::getItemFromIndex(), hal::BaseTreeModel::index(), and QModelIndex::isValid().
gateNameChanged()
void hal::NetlistElementsTreeModel::gateNameChanged (Gate * g)
Definition at line 150 of file netlist_elements_tree_model.cpp.
References QAbstractItemModel::createIndex(), QAbstractItemModel::dataChanged(), QString::fromStdString(), test_plugin::g, hal::BaseTreeModel::getIndexFromItem(), QModelIndex::internalPointer(), QObject::Q_EMIT(), QModelIndex::row(), and sNameColumn.
Referenced by NetlistElementsTreeModel().
gateRemoved()
void hal::NetlistElementsTreeModel::gateRemoved (Gate * g)
Definition at line 161 of file netlist_elements_tree_model.cpp.
References QAbstractItemModel::beginRemoveRows(), QAbstractItemModel::beginResetModel(), QAbstractItemModel::endRemoveRows(), QAbstractItemModel::endResetModel(), test_plugin::g, hal::BaseTreeModel::getIndexFromItem(), hal::BaseTreeModel::mRootItem, and QObject::parent().
Referenced by moduleGateRemoved(), and NetlistElementsTreeModel().
getRepresentedIdOfItem()
int hal::NetlistElementsTreeModel::getRepresentedIdOfItem (TreeItem * item) const
Get the module/gate/net id that the given item represents. To know the type of the item, call getTypeOfItem().
Parameters
item - The item from which to extract the id.
Returns
The corresponding module, gate, or net id.
Definition at line 145 of file netlist_elements_tree_model.cpp.
References hal::TreeItem::getAdditionalData(), keyRepresentedID, and QVariant::toInt().
getTypeOfItem()
NetlistElementsTreeModel::itemType hal::NetlistElementsTreeModel::getTypeOfItem (TreeItem * item) const
Get the type (enum) of a given item.
Parameters
item - The item for which the type is requested.
Returns
The item's type.
Definition at line 140 of file netlist_elements_tree_model.cpp.
References hal::TreeItem::getAdditionalData(), keyItemType, and QVariant::value().
Referenced by moduleGateAssigned(), and moduleSubmoduleRemoved().
moduleGateAssigned()
void hal::NetlistElementsTreeModel::moduleGateAssigned (Module * m, int assigned_gate)
Definition at line 269 of file netlist_elements_tree_model.cpp.
References QAbstractItemModel::beginResetModel(), QAbstractItemModel::endResetModel(), QString::fromStdString(), QVariant::fromValue(), gate, hal::Netlist::get_gate_by_id(), hal::Gate::get_id(), hal::Module::get_id(), hal::Gate::get_name(), hal::GateType::get_name(), hal::Gate::get_type(), getTypeOfItem(), hal::gNetlist, keyItemType, keyRepresentedID, module, hal::BaseTreeModel::mRootItem, and hal::TreeItem::setAdditionalData().
Referenced by NetlistElementsTreeModel().
moduleGateRemoved()
void hal::NetlistElementsTreeModel::moduleGateRemoved (Module * m, int removed_gate)
Definition at line 306 of file netlist_elements_tree_model.cpp.
References gateRemoved(), hal::Netlist::get_gate_by_id(), and hal::gNetlist.
Referenced by NetlistElementsTreeModel().
moduleNameChanged()
void hal::NetlistElementsTreeModel::moduleNameChanged (Module * m)
Definition at line 204 of file netlist_elements_tree_model.cpp.
References QAbstractItemModel::createIndex(), QAbstractItemModel::dataChanged(), QString::fromStdString(), hal::Module::get_name(), hal::BaseTreeModel::getIndexFromItem(), QModelIndex::internalPointer(), QObject::Q_EMIT(), QModelIndex::row(), and sNameColumn.
Referenced by NetlistElementsTreeModel().
moduleSubmoduleAdded()
void hal::NetlistElementsTreeModel::moduleSubmoduleAdded (Module * m, int added_module)
Definition at line 312 of file netlist_elements_tree_model.cpp.
References QAbstractItemModel::beginResetModel(), QAbstractItemModel::endResetModel(), QString::fromStdString(), QVariant::fromValue(), hal::Module::get_id(), hal::Netlist::get_module_by_id(), hal::Module::get_name(), hal::Module::get_submodules(), hal::Module::get_type(), hal::gNetlist, keyItemType, keyRepresentedID, module, hal::BaseTreeModel::mRootItem, numberOfSubmodulesChanged(), QObject::Q_EMIT(), and hal::TreeItem::setAdditionalData().
Referenced by NetlistElementsTreeModel().
moduleSubmoduleRemoved()
void hal::NetlistElementsTreeModel::moduleSubmoduleRemoved (Module * m, int removed_module)
Definition at line 224 of file netlist_elements_tree_model.cpp.
References QList::append(), QAbstractItemModel::beginResetModel(), clear(), QQueue::dequeue(), QAbstractItemModel::endResetModel(), QQueue::enqueue(), gate, hal::Netlist::get_gate_by_id(), hal::Module::get_id(), hal::Netlist::get_module_by_id(), hal::Netlist::get_net_by_id(), hal::Module::get_submodules(), hal::TreeItem::getAdditionalData(), hal::TreeItem::getChildren(), getTypeOfItem(), hal::gNetlist, QList::isEmpty(), keyRepresentedID, module, net, numberOfSubmodulesChanged(), QObject::Q_EMIT(), and QVariant::toUInt().
Referenced by NetlistElementsTreeModel().
moduleTypeChanged()
void hal::NetlistElementsTreeModel::moduleTypeChanged (Module * m)
Definition at line 214 of file netlist_elements_tree_model.cpp.
References QAbstractItemModel::createIndex(), QAbstractItemModel::dataChanged(), QString::fromStdString(), hal::Module::get_type(), hal::BaseTreeModel::getIndexFromItem(), QModelIndex::internalPointer(), QObject::Q_EMIT(), QModelIndex::row(), and sTypeColumn.
Referenced by NetlistElementsTreeModel().
netNameChanged()
void hal::NetlistElementsTreeModel::netNameChanged (Net * n)
Definition at line 180 of file netlist_elements_tree_model.cpp.
References QAbstractItemModel::createIndex(), QAbstractItemModel::dataChanged(), QString::fromStdString(), hal::BaseTreeModel::getIndexFromItem(), QModelIndex::internalPointer(), test::n, QObject::Q_EMIT(), QModelIndex::row(), and sNameColumn.
netRemoved()
void hal::NetlistElementsTreeModel::netRemoved (Net * n)
Definition at line 191 of file netlist_elements_tree_model.cpp.
References QAbstractItemModel::beginRemoveRows(), QAbstractItemModel::endRemoveRows(), hal::BaseTreeModel::getIndexFromItem(), test::n, and QObject::parent().
Referenced by NetlistElementsTreeModel().
numberOfSubmodulesChanged
void hal::NetlistElementsTreeModel::numberOfSubmodulesChanged (const int newNumber) signal
Signal that is emitted when the number of direct submodules changed in the case the displayed content is displayed by using the method setModule().
Parameters
newNumber - The new number of direct submodules.
Referenced by moduleSubmoduleAdded(), moduleSubmoduleRemoved(), and setModule().
setContent()
void hal::NetlistElementsTreeModel::setContent (QList< int > modIds, QList< int > gateIds, QList< int > netIds, bool displayModulesRecursive = true, bool showGatesInSubmods = true, bool showNetsInSubmods = true)
Sets the module's content to the specified ids. Adds all Elements to the top level of the tree. As of now, the model does not check the consistency of the items. For instance, if modules that shall explicity be displayed are already within other given modules. This also applies to gates. This can result in duplicate items that are displayed at the top level as well as within a module hirarchy.
Parameters
modIds - Ids of modules.
gateIds - Ids of gates.
netIds - Ids of nets.
displayModulesRecursive - True to add all submodules of the given module list to the tree.
showGatesInSubmods - True to show the gates in the submodules that were added if displayModulesRecursive = true.
showNetsInSubmods - True to show the net in the submodules that were added if displayModulesRecursive = true.
Definition at line 65 of file netlist_elements_tree_model.cpp.
References hal::TreeItem::appendChild(), QAbstractItemModel::beginResetModel(), clear(), QAbstractItemModel::endResetModel(), QString::fromStdString(), QVariant::fromValue(), gate, hal::Netlist::get_gate_by_id(), hal::Gate::get_id(), hal::Module::get_id(), hal::Netlist::get_module_by_id(), hal::Gate::get_name(), hal::Module::get_name(), hal::GateType::get_name(), hal::Netlist::get_net_by_id(), hal::Module::get_type(), hal::Gate::get_type(), hal::gNetlist, keyItemType, keyRepresentedID, module, hal::BaseTreeModel::mRootItem, net, net, and hal::TreeItem::setAdditionalData().
Referenced by setModule().
setModule()
void hal::NetlistElementsTreeModel::setModule (Module * mod, bool showGates = true, bool showNets = true, bool displayModulesRecursive = true)
Updates the model's content to the given module. Convenient functions that can be used instead of the more general setContent() function.
Parameters
mod - The module to display.
showGates - True to add gates, False to show only module hierarchy.
showNets - True to add nets, False to show only module hierarchy.
displayModulesRecursive - True to show
Definition at line 119 of file netlist_elements_tree_model.cpp.
References QList::append(), hal::Module::get_gates(), hal::Module::get_id(), hal::Module::get_internal_nets(), hal::Module::get_submodules(), net, numberOfSubmodulesChanged(), QObject::Q_EMIT(), and setContent().
Member Data Documentation
keyItemType
const QString hal::NetlistElementsTreeModel::keyItemType = "type"
Definition at line 147 of file netlist_elements_tree_model.h.
Referenced by getTypeOfItem(), moduleGateAssigned(), moduleSubmoduleAdded(), and setContent().
keyRepresentedID
const QString hal::NetlistElementsTreeModel::keyRepresentedID = "id"
Definition at line 148 of file netlist_elements_tree_model.h.
Referenced by getRepresentedIdOfItem(), moduleGateAssigned(), moduleSubmoduleAdded(), moduleSubmoduleRemoved(), and setContent().
sIdColumn
const int hal::NetlistElementsTreeModel::sIdColumn = 1 static
Definition at line 143 of file netlist_elements_tree_model.h.
sNameColumn
const int hal::NetlistElementsTreeModel::sNameColumn = 0 static
Definition at line 142 of file netlist_elements_tree_model.h.
Referenced by gateNameChanged(), hal::ModuleElementsTree::handleContextMenuRequested(), moduleNameChanged(), and netNameChanged().
sTypeColumn
const int hal::NetlistElementsTreeModel::sTypeColumn = 2 static
Definition at line 144 of file netlist_elements_tree_model.h.
Referenced by hal::ModuleElementsTree::handleContextMenuRequested(), and moduleTypeChanged().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/module_details_widget/netlist_elements_tree_model.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/module_details_widget/netlist_elements_tree_model.cpp