HAL: subprocess::Popen Class Reference
subprocess::Popen Class Reference
#include <process.h>
Public Member Functions
template<typename... Args>
Popen (const std::string &cmd_args, Args &&... args)
template<typename... Args>
Popen (std::initializer_list< const char * > cmd_args, Args &&... args)
template<typename... Args>
Popen (std::vector< std::string > vargs_, Args &&... args)
void start_process () noexcept(false)
int pid () const noexcept
int retcode () const noexcept
int wait () noexcept(false)
int poll () noexcept(false)
void kill (int sig_num=9)
void set_out_buf_cap (size_t cap)
void set_err_buf_cap (size_t cap)
int send (const char *msg, size_t length)
int send (const std::string &msg)
int send (const std::vector< char > &msg)
std::pair< OutBuffer, ErrBuffer > communicate (const char *msg, size_t length)
std::pair< OutBuffer, ErrBuffer > communicate (const std::string &msg)
std::pair< OutBuffer, ErrBuffer > communicate (const std::vector< char > &msg)
std::pair< OutBuffer, ErrBuffer > communicate ()
FILE * input ()
FILE * output ()
FILE * error ()
void close_input ()
Stream close APIs.
void close_output ()
void close_error ()
Friends
struct detail::ArgumentDeducer
class detail::Child
Detailed Description
class: Popen This is the single most important class in the whole library and glues together all the helper classes to provide a common interface to the client.
API's provided by the class:
Popen({"cmd"}, output{..}, error{..}, cwd{..}, ....) Command provided as a sequence.
Popen("cmd arg1"m output{..}, error{..}, cwd{..}, ....) Command provided in a single string.
wait() - Wait for the child to exit.
retcode() - The return code of the exited child.
pid() - PID of the spawned child.
poll() - Check the status of the running child.
kill(sig_num) - Kill the child. SIGTERM used by default.
send(...) - Send input to the input channel of the child.
communicate(...) - Get the output/error from the child and close the channels from the parent side.
input() - Get the input channel/File pointer. Can be used for cutomizing the way of sending input to child.
output() - Get the output channel/File pointer. Usually used in case of redirection. See piping examples.
error() - Get the error channel/File poiner. Usually used in case of redirection.
start_process() - Start the child process. Only to be used when defer_spawn option was provided in Popen constructor.
Definition at line 1365 of file process.h.
Constructor & Destructor Documentation
Popen() [1/3]
template<typename... Args> subprocess::Popen::Popen (const std::string & cmd_args, Args &&... args) inline
Definition at line 1372 of file process.h.
Popen() [2/3]
template<typename... Args> subprocess::Popen::Popen (std::initializer_list< const char * > cmd_args, Args &&... args) inline
Definition at line 1385 of file process.h.
References control::args, and subprocess::detail::Streams::setup_comm_channels().
Popen() [3/3]
template<typename... Args> subprocess::Popen::Popen (std::vector< std::string > vargs_, Args &&... args) inline
Definition at line 1398 of file process.h.
References control::args, and subprocess::detail::Streams::setup_comm_channels().
Member Function Documentation
close_error()
void subprocess::Popen::close_error () inline
Definition at line 1509 of file process.h.
References subprocess::detail::Streams::error_.
close_input()
void subprocess::Popen::close_input () inline
Stream close APIs.
Definition at line 1501 of file process.h.
References subprocess::detail::Streams::input_.
close_output()
void subprocess::Popen::close_output () inline
Definition at line 1505 of file process.h.
References subprocess::detail::Streams::output_.
communicate() [1/4]
std::pair<OutBuffer, ErrBuffer> subprocess::Popen::communicate () inline
Definition at line 1482 of file process.h.
Referenced by communicate().
communicate() [2/4]
std::pair<OutBuffer, ErrBuffer> subprocess::Popen::communicate (const char * msg, size_t length) inline
Definition at line 1463 of file process.h.
References subprocess::detail::Streams::communicate(), and wait().
Referenced by subprocess::detail::check_output_impl().
communicate() [3/4]
std::pair<OutBuffer, ErrBuffer> subprocess::Popen::communicate (const std::string & msg) inline
Definition at line 1470 of file process.h.
References communicate().
communicate() [4/4]
std::pair<OutBuffer, ErrBuffer> subprocess::Popen::communicate (const std::vector< char > & msg) inline
Definition at line 1475 of file process.h.
References subprocess::detail::Streams::communicate(), and wait().
error()
FILE* subprocess::Popen::error () inline
Definition at line 1495 of file process.h.
References subprocess::detail::Streams::error().
input()
FILE* subprocess::Popen::input () inline
Definition at line 1487 of file process.h.
References subprocess::detail::Streams::input().
kill()
void subprocess::Popen::kill (int sig_num = 9) inline
Definition at line 1684 of file process.h.
output()
FILE* subprocess::Popen::output () inline
Definition at line 1491 of file process.h.
References subprocess::detail::Streams::output().
pid()
int subprocess::Popen::pid () const inline noexcept
Definition at line 1420 of file process.h.
poll()
int subprocess::Popen::poll () inline noexcept
Definition at line 1616 of file process.h.
retcode()
int subprocess::Popen::retcode () const inline noexcept
Definition at line 1425 of file process.h.
send() [1/3]
int subprocess::Popen::send (const char * msg, size_t length) inline
Definition at line 1448 of file process.h.
References subprocess::detail::Streams::send().
Referenced by hal::SMT::Z3::query(), hal::SMT::Boolector::query(), and send().
send() [2/3]
int subprocess::Popen::send (const std::string & msg) inline
Definition at line 1453 of file process.h.
References send().
send() [3/3]
int subprocess::Popen::send (const std::vector< char > & msg) inline
Definition at line 1458 of file process.h.
References subprocess::detail::Streams::send().
set_err_buf_cap()
void subprocess::Popen::set_err_buf_cap (size_t cap) inline
Definition at line 1443 of file process.h.
References subprocess::detail::Streams::set_err_buf_cap().
set_out_buf_cap()
void subprocess::Popen::set_out_buf_cap (size_t cap) inline
Definition at line 1438 of file process.h.
References subprocess::detail::Streams::set_out_buf_cap().
start_process()
void subprocess::Popen::start_process () inline noexcept
Definition at line 1575 of file process.h.
wait()
int subprocess::Popen::wait () inline noexcept
Definition at line 1590 of file process.h.
Referenced by subprocess::detail::call_impl(), and communicate().
Friends And Related Function Documentation
detail::ArgumentDeducer
friend struct detail::ArgumentDeducer friend
Definition at line 1368 of file process.h.
detail::Child
friend class detail::Child friend
Definition at line 1369 of file process.h.
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/include/hal_core/utilities/process.h