HAL: hal::SettingsItem Class Reference
hal::SettingsItem Class Reference abstract
HAL Gui » Settings System
The interface for the logical part of a setting.
#include <settings_item.h>
Signals
void valueChanged ()
Public Member Functions
SettingsItem (QObject *parent=nullptr)
virtual ~ SettingsItem ()
virtual QVariant value () const =0
virtual QVariant defaultValue () const =0
virtual void setValue (const QVariant &v)=0
virtual void setDefaultValue (const QVariant &dv)=0
virtual SettingsWidget * editWidget (QWidget *parent=nullptr)=0
virtual bool isDefaultValue () const
virtual QVariant persistToSettings () const
virtual void restoreFromSettings (const QVariant &val)
virtual bool isGlobal () const
virtual QString label () const
virtual QString description () const
virtual QString tag () const
virtual QString category () const
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Attributes
bool mIsGlobal
QString mLabel
QString mDescription
QString mTag
QString mCategory
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
The interface for the logical part of a setting.
The SettingsItem class provides an interface and commonly shared function for all kinds of specific settings. It is the logical part of a setting in comparison to the SettingsWidget, which represents the corresponding visual part. It -more precise the specific settings- connects to the SettingsManager.
Definition at line 45 of file settings_item.h.
Constructor & Destructor Documentation
SettingsItem()
hal::SettingsItem::SettingsItem (QObject * parent = nullptr) inline
The constructor.
Parameters
parent - The settings parent.
Definition at line 55 of file settings_item.h.
~ SettingsItem()
virtual hal::SettingsItem::~ SettingsItem () inline virtual
The destructor.
Definition at line 60 of file settings_item.h.
Member Function Documentation
category()
virtual QString hal::SettingsItem::category () const inline virtual
Get the category this setting belongs to.
Returns
The category.
Definition at line 174 of file settings_item.h.
References mCategory.
defaultValue()
virtual QVariant hal::SettingsItem::defaultValue () const pure virtual
Get the default value.
Returns
The default value.
Implemented in hal::SettingsItemKeybind, hal::SettingsItemDropdown, hal::SettingsItemCheckbox, hal::SettingsItemSlider, hal::SettingsItemSpinbox, and hal::SettingsItemText.
Referenced by hal::SettingsWidgetKeybind::handleSetDefaultValue(), hal::SettingsWidget::handleSetDefaultValue(), isDefaultValue(), and hal::SettingsWidget::trigger_setting_updated().
description()
virtual QString hal::SettingsItem::description () const inline virtual
Get the setting's description.
Returns
The setting's description.
Definition at line 154 of file settings_item.h.
References mDescription.
Referenced by hal::MainSettingsWidget::handleDescriptionUpdate().
editWidget()
virtual SettingsWidget* hal::SettingsItem::editWidget (QWidget * parent = nullptr) pure virtual
Get a corresponding SettingsWidget which holds a reference to the settings item.
Parameters
parent - The widget's soon to be parent.
Returns
A SettingsWidget able to modify the setting.
Implemented in hal::SettingsItemKeybind, hal::SettingsItemDropdown, hal::SettingsItemCheckbox, hal::SettingsItemSlider, hal::SettingsItemSpinbox, and hal::SettingsItemText.
isDefaultValue()
virtual bool hal::SettingsItem::isDefaultValue () const inline virtual
Compares the default value to the current value.
Returns
True if they are the same. False otherwise.
Definition at line 104 of file settings_item.h.
References defaultValue(), and value().
Referenced by hal::SettingsWidget::prepare(), and hal::SettingsWidget::SettingsWidget().
isGlobal()
virtual bool hal::SettingsItem::isGlobal () const inline virtual
Checks if the setting is a global setting.
Returns
True if it is, False otherwise.
Definition at line 134 of file settings_item.h.
References mIsGlobal.
Referenced by hal::SettingsItemCheckbox::SettingsItemCheckbox(), hal::SettingsItemDropdown::SettingsItemDropdown(), hal::SettingsItemKeybind::SettingsItemKeybind(), hal::SettingsItemSlider::SettingsItemSlider(), hal::SettingsItemSpinbox::SettingsItemSpinbox(), and hal::SettingsItemText::SettingsItemText().
label()
virtual QString hal::SettingsItem::label () const inline virtual
Get the settings label.
Returns
The label.
Definition at line 144 of file settings_item.h.
References mLabel.
Referenced by hal::KeybindEdit::doValidate(), hal::MainSettingsWidget::handleDescriptionUpdate(), hal::SettingsWidget::matchLabel(), hal::SettingsItemCheckbox::SettingsItemCheckbox(), hal::SettingsItemDropdown::SettingsItemDropdown(), hal::SettingsItemKeybind::SettingsItemKeybind(), hal::SettingsItemSlider::SettingsItemSlider(), hal::SettingsItemSpinbox::SettingsItemSpinbox(), hal::SettingsItemText::SettingsItemText(), and hal::SettingsWidget::SettingsWidget().
persistToSettings()
virtual QVariant hal::SettingsItem::persistToSettings () const inline virtual
Get the value of the item. See value().
Returns
The current value.
Reimplemented in hal::SettingsItemDropdown.
Definition at line 114 of file settings_item.h.
References value().
restoreFromSettings()
virtual void hal::SettingsItem::restoreFromSettings (const QVariant & val) inline virtual
Sets the value of the settings to the given value.
Parameters
val - The value to set.
Reimplemented in hal::SettingsItemDropdown.
Definition at line 124 of file settings_item.h.
References setValue().
Referenced by hal::SettingsManager::registerSetting().
setDefaultValue()
virtual void hal::SettingsItem::setDefaultValue (const QVariant & dv) pure virtual
Sets the default value of the setting.
Parameters
dv - The default value.
Implemented in hal::SettingsItemKeybind, hal::SettingsItemDropdown, hal::SettingsItemCheckbox, hal::SettingsItemSlider, hal::SettingsItemSpinbox, and hal::SettingsItemText.
Referenced by hal::SettingsManager::registerSetting().
setValue()
virtual void hal::SettingsItem::setValue (const QVariant & v) pure virtual
Sets the value of the setting.
Parameters
v - The value to set.
Implemented in hal::SettingsItemKeybind, hal::SettingsItemDropdown, hal::SettingsItemCheckbox, hal::SettingsItemSlider, hal::SettingsItemSpinbox, and hal::SettingsItemText.
Referenced by hal::SettingsWidget::acceptValue(), and restoreFromSettings().
tag()
virtual QString hal::SettingsItem::tag () const inline virtual
Get the setting's tag (key).
Returns
The tag (key).
Definition at line 164 of file settings_item.h.
References mTag.
Referenced by hal::SettingsManager::registerSetting(), hal::SettingsItemCheckbox::SettingsItemCheckbox(), hal::SettingsItemDropdown::SettingsItemDropdown(), hal::SettingsItemKeybind::SettingsItemKeybind(), hal::SettingsItemSlider::SettingsItemSlider(), hal::SettingsItemSpinbox::SettingsItemSpinbox(), and hal::SettingsItemText::SettingsItemText().
value()
virtual QVariant hal::SettingsItem::value () const pure virtual
Get the current value.
Returns
The current value.
Implemented in hal::SettingsItemKeybind, hal::SettingsItemDropdown, hal::SettingsItemCheckbox, hal::SettingsItemSlider, hal::SettingsItemSpinbox, and hal::SettingsItemText.
Referenced by hal::SettingsWidgetKeybind::handleRevertModification(), hal::SettingsWidget::handleRevertModification(), isDefaultValue(), hal::SettingsWidget::loadCurrentValue(), persistToSettings(), hal::SettingsWidget::prepare(), and hal::SettingsWidget::trigger_setting_updated().
valueChanged
void hal::SettingsItem::valueChanged () signal
Q_SIGNAL that should be commited when the value changes.
Referenced by hal::GraphicsScene::GraphicsScene(), hal::SettingsItemText::setValue(), hal::SettingsItemSpinbox::setValue(), hal::SettingsItemSlider::setValue(), hal::SettingsItemCheckbox::setValue(), hal::SettingsItemDropdown::setValue(), and hal::SettingsItemKeybind::setValue().
Member Data Documentation
mCategory
QString hal::SettingsItem::mCategory protected
Definition at line 191 of file settings_item.h.
Referenced by category(), hal::SettingsItemCheckbox::SettingsItemCheckbox(), hal::SettingsItemDropdown::SettingsItemDropdown(), hal::SettingsItemKeybind::SettingsItemKeybind(), hal::SettingsItemSlider::SettingsItemSlider(), hal::SettingsItemSpinbox::SettingsItemSpinbox(), and hal::SettingsItemText::SettingsItemText().
mDescription
QString hal::SettingsItem::mDescription protected
Definition at line 189 of file settings_item.h.
Referenced by description(), hal::SettingsItemCheckbox::SettingsItemCheckbox(), hal::SettingsItemDropdown::SettingsItemDropdown(), hal::SettingsItemKeybind::SettingsItemKeybind(), hal::SettingsItemSlider::SettingsItemSlider(), hal::SettingsItemSpinbox::SettingsItemSpinbox(), and hal::SettingsItemText::SettingsItemText().
mIsGlobal
bool hal::SettingsItem::mIsGlobal protected
Definition at line 187 of file settings_item.h.
Referenced by isGlobal(), hal::SettingsItemCheckbox::SettingsItemCheckbox(), hal::SettingsItemDropdown::SettingsItemDropdown(), hal::SettingsItemKeybind::SettingsItemKeybind(), hal::SettingsItemSlider::SettingsItemSlider(), hal::SettingsItemSpinbox::SettingsItemSpinbox(), and hal::SettingsItemText::SettingsItemText().
mLabel
QString hal::SettingsItem::mLabel protected
Definition at line 188 of file settings_item.h.
Referenced by label(), hal::SettingsItemCheckbox::SettingsItemCheckbox(), hal::SettingsItemDropdown::SettingsItemDropdown(), hal::SettingsItemKeybind::SettingsItemKeybind(), hal::SettingsItemSlider::SettingsItemSlider(), hal::SettingsItemSpinbox::SettingsItemSpinbox(), and hal::SettingsItemText::SettingsItemText().
mTag
QString hal::SettingsItem::mTag protected
Definition at line 190 of file settings_item.h.
Referenced by hal::SettingsItemCheckbox::SettingsItemCheckbox(), hal::SettingsItemDropdown::SettingsItemDropdown(), hal::SettingsItemKeybind::SettingsItemKeybind(), hal::SettingsItemSlider::SettingsItemSlider(), hal::SettingsItemSpinbox::SettingsItemSpinbox(), hal::SettingsItemText::SettingsItemText(), and tag().
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/plugins/gui/include/gui/settings/settings_items/settings_item.h