HAL: hal::CommentEntry Class Reference
hal::CommentEntry Class Reference
HAL Gui
The CommentEntry class encapsulated information related to a comment.
#include <comment_entry.h>
Public Member Functions
CommentEntry (Node n, QString text=QString(), QString header=QString())
CommentEntry (const QJsonObject &jsonObj)
~CommentEntry ()
void setHeader (QString newHeader)
void setText (QString newText)
void setDirty (bool dirty)
QString getHeader () const
QString getText () const
Node getNode () const
QDateTime getCreationTime () const
QDateTime getLastModifiedTime () const
QJsonObject toJson () const
bool isInvalid () const
void dump () const
QString getDateFormatString () const
Detailed Description
The CommentEntry class encapsulated information related to a comment.
This class holds all relvant information for a gui comment such as a header, the time of creation, and the text itself. For now only gates and modules can be associated with a comment.
Definition at line 42 of file comment_entry.h.
Constructor & Destructor Documentation
CommentEntry() [1/2]
hal::CommentEntry::CommentEntry (Node n, QString text = QString(), QString header = QString())
Definition at line 7 of file comment_entry.cpp.
References QDateTime::currentDateTime(), and QDateTime::toUTC().
CommentEntry() [2/2]
hal::CommentEntry::CommentEntry (const QJsonObject & jsonObj)
Definition at line 13 of file comment_entry.cpp.
References QJsonObject::contains(), QDateTime::fromString(), and Qt::ISODate.
~CommentEntry()
hal::CommentEntry::~CommentEntry () inline
Definition at line 47 of file comment_entry.h.
Member Function Documentation
dump()
void hal::CommentEntry::dump () const
Definition at line 95 of file comment_entry.cpp.
References hal::Node::id(), hal::Node::isGate(), QString::left(), QDateTime::toString(), and QIODevice::WriteOnly.
getCreationTime()
QDateTime hal::CommentEntry::getCreationTime () const
Definition at line 66 of file comment_entry.cpp.
getDateFormatString()
QString hal::CommentEntry::getDateFormatString () const
Definition at line 105 of file comment_entry.cpp.
Referenced by hal::CommentDialog::CommentDialog(), and hal::CommentItem::updateCurrentEntry().
getHeader()
QString hal::CommentEntry::getHeader () const
Definition at line 51 of file comment_entry.cpp.
Referenced by hal::CommentDialog::CommentDialog(), and hal::CommentItem::updateCurrentEntry().
getLastModifiedTime()
QDateTime hal::CommentEntry::getLastModifiedTime () const
Definition at line 71 of file comment_entry.cpp.
Referenced by hal::CommentDialog::CommentDialog(), and hal::CommentItem::updateCurrentEntry().
getNode()
Node hal::CommentEntry::getNode () const
Definition at line 61 of file comment_entry.cpp.
Referenced by hal::CommentManager::addComment(), and hal::CommentManager::deleteComment().
getText()
QString hal::CommentEntry::getText () const
Definition at line 56 of file comment_entry.cpp.
Referenced by hal::CommentDialog::CommentDialog(), and hal::CommentItem::updateCurrentEntry().
isInvalid()
bool hal::CommentEntry::isInvalid () const
Definition at line 90 of file comment_entry.cpp.
References hal::Node::isNull().
setDirty()
void hal::CommentEntry::setDirty (bool dirty)
Definition at line 46 of file comment_entry.cpp.
setHeader()
void hal::CommentEntry::setHeader (QString newHeader)
Definition at line 32 of file comment_entry.cpp.
References QDateTime::currentDateTime(), and QDateTime::toUTC().
setText()
void hal::CommentEntry::setText (QString newText)
Definition at line 39 of file comment_entry.cpp.
References QDateTime::currentDateTime(), and QDateTime::toUTC().
toJson()
QJsonObject hal::CommentEntry::toJson () const
Definition at line 76 of file comment_entry.cpp.
References hal::Node::id(), Qt::ISODate, QDateTime::toString(), and hal::Node::type().
Referenced by hal::CommentManager::serialize().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/comment_system/comment_entry.h
/home/runner/work/hal/hal/plugins/gui/src/comment_system/comment_entry.cpp