HAL: hal::ModuleSelectProxy Class Reference
hal::ModuleSelectProxy Class Reference
The ModuleSelectProxy class allows sorting and filtering of module tables.
#include <module_select_model.h>
Public Slots
void setSortMechanism (gui_utility::mSortMechanism sortMechanism)
void startSearch (QString text, int options) override
bool filterAcceptsRow (int source_row, const QModelIndex &source_parent) const override
Public Slots inherited from hal::SearchProxyModel
virtual void startSearch (QString text, int options)=0
Public Member Functions
ModuleSelectProxy (QObject *parent=nullptr)
Public Member Functions inherited from hal::SearchProxyModel
SearchProxyModel (QObject *parent=nullptr)
virtual QList< QString > getColumnNames ()
Public Member Functions inherited from QSortFilterProxyModel
QSortFilterProxyModel (QObject *parent)
virtual ~QSortFilterProxyModel ()
virtual void setSourceModel (QAbstractItemModel *sourceModel) override
virtual QModelIndex mapToSource (const QModelIndex &proxyIndex) const const override
virtual QModelIndex mapFromSource (const QModelIndex &sourceIndex) const const override
virtual QItemSelection mapSelectionToSource (const QItemSelection &proxySelection) const const override
virtual QItemSelection mapSelectionFromSource (const QItemSelection &sourceSelection) const const override
QRegExp filterRegExp () const const
QRegularExpression filterRegularExpression () const const
int filterKeyColumn () const const
void setFilterKeyColumn (int column)
Qt::CaseSensitivity filterCaseSensitivity () const const
void setFilterCaseSensitivity (Qt::CaseSensitivity cs)
Qt::CaseSensitivity sortCaseSensitivity () const const
void setSortCaseSensitivity (Qt::CaseSensitivity cs)
bool isSortLocaleAware () const const
void setSortLocaleAware (bool on)
int sortColumn () const const
Qt::SortOrder sortOrder () const const
bool dynamicSortFilter () const const
void setDynamicSortFilter (bool enable)
int sortRole () const const
void setSortRole (int role)
int filterRole () const const
void setFilterRole (int role)
bool isRecursiveFilteringEnabled () const const
void setRecursiveFilteringEnabled (bool recursive)
void setFilterRegExp (const QString &pattern)
void setFilterRegExp (const QRegExp &regExp)
void setFilterRegularExpression (const QString &pattern)
void setFilterRegularExpression (const QRegularExpression &regularExpression)
void setFilterWildcard (const QString &pattern)
void setFilterFixedString (const QString &pattern)
void clear ()
void invalidate ()
virtual QModelIndex index (int row, int column, const QModelIndex &parent) const const override
virtual QModelIndex parent (const QModelIndex &child) const const override
virtual QModelIndex sibling (int row, int column, const QModelIndex &idx) const const override
virtual int rowCount (const QModelIndex &parent) const const override
virtual int columnCount (const QModelIndex &parent) const const override
virtual bool hasChildren (const QModelIndex &parent) const const override
virtual QVariant data (const QModelIndex &index, int role) const const override
virtual bool setData (const QModelIndex &index, const QVariant &value, int role) override
virtual QVariant headerData (int section, Qt::Orientation orientation, int role) const const override
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role) override
virtual QMimeData * mimeData (const QModelIndexList &indexes) const const override
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) override
virtual bool insertRows (int row, int count, const QModelIndex &parent) override
virtual bool insertColumns (int column, int count, const QModelIndex &parent) override
virtual bool removeRows (int row, int count, const QModelIndex &parent) override
virtual bool removeColumns (int column, int count, const QModelIndex &parent) override
virtual void fetchMore (const QModelIndex &parent) override
virtual bool canFetchMore (const QModelIndex &parent) const const override
virtual Qt::ItemFlags flags (const QModelIndex &index) const const override
virtual QModelIndex buddy (const QModelIndex &index) const const override
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const override
virtual QSize span (const QModelIndex &index) const const override
virtual void sort (int column, Qt::SortOrder order) override
virtual QStringList mimeTypes () const const override
virtual Qt::DropActions supportedDropActions () const const override
void filterCaseSensitivityChanged (Qt::CaseSensitivity filterCaseSensitivity)
void sortCaseSensitivityChanged (Qt::CaseSensitivity sortCaseSensitivity)
void sortLocaleAwareChanged (bool sortLocaleAware)
void sortRoleChanged (int sortRole)
void filterRoleChanged (int filterRole)
void recursiveFilteringEnabledChanged (bool recursiveFilteringEnabled)
Public Member Functions inherited from QAbstractProxyModel
QAbstractProxyModel (QObject *parent)
virtual ~QAbstractProxyModel ()
QAbstractItemModel * sourceModel () const const
virtual bool submit () override
virtual void revert () override
virtual QMap< int, QVariant > itemData (const QModelIndex &proxyIndex) const const override
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles) override
virtual bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const const override
virtual Qt::DropActions supportedDragActions () const const override
void sourceModelChanged ()
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Member Functions
bool lessThan (const QModelIndex &sourceLeft, const QModelIndex &sourceRight) const override
Protected Member Functions inherited from hal::SearchProxyModel
bool isMatching (const QString searchString, const QString stringToCheck) const
Check if a string matches the SearchOptions.
bool checkRow (int sourceRow, const QModelIndex &sourceParent, int startIndex, int endIndex, int offset=0) const
Should be called inside filterAcceptsRow function and returns true if the source_row, source_parent matches given SearchOptions.
virtual bool checkRowRecursion (int sourceRow, const QModelIndex &sourceParent, int startIndex, int endIndex, int offset=0) const
Protected Member Functions inherited from QSortFilterProxyModel
virtual bool filterAcceptsRow (int source_row, const QModelIndex &source_parent) const const
virtual bool filterAcceptsColumn (int source_column, const QModelIndex &source_parent) const const
void filterChanged ()
void invalidateFilter ()
Protected Member Functions inherited from QAbstractProxyModel
void resetInternalData ()
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Static Protected Member Functions
static bool lessThan (const QColor &a, const QColor &b)
Additional Inherited Members
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Protected Attributes inherited from hal::SearchProxyModel
SearchOptions mSearchOptions
QString mSearchString
Properties inherited from QSortFilterProxyModel
filterRegExp
filterRegularExpression
filterKeyColumn
dynamicSortFilter
filterCaseSensitivity
sortCaseSensitivity
isSortLocaleAware
sortRole
filterRole
recursiveFilteringEnabled
Properties inherited from QAbstractProxyModel
sourceModel
Properties inherited from QObject
objectName
Detailed Description
The ModuleSelectProxy class allows sorting and filtering of module tables.
Definition at line 125 of file module_select_model.h.
Constructor & Destructor Documentation
ModuleSelectProxy()
hal::ModuleSelectProxy::ModuleSelectProxy (QObject * parent = nullptr)
Definition at line 161 of file module_select_model.cpp.
Member Function Documentation
filterAcceptsRow
bool hal::ModuleSelectProxy::filterAcceptsRow (int source_row, const QModelIndex & source_parent) const override slot
Definition at line 205 of file module_select_model.cpp.
References hal::SearchProxyModel::checkRow().
lessThan() [1/2]
bool hal::ModuleSelectProxy::lessThan (const QColor & a, const QColor & b) static protected
Definition at line 171 of file module_select_model.cpp.
References QColor::hue(), QColor::saturation(), and QColor::value().
Referenced by lessThan().
lessThan() [2/2]
bool hal::ModuleSelectProxy::lessThan (const QModelIndex & sourceLeft, const QModelIndex & sourceRight) const override protected virtual
Reimplemented from QSortFilterProxyModel.
Definition at line 184 of file module_select_model.cpp.
References QModelIndex::column(), hal::gui_utility::compare(), lessThan(), hal::ModuleSelectModel::moduleColor(), QModelIndex::row(), and QAbstractProxyModel::sourceModel.
setSortMechanism
void hal::ModuleSelectProxy::setSortMechanism (gui_utility::mSortMechanism sortMechanism) slot
Definition at line 166 of file module_select_model.cpp.
startSearch
void hal::ModuleSelectProxy::startSearch (QString text, int options) override slot
Definition at line 198 of file module_select_model.cpp.
References QSortFilterProxyModel::invalidateFilter(), hal::SearchProxyModel::mSearchOptions, and hal::SearchProxyModel::mSearchString.
Referenced by hal::ModuleDialog::ModuleDialog(), and hal::ModuleSelectView::ModuleSelectView().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/module_dialog/module_select_model.h
/home/runner/work/hal/hal/plugins/gui/src/module_dialog/module_select_model.cpp