HAL: hal::GroupingColorDelegate Class Reference
hal::GroupingColorDelegate Class Reference
HAL Gui » Utility Widgets » Grouping Widget
Displays a colored box for the GroupingManagerWidget.
#include <grouping_color_delegate.h>
Public Member Functions
GroupingColorDelegate (QObject *parent=0)
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const override
Public Member Functions inherited from QStyledItemDelegate
QStyledItemDelegate (QObject *parent)
virtual ~QStyledItemDelegate ()
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const const override
virtual void setEditorData (QWidget *editor, const QModelIndex &index) const const override
virtual void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const const override
virtual void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const const override
QItemEditorFactory * itemEditorFactory () const const
void setItemEditorFactory (QItemEditorFactory *factory)
virtual QString displayText (const QVariant &value, const QLocale &locale) const const
Public Member Functions inherited from QAbstractItemDelegate
QAbstractItemDelegate (QObject *parent)
virtual ~QAbstractItemDelegate ()
virtual void destroyEditor (QWidget *editor, const QModelIndex &index) const const
virtual bool helpEvent (QHelpEvent *event, QAbstractItemView *view, const QStyleOptionViewItem &option, const QModelIndex &index)
void commitData (QWidget *editor)
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
void sizeHintChanged (const QModelIndex &index)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Public Types inherited from QAbstractItemDelegate
enum EndEditHint
Static Public Member Functions inherited from QAbstractItemDelegate
QString elidedText (const QFontMetrics &fontMetrics, int width, Qt::TextElideMode mode, const QString &text)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemDelegate
NoHint
EditNextItem
EditPreviousItem
SubmitModelCache
RevertModelCache
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QStyledItemDelegate
virtual void initStyleOption (QStyleOptionViewItem *option, const QModelIndex &index) const const
virtual bool eventFilter (QObject *editor, QEvent *event) override
virtual bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index) override
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Displays a colored box for the GroupingManagerWidget.
QStyledItemDelegate used for displaying a colored box in the 'Color'-column within the grouping_manager_widget table.
Definition at line 38 of file grouping_color_delegate.h.
Constructor & Destructor Documentation
GroupingColorDelegate()
hal::GroupingColorDelegate::GroupingColorDelegate (QObject * parent = 0) inline
Constructor.
Parameters
parent - The parent widget
Definition at line 47 of file grouping_color_delegate.h.
Member Function Documentation
paint()
void hal::GroupingColorDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override virtual
Paints the colored box in the table cell.
Parameters
painter - The used painter
option - The used style options
index - The index of the grouping within the GroupingTableModel
Reimplemented from QStyledItemDelegate.
Definition at line 10 of file grouping_color_delegate.cpp.
References Qt::BackgroundRole, Qt::black, hal::GroupingTableModel::data(), QPainter::fillRect(), QRect::height(), QAbstractItemView::model(), option(), QObject::parent(), QRect::topLeft(), QVariant::value(), and QRect::width().
sizeHint()
QSize hal::GroupingColorDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const override virtual
Returns the sized needed by the delegate to display the colored box.
Parameters
option - The used style options
index - The index of the grouping within the GroupingTableModel
Returns
he sized needed by the delegate to display the colored box
Reimplemented from QStyledItemDelegate.
Definition at line 26 of file grouping_color_delegate.cpp.
References option().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/grouping/grouping_color_delegate.h
/home/runner/work/hal/hal/plugins/gui/src/grouping/grouping_color_delegate.cpp