HAL: hal::ModuleSelectPicker Class Reference
hal::ModuleSelectPicker Class Reference
The ModuleSelectPicker class instance gets spawned to pick module from graph.
#include <module_select_model.h>
Public Slots
void terminatePicker ()
void handleSelectionChanged (void *sender)
Signals
void triggerCursor (int icurs)
void modulesPicked (QSet< u32 > mods)
Public Member Functions
ModuleSelectPicker (ModuleSelectReceiver *receiver, QObject *parent=nullptr)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
The ModuleSelectPicker class instance gets spawned to pick module from graph.
Definition at line 155 of file module_select_model.h.
Constructor & Destructor Documentation
ModuleSelectPicker()
hal::ModuleSelectPicker::ModuleSelectPicker (ModuleSelectReceiver * receiver, QObject * parent = nullptr)
Definition at line 245 of file module_select_model.cpp.
References QObject::connect(), hal::gContentManager, hal::ContentManager::getGraphTabWidget(), hal::gSelectionRelay, hal::ModuleSelectReceiver::handleModulesPicked(), handleSelectionChanged(), modulesPicked(), hal::GraphTabWidget::PickModule, QObject::Q_EMIT(), hal::SelectionRelay::selectionChanged(), hal::GraphTabWidget::setSelectCursor(), terminatePicker(), triggerCursor(), and hal::GraphTabWidget::triggerTerminatePicker().
Member Function Documentation
handleSelectionChanged
void hal::ModuleSelectPicker::handleSelectionChanged (void * sender) slot
Definition at line 255 of file module_select_model.cpp.
References QString::arg(), QString::fromStdString(), hal::Module::get_id(), hal::Netlist::get_module_by_id(), hal::Module::get_name(), hal::gNetlist, hal::gSelectionRelay, QSet::insert(), hal::ModuleSelectExclude::isAccepted(), hal::SelectionRelay::numberSelectedItems(), hal::SelectionRelay::selectedModulesList(), QObject::sender(), terminatePicker(), and QMessageBox::warning().
Referenced by ModuleSelectPicker(), and terminatePicker().
modulesPicked
void hal::ModuleSelectPicker::modulesPicked (QSet< u32 > mods) signal
Referenced by ModuleSelectPicker(), and terminatePicker().
terminatePicker
void hal::ModuleSelectPicker::terminatePicker () slot
Definition at line 300 of file module_select_model.cpp.
References QObject::deleteLater(), QObject::disconnect(), hal::gContentManager, hal::ContentManager::getGraphTabWidget(), hal::gSelectionRelay, handleSelectionChanged(), modulesPicked(), QObject::Q_EMIT(), hal::GraphTabWidget::Select, hal::SelectionRelay::selectionChanged(), triggerCursor(), and hal::GraphTabWidget::triggerTerminatePicker().
Referenced by handleSelectionChanged(), and ModuleSelectPicker().
triggerCursor
void hal::ModuleSelectPicker::triggerCursor (int icurs) signal
Referenced by ModuleSelectPicker(), and terminatePicker().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/module_dialog/module_select_model.h
/home/runner/work/hal/hal/plugins/gui/src/module_dialog/module_select_model.cpp