HAL: subprocess::detail::Streams Class Reference
subprocess::detail::Streams Class Reference
#include <process.h>
Public Member Functions
Streams ()
void operator= (const Streams &)=delete
void setup_comm_channels ()
void cleanup_fds ()
void close_parent_fds ()
void close_child_fds ()
FILE * input ()
FILE * output ()
FILE * error ()
void input (FILE *fp)
void output (FILE *fp)
void error (FILE *fp)
void set_out_buf_cap (size_t cap)
void set_err_buf_cap (size_t cap)
int send (const char *msg, size_t length)
int send (const std::vector< char > &msg)
std::pair< OutBuffer, ErrBuffer > communicate (const char *msg, size_t length)
std::pair< OutBuffer, ErrBuffer > communicate (const std::vector< char > &msg)
Public Attributes
std::shared_ptr< FILE > input_ = nullptr
std::shared_ptr< FILE > output_ = nullptr
std::shared_ptr< FILE > error_ = nullptr
int bufsiz_ = 0
int write_to_child_ = -1
int read_from_parent_ = -1
int write_to_parent_ = -1
int read_from_child_ = -1
int err_write_ = -1
int err_read_ = -1
Detailed Description
This is a helper class to Popen. It takes care of management of all the file descriptors and file pointers. It dispatches of the communication aspects to the Communication class. Read through the data members to understand about the various file descriptors used.
Definition at line 1089 of file process.h.
Constructor & Destructor Documentation
Streams()
subprocess::detail::Streams::Streams () inline
Definition at line 1092 of file process.h.
Member Function Documentation
cleanup_fds()
void subprocess::detail::Streams::cleanup_fds () inline
Definition at line 1098 of file process.h.
References err_read_, err_write_, read_from_child_, read_from_parent_, write_to_child_, and write_to_parent_.
close_child_fds()
void subprocess::detail::Streams::close_child_fds () inline
Definition at line 1118 of file process.h.
References err_write_, read_from_parent_, and write_to_parent_.
close_parent_fds()
void subprocess::detail::Streams::close_parent_fds () inline
Definition at line 1111 of file process.h.
References err_read_, read_from_child_, and write_to_child_.
communicate() [1/2]
std::pair<OutBuffer, ErrBuffer> subprocess::detail::Streams::communicate (const char * msg, size_t length) inline
Definition at line 1143 of file process.h.
References subprocess::detail::Communication::communicate().
Referenced by subprocess::Popen::communicate().
communicate() [2/2]
std::pair<OutBuffer, ErrBuffer> subprocess::detail::Streams::communicate (const std::vector< char > & msg) inline
Definition at line 1146 of file process.h.
References subprocess::detail::Communication::communicate().
error() [1/2]
FILE* subprocess::detail::Streams::error () inline
Definition at line 1127 of file process.h.
References error_.
Referenced by subprocess::detail::Communication::communicate(), subprocess::Popen::error(), and setup_comm_channels().
error() [2/2]
void subprocess::detail::Streams::error (FILE * fp) inline
Definition at line 1131 of file process.h.
References error_.
input() [1/2]
FILE* subprocess::detail::Streams::input () inline
Definition at line 1125 of file process.h.
References input_.
Referenced by subprocess::detail::Communication::communicate(), subprocess::Popen::input(), subprocess::detail::Communication::send(), and setup_comm_channels().
input() [2/2]
void subprocess::detail::Streams::input (FILE * fp) inline
Definition at line 1129 of file process.h.
References input_.
operator=()
void subprocess::detail::Streams::operator= (const Streams &) delete
output() [1/2]
FILE* subprocess::detail::Streams::output () inline
Definition at line 1126 of file process.h.
References output_.
Referenced by subprocess::detail::Communication::communicate(), subprocess::Popen::output(), and setup_comm_channels().
output() [2/2]
void subprocess::detail::Streams::output (FILE * fp) inline
Definition at line 1130 of file process.h.
References output_.
send() [1/2]
int subprocess::detail::Streams::send (const char * msg, size_t length) inline
Definition at line 1137 of file process.h.
References subprocess::detail::Communication::send().
Referenced by subprocess::Popen::send().
send() [2/2]
int subprocess::detail::Streams::send (const std::vector< char > & msg) inline
Definition at line 1140 of file process.h.
References subprocess::detail::Communication::send().
set_err_buf_cap()
void subprocess::detail::Streams::set_err_buf_cap (size_t cap) inline
Definition at line 1134 of file process.h.
References subprocess::detail::Communication::set_err_buf_cap().
Referenced by subprocess::Popen::set_err_buf_cap().
set_out_buf_cap()
void subprocess::detail::Streams::set_out_buf_cap (size_t cap) inline
Definition at line 1133 of file process.h.
References subprocess::detail::Communication::set_out_buf_cap().
Referenced by subprocess::Popen::set_out_buf_cap().
setup_comm_channels()
void subprocess::detail::Streams::setup_comm_channels () inline
Definition at line 1806 of file process.h.
References bufsiz_, err_read_, error(), input(), output(), read_from_child_, and write_to_child_.
Referenced by subprocess::Popen::Popen().
Member Data Documentation
bufsiz_
int subprocess::detail::Streams::bufsiz_ = 0
Definition at line 1166 of file process.h.
Referenced by subprocess::detail::ArgumentDeducer::set_option(), and setup_comm_channels().
err_read_
int subprocess::detail::Streams::err_read_ = -1
Definition at line 1180 of file process.h.
Referenced by cleanup_fds(), close_parent_fds(), subprocess::detail::ArgumentDeducer::set_option(), and setup_comm_channels().
err_write_
int subprocess::detail::Streams::err_write_ = -1
Definition at line 1179 of file process.h.
Referenced by cleanup_fds(), close_child_fds(), and subprocess::detail::ArgumentDeducer::set_option().
error_
std::shared_ptr<FILE> subprocess::detail::Streams::error_ = nullptr
Definition at line 1154 of file process.h.
Referenced by subprocess::Popen::close_error(), subprocess::detail::Communication::communicate(), and error().
input_
std::shared_ptr<FILE> subprocess::detail::Streams::input_ = nullptr
Definition at line 1152 of file process.h.
Referenced by subprocess::Popen::close_input(), subprocess::detail::Communication::communicate(), and input().
output_
std::shared_ptr<FILE> subprocess::detail::Streams::output_ = nullptr
Definition at line 1153 of file process.h.
Referenced by subprocess::Popen::close_output(), subprocess::detail::Communication::communicate(), and output().
read_from_child_
int subprocess::detail::Streams::read_from_child_ = -1
Definition at line 1176 of file process.h.
Referenced by cleanup_fds(), close_parent_fds(), subprocess::detail::ArgumentDeducer::set_option(), and setup_comm_channels().
read_from_parent_
int subprocess::detail::Streams::read_from_parent_ = -1
Definition at line 1172 of file process.h.
Referenced by cleanup_fds(), close_child_fds(), and subprocess::detail::ArgumentDeducer::set_option().
write_to_child_
int subprocess::detail::Streams::write_to_child_ = -1
Definition at line 1171 of file process.h.
Referenced by cleanup_fds(), close_parent_fds(), subprocess::detail::ArgumentDeducer::set_option(), and setup_comm_channels().
write_to_parent_
int subprocess::detail::Streams::write_to_parent_ = -1
Definition at line 1175 of file process.h.
Referenced by cleanup_fds(), close_child_fds(), subprocess::detail::Child::execute_child(), and subprocess::detail::ArgumentDeducer::set_option().
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/include/hal_core/utilities/process.h