HAL: hal::GuiApi Class Reference
hal::GuiApi Class Reference
HAL Gui
Interface to interact with the gui itself.
#include <gui_api.h>
Signals
void navigationRequested ()
Public Member Functions
GuiApi ()
std::vector< u32 > getSelectedGateIds ()
std::vector< u32 > getSelectedNetIds ()
std::vector< u32 > getSelectedModuleIds ()
std::tuple< std::vector< u32 >, std::vector< u32 >, std::vector< u32 > > getSelectedItemIds ()
std::vector< Gate * > getSelectedGates ()
std::vector< Net * > getSelectedNets ()
std::vector< Module * > getSelectedModules ()
std::tuple< std::vector< Gate * >, std::vector< Net * >, std::vector< Module * > > getSelectedItems ()
void selectGate (u32 gate_id, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectGate (const std::vector< u32 > &gate_ids, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectGate (Gate *gate, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectGate (const std::vector< Gate * > &gates, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectNet (u32 netId, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectNet (const std::vector< u32 > &net_ids, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectNet (Net *net, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectNet (const std::vector< Net * > &nets, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectModule (u32 module_id, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectModule (const std::vector< u32 > &module_ids, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectModule (Module *module, bool clear_current_selection=true, bool navigate_to_selection=true)
void selectModule (const std::vector< Module * > &modules, bool clear_current_selection=true, bool navigate_to_selection=true)
void select (Gate *gate, bool clear_current_selection=true, bool navigate_to_selection=true)
void select (Net *net, bool clear_current_selection=true, bool navigate_to_selection=true)
void select (Module *module, bool clear_current_selection=true, bool navigate_to_selection=true)
void select (const std::vector< Gate * > &gates, bool clear_current_selection=true, bool navigate_to_selection=true)
void select (const std::vector< Net * > &nets, bool clear_current_selection=true, bool navigate_to_selection=true)
void select (const std::vector< Module * > &modules, bool clear_current_selection=true, bool navigate_to_selection=true)
void select (const std::vector< u32 > &gate_ids, const std::vector< u32 > &net_ids, const std::vector< u32 > &module_ids, bool clear_current_selection=true, bool navigate_to_selection=true)
void select (const std::vector< Gate * > &gates, const std::vector< Net * > &nets, const std::vector< Module * > &modules, bool clear_current_selection=true, bool navigate_to_selection=true)
void deselectGate (u32 gate_id)
void deselectGate (const std::vector< u32 > &gate_ids)
void deselectGate (Gate *gate)
void deselectGate (const std::vector< Gate * > &gates)
void deselectNet (u32 netId)
void deselectNet (const std::vector< u32 > &net_ids)
void deselectNet (Net *net)
void deselectNet (const std::vector< Net * > &nets)
void deselectModule (u32 module_id)
void deselectModule (const std::vector< u32 > &module_ids)
void deselectModule (Module *module)
void deselectModule (const std::vector< Module * > &modules)
void deselectAllItems ()
void deselect (Gate *gate)
void deselect (Net *net)
void deselect (Module *module)
void deselect (const std::vector< Gate * > &gates)
void deselect (const std::vector< Net * > &nets)
void deselect (const std::vector< Module * > &modules)
void deselect (const std::vector< u32 > &gate_ids, const std::vector< u32 > &net_ids, const std::vector< u32 > &module_ids)
void deselect (const std::vector< Gate * > &gates, const std::vector< Net * > &nets, const std::vector< Module * > &modules)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Interface to interact with the gui itself.
The GuiApi is a class that contains several functions to simulate various actions within the gui like selecting a graphical item (e.g. a gate) or to get a list of all currently selected items.
Its main purpose is NOT to create an easier interface for other gui classes. Instead it implements the API that is used by the python context to provide access to the gui features in the python console and the python code editor execution.
Definition at line 92 of file gui_api.h.
Constructor & Destructor Documentation
GuiApi()
hal::GuiApi::GuiApi ()
Constructor.
Definition at line 27 of file gui_api.cpp.
References hal::gSelectionRelay, and hal::SelectionRelay::registerSender().
Member Function Documentation
deselect() [1/8]
void hal::GuiApi::deselect (const std::vector< Gate * > & gates)
Removes multiple gates from the selection.
Parameters
gates - A list of gates. These gates will be removed from the selection.
Definition at line 415 of file gui_api.cpp.
References deselectGate().
deselect() [2/8]
void hal::GuiApi::deselect (const std::vector< Gate * > & gates, const std::vector< Net * > & nets, const std::vector< Module * > & modules)
Removes multiple gates, nets and modules from the selection.
Parameters
gates - A list of gates. These gates will be removed from the selection.
nets - A list of nets. These nets will be removed from the selection.
modules - A list of modules. These modules will be removed from the selection.
Definition at line 436 of file gui_api.cpp.
References deselectGate(), deselectModule(), and deselectNet().
deselect() [3/8]
void hal::GuiApi::deselect (const std::vector< Module * > & modules)
Removes multiple modules from the selection.
Parameters
modules - A list of modules. These modules will be removed from the selection.
Definition at line 424 of file gui_api.cpp.
References deselectModule().
deselect() [4/8]
void hal::GuiApi::deselect (const std::vector< Net * > & nets)
Removes multiple nets from the selection.
Parameters
nets - A list of nets. These nets will be removed from the selection.
Definition at line 419 of file gui_api.cpp.
References deselectNet().
deselect() [5/8]
void hal::GuiApi::deselect (const std::vector< u32 > & gate_ids, const std::vector< u32 > & net_ids, const std::vector< u32 > & module_ids)
Removes multiple gates, nets and modules that are specified by their id from the selection.
Parameters
gate_ids - A list of gate ids. These gates will be removed from the selection.
net_ids - A list of net ids. These nets will be removed from the selection.
module_ids - A list of module ids. These modules will be removed from the selection.
Definition at line 429 of file gui_api.cpp.
References deselectGate(), deselectModule(), and deselectNet().
deselect() [6/8]
void hal::GuiApi::deselect (Gate * gate)
Removes the specified gate from the selection.
Parameters
gate - The gate that will be removed from the selection
Definition at line 401 of file gui_api.cpp.
References deselectGate().
Referenced by hal::PYBIND11_PLUGIN().
deselect() [7/8]
void hal::GuiApi::deselect (Module * module)
Removes the specified module from the selection.
Parameters
module - The module that will be removed from the selection
Definition at line 410 of file gui_api.cpp.
References deselectModule(), and hal::ShortestPath::module().
deselect() [8/8]
void hal::GuiApi::deselect (Net * net)
Removes the specified net from the selection.
Parameters
net - The net that will be removed from the selection
Definition at line 406 of file gui_api.cpp.
References deselectNet(), and net.
deselectAllItems()
void hal::GuiApi::deselectAllItems ()
Clears the current selection.
Definition at line 443 of file gui_api.cpp.
References hal::SelectionRelay::clearAndUpdate(), and hal::gSelectionRelay.
Referenced by hal::PYBIND11_PLUGIN().
deselectGate() [1/4]
void hal::GuiApi::deselectGate (const std::vector< Gate * > & gates)
Removes multiple gates from the selection.
Parameters
gates - A list of gates. These gates will be removed from the selection.
Definition at line 302 of file gui_api.cpp.
References QSet::end(), QSet::erase(), QSet::find(), hal::gNetlist, hal::gSelectionRelay, hal::Netlist::is_gate_in_netlist(), hal::SelectionRelay::relaySelectionChanged(), hal::SelectionRelay::selectedGates(), and hal::SelectionRelay::setSelectedGates().
deselectGate() [2/4]
void hal::GuiApi::deselectGate (const std::vector< u32 > & gate_ids)
Removes multiple gates that are specified by their id from the selection.
Parameters
gate_ids - A list of gate ids. These gates will be removed from the selection.
Definition at line 319 of file gui_api.cpp.
References deselectGate().
deselectGate() [3/4]
void hal::GuiApi::deselectGate (Gate * gate)
Removes the specified gate from the selection.
Parameters
gate - The gate that will be removed from the selection
Definition at line 288 of file gui_api.cpp.
References hal::Gate::get_id(), hal::gNetlist, hal::gSelectionRelay, hal::Netlist::is_gate_in_netlist(), hal::SelectionRelay::relaySelectionChanged(), and hal::SelectionRelay::removeGate().
deselectGate() [4/4]
void hal::GuiApi::deselectGate (u32 gate_id)
Removes the gate with the specified id from the selection.
Parameters
gate_id - The id of the gate that will be removed from the selection
Definition at line 297 of file gui_api.cpp.
References hal::Netlist::get_gate_by_id(), and hal::gNetlist.
Referenced by deselect(), deselectGate(), and hal::PYBIND11_PLUGIN().
deselectModule() [1/4]
void hal::GuiApi::deselectModule (const std::vector< Module * > & modules)
Removes multiple modules from the selection.
Parameters
modules - A list of modules. These modules will be removed from the selection.
Definition at line 378 of file gui_api.cpp.
References QSet::end(), QSet::erase(), QSet::find(), hal::Module::get_id(), hal::gNetlist, hal::gSelectionRelay, hal::Netlist::is_module_in_netlist(), hal::ShortestPath::module(), hal::SelectionRelay::relaySelectionChanged(), hal::SelectionRelay::selectedModules(), and hal::SelectionRelay::setSelectedModules().
deselectModule() [2/4]
void hal::GuiApi::deselectModule (const std::vector< u32 > & module_ids)
Removes multiple modules that are specified by their id from the selection.
Parameters
module_ids - A list of module ids. These modules will be removed from the selection.
Definition at line 394 of file gui_api.cpp.
References deselectModule().
deselectModule() [3/4]
void hal::GuiApi::deselectModule (Module * module)
Removes the specified module from the selection.
Parameters
module - The module that will be removed from the selection
Definition at line 364 of file gui_api.cpp.
References hal::Module::get_id(), hal::gNetlist, hal::gSelectionRelay, hal::Netlist::is_module_in_netlist(), hal::ShortestPath::module(), hal::SelectionRelay::relaySelectionChanged(), and hal::SelectionRelay::removeModule().
deselectModule() [4/4]
void hal::GuiApi::deselectModule (u32 module_id)
Removes the module with the specified id from the selection.
Parameters
module_id - The id of the module that will be removed from the selection
Definition at line 373 of file gui_api.cpp.
References hal::Netlist::get_module_by_id(), and hal::gNetlist.
Referenced by deselect(), deselectModule(), and hal::PYBIND11_PLUGIN().
deselectNet() [1/4]
void hal::GuiApi::deselectNet (const std::vector< Net * > & nets)
Removes multiple nets from the selection.
Parameters
nets - A list of nets. These nets will be removed from the selection.
Definition at line 340 of file gui_api.cpp.
References QSet::end(), QSet::erase(), QSet::find(), hal::gNetlist, hal::gSelectionRelay, hal::Netlist::is_net_in_netlist(), net, hal::SelectionRelay::relaySelectionChanged(), hal::SelectionRelay::selectedNets(), and hal::SelectionRelay::setSelectedNets().
deselectNet() [2/4]
void hal::GuiApi::deselectNet (const std::vector< u32 > & net_ids)
Removes multiple nets that are specified by their id from the selection.
Parameters
net_ids - A list of net ids. These nets will be removed from the selection.
Definition at line 357 of file gui_api.cpp.
References deselectNet().
deselectNet() [3/4]
void hal::GuiApi::deselectNet (Net * net)
Removes the specified net from the selection.
Parameters
net - The net that will be removed from the selection
Definition at line 326 of file gui_api.cpp.
References hal::gNetlist, hal::gSelectionRelay, hal::Netlist::is_net_in_netlist(), net, hal::SelectionRelay::relaySelectionChanged(), and hal::SelectionRelay::removeNet().
deselectNet() [4/4]
void hal::GuiApi::deselectNet (u32 netId)
Removes the net with the specified id from the selection.
Parameters
netId - The id of the net that will be removed from the selection
Definition at line 335 of file gui_api.cpp.
References hal::Netlist::get_net_by_id(), and hal::gNetlist.
Referenced by deselect(), deselectNet(), and hal::PYBIND11_PLUGIN().
getSelectedGateIds()
std::vector< u32 > hal::GuiApi::getSelectedGateIds ()
Gets a list that contains the ids of all currently selected gates. The ids are not sorted in any way.
Returns
the ids of all selected gates
Definition at line 32 of file gui_api.cpp.
References hal::gSelectionRelay, and hal::SelectionRelay::selectedGatesVector().
Referenced by getSelectedItemIds(), and hal::PYBIND11_PLUGIN().
getSelectedGates()
std::vector< Gate * > hal::GuiApi::getSelectedGates ()
Gets a list of all currently selected gates. The gates are not sorted in any meaningful way.
Returns
all selected gates
Definition at line 52 of file gui_api.cpp.
References hal::Netlist::get_gate_by_id(), hal::gNetlist, hal::gSelectionRelay, and hal::SelectionRelay::selectedGatesList().
Referenced by getSelectedItems(), and hal::PYBIND11_PLUGIN().
getSelectedItemIds()
std::tuple< std::vector< u32 >, std::vector< u32 >, std::vector< u32 > > hal::GuiApi::getSelectedItemIds ()
Gets a tuple [selectedGateIds, selectedNetIds, selectedModuleIds]. The element selectedGate/-Net/-ModuleIds is a list that contains the ids of all currently selected gates/nets/modules. The ids are not sorted in any meaningful way.
Returns
the tuple [selectedGateIds, selectedNetIds, selectedModuleIds]
Definition at line 47 of file gui_api.cpp.
References getSelectedGateIds(), getSelectedModuleIds(), and getSelectedNetIds().
Referenced by hal::PYBIND11_PLUGIN().
getSelectedItems()
std::tuple< std::vector< Gate * >, std::vector< Net * >, std::vector< Module * > > hal::GuiApi::getSelectedItems ()
Gets a tuple [selectedGates, selectedNets, selectedModules]. The element selectedGate/-Net/-Modules is a list of all currently selected gates/nets/modules. The items are not sorted in any meaningful way.
Returns
the tuple [selectedGates, selectedNets, selectedModules]
Definition at line 76 of file gui_api.cpp.
References getSelectedGates(), getSelectedModules(), and getSelectedNets().
Referenced by hal::PYBIND11_PLUGIN().
getSelectedModuleIds()
std::vector< u32 > hal::GuiApi::getSelectedModuleIds ()
Gets a list that contains the ids of all currently selected modules. The ids are not sorted in any meaningful way.
Returns
the ids of all selected modules
Definition at line 42 of file gui_api.cpp.
References hal::gSelectionRelay, and hal::SelectionRelay::selectedModulesVector().
Referenced by getSelectedItemIds(), and hal::PYBIND11_PLUGIN().
getSelectedModules()
std::vector< Module * > hal::GuiApi::getSelectedModules ()
Gets a list of all currently selected modules. The modules are not sorted in any meaningful way.
Returns
all selected modules
Definition at line 68 of file gui_api.cpp.
References hal::Netlist::get_module_by_id(), hal::gNetlist, hal::gSelectionRelay, and hal::SelectionRelay::selectedModulesList().
Referenced by getSelectedItems(), and hal::PYBIND11_PLUGIN().
getSelectedNetIds()
std::vector< u32 > hal::GuiApi::getSelectedNetIds ()
Gets a list that contains the ids of all currently selected nets. The ids are not sorted in any way.
Returns
the ids of all selected nets
Definition at line 37 of file gui_api.cpp.
References hal::gSelectionRelay, and hal::SelectionRelay::selectedNetsVector().
Referenced by getSelectedItemIds(), and hal::PYBIND11_PLUGIN().
getSelectedNets()
std::vector< Net * > hal::GuiApi::getSelectedNets ()
Gets a list of all currently selected nets. The nets are not sorted in any meaningful way.
Returns
all selected nets
Definition at line 60 of file gui_api.cpp.
References hal::Netlist::get_net_by_id(), hal::gNetlist, hal::gSelectionRelay, and hal::SelectionRelay::selectedNetsList().
Referenced by getSelectedItems(), and hal::PYBIND11_PLUGIN().
navigationRequested
void hal::GuiApi::navigationRequested () signal
Q_SIGNAL that is emitted whenever the view should be moved to a new selection.
Referenced by hal::GraphTabWidget::GraphTabWidget(), select(), selectGate(), selectModule(), and selectNet().
select() [1/8]
void hal::GuiApi::select (const std::vector< Gate * > & gates, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple gates. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
gates - A list of gates. These gates will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 248 of file gui_api.cpp.
References selectGate().
select() [2/8]
void hal::GuiApi::select (const std::vector< Gate * > & gates, const std::vector< Net * > & nets, const std::vector< Module * > & modules, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple gates, nets and modules. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
gates - A list of gates. These gates will be selected.
nets - A list of nets. These nets will be selected.
modules - A list of modules. These modules will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 275 of file gui_api.cpp.
References hal::SelectionRelay::clear(), hal::gSelectionRelay, navigationRequested(), QObject::Q_EMIT(), selectGate(), selectModule(), and selectNet().
select() [3/8]
void hal::GuiApi::select (const std::vector< Module * > & modules, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple modules. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
modules - A list of modules. These modules will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 257 of file gui_api.cpp.
References selectModule().
select() [4/8]
void hal::GuiApi::select (const std::vector< Net * > & nets, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple nets. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
nets - A list of nets. These nets will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 252 of file gui_api.cpp.
References selectNet().
select() [5/8]
void hal::GuiApi::select (const std::vector< u32 > & gate_ids, const std::vector< u32 > & net_ids, const std::vector< u32 > & module_ids, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple gates, nets and modules that are specified by their id. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
gate_ids - A list of gate ids. These gates will bse selected.
net_ids - A list of net ids. These nets will be selected.
module_ids - A list of module ids. These modules will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 262 of file gui_api.cpp.
References hal::SelectionRelay::clear(), hal::gSelectionRelay, navigationRequested(), QObject::Q_EMIT(), selectGate(), selectModule(), and selectNet().
select() [6/8]
void hal::GuiApi::select (Gate * gate, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects the specified gate. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
gate - The gate to select
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 234 of file gui_api.cpp.
References selectGate().
Referenced by hal::PYBIND11_PLUGIN().
select() [7/8]
void hal::GuiApi::select (Module * module, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects the specified module. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
module - The module to select
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 243 of file gui_api.cpp.
References hal::ShortestPath::module(), and selectModule().
select() [8/8]
void hal::GuiApi::select (Net * net, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects the specified net. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
net - The net to select
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 239 of file gui_api.cpp.
References net, and selectNet().
selectGate() [1/4]
void hal::GuiApi::selectGate (const std::vector< Gate * > & gates, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple gates. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
gates - A list of gates. These gates will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 102 of file gui_api.cpp.
References hal::SelectionRelay::clear(), hal::gNetlist, hal::gSelectionRelay, QSet::insert(), hal::Netlist::is_gate_in_netlist(), navigationRequested(), QObject::Q_EMIT(), hal::SelectionRelay::relaySelectionChanged(), hal::SelectionRelay::selectedGates(), hal::SelectionRelay::setSelectedGates(), and QSet::unite().
selectGate() [2/4]
void hal::GuiApi::selectGate (const std::vector< u32 > & gate_ids, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple gates that are specified by their id. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
gate_ids - A list of gate ids. These gates will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 125 of file gui_api.cpp.
References selectGate().
selectGate() [3/4]
void hal::GuiApi::selectGate (Gate * gate, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects the specified gate. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
gate - The gate to select
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 81 of file gui_api.cpp.
References hal::SelectionRelay::addGate(), hal::SelectionRelay::clear(), hal::SelectionRelay::Gate, hal::Gate::get_id(), hal::gNetlist, hal::gSelectionRelay, hal::Netlist::is_gate_in_netlist(), navigationRequested(), QObject::Q_EMIT(), hal::SelectionRelay::relaySelectionChanged(), and hal::SelectionRelay::setFocus().
selectGate() [4/4]
void hal::GuiApi::selectGate (u32 gate_id, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects a single gate with the specified id. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
gate_id - The id of the gate to select
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 97 of file gui_api.cpp.
References hal::Netlist::get_gate_by_id(), and hal::gNetlist.
Referenced by hal::PYBIND11_PLUGIN(), select(), and selectGate().
selectModule() [1/4]
void hal::GuiApi::selectModule (const std::vector< Module * > & modules, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple modules. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
modules - A list of modules. These modules will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 204 of file gui_api.cpp.
References hal::SelectionRelay::clear(), hal::Module::get_id(), hal::gNetlist, hal::gSelectionRelay, QSet::insert(), hal::Netlist::is_module_in_netlist(), hal::ShortestPath::module(), navigationRequested(), QObject::Q_EMIT(), hal::SelectionRelay::relaySelectionChanged(), hal::SelectionRelay::selectedModules(), hal::SelectionRelay::setSelectedModules(), and QSet::unite().
selectModule() [2/4]
void hal::GuiApi::selectModule (const std::vector< u32 > & module_ids, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple modules that are specified by their id. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
module_ids - A list of module ids. These modules will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 227 of file gui_api.cpp.
References selectModule().
selectModule() [3/4]
void hal::GuiApi::selectModule (Module * module, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects the specified module. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
module - The module to select
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 183 of file gui_api.cpp.
References hal::SelectionRelay::addModule(), hal::SelectionRelay::clear(), hal::Module::get_id(), hal::gNetlist, hal::gSelectionRelay, hal::Netlist::is_module_in_netlist(), hal::SelectionRelay::Module, hal::ShortestPath::module(), navigationRequested(), QObject::Q_EMIT(), hal::SelectionRelay::relaySelectionChanged(), and hal::SelectionRelay::setFocus().
selectModule() [4/4]
void hal::GuiApi::selectModule (u32 module_id, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects a single module with the specified id. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
module_id - The id of the module to select
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 199 of file gui_api.cpp.
References hal::Netlist::get_module_by_id(), and hal::gNetlist.
Referenced by hal::PYBIND11_PLUGIN(), select(), and selectModule().
selectNet() [1/4]
void hal::GuiApi::selectNet (const std::vector< Net * > & nets, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple nets. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
nets - A list of nets. These nets will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 153 of file gui_api.cpp.
References hal::SelectionRelay::clear(), hal::gNetlist, hal::gSelectionRelay, QSet::insert(), hal::Netlist::is_net_in_netlist(), navigationRequested(), net, QObject::Q_EMIT(), hal::SelectionRelay::relaySelectionChanged(), hal::SelectionRelay::selectedNets(), hal::SelectionRelay::setSelectedNets(), and QSet::unite().
selectNet() [2/4]
void hal::GuiApi::selectNet (const std::vector< u32 > & net_ids, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects multiple nets that are specified by their id. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
net_ids - A list of net ids. These nets will be selected.
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 176 of file gui_api.cpp.
References selectNet().
selectNet() [3/4]
void hal::GuiApi::selectNet (Net * net, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects the specified net. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
net - The net to select
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 132 of file gui_api.cpp.
References hal::SelectionRelay::addNet(), hal::SelectionRelay::clear(), hal::gNetlist, hal::gSelectionRelay, hal::Netlist::is_net_in_netlist(), navigationRequested(), hal::SelectionRelay::Net, net, QObject::Q_EMIT(), hal::SelectionRelay::relaySelectionChanged(), and hal::SelectionRelay::setFocus().
selectNet() [4/4]
void hal::GuiApi::selectNet (u32 netId, bool clear_current_selection = true, bool navigate_to_selection = true)
Selects a single net with the specified id. By default, the new selection will overwrite the old one and the view will move to the new selection. This behaviour can be changed with the parameters clear_current_selection and navigate_to_selection.
Parameters
netId - The id of the net to select
clear_current_selection - true (default): The old selection will be overwritten.
false: The new selection will be appended to the old one.
navigate_to_selection - true (default): The view will be moved to the new selection.
false: The view won't be moved.
Definition at line 148 of file gui_api.cpp.
References hal::Netlist::get_net_by_id(), and hal::gNetlist.
Referenced by hal::PYBIND11_PLUGIN(), select(), and selectNet().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/gui_api/gui_api.h
/home/runner/work/hal/hal/plugins/gui/src/gui_api/gui_api.cpp