HAL: hal::Simulation Class Reference
hal::Simulation Class Reference
#include <simulation.h>
Public Member Functions
BooleanFunction::Value get_net_value (const Net *net, u64 time) const
void add_event (const Event &event)
std::unordered_map< const Net *, std::vector< Event > > get_events () const
Friends
class NetlistSimulator
Detailed Description
Definition at line 35 of file simulation.h.
Member Function Documentation
add_event()
void hal::Simulation::add_event (const Event & event)
Adds a custom event to the simulation.
Parameters
[in] event - The event to add.
Definition at line 26 of file simulation.cpp.
Referenced by hal::SimulatorTest::parse_vcd(), and hal::PYBIND11_PLUGIN().
get_events()
std::unordered_map< const Net *, std::vector< Event > > hal::Simulation::get_events () const
Get all events of the simulation.
Returns
A map from net to associated events for that net sorted by time.
Definition at line 31 of file simulation.cpp.
Referenced by hal::SimulatorTest::cmp_sim_data(), hal::NetlistSimulator::generate_vcd(), and hal::PYBIND11_PLUGIN().
get_net_value()
BooleanFunction::Value hal::Simulation::get_net_value (const Net * net, u64 time) const
Get the signal value of a specific net at a specific point in time specified in picoseconds.
Parameters
[in] net - The net to inspect.
[in] time - The time in .
Returns
The net's signal value.
Definition at line 8 of file simulation.cpp.
References hal::ShortestPath::net(), hal::Event::new_value, and hal::Event::time.
Referenced by hal::PYBIND11_PLUGIN().
Friends And Related Function Documentation
NetlistSimulator
friend class NetlistSimulator friend
Definition at line 62 of file simulation.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/netlist_simulator/include/netlist_simulator/simulation.h
/home/runner/work/hal/hal/plugins/netlist_simulator/src/simulation.cpp