HAL: hal::FileActions Class Reference
hal::FileActions Class Reference
#include <file_actions.h>
Public Slots
void handleFileStatusChanged (bool gateLibraryAffected, bool isDirty)
void handleFileOpenChanged (bool gateLibraryAffected, bool isOpen)
Public Member Functions
FileActions (QWidget *parent=nullptr)
QString newFileIconPath () const
QString newFileIconStyle () const
QString openProjIconPath () const
QString openProjIconStyle () const
QString saveIconPath () const
QString saveAsIconPath () const
QString closeIconPath () const
QString closeIconStyle () const
QString enabledIconStyle () const
QString disabledIconStyle () const
void setNewFileIconPath (const QString &path)
void setNewFileIconStyle (const QString &style)
void setOpenProjIconPath (const QString &path)
void setOpenProjIconStyle (const QString &style)
void setSaveIconPath (const QString &path)
void setSaveAsIconPath (const QString &path)
void setCloseIconPath (const QString &path)
void setCloseIconStyle (const QString &style)
void setEnabledIconStyle (const QString &style)
void setDisabledIconStyle (const QString &style)
Action * create () const
Action * open () const
Action * close () const
Action * save () const
Action * saveAs () const
void setup (GateLibraryManager *glcw=nullptr, GuiPluginManager *plmgr=nullptr)
void repolish ()
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
virtual void setVisible (bool visible)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
virtual QSize sizeHint () const const
virtual QSize minimumSizeHint () const const
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Properties
QString saveIconPath
QString saveAsIconPath
QString enabledIconStyle
QString disabledIconStyle
QString closeIconPath
QString closeIconStyle
QString newFileIconPath
QString newFileIconStyle
QString openProjIconPath
QString openProjIconStyle
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Protected Member Functions inherited from QWidget
virtual bool event (QEvent *event) override
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void paintEvent (QPaintEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void closeEvent (QCloseEvent *event)
virtual void contextMenuEvent (QContextMenuEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void dragEnterEvent (QDragEnterEvent *event)
virtual void dragMoveEvent (QDragMoveEvent *event)
virtual void dragLeaveEvent (QDragLeaveEvent *event)
virtual void dropEvent (QDropEvent *event)
virtual void showEvent (QShowEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual void changeEvent (QEvent *event)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
virtual void inputMethodEvent (QInputMethodEvent *event)
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
virtual bool focusNextPrevChild (bool next)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Detailed Description
Definition at line 37 of file file_actions.h.
Constructor & Destructor Documentation
FileActions()
hal::FileActions::FileActions (QWidget * parent = nullptr)
Definition at line 14 of file file_actions.cpp.
References QShortcut::activated(), QObject::connect(), hal::gui_utility::getStyledSvgIcon(), hal::gFileStatusManager, handleFileOpenChanged(), handleFileStatusChanged(), QWidget::hide(), hal::SettingsItemKeybind::keySequenceChanged(), hal::FileStatusManager::open_changed(), QObject::parent(), repolish(), QAction::setIcon(), QShortcut::setKey(), setup(), hal::FileStatusManager::status_changed(), QVariant::toString(), QAction::trigger(), and hal::SettingsItemKeybind::value().
Member Function Documentation
close()
Action* hal::FileActions::close () const inline
Definition at line 226 of file file_actions.h.
closeIconPath()
QString hal::FileActions::closeIconPath () const inline
Q_PROPERTY READ function for the 'Close Project'-icon path.
Returns
the 'Close Project'-icon path
Definition at line 130 of file file_actions.h.
closeIconStyle()
QString hal::FileActions::closeIconStyle () const inline
Q_PROPERTY READ function for the 'Close Project'-icon style.
Returns
the 'Close Project'-icon style
Definition at line 137 of file file_actions.h.
create()
Action* hal::FileActions::create () const inline
Definition at line 224 of file file_actions.h.
disabledIconStyle()
QString hal::FileActions::disabledIconStyle () const inline
Q_PROPERTY READ function for the 'Disabled'-icon style.
Returns
the 'Disabled'-icon style
Definition at line 151 of file file_actions.h.
enabledIconStyle()
QString hal::FileActions::enabledIconStyle () const inline
Q_PROPERTY READ function for the 'Enabled'-icon style.
Returns
the 'Enabled'-icon style
Definition at line 144 of file file_actions.h.
handleFileOpenChanged
void hal::FileActions::handleFileOpenChanged (bool gateLibraryAffected, bool isOpen) slot
Definition at line 71 of file file_actions.cpp.
References QAction::setEnabled().
Referenced by FileActions().
handleFileStatusChanged
void hal::FileActions::handleFileStatusChanged (bool gateLibraryAffected, bool isDirty) slot
Definition at line 64 of file file_actions.cpp.
References QAction::setEnabled().
Referenced by FileActions().
newFileIconPath()
QString hal::FileActions::newFileIconPath () const inline
Q_PROPERTY READ function for the 'New File'-icon path.
Returns
the 'New File'-icon path
Definition at line 88 of file file_actions.h.
newFileIconStyle()
QString hal::FileActions::newFileIconStyle () const inline
Q_PROPERTY READ function for the 'New File'-icon style.
Returns
the 'New File'-icon style
Definition at line 95 of file file_actions.h.
open()
Action* hal::FileActions::open () const inline
Definition at line 225 of file file_actions.h.
openProjIconPath()
QString hal::FileActions::openProjIconPath () const inline
Q_PROPERTY READ function for the 'Open Proj'-icon path.
Returns
the 'Open Proj'-icon path
Definition at line 102 of file file_actions.h.
openProjIconStyle()
QString hal::FileActions::openProjIconStyle () const inline
Q_PROPERTY READ function for the 'Open Proj'-icon style.
Returns
the 'Open Proj'-icon style
Definition at line 109 of file file_actions.h.
repolish()
void hal::FileActions::repolish ()
Definition at line 56 of file file_actions.cpp.
References QStyle::polish(), QWidget::style(), and QStyle::unpolish().
Referenced by FileActions().
save()
Action* hal::FileActions::save () const inline
Definition at line 227 of file file_actions.h.
saveAs()
Action* hal::FileActions::saveAs () const inline
Definition at line 228 of file file_actions.h.
saveAsIconPath()
QString hal::FileActions::saveAsIconPath () const inline
Q_PROPERTY READ function for the 'SaveAs File'-icon path.
Returns
the 'SaveAsFile'-icon path
Definition at line 123 of file file_actions.h.
saveIconPath()
QString hal::FileActions::saveIconPath () const inline
Q_PROPERTY READ function for the 'Save File'-icon path.
Returns
the 'SaveFile'-icon path
Definition at line 116 of file file_actions.h.
setCloseIconPath()
void hal::FileActions::setCloseIconPath (const QString & path) inline
Q_PROPERTY WRITE function for the 'Close Project'-icon path.
Parameters
path - The new path
Definition at line 200 of file file_actions.h.
setCloseIconStyle()
void hal::FileActions::setCloseIconStyle (const QString & style) inline
Q_PROPERTY WRITE function for the 'Close Project'-icon style.
Parameters
style - The new style
Definition at line 208 of file file_actions.h.
References QWidget::style().
setDisabledIconStyle()
void hal::FileActions::setDisabledIconStyle (const QString & style) inline
Q_PROPERTY WRITE function for the 'Disabled'-icon style.
Parameters
style - The new style
Definition at line 222 of file file_actions.h.
References QWidget::style().
setEnabledIconStyle()
void hal::FileActions::setEnabledIconStyle (const QString & style) inline
Q_PROPERTY WRITE function for the 'Enabled'-icon style.
Parameters
style - The new style
Definition at line 215 of file file_actions.h.
References QWidget::style().
setNewFileIconPath()
void hal::FileActions::setNewFileIconPath (const QString & path) inline
Q_PROPERTY WRITE function for the 'New File'-icon path.
Parameters
path - The new path
Definition at line 158 of file file_actions.h.
setNewFileIconStyle()
void hal::FileActions::setNewFileIconStyle (const QString & style) inline
Q_PROPERTY WRITE function for the 'New File'-icon style.
Parameters
style - The new style
Definition at line 165 of file file_actions.h.
References QWidget::style().
setOpenProjIconPath()
void hal::FileActions::setOpenProjIconPath (const QString & path) inline
Q_PROPERTY WRITE function for the 'Open Proj'-icon path.
Parameters
path - The new path
Definition at line 172 of file file_actions.h.
setOpenProjIconStyle()
void hal::FileActions::setOpenProjIconStyle (const QString & style) inline
Q_PROPERTY WRITE function for the 'Open Proj'-icon style.
Parameters
style - The new style
Definition at line 179 of file file_actions.h.
References QWidget::style().
setSaveAsIconPath()
void hal::FileActions::setSaveAsIconPath (const QString & path) inline
Q_PROPERTY WRITE function for the 'SaveAs File'-icon path.
Parameters
path - The new path
Definition at line 193 of file file_actions.h.
setSaveIconPath()
void hal::FileActions::setSaveIconPath (const QString & path) inline
Q_PROPERTY WRITE function for the 'Save File'-icon path. yle
Parameters
path - The new path
Definition at line 186 of file file_actions.h.
setup()
void hal::FileActions::setup (GateLibraryManager * glcw = nullptr, GuiPluginManager * plmgr = nullptr)
Definition at line 78 of file file_actions.cpp.
References QObject::connect(), QObject::disconnect(), hal::gFileStatusManager, hal::MainWindow::handleActionCloseFile(), hal::MainWindow::handleActionGatelibraryManager(), hal::MainWindow::handleActionNew(), hal::MainWindow::handleActionOpenProject(), hal::GuiPluginManager::handleButtonCancel(), hal::GateLibraryManager::handleCancelClicked(), hal::GateLibraryManager::handleCreateAction(), hal::GuiPluginManager::handleLoadExternalPlugin(), hal::GateLibraryManager::handleSaveAction(), hal::GateLibraryManager::handleSaveAsAction(), hal::MainWindow::handleSaveAsTriggered(), hal::MainWindow::handleSaveTriggered(), hal::FileStatusManager::isGatelibModified(), hal::GateLibraryManager::isReadOnly(), hal::FileStatusManager::modifiedFilesExisting(), QAction::setDisabled(), QAction::setEnabled(), hal::Action::setText(), and QAction::triggered().
Referenced by FileActions().
Property Documentation
closeIconPath
QString hal::FileActions::closeIconPath read write
Definition at line 1 of file file_actions.h.
closeIconStyle
QString hal::FileActions::closeIconStyle read write
Definition at line 1 of file file_actions.h.
disabledIconStyle
QString hal::FileActions::disabledIconStyle read write
Definition at line 1 of file file_actions.h.
enabledIconStyle
QString hal::FileActions::enabledIconStyle read write
Definition at line 1 of file file_actions.h.
newFileIconPath
QString hal::FileActions::newFileIconPath read write
Definition at line 1 of file file_actions.h.
newFileIconStyle
QString hal::FileActions::newFileIconStyle read write
Definition at line 1 of file file_actions.h.
openProjIconPath
QString hal::FileActions::openProjIconPath read write
Definition at line 1 of file file_actions.h.
openProjIconStyle
QString hal::FileActions::openProjIconStyle read write
Definition at line 1 of file file_actions.h.
saveAsIconPath
QString hal::FileActions::saveAsIconPath read write
Definition at line 1 of file file_actions.h.
saveIconPath
QString hal::FileActions::saveIconPath read write
Definition at line 1 of file file_actions.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/main_window/file_actions.h
/home/runner/work/hal/hal/plugins/gui/src/main_window/file_actions.cpp