HAL: hal::SelectionTreeItemModule Class Reference
hal::SelectionTreeItemModule Class Reference
HAL Gui » Utility Widgets » Selection Details Widget
Tree item that represents a module.
#include <selection_tree_item.h>
Public Member Functions
SelectionTreeItemModule (u32 id_)
~SelectionTreeItemModule ()
virtual int childCount () const
virtual SelectionTreeItem * child (int row) const
virtual QVariant name () const
virtual QIcon icon () const
virtual QVariant boxType () const
virtual bool match (const QRegularExpression &regex) const
virtual void suppressedByFilterRecursion (QList< u32 > &modIds, QList< u32 > &gatIds, QList< u32 > &netIds, const QRegularExpression &regex) const
void addChild (SelectionTreeItem *cld)
bool isRoot () const
Public Member Functions inherited from hal::SelectionTreeItem
SelectionTreeItem (TreeItemType t=NullItem, u32 id_=0)
virtual ~SelectionTreeItem ()
TreeItemType itemType () const
u32 id () const
SelectionTreeItem * parent () const
void setParent (SelectionTreeItem *p)
virtual QVariant data (int column) const
bool isEqual (const SelectionTreeItem *sti) const
Protected Attributes
bool mIsRoot
QList< SelectionTreeItem * > mChildItem
Protected Attributes inherited from hal::SelectionTreeItem
TreeItemType mItemType
u32 mId
SelectionTreeItem * mParent
Additional Inherited Members
Public Types inherited from hal::SelectionTreeItem
enum TreeItemType {
NullItem, ModuleItem, GateItem, NetItem,
MaxItem
}
Detailed Description
Tree item that represents a module.
A subclass of the basic tree item class that represents a module of the netlist. It adds new hierarchical functionality since the module type item is the only item that can have children (and thus building the tree structure).
Definition at line 189 of file selection_tree_item.h.
Constructor & Destructor Documentation
SelectionTreeItemModule()
hal::SelectionTreeItemModule::SelectionTreeItemModule (u32 id_)
The constructor.
Parameters
id_ - The item's id. It is the same id as the module it represents.
Definition at line 74 of file selection_tree_item.cpp.
~SelectionTreeItemModule()
hal::SelectionTreeItemModule::~SelectionTreeItemModule ()
The destructor.
Definition at line 78 of file selection_tree_item.cpp.
References mChildItem.
Member Function Documentation
addChild()
void hal::SelectionTreeItemModule::addChild (SelectionTreeItem * cld)
Appends the given tree item to its children.
Parameters
cld - The item to append.
Definition at line 119 of file selection_tree_item.cpp.
References mChildItem, and hal::SelectionTreeItem::setParent().
Referenced by hal::SelectionTreeModel::fetchSelection().
boxType()
QVariant hal::SelectionTreeItemModule::boxType () const virtual
Returns the name of the module's type.
Returns
The name of the module's type.
Reimplemented from hal::SelectionTreeItem.
Definition at line 125 of file selection_tree_item.cpp.
References QString::fromStdString(), hal::Netlist::get_module_by_id(), hal::Module::get_type(), hal::gNetlist, hal::SelectionTreeItem::mId, and hal::ShortestPath::module().
child()
SelectionTreeItem * hal::SelectionTreeItemModule::child (int row) const virtual
Get the child from the given row.
Parameters
row - The row for which the child is requested.
Returns
The child for the given row. If the row is not in the childCount range, a nullptr is returned.
Reimplemented from hal::SelectionTreeItem.
Definition at line 101 of file selection_tree_item.cpp.
References mChildItem.
childCount()
int hal::SelectionTreeItemModule::childCount () const virtual
Get the number of child item (the items to which this item is the direct ancestor in the tree).
Returns
The number of children.
Reimplemented from hal::SelectionTreeItem.
Definition at line 95 of file selection_tree_item.cpp.
References mChildItem.
icon()
QIcon hal::SelectionTreeItemModule::icon () const virtual
Get the icon for a module type item.
Returns
The module specific icon.
Implements hal::SelectionTreeItem.
Definition at line 114 of file selection_tree_item.cpp.
References hal::SelectionDetailsIconProvider::instance(), hal::SelectionTreeItem::mId, and hal::SelectionDetailsIconProvider::ModuleIcon.
isRoot()
bool hal::SelectionTreeItemModule::isRoot () const
Checks if the module is the root item of the model.
Returns
True if the item is the root item. False otherwise.
Definition at line 90 of file selection_tree_item.cpp.
References mIsRoot.
Referenced by suppressedByFilterRecursion().
match()
bool hal::SelectionTreeItemModule::match (const QRegularExpression & regex) const virtual
Calls the match() function of its children and matches the regex against its id and name.
Parameters
regex - The regex to match against.
Returns
True if a match in either of the categories was found or if a child item returns True. False otherwise.
Reimplemented from hal::SelectionTreeItem.
Definition at line 132 of file selection_tree_item.cpp.
References hal::SelectionTreeItem::match(), and mChildItem.
Referenced by suppressedByFilterRecursion().
name()
QVariant hal::SelectionTreeItemModule::name () const virtual
Get the name of the item. The name is usually the name of the underlying netlist item.
Returns
The item's name.
Implements hal::SelectionTreeItem.
Definition at line 107 of file selection_tree_item.cpp.
References QString::fromStdString(), hal::Netlist::get_module_by_id(), hal::Module::get_name(), hal::gNetlist, hal::SelectionTreeItem::mId, and hal::ShortestPath::module().
suppressedByFilterRecursion()
void hal::SelectionTreeItemModule::suppressedByFilterRecursion (QList< u32 > & modIds, QList< u32 > & gatIds, QList< u32 > & netIds, const QRegularExpression & regex) const virtual
Matches itself against the given regex. If no mbrief boxTypeatch was found or the module item is the root of the model, the item inserts itself in the modIds list. This function is then invoked on all of its children.
Parameters
modIds - The list that contains the suppresed module-type items at the end.
gatIds - The list that contains the suppressed gate-type items at the end.
netIds - The list that contains the suppressed net-type items at the end.
regex - The regular expression to match the items against.
Implements hal::SelectionTreeItem.
Definition at line 140 of file selection_tree_item.cpp.
References QList::append(), isRoot(), match(), mChildItem, and hal::SelectionTreeItem::mId.
Referenced by hal::SelectionTreeModel::suppressedByFilter().
Member Data Documentation
mChildItem
QList<SelectionTreeItem*> hal::SelectionTreeItemModule::mChildItem protected
Definition at line 277 of file selection_tree_item.h.
Referenced by addChild(), child(), childCount(), match(), suppressedByFilterRecursion(), and ~SelectionTreeItemModule().
mIsRoot
bool hal::SelectionTreeItemModule::mIsRoot protected
Definition at line 276 of file selection_tree_item.h.
Referenced by isRoot(), and hal::SelectionTreeItemRoot::SelectionTreeItemRoot().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/tree_navigation/selection_tree_item.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/tree_navigation/selection_tree_item.cpp