HAL: hal::DrawNetThread Class Reference
hal::DrawNetThread Class Reference
#include <graph_layouter.h>
Public Member Functions
DrawNetThread (u32 id, GraphLayouter *parent)
u32 id () const
void run () override
Public Member Functions inherited from QThread
QThread (QObject *parent)
virtual ~QThread ()
void setPriority (QThread::Priority priority)
QThread::Priority priority () const const
bool isFinished () const const
bool isRunning () const const
void requestInterruption ()
bool isInterruptionRequested () const const
void setStackSize (uint stackSize)
uint stackSize () const const
void exit (int returnCode)
QAbstractEventDispatcher * eventDispatcher () const const
void setEventDispatcher (QAbstractEventDispatcher *eventDispatcher)
virtual bool event (QEvent *event) override
int loopLevel () const const
void start (QThread::Priority priority)
void terminate ()
void quit ()
bool wait (QDeadlineTimer deadline)
bool wait (unsigned long time)
void started ()
void finished ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Attributes
StandardGraphicsNet::Lines mLines
QList< QPointF > mKnots
Public Attributes inherited from QThread
IdlePriority
LowestPriority
LowPriority
NormalPriority
HighPriority
HighestPriority
TimeCriticalPriority
InheritPriority
Public Attributes inherited from QObject
typedef QObjectList
Additional Inherited Members
Public Types inherited from QThread
enum Priority
Static Public Member Functions inherited from QThread
Qt::HANDLE currentThreadId ()
QThread * currentThread ()
int idealThreadCount ()
void yieldCurrentThread ()
QThread * create (Function &&f, Args &&... args)
QThread * create (Function &&f)
void sleep (unsigned long secs)
void msleep (unsigned long msecs)
void usleep (unsigned long usecs)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions inherited from QThread
int exec ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Static Protected Member Functions inherited from QThread
void setTerminationEnabled (bool enabled)
Properties inherited from QObject
objectName
Detailed Description
Definition at line 419 of file graph_layouter.h.
Constructor & Destructor Documentation
DrawNetThread()
hal::DrawNetThread::DrawNetThread (u32 id, GraphLayouter * parent) inline
Definition at line 429 of file graph_layouter.h.
Member Function Documentation
id()
u32 hal::DrawNetThread::id () const inline
Definition at line 430 of file graph_layouter.h.
run()
void hal::DrawNetThread::run () override virtual
Reimplemented from QThread.
Definition at line 1356 of file graph_layouter.cpp.
References hal::StandardGraphicsNet::Lines::appendHLine(), hal::StandardGraphicsNet::Lines::appendVLine(), QRect::bottom(), QHash::constBegin(), QHash::constEnd(), hal::NetLayoutWire::DestinationPoint, hal::Netlist::get_net_by_id(), hal::gNetlist, hal::NetLayoutPoint::isEndpoint(), QRect::left(), mLines, test::n, hal::NetLayoutJunction::rect(), QRect::right(), hal::NetLayoutWire::SourcePoint, QRect::top(), QHash::value(), QPoint::x(), and QPoint::y().
Member Data Documentation
mKnots
QList<QPointF> hal::DrawNetThread::mKnots
Definition at line 428 of file graph_layouter.h.
mLines
StandardGraphicsNet::Lines hal::DrawNetThread::mLines
Definition at line 427 of file graph_layouter.h.
Referenced by run().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/graph_layouter.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/graph_layouter.cpp