HAL: hal::NetLayoutPoint Class Reference
hal::NetLayoutPoint Class Reference
HAL Gui » Graph Widget » Layouters
#include <net_layout_point.h>
Public Member Functions
NetLayoutPoint (int x_=INT_MIN, int y_=INT_MIN)
NetLayoutPoint (const QPoint &p)
QGraphicsEllipseItem * graphicsFactory (float r) const
int distanceTo (const NetLayoutPoint &other) const
int yGrid () const
QPoint gridPoint () const
bool isEndpoint () const
bool isUndefined () const
NetLayoutPoint nextPoint (const NetLayoutDirection &dir, bool omitEndpoint=false) const
Public Member Functions inherited from QPoint
QPoint ()
QPoint (int xpos, int ypos)
bool isNull () const const
int x () const const
int y () const const
void setX (int x)
void setY (int y)
int manhattanLength () const const
QPoint transposed () const const
int & rx ()
int & ry ()
QPoint & operator+= (const QPoint &point)
QPoint & operator-= (const QPoint &point)
QPoint & operator*= (float factor)
QPoint & operator*= (double factor)
QPoint & operator*= (int factor)
QPoint & operator/= (qreal divisor)
CGPoint toCGPoint () const const
bool operator== (const QPoint &p1, const QPoint &p2)
bool operator!= (const QPoint &p1, const QPoint &p2)
const QPoint operator+ (const QPoint &p1, const QPoint &p2)
const QPoint operator- (const QPoint &p1, const QPoint &p2)
const QPoint operator* (const QPoint &point, float factor)
const QPoint operator* (const QPoint &point, double factor)
const QPoint operator* (const QPoint &point, int factor)
const QPoint operator* (float factor, const QPoint &point)
const QPoint operator* (double factor, const QPoint &point)
const QPoint operator* (int factor, const QPoint &point)
const QPoint operator+ (const QPoint &point)
const QPoint operator- (const QPoint &point)
const QPoint operator/ (const QPoint &point, qreal divisor)
QDataStream & operator<< (QDataStream &stream, const QPoint &point)
QDataStream & operator>> (QDataStream &stream, QPoint &point)
Static Public Member Functions
static NetLayoutPoint fromBox (const QPoint &boxPosition, bool isInput)
static QList< NetLayoutPoint > orderByDistance (const QList< NetLayoutPoint > &points)
Static Public Member Functions inherited from QPoint
int dotProduct (const QPoint &p1, const QPoint &p2)
Detailed Description
Definition at line 75 of file net_layout_point.h.
Constructor & Destructor Documentation
NetLayoutPoint() [1/2]
hal::NetLayoutPoint::NetLayoutPoint (int x_ = INT_MIN, int y_ = INT_MIN)
Definition at line 75 of file net_layout_point.cpp.
Referenced by fromBox(), and nextPoint().
NetLayoutPoint() [2/2]
hal::NetLayoutPoint::NetLayoutPoint (const QPoint & p)
Definition at line 79 of file net_layout_point.cpp.
Member Function Documentation
distanceTo()
int hal::NetLayoutPoint::distanceTo (const NetLayoutPoint & other) const
Definition at line 106 of file net_layout_point.cpp.
References isEndpoint(), QPoint::x(), and QPoint::y().
Referenced by hal::NetLayoutConnection::closestPoint().
fromBox()
NetLayoutPoint hal::NetLayoutPoint::fromBox (const QPoint & boxPosition, bool isInput) static
Definition at line 96 of file net_layout_point.cpp.
References NetLayoutPoint(), QPoint::x(), and QPoint::y().
graphicsFactory()
QGraphicsEllipseItem * hal::NetLayoutPoint::graphicsFactory (float r) const
Definition at line 123 of file net_layout_point.cpp.
References Qt::black, scenePoint(), QAbstractGraphicsShapeItem::setPen(), QPointF::x(), and QPointF::y().
gridPoint()
QPoint hal::NetLayoutPoint::gridPoint () const inline
Definition at line 83 of file net_layout_point.h.
References QPoint::QPoint(), QPoint::x(), and yGrid().
isEndpoint()
bool hal::NetLayoutPoint::isEndpoint () const
Definition at line 101 of file net_layout_point.cpp.
References QPoint::y().
Referenced by distanceTo(), hal::NetLayoutConnection::NetLayoutConnection(), and hal::DrawNetThread::run().
isUndefined()
bool hal::NetLayoutPoint::isUndefined () const inline
Definition at line 85 of file net_layout_point.h.
References QPoint::x(), and QPoint::y().
Referenced by hal::NetLayoutConnection::closestPoint(), hal::ActionFoldModule::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionUnfoldModule::exec(), hal::GraphContext::unfoldModule(), and hal::GraphContext::writeToFile().
nextPoint()
NetLayoutPoint hal::NetLayoutPoint::nextPoint (const NetLayoutDirection & dir, bool omitEndpoint = false) const
Definition at line 83 of file net_layout_point.cpp.
References NetLayoutPoint(), and hal::NetLayoutDirection::step().
Referenced by hal::NetLayoutWire::graphicsFactory(), and hal::NetLayoutWire::NetLayoutWire().
orderByDistance()
QList< NetLayoutPoint > hal::NetLayoutPoint::orderByDistance (const QList< NetLayoutPoint > & points) static
Definition at line 131 of file net_layout_point.cpp.
References QList::append(), QList::at(), QMap::begin(), QSet::contains(), QMap::end(), QMap::erase(), QMultiMap::insert(), QSet::insert(), test::n, QList::size(), and QMap::iterator::value().
Referenced by hal::NetLayoutConnectionFactory::NetLayoutConnectionFactory().
yGrid()
int hal::NetLayoutPoint::yGrid () const
Definition at line 89 of file net_layout_point.cpp.
References QPoint::y().
Referenced by gridPoint().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/net_layout_point.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/net_layout_point.cpp