HAL: hal::UserActionFactory Class Reference
hal::UserActionFactory Class Reference abstract
HAL Gui » User Actions
The UserActionFactory is the abstract base class for registration.
#include <user_action.h>
Public Member Functions
UserActionFactory (const QString &nam)
QString tagname () const
virtual UserAction * newAction () const =0
Protected Attributes
QString mTagname
Detailed Description
The UserActionFactory is the abstract base class for registration.
Each class derived from UserAction is supposed to come with a derived factory as well. The factory is used to register the user action constructor with the user action manager. Doing so new interactions can be implemented without tempering with the manager class.
Definition at line 224 of file user_action.h.
Constructor & Destructor Documentation
UserActionFactory()
hal::UserActionFactory::UserActionFactory (const QString & nam)
Register the constructor for user action with tag name provided by derived class.
Parameters
nam - The tag name.
Definition at line 6 of file user_action.cpp.
References hal::UserActionManager::instance(), and hal::UserActionManager::registerFactory().
Member Function Documentation
newAction()
virtual UserAction* hal::UserActionFactory::newAction () const pure virtual
Call the user action constructor.
Returns
The user action.
Implemented in hal::ActionSetObjectDataFactory, hal::ActionAddBooleanFunctionFactory, hal::UserActionCompoundFactory, hal::ActionUnfoldModuleFactory, hal::ActionSetSelectionFocusFactory, hal::ActionSetObjectTypeFactory, hal::ActionSetObjectColorFactory, hal::ActionRenameObjectFactory, hal::ActionRemoveItemsFromObjectFactory, hal::ActionPingroupFactory, hal::ActionOpenNetlistFileFactory, hal::ActionMoveNodeFactory, hal::ActionMoveItemFactory, hal::ActionFoldModuleFactory, hal::ActionDeleteObjectFactory, hal::ActionCreateObjectFactory, and hal::ActionAddItemsToObjectFactory.
Referenced by hal::UserActionManager::getParsedAction().
tagname()
QString hal::UserActionFactory::tagname () const inline
Get the tag name of derived class.
Returns
The tag name.
Definition at line 242 of file user_action.h.
References mTagname.
Referenced by hal::UserActionManager::registerFactory(), hal::ActionAddBooleanFunction::tagname(), hal::ActionAddItemsToObject::tagname(), hal::ActionCreateObject::tagname(), hal::ActionDeleteObject::tagname(), hal::ActionFoldModule::tagname(), hal::ActionMoveItem::tagname(), hal::ActionMoveNode::tagname(), hal::ActionOpenNetlistFile::tagname(), hal::ActionPingroup::tagname(), hal::ActionRemoveItemsFromObject::tagname(), hal::ActionRenameObject::tagname(), hal::ActionSetObjectColor::tagname(), hal::ActionSetObjectData::tagname(), hal::ActionSetObjectType::tagname(), hal::ActionSetSelectionFocus::tagname(), hal::ActionUnfoldModule::tagname(), and hal::UserActionCompound::tagname().
Member Data Documentation
mTagname
QString hal::UserActionFactory::mTagname protected
Definition at line 227 of file user_action.h.
Referenced by tagname().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/user_action.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/user_action.cpp