HAL: hal::TreeItem Class Reference
hal::TreeItem Class Reference
(Future) Base class for all tree models related to the details widget.
#include <tree_item.h>
Public Member Functions
TreeItem ()
TreeItem (QList< QVariant > columnData)
~TreeItem ()
QVariant getData (int column)
void setData (QList< QVariant > data)
void setDataAtIndex (int index, QVariant data)
void appendData (QVariant data)
TreeItem * getParent ()
void setParent (TreeItem *parent)
TreeItem * getChild (int row)
QList< TreeItem * > getChildren ()
void appendChild (TreeItem *child)
void insertChild (int index, TreeItem *child)
TreeItem * removeChildAtPos (int row)
bool removeChild (TreeItem *child)
int getChildCount ()
int getColumnCount ()
int getRowForChild (TreeItem *child)
int getOwnRow ()
void setAdditionalData (QString key, QVariant data)
QVariant getAdditionalData (QString key)
Detailed Description
(Future) Base class for all tree models related to the details widget.
This class functions as a generic data container for all tree models. For this purpose, it uses QVariants as its main type of storage for its columns. (Note: Perhaps add additional data in form of a list or map (split it from "normal" displayed column data)
Definition at line 40 of file tree_item.h.
Constructor & Destructor Documentation
TreeItem() [1/2]
hal::TreeItem::TreeItem ()
The constructor.
Definition at line 6 of file tree_item.cpp.
TreeItem() [2/2]
hal::TreeItem::TreeItem (QList< QVariant > columnData)
Second constructor to immediately assign column data.
Parameters
columnData - The item's data.
Definition at line 11 of file tree_item.cpp.
~TreeItem()
hal::TreeItem::~TreeItem ()
The destructor.
Definition at line 16 of file tree_item.cpp.
Member Function Documentation
appendChild()
void hal::TreeItem::appendChild (TreeItem * child)
Appends a child.
Parameters
child - The child to append.
Definition at line 63 of file tree_item.cpp.
References setParent().
Referenced by hal::NetlistElementsTreeModel::setContent(), hal::BaseTreeModel::setContent(), hal::GatePinsTreeModel::setGate(), hal::ModuleTreeModel::setModule(), and hal::ModulePinsTreeModel::setModule().
appendData()
void hal::TreeItem::appendData (QVariant data)
Appends a new column to the item.
Parameters
data - The data of the new column.
Definition at line 38 of file tree_item.cpp.
References QList::append(), and hal::data.
getAdditionalData()
QVariant hal::TreeItem::getAdditionalData (QString key)
Retrieve the data stored under the given key.
Parameters
key - The key for the requested data.
Returns
The data if something was stored under the key, empty QVariant otherwise.
Definition at line 136 of file tree_item.cpp.
References QMap::value().
Referenced by hal::ModulePinsTreeModel::getIdOfItem(), hal::GatePinsTreeModel::getNetIDsOfTreeItem(), hal::NetlistElementsTreeModel::getRepresentedIdOfItem(), hal::ModuleTreeModel::getTypeOfItem(), hal::GatePinsTreeModel::getTypeOfItem(), hal::ModulePinsTreeModel::getTypeOfItem(), hal::NetlistElementsTreeModel::getTypeOfItem(), and hal::NetlistElementsTreeModel::moduleSubmoduleRemoved().
getChild()
TreeItem * hal::TreeItem::getChild (int row)
Get the child of a specific row.
Parameters
row - The requested row.
Returns
The child if within bounds. Nullptr otherwise.
Definition at line 53 of file tree_item.cpp.
Referenced by hal::BaseTreeModel::index().
getChildCount()
int hal::TreeItem::getChildCount ()
Get the number of children.
Returns
The number of children.
Definition at line 99 of file tree_item.cpp.
Referenced by hal::BaseTreeModel::clear(), hal::ModulePinsTreeModel::dropMimeData(), hal::BaseTreeModel::rowCount(), and hal::ModuleTreeModel::setModule().
getChildren()
QList< TreeItem * > hal::TreeItem::getChildren ()
Get the list of all children.
Returns
The list of children.
Definition at line 58 of file tree_item.cpp.
Referenced by hal::SizeAdjustableTreeView::adjustSizeToContents(), hal::GatePinTree::handleContextMenuRequested(), and hal::NetlistElementsTreeModel::moduleSubmoduleRemoved().
getColumnCount()
int hal::TreeItem::getColumnCount ()
Get the number of currently stored column data.
Returns
The column count.
Definition at line 104 of file tree_item.cpp.
References QList::size().
Referenced by hal::BaseTreeModel::columnCount().
getData()
QVariant hal::TreeItem::getData (int column)
Get the data of a specific column (most in the form of a string).
Parameters
column - The requested column.
Returns
The data if within the column count. Empty QVariant otherwise.
Definition at line 22 of file tree_item.cpp.
References QList::at(), and QList::size().
Referenced by hal::BaseTreeModel::data(), hal::ModuleElementsTree::handleContextMenuRequested(), hal::ModulePinsTree::handleContextMenuRequested(), hal::GatePinTree::handleContextMenuRequested(), and hal::BaseTreeModel::headerData().
getOwnRow()
int hal::TreeItem::getOwnRow ()
Convenience method to get the row of this item within the parent's list. If the item has no parent, -1 is returned.
Returns
The row of this item if it has a parent, -1 otherwise.
Definition at line 123 of file tree_item.cpp.
References getRowForChild().
getParent()
TreeItem * hal::TreeItem::getParent ()
Get the item's parent.
Returns
The parent.
Definition at line 43 of file tree_item.cpp.
Referenced by hal::ModulePinsTreeModel::flags(), hal::BaseTreeModel::getIndexFromItem(), and hal::BaseTreeModel::parent().
getRowForChild()
int hal::TreeItem::getRowForChild (TreeItem * child)
Convenience method to get the row for a given item. If the item is not a child of this item, -1 is returned.
Parameters
child - The child for which the row is requested.
Returns
The row if the item is a child, -1 otherwise.
Definition at line 109 of file tree_item.cpp.
Referenced by hal::BaseTreeModel::getIndexFromItem(), and getOwnRow().
insertChild()
void hal::TreeItem::insertChild (int index, TreeItem * child)
Inserts a child at the given index. If the index exceeds the amount of children, the new child is appended.
Parameters
index - The position at which to insert.
child - The child to insert.
Definition at line 69 of file tree_item.cpp.
References setParent().
removeChild()
bool hal::TreeItem::removeChild (TreeItem * child)
Removes the given item and returns True if removing was successful or False if the given item was no child.
Parameters
child - The child to remove.
Returns
True on success, False otherwise.
Definition at line 87 of file tree_item.cpp.
removeChildAtPos()
TreeItem * hal::TreeItem::removeChildAtPos (int row)
Removes the child at the given row and returns it.
Parameters
row - The row from which to remove the child.
Returns
The removed child. Nullptr if row was out of bounds.
Definition at line 75 of file tree_item.cpp.
Referenced by hal::BaseTreeModel::clear(), and hal::ModuleTreeModel::setModule().
setAdditionalData()
void hal::TreeItem::setAdditionalData (QString key, QVariant data)
Stores additional data. Can be accessed by getAdditionalData. (For example, a menu or color)
Parameters
key - The key to store the data under.
data - The actual data to store.
Definition at line 131 of file tree_item.cpp.
References hal::data, and QMap::insert().
Referenced by hal::ModulePinsTreeModel::dropMimeData(), hal::NetlistElementsTreeModel::moduleGateAssigned(), hal::NetlistElementsTreeModel::moduleSubmoduleAdded(), hal::NetlistElementsTreeModel::setContent(), hal::GatePinsTreeModel::setGate(), hal::ModuleTreeModel::setModule(), and hal::ModulePinsTreeModel::setModule().
setData()
void hal::TreeItem::setData (QList< QVariant > data)
Sets the data for all columns.
Parameters
data - Each entry in the list represents one column.
Definition at line 27 of file tree_item.cpp.
References hal::data.
Referenced by hal::GatePinsTreeModel::setGate(), and hal::BaseTreeModel::setHeaderLabels().
setDataAtIndex()
void hal::TreeItem::setDataAtIndex (int index, QVariant data)
Sets the data for a specified column. The index must be within already existing boundaries (for example, add dummy data beforehand).
Parameters
index - The column to set the new data.
data - The new column data.
Definition at line 32 of file tree_item.cpp.
References hal::data, QList::empty(), QList::replace(), and QList::size().
Referenced by hal::ModulePinsTreeModel::setModule().
setParent()
void hal::TreeItem::setParent (TreeItem * parent)
Sets the item's parent.
Parameters
parent - The parent.
Definition at line 48 of file tree_item.cpp.
Referenced by appendChild(), and insertChild().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/basic_tree_model/tree_item.h
/home/runner/work/hal/hal/plugins/gui/src/basic_tree_model/tree_item.cpp