HAL: hal::PluginGui Class Reference
hal::PluginGui Class Reference
HAL Gui
#include <plugin_gui.h>
Public Member Functions
std::string get_name () const override
std::string get_version () const override
void initialize_logging () override
ProgramOptions get_cli_options () const override
bool exec (ProgramArguments &args) override
Public Member Functions inherited from hal::UIPluginInterface
UIPluginInterface ()=default
virtual ~UIPluginInterface ()=default
Public Member Functions inherited from hal::BasePluginInterface
BasePluginInterface ()=default
virtual ~BasePluginInterface ()=default
virtual void initialize ()
bool has_type (PluginInterfaceType t) const
template<typename... Args>
void log (const Args &... args) const
virtual std::set< std::string > get_dependencies () const
virtual void on_load ()
virtual void on_unload ()
Detailed Description
PluginGui is a huge plugin that provides a graphical user interface to load and work with netlists. If compiled it can be started using the '-g'/'–gui' flag.
Definition at line 34 of file plugin_gui.h.
Member Function Documentation
exec()
bool hal::PluginGui::exec (ProgramArguments & args) override virtual
Executes the gui plugin.
Parameters
args - The given program arguments.
Returns
True on success, False otherwise.
Implements hal::UIPluginInterface.
Definition at line 136 of file plugin_gui.cpp.
References Qt::AA_DontUseNativeDialogs, Qt::AA_UseHighDpiPixmaps, QCoreApplication::aboutToQuit(), QFontDatabase::addApplicationFont(), control::args, QFileDevice::close(), QObject::connect(), hal::style::debugUpdate(), QApplication::exec(), QString::fromStdString(), hal::utils::get_user_config_directory(), hal::gFileStatusManager, hal::gGraphContextManager, hal::gGuiApi, hal::gGuiState, hal::gNetlistRelay, hal::gPluginRelay, hal::gSelectionRelay, QSettings::IniFormat, hal::mGSettings, QFile::open(), QIODevice::readAll(), QIODevice::ReadOnly, QResource::registerResource(), QCoreApplication::setApplicationName(), QCoreApplication::setAttribute(), QCoreApplication::setOrganizationDomain(), QCoreApplication::setOrganizationName(), QApplication::setStyleSheet(), hal::SettingsItemDropdown::setValueNames(), QWidget::show(), hal::MainWindow::sSettingStyle, QVariant::toInt(), and hal::SettingsItemDropdown::value().
get_cli_options()
ProgramOptions hal::PluginGui::get_cli_options () const override virtual
Initializes the command line options for this plugin: '-g'/'–gui' to start the gui
Returns
the available command line options
Implements hal::UIPluginInterface.
Definition at line 255 of file plugin_gui.cpp.
References hal::ProgramOptions::add().
get_name()
std::string hal::PluginGui::get_name () const override virtual
Returns the plugin name: 'hal_gui'
Returns
the plugin name
Implements hal::BasePluginInterface.
Definition at line 236 of file plugin_gui.cpp.
get_version()
std::string hal::PluginGui::get_version () const override virtual
Returns the current version of the plugin.
Returns
the current version number of the plugin
Implements hal::BasePluginInterface.
Definition at line 241 of file plugin_gui.cpp.
initialize_logging()
void hal::PluginGui::initialize_logging () override virtual
Adds all gui related channels to the LogManager.
Reimplemented from hal::BasePluginInterface.
Definition at line 246 of file plugin_gui.cpp.
References hal::LogManager::add_channel(), hal::LogManager::create_file_sink(), hal::LogManager::create_gui_sink(), hal::LogManager::create_stdout_sink(), and hal::LogManager::get_instance().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/plugin_gui.h
/home/runner/work/hal/hal/plugins/gui/src/plugin_gui.cpp