HAL: hal::SelectionTreeModel Class Reference
hal::SelectionTreeModel Class Reference
HAL Gui » Utility Widgets » Selection Details Widget
A model that contains the current selection.
#include <selection_tree_model.h>
Public Slots
void handleGateItemChanged (Gate *gate)
void handleModuleItemChanged (Module *module)
Public Member Functions
SelectionTreeModel (QObject *parent=nullptr)
~SelectionTreeModel ()
void fetchSelection (bool hasEntries)
QModelIndex indexFromItem (SelectionTreeItem *item) const
void suppressedByFilter (QList< u32 > &modIds, QList< u32 > &gatIds, QList< u32 > &netIds, const QRegularExpression &regex) const
Overwritten model functions.
QVariant data (const QModelIndex &index, int role) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
QModelIndex parent (const QModelIndex &index) const override
Qt::ItemFlags flags (const QModelIndex &index) const override
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
virtual QModelIndex sibling (int row, int column, const QModelIndex &index) const const
virtual bool hasChildren (const QModelIndex &parent) const const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role)
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const const
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
virtual QStringList mimeTypes () const const
virtual QMimeData * mimeData (const QModelIndexList &indexes) const const
virtual bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const const
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
virtual Qt::DropActions supportedDropActions () const const
virtual Qt::DropActions supportedDragActions () const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool insertRows (int row, int count, const QModelIndex &parent)
virtual bool insertColumns (int column, int count, const QModelIndex &parent)
virtual bool removeRows (int row, int count, const QModelIndex &parent)
virtual bool removeColumns (int column, int count, const QModelIndex &parent)
virtual bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual void fetchMore (const QModelIndex &parent)
virtual bool canFetchMore (const QModelIndex &parent) const const
virtual void sort (int column, Qt::SortOrder order)
virtual QModelIndex buddy (const QModelIndex &index) const const
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const
virtual QSize span (const QModelIndex &index) const const
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual bool submit ()
virtual void revert ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Attributes
static const int sNameColumn = 0
static const int sIdColumn = 1
static const int sTypeColumn = 2
static const int sMaxColumn = 3
Additional Inherited Members
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
A model that contains the current selection.
A model that manages the current selection in a tree-styled fashion. Its most important function is fetchSelection that automatically updates the model's internal data.
Definition at line 52 of file selection_tree_model.h.
Constructor & Destructor Documentation
SelectionTreeModel()
hal::SelectionTreeModel::SelectionTreeModel (QObject * parent = nullptr)
The constructor.
Parameters
parent - The model's parent.
Definition at line 12 of file selection_tree_model.cpp.
References QObject::connect(), hal::NetlistRelay::gateNameChanged(), hal::gNetlistRelay, handleGateItemChanged(), handleModuleItemChanged(), hal::NetlistRelay::moduleNameChanged(), and hal::NetlistRelay::moduleTypeChanged().
~SelectionTreeModel()
hal::SelectionTreeModel::~SelectionTreeModel ()
The destructor.
Definition at line 23 of file selection_tree_model.cpp.
Member Function Documentation
columnCount()
int hal::SelectionTreeModel::columnCount (const QModelIndex & parent = QModelIndex()) const override virtual
Overwritten Qt function that is necessary for the model. For further information pleaser refer to the Qt documentation.
Implements QAbstractItemModel.
Definition at line 141 of file selection_tree_model.cpp.
References QObject::parent(), and sMaxColumn.
Referenced by headerData().
data()
QVariant hal::SelectionTreeModel::data (const QModelIndex & index, int role) const override virtual
Overwritten Qt function that is necessary for the model. For further information pleaser refer to the Qt documentation.
Implements QAbstractItemModel.
Definition at line 34 of file selection_tree_model.cpp.
References Qt::AlignLeft, Qt::AlignRight, QModelIndex::column(), hal::SelectionTreeItem::data(), Qt::DecorationRole, Qt::DisplayRole, hal::SelectionTreeItem::icon(), index(), sIdColumn, sNameColumn, and Qt::TextAlignmentRole.
fetchSelection()
void hal::SelectionTreeModel::fetchSelection (bool hasEntries)
Updates its internal data. If hasEntries is set to True, the current selection is fetched from the selectionRelay. Otherwise the model is simply cleared.
Parameters
hasEntries - Decides wether the current selection is fetched.
Definition at line 147 of file selection_tree_model.cpp.
References hal::SelectionTreeItemModule::addChild(), QAbstractItemModel::beginResetModel(), hal::SelectionTreeModelDisposer::dispose(), QAbstractItemModel::endResetModel(), hal::gSelectionRelay, hal::SelectionRelay::selectedGatesList(), hal::SelectionRelay::selectedModulesList(), hal::SelectionRelay::selectedNetsList(), and QTimer::singleShot.
Referenced by hal::SelectionTreeView::populate().
flags()
Qt::ItemFlags hal::SelectionTreeModel::flags (const QModelIndex & index) const override virtual
Overwritten Qt function that is necessary for the model. For further information pleaser refer to the Qt documentation.
Reimplemented from QAbstractItemModel.
Definition at line 126 of file selection_tree_model.cpp.
References QAbstractItemModel::flags(), and index().
handleGateItemChanged
void hal::SelectionTreeModel::handleGateItemChanged (Gate * gate) slot
Q_SLOT to handle the change of a gate and emits the dataChanged signal. This function is connected to the gateNameChanged signal.
Parameters
gate - The gate whose information changed.
Definition at line 209 of file selection_tree_model.cpp.
References QAbstractItemModel::createIndex(), QAbstractItemModel::dataChanged(), hal::Gate::get_id(), indexFromItem(), QModelIndex::internalPointer(), QObject::Q_EMIT(), and QModelIndex::row().
Referenced by SelectionTreeModel().
handleModuleItemChanged
void hal::SelectionTreeModel::handleModuleItemChanged (Module * module) slot
Q_SLOT to handle the change of a module and emits the dataChanged signal. This function is connected to the moduleNameChanged and moduleTypeChanged signal.
Parameters
module - The module whose information changed.
Definition at line 221 of file selection_tree_model.cpp.
References QAbstractItemModel::createIndex(), QAbstractItemModel::dataChanged(), hal::Module::get_id(), indexFromItem(), QModelIndex::internalPointer(), hal::ShortestPath::module(), QObject::Q_EMIT(), and QModelIndex::row().
Referenced by SelectionTreeModel().
headerData()
QVariant hal::SelectionTreeModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override virtual
Overwritten Qt function that is necessary for the model. For further information pleaser refer to the Qt documentation.
Reimplemented from QAbstractItemModel.
Definition at line 72 of file selection_tree_model.cpp.
References columnCount(), Qt::DisplayRole, and Qt::Horizontal.
index()
QModelIndex hal::SelectionTreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const override virtual
Overwritten Qt function that is necessary for the model. For further information pleaser refer to the Qt documentation.
Implements QAbstractItemModel.
Definition at line 92 of file selection_tree_model.cpp.
References hal::SelectionTreeItem::child(), QAbstractItemModel::createIndex(), QAbstractItemModel::hasIndex(), and QObject::parent().
Referenced by data(), flags(), and parent().
indexFromItem()
QModelIndex hal::SelectionTreeModel::indexFromItem (SelectionTreeItem * item) const
Helper functions to convert between an item and its corresponding index.
Parameters
item - The item from which to get the index.
Returns
The index that holds the item.
Definition at line 248 of file selection_tree_model.cpp.
References hal::SelectionTreeItem::child(), hal::SelectionTreeItem::childCount(), QAbstractItemModel::createIndex(), and hal::SelectionTreeItem::parent().
Referenced by handleGateItemChanged(), handleModuleItemChanged(), and parent().
parent()
QModelIndex hal::SelectionTreeModel::parent (const QModelIndex & index) const override virtual
Overwritten Qt function that is necessary for the model. For further information pleaser refer to the Qt documentation.
Implements QAbstractItemModel.
Definition at line 109 of file selection_tree_model.cpp.
References index(), indexFromItem(), QModelIndex::isValid(), and hal::SelectionTreeItem::parent().
rowCount()
int hal::SelectionTreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const override virtual
Overwritten Qt function that is necessary for the model. For further information pleaser refer to the Qt documentation.
Implements QAbstractItemModel.
Definition at line 131 of file selection_tree_model.cpp.
References hal::SelectionTreeItem::childCount(), and QObject::parent().
suppressedByFilter()
void hal::SelectionTreeModel::suppressedByFilter (QList< u32 > & modIds, QList< u32 > & gatIds, QList< u32 > & netIds, const QRegularExpression & regex) const
A recursive function to get the suppressed items that are not matched by the given regular expression (and therefore should not be displayed). The ids of theese items are then stored in the appropriate lists.
Parameters
modIds - The list that holds the ids of the suppressed modules.
gatIds - The list that holds the ids of the suppressed gates.
netIds - The list that holds the ids of the suppressed nets.
regex - The regex to match the items against.
Definition at line 267 of file selection_tree_model.cpp.
References hal::SelectionTreeItemModule::suppressedByFilterRecursion().
Member Data Documentation
sIdColumn
const int hal::SelectionTreeModel::sIdColumn = 1 static
Definition at line 148 of file selection_tree_model.h.
Referenced by data(), and hal::SelectionTreeView::setDefaultColumnWidth().
sMaxColumn
const int hal::SelectionTreeModel::sMaxColumn = 3 static
Definition at line 150 of file selection_tree_model.h.
Referenced by columnCount().
sNameColumn
const int hal::SelectionTreeModel::sNameColumn = 0 static
Definition at line 147 of file selection_tree_model.h.
Referenced by data(), and hal::SelectionTreeView::setDefaultColumnWidth().
sTypeColumn
const int hal::SelectionTreeModel::sTypeColumn = 2 static
Definition at line 149 of file selection_tree_model.h.
Referenced by hal::SelectionTreeView::setDefaultColumnWidth().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/tree_navigation/selection_tree_model.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/tree_navigation/selection_tree_model.cpp