HAL: hal::NetLayoutJunctionOccupiedHash Class Reference
hal::NetLayoutJunctionOccupiedHash Class Reference
HAL Gui » Graph Widget » Layouters
#include <net_layout_junction.h>
Classes
class AddOrMerge
Public Member Functions
AddOrMerge addOrMerge (const LaneIndex &ri, const NetLayoutJunctionRange &rng)
Public Member Functions inherited from QHash< LaneIndex, NetLayoutJunctionOccupied >
QHash ()
QHash (std::initializer_list< std::pair< Key, T > > list)
QHash (const QHash< K, V > &other)
QHash (QHash< K, V > &&other)
QHash (InputIterator begin, InputIterator end)
~QHash ()
QHash< K, V > & operator= (const QHash< K, V > &other)
QHash< K, V > & operator= (QHash< K, V > &&other)
void swap (QHash< K, V > &other)
bool operator== (const QHash< K, V > &other) const const
bool operator!= (const QHash< K, V > &other) const const
int size () const const
bool isEmpty () const const
int capacity () const const
void reserve (int size)
void squeeze ()
void clear ()
int remove (const Key &key)
T take (const Key &key)
bool contains (const Key &key) const const
const Key key (const T &value) const const
const Key key (const T &value, const Key &defaultKey) const const
const T value (const Key &key) const const
const T value (const Key &key, const T &defaultValue) const const
T & operator[] (const Key &key)
const T operator[] (const Key &key) const const
QList< Key > keys () const const
QList< Key > keys (const T &value) const const
QList< T > values () const const
QList< T > values (const Key &key) const const
QList< Key > uniqueKeys () const const
int count (const Key &key) const const
int count () const const
QHash::iterator begin ()
QHash::const_iterator begin () const const
QHash::const_iterator cbegin () const const
QHash::const_iterator constBegin () const const
QHash::iterator end ()
QHash::const_iterator end () const const
QHash::const_iterator cend () const const
QHash::const_iterator constEnd () const const
QHash::key_iterator keyBegin () const const
QHash::key_iterator keyEnd () const const
QHash::key_value_iterator keyValueBegin ()
QHash::const_key_value_iterator keyValueBegin () const const
QHash::key_value_iterator keyValueEnd ()
QHash::const_key_value_iterator keyValueEnd () const const
QHash::const_key_value_iterator constKeyValueBegin () const const
QHash::const_key_value_iterator constKeyValueEnd () const const
QPair< QHash::iterator, QHash::iterator > equal_range (const Key &key)
QPair< QHash::const_iterator, QHash::const_iterator > equal_range (const Key &key) const const
QHash::iterator erase (QHash::iterator pos)
QHash::iterator erase (QHash::const_iterator pos)
QHash::iterator find (const Key &key)
QHash::const_iterator find (const Key &key) const const
QHash::const_iterator constFind (const Key &key) const const
QHash::iterator insert (const Key &key, const T &value)
void insert (const QHash< K, V > &other)
QHash::iterator insertMulti (const Key &key, const T &value)
QHash< K, V > & unite (const QHash< K, V > &other)
bool empty () const const
uint qHash (const QUrl &url, uint seed)
uint qHash (const QDateTime &key, uint seed)
uint qHash (const QDate &key, uint seed)
uint qHash (const QTime &key, uint seed)
uint qHash (const QPair< T1, T2 > &key, uint seed)
uint qHash (const std::pair< T1, T2 > &key, uint seed)
uint qHash (char key, uint seed)
uint qHash (uchar key, uint seed)
uint qHash (signed char key, uint seed)
uint qHash (ushort key, uint seed)
uint qHash (short key, uint seed)
uint qHash (uint key, uint seed)
uint qHash (int key, uint seed)
uint qHash (ulong key, uint seed)
uint qHash (long key, uint seed)
uint qHash (quint64 key, uint seed)
uint qHash (qint64 key, uint seed)
uint qHash (float key, uint seed)
uint qHash (double key, uint seed)
uint qHash (long double key, uint seed)
uint qHash (const QChar key, uint seed)
uint qHash (const QByteArray &key, uint seed)
uint qHash (const QBitArray &key, uint seed)
uint qHash (const QString &key, uint seed)
uint qHash (const QStringRef &key, uint seed)
uint qHash (QLatin1String key, uint seed)
uint qHash (const T *key, uint seed)
uint qHash (const QHash< Key, T > &key, uint seed)
uint qHash (const QSet< T > &key, uint seed)
uint qHash (const QVersionNumber &key, uint seed)
int qGlobalQHashSeed ()
void qSetGlobalQHashSeed (int newSeed)
uint qHashRange (InputIterator first, InputIterator last, uint seed)
uint qHashRangeCommutative (InputIterator first, InputIterator last, uint seed)
uint qHashBits (const void *p, size_t len, uint seed)
QDataStream & operator<< (QDataStream &out, const QHash< Key, T > &hash)
QDataStream & operator>> (QDataStream &in, QHash< Key, T > &hash)
Additional Inherited Members
Public Attributes inherited from QHash< LaneIndex, NetLayoutJunctionOccupied >
typedef const_key_value_iterator
typedef key_value_iterator
typedef Iterator
typedef ConstIterator
typedef mapped_type
typedef key_type
typedef difference_type
typedef size_type
Detailed Description
Definition at line 375 of file net_layout_junction.h.
Member Function Documentation
addOrMerge()
NetLayoutJunctionOccupiedHash::AddOrMerge hal::NetLayoutJunctionOccupiedHash::addOrMerge (const LaneIndex & ri, const NetLayoutJunctionRange & rng)
Adds new entry for range or merges it
Parameters
ri Road index where to add
rng Range to add
Returns
see AddType above.
Definition at line 686 of file net_layout_junction.cpp.
References hal::NetLayoutJunctionOccupiedHash::AddOrMerge::Added, hal::NetLayoutJunctionOccupiedHash::AddOrMerge::AlreadyExisting, QList::append(), QList::begin(), QList::end(), hal::NetLayoutJunctionOccupiedHash::AddOrMerge::Merged, hal::NetLayoutJunctionOccupiedHash::AddOrMerge::mNewRange, hal::NetLayoutJunctionOccupiedHash::AddOrMerge::mOldRange, hal::NetLayoutJunctionOccupiedHash::AddOrMerge::mType, hal::NetLayoutJunctionRange::netId(), and QHash< LaneIndex, NetLayoutJunctionOccupied >::operator[]().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/net_layout_junction.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/net_layout_junction.cpp