HAL: hal::ContextDirectory Class Reference
hal::ContextDirectory Class Reference
#include <context_tree_model.h>
Public Member Functions
ContextDirectory (QString name, u32 parentId, u32 id)
void writeToFile (QJsonObject &json)
QString name () const
u32 id () const
void setId (u32 id_)
void setName (QString name_)
Detailed Description
Definition at line 37 of file context_tree_model.h.
Constructor & Destructor Documentation
ContextDirectory()
hal::ContextDirectory::ContextDirectory (QString name, u32 parentId, u32 id) inline
Definition at line 45 of file context_tree_model.h.
References id().
Member Function Documentation
id()
u32 hal::ContextDirectory::id () const inline
Definition at line 58 of file context_tree_model.h.
Referenced by hal::ContextProxyModel::canDropMimeData(), ContextDirectory(), hal::ContextProxyModel::dropMimeData(), hal::ActionCreateObject::exec(), hal::ActionDeleteObject::exec(), hal::GuiApiClasses::View::getCurrentDirectory(), hal::ContextTreeItem::getData(), hal::ContextTreeItem::getId(), hal::ContextProxyModel::mimeData(), and hal::ContextTreeModel::removeDirectory().
name()
QString hal::ContextDirectory::name () const inline
Definition at line 57 of file context_tree_model.h.
Referenced by hal::ActionDeleteObject::exec(), hal::ActionRenameObject::exec(), hal::ContextTreeItem::getData(), and hal::ContextTreeItem::getName().
setId()
void hal::ContextDirectory::setId (u32 id_) inline
Definition at line 59 of file context_tree_model.h.
Referenced by hal::ActionCreateObject::exec().
setName()
void hal::ContextDirectory::setName (QString name_) inline
Definition at line 60 of file context_tree_model.h.
Referenced by hal::GraphContextManager::renameContextDirectoryAction().
writeToFile()
void hal::ContextDirectory::writeToFile (QJsonObject & json)
Writes the directory to a given json object.
Parameters
json - The object to write to.
Definition at line 12 of file context_tree_model.cpp.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/context_manager_widget/models/context_tree_model.h
/home/runner/work/hal/hal/plugins/gui/src/context_manager_widget/models/context_tree_model.cpp