HAL: hal::CoordinateFromData Class Reference
hal::CoordinateFromData Class Reference
HAL Gui » Graph Widget » Layouters
Utility class that extracts (if possible) x and y coordinates contained in the netlist.
#include <coordinate_from_data.h>
Public Member Functions
CoordinateFromData (int x_=INT_MIN, int y_=INT_MIN)
bool isUndefined () const
Public Member Functions inherited from QPoint
QPoint ()
QPoint (int xpos, int ypos)
bool isNull () const const
int x () const const
int y () const const
void setX (int x)
void setY (int y)
int manhattanLength () const const
QPoint transposed () const const
int & rx ()
int & ry ()
QPoint & operator+= (const QPoint &point)
QPoint & operator-= (const QPoint &point)
QPoint & operator*= (float factor)
QPoint & operator*= (double factor)
QPoint & operator*= (int factor)
QPoint & operator/= (qreal divisor)
CGPoint toCGPoint () const const
bool operator== (const QPoint &p1, const QPoint &p2)
bool operator!= (const QPoint &p1, const QPoint &p2)
const QPoint operator+ (const QPoint &p1, const QPoint &p2)
const QPoint operator- (const QPoint &p1, const QPoint &p2)
const QPoint operator* (const QPoint &point, float factor)
const QPoint operator* (const QPoint &point, double factor)
const QPoint operator* (const QPoint &point, int factor)
const QPoint operator* (float factor, const QPoint &point)
const QPoint operator* (double factor, const QPoint &point)
const QPoint operator* (int factor, const QPoint &point)
const QPoint operator+ (const QPoint &point)
const QPoint operator- (const QPoint &point)
const QPoint operator/ (const QPoint &point, qreal divisor)
QDataStream & operator<< (QDataStream &stream, const QPoint &point)
QDataStream & operator>> (QDataStream &stream, QPoint &point)
Static Public Member Functions
static CoordinateFromData fromNode (const Node &nd)
Static Public Member Functions inherited from QPoint
int dotProduct (const QPoint &p1, const QPoint &p2)
Detailed Description
Utility class that extracts (if possible) x and y coordinates contained in the netlist.
Definition at line 48 of file coordinate_from_data.h.
Constructor & Destructor Documentation
CoordinateFromData()
hal::CoordinateFromData::CoordinateFromData (int x_ = INT_MIN, int y_ = INT_MIN)
Definition at line 11 of file coordinate_from_data.cpp.
Referenced by fromNode().
Member Function Documentation
fromNode()
CoordinateFromData hal::CoordinateFromData::fromNode (const Node & nd) static
Definition at line 15 of file coordinate_from_data.cpp.
References CoordinateFromData(), test::g, hal::Node::Gate, hal::DataContainer::get_data_map(), hal::Netlist::get_gate_by_id(), hal::Netlist::get_module_by_id(), hal::gNetlist, hal::Node::id(), hal::Node::Module, and hal::Node::type().
Referenced by hal::CoordinateFromDataMap::CoordinateFromDataMap().
isUndefined()
bool hal::CoordinateFromData::isUndefined () const inline
Definition at line 52 of file coordinate_from_data.h.
References QPoint::x(), and QPoint::y().
Referenced by hal::CoordinateFromDataMap::CoordinateFromDataMap().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/coordinate_from_data.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/coordinate_from_data.cpp