HAL: hal::JsonWriteData Class Reference
hal::JsonWriteData Class Reference
#include <json_write_document.h>
Public Member Functions
JsonWriteData (const std::string &tag, JsonWriteComplex *parent)
virtual ~JsonWriteData ()
JsonWriteData & operator= (const std::string &txt)
JsonWriteData & operator= (int ivalue)
JsonWriteData & operator= (double value)
JsonWriteData & operator= (uint64_t u64Value)
Protected Member Functions
virtual rapidjson::Document::AllocatorType & allocator ()
Protected Attributes
std::string mTagname
JsonWriteComplex * mParent
Friends
class JsonWriteComplex
Detailed Description
The JsonWriteData class represents a simple data field which gets assigned using the operator=
Definition at line 47 of file json_write_document.h.
Constructor & Destructor Documentation
JsonWriteData()
hal::JsonWriteData::JsonWriteData (const std::string & tag, JsonWriteComplex * parent)
Constructor
Parameters
[in] tag JSON tag name
[in] parent Parent instance
Definition at line 18 of file json_write_document.cpp.
~JsonWriteData()
virtual hal::JsonWriteData::~JsonWriteData () inline virtual
Definition at line 65 of file json_write_document.h.
Member Function Documentation
allocator()
rapidjson::Document::AllocatorType & hal::JsonWriteData::allocator () protected virtual
Reimplemented in hal::JsonWriteDocument.
Definition at line 23 of file json_write_document.cpp.
References hal::JsonWriteDocument::allocator(), and mParent.
Referenced by hal::JsonWriteObject::add_member(), hal::JsonWriteObject::finalize(), hal::JsonWriteArray::finalize(), hal::JsonWriteArray::operator<<(), and operator=().
operator=() [1/4]
JsonWriteData & hal::JsonWriteData::operator= (const std::string & txt)
Assign text string to JSON field
Parameters
[in] txt The text content
Returns
The instance of the class
Definition at line 39 of file json_write_document.cpp.
References hal::JsonWriteObject::add_member(), allocator(), mParent, and mTagname.
operator=() [2/4]
JsonWriteData & hal::JsonWriteData::operator= (double value)
Assign int value to JSON field.
Parameters
[in] value - The numerical content (floating point).
Returns
The instance of the class.
Definition at line 63 of file json_write_document.cpp.
References hal::JsonWriteObject::add_member(), allocator(), mParent, and mTagname.
operator=() [3/4]
JsonWriteData & hal::JsonWriteData::operator= (int ivalue)
Assign int value to JSON field
Parameters
[in] ivalue The numerical content
Returns
The instance of the class
Definition at line 47 of file json_write_document.cpp.
References hal::JsonWriteObject::add_member(), allocator(), mParent, and mTagname.
operator=() [4/4]
JsonWriteData & hal::JsonWriteData::operator= (uint64_t u64Value)
Assign unsigned 64 bit value to JSON field.
Parameters
[in] u64Value - The numerical content.
Returns
The instance of the class.
Definition at line 55 of file json_write_document.cpp.
References hal::JsonWriteObject::add_member(), allocator(), mParent, and mTagname.
Friends And Related Function Documentation
JsonWriteComplex
friend class JsonWriteComplex friend
Definition at line 49 of file json_write_document.h.
Member Data Documentation
mParent
JsonWriteComplex* hal::JsonWriteData::mParent protected
Definition at line 53 of file json_write_document.h.
Referenced by allocator(), hal::JsonWriteComplex::close(), and operator=().
mTagname
std::string hal::JsonWriteData::mTagname protected
Definition at line 52 of file json_write_document.h.
Referenced by hal::JsonWriteObject::finalize(), hal::JsonWriteDocument::finalize(), and operator=().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/include/hal_core/utilities/json_write_document.h
/home/runner/work/hal/hal/src/utilities/json_write_document.cpp