HAL: hal::GroupingManagerWidget Class Reference
hal::GroupingManagerWidget Class Reference
HAL Gui » Utility Widgets » Grouping Widget
User interface for Groupings.
#include <grouping_manager_widget.h>
Public Slots
void handleLastEntryDeleted ()
void handleNewEntryAdded (const QModelIndex &modelIndex)
void handleCurrentChanged (const QModelIndex &current=QModelIndex(), const QModelIndex &previous=QModelIndex())
void handleToolboxPredecessor ()
void handleToolboxSuccessor ()
void handleToolboxPredecessorDistance ()
void handleToolboxSuccessorDistance ()
Public Slots inherited from hal::ContentWidget
void remove ()
void detach ()
void reattach ()
void open ()
void close ()
void handleSearchKeysequenceChanged (QKeySequence seq)
virtual void restoreFromProject ()
Public Slots inherited from hal::Widget
void hide ()
void show ()
Public Member Functions
GroupingManagerWidget (QWidget *parent=nullptr)
virtual void setupToolbar (Toolbar *toolbar) override
virtual QList< QShortcut * > createShortcuts () override
GroupingTableModel * getModel () const
GroupingProxyModel * getProxyModel () const
void setToolbarButtonsEnabled (bool enable)
void enableSearchbar (bool enable)
void newGroupingSuccOrPred (int maxDepth, bool succ, const GraphicsItem *item)
void newGroupingByDistance (int maxDepth, bool succ, const GraphicsItem *item)
Q_PROPERTY READ Functions
QString newGroupingIconPath () const
QString newGroupingIconStyle () const
QString toolboxIconPath () const
QString toolboxIconStyle () const
QString renameGroupingIconPath () const
QString renameGroupingIconStyle () const
QString deleteIconPath () const
QString deleteIconStyle () const
QString colorSelectIconPath () const
QString colorSelectIconStyle () const
QString toSelectionIconPath () const
QString toSelectionIconStyle () const
QString disabledIconStyle () const
QString searchIconPath () const
QString searchIconStyle () const
QString searchActiveIconStyle () const
QString tableIconPath () const
QString tableIconStyle () const
Q_PROPERTY WRITE Functions
void setDisabledIconStyle (const QString &style)
void setNewGroupingIconPath (const QString &path)
void setNewGroupingIconStyle (const QString &style)
void setToolboxIconPath (const QString &path)
void setToolboxIconStyle (const QString &style)
void setRenameGroupingIconPath (const QString &path)
void setRenameGroupingIconStyle (const QString &style)
void setDeleteIconPath (const QString &path)
void setDeleteIconStyle (const QString &style)
void setColorSelectIconPath (const QString &path)
void setColorSelectIconStyle (const QString &style)
void setToSelectionIconPath (const QString &path)
void setToSelectionIconStyle (const QString &style)
void setSearchIconPath (const QString &path)
void setSearchIconStyle (const QString &style)
void setSearchActiveIconStyle (const QString &style)
void setTableIconPath (const QString &path)
void setTableIconStyle (const QString &style)
Public Member Functions inherited from hal::ContentWidget
ContentWidget (QString name, QWidget *parent=nullptr)
void repolish ()
QString name ()
QIcon icon ()
void setAnchor (ContentAnchor *anchor)
void setIcon (QIcon icon)
void set_name (const QString &name)
QString iconStyle ()
QString iconPath ()
void setIconStyle (const QString &style)
void setIconPath (const QString &path)
Public Member Functions inherited from hal::Widget
Widget (QWidget *parent=nullptr)
void setParent (QWidget *parent)
Public Member Functions inherited from QWidget
QWidget (QWidget *parent, Qt::WindowFlags f)
virtual ~QWidget ()
WId winId () const const
WId effectiveWinId () const const
QStyle * style () const const
void setStyle (QStyle *style)
bool isTopLevel () const const
bool isWindow () const const
bool isModal () const const
Qt::WindowModality windowModality () const const
void setWindowModality (Qt::WindowModality windowModality)
bool isEnabled () const const
bool isEnabledTo (const QWidget *ancestor) const const
bool isEnabledToTLW () const const
void setEnabled (bool)
void setDisabled (bool disable)
void setWindowModified (bool)
QRect frameGeometry () const const
const QRect & geometry () const const
QRect normalGeometry () const const
int x () const const
int y () const const
QPoint pos () const const
QSize frameSize () const const
QSize size () const const
int width () const const
int height () const const
QRect rect () const const
QRect childrenRect () const const
QRegion childrenRegion () const const
QSize minimumSize () const const
QSize maximumSize () const const
int minimumWidth () const const
int minimumHeight () const const
int maximumWidth () const const
int maximumHeight () const const
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
void setMinimumWidth (int minw)
void setMinimumHeight (int minh)
void setMaximumWidth (int maxw)
void setMaximumHeight (int maxh)
void setupUi (QWidget *widget)
QSize sizeIncrement () const const
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
QSize baseSize () const const
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
void setFixedSize (const QSize &s)
void setFixedSize (int w, int h)
void setFixedWidth (int w)
void setFixedHeight (int h)
QPoint mapToGlobal (const QPoint &pos) const const
QPoint mapFromGlobal (const QPoint &pos) const const
QPoint mapToParent (const QPoint &pos) const const
QPoint mapFromParent (const QPoint &pos) const const
QPoint mapTo (const QWidget *parent, const QPoint &pos) const const
QPoint mapFrom (const QWidget *parent, const QPoint &pos) const const
QWidget * window () const const
QWidget * nativeParentWidget () const const
QWidget * topLevelWidget () const const
const QPalette & palette () const const
void setPalette (const QPalette &)
void setBackgroundRole (QPalette::ColorRole role)
QPalette::ColorRole backgroundRole () const const
void setForegroundRole (QPalette::ColorRole role)
QPalette::ColorRole foregroundRole () const const
const QFont & font () const const
void setFont (const QFont &)
QFontMetrics fontMetrics () const const
QFontInfo fontInfo () const const
QCursor cursor () const const
void setCursor (const QCursor &)
void unsetCursor ()
void setMouseTracking (bool enable)
bool hasMouseTracking () const const
bool underMouse () const const
void setTabletTracking (bool enable)
bool hasTabletTracking () const const
void setMask (const QBitmap &bitmap)
void setMask (const QRegion &region)
QRegion mask () const const
void clearMask ()
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void render (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
QPixmap grab (const QRect &rectangle)
QGraphicsEffect * graphicsEffect () const const
void setGraphicsEffect (QGraphicsEffect *effect)
void grabGesture (Qt::GestureType gesture, Qt::GestureFlags flags)
void ungrabGesture (Qt::GestureType gesture)
void setWindowTitle (const QString &)
void setStyleSheet (const QString &styleSheet)
QString styleSheet () const const
QString windowTitle () const const
void setWindowIcon (const QIcon &icon)
QIcon windowIcon () const const
void setWindowIconText (const QString &)
QString windowIconText () const const
void setWindowRole (const QString &role)
QString windowRole () const const
void setWindowFilePath (const QString &filePath)
QString windowFilePath () const const
void setWindowOpacity (qreal level)
qreal windowOpacity () const const
bool isWindowModified () const const
void setToolTip (const QString &)
QString toolTip () const const
void setToolTipDuration (int msec)
int toolTipDuration () const const
void setStatusTip (const QString &)
QString statusTip () const const
void setWhatsThis (const QString &)
QString whatsThis () const const
QString accessibleName () const const
void setAccessibleName (const QString &name)
QString accessibleDescription () const const
void setAccessibleDescription (const QString &description)
void setLayoutDirection (Qt::LayoutDirection direction)
Qt::LayoutDirection layoutDirection () const const
void unsetLayoutDirection ()
void setLocale (const QLocale &locale)
QLocale locale () const const
void unsetLocale ()
void setFocus ()
bool isActiveWindow () const const
void activateWindow ()
void clearFocus ()
void setFocus (Qt::FocusReason reason)
Qt::FocusPolicy focusPolicy () const const
void setFocusPolicy (Qt::FocusPolicy policy)
bool hasFocus () const const
void setFocusProxy (QWidget *w)
QWidget * focusProxy () const const
Qt::ContextMenuPolicy contextMenuPolicy () const const
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void grabMouse ()
void grabMouse (const QCursor &cursor)
void releaseMouse ()
void grabKeyboard ()
void releaseKeyboard ()
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context)
void releaseShortcut (int id)
void setShortcutEnabled (int id, bool enable)
void setShortcutAutoRepeat (int id, bool enable)
bool updatesEnabled () const const
void setUpdatesEnabled (bool enable)
QGraphicsProxyWidget * graphicsProxyWidget () const const
void update ()
void repaint ()
void update (int x, int y, int w, int h)
void update (const QRect &rect)
void update (const QRegion &rgn)
void repaint (int x, int y, int w, int h)
void repaint (const QRect &rect)
void repaint (const QRegion &rgn)
virtual void setVisible (bool visible)
void setHidden (bool hidden)
void show ()
void hide ()
void showMinimized ()
void showMaximized ()
void showFullScreen ()
void showNormal ()
bool close ()
void raise ()
void lower ()
void stackUnder (QWidget *w)
void move (int x, int y)
void move (const QPoint &)
void resize (int w, int h)
void resize (const QSize &)
void setGeometry (int x, int y, int w, int h)
void setGeometry (const QRect &)
QByteArray saveGeometry () const const
bool restoreGeometry (const QByteArray &geometry)
void adjustSize ()
bool isVisible () const const
bool isVisibleTo (const QWidget *ancestor) const const
bool isHidden () const const
bool isMinimized () const const
bool isMaximized () const const
bool isFullScreen () const const
Qt::WindowStates windowState () const const
void setWindowState (Qt::WindowStates windowState)
virtual QSize sizeHint () const const
virtual QSize minimumSizeHint () const const
QSizePolicy sizePolicy () const const
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
virtual int heightForWidth (int w) const const
virtual bool hasHeightForWidth () const const
QRegion visibleRegion () const const
void setContentsMargins (int left, int top, int right, int bottom)
void setContentsMargins (const QMargins &margins)
void getContentsMargins (int *left, int *top, int *right, int *bottom) const const
QMargins contentsMargins () const const
QRect contentsRect () const const
QLayout * layout () const const
void setLayout (QLayout *layout)
void updateGeometry ()
void setParent (QWidget *parent)
void setParent (QWidget *parent, Qt::WindowFlags f)
void scroll (int dx, int dy)
void scroll (int dx, int dy, const QRect &r)
QWidget * focusWidget () const const
QWidget * nextInFocusChain () const const
QWidget * previousInFocusChain () const const
bool acceptDrops () const const
void setAcceptDrops (bool on)
void addAction (QAction *action)
void addActions (QList< QAction * > actions)
void insertActions (QAction *before, QList< QAction * > actions)
void insertAction (QAction *before, QAction *action)
void removeAction (QAction *action)
QList< QAction * > actions () const const
QWidget * parentWidget () const const
void setWindowFlags (Qt::WindowFlags type)
Qt::WindowFlags windowFlags () const const
void setWindowFlag (Qt::WindowType flag, bool on)
void overrideWindowFlags (Qt::WindowFlags flags)
Qt::WindowType windowType () const const
QWidget * childAt (int x, int y) const const
QWidget * childAt (const QPoint &p) const const
void setAttribute (Qt::WidgetAttribute attribute, bool on)
bool testAttribute (Qt::WidgetAttribute attribute) const const
virtual QPaintEngine * paintEngine () const const override
void ensurePolished () const const
bool isAncestorOf (const QWidget *child) const const
bool hasEditFocus () const const
void setEditFocus (bool enable)
bool autoFillBackground () const const
void setAutoFillBackground (bool enabled)
QBackingStore * backingStore () const const
QWindow * windowHandle () const const
QScreen * screen () const const
void windowTitleChanged (const QString &title)
void windowIconChanged (const QIcon &icon)
void windowIconTextChanged (const QString &iconText)
void customContextMenuRequested (const QPoint &pos)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const const
Qt::InputMethodHints inputMethodHints () const const
void setInputMethodHints (Qt::InputMethodHints hints)
QWIDGETSIZE_MAX QWIDGETSIZE_MAX
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Member Functions inherited from QPaintDevice
virtual ~QPaintDevice ()
bool paintingActive () const const
int width () const const
int height () const const
int widthMM () const const
int heightMM () const const
int logicalDpiX () const const
int logicalDpiY () const const
int physicalDpiX () const const
int physicalDpiY () const const
int devicePixelRatio () const const
qreal devicePixelRatioF () const const
int colorCount () const const
int depth () const const
Properties
QString disabledIconStyle
QString newGroupingIconPath
QString newGroupingIconStyle
QString toolboxIconPath
QString toolboxIconStyle
QString renameGroupingIconPath
QString renameGroupingIconStyle
QString deleteIconPath
QString deleteIconStyle
QString colorSelectIconPath
QString colorSelectIconStyle
QString toSelectionIconPath
QString toSelectionIconStyle
QString searchIconPath
QString searchIconStyle
QString searchActiveIconStyle
QString tableIconPath
QString tableIconStyle
Properties inherited from hal::ContentWidget
QString iconStyle
QString iconPath
Properties inherited from QWidget
modal
windowModality
enabled
geometry
frameGeometry
normalGeometry
x
y
pos
frameSize
size
width
height
rect
childrenRect
childrenRegion
sizePolicy
minimumSize
maximumSize
minimumWidth
minimumHeight
maximumWidth
maximumHeight
sizeIncrement
baseSize
palette
font
cursor
mouseTracking
tabletTracking
isActiveWindow
focusPolicy
focus
contextMenuPolicy
updatesEnabled
visible
minimized
maximized
fullScreen
sizeHint
minimumSizeHint
acceptDrops
windowTitle
windowIcon
windowIconText
windowOpacity
windowModified
toolTip
toolTipDuration
statusTip
whatsThis
accessibleName
accessibleDescription
layoutDirection
windowFlags
autoFillBackground
styleSheet
locale
windowFilePath
inputMethodHints
Properties inherited from QObject
objectName
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag
Public Types inherited from QPaintDevice
enum PaintDeviceMetric
Signals inherited from hal::ContentWidget
void removed ()
void detached ()
void reattached ()
void opened ()
void closed ()
void name_changed (const QString &name)
Signals inherited from hal::Widget
void parentSetTo (QWidget *parent)
void hidden ()
void shown ()
Static Public Member Functions inherited from QWidget
void setTabOrder (QWidget *first, QWidget *second)
QWidget * mouseGrabber ()
QWidget * keyboardGrabber ()
QWidget * find (WId id)
QWidget * createWindowContainer (QWindow *window, QWidget *parent, Qt::WindowFlags flags)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QWidget
typedef RenderFlags
DrawWindowBackground
DrawChildren
IgnoreMask
Public Attributes inherited from QObject
typedef QObjectList
Public Attributes inherited from QPaintDevice
PdmWidth
PdmHeight
PdmWidthMM
PdmHeightMM
PdmNumColors
PdmDepth
PdmDpiX
PdmDpiY
PdmPhysicalDpiX
PdmPhysicalDpiY
PdmDevicePixelRatio
PdmDevicePixelRatioScaled
Protected Member Functions inherited from QWidget
virtual bool event (QEvent *event) override
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void focusInEvent (QFocusEvent *event)
virtual void focusOutEvent (QFocusEvent *event)
virtual void enterEvent (QEvent *event)
virtual void leaveEvent (QEvent *event)
virtual void paintEvent (QPaintEvent *event)
virtual void moveEvent (QMoveEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void contextMenuEvent (QContextMenuEvent *event)
virtual void tabletEvent (QTabletEvent *event)
virtual void actionEvent (QActionEvent *event)
virtual void dragEnterEvent (QDragEnterEvent *event)
virtual void dragMoveEvent (QDragMoveEvent *event)
virtual void dragLeaveEvent (QDragLeaveEvent *event)
virtual void dropEvent (QDropEvent *event)
virtual void showEvent (QShowEvent *event)
virtual void hideEvent (QHideEvent *event)
virtual bool nativeEvent (const QByteArray &eventType, void *message, long *result)
virtual void changeEvent (QEvent *event)
virtual int metric (QPaintDevice::PaintDeviceMetric m) const const override
virtual void initPainter (QPainter *painter) const const override
virtual void inputMethodEvent (QInputMethodEvent *event)
void updateMicroFocus ()
void create (WId window, bool initializeWindow, bool destroyOldWindow)
void destroy (bool destroyWindow, bool destroySubWindows)
virtual bool focusNextPrevChild (bool next)
bool focusNextChild ()
bool focusPreviousChild ()
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Member Functions inherited from QPaintDevice
QPaintDevice ()
Protected Attributes inherited from hal::ContentWidget
QVBoxLayout * mContentLayout
QAction * mSearchAction
QShortcut * mSearchShortcut
QKeySequence mSearchKeysequence
Detailed Description
User interface for Groupings.
Groupings are disjoint subsets of Gates, Modules and Nets that can be used to categorize these objects. In the GUI the groupings are drawn in their specified color. The objects of one grouping can be easily selected all together to simplify the work with gates/modules/nets that share a certain property.
Definition at line 58 of file grouping_manager_widget.h.
Constructor & Destructor Documentation
GroupingManagerWidget()
hal::GroupingManagerWidget::GroupingManagerWidget (QWidget * parent = nullptr)
Constructor.
Parameters
parent - The parent widget
Definition at line 37 of file grouping_manager_widget.cpp.
References QShortcut::activated(), QBoxLayout::addWidget(), Qt::AlignCenter, Qt::AlignHCenter, QObject::connect(), QItemSelectionModel::currentChanged(), QWidget::customContextMenuRequested(), QAbstractItemView::doubleClicked(), QWidget::ensurePolished(), QSizePolicy::Expanding, QApplication::focusChanged(), QWidget::font, hal::SearchProxyModel::getColumnNames(), hal::gui_utility::getStyledSvgIcon(), handleCurrentChanged(), handleLastEntryDeleted(), handleNewEntryAdded(), QWidget::hide(), QTableView::horizontalHeader(), hal::SettingsItemKeybind::keySequenceChanged(), hal::GroupingTableModel::lastEntryDeleted(), hal::ContentWidget::mContentLayout, hal::ContentWidget::mSearchAction, hal::GroupingTableModel::newEntryAdded(), QHeaderView::ResizeToContents, hal::GroupingColorSerializer::restore(), QAbstractItemView::selectionModel(), QAbstractItemView::SelectRows, hal::Searchbar::setColumnNames(), QWidget::setContextMenuPolicy(), QHeaderView::setDefaultAlignment(), QShortcut::setEnabled(), QWidget::setFont(), QAction::setIcon(), QAbstractItemView::setItemDelegateForColumn(), QShortcut::setKey(), QTableView::setModel(), QHeaderView::setSectionResizeMode(), QAbstractItemView::setSelectionBehavior(), QAbstractItemView::setSelectionMode(), QWidget::setSizePolicy(), QTableView::setSortingEnabled(), QSortFilterProxyModel::setSortRole(), QSortFilterProxyModel::setSourceModel(), QAction::setText(), QAction::setToolTip(), QAbstractItemView::SingleSelection, QTableView::sortByColumn(), hal::ContentManager::sSettingDeleteItem, hal::GroupingProxyModel::startSearch(), QHeaderView::Stretch, QAction::triggered(), hal::Searchbar::triggerNewSearch(), Qt::UserRole, and QTableView::verticalHeader().
Member Function Documentation
colorSelectIconPath()
QString hal::GroupingManagerWidget::colorSelectIconPath () const
Definition at line 723 of file grouping_manager_widget.cpp.
colorSelectIconStyle()
QString hal::GroupingManagerWidget::colorSelectIconStyle () const
Definition at line 728 of file grouping_manager_widget.cpp.
createShortcuts()
QList< QShortcut * > hal::GroupingManagerWidget::createShortcuts () override virtual
Create and connect the shortcuts that were provided by the GroupingsManagerWidget
Returns
the list of created shortcuts.
Reimplemented from hal::ContentWidget.
Definition at line 129 of file grouping_manager_widget.cpp.
References QShortcut::activated(), QList::append(), QObject::connect(), hal::ContentWidget::mSearchAction, hal::ContentWidget::mSearchKeysequence, hal::ContentWidget::mSearchShortcut, and QAction::trigger().
deleteIconPath()
QString hal::GroupingManagerWidget::deleteIconPath () const
Definition at line 713 of file grouping_manager_widget.cpp.
deleteIconStyle()
QString hal::GroupingManagerWidget::deleteIconStyle () const
Definition at line 718 of file grouping_manager_widget.cpp.
disabledIconStyle()
QString hal::GroupingManagerWidget::disabledIconStyle () const
Definition at line 678 of file grouping_manager_widget.cpp.
enableSearchbar()
void hal::GroupingManagerWidget::enableSearchbar (bool enable)
Enable/Disable the searchbar and update icon accordingly
Definition at line 666 of file grouping_manager_widget.cpp.
References hal::enable, hal::gui_utility::getStyledSvgIcon(), QWidget::hide(), hal::ContentWidget::iconStyle, QWidget::isVisible(), hal::ContentWidget::mSearchAction, QAction::setEnabled(), QWidget::setFocus(), and QAction::setIcon().
Referenced by handleCurrentChanged().
getModel()
GroupingTableModel* hal::GroupingManagerWidget::getModel () const inline
Accesses the underlying table model of this GroupingManagerWidget.
Returns
the GroupingTableModel of this GroupingManagerWidget
Definition at line 156 of file grouping_manager_widget.h.
Referenced by hal::GraphicsScene::connectAll(), hal::GraphicsScene::disconnectAll(), hal::ActionCreateObject::exec(), hal::ActionDeleteObject::exec(), hal::ActionRenameObject::exec(), hal::ActionSetObjectColor::exec(), hal::GraphicsItem::groupingColor(), hal::GroupingsOfItemModel::GroupingsOfItemModel(), hal::StandardGraphicsGate::paint(), and hal::GroupingColorSerializer::serialize().
getProxyModel()
GroupingProxyModel* hal::GroupingManagerWidget::getProxyModel () const inline
Get the underlying proxy model that is used to sort and filter the normal model.
Returns
The proxy model.
Definition at line 166 of file grouping_manager_widget.h.
Referenced by hal::ContentManager::handleOpenDocument().
handleCurrentChanged
void hal::GroupingManagerWidget::handleCurrentChanged (const QModelIndex & current = QModelIndex(), const QModelIndex & previous = QModelIndex()) slot
Q_SLOT to handle that the current item of the table views selection model has been changed.
Parameters
current - The index of the newly current item.
previous - The index of the previous current item.
Definition at line 611 of file grouping_manager_widget.cpp.
References QString::at(), disabledIconStyle, hal::enable, enableSearchbar(), hal::gui_utility::getStyledSvgIcon(), hal::ContentWidget::iconPath, hal::ContentWidget::iconStyle, QModelIndex::isValid(), hal::GroupingTableModel::rowCount(), QAction::setEnabled(), and QAction::setIcon().
Referenced by GroupingManagerWidget(), handleLastEntryDeleted(), and handleNewEntryAdded().
handleLastEntryDeleted
void hal::GroupingManagerWidget::handleLastEntryDeleted () slot
Q_SLOT to handle that the last entry of GroupingTableModel was deleted.
Definition at line 599 of file grouping_manager_widget.cpp.
References handleCurrentChanged(), QSortFilterProxyModel::index(), QSortFilterProxyModel::rowCount(), and QAbstractItemView::setCurrentIndex().
Referenced by GroupingManagerWidget().
handleNewEntryAdded
void hal::GroupingManagerWidget::handleNewEntryAdded (const QModelIndex & modelIndex) slot
Q_SLOT to handle that a new entry was added to the GroupingsTableModel.
Parameters
modelIndex - The index of the new entry withing the GroupingsTableModel
Definition at line 588 of file grouping_manager_widget.cpp.
References handleCurrentChanged(), QModelIndex::isValid(), QSortFilterProxyModel::mapFromSource(), and QAbstractItemView::setCurrentIndex().
Referenced by GroupingManagerWidget().
handleToolboxPredecessor
void hal::GroupingManagerWidget::handleToolboxPredecessor () slot
Adds predecessors of the currently selected gate or module to a new grouping.
Definition at line 305 of file grouping_manager_widget.cpp.
References newGroupingSuccOrPred().
handleToolboxPredecessorDistance
void hal::GroupingManagerWidget::handleToolboxPredecessorDistance () slot
Performs a BFS with a max-depth of three and creates a new grouping for the predecessors of each depth.
Definition at line 368 of file grouping_manager_widget.cpp.
References newGroupingByDistance().
handleToolboxSuccessor
void hal::GroupingManagerWidget::handleToolboxSuccessor () slot
Adds successors of the currently selected gate or module to a new grouping.
Definition at line 310 of file grouping_manager_widget.cpp.
References newGroupingSuccOrPred().
handleToolboxSuccessorDistance
void hal::GroupingManagerWidget::handleToolboxSuccessorDistance () slot
Performs a BFS with a max-depth of three and creates a new grouping for the successors of each depth.
Definition at line 373 of file grouping_manager_widget.cpp.
References newGroupingByDistance().
newGroupingByDistance()
void hal::GroupingManagerWidget::newGroupingByDistance (int maxDepth, bool succ, const GraphicsItem * item)
Creates groupings dependend on distance to start item.
Parameters
maxDepth - maximum recursion depth in view
succ - if true successors are highlighted, predecessors otherwise
item - the item to start from. If null recursion starts from first selected item.
Definition at line 378 of file grouping_manager_widget.cpp.
References hal::UserActionCompound::addAction(), QVector::append(), QVector::clear(), QSet::contains(), hal::UserActionCompound::exec(), hal::Node::Gate, hal::UserActionObjectType::Grouping, QSet::insert(), QSet::isEmpty(), QVector::isEmpty(), hal::Node::Module, test::n, and hal::UserActionCompound::setUseCreatedObject().
Referenced by handleToolboxPredecessorDistance(), and handleToolboxSuccessorDistance().
newGroupingIconPath()
QString hal::GroupingManagerWidget::newGroupingIconPath () const
Definition at line 683 of file grouping_manager_widget.cpp.
newGroupingIconStyle()
QString hal::GroupingManagerWidget::newGroupingIconStyle () const
Definition at line 688 of file grouping_manager_widget.cpp.
newGroupingSuccOrPred()
void hal::GroupingManagerWidget::newGroupingSuccOrPred (int maxDepth, bool succ, const GraphicsItem * item)
Creates a new grouping for successors or predecessors of item.
Parameters
maxDepth - maximum recursion depth in view
succ - if true successors are highlighted, predecessors otherwise
item - the item to start from. If null recursion starts from first selected item.
Definition at line 315 of file grouping_manager_widget.cpp.
References hal::UserActionCompound::addAction(), QVector::append(), QSet::contains(), hal::UserActionCompound::exec(), hal::Node::Gate, hal::UserActionObjectType::Grouping, QSet::insert(), QVector::isEmpty(), hal::Node::Module, test::n, and hal::UserActionCompound::setUseCreatedObject().
Referenced by handleToolboxPredecessor(), and handleToolboxSuccessor().
renameGroupingIconPath()
QString hal::GroupingManagerWidget::renameGroupingIconPath () const
Definition at line 703 of file grouping_manager_widget.cpp.
renameGroupingIconStyle()
QString hal::GroupingManagerWidget::renameGroupingIconStyle () const
Definition at line 708 of file grouping_manager_widget.cpp.
searchActiveIconStyle()
QString hal::GroupingManagerWidget::searchActiveIconStyle () const
Definition at line 818 of file grouping_manager_widget.cpp.
searchIconPath()
QString hal::GroupingManagerWidget::searchIconPath () const
Definition at line 808 of file grouping_manager_widget.cpp.
searchIconStyle()
QString hal::GroupingManagerWidget::searchIconStyle () const
Definition at line 813 of file grouping_manager_widget.cpp.
setColorSelectIconPath()
void hal::GroupingManagerWidget::setColorSelectIconPath (const QString & path)
Definition at line 788 of file grouping_manager_widget.cpp.
setColorSelectIconStyle()
void hal::GroupingManagerWidget::setColorSelectIconStyle (const QString & style)
Definition at line 793 of file grouping_manager_widget.cpp.
References QWidget::style().
setDeleteIconPath()
void hal::GroupingManagerWidget::setDeleteIconPath (const QString & path)
Definition at line 778 of file grouping_manager_widget.cpp.
setDeleteIconStyle()
void hal::GroupingManagerWidget::setDeleteIconStyle (const QString & style)
Definition at line 783 of file grouping_manager_widget.cpp.
References QWidget::style().
setDisabledIconStyle()
void hal::GroupingManagerWidget::setDisabledIconStyle (const QString & style)
Definition at line 743 of file grouping_manager_widget.cpp.
References QWidget::style().
setNewGroupingIconPath()
void hal::GroupingManagerWidget::setNewGroupingIconPath (const QString & path)
Definition at line 748 of file grouping_manager_widget.cpp.
setNewGroupingIconStyle()
void hal::GroupingManagerWidget::setNewGroupingIconStyle (const QString & style)
Definition at line 753 of file grouping_manager_widget.cpp.
References QWidget::style().
setRenameGroupingIconPath()
void hal::GroupingManagerWidget::setRenameGroupingIconPath (const QString & path)
Definition at line 768 of file grouping_manager_widget.cpp.
setRenameGroupingIconStyle()
void hal::GroupingManagerWidget::setRenameGroupingIconStyle (const QString & style)
Definition at line 773 of file grouping_manager_widget.cpp.
References QWidget::style().
setSearchActiveIconStyle()
void hal::GroupingManagerWidget::setSearchActiveIconStyle (const QString & style)
Definition at line 843 of file grouping_manager_widget.cpp.
References QWidget::style().
setSearchIconPath()
void hal::GroupingManagerWidget::setSearchIconPath (const QString & path)
Definition at line 833 of file grouping_manager_widget.cpp.
setSearchIconStyle()
void hal::GroupingManagerWidget::setSearchIconStyle (const QString & style)
Definition at line 838 of file grouping_manager_widget.cpp.
References QWidget::style().
setTableIconPath()
void hal::GroupingManagerWidget::setTableIconPath (const QString & path)
Definition at line 848 of file grouping_manager_widget.cpp.
setTableIconStyle()
void hal::GroupingManagerWidget::setTableIconStyle (const QString & style)
Definition at line 853 of file grouping_manager_widget.cpp.
References QWidget::style().
setToolbarButtonsEnabled()
void hal::GroupingManagerWidget::setToolbarButtonsEnabled (bool enable)
Enable/Disable the toolbar buttons which require a valid selection
Definition at line 579 of file grouping_manager_widget.cpp.
References hal::enable, and QAction::setEnabled().
setToolboxIconPath()
void hal::GroupingManagerWidget::setToolboxIconPath (const QString & path)
Definition at line 758 of file grouping_manager_widget.cpp.
setToolboxIconStyle()
void hal::GroupingManagerWidget::setToolboxIconStyle (const QString & style)
Definition at line 763 of file grouping_manager_widget.cpp.
References QWidget::style().
setToSelectionIconPath()
void hal::GroupingManagerWidget::setToSelectionIconPath (const QString & path)
Definition at line 798 of file grouping_manager_widget.cpp.
setToSelectionIconStyle()
void hal::GroupingManagerWidget::setToSelectionIconStyle (const QString & style)
Definition at line 803 of file grouping_manager_widget.cpp.
References QWidget::style().
setupToolbar()
void hal::GroupingManagerWidget::setupToolbar (Toolbar * toolbar) override virtual
Setups the toolbar with the actions that are supported by the grouping.
Parameters
toolbar - The toolbar to set up
Reimplemented from hal::ContentWidget.
Definition at line 567 of file grouping_manager_widget.cpp.
References QToolBar::addAction(), hal::ContentWidget::mSearchAction, hal::GroupingTableModel::rowCount(), and QAction::setEnabled().
tableIconPath()
QString hal::GroupingManagerWidget::tableIconPath () const
Definition at line 823 of file grouping_manager_widget.cpp.
tableIconStyle()
QString hal::GroupingManagerWidget::tableIconStyle () const
Definition at line 828 of file grouping_manager_widget.cpp.
toolboxIconPath()
QString hal::GroupingManagerWidget::toolboxIconPath () const
Definition at line 693 of file grouping_manager_widget.cpp.
toolboxIconStyle()
QString hal::GroupingManagerWidget::toolboxIconStyle () const
Definition at line 698 of file grouping_manager_widget.cpp.
toSelectionIconPath()
QString hal::GroupingManagerWidget::toSelectionIconPath () const
Definition at line 733 of file grouping_manager_widget.cpp.
toSelectionIconStyle()
QString hal::GroupingManagerWidget::toSelectionIconStyle () const
Definition at line 738 of file grouping_manager_widget.cpp.
Property Documentation
colorSelectIconPath
QString hal::GroupingManagerWidget::colorSelectIconPath read write
Definition at line 1 of file grouping_manager_widget.h.
colorSelectIconStyle
QString hal::GroupingManagerWidget::colorSelectIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
deleteIconPath
QString hal::GroupingManagerWidget::deleteIconPath read write
Definition at line 1 of file grouping_manager_widget.h.
deleteIconStyle
QString hal::GroupingManagerWidget::deleteIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
disabledIconStyle
QString hal::GroupingManagerWidget::disabledIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
Referenced by handleCurrentChanged().
newGroupingIconPath
QString hal::GroupingManagerWidget::newGroupingIconPath read write
Definition at line 1 of file grouping_manager_widget.h.
newGroupingIconStyle
QString hal::GroupingManagerWidget::newGroupingIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
renameGroupingIconPath
QString hal::GroupingManagerWidget::renameGroupingIconPath read write
Definition at line 1 of file grouping_manager_widget.h.
renameGroupingIconStyle
QString hal::GroupingManagerWidget::renameGroupingIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
searchActiveIconStyle
QString hal::GroupingManagerWidget::searchActiveIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
searchIconPath
QString hal::GroupingManagerWidget::searchIconPath read write
Definition at line 1 of file grouping_manager_widget.h.
searchIconStyle
QString hal::GroupingManagerWidget::searchIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
tableIconPath
QString hal::GroupingManagerWidget::tableIconPath read write
Definition at line 1 of file grouping_manager_widget.h.
tableIconStyle
QString hal::GroupingManagerWidget::tableIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
toolboxIconPath
QString hal::GroupingManagerWidget::toolboxIconPath read write
Definition at line 1 of file grouping_manager_widget.h.
toolboxIconStyle
QString hal::GroupingManagerWidget::toolboxIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
toSelectionIconPath
QString hal::GroupingManagerWidget::toSelectionIconPath read write
Definition at line 1 of file grouping_manager_widget.h.
toSelectionIconStyle
QString hal::GroupingManagerWidget::toSelectionIconStyle read write
Definition at line 1 of file grouping_manager_widget.h.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/grouping/grouping_manager_widget.h
/home/runner/work/hal/hal/plugins/gui/src/grouping/grouping_manager_widget.cpp