HAL: hal::BooleanInfluencePlugin Class Reference
hal::BooleanInfluencePlugin Class Reference
#include <plugin_boolean_influence.h>
Public Member Functions
std::string get_name () const override
std::string get_version () const override
void initialize () override
Public Member Functions inherited from hal::BasePluginInterface
BasePluginInterface ()=default
virtual ~BasePluginInterface ()
virtual std::string get_description () const
virtual std::set< std::string > get_dependencies () const
template<typename... Args>
void log (const Args &... args) const
virtual void on_load ()
virtual void on_unload ()
virtual void initialize_logging ()
virtual std::vector< AbstractExtensionInterface * > get_extensions () const
template<typename T >
T * get_first_extension () const
void delete_extension (AbstractExtensionInterface *aeif)
Static Public Member Functions
static Result< std::unordered_map< std::string, double > > get_boolean_influence (const BooleanFunction &bf, const u32 num_evaluations=32000, const std::string &unique_identifier="")
static Result< std::unordered_map< std::string, double > > get_boolean_influence (const z3::expr &e, const u32 num_evaluations=32000, const std::string &unique_identifier="")
static Result< std::unordered_map< std::string, double > > get_boolean_influence_deterministic (const BooleanFunction &bf, const std::string &unique_identifier="")
static Result< std::unordered_map< std::string, double > > get_boolean_influence_deterministic (const z3::expr &e, const std::string &unique_identifier="")
static Result< std::map< Net *, double > > get_boolean_influences_of_subcircuit (const std::vector< Gate * > &gates, const Net *start_net, const u32 num_evaluations=32000, const std::string &unique_identifier="")
static Result< std::map< Net *, double > > get_boolean_influences_of_gate (const Gate *gate, const u32 num_evaluations=32000, const std::string &unique_identifier="")
static Result< std::map< Net *, double > > get_boolean_influences_of_subcircuit_deterministic (const std::vector< Gate * > &gates, const Net *start_net, const std::string &unique_identifier="")
static Result< std::map< Net *, double > > get_boolean_influences_of_gate_deterministic (const Gate *gate, const std::string &unique_identifier="")
static Result< std::pair< std::map< u32, Gate * >, std::vector< std::vector< double > > > > get_ff_dependency_matrix (const Netlist *netlist, bool with_boolean_influence)
Additional Inherited Members
Protected Attributes inherited from hal::BasePluginInterface
std::vector< AbstractExtensionInterface * > m_extensions
Detailed Description
Definition at line 38 of file plugin_boolean_influence.h.
Member Function Documentation
get_boolean_influence() [1/2]
Result< std::unordered_map< std::string, double > > hal::BooleanInfluencePlugin::get_boolean_influence (const BooleanFunction & bf, const u32 num_evaluations = 32000, const std::string & unique_identifier = "") static
Generates the Boolean influence of each input variable of a Boolean function.
Parameters
[in] bf - The Boolean function.
[in] num_evaluations - The amount of evaluations that are performed for each input variable.
[in] unique_identifier - A unique identifier that is applied to file names to prevent collisions during multi-threading.
Returns
A map from the variables that appear in the function to their Boolean influence on said function on success, an error otherwise.
Definition at line 419 of file plugin_boolean_influence.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_boolean_influence() [2/2]
Result< std::unordered_map< std::string, double > > hal::BooleanInfluencePlugin::get_boolean_influence (const z3::expr & e, const u32 num_evaluations = 32000, const std::string & unique_identifier = "") static
Generates the Boolean influence of each input variable of a Boolean function.
Parameters
[in] e - The z3 expression representing a Boolean function.
[in] num_evaluations - The amount of evaluations that are performed for each input variable.
[in] unique_identifier - A unique identifier that is applied to file names to prevent collisions during multi threading.
Returns
A map from the variables that appear in the function to their Boolean influence on said function on success, an error otherwise.
Definition at line 427 of file plugin_boolean_influence.cpp.
get_boolean_influence_deterministic() [1/2]
Result< std::unordered_map< std::string, double > > hal::BooleanInfluencePlugin::get_boolean_influence_deterministic (const BooleanFunction & bf, const std::string & unique_identifier = "") static
Generates the Boolean influence of each input variable of a Boolean function.
Parameters
[in] bf - The Boolean function.
[in] unique_identifier - A unique identifier that is applied to file names to prevent collisions during multi-threading.
Returns
A map from the variables that appear in the function to their Boolean influence on said function on success, an error otherwise.
Definition at line 432 of file plugin_boolean_influence.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_boolean_influence_deterministic() [2/2]
Result< std::unordered_map< std::string, double > > hal::BooleanInfluencePlugin::get_boolean_influence_deterministic (const z3::expr & e, const std::string & unique_identifier = "") static
Generates the Boolean influence of each input variable of a Boolean function.
Parameters
[in] e - The z3 expression representing a Boolean function.
[in] unique_identifier - A unique identifier that is applied to file names to prevent collisions during multi threading.
Returns
A map from the variables that appear in the function to their Boolean influence on said function on success, an error otherwise.
Definition at line 440 of file plugin_boolean_influence.cpp.
get_boolean_influences_of_gate()
Result< std::map< Net *, double > > hal::BooleanInfluencePlugin::get_boolean_influences_of_gate (const Gate * gate, const u32 num_evaluations = 32000, const std::string & unique_identifier = "") static
Generates the function of the dataport net of the given flip-flop. Afterwards the generated function gets translated from a z3::expr to efficient c code, compiled, executed and evaluated.
Parameters
[in] gate - Pointer to the flip-flop which data input net is used to build the Boolean function.
[in] num_evaluations - The amount of evaluations that are performed for each input variable.
[in] unique_identifier - A unique identifier that is applied to file names to prevent collisions during multi threading.
Returns
A map from the nets that appear in the function of the data net to their Boolean influence on said function on success, an error otherwise.
Definition at line 451 of file plugin_boolean_influence.cpp.
Referenced by get_ff_dependency_matrix(), and hal::PYBIND11_PLUGIN().
get_boolean_influences_of_gate_deterministic()
Result< std::map< Net *, double > > hal::BooleanInfluencePlugin::get_boolean_influences_of_gate_deterministic (const Gate * gate, const std::string & unique_identifier = "") static
Generates the function of the dataport net of the given flip-flop. Afterwards the generated function gets translated from a z3::expr to efficient c code, compiled, executed and evaluated.
Parameters
[in] gate - Pointer to the flip-flop which data input net is used to build the Boolean function.
[in] unique_identifier - A unique identifier that is applied to file names to prevent collisions during multi threading.
Returns
A map from the nets that appear in the function of the data net to their Boolean influence on said function on success, an error otherwise.
Definition at line 462 of file plugin_boolean_influence.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_boolean_influences_of_subcircuit()
Result< std::map< Net *, double > > hal::BooleanInfluencePlugin::get_boolean_influences_of_subcircuit (const std::vector< Gate * > & gates, const Net * start_net, const u32 num_evaluations = 32000, const std::string & unique_identifier = "") static
Generates the function of the net using only the given gates. Afterwards the generated function gets translated from a z3::expr to efficent c code, compiled, executed and evaluated.
Parameters
[in] gates - The gates of the subcircuit.
[in] start_net - The output net of the subcircuit at which to start the analysis.
[in] num_evaluations - The amount of evaluations that are performed for each input variable.
[in] unique_identifier - A unique identifier that is applied to file names to prevent collisions during multi threading.
Returns
A map from the nets that appear in the function of the start net to their Boolean influence on said function on success, an error otherwise.
Definition at line 446 of file plugin_boolean_influence.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_boolean_influences_of_subcircuit_deterministic()
Result< std::map< Net *, double > > hal::BooleanInfluencePlugin::get_boolean_influences_of_subcircuit_deterministic (const std::vector< Gate * > & gates, const Net * start_net, const std::string & unique_identifier = "") static
Generates the function of the net using only the given gates. Afterwards the generated function gets translated from a z3::expr to efficent c code, compiled, executed and evaluated.
Parameters
[in] gates - The gates of the subcircuit.
[in] start_net - The output net of the subcircuit at which to start the analysis.
[in] unique_identifier - A unique identifier that is applied to file names to prevent collisions during multi threading.
Returns
A map from the nets that appear in the function of the start net to their Boolean influence on said function on success, an error otherwise.
Definition at line 457 of file plugin_boolean_influence.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_ff_dependency_matrix()
Result< std::pair< std::map< u32, Gate * >, std::vector< std::vector< double > > > > hal::BooleanInfluencePlugin::get_ff_dependency_matrix (const Netlist * netlist, bool with_boolean_influence) static
Get the FF dependency matrix of a netlist.
Parameters
[in] netlist - The netlist to extract the dependency matrix from.
[in] with_boolean_influence - True – set Boolean influence, False – sets 1.0 if connection between FFs
Returns
A pair consisting of std::map<u32, Gate*>, which includes the mapping from the original gate IDs to the ones in the matrix, and a std::vector<std::vector<double>, which is the ff dependency matrix
Definition at line 467 of file plugin_boolean_influence.cpp.
References ERR_APPEND, hal::ff, get_boolean_influences_of_gate(), hal::Gate::get_fan_out_nets(), hal::Netlist::get_gates(), hal::netlist_utils::get_next_sequential_gates(), log_info, and OK.
Referenced by hal::PYBIND11_PLUGIN().
get_name()
std::string hal::BooleanInfluencePlugin::get_name () const override virtual
Get the name of the plugin.
Returns
The name of the plugin.
Implements hal::BasePluginInterface.
Definition at line 18 of file plugin_boolean_influence.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_version()
std::string hal::BooleanInfluencePlugin::get_version () const override virtual
Get the version of the plugin.
Returns
The version of the plugin.
Implements hal::BasePluginInterface.
Definition at line 23 of file plugin_boolean_influence.cpp.
Referenced by hal::PYBIND11_PLUGIN().
initialize()
void hal::BooleanInfluencePlugin::initialize () override virtual
Plugins utilize two phase construction. Always populate all members etc in the initialize function which is automatically called by plugin_manager::get_plugin_instance()
Reimplemented from hal::BasePluginInterface.
Definition at line 28 of file plugin_boolean_influence.cpp.
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/boolean_influence/include/boolean_influence/plugin_boolean_influence.h
/home/runner/work/hal/hal/plugins/boolean_influence/src/plugin_boolean_influence.cpp