HAL: hal::NetLayoutConnectionFactory Class Reference
hal::NetLayoutConnectionFactory Class Reference
HAL Gui » Graph Widget » Layouters
#include <net_layout_point.h>
Public Member Functions
NetLayoutConnectionFactory (const QList< NetLayoutPoint > &sources, const QList< NetLayoutPoint > &destinations)
QList< NetLayoutPoint > points () const
void dump (const QString &stub) const
Public Attributes
NetLayoutConnection * connection
Detailed Description
Definition at line 150 of file net_layout_point.h.
Constructor & Destructor Documentation
NetLayoutConnectionFactory()
hal::NetLayoutConnectionFactory::NetLayoutConnectionFactory (const QList< NetLayoutPoint > & sources, const QList< NetLayoutPoint > & destinations)
Definition at line 394 of file net_layout_point.cpp.
References hal::NetLayoutConnection::add(), QList::append(), QList::at(), hal::NetLayoutConnection::closestPoint(), connection, test::n, hal::NetLayoutPoint::orderByDistance(), and QList::size().
Member Function Documentation
dump()
void hal::NetLayoutConnectionFactory::dump (const QString & stub) const
Definition at line 421 of file net_layout_point.cpp.
References QString::arg(), connection, hal::NetLayoutWire::SourcePoint, QIODevice::WriteOnly, QPoint::x(), and QPoint::y().
points()
QList<NetLayoutPoint> hal::NetLayoutConnectionFactory::points () const inline
Definition at line 154 of file net_layout_point.h.
Member Data Documentation
connection
NetLayoutConnection* hal::NetLayoutConnectionFactory::connection
Definition at line 155 of file net_layout_point.h.
Referenced by dump(), and NetLayoutConnectionFactory().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/net_layout_point.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/net_layout_point.cpp