HAL: hal::VerilogParser Class Reference
hal::VerilogParser Class Reference
HAL Core » Netlist » Netlist Parser
#include <verilog_parser.h>
Public Member Functions
VerilogParser ()=default
~VerilogParser ()=default
bool parse (const std::filesystem::path &file_path) override
std::unique_ptr< Netlist > instantiate (const GateLibrary *gate_library) override
Public Member Functions inherited from hal::NetlistParser
NetlistParser ()=default
virtual ~NetlistParser ()=default
std::unique_ptr< Netlist > parse_and_instantiate (const std::filesystem::path &file_path, const GateLibrary *gate_library)
Detailed Description
Definition at line 45 of file verilog_parser.h.
Constructor & Destructor Documentation
VerilogParser()
hal::VerilogParser::VerilogParser () default
~VerilogParser()
hal::VerilogParser::~VerilogParser () default
Member Function Documentation
instantiate()
std::unique_ptr< Netlist > hal::VerilogParser::instantiate (const GateLibrary * gate_library) override virtual
Instantiate the parsed Verilog netlist using the specified gate library.
Parameters
[in] gate_library - The gate library.
Returns
A pointer to the resulting netlist.
Implements hal::NetlistParser.
Definition at line 188 of file verilog_parser.cpp.
References hal::Net::add_source(), hal::Netlist::create_gate(), hal::Netlist::create_net(), hal::netlist_factory::create_netlist(), hal::Netlist::delete_net(), hal::Net::get_destinations(), hal::GateLibrary::get_gate_types(), hal::GateLibrary::get_gnd_gate_types(), hal::Netlist::get_gnd_gates(), hal::Net::get_name(), hal::Netlist::get_nets(), hal::Net::get_num_of_destinations(), hal::Net::get_num_of_sources(), hal::GateType::get_pins_of_direction(), hal::Netlist::get_unique_gate_id(), hal::GateLibrary::get_vcc_gate_types(), hal::Netlist::get_vcc_gates(), hal::Net::is_global_input_net(), hal::Net::is_global_output_net(), hal::Netlist::load_gate_locations_from_data(), log_error, hal::Netlist::mark_gnd_gate(), hal::Netlist::mark_vcc_gate(), hal::ShortestPath::net(), and hal::output.
parse()
bool hal::VerilogParser::parse (const std::filesystem::path & file_path) override virtual
Parse a Verilog netlist into an internal intermediate format.
Parameters
[in] file_path - Path to the Verilog netlist file.
Returns
True on success, false otherwise.
Implements hal::NetlistParser.
Definition at line 17 of file verilog_parser.cpp.
References log_error, and hal::ShortestPath::module().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/verilog_parser/include/verilog_parser/verilog_parser.h
/home/runner/work/hal/hal/plugins/verilog_parser/src/verilog_parser.cpp