HAL: hal::PinActionType Class Reference
hal::PinActionType Class Reference
#include <action_pingroup.h>
Public Types
enum Type {
None , GroupCreate , GroupDelete , GroupMoveToRow ,
GroupRename , GroupTypeChange , GroupDirChange , PinAsignToGroup ,
PinRename , PinTypeChange , PinDirChange , PinMoveToRow ,
MaxAction
}
Public Member Functions
Q_ENUM (Type)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static QString toString (Type tp)
static Type fromString (const QString &s)
static bool useExistingGroup (Type tp)
static bool useExistingPin (Type tp)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Additional Inherited Members
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
Definition at line 34 of file action_pingroup.h.
Member Enumeration Documentation
Type
enum hal::PinActionType::Type
Enumerator
None
GroupCreate
GroupDelete
GroupMoveToRow
GroupRename
GroupTypeChange
GroupDirChange
PinAsignToGroup
PinRename
PinTypeChange
PinDirChange
PinMoveToRow
MaxAction
Definition at line 38 of file action_pingroup.h.
Member Function Documentation
fromString()
PinActionType::Type hal::PinActionType::fromString (const QString & s) static
Definition at line 79 of file action_pingroup.cpp.
References QMetaEnum::key(), MaxAction, and None.
Referenced by hal::ActionPingroup::readFromXml().
Q_ENUM()
hal::PinActionType::Q_ENUM (Type)
toString()
QString hal::PinActionType::toString (PinActionType::Type tp) static
Definition at line 73 of file action_pingroup.cpp.
References QMetaEnum::key().
Referenced by hal::ActionPingroup::writeToXml().
useExistingGroup()
bool hal::PinActionType::useExistingGroup (PinActionType::Type tp) static
Definition at line 90 of file action_pingroup.cpp.
References QSet::contains(), GroupDelete, GroupDirChange, GroupMoveToRow, GroupRename, and GroupTypeChange.
Referenced by hal::ActionPingroup::exec().
useExistingPin()
bool hal::PinActionType::useExistingPin (PinActionType::Type tp) static
Definition at line 96 of file action_pingroup.cpp.
References QSet::contains(), PinAsignToGroup, PinDirChange, PinMoveToRow, PinRename, and PinTypeChange.
Referenced by hal::ActionPingroup::exec().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/action_pingroup.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/action_pingroup.cpp