HAL: hal::PythonSyntaxHighlighter Class Reference
hal::PythonSyntaxHighlighter Class Reference
HAL Gui » Python
A syntax highlighter that fits for python code.
#include <python_syntax_highlighter.h>
Public Member Functions
PythonSyntaxHighlighter (QTextDocument *parent=nullptr)
Public Member Functions inherited from QSyntaxHighlighter
QSyntaxHighlighter (QObject *parent)
QSyntaxHighlighter (QTextDocument *parent)
virtual ~QSyntaxHighlighter ()
void setDocument (QTextDocument *doc)
QTextDocument * document () const const
void rehighlight ()
void rehighlightBlock (const QTextBlock &block)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Protected Member Functions
void highlightBlock (const QString &text) override
Protected Member Functions inherited from QSyntaxHighlighter
void setFormat (int start, int count, const QTextCharFormat &format)
void setFormat (int start, int count, const QColor &color)
void setFormat (int start, int count, const QFont &font)
QTextCharFormat format (int position) const const
int previousBlockState () const const
int currentBlockState () const const
void setCurrentBlockState (int newState)
void setCurrentBlockUserData (QTextBlockUserData *data)
QTextBlockUserData * currentBlockUserData () const const
QTextBlock currentBlock () const const
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Public Attributes inherited from QObject
typedef QObjectList
Properties inherited from QObject
objectName
Detailed Description
A syntax highlighter that fits for python code.
The following sections are distinguished and their color can be configured in the qss file:
Python Keywords (e.g. if, and, break, class, True, ...)
Operators (e.g. =, +, -, ==, &, <<, ...)
Brackets (round brackets (), curly brackets {} and square brackets [])
Single Quoted String ('string')
Double Quoted String ("string")
Keyword: self
Numbers (e.g. 42, 3.5, 0xDEADBEAF, 0765)
Comments (single- and multiline)
Definition at line 50 of file python_syntax_highlighter.h.
Constructor & Destructor Documentation
PythonSyntaxHighlighter()
hal::PythonSyntaxHighlighter::PythonSyntaxHighlighter (QTextDocument * parent = nullptr) explicit
Constructor. Initializes the syntax highlight patterns.
Parameters
parent - The parent text document
Definition at line 6 of file python_syntax_highlighter.cpp.
References QVector::append(), hal::PythonQssAdapter::instance(), hal::PythonQssAdapter::mBraceFormat, hal::PythonQssAdapter::mCommentFormat, hal::PythonQssAdapter::mDoubleQuotedStringFormat, hal::PythonQssAdapter::mKeywordFormat, hal::PythonQssAdapter::mNumberFormat, hal::PythonQssAdapter::mOperatorFormat, hal::PythonQssAdapter::mSelfFormat, and hal::PythonQssAdapter::mSingleQuotedStringFormat.
Member Function Documentation
highlightBlock()
void hal::PythonSyntaxHighlighter::highlightBlock (const QString & text) override protected virtual
Highlights the given text block.
Parameters
text - the text block to highlight
Implements QSyntaxHighlighter.
Definition at line 80 of file python_syntax_highlighter.cpp.
References QString::at(), QRegularExpressionMatch::capturedLength(), QRegularExpressionMatch::capturedStart(), QRegularExpressionMatch::hasMatch(), QRegularExpressionMatchIterator::hasNext(), hal::PythonQssAdapter::instance(), QString::length(), QRegularExpression::match(), hal::PythonQssAdapter::mCommentFormat, QRegularExpressionMatchIterator::next(), QSyntaxHighlighter::previousBlockState(), QSyntaxHighlighter::setCurrentBlockState(), and QSyntaxHighlighter::setFormat().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/code_editor/syntax_highlighter/python_syntax_highlighter.h
/home/runner/work/hal/hal/plugins/gui/src/code_editor/syntax_highlighter/python_syntax_highlighter.cpp