HAL: hal::GatePinsTreeModel Class Reference
hal::GatePinsTreeModel Class Reference
HAL Gui
A model to display the pins of a gate.
#include <pin_tree_model.h>
Public Types
enum itemType { itemType::grouping = 0, itemType::pin = 1 }
Public Types inherited from QAbstractItemModel
enum LayoutChangeHint
enum CheckIndexOption
Public Member Functions
GatePinsTreeModel (QObject *parent=nullptr)
~GatePinsTreeModel ()
void clear () override
void setGate (Gate *g)
int getCurrentGateID ()
QList< int > getNetIDsOfTreeItem (TreeItem *item)
itemType getTypeOfItem (TreeItem *item)
int getNumberOfDisplayedPins ()
Public Member Functions inherited from hal::BaseTreeModel
BaseTreeModel (QObject *parent=nullptr)
void setContent (QList< TreeItem * > firstLevelItems)
void setHeaderLabels (QList< QVariant > labels)
QModelIndex getIndexFromItem (TreeItem *item) const
TreeItem * getItemFromIndex (QModelIndex index) const
TreeItem * getRootItem () const
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
virtual QModelIndex parent (const QModelIndex &index) const override
virtual Qt::ItemFlags flags (const QModelIndex &index) const override
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const override
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const override
Public Member Functions inherited from QAbstractItemModel
QAbstractItemModel (QObject *parent)
virtual ~QAbstractItemModel ()
bool hasIndex (int row, int column, const QModelIndex &parent) const const
virtual QModelIndex sibling (int row, int column, const QModelIndex &index) const const
virtual bool hasChildren (const QModelIndex &parent) const const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role)
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const const
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
virtual QStringList mimeTypes () const const
virtual QMimeData * mimeData (const QModelIndexList &indexes) const const
virtual bool canDropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent) const const
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
virtual Qt::DropActions supportedDropActions () const const
virtual Qt::DropActions supportedDragActions () const const
void setSupportedDragActions (Qt::DropActions actions)
virtual bool insertRows (int row, int count, const QModelIndex &parent)
virtual bool insertColumns (int column, int count, const QModelIndex &parent)
virtual bool removeRows (int row, int count, const QModelIndex &parent)
virtual bool removeColumns (int column, int count, const QModelIndex &parent)
virtual bool moveRows (const QModelIndex &sourceParent, int sourceRow, int count, const QModelIndex &destinationParent, int destinationChild)
virtual bool moveColumns (const QModelIndex &sourceParent, int sourceColumn, int count, const QModelIndex &destinationParent, int destinationChild)
bool insertRow (int row, const QModelIndex &parent)
bool insertColumn (int column, const QModelIndex &parent)
bool removeRow (int row, const QModelIndex &parent)
bool removeColumn (int column, const QModelIndex &parent)
bool moveRow (const QModelIndex &sourceParent, int sourceRow, const QModelIndex &destinationParent, int destinationChild)
bool moveColumn (const QModelIndex &sourceParent, int sourceColumn, const QModelIndex &destinationParent, int destinationChild)
virtual void fetchMore (const QModelIndex &parent)
virtual bool canFetchMore (const QModelIndex &parent) const const
virtual void sort (int column, Qt::SortOrder order)
virtual QModelIndex buddy (const QModelIndex &index) const const
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits, Qt::MatchFlags flags) const const
virtual QSize span (const QModelIndex &index) const const
virtual QHash< int, QByteArray > roleNames () const const
bool checkIndex (const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options) const const
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles)
void headerDataChanged (Qt::Orientation orientation, int first, int last)
void layoutChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void layoutAboutToBeChanged (const QList< QPersistentModelIndex > &parents, QAbstractItemModel::LayoutChangeHint hint)
void rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
void modelAboutToBeReset ()
void modelReset ()
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual bool submit ()
virtual void revert ()
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Public Attributes
const QString keyType = "type"
const QString keyRepresentedNetsID = "netID"
Public Attributes inherited from QAbstractItemModel
typedef CheckIndexOptions
NoLayoutChangeHint
VerticalSortHint
HorizontalSortHint
NoOption
IndexIsValid
DoNotUseParent
ParentIsInvalid
Public Attributes inherited from QObject
typedef QObjectList
Static Public Attributes
static const int sNameColumn = 0
static const int sDirectionColumn = 1
static const int sTypeColumn = 2
static const int sConnectedNetColumn = 3
Additional Inherited Members
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Protected Member Functions inherited from QAbstractItemModel
void resetInternalData ()
QModelIndex createIndex (int row, int column, void *ptr) const const
QModelIndex createIndex (int row, int column, quintptr id) const const
void beginInsertRows (const QModelIndex &parent, int first, int last)
void endInsertRows ()
void beginRemoveRows (const QModelIndex &parent, int first, int last)
void endRemoveRows ()
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveRows ()
void beginInsertColumns (const QModelIndex &parent, int first, int last)
void endInsertColumns ()
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
void endRemoveColumns ()
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationChild)
void endMoveColumns ()
void reset ()
void beginResetModel ()
void endResetModel ()
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
QModelIndexList persistentIndexList () const const
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Protected Attributes inherited from hal::BaseTreeModel
TreeItem * mRootItem
Properties inherited from QObject
objectName
Detailed Description
A model to display the pins of a gate.
Definition at line 41 of file pin_tree_model.h.
Member Enumeration Documentation
itemType
enum hal::GatePinsTreeModel::itemType strong
Enumerator
grouping
pin
Definition at line 48 of file pin_tree_model.h.
Constructor & Destructor Documentation
GatePinsTreeModel()
hal::GatePinsTreeModel::GatePinsTreeModel (QObject * parent = nullptr)
The constructor.
Parameters
parent - The model's parent.
Definition at line 15 of file pin_tree_model.cpp.
References hal::BaseTreeModel::setHeaderLabels().
~GatePinsTreeModel()
hal::GatePinsTreeModel::~GatePinsTreeModel ()
The destructor.
Definition at line 27 of file pin_tree_model.cpp.
References hal::BaseTreeModel::mRootItem.
Member Function Documentation
clear()
void hal::GatePinsTreeModel::clear () override virtual
Overwritten BaseTreeModel function.
Reimplemented from hal::BaseTreeModel.
Definition at line 32 of file pin_tree_model.cpp.
References hal::BaseTreeModel::clear().
Referenced by hal::GatePinTree::removeContent(), and setGate().
getCurrentGateID()
int hal::GatePinsTreeModel::getCurrentGateID ()
Get the ID of the gate that is currently displayed. If no gate is currently displayed, -1 is returned.
Returns
The gate's id.
Definition at line 116 of file pin_tree_model.cpp.
getNetIDsOfTreeItem()
QList< int > hal::GatePinsTreeModel::getNetIDsOfTreeItem (TreeItem * item)
Get the connected nets for a given treeitem (represents a pin). If the item is grouping type or the pin has no connected net, an empty list is returned. In case of an inout pin, even multiple connected nets are possible.
Parameters
item - The treeitem from which to get the connected nets.
Returns
A list of net ids.
Definition at line 121 of file pin_tree_model.cpp.
References hal::TreeItem::getAdditionalData(), keyRepresentedNetsID, and QVariant::value().
Referenced by hal::GatePinTree::handleContextMenuRequested(), and hal::GatePinTree::mouseDoubleClickEvent().
getNumberOfDisplayedPins()
int hal::GatePinsTreeModel::getNumberOfDisplayedPins ()
Get the number of displayed pins (the number of pins of all types).
Returns
The number of pins.
Definition at line 131 of file pin_tree_model.cpp.
References test_plugin::g, hal::Netlist::get_gate_by_id(), and hal::gNetlist.
Referenced by hal::GatePinTree::setGate().
getTypeOfItem()
GatePinsTreeModel::itemType hal::GatePinsTreeModel::getTypeOfItem (TreeItem * item)
Get the type (enum) of a given item.
Parameters
item - The item for which the type is requested.
Returns
The item's type.
Definition at line 126 of file pin_tree_model.cpp.
References hal::TreeItem::getAdditionalData(), keyType, and QVariant::value().
Referenced by hal::GatePinTree::handleContextMenuRequested(), and hal::GatePinTree::mouseDoubleClickEvent().
setGate()
void hal::GatePinsTreeModel::setGate (Gate * g)
Sets the gate of the pins this model will represent.
Parameters
g - The gate of the pins.
Definition at line 39 of file pin_tree_model.cpp.
References QList::append(), hal::TreeItem::appendChild(), QAbstractItemModel::beginResetModel(), clear(), direction, QAbstractItemModel::endResetModel(), hal::enum_to_string(), QString::fromStdString(), QVariant::fromValue(), test_plugin::g, hal::GateType::get_pins(), grouping, hal::inout, hal::input, QString::isEmpty(), keyRepresentedNetsID, keyType, hal::BaseTreeModel::mRootItem, hal::output, pin, hal::TreeItem::setAdditionalData(), and hal::TreeItem::setData().
Referenced by hal::GatePinTree::setGate().
Member Data Documentation
keyRepresentedNetsID
const QString hal::GatePinsTreeModel::keyRepresentedNetsID = "netID"
Definition at line 116 of file pin_tree_model.h.
Referenced by getNetIDsOfTreeItem(), and setGate().
keyType
const QString hal::GatePinsTreeModel::keyType = "type"
Definition at line 115 of file pin_tree_model.h.
Referenced by getTypeOfItem(), and setGate().
sConnectedNetColumn
const int hal::GatePinsTreeModel::sConnectedNetColumn = 3 static
Definition at line 112 of file pin_tree_model.h.
sDirectionColumn
const int hal::GatePinsTreeModel::sDirectionColumn = 1 static
Definition at line 110 of file pin_tree_model.h.
Referenced by hal::GatePinTree::handleContextMenuRequested(), and hal::GatePinTree::mouseDoubleClickEvent().
sNameColumn
const int hal::GatePinsTreeModel::sNameColumn = 0 static
Definition at line 109 of file pin_tree_model.h.
Referenced by hal::GatePinTree::handleContextMenuRequested().
sTypeColumn
const int hal::GatePinsTreeModel::sTypeColumn = 2 static
Definition at line 111 of file pin_tree_model.h.
Referenced by hal::GatePinTree::handleContextMenuRequested().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/gate_details_widget/pin_tree_model.h
/home/runner/work/hal/hal/plugins/gui/src/selection_details_widget/gate_details_widget/pin_tree_model.cpp