HAL: hal::UserActionObjectType Class Reference
hal::UserActionObjectType Class Reference
HAL Gui » User Actions
The UserActionObjectType class provides the type for UserActionObject.
#include <user_action_object.h>
Public Types
enum ObjectType {
None , Module , Gate , Net ,
Grouping , Netlist , ContextView , ContextDir ,
MaxObjectType
}
Public Member Functions
Q_ENUM (ObjectType) static ObjectType fromString(const QString &s)
Public Member Functions inherited from QObject
virtual const QMetaObject * metaObject () const const
QObject (QObject *parent)
virtual ~QObject ()
virtual bool event (QEvent *e)
virtual bool eventFilter (QObject *watched, QEvent *event)
QString objectName () const const
void setObjectName (const QString &name)
bool isWidgetType () const const
bool isWindowType () const const
bool signalsBlocked () const const
bool blockSignals (bool block)
QThread * thread () const const
void moveToThread (QThread *targetThread)
int startTimer (int interval, Qt::TimerType timerType)
int startTimer (std::chrono::milliseconds time, Qt::TimerType timerType)
void killTimer (int id)
T findChild (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QString &name, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegExp &regExp, Qt::FindChildOptions options) const const
QList< T > findChildren (const QRegularExpression &re, Qt::FindChildOptions options) const const
const QObjectList & children () const const
void setParent (QObject *parent)
void installEventFilter (QObject *filterObj)
void removeEventFilter (QObject *obj)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const char *method, Qt::ConnectionType type) const const
bool disconnect (const char *signal, const QObject *receiver, const char *method) const const
bool disconnect (const QObject *receiver, const char *method) const const
void dumpObjectTree ()
void dumpObjectInfo ()
void dumpObjectTree () const const
void dumpObjectInfo () const const
bool setProperty (const char *name, const QVariant &value)
QVariant property (const char *name) const const
QList< QByteArray > dynamicPropertyNames () const const
void destroyed (QObject *obj)
void objectNameChanged (const QString &objectName)
QObject * parent () const const
bool inherits (const char *className) const const
void deleteLater ()
Q_DISABLE_COPY (Class)
Q_DISABLE_MOVE (Class)
Q_DISABLE_COPY_MOVE (Class)
T qobject_cast (QObject *object)
T qobject_cast (const QObject *object)
T qFindChild (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QString &name)
QList< T > qFindChildren (const QObject *obj, const QRegExp &regExp)
Q_CLASSINFO (Name, Value)
Q_INTERFACES (...)
Q_PROPERTY (...)
Q_ENUMS (...)
Q_FLAGS (...)
Q_ENUM (...)
Q_FLAG (...)
Q_ENUM_NS (...)
Q_FLAG_NS (...)
Q_OBJECT Q_OBJECT
Q_GADGET Q_GADGET
Q_NAMESPACE Q_NAMESPACE
Q_NAMESPACE_EXPORT (EXPORT_MACRO)
Q_SIGNALS Q_SIGNALS
Q_SIGNAL Q_SIGNAL
Q_SLOTS Q_SLOTS
Q_SLOT Q_SLOT
Q_EMIT Q_EMIT
Q_INVOKABLE Q_INVOKABLE
Q_REVISION Q_REVISION
Q_SET_OBJECT_NAME (Object)
QT_NO_NARROWING_CONVERSIONS_IN_CONNECT QT_NO_NARROWING_CONVERSIONS_IN_CONNECT
Static Public Member Functions
static QString toString (ObjectType t)
static ObjectType fromSelectionType (SelectionRelay::ItemType itp)
static SelectionRelay::ItemType toSelectionType (ObjectType t)
static ObjectType fromHalType (hal::ItemType itp)
static hal::ItemType toHalType (ObjectType t)
static ObjectType fromNodeType (Node::NodeType ntp)
static Node::NodeType toNodeType (ObjectType t)
Static Public Member Functions inherited from QObject
QString tr (const char *sourceText, const char *disambiguation, int n)
QString trUtf8 (const char *sourceText, const char *disambiguation, int n)
QMetaObject::Connection connect (const QObject *sender, const char *signal, const QObject *receiver, const char *method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method, Qt::ConnectionType type)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, Functor functor)
QMetaObject::Connection connect (const QObject *sender, PointerToMemberFunction signal, const QObject *context, Functor functor, Qt::ConnectionType type)
bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *method)
bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method)
bool disconnect (const QMetaObject::Connection &connection)
bool disconnect (const QObject *sender, PointerToMemberFunction signal, const QObject *receiver, PointerToMemberFunction method)
Additional Inherited Members
Public Attributes inherited from QObject
typedef QObjectList
Protected Member Functions inherited from QObject
QObject * sender () const const
int senderSignalIndex () const const
int receivers (const char *signal) const const
bool isSignalConnected (const QMetaMethod &signal) const const
virtual void timerEvent (QTimerEvent *event)
virtual void childEvent (QChildEvent *event)
virtual void customEvent (QEvent *event)
virtual void connectNotify (const QMetaMethod &signal)
virtual void disconnectNotify (const QMetaMethod &signal)
Properties inherited from QObject
objectName
Detailed Description
The UserActionObjectType class provides the type for UserActionObject.
There are conversation methods to conveniently convert the type for persistence to xml file and for graphics ItemType
Definition at line 44 of file user_action_object.h.
Member Enumeration Documentation
ObjectType
enum hal::UserActionObjectType::ObjectType
Enumerator
None
Module
Gate
Net
Grouping
Netlist
ContextView
ContextDir
MaxObjectType
Definition at line 48 of file user_action_object.h.
Member Function Documentation
fromHalType()
UserActionObjectType::ObjectType hal::UserActionObjectType::fromHalType (hal::ItemType itp) static
Definition at line 21 of file user_action_object.cpp.
References hal::Gate, Gate, hal::Module, Module, hal::Net, Net, and None.
fromNodeType()
UserActionObjectType::ObjectType hal::UserActionObjectType::fromNodeType (Node::NodeType ntp) static
Definition at line 73 of file user_action_object.cpp.
References hal::Node::Gate, Gate, hal::Node::Module, Module, and None.
Referenced by hal::ActionAddItemsToObject::writeToXml().
fromSelectionType()
UserActionObjectType::ObjectType hal::UserActionObjectType::fromSelectionType (SelectionRelay::ItemType itp) static
Definition at line 47 of file user_action_object.cpp.
References hal::SelectionRelay::Gate, Gate, hal::SelectionRelay::Module, Module, hal::SelectionRelay::Net, Net, and None.
Referenced by hal::ActionSetSelectionFocus::exec(), hal::ActionSetSelectionFocus::hasModifications(), and hal::SelectionRelay::setFocus().
Q_ENUM()
hal::UserActionObjectType::Q_ENUM (ObjectType) const &
toHalType()
hal::ItemType hal::UserActionObjectType::toHalType (UserActionObjectType::ObjectType t) static
Definition at line 34 of file user_action_object.cpp.
References hal::Gate, Gate, hal::Module, Module, hal::Net, Net, and hal::None.
toNodeType()
Node::NodeType hal::UserActionObjectType::toNodeType (UserActionObjectType::ObjectType t) static
Definition at line 85 of file user_action_object.cpp.
References hal::Node::Gate, Gate, hal::Node::Module, Module, and hal::Node::None.
Referenced by hal::ActionAddItemsToObject::readFromXml().
toSelectionType()
SelectionRelay::ItemType hal::UserActionObjectType::toSelectionType (UserActionObjectType::ObjectType t) static
Definition at line 60 of file user_action_object.cpp.
References hal::SelectionRelay::Gate, Gate, hal::SelectionRelay::Module, Module, hal::SelectionRelay::Net, Net, and hal::SelectionRelay::None.
Referenced by hal::ActionSetSelectionFocus::exec().
toString()
QString hal::UserActionObjectType::toString (ObjectType t) static
Definition at line 15 of file user_action_object.cpp.
References QMetaEnum::key().
Referenced by hal::UserActionObject::writeToXml(), and hal::ActionAddItemsToObject::writeToXml().
The documentation for this class was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/user_action/user_action_object.h
/home/runner/work/hal/hal/plugins/gui/src/user_action/user_action_object.cpp