HAL: hal::DetailsGeneralCommonInfo< T > Class Template Reference
hal::DetailsGeneralCommonInfo< T > Class Template Reference
HAL Gui » Utility Widgets » Selection Details Widget
Helper wrapper class.
#include <details_general_model.h>
Public Member Functions
QString getPythonBase (Module *m)
QString getPythonBase (Gate *g)
QString getPythonBase (Net *n)
QString name () const
QString grouping () const
QString typeName () const
u32 id () const
DetailsGeneralCommonInfo (T *item)
Detailed Description
template<typename T>
class hal::DetailsGeneralCommonInfo< T >
Helper wrapper class.
A convenience class used to gather and extract the commonly shared information (such as name, type, id) of a module, gate and net in a single place. It functions as sort of a wrapper class.
Definition at line 142 of file details_general_model.h.
Constructor & Destructor Documentation
DetailsGeneralCommonInfo()
template<typename T > hal::DetailsGeneralCommonInfo< T >::DetailsGeneralCommonInfo (T * item) inline
The constructor. The commonly shared information of all items are extracted here.
Parameters
item - The item to extract the information from (module, gate or net).
Definition at line 267 of file details_general_model.h.
References QString::fromStdString().
Member Function Documentation
getPythonBase() [1/3]
template<typename T > QString hal::DetailsGeneralCommonInfo< T >::getPythonBase (Gate * g) inline
Generates the python code that returns the given gate.
Parameters
g - The gate for which to generate the python code.
Returns
The constructed python code.
Definition at line 206 of file details_general_model.h.
References QString::arg(), and g.
getPythonBase() [2/3]
template<typename T > QString hal::DetailsGeneralCommonInfo< T >::getPythonBase (Module * m) inline
Generates the python code that returns the given module.
Parameters
m - The module for which to generate the python code.
Returns
The constructed python code that returns the module.
Definition at line 195 of file details_general_model.h.
References QString::arg(), and hal::Module::get_id().
Referenced by hal::DetailsGeneralModel::setContent().
getPythonBase() [3/3]
template<typename T > QString hal::DetailsGeneralCommonInfo< T >::getPythonBase (Net * n) inline
Generates the python code that returns the given net.
Parameters
n - The net for which to generate the python code.
Returns
- The constructed python code.
Definition at line 217 of file details_general_model.h.
References QString::arg(), and hal::Net::get_id().
grouping()
template<typename T > QString hal::DetailsGeneralCommonInfo< T >::grouping () const inline
Get the grouping's name of the item.
Returns
The name of the grouping.
Definition at line 238 of file details_general_model.h.
References QString::fromStdString(), and hal::Grouping::get_name().
Referenced by hal::DetailsGeneralModel::setContent().
id()
template<typename T > u32 hal::DetailsGeneralCommonInfo< T >::id () const inline
Get the id of the item.
Returns
The item's id.
Definition at line 260 of file details_general_model.h.
Referenced by hal::DetailsGeneralModel::setContent().
name()
template<typename T > QString hal::DetailsGeneralCommonInfo< T >::name () const inline
Get the name of the item.
Returns
The name.
Definition at line 227 of file details_general_model.h.
References QString::isEmpty().
Referenced by hal::DetailsGeneralModel::setContent().
typeName()
template<typename T > QString hal::DetailsGeneralCommonInfo< T >::typeName () const inline
Get the type's name of the item.
Returns
The name of the type.
Definition at line 249 of file details_general_model.h.
References QString::isEmpty().
Referenced by hal::DetailsGeneralModel::setContent().
The documentation for this class was generated from the following file:
/home/runner/work/hal/hal/plugins/gui/include/gui/selection_details_widget/details_general_model.h