HAL: /home/runner/work/hal/hal/plugins/netlist_simulator/test/netlists/bram/generic_tb.cpp File Reference
generic_tb.cpp File Reference
#include "Vbram_netlist.h"
#include "utils/testbench.h"
#include "verilated.h"
#include "verilated_vcd_c.h"
#include <ctype.h>
#include <fstream>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <unistd.h>
Functions
double sc_time_stamp ()
void write_data (uint16_t din)
uint16_t read_data ()
void set_write_addr (uint8_t waddr)
void set_read_addr (uint8_t raddr)
void set_write_en (char write_en)
void set_read_en (char read_en)
void set_rclke (char rclke)
void set_wclke (char wclke)
int main (int argc, char **argv)
Variables
TESTB< Vbram_netlist > * tb
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 104 of file generic_tb.cpp.
References read_data(), set_rclke(), set_read_addr(), set_read_en(), set_wclke(), set_write_addr(), set_write_en(), tb, and write_data().
read_data()
uint16_t read_data ()
Definition at line 41 of file generic_tb.cpp.
References tb.
Referenced by main().
sc_time_stamp()
double sc_time_stamp ()
Definition at line 16 of file generic_tb.cpp.
References tb.
set_rclke()
void set_rclke (char rclke)
Definition at line 95 of file generic_tb.cpp.
References tb.
Referenced by main().
set_read_addr()
void set_read_addr (uint8_t raddr)
Definition at line 75 of file generic_tb.cpp.
References tb.
Referenced by main().
set_read_en()
void set_read_en (char read_en)
Definition at line 91 of file generic_tb.cpp.
References tb.
Referenced by main().
set_wclke()
void set_wclke (char wclke)
Definition at line 99 of file generic_tb.cpp.
References tb.
Referenced by main().
set_write_addr()
void set_write_addr (uint8_t waddr)
Definition at line 63 of file generic_tb.cpp.
References tb.
Referenced by main().
set_write_en()
void set_write_en (char write_en)
Definition at line 87 of file generic_tb.cpp.
References tb.
Referenced by main().
write_data()
void write_data (uint16_t din)
Definition at line 21 of file generic_tb.cpp.
References tb.
Referenced by main().
Variable Documentation
tb
TESTB<Vbram_netlist>* tb
Definition at line 14 of file generic_tb.cpp.
Referenced by main(), read_data(), sc_time_stamp(), set_rclke(), set_read_addr(), set_read_en(), set_wclke(), set_write_addr(), set_write_en(), and write_data().