HAL: Python Bindings
Python Bindings
HAL Core
Typedefs
template<class T >
using hal::RawPtrWrapper = std::unique_ptr< T, py::nodelete >
void hal::data_container_init (py::module &m)
void hal::core_utils_init (py::module &m)
void hal::gate_type_init (py::module &m)
void hal::gate_type_components_init (py::module &m)
void hal::gate_type_lut_init (py::module &m)
void hal::gate_type_sequential_init (py::module &m)
void hal::gate_library_init (py::module &m)
void hal::gate_library_manager_init (py::module &m)
void hal::endpoint_init (py::module &m)
void hal::netlist_init (py::module &m)
void hal::project_manager_init (py::module &m)
void hal::netlist_serializer_init (py::module &m)
void hal::netlist_utils_init (py::module &m)
void hal::base_pin_init (py::module &m)
void hal::gate_pin_init (py::module &m)
void hal::gate_pin_group_init (py::module &m)
void hal::module_pin_init (py::module &m)
void hal::module_pin_group_init (py::module &m)
void hal::gate_init (py::module &m)
void hal::net_init (py::module &m)
void hal::module_init (py::module &m)
void hal::grouping_init (py::module &m)
void hal::netlist_factory_init (py::module &m)
void hal::netlist_writer_manager_init (py::module &m)
void hal::plugin_manager_init (py::module &m)
void hal::plugin_interfaces_init (py::module &m)
void hal::boolean_function_init (py::module &m)
void hal::smt_init (py::module &m)
void hal::boolean_function_net_decorator_init (py::module &m)
void hal::subgraph_netlist_decorator_init (py::module &m)
void hal::boolean_function_decorator_init (py::module &m)
void hal::netlist_modification_decorator_init (py::module &m)
Detailed Description
Typedef Documentation
RawPtrWrapper
template<class T > using hal::RawPtrWrapper = typedef std::unique_ptr<T, py::nodelete>
Wrapper class so that PyBind can work with raw pointers to classes that are managed by HAL.
Definition at line 89 of file python_bindings.h.
Function Documentation
base_pin_init()
void hal::base_pin_init (py::module & m)
Initializes Python bindings for the HAL base pins in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file base_pin.cpp.
Referenced by hal::PYBIND11_PLUGIN().
boolean_function_decorator_init()
void hal::boolean_function_decorator_init (py::module & m)
Initializes Python bindings for the HAL Boolean function decorator in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file boolean_function_decorator.cpp.
References test_plugin::g, hal::BooleanFunctionDecorator::get_boolean_function_from(), and log_error.
Referenced by hal::PYBIND11_PLUGIN().
boolean_function_init()
void hal::boolean_function_init (py::module & m)
Initializes Python bindings for the HAL Boolean function in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file boolean_function.cpp.
References hal::BooleanFunction::Add(), hal::BooleanFunction::NodeType::Add, hal::BooleanFunction::And(), hal::BooleanFunction::NodeType::And, hal::BooleanFunction::clone(), hal::BooleanFunction::Node::clone(), hal::BooleanFunction::Concat(), hal::BooleanFunction::NodeType::Concat, hal::BooleanFunction::Const(), hal::BooleanFunction::Node::constant, hal::BooleanFunction::Node::Constant(), hal::BooleanFunction::NodeType::Constant, hal::BooleanFunction::Eq(), hal::BooleanFunction::NodeType::Eq, hal::BooleanFunction::from_string(), hal::BooleanFunction::Node::get_arity(), hal::BooleanFunction::Node::get_arity_of_type(), hal::BooleanFunction::get_nodes(), hal::BooleanFunction::get_parameters(), hal::BooleanFunction::get_top_level_node(), hal::BooleanFunction::get_variable_names(), hal::BooleanFunction::has_constant_value(), hal::BooleanFunction::Node::has_constant_value(), hal::BooleanFunction::has_index_value(), hal::BooleanFunction::Node::has_index_value(), hal::BooleanFunction::has_variable_name(), hal::BooleanFunction::Node::has_variable_name(), hal::BooleanFunction::Index(), hal::BooleanFunction::Node::index, hal::BooleanFunction::Node::Index(), hal::BooleanFunction::NodeType::Index, hal::BooleanFunction::is(), hal::BooleanFunction::Node::is(), hal::BooleanFunction::Node::is_commutative(), hal::BooleanFunction::is_constant(), hal::BooleanFunction::Node::is_constant(), hal::BooleanFunction::is_empty(), hal::BooleanFunction::is_index(), hal::BooleanFunction::Node::is_index(), hal::BooleanFunction::Node::is_operand(), hal::BooleanFunction::Node::is_operation(), hal::BooleanFunction::is_variable(), hal::BooleanFunction::Node::is_variable(), hal::BooleanFunction::Ite(), hal::BooleanFunction::NodeType::Ite, hal::BooleanFunction::length(), log_error, hal::BooleanFunction::Mul(), hal::BooleanFunction::NodeType::Mul, test::n, hal::BooleanFunction::Not(), hal::BooleanFunction::NodeType::Not, hal::BooleanFunction::Node::Operation(), hal::BooleanFunction::Or(), hal::BooleanFunction::NodeType::Or, hal::BooleanFunction::Sdiv(), hal::BooleanFunction::NodeType::Sdiv, hal::BooleanFunction::Sext(), hal::BooleanFunction::NodeType::Sext, hal::BooleanFunction::simplify(), hal::BooleanFunction::size(), hal::BooleanFunction::Node::size, hal::BooleanFunction::Sle(), hal::BooleanFunction::NodeType::Sle, hal::BooleanFunction::Slice(), hal::BooleanFunction::NodeType::Slice, hal::BooleanFunction::Slt(), hal::BooleanFunction::NodeType::Slt, hal::BooleanFunction::Srem(), hal::BooleanFunction::NodeType::Srem, hal::BooleanFunction::Sub(), hal::BooleanFunction::NodeType::Sub, hal::BooleanFunction::substitute(), hal::BooleanFunction::to_string(), hal::BooleanFunction::to_u64(), hal::BooleanFunction::Node::type, hal::BooleanFunction::Udiv(), hal::BooleanFunction::NodeType::Udiv, hal::BooleanFunction::Ule(), hal::BooleanFunction::NodeType::Ule, hal::BooleanFunction::Ult(), hal::BooleanFunction::NodeType::Ult, hal::BooleanFunction::Urem(), hal::BooleanFunction::NodeType::Urem, hal::BooleanFunction::Var(), hal::BooleanFunction::Node::variable, hal::BooleanFunction::Node::Variable(), hal::BooleanFunction::NodeType::Variable, hal::BooleanFunction::Xor(), hal::BooleanFunction::NodeType::Xor, hal::BooleanFunction::Zext(), and hal::BooleanFunction::NodeType::Zext.
Referenced by hal::PYBIND11_PLUGIN().
boolean_function_net_decorator_init()
void hal::boolean_function_net_decorator_init (py::module & m)
Initializes Python bindings for the HAL Boolean function net decorator in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file boolean_function_net_decorator.cpp.
References hal::BooleanFunctionNetDecorator::get_boolean_variable(), hal::BooleanFunctionNetDecorator::get_boolean_variable_name(), hal::BooleanFunctionNetDecorator::get_net_from(), log_error, and test_multiple::netlist.
Referenced by hal::PYBIND11_PLUGIN().
core_utils_init()
void hal::core_utils_init (py::module & m)
Initializes Python bindings for the HAL core utils in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file core_utils.cpp.
References hal::utils::get_base_directory(), hal::utils::get_binary_directory(), hal::utils::get_default_log_directory(), hal::utils::get_gate_library_directories(), hal::utils::get_library_directory(), hal::utils::get_plugin_directories(), hal::utils::get_share_directory(), hal::utils::get_user_config_directory(), and hal::utils::get_user_share_directory().
Referenced by hal::PYBIND11_PLUGIN().
data_container_init()
void hal::data_container_init (py::module & m)
TODO move into own namespace Initializes Python bindings for the HAL data container in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file data_container.cpp.
References hal::DataContainer::delete_data(), hal::DataContainer::get_data(), hal::DataContainer::get_data_map(), hal::DataContainer::has_data(), and hal::DataContainer::set_data().
Referenced by hal::PYBIND11_PLUGIN().
endpoint_init()
void hal::endpoint_init (py::module & m)
Initializes Python bindings for the HAL endpoint in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file endpoint.cpp.
References hal::Endpoint::get_gate(), hal::Endpoint::get_net(), hal::Endpoint::get_pin(), hal::Endpoint::is_destination_pin(), and hal::Endpoint::is_source_pin().
Referenced by hal::PYBIND11_PLUGIN().
gate_init()
void hal::gate_init (py::module & m)
Initializes Python bindings for the HAL gate in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file gate.cpp.
References hal::Gate::add_boolean_function(), test_plugin::g, hal::Gate::get_boolean_function(), hal::Gate::get_boolean_functions(), hal::Gate::get_fan_in_endpoint(), hal::Gate::get_fan_in_endpoints(), hal::Gate::get_fan_in_net(), hal::Gate::get_fan_in_nets(), hal::Gate::get_fan_out_endpoint(), hal::Gate::get_fan_out_endpoints(), hal::Gate::get_fan_out_net(), hal::Gate::get_fan_out_nets(), hal::Gate::get_grouping(), hal::Gate::get_hash(), hal::Gate::get_id(), hal::Gate::get_location(), hal::Gate::get_location_x(), hal::Gate::get_location_y(), hal::Gate::get_module(), hal::Gate::get_modules(), hal::Gate::get_name(), hal::Gate::get_predecessor(), hal::Gate::get_predecessors(), hal::Gate::get_successor(), hal::Gate::get_successors(), hal::Gate::get_type(), hal::Gate::get_unique_predecessors(), hal::Gate::get_unique_successors(), hal::Gate::has_location(), hal::Gate::is_fan_in_net(), hal::Gate::is_fan_out_net(), hal::Gate::is_gnd_gate(), hal::Gate::is_vcc_gate(), log_error, hal::Gate::mark_gnd_gate(), hal::Gate::mark_vcc_gate(), hal::Gate::set_location(), hal::Gate::set_location_x(), hal::Gate::set_location_y(), hal::Gate::set_name(), hal::Gate::unmark_gnd_gate(), and hal::Gate::unmark_vcc_gate().
Referenced by hal::PYBIND11_PLUGIN().
gate_library_init()
void hal::gate_library_init (py::module & m)
Initializes Python bindings for the HAL gate library in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file gate_library.cpp.
References hal::GateLibrary::add_include(), hal::GateLibrary::contains_gate_type(), hal::GateLibrary::contains_gate_type_by_name(), hal::GateLibrary::get_gate_location_data_category(), hal::GateLibrary::get_gate_type_by_name(), hal::GateLibrary::get_gate_types(), hal::GateLibrary::get_gnd_gate_types(), hal::GateLibrary::get_includes(), hal::GateLibrary::get_name(), hal::GateLibrary::get_vcc_gate_types(), hal::GateLibrary::mark_gnd_gate_type(), hal::GateLibrary::mark_vcc_gate_type(), hal::GateLibrary::set_gate_location_data_category(), and hal::GateLibrary::set_gate_location_data_identifiers().
Referenced by hal::PYBIND11_PLUGIN().
gate_library_manager_init()
void hal::gate_library_manager_init (py::module & m)
Initializes Python bindings for the HAL gate library manager in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file gate_library_manager.cpp.
References hal::gate_library_manager::get_gate_libraries(), hal::gate_library_manager::get_gate_library(), hal::gate_library_manager::get_gate_library_by_name(), hal::gate_library_manager::load(), hal::gate_library_manager::load_all(), and hal::gate_library_manager::save().
Referenced by hal::PYBIND11_PLUGIN().
gate_pin_group_init()
void hal::gate_pin_group_init (py::module & m)
Initializes Python bindings for the HAL gate pin groups in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file gate_pin_group.cpp.
References log_error.
Referenced by hal::PYBIND11_PLUGIN().
gate_pin_init()
void hal::gate_pin_init (py::module & m)
Initializes Python bindings for the HAL gate pins in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file gate_pin.cpp.
Referenced by hal::PYBIND11_PLUGIN().
gate_type_components_init()
void hal::gate_type_components_init (py::module & m)
Initializes Python bindings for the HAL gate type components in a python module.
Parameters
[in] m - the python module
Definition at line 14 of file gate_type_components.cpp.
References hal::GateTypeComponent::ff, hal::RAMPortComponent::get_address_group(), hal::LatchComponent::get_async_reset_function(), hal::FFComponent::get_async_reset_function(), hal::LatchComponent::get_async_set_function(), hal::FFComponent::get_async_set_function(), hal::LatchComponent::get_async_set_reset_behavior(), hal::FFComponent::get_async_set_reset_behavior(), hal::RAMComponent::get_bit_size(), hal::FFComponent::get_clock_function(), hal::RAMPortComponent::get_clock_function(), hal::GateTypeComponent::get_component(), hal::GateTypeComponent::get_components(), hal::RAMPortComponent::get_data_group(), hal::LatchComponent::get_data_in_function(), hal::LatchComponent::get_enable_function(), hal::RAMPortComponent::get_enable_function(), hal::InitComponent::get_init_category(), hal::InitComponent::get_init_identifiers(), hal::StateComponent::get_neg_state_identifier(), hal::FFComponent::get_next_state_function(), hal::StateComponent::get_state_identifier(), hal::GateTypeComponent::get_type(), hal::GateTypeComponent::init, hal::MACComponent::is_class_of(), hal::RAMComponent::is_class_of(), hal::LUTComponent::is_class_of(), hal::InitComponent::is_class_of(), hal::LatchComponent::is_class_of(), hal::StateComponent::is_class_of(), hal::FFComponent::is_class_of(), hal::RAMPortComponent::is_class_of(), hal::LUTComponent::is_init_ascending(), hal::RAMPortComponent::is_write_port(), hal::GateTypeComponent::latch, hal::GateTypeComponent::lut, hal::GateTypeComponent::mac, hal::GateTypeComponent::ram, hal::GateTypeComponent::ram_port, hal::RAMPortComponent::set_address_group(), hal::LatchComponent::set_async_reset_function(), hal::FFComponent::set_async_reset_function(), hal::LatchComponent::set_async_set_function(), hal::FFComponent::set_async_set_function(), hal::LatchComponent::set_async_set_reset_behavior(), hal::FFComponent::set_async_set_reset_behavior(), hal::RAMComponent::set_bit_size(), hal::FFComponent::set_clock_function(), hal::RAMPortComponent::set_clock_function(), hal::RAMPortComponent::set_data_group(), hal::LatchComponent::set_data_in_function(), hal::LatchComponent::set_enable_function(), hal::RAMPortComponent::set_enable_function(), hal::LUTComponent::set_init_ascending(), hal::InitComponent::set_init_category(), hal::InitComponent::set_init_identifiers(), hal::StateComponent::set_neg_state_identifier(), hal::FFComponent::set_next_state_function(), hal::StateComponent::set_state_identifier(), hal::RAMPortComponent::set_write_port(), and hal::GateTypeComponent::state.
Referenced by hal::PYBIND11_PLUGIN().
gate_type_init()
void hal::gate_type_init (py::module & m)
Initializes Python bindings for the HAL gate type in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file gate_type.cpp.
References hal::GateType::add_boolean_function(), hal::GateType::add_boolean_functions(), hal::address, ascending, hal::GateType::assign_property(), hal::c_and, hal::c_aoi, hal::c_buffer, hal::c_carry, hal::c_full_adder, hal::c_half_adder, hal::c_inverter, hal::c_lut, hal::c_mux, hal::c_nand, hal::c_nor, hal::c_oai, hal::c_or, hal::c_xnor, hal::c_xor, hal::carry, hal::clock, hal::combinational, hal::data, direction, hal::dsp, hal::enable, hal::ff, hal::GateType::get_boolean_function(), hal::GateType::get_boolean_functions(), hal::GateType::get_component(), hal::GateType::get_components(), hal::GateType::get_gate_library(), hal::GateType::get_id(), hal::GateType::get_input_pin_names(), hal::GateType::get_input_pins(), hal::GateType::get_name(), hal::GateType::get_output_pin_names(), hal::GateType::get_output_pins(), hal::GateType::get_pin_by_id(), hal::GateType::get_pin_by_name(), hal::GateType::get_pin_group_by_id(), hal::GateType::get_pin_group_by_name(), hal::GateType::get_pin_groups(), hal::GateType::get_pin_names(), hal::GateType::get_pins(), hal::GateType::get_properties(), hal::GateType::get_property_list(), hal::ground, hal::H, hal::GateType::has_component_of_type(), hal::GateType::has_property(), hal::inout, hal::input, hal::internal, hal::io, hal::io_pad, hal::L, hal::latch, log_error, hal::lut, hal::N, name, hal::neg_state, hal::none, hal::oscillator, hal::output, pins, hal::pll, hal::power, hal::ram, hal::reset, hal::scan, hal::select, hal::sequential, hal::set, start_index, hal::state, hal::sum, hal::T, hal::GateType::to_string(), hal::tristate, type, hal::undef, and hal::X.
Referenced by hal::PYBIND11_PLUGIN().
gate_type_lut_init()
void hal::gate_type_lut_init (py::module & m)
Initializes Python bindings for the HAL LUT gate type in a python module.
Parameters
[in] m - the python module
gate_type_sequential_init()
void hal::gate_type_sequential_init (py::module & m)
Initializes Python bindings for the HAL sequential gate type in a python module.
Parameters
[in] m - the python module
grouping_init()
void hal::grouping_init (py::module & m)
Initializes Python bindings for the HAL grouping in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file grouping.cpp.
References hal::Grouping::assign_gate(), hal::Grouping::assign_gate_by_id(), hal::Grouping::assign_module(), hal::Grouping::assign_module_by_id(), hal::Grouping::assign_net(), hal::Grouping::assign_net_by_id(), hal::Grouping::contains_gate(), hal::Grouping::contains_gate_by_id(), hal::Grouping::contains_module(), hal::Grouping::contains_module_by_id(), hal::Grouping::contains_net(), hal::Grouping::contains_net_by_id(), hal::Grouping::get_gate_ids(), hal::Grouping::get_gates(), hal::Grouping::get_id(), hal::Grouping::get_module_ids(), hal::Grouping::get_modules(), hal::Grouping::get_name(), hal::Grouping::get_net_ids(), hal::Grouping::get_netlist(), hal::Grouping::get_nets(), hal::Grouping::remove_gate(), hal::Grouping::remove_gate_by_id(), hal::Grouping::remove_module(), hal::Grouping::remove_net(), hal::Grouping::remove_net_by_id(), and hal::Grouping::set_name().
Referenced by hal::PYBIND11_PLUGIN().
module_init()
void hal::module_init (py::module & m)
Initializes Python bindings for the HAL module in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file module.cpp.
References ascending, hal::Module::assign_gate(), hal::Module::assign_gates(), hal::Module::contains_gate(), hal::Module::contains_module(), hal::Module::contains_net(), direction, hal::Module::get_gate_by_id(), hal::Module::get_gates(), hal::Module::get_grouping(), hal::Module::get_hash(), hal::Module::get_id(), hal::Module::get_input_nets(), hal::Module::get_input_pin_names(), hal::Module::get_input_pins(), hal::Module::get_internal_nets(), hal::Module::get_name(), hal::Module::get_netlist(), hal::Module::get_nets(), hal::Module::get_output_nets(), hal::Module::get_output_pin_names(), hal::Module::get_output_pins(), hal::Module::get_parent_module(), hal::Module::get_parent_modules(), hal::Module::get_pin_by_id(), hal::Module::get_pin_by_name(), hal::Module::get_pin_by_net(), hal::Module::get_pin_group_by_id(), hal::Module::get_pin_group_by_name(), hal::Module::get_pin_groups(), hal::Module::get_pin_names(), hal::Module::get_pins(), hal::Module::get_submodule_depth(), hal::Module::get_submodules(), hal::Module::get_type(), hal::Module::get_unique_pin_group_id(), hal::Module::get_unique_pin_id(), hal::Module::is_input_net(), hal::Module::is_internal_net(), hal::Module::is_output_net(), hal::Module::is_parent_module_of(), hal::Module::is_submodule_of(), hal::Module::is_top_module(), log_error, hal::ShortestPath::module(), name, net, hal::none, pins, hal::Module::remove_gate(), hal::Module::remove_gates(), hal::Module::set_name(), hal::Module::set_parent_module(), hal::Module::set_pin_group_direction(), hal::Module::set_pin_group_name(), hal::Module::set_pin_group_type(), hal::Module::set_pin_name(), hal::Module::set_pin_type(), hal::Module::set_type(), start_index, type, and hal::Module::update_nets().
Referenced by hal::PYBIND11_PLUGIN().
module_pin_group_init()
void hal::module_pin_group_init (py::module & m)
Initializes Python bindings for the HAL module pin groups in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file module_pin_group.cpp.
References log_error.
Referenced by hal::PYBIND11_PLUGIN().
module_pin_init()
void hal::module_pin_init (py::module & m)
Initializes Python bindings for the HAL module pins in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file module_pin.cpp.
References hal::ModulePin::get_net().
Referenced by hal::PYBIND11_PLUGIN().
net_init()
void hal::net_init (py::module & m)
Initializes Python bindings for the HAL net in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file net.cpp.
References hal::Net::add_destination(), hal::Net::add_source(), hal::Net::get_destinations(), hal::Net::get_grouping(), hal::Net::get_hash(), hal::Net::get_id(), hal::Net::get_name(), hal::Net::get_netlist(), hal::Net::get_num_of_destinations(), hal::Net::get_num_of_sources(), hal::Net::get_sources(), hal::Net::is_a_destination(), hal::Net::is_a_source(), hal::Net::is_global_input_net(), hal::Net::is_global_output_net(), hal::Net::is_gnd_net(), hal::Net::is_unrouted(), hal::Net::is_vcc_net(), hal::Net::mark_global_input_net(), hal::Net::mark_global_output_net(), test::n, net, hal::Net::remove_destination(), hal::Net::remove_source(), hal::Net::set_name(), hal::Net::unmark_global_input_net(), and hal::Net::unmark_global_output_net().
Referenced by hal::PYBIND11_PLUGIN().
netlist_factory_init()
void hal::netlist_factory_init (py::module & m)
Initializes Python bindings for the HAL netlist factory in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file netlist_factory.cpp.
References hal::netlist_factory::create_netlist(), hal::netlist_factory::load_hal_project(), hal::netlist_factory::load_netlist(), and hal::netlist_factory::load_netlists().
Referenced by hal::PYBIND11_PLUGIN().
netlist_init()
void hal::netlist_init (py::module & m)
Initializes Python bindings for the HAL netlist in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file netlist.cpp.
References hal::Netlist::clear_caches(), hal::Netlist::copy(), hal::Netlist::create_gate(), hal::Netlist::create_grouping(), hal::Netlist::create_module(), hal::Netlist::create_net(), hal::Netlist::delete_gate(), hal::Netlist::delete_grouping(), hal::Netlist::delete_module(), hal::Netlist::delete_net(), hal::Netlist::enable_automatic_net_checks(), hal::Netlist::get_design_name(), hal::Netlist::get_device_name(), hal::Netlist::get_free_gate_ids(), hal::Netlist::get_free_grouping_ids(), hal::Netlist::get_free_module_ids(), hal::Netlist::get_free_net_ids(), hal::Netlist::get_gate_by_id(), hal::Netlist::get_gate_library(), hal::Netlist::get_gates(), hal::Netlist::get_global_input_nets(), hal::Netlist::get_global_output_nets(), hal::Netlist::get_gnd_gates(), hal::Netlist::get_grouping_by_id(), hal::Netlist::get_groupings(), hal::Netlist::get_id(), hal::Netlist::get_input_filename(), hal::Netlist::get_module_by_id(), hal::Netlist::get_modules(), hal::Netlist::get_net_by_id(), hal::Netlist::get_nets(), hal::Netlist::get_next_gate_id(), hal::Netlist::get_next_grouping_id(), hal::Netlist::get_next_module_id(), hal::Netlist::get_next_net_id(), hal::Netlist::get_top_module(), hal::Netlist::get_unique_gate_id(), hal::Netlist::get_unique_grouping_id(), hal::Netlist::get_unique_module_id(), hal::Netlist::get_unique_net_id(), hal::Netlist::get_used_gate_ids(), hal::Netlist::get_used_grouping_ids(), hal::Netlist::get_used_module_ids(), hal::Netlist::get_used_net_ids(), hal::Netlist::get_vcc_gates(), hal::Netlist::is_gate_in_netlist(), hal::Netlist::is_global_input_net(), hal::Netlist::is_global_output_net(), hal::Netlist::is_gnd_gate(), hal::Netlist::is_grouping_in_netlist(), hal::Netlist::is_module_in_netlist(), hal::Netlist::is_net_in_netlist(), hal::Netlist::is_vcc_gate(), hal::Netlist::load_gate_locations_from_data(), hal::Netlist::mark_global_input_net(), hal::Netlist::mark_global_output_net(), hal::Netlist::mark_gnd_gate(), hal::Netlist::mark_vcc_gate(), hal::Netlist::set_design_name(), hal::Netlist::set_device_name(), hal::Netlist::set_free_gate_ids(), hal::Netlist::set_free_grouping_ids(), hal::Netlist::set_free_module_ids(), hal::Netlist::set_free_net_ids(), hal::Netlist::set_id(), hal::Netlist::set_input_filename(), hal::Netlist::set_next_gate_id(), hal::Netlist::set_next_grouping_id(), hal::Netlist::set_next_module_id(), hal::Netlist::set_next_net_id(), hal::Netlist::set_used_gate_ids(), hal::Netlist::set_used_grouping_ids(), hal::Netlist::set_used_module_ids(), hal::Netlist::set_used_net_ids(), hal::Netlist::unmark_global_input_net(), hal::Netlist::unmark_global_output_net(), hal::Netlist::unmark_gnd_gate(), and hal::Netlist::unmark_vcc_gate().
Referenced by hal::PYBIND11_PLUGIN().
netlist_modification_decorator_init()
void hal::netlist_modification_decorator_init (py::module & m)
Initializes Python bindings for the HAL netlist modification decorator in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file netlist_modification_decorator.cpp.
References log_error.
Referenced by hal::PYBIND11_PLUGIN().
netlist_serializer_init()
void hal::netlist_serializer_init (py::module & m)
Initializes Python bindings for the HAL netlist serializer in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file netlist_serializer.cpp.
References hal::netlist_serializer::deserialize_from_file(), and hal::netlist_serializer::serialize_to_file().
Referenced by hal::PYBIND11_PLUGIN().
netlist_utils_init()
void hal::netlist_utils_init (py::module & m)
Initializes Python bindings for the HAL netlist utils in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file netlist_utils.cpp.
References hal::netlist_utils::copy_netlist(), hal::netlist_utils::get_common_inputs(), hal::netlist_utils::get_complex_gate_chain(), hal::netlist_utils::get_ff_dependency_matrix(), hal::netlist_utils::get_gate_chain(), hal::netlist_utils::get_nets_at_pins(), hal::netlist_utils::get_next_gates(), hal::netlist_utils::get_next_sequential_gates(), hal::netlist_utils::get_path(), hal::netlist_utils::get_shortest_path(), hal::netlist_utils::get_subgraph_function(), log_error, net, test_multiple::netlist, hal::netlist_utils::remove_buffers(), hal::netlist_utils::remove_unused_lut_endpoints(), and hal::netlist_utils::replace_gate().
Referenced by hal::PYBIND11_PLUGIN().
netlist_writer_manager_init()
void hal::netlist_writer_manager_init (py::module & m)
Initializes Python bindings for the HAL netlist writer manager in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file netlist_writer_manager.cpp.
References hal::netlist_writer_manager::write().
Referenced by hal::PYBIND11_PLUGIN().
plugin_interfaces_init()
void hal::plugin_interfaces_init (py::module & m)
Initializes Python bindings for the HAL plugin interfaces in a python module.
Parameters
[in] m - the python module
Definition at line 28 of file plugin_interfaces.cpp.
References hal::BasePluginInterface::get_name(), and hal::BasePluginInterface::get_version().
Referenced by hal::PYBIND11_PLUGIN().
plugin_manager_init()
void hal::plugin_manager_init (py::module & m)
Initializes Python bindings for the HAL plugin manager in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file plugin_manager.cpp.
References hal::plugin_manager::get_plugin_names(), hal::plugin_manager::load(), hal::plugin_manager::load_all_plugins(), hal::plugin_manager::unload(), and hal::plugin_manager::unload_all_plugins().
Referenced by hal::PYBIND11_PLUGIN().
project_manager_init()
void hal::project_manager_init (py::module & m)
Initializes Python bindings for the HAL project manager in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file project_manager.cpp.
References hal::ProjectManager::create_project_directory(), hal::ProjectManager::get_filename(), hal::ProjectManager::get_netlist_filename(), hal::ProjectManager::get_project_status(), hal::ProjectManager::instance(), hal::ProjectManager::open_project(), hal::ProjectManager::remove_project_directory(), hal::ProjectManager::serialize_project(), hal::ProjectManager::set_gate_library_path(), hal::ProjectManager::set_project_directory(), and hal::ProjectManager::set_project_status().
Referenced by hal::PYBIND11_PLUGIN().
smt_init()
void hal::smt_init (py::module & m)
Initializes Python bindings for the HAL SMT solver system in a python module.
Parameters
[in] m - the python module
Definition at line 5 of file smt.cpp.
References hal::SMT::Boolector, hal::SMT::Constraint::constraint, hal::SMT::SymbolicExecution::evaluate(), hal::SMT::QueryConfig::generate_model, hal::SMT::SymbolicState::get(), hal::SMT::Solver::get_constraints(), hal::SMT::Solver::has_local_solver_for(), hal::SMT::SolverResult::is(), hal::SMT::Constraint::is_assignment(), hal::SMT::SolverResult::is_sat(), hal::SMT::SolverResult::is_unknown(), hal::SMT::SolverResult::is_unsat(), log_error, hal::SMT::Model::model, hal::SMT::SolverResult::model, hal::SMT::Model::parse(), hal::SMT::Solver::query_local(), hal::SMT::Solver::query_remote(), hal::SMT::Sat, hal::SMT::SolverResult::Sat(), hal::SMT::SymbolicState::set(), hal::SMT::QueryConfig::solver, hal::SMT::SymbolicExecution::state, hal::SMT::QueryConfig::timeout_in_seconds, hal::SMT::SolverResult::type, hal::SMT::Unknown, hal::SMT::SolverResult::Unknown(), hal::SMT::UnSat, hal::SMT::SolverResult::UnSat(), hal::SMT::QueryConfig::with_call(), hal::SMT::Solver::with_constraint(), hal::SMT::Solver::with_constraints(), hal::SMT::QueryConfig::with_local_solver(), hal::SMT::QueryConfig::with_model_generation(), hal::SMT::QueryConfig::with_remote_solver(), hal::SMT::QueryConfig::with_solver(), hal::SMT::QueryConfig::with_timeout(), hal::SMT::QueryConfig::without_model_generation(), and hal::SMT::Z3.
Referenced by hal::PYBIND11_PLUGIN().
subgraph_netlist_decorator_init()
void hal::subgraph_netlist_decorator_init (py::module & m)
Initializes Python bindings for the HAL subgraph netlist decorator in a python module.
Parameters
[in] m - the python module
Definition at line 7 of file subgraph_netlist_decorator.cpp.
References log_error.
Referenced by hal::PYBIND11_PLUGIN().