HAL: HAL Gui
HAL Gui
The Gui is a huge plugin that provides a graphical user interface to load and work with Netlists. If compiled it can be started using the '-g'/'–gui' flag. To learn more about the GUI and its structure make sure to check out our GitHub Wiki!
Modules
Graph Widget
Contains all classes that are relevant for the GraphWidget and the management of GraphContexts.
Python
Contains everything that can be associated with the python usage within the GUI.
Docking System
Contains all classes that are relevant for the ContentWidget's docking system.
Logging System
Contains everything that can be associated with the LoggerWidget.
Settings System
Contains all classes that belong to the settings system.
User Actions
Contains the classes for all available UserActions and the UserAction management system.
File Management
Contains the classes that are responsible for working with files.
Utility Widgets
Contains classes related to the ContextManagerWidget, ModuleWidget, GroupingsWidget and the SelectionDetailsWidget.
Unused
Classes and systems that are no longer used or that are not (yet) available in a current master build.
Namespaces
hal::gui_utility
hal::style
Classes
class hal::Action
Provides an interface for triggerable functionality that can be inserted into widgets and also connected to shortcuts.
class hal::BaseTreeModel
The BaseTreeModel implements generic standard functions of a tree model.
class hal::CommentEntry
The CommentEntry class encapsulated information related to a comment.
class hal::ContentLayoutArea
Manages the layout of all ContentWidgets.
class hal::ContentManager
Manages all ContentWidgets.
class hal::ContentWidget
Abstract class for Widgets within HAL's ContentArea.
class hal::ExportRegisteredFormat
Utility class to export (save) different hal files.
class hal::LabeledFrame
A QFrame with a label.
class hal::GatelibraryManagementDialog
A dialog for the management of gate libraries.
class hal::GatelibraryTableModel
A model to display loaded gatelibraries.
class hal::NetLayoutJunctionWireIntersection
class hal::GuiApi
Interface to interact with the gui itself.
class hal::Node
The Node class object represents a module or a gate.
class hal::SpecialLogContentManager
Logs the python editor and gui screenshots.
class hal::InputDialog
Generic input dialog for user input.
class hal::LabelButton
Adds button functionality to a QLabel.
class hal::AboutDialog
A dialog that displays the Qt version and our open source license.
class hal::MainWindow
The top level widget.
class hal::ModuleItem
An item in the ModuleModel.
class hal::ModuleModel
Represents the netlist module's hierarchy.
class hal::ModuleProxyModel
Enables filtering in the ModuleModel.
class hal::NetlistRelay
Connects the hal-core events to the gui.
class hal::Overlay
The Overlay overlays its parent.
class hal::WidgetOverlay
Container for a QWidget that overlays another one.
class hal::PluginRelay
Forwards plugin related events from the core to the gui.
class hal::Searchbar
A QFrame with a QLineEdit that can be used to input a substring to search for.
class hal::GatePinsTreeModel
A model to display the pins of a gate.
class hal::GroupingsOfItemModel
A TableModel to store all Groupings that contain a specified Gate, Net or Module.
class hal::EndpointTableModel
A model to display endpoint data.
class hal::ModuleTableModel
A model to display module data.
class hal::SelectionRelay
Stores and manages the gui's selection state.
class hal::Splitter
A QSplitter that can be checked if it is unused or not.
class hal::SvgIconEngine
Creates Icons from svg data.
class hal::Toolbar
Toolbar for all ContentFrames and ContentWidgets.
class hal::ActionAddBooleanFunction
Either adds a new function or changes an exisiting function of a given gate.
class hal::EmptyStringValidator
Checks if a given string is not empty.
class hal::StackedValidator
Combines different validators into one.
class hal::UniqueStringValidator
Checks if a given string is unique compared to other given strings.
class hal::Validator
Base class for any string validator.
class hal::GetInTouchItem
One item in the welcome screen's GetInTouch section.
class hal::GetInTouchWidget
The welcome screen's GetInTouch section.
class hal::OpenFileWidget
The welcome screen's OpenFile section.
class hal::RecentFileItem
One item in the welcome screen's RecentFiles section.
class hal::RecentFilesWidget
The welcome screen's RecentFiles section.
class hal::WelcomeScreen
Hal's welcome screen.
class hal::Widget
A QWidget customized for hal.
Enumerations
enum hal::ItemType { hal::ItemType::None, hal::ItemType::Module, hal::ItemType::Gate, hal::ItemType::Net }
The ItemType enum provides the enum type to classify graphic items into Modules, Gates or Nets. The ItemType None indicates that the ItemType has not been initialized or that a function could not determine the ItemType.
Functions
void hal::gui_utility::ensureOnScreen (QWidget *w)
(Fully) displays the widget by moving it.
Q_DECLARE_METATYPE (u32) namespace hal
Detailed Description
The Gui is a huge plugin that provides a graphical user interface to load and work with Netlists. If compiled it can be started using the '-g'/'–gui' flag. To learn more about the GUI and its structure make sure to check out our GitHub Wiki!
Enumeration Type Documentation
ItemType
enum hal::ItemType strong
The ItemType enum provides the enum type to classify graphic items into Modules, Gates or Nets. The ItemType None indicates that the ItemType has not been initialized or that a function could not determine the ItemType.
Enumerator
None
Module
Gate
Net
Definition at line 42 of file gui_def.h.
Function Documentation
ensureOnScreen()
void hal::gui_utility::ensureOnScreen (QWidget * w)
(Fully) displays the widget by moving it.
Tries to display the given widget completely on the screen (e.g. when its partially out of bounds). It checks the geometry (size) of the screen and the widget and moves the widget accordingly, prioritizing the widget's top side and left side to be seen.
Parameters
w- The widget to be (fully) displayed on the screen.
Definition at line 11 of file geometry.cpp.
References QDesktopWidget::availableGeometry(), QApplication::desktop(), QWidget::geometry, and QWidget::move().
Q_DECLARE_METATYPE()
Q_DECLARE_METATYPE (u32)
PluginGui is a huge plugin that provides a graphical user interface to load and work with netlists. If compiled it can be started using the '-g'/'–gui' flag.
Returns the plugin name: 'hal_gui'
Returns
the plugin name
Returns the current version of the plugin.
Returns
the current version number of the plugin
Adds all gui related channels to the LogManager.
Initializes the command line options for this plugin: '-g'/'–gui' to start the gui
Returns
the available command line options
Executes the gui plugin.
Parameters
args - The given program arguments.
Returns
True on success, False otherwise.
Call to block layouter.
Can be enabled multiple times, but each enable must be match by disable to remove the lock.
Parameters
[in] enable Enable lock on true, disable on false
Definition at line 32 of file plugin_gui.h.
References control::args, and hal::netlist_parser_manager::get_cli_options().