HAL: hal::dataflow::state_to_module Namespace Reference
hal::dataflow::state_to_module Namespace Reference
Functions
bool create_modules (Netlist *nl, const std::shared_ptr< const Grouping > &state)
std::vector< std::vector< Gate * > > create_sets (Netlist *nl, const std::shared_ptr< const Grouping > &state)
Function Documentation
create_modules()
bool hal::dataflow::state_to_module::create_modules (Netlist * nl, const std::shared_ptr< const Grouping > & state)
Definition at line 16 of file state_to_module.cpp.
References hal::Netlist::create_module(), hal::Netlist::delete_module(), hal::Netlist::get_gate_by_id(), hal::Gate::get_module(), hal::Netlist::get_modules(), hal::Netlist::get_top_module(), log_info, hal::state, and nlohmann::to_string().
Referenced by hal::plugin_dataflow::execute(), and hal::plugin_dataflow::set_parameter().
create_sets()
std::vector< std::vector< Gate * > > hal::dataflow::state_to_module::create_sets (Netlist * nl, const std::shared_ptr< const Grouping > & state)
Definition at line 63 of file state_to_module.cpp.
References hal::Netlist::get_gate_by_id(), and hal::state.
Referenced by hal::plugin_dataflow::execute().