HAL: hal::simulation_utils Namespace Reference
hal::simulation_utils Namespace Reference
Functions
BooleanFunction::Value toggle (BooleanFunction::Value v)
BooleanFunction::Value process_clear_preset_behavior (AsyncSetResetBehavior behavior, BooleanFunction::Value previous_output)
std::vector< BooleanFunction::Value > int_to_values (u32 integer, u32 len)
u32 values_to_int (const std::vector< BooleanFunction::Value > &values)
u32 get_int_bus_value (const std::unordered_map< std::string, BooleanFunction::Value > &signal_values, const std::vector< std::string > &ordered_pins)
Function Documentation
get_int_bus_value()
u32 hal::simulation_utils::get_int_bus_value (const std::unordered_map< std::string, BooleanFunction::Value > & signal_values, const std::vector< std::string > & ordered_pins)
Definition at line 82 of file simulation_utils.cpp.
References values_to_int().
int_to_values()
std::vector< BooleanFunction::Value > hal::simulation_utils::int_to_values (u32 integer, u32 len)
Definition at line 42 of file simulation_utils.cpp.
process_clear_preset_behavior()
BooleanFunction::Value hal::simulation_utils::process_clear_preset_behavior (AsyncSetResetBehavior behavior, BooleanFunction::Value previous_output)
Definition at line 16 of file simulation_utils.cpp.
References hal::enum_to_string(), hal::H, hal::L, log_error, hal::N, hal::T, toggle(), and hal::X.
toggle()
BooleanFunction::Value hal::simulation_utils::toggle (BooleanFunction::Value v)
Definition at line 7 of file simulation_utils.cpp.
Referenced by hal::NetlistSimulator::load_initial_values(), hal::NetlistSimulator::load_initial_values_from_netlist(), and process_clear_preset_behavior().
values_to_int()
u32 hal::simulation_utils::values_to_int (const std::vector< BooleanFunction::Value > & values)
Definition at line 58 of file simulation_utils.cpp.
Referenced by get_int_bus_value().