HAL: utils Namespace Reference
utils Namespace Reference
Functions
def round_float (value)
def round_float_1 (value)
def expect (condition, error_message)
def get_gate_library (design, synthesizer)
def execute_hal (synthesizer, design, rebuild_debug, debug, sizes)
Function Documentation
execute_hal()
def utils.execute_hal (synthesizer, design, rebuild_debug, debug, sizes)
Definition at line 25 of file utils.py.
References expect(), and get_gate_library().
expect()
def utils.expect (condition, error_message)
Definition at line 14 of file utils.py.
Referenced by execute_hal().
get_gate_library()
def utils.get_gate_library (design, synthesizer)
Definition at line 19 of file utils.py.
Referenced by execute_hal().
round_float()
def utils.round_float (value)
Definition at line 4 of file utils.py.
round_float_1()
def utils.round_float_1 (value)
Definition at line 11 of file utils.py.