HAL: hal Namespace Reference
hal Namespace Reference
HAL Core » Netlist » Event System
Namespaces
BooleanFunctionParser
core_strings
dataflow
event_log
gate_library_manager
gate_library_parser_manager
gate_library_writer_manager
graph_widget_constants
GraphicsFactory
Contains utility factory functions.
gui_utility
JsonConverter
netlist_factory
netlist_parser_manager
netlist_serializer
netlist_utils
netlist_writer_manager
plugin_manager
result_constructor_type
ShortestPath
Simplification
SMT
style
utils
Classes
class AboutDialog
A dialog that displays the Qt version and our open source license.
class AbstractBusyIndicator
class Action
Provides an interface for triggerable functionality that can be inserted into widgets and also connected to shortcuts.
class ActionAddBooleanFunction
Either adds a new function or changes an exisiting function of a given gate.
class ActionAddBooleanFunctionFactory
The ActionAddBooleanFunctionFactory class.
class ActionAddItemsToObject
Adds an item to a module or grouping.
class ActionAddItemsToObjectFactory
UserActionFactory for ActionAddItemsToObject.
class ActionCreateObject
Create a new item.
class ActionCreateObjectFactory
UserActionFactory for ActionCreateObject.
class ActionDeleteObject
Deletes an object.
class ActionDeleteObjectFactory
UserActionFactory for ActionDeleteObject.
class ActionFoldModule
Folds a module.
class ActionFoldModuleFactory
UserActionFactory for ActionFoldModule.
class ActionMoveNode
Moves a node.
class ActionMoveNodeFactory
UserActionFactory for ActionMoveNode.
class ActionOpenNetlistFile
Loads a netlist.
class ActionOpenNetlistFileFactory
UserActionFactory for ActionOpenNetlistFile.
class ActionRemoveItemsFromObject
Removes an item from a Module or Grouping.
class ActionRemoveItemsFromObjectFactory
UserActionFactory for ActionRemoveItemsFromObject.
class ActionRenameObject
Renames an item.
class ActionRenameObjectFactory
UserActionFactory for ActionRenameObject.
class ActionReorderObject
Reorders an item within a container.
class ActionReorderObjectFactory
UserActionFactory for ActionReorderObject.
class ActionSetObjectColor
Recolors the object.
class ActionSetObjectColorFactory
UserActionFactory for ActionSetObjectColor.
class ActionSetObjectData
class ActionSetObjectDataFactory
The ActionSetObjectDataFactory class.
class ActionSetObjectType
Assigns a new type to a module.
class ActionSetObjectTypeFactory
UserActionFactory for ActionSetObjectType.
class ActionSetSelectionFocus
Set the selection and focus.
class ActionSetSelectionFocusFactory
UserActionFactory for ActionSetSelectionFocus.
class ActionUnfoldModule
Unfolds a module.
class ActionUnfoldModuleFactory
UserActionFactory for ActionUnfoldModule.
class AddToModuleReceiver
class ArrowSeparatedNet
Used to display all nets which destinations are not in the current view.
class AssignedKeybindMap
A map to keep track of the assigned keybinds.
class BasePin
class BasePluginInterface
class BaseTreeModel
The BaseTreeModel implements generic standard functions of a tree model.
class BooleanFunction
class BooleanFunctionDecorator
class BooleanFunctionEntry
A BooleanFunctionTableEntry that represents a boolean function.
class BooleanFunctionNetDecorator
class BooleanFunctionTable
A table view that shows BooleanFunctions and clear-preset behaviors.
class BooleanFunctionTableEntry
An entry in the boolean function table model.
class BooleanFunctionTableModel
A model that holds BooleanFunctions and clear-preset behaviors.
class BooleanInfluencePlugin
class BusyAnimation
class BusyIndicator
class CallbackHook
class CallbackHook< R(ArgTypes...)>
struct ChannelEntry
The ChannelEntry struct is used by the ChannelItem class to store a single entry.
class ChannelItem
This class represents a channel in the channel model. It primarily holds the channel name and its entries.
class ChannelModel
Table model for log channels.
class ChannelSelector
A combobox for selecting a logger channel.
class CircleSeparatedNet
Used to display all nets which destinations are not in the current view.
class CLIPluginInterface
class CodeEditor
A plain text edit widget that is intended for editing code.
class CodeEditorMinimap
A minimap that supports an easier navigation in larger files.
class CodeEditorScrollbar
Represents the scrollbar of the CodeEditor.
class ColorSelection
class ComboboxDialog
class CommentColorPicker
class CommentDialog
class CommentEntry
The CommentEntry class encapsulated information related to a comment.
class CommentItem
class CommentManager
class CommentSpeechBubble
class CommentWidget
class CommonSuccessorPredecessor
class CommonSuccessorPredecessorGateQueue
class ContentAnchor
An abstract class that provides the interface for specific anchors (see SplitterAnchor or TabWidget).
class ContentDragRelay
This relay provides the timing information when a DockButton is dragged. It is implemented as a singleton pattern.
class ContentFactory
class ContentFrame
Wraps the ContentWidget class.
class ContentLayoutArea
Manages the layout of all ContentWidgets.
class ContentManager
Manages all ContentWidgets.
class ContentWidget
Abstract class for Widgets within HAL's ContentArea.
class ContextManagerWidget
Provides the user with an interface to manage GraphContexts.
class ContextTableModel
Base model for the ContextManagerWidget to manage GraphContexts.
class ContextTableProxyModel
A proxy model to filter the ContextTableModel by a given string.
class CoordinateFromData
Utility class that extracts (if possible) x and y coordinates contained in the netlist.
class CoordinateFromDataMap
Utility class that stores the nodes that contained existing x and y coordinates.
class CPBehaviorEntry
A BooleanFunctionTableEntry that represents a clear-preset behavior.
class DataContainer
class DataTableModel
A model to display the data of a DataContainer.
class DataTableWidget
A widget to display the data of a DataContainer (Module, Gate or Net)
class DetailsFrameWidget
class DetailsTableUtilities
Helper class consisting of usefull details-related functions.
class DetailsTabWidget
class DockBar
Contains and handles DockButtons.
class DockButton
A button of in the DockerBar.
class DockMimeData
QMineData to store and transfer information while dragging a DockButton.
class EmptyStringValidator
Checks if a given string is not empty.
class Endpoint
class EndpointTableModel
A model to display endpoint data.
struct EnumStrings
class Error
class EventHandler
class ExpandingListButton
One button of the ExpandingListWidget.
class ExpandingListGroup
A helper class to group related list items (buttons).
class ExpandingListItem
Wrapper for ExpandingListButtons.
class ExpandingListWidget
A selection menu with a hierarchic structure.
class ExportProjectDialog
class ExportRegisteredFormat
Utility class to export (save) different hal files.
class ExternalContent
class FFComponent
class FFComponentEntry
A entry type that represents properties (functions and behaviors) of an FFCompont.
class FileManager
Stores information about the currently opened netlist.
class FileModifiedBar
A dialog in form of a bar to let the user decide how to handle file changes outside of HAL.
class FileSelectWidget
class FileStatusManager
Holds information about the state (e.g. saved/unsaved) of all laded files (i.e. .hal/.python files).
class Gate
class GateDetailsTabWidget
The DetailsTabWidget that is responsible for showing Gate details.
class GateDialog
The GateDialog class opens a popup window for module selection.
class GateEvent
class GateInfoTable
class GateLibrary
class GatelibraryManagementDialog
A dialog for the management of gate libraries.
class GateLibraryParser
class GatelibraryProxyModel
Helper model to make filtering available.
class GatelibraryTableModel
A model to display loaded gatelibraries.
class GatelibraryTableView
class GateLibraryWriter
class GatePin
class GatePinsTreeModel
A model to display the pins of a gate.
class GatePinTree
A widget to display the pins of a given gate.
class GateSelectEntry
The GateSelectEntry class comprises a single entry of the module selection table.
class GateSelectHistory
The GateSelectHistory class singleton comprises a list of user selected modules.
class GateSelectModel
The GateSelectModel class is the source model for module selection.
class GateSelectPicker
The GateSelectPicker class instance gets spawned to pick module from graph.
class GateSelectProxy
The GateSelectProxy class allows sorting and filtering of module tables.
class GateSelectReceiver
class GateSelectView
The GateSelectView class is the table widget for module selection.
class GateType
class GateTypeComponent
class GeneralTableWidget
class GetInTouchItem
One item in the welcome screen's GetInTouch section.
class GetInTouchWidget
The welcome screen's GetInTouch section.
class GraphAlgorithmPlugin
class GraphContext
Logical container for modules, gates, and nets.
class GraphContextManager
User interface to manage all GraphContexts.
class GraphContextSerializer
class GraphGraphicsView
A view to display the rendered graph (needs a GraphicsScene).
class GraphGraphicsViewNeighborSelector
class GraphicsGate
Abstract base class for gates.
class GraphicsItem
Superclass for all graphic items used ins the GraphicsScene. It contains information about the underlying objects that are represented, i.e. the type and the id.
class GraphicsModule
Abstract base class for modules.
class GraphicsNet
The basic net class all other nets inherit from.
class GraphicsNode
Abstract base class for nodes (e.g. gates, modules)
class GraphicsQssAdapter
Connects the stylesheet properties with the code.
class GraphicsScene
Container for a GraphGraphicsView containing gates, nets, and modules.
class GraphLayouter
Base class for all specific layouters.
class GraphNavigationTableWidget
A widget used to select destinations when traversing through the graph.
class GraphNavigationTreeWidget
class GraphNavigationWidget
class GraphShader
Base class to store and update visual information about the graph.
class GraphTabWidget
A ContentWidget that holds all GraphWidget objects (GraphView) as tabs of a QTabWidget.
class GraphWidget
Wraps a GraphContext and a GraphGraphicsView.
class Grouping
class GroupingColorDelegate
Displays a colored box for the GroupingManagerWidget.
class GroupingColorSerializer
class GroupingDialog
class GroupingEvent
class GroupingManagerWidget
User interface for Groupings.
class GroupingProxyModel
Helper model to make filtering available.
class GroupingSerializer
class GroupingsOfItemModel
A TableModel to store all Groupings that contain a specified Gate, Net or Module.
class GroupingsOfItemWidget
A TableView to display all groupings that contain a specified Gate, Net or Module.
class GroupingTableEntry
An entry within a GroupingTableModel.
class GroupingTableHistory
class GroupingTableModel
Table that holds information about all groupings.
class GroupingTableView
class GuiApi
Interface to interact with the gui itself.
class GUIPluginInterface
class HexadecimalValidator
class HGLParser
class HGLParserPlugin
class HGLParserTest
class HGLWriter
class HGLWriterPlugin
class HGLWriterTest
class ImportNetlistDialog
class ImportProjectDialog
class InitComponent
class InputDialog
Generic input dialog for user input.
class JsonWriteArray
class JsonWriteComplex
class JsonWriteData
class JsonWriteDocument
class JsonWriteObject
class KeybindEdit
A widget to set or configure key shortcuts.
class KeyValueTable
class LabelButton
Adds button functionality to a QLabel.
class LabeledFrame
A QFrame with a label.
class LabeledSeparatedNet
Nets whose output and input can be labeled (e.g. from GND/VCC)
class LatchComponent
class LatchComponentEntry
An entry type that represents properties (functions or behaviors) of a LatchComponent.
class LayoutLocker
class LayoutLockerManager
class LibertyParser
class LibertyParserPlugin
class LibertyParserTest
class LineNumberArea
Shows line numbers next to a CodeEditor.
class log_gui_sink
class LoggerMarshall
Appends log messages to the corresponding LoggerWidget.
class LoggerQssAdapter
Connects the stylesheet properties to the log designs.
struct LoggerSettings
class LoggerWidget
Displays the logs in the gui.
class LogManager
class LUTComponent
class LUTTableModel
A model for truth-tables.
class LUTTableWidget
A view for truth-tables (based on the LUTTableModel)
class MACComponent
class MainSettingsList
List that contains all SettingsWidgets.
class MainSettingsWidget
The top-level widget that displays all settings.
class MainWindow
The top level widget.
class MinimapScrollbar
The scrollbar of the CodeEditorMinimap.
class Module
class ModuleColorSerializer
class ModuleDetailsTabWidget
The DetailsTabWidget that is responsible for showing Module details.
class ModuleDialog
The ModuleDialog class opens a popup window for module selection.
class ModuleElementsTree
A widget to display the specific (direct submodules, gates) items of a given module.
class ModuleEvent
class ModuleInfoTable
class ModuleItem
An item in the ModuleModel.
class ModuleModel
Represents the netlist module's hierarchy.
class ModulePin
class ModulePinsTree
A widget to display the ports of a given module.
class ModulePinsTreeModel
A model to represent the ports of a module.
class ModuleProxyModel
Enables filtering in the ModuleModel.
class ModuleSelectEntry
The ModuleSelectEntry class comprises a single entry of the module selection table.
class ModuleSelectExclude
The ModuleSelectExclude class is used to determine which modules can't be selected.
class ModuleSelectHistory
The ModuleSelectHistory class singleton comprises a list of user selected modules.
class ModuleSelectModel
The ModuleSelectModel class is the source model for module selection.
class ModuleSelectPicker
The ModuleSelectPicker class instance gets spawned to pick module from graph.
class ModuleSelectProxy
The ModuleSelectProxy class allows sorting and filtering of module tables.
class ModuleSelectReceiver
class ModuleSelectView
The ModuleSelectView class is the table widget for module selection.
class ModuleShader
Specifically stores/updates visual information about a module and its items.
class ModuleTableModel
A model to display module data.
class ModuleTreeModel
class ModuleTreeView
Wraps the QTreeView used for the ModuleWidget.
class ModuleWidget
Shows the modules of the netlist hierarchical in a tree view.
class Net
class NetDetailsTabWidget
The DetailsTabWidget that is responsible for showing Module details.
class NetEndpointTable
class NetEvent
class NetInfoTable
class NetLayoutConnection
class NetLayoutConnectionFactory
class NetLayoutConnectionMetric
class NetLayoutDirection
class NetLayoutJunction
class NetLayoutJunctionEntries
class NetLayoutJunctionHash
class NetLayoutJunctionMultiPin
class NetLayoutJunctionNet
class NetLayoutJunctionOccupied
class NetLayoutJunctionRange
class NetLayoutJunctionWire
class NetLayoutJunctionWireIntersection
class NetLayoutMetric
class NetLayoutPoint
class NetLayoutWire
class Netlist
class NetlistElementsTreeModel
A model to display arbitrary elements of the netlist.
class NetlistEvent
class NetlistInternalManager
class NetlistParser
class NetlistRelay
Connects the hal-core events to the gui.
class NetlistWriter
class NetModuleTable
class NewProjectDialog
class Node
The Node class object represents a module or a gate.
class NodeBox
The NodeBox class represents a node placed at a grid position within a hal view.
class NodeBoxes
The NodeBoxes class owns all NodeBox'es from hal view.
class NodeDragShadow
An item that is drawn when a node is dragged through the scene.
class OpenFileWidget
The welcome screen's OpenFile section.
class Overlay
The Overlay overlays its parent.
class PhysicalGraphLayouter
A specific implementation of a layouter.
class PinGroup
class PingroupSelectorDialog
class PlacementEntry
Container class to store a PlacementHint togerther with a set of modules and gates.
class PlacementHint
The PlacementHint class object provides hints for the layouter how new box objects are placed on a view. In standard mode placement is done using the most compact squere-like arrangement. Alternatively new box objects can be placed to the left or right to a node which serves as 'origin'.
class plugin_dataflow
class PluginParameter
class PluginParameterDialog
class PluginParameterFileDialog
class PluginRelay
Forwards plugin related events from the core to the gui.
class PositionGenerator
class PreviewWidget
unused.
class ProgramArguments
class ProgramOptions
class ProgressBar
class ProjectDirDialog
class ProjectDirDialogStatus
class ProjectDirectory
class ProjectJson
class ProjectManager
class ProjectSerializer
class PyCodeProvider
class Pyi_base
class Pyi_gui
class PythonCodeEditor
Code editor to write python code.
class PythonConsole
An interactable python console.
class PythonConsoleAbortThread
class PythonConsoleHistory
Stores the history of python commands.
class PythonConsoleQssAdapter
Connects the stylesheet properties to the console code.
class PythonConsoleWidget
Wraps the PythonConsole.
class PythonContextSubscriber
Interface for handling python outputs.
class PythonEditor
Main widget that combines all neccessary functionality to develop in python (for hal).
class PythonEditorCodeCompletionDialog
Dialog for python code completion.
class PythonGateSelectionReceiver
class PythonModuleSelectionReceiver
class PythonQssAdapter
QSS Adapter to provide the color configurations used by the PythonSyntaxHighlighter.
class PythonSerializer
class PythonSyntaxHighlighter
A syntax highlighter that fits for python code.
class PythonThread
class RAMComponent
class RAMPortComponent
class RecentFileItem
One item in the welcome screen's RecentFiles section.
class RecentFilesWidget
The welcome screen's RecentFiles section.
class Result
class RuntimeLibrary
class Searchbar
A QFrame with a QLineEdit that can be used to input a substring to search for.
class SelectionDetailsIconProvider
class SelectionDetailsWidget
Container for all specific details widgets.
class SelectionRelay
Stores and manages the gui's selection state.
class SelectionTreeItem
Basic item for the SelectionTreeModel.
class SelectionTreeItemGate
Tree item that represents a gate.
class SelectionTreeItemModule
Tree item that represents a module.
class SelectionTreeItemNet
Tree item that represents a net.
class SelectionTreeItemRoot
Tree item that represent the root.
class SelectionTreeModel
A model that contains the current selection.
class SelectionTreeModelDisposer
Deletes the current SelectionTreeModel.
class SelectionTreeProxyModel
Enables filtering of the SelectionTreeModel.
class SelectionTreeView
Displays the current selection.
class SeparatedGraphicsNet
Abstract base class for separated nets (e.g. ArrowSeparatedNet)
class SettingsDisplay
unused.
class SettingsItem
The interface for the logical part of a setting.
class SettingsItemCheckbox
A SettingsItem representing a Checkbox.
class SettingsItemDropdown
A SettingsItem that represents a dropdown menu.
class SettingsItemKeybind
A SettingsItem to modify keybinds.
class SettingsItemSlider
A SettingsItem representing a slider.
class SettingsItemSpinbox
A SettingsItem that represents a spinbox.
class SettingsItemText
A SettingsItem that represents a textfield.
class SettingsManager
Manages and persists the settings on the lowest level.
class SettingsWidget
The base class for all specific SettingsWidgets.
class SettingsWidgetCheckbox
A SettingsWidget representing a checkbox.
class SettingsWidgetDropdown
A SettingsWidget representing a dropdown menu.
class SettingsWidgetKeybind
A setting to configure keybinds.
class SettingsWidgetSlider
A SettingsWidget representing a slider.
class SettingsWidgetSpinbox
A SettingsWidget representing a spinbox.
class SettingsWidgetText
A SettingsWidget representing a textfield.
class SeveritySelector
class ShadowEffect
Creates a shadow effect around QObjects.
class SizeAdjustableTreeView
class SolveFsmPlugin
class SpecialLogContentManager
Logs the python editor and gui screenshots.
class SpinnerWidget
A loading wheel.
class Splitter
A QSplitter that can be checked if it is unused or not.
class SplitterAnchor
Adds specific ContentWidgets to HALs main content area.
class StackedValidator
Combines different validators into one.
class StandardArrowNet
A standard net that has parts of a separated net.
class StandardGraphicsGate
The standard gate to visualize netlist gates.
class StandardGraphicsModule
The standard module to visualize netlist modules.
class StandardGraphicsNet
The most basic net to display the standard nets.
class StandardGraphLayouter
The standard layouter used to layout netlists.
class StateComponent
class StateComponentEntry
Utility class that represents a state of the StateComponent.
class SubgraphNetlistDecorator
class SvgIconEngine
Creates Icons from svg data.
class TabWidget
Adds specific ContentWidgets to HALs main content area.
struct Token
class TokenStream
class Toolbar
Toolbar for all ContentFrames and ContentWidgets.
class TreeItem
(Future) Base class for all tree models related to the details widget.
class UIPluginInterface
class UniqueStringValidator
Checks if a given string is unique compared to other given strings.
class UserAction
The UserAction class is the abstract base class for user interactions.
class UserActionCompound
class UserActionCompoundFactory
class UserActionFactory
The UserActionFactory is the abstract base class for registration.
class UserActionManager
Handles and manages user actions related proccesses.
class UserActionObject
The UserActionObject class represents a single object used in UserAction.
class UserActionObjectType
The UserActionObjectType class provides the type for UserActionObject.
class Validator
Base class for any string validator.
class VerilogParser
class VerilogParserPlugin
class VerilogParserTest
class VerilogWriter
class VerilogWriterPlugin
class VerilogWriterTest
class VHDLParser
class VHDLParserPlugin
class VHDLParserTest
class WaitToBeSeatedEntry
class WaitToBeSeatedList
class WelcomeScreen
Hal's welcome screen.
class Widget
A QWidget customized for hal.
class WidgetOverlay
Container for a QWidget that overlays another one.
Typedefs
typedef std::error_code error_code
using instantiate_plugin_function = std::unique_ptr< BasePluginInterface >(*)()
using lib_fn_ptr_t = void(*)()
using handle_ptr_t = void *
template<class T >
using RawPtrWrapper = std::unique_ptr< T, py::nodelete >
Enumerations
enum content_anchor { content_anchor::center = 0, content_anchor::left = 1, content_anchor::right = 2, content_anchor::bottom = 3 }
enum button_orientation { button_orientation::horizontal = 0, button_orientation::vertical_up = 1, button_orientation::vertical_down = 2 }
enum ItemType { ItemType::None, ItemType::Module, ItemType::Gate, ItemType::Net }
The ItemType enum provides the enum type to classify graphic items into Modules, Gates or Nets. The ItemType None indicates that the ItemType has not been initialized or that a function could not determine the ItemType.
enum AsyncSetResetBehavior {
AsyncSetResetBehavior::L, AsyncSetResetBehavior::H, AsyncSetResetBehavior::N, AsyncSetResetBehavior::T,
AsyncSetResetBehavior::X, AsyncSetResetBehavior::undef
}
enum GateTypeProperty {
GateTypeProperty::combinational, GateTypeProperty::sequential, GateTypeProperty::tristate, GateTypeProperty::power,
GateTypeProperty::ground, GateTypeProperty::ff, GateTypeProperty::latch, GateTypeProperty::ram,
GateTypeProperty::io, GateTypeProperty::dsp, GateTypeProperty::pll, GateTypeProperty::oscillator,
GateTypeProperty::scan, GateTypeProperty::c_buffer, GateTypeProperty::c_inverter, GateTypeProperty::c_and,
GateTypeProperty::c_nand, GateTypeProperty::c_or, GateTypeProperty::c_nor, GateTypeProperty::c_xor,
GateTypeProperty::c_xnor, GateTypeProperty::c_aoi, GateTypeProperty::c_oai, GateTypeProperty::c_mux,
GateTypeProperty::c_carry, GateTypeProperty::c_half_adder, GateTypeProperty::c_full_adder, GateTypeProperty::c_lut
}
enum PinDirection {
PinDirection::none, PinDirection::input, PinDirection::output, PinDirection::inout,
PinDirection::internal
}
enum PinType {
PinType::none, PinType::power, PinType::ground, PinType::lut,
PinType::state, PinType::neg_state, PinType::clock, PinType::enable,
PinType::set, PinType::reset, PinType::data, PinType::address,
PinType::io_pad, PinType::select, PinType::carry, PinType::sum
}
Functions
std::ostream & operator<< (std::ostream &os, BooleanFunction::Value v)
std::ostream & operator<< (std::ostream &os, const BooleanFunction &function)
void initialize ()
std::ostream & operator<< (std::ostream &os, const GateType &gt)
PYBIND11_PLUGIN (hal_py)
uint qHash (const hal::NetLayoutWire &w)
uint qHash (const hal::NetLayoutPoint &p)
bool compareWaitToBeSeated (const WaitToBeSeatedEntry *a, const WaitToBeSeatedEntry *b)
uint qHash (const Node &n)
QColor toQColor (utils::Color c)
void runMain (const QString fileName, const QList< QString > plugins)
std::unique_ptr< BasePluginInterface > create_plugin_instance ()
PYBIND11_PLUGIN (hal_gui)
PYBIND11_PLUGIN (boolean_influence)
PYBIND11_PLUGIN (dataflow)
PYBIND11_PLUGIN (solve_fsm)
TEST_F (HGLParserTest, check_library)
TEST_F (HGLWriterTest, check_library)
PYBIND11_PLUGIN (graph_algorithm)
TEST_F (VerilogParserTest, check_main_example)
TEST_F (VerilogParserTest, check_whitespace_chaos)
TEST_F (VerilogParserTest, check_pin_assignments)
TEST_F (VerilogParserTest, check_parameters)
TEST_F (VerilogParserTest, check_net_vectors)
TEST_F (VerilogParserTest, check_zero_padding)
TEST_F (VerilogParserTest, check_special_nets)
TEST_F (VerilogParserTest, check_multiple_entities)
TEST_F (VerilogParserTest, check_direct_assignment)
TEST_F (VerilogParserTest, check_pin_group_port_assignment)
TEST_F (VerilogParserTest, check_comments)
TEST_F (VerilogParserTest, check_attributes)
TEST_F (VerilogParserTest, check_one_line_multiple_nets)
TEST_F (VerilogParserTest, check_port_dekl_in_list_of_ports)
TEST_F (VerilogParserTest, check_invalid_input)
TEST_F (VerilogWriterTest, check_main)
TEST_F (VerilogWriterTest, check_global_nets)
TEST_F (VerilogWriterTest, check_modules)
TEST_F (VerilogWriterTest, check_data)
TEST_F (VerilogWriterTest, check_multi_bit_pins)
TEST_F (VHDLParserTest, check_main_example)
TEST_F (VHDLParserTest, check_whitespace_chaos_)
TEST_F (VHDLParserTest, check_pin_assignments)
TEST_F (VHDLParserTest, check_generic_map)
TEST_F (VHDLParserTest, check_net_vectors)
TEST_F (VHDLParserTest, check_special_nets)
TEST_F (VHDLParserTest, check_multiple_entities)
TEST_F (VHDLParserTest, check_direct_assignment)
TEST_F (VHDLParserTest, check_pin_group_port_assignment)
TEST_F (VHDLParserTest, check_comments)
TEST_F (VHDLParserTest, check_attributes)
TEST_F (VHDLParserTest, check_lib_prefix)
TEST_F (VHDLParserTest, check_component)
TEST_F (VHDLParserTest, check_invalid_input)
TEST_F (LibertyParserTest, check_combinatorial)
TEST_F (LibertyParserTest, check_flip_flop)
TEST_F (LibertyParserTest, check_latch)
TEST_F (LibertyParserTest, check_multiline_comment)
TEST_F (LibertyParserTest, check_invalid_input)
template<typename T , typename = typename std::enable_if<std::is_enum<T>::value, T>::type>
std::string enum_to_string (T e)
template<typename T , typename = typename std::enable_if<std::is_enum<T>::value, T>::type>
T enum_from_string (const std::string &str)
template<typename T , typename = typename std::enable_if<std::is_enum<T>::value, T>::type>
T enum_from_string (const std::string &str, const T default_val) noexcept
template<typename T , typename = typename std::enable_if<std::is_enum<T>::value, T>::type>
std::ostream & operator<< (std::ostream &os, T e)
Variables
QSettings * mGSettings = nullptr
const char * sOpenMethodsPersist [] = {"Undefined", "CreateNew", "ImportFile", "OpenProject", nullptr}
Typedef Documentation
error_code
typedef std::error_code hal::error_code
Definition at line 50 of file defines.h.
handle_ptr_t
using hal::handle_ptr_t = typedef void*
Definition at line 42 of file runtime_library.h.
instantiate_plugin_function
using hal::instantiate_plugin_function = typedef std::unique_ptr<BasePluginInterface> (*)()
Definition at line 157 of file plugin_interface_base.h.
lib_fn_ptr_t
using hal::lib_fn_ptr_t = typedef void (*)()
Definition at line 41 of file runtime_library.h.
Enumeration Type Documentation
AsyncSetResetBehavior
enum hal::AsyncSetResetBehavior strong
Defines the behavior of the gate type in case both asynchronous set and reset are active at the same time.
Enumerator
L
Set the internal state to 0.
H
Set the internal state to 1.
N
Do not change the internal state.
T
Toggle, i.e., invert the internal state.
X
Set the internal state to X.
undef
Invalid behavior, used by default.
Definition at line 35 of file async_set_reset_behavior.h.
content_anchor
enum hal::content_anchor strong
Enumerator
center
left
right
bottom
Definition at line 43 of file content_layout_area.h.
GateTypeProperty
enum hal::GateTypeProperty strong
A set of available properties for a gate type.
Enumerator
combinational
Combinational gate type.
sequential
Sequential gate type.
tristate
Tristate gate type.
power
Power gate type.
ground
Ground gate type.
ff
Flip-flop gate type.
latch
Latch gate type.
ram
RAM gate type.
io
IO gate type.
dsp
DSP gate type.
pll
PLL gate type.
oscillator
Oscillator gate type.
scan
Scan gate type.
c_buffer
Buffer gate type.
c_inverter
Inverter gate type.
c_and
AND gate type.
c_nand
NAND gate type.
c_or
OR gate type.
c_nor
NOR gate type.
c_xor
XOR gate type.
c_xnor
XNOR gate type.
c_aoi
AOI gate type.
c_oai
OAI gate type.
c_mux
MUX gate type.
c_carry
Carry gate type.
c_half_adder
Half adder gate type.
c_full_adder
Full adder gate type.
c_lut
LUT gate type.
Definition at line 33 of file gate_type_property.h.
PinDirection
enum hal::PinDirection strong
Defines the direction of a pin.
Enumerator
none
Invalid pin.
input
Input pin.
output
Output pin.
inout
Inout pin.
internal
Internal pin.
Definition at line 35 of file pin_direction.h.
PinType
enum hal::PinType strong
Defines the type of a pin.
Enumerator
none
Default pin.
power
Power pin.
ground
Ground pin.
lut
Pin that generates output from LUT initialization string.
state
Pin that generates output from internal state.
neg_state
Pin that generates output from negated internal state.
clock
Clock pin.
enable
Enable pin.
set
Set/preset pin.
reset
Reset/clear pin.
data
Data pin.
address
Address pin.
io_pad
IO pad pin.
select
Select pin.
carry
Carry pin.
sum
Sum pin.
Definition at line 35 of file pin_type.h.
Function Documentation
compareWaitToBeSeated()
bool hal::compareWaitToBeSeated (const WaitToBeSeatedEntry * a, const WaitToBeSeatedEntry * b)
Definition at line 66 of file wait_to_be_seated.cpp.
References hal::gui_utility::b, and hal::WaitToBeSeatedEntry::getId().
Referenced by hal::WaitToBeSeatedList::setLinks().
create_plugin_instance()
PLUGIN_API std::unique_ptr< BasePluginInterface > hal::create_plugin_instance ()
Definition at line 43 of file plugin_gui.cpp.
enum_from_string() [1/2]
template<typename T , typename = typename std::enable_if<std::is_enum<T>::value, T>::type> T hal::enum_from_string (const std::string & str)
Translates a string into an enum value if possible. Throws an exception if no matching enum value is found.
Parameters
[in] str - The string.
Returns
The enum value.
Definition at line 72 of file enums.h.
References control::str, and T.
enum_from_string() [2/2]
template<typename T , typename = typename std::enable_if<std::is_enum<T>::value, T>::type> T hal::enum_from_string (const std::string & str, const T default_val) noexcept
Translates a string into an enum value if possible. Defaults to the given default value if no matching enum value is found.
Parameters
[in] str - The string.
[in] default_val - The default value.
Returns
The enum value.
Definition at line 94 of file enums.h.
References control::str, and T.
enum_to_string()
template<typename T , typename = typename std::enable_if<std::is_enum<T>::value, T>::type> std::string hal::enum_to_string (T e)
Translates an enum value into its string representation.
Parameters
[in] e - The enum value.
Returns
The string representation.
Definition at line 52 of file enums.h.
References nlohmann::to_string().
Referenced by hal::GateType::create_pin(), hal::ActionSetObjectType::exec(), operator<<(), hal::SMT::operator<<(), hal::GatePinsTreeModel::setGate(), hal::ModulePinsTreeModel::setModule(), and hal::BooleanFunction::Node::to_string().
initialize()
void hal::initialize ()
Definition at line 299 of file event_log.cpp.
References hal::LogManager::add_channel(), hal::LogManager::create_file_sink(), hal::LogManager::create_gui_sink(), hal::LogManager::create_stdout_sink(), and hal::LogManager::get_instance().
Referenced by hal::dataflow::processing::pass_collection::get_passes(), and hal::plugin_manager::get_plugin_instance().
operator<<() [1/4]
std::ostream& hal::operator<< (std::ostream & os, BooleanFunction::Value v)
Output stream operator that forwards to_string of a value.
Parameters
[in] os - The stream to write to.
[in] value - The value.
Returns
A reference to output stream.
Definition at line 229 of file boolean_function.cpp.
References hal::BooleanFunction::to_string().
operator<<() [2/4]
std::ostream& hal::operator<< (std::ostream & os, const BooleanFunction & function)
The ostream operator that forwards to_string of a boolean function.
Parameters
[in] os - the stream to write to.
[in] f - the function.
Returns
A reference to os.
Definition at line 533 of file boolean_function.cpp.
operator<<() [3/4]
std::ostream& hal::operator<< (std::ostream & os, const GateType & gt)
Insert the gate type object to an output stream.
Parameters
[in] os - The output stream.
[in] gate_type - The gate type.
Returns
An output stream.
Definition at line 105 of file gate_type.cpp.
References hal::GateType::to_string().
operator<<() [4/4]
template<typename T , typename = typename std::enable_if<std::is_enum<T>::value, T>::type> std::ostream& hal::operator<< (std::ostream & os, T e)
Inserts the string representation of an enum value into an output stream.
Parameters
[in] os - The output stream.
[in] e - The enum value.
Returns
Reference to the provided stream.
Definition at line 115 of file enums.h.
References enum_to_string().
PYBIND11_PLUGIN() [1/6]
hal::PYBIND11_PLUGIN (boolean_influence)
Definition at line 22 of file python_bindings.cpp.
References hal::BooleanInfluencePlugin::get_boolean_influence(), hal::BooleanInfluencePlugin::get_boolean_influences_of_gate(), hal::BooleanInfluencePlugin::get_boolean_influences_of_subcircuit(), hal::BooleanInfluencePlugin::get_ff_dependency_matrix(), hal::BooleanInfluencePlugin::get_name(), hal::BooleanInfluencePlugin::get_version(), log_error, and hal::ShortestPath::module().
PYBIND11_PLUGIN() [2/6]
hal::PYBIND11_PLUGIN (dataflow)
Definition at line 18 of file python_bindings.cpp.
References hal::plugin_dataflow::execute(), hal::plugin_dataflow::get_name(), hal::plugin_dataflow::get_version(), and hal::ShortestPath::module().
PYBIND11_PLUGIN() [3/6]
hal::PYBIND11_PLUGIN (graph_algorithm)
Definition at line 35 of file python_bindings.cpp.
References hal::GraphAlgorithmPlugin::get_communities(), hal::GraphAlgorithmPlugin::get_communities_fast_greedy(), hal::GraphAlgorithmPlugin::get_communities_spinglass(), hal::GraphAlgorithmPlugin::get_graph_cut(), hal::GraphAlgorithmPlugin::get_name(), hal::GraphAlgorithmPlugin::get_strongly_connected_components(), hal::GraphAlgorithmPlugin::get_version(), and hal::ShortestPath::module().
PYBIND11_PLUGIN() [4/6]
hal::PYBIND11_PLUGIN (hal_gui)
Definition at line 30 of file python_gui_api_bindings.cpp.
References hal::GuiApi::deselect(), hal::GuiApi::deselectAllItems(), hal::GuiApi::deselectGate(), hal::GuiApi::deselectModule(), hal::GuiApi::deselectNet(), QString::fromStdString(), hal::GuiApi::getSelectedGateIds(), hal::GuiApi::getSelectedGates(), hal::GuiApi::getSelectedItemIds(), hal::GuiApi::getSelectedItems(), hal::GuiApi::getSelectedModuleIds(), hal::GuiApi::getSelectedModules(), hal::GuiApi::getSelectedNetIds(), hal::GuiApi::getSelectedNets(), gPythonContext, hal::ShortestPath::module(), hal::GuiApi::select(), hal::GuiApi::selectGate(), hal::GuiApi::selectModule(), and hal::GuiApi::selectNet().
PYBIND11_PLUGIN() [5/6]
hal::PYBIND11_PLUGIN (hal_py)
Definition at line 10 of file python_bindings.cpp.
References base_pin_init(), boolean_function_decorator_init(), boolean_function_init(), boolean_function_net_decorator_init(), core_utils_init(), data_container_init(), endpoint_init(), gate_init(), gate_library_init(), gate_library_manager_init(), gate_pin_init(), gate_type_components_init(), gate_type_init(), grouping_init(), log_info, message(), hal::ShortestPath::module(), module_init(), module_pin_init(), net_init(), netlist_factory_init(), netlist_init(), netlist_serializer_init(), netlist_utils_init(), netlist_writer_manager_init(), path_init(), pin_group_init(), plugin_interfaces_init(), plugin_manager_init(), project_manager_init(), smt_init(), and subgraph_netlist_decorator_init().
PYBIND11_PLUGIN() [6/6]
hal::PYBIND11_PLUGIN (solve_fsm)
Definition at line 24 of file python_bindings.cpp.
References base, hal::SolveFsmPlugin::generate_dot_graph(), hal::SolveFsmPlugin::get_name(), hal::SolveFsmPlugin::get_version(), test_plugin::initial_state, log_error, hal::ShortestPath::module(), hal::SolveFsmPlugin::solve_fsm(), hal::SolveFsmPlugin::solve_fsm_brute_force(), and test_plugin::timeout.
qHash() [1/3]
uint hal::qHash (const hal::NetLayoutPoint & p)
Definition at line 21 of file net_layout_point.cpp.
References qHash().
qHash() [2/3]
uint hal::qHash (const hal::NetLayoutWire & w)
Definition at line 26 of file net_layout_point.cpp.
References hal::NetLayoutWire::endPoint(), hal::NetLayoutWire::isHorizontal(), and hal::NetLayoutWire::SourcePoint.
Referenced by qHash().
qHash() [3/3]
uint hal::qHash (const Node & n)
Definition at line 94 of file node_box.cpp.
References hal::Node::id(), hal::Node::Module, and hal::Node::type().
runMain()
void hal::runMain (const QString fileName, const QList< QString > plugins)
TEST_F() [1/41]
hal::TEST_F (HGLParserTest , check_library)
Testing parsing an HGL file.
Functions: parse
Definition at line 26 of file hgl_parser.cpp.
References hal::utils::get_base_directory(), hal::gate_library_manager::get_gate_library(), and control::parser.
TEST_F() [2/41]
hal::TEST_F (HGLWriterTest , check_library)
Testing writing an HGL file.
Functions: write
Definition at line 28 of file hgl_writer.cpp.
References hal::gate_library_manager::get_gate_library(), control::parser, and hal::HGLWriter::write().
TEST_F() [3/41]
hal::TEST_F (LibertyParserTest , check_combinatorial)
Testing the creation of a combinatorial Gate type with one input pin, one output pin and a boolean function.
Functions: parse
Definition at line 26 of file liberty_parser.cpp.
References hal::BooleanFunction::from_string(), hal::utils::get_base_directory(), hal::GateType::get_boolean_functions(), hal::GateType::get_components(), hal::GateType::get_pins(), hal::GateType::get_properties(), ground, input, none, output, hal::LibertyParser::parse(), pins, power, and hal::BooleanFunction::Var().
TEST_F() [4/41]
hal::TEST_F (LibertyParserTest , check_flip_flop)
Testing the creation of flip-flops
Functions: parse
Definition at line 97 of file liberty_parser.cpp.
References clock, hal::BooleanFunction::from_string(), hal::FFComponent::get_async_reset_function(), hal::FFComponent::get_async_set_function(), hal::FFComponent::get_async_set_reset_behavior(), hal::utils::get_base_directory(), hal::GateType::get_boolean_functions(), hal::FFComponent::get_clock_function(), hal::GateType::get_component_as(), hal::GateType::get_components(), hal::StateComponent::get_neg_state_identifier(), hal::FFComponent::get_next_state_function(), hal::GateType::get_pins(), hal::GateType::get_properties(), hal::StateComponent::get_state_identifier(), H, input, hal::StateComponent::is_class_of(), hal::FFComponent::is_class_of(), L, neg_state, output, hal::LibertyParser::parse(), pins, state, and hal::BooleanFunction::Var().
TEST_F() [5/41]
hal::TEST_F (LibertyParserTest , check_invalid_input)
Testing the correct handling of invalid input and other uncommon inputs
Functions: parse
Definition at line 359 of file liberty_parser.cpp.
References hal::utils::get_base_directory(), and hal::LibertyParser::parse().
TEST_F() [6/41]
hal::TEST_F (LibertyParserTest , check_latch)
Testing the creation of a latches
Functions: parse
Definition at line 202 of file liberty_parser.cpp.
References hal::BooleanFunction::from_string(), hal::LatchComponent::get_async_reset_function(), hal::LatchComponent::get_async_set_function(), hal::LatchComponent::get_async_set_reset_behavior(), hal::utils::get_base_directory(), hal::GateType::get_boolean_functions(), hal::GateType::get_component_as(), hal::GateType::get_components(), hal::LatchComponent::get_data_in_function(), hal::LatchComponent::get_enable_function(), hal::StateComponent::get_neg_state_identifier(), hal::GateType::get_pins(), hal::GateType::get_properties(), hal::StateComponent::get_state_identifier(), input, hal::LatchComponent::is_class_of(), hal::StateComponent::is_class_of(), N, neg_state, output, hal::LibertyParser::parse(), pins, state, T, and hal::BooleanFunction::Var().
TEST_F() [7/41]
hal::TEST_F (LibertyParserTest , check_multiline_comment)
Testing the usage of multiline comments (via '/ *' and '* /' (without space))
Functions: parse
Definition at line 300 of file liberty_parser.cpp.
References hal::utils::get_base_directory(), hal::GateType::get_pins(), input, output, hal::LibertyParser::parse(), and pins.
TEST_F() [8/41]
hal::TEST_F (VerilogParserTest , check_attributes)
Testing the usage of attributes for gates nets and modules
Functions: parse
Definition at line 2246 of file verilog_parser.cpp.
References hal::DataContainer::get_data(), hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [9/41]
hal::TEST_F (VerilogParserTest , check_comments)
Testing the correct detection of single line comments (with '//') and comment blocks(with '/ *' and '* /').
Functions: parse
Definition at line 2172 of file verilog_parser.cpp.
References hal::DataContainer::get_data(), hal::Gate::get_fan_out_net(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [10/41]
hal::TEST_F (VerilogParserTest , check_direct_assignment)
Testing the correct handling of direct assignment (e.g. 'assign net_slave = net_master;'), where two (wire-)identifiers address the same Net. The Net (wire) at the left side of the expression is mapped to the Net at the right side, so only the Net with the right identifier will be created.
In Verilog, assignemts of vectors (for example: assign sig_vec_1[0:3] = sig_vec_2[0:3]) and assignments of lists of vectors and/or single nets (for example: "assign {sig_vec_1, signal_1} = {sig_vec_big[0:4]}", if |sig_vec_1|=4) are also supported.
However, logic expressions like 'assign A = B ^ C' are NOT supported.
Functions: parse
Definition at line 1540 of file verilog_parser.cpp.
References hal::Net::get_destinations(), hal::Gate::get_fan_in_net(), hal::Gate::get_fan_out_net(), hal::Endpoint::get_gate(), hal::gate_library_manager::get_gate_library(), hal::BasePin< T >::get_name(), hal::Gate::get_name(), hal::Endpoint::get_pin(), hal::Net::is_global_input_net(), hal::NetlistParser::parse_and_instantiate(), and nlohmann::to_string().
TEST_F() [11/41]
hal::TEST_F (VerilogParserTest , check_invalid_input)
Testing the correct handling of invalid input
Functions: parse
Definition at line 2521 of file verilog_parser.cpp.
References hal::Gate::get_fan_in_net(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [12/41]
hal::TEST_F (VerilogParserTest , check_main_example)
Testing the correct usage of the verilog parser by parse a small verilog-format string, which describes the netlist shown above.
Functions: parse
Definition at line 41 of file verilog_parser.cpp.
References hal::Net::get_destinations(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), hal::Gate::get_name(), hal::Net::get_sources(), hal::NetlistParser::parse_and_instantiate(), and hal::utils::vectors_have_same_content().
TEST_F() [13/41]
hal::TEST_F (VerilogParserTest , check_multiple_entities)
Testing the usage of additional entities. Entities that are used by the main entity (the last one) are recursively split in gates that are part of the Gate library, while the original entity hierarchy is represented by the Module- hierarchy of the netlist. Therefore, there can be multiple gates with the same name, so names that occur twice or more will be extended by a unique suffix.
Functions: parse
Definition at line 1044 of file verilog_parser.cpp.
References test::g, hal::DataContainer::get_data(), hal::Net::get_destinations(), hal::Gate::get_fan_in_net(), hal::Gate::get_fan_out_net(), hal::Endpoint::get_gate(), hal::gate_library_manager::get_gate_library(), hal::Module::get_gates(), hal::Module::get_name(), hal::Gate::get_name(), hal::Module::get_output_nets(), hal::Module::get_submodules(), hal::Gate::get_successor(), hal::Module::get_type(), hal::Module::is_top_module(), hal::NetlistParser::parse_and_instantiate(), hal::utils::starts_with(), and hal::utils::vectors_have_same_content().
TEST_F() [14/41]
hal::TEST_F (VerilogParserTest , check_net_vectors)
Testing the handling of Net-vectors in dimension 1-3
Functions: parse
Definition at line 737 of file verilog_parser.cpp.
References hal::Net::get_destinations(), hal::gate_library_manager::get_gate_library(), hal::Net::get_sources(), hal::NetlistParser::parse_and_instantiate(), and nlohmann::to_string().
TEST_F() [15/41]
hal::TEST_F (VerilogParserTest , check_one_line_multiple_nets)
Testing the declaration of multiple wire vectors within one single line.
Functions: parse
Definition at line 2333 of file verilog_parser.cpp.
References hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [16/41]
hal::TEST_F (VerilogParserTest , check_parameters)
Testing the correct storage of data of the following data types: integer, floating_point, string, bit_vector (hexadecimal, decimal, octal, binary)
Functions: parse
Definition at line 676 of file verilog_parser.cpp.
References hal::DataContainer::get_data(), hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [17/41]
hal::TEST_F (VerilogParserTest , check_pin_assignments)
Test different variants of pin assignments to modules and gates.
Functions: parse
Definition at line 235 of file verilog_parser.cpp.
References hal::Gate::get_fan_in_endpoint(), hal::Gate::get_fan_out_endpoint(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), hal::Endpoint::get_net(), hal::Module::get_pins(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [18/41]
hal::TEST_F (VerilogParserTest , check_pin_group_port_assignment)
Testing the port assignment of multiple pins and nets using pin groups and signal vectors
Functions: parse
Definition at line 1859 of file verilog_parser.cpp.
References hal::Gate::get_fan_in_net(), hal::Gate::get_fan_in_nets(), hal::Gate::get_fan_out_net(), hal::Gate::get_fan_out_nets(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), net, and hal::NetlistParser::parse_and_instantiate().
TEST_F() [19/41]
hal::TEST_F (VerilogParserTest , check_port_dekl_in_list_of_ports)
Testing the port declaration within the list of ports.
Functions: parse
Definition at line 2394 of file verilog_parser.cpp.
References hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [20/41]
hal::TEST_F (VerilogParserTest , check_special_nets)
Testing assignment of '0', '1', 'Z', and 'X'.
Functions: parse
Definition at line 963 of file verilog_parser.cpp.
References hal::Gate::get_fan_in_net(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), hal::Net::get_sources(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [21/41]
hal::TEST_F (VerilogParserTest , check_whitespace_chaos)
The same test, as the main example, but use white spaces of different types (' ','
','\t') in various locations (or remove some unnecessary ones)
Functions: parse
Definition at line 148 of file verilog_parser.cpp.
References hal::Net::get_destinations(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), hal::Gate::get_name(), hal::Net::get_sources(), hal::NetlistParser::parse_and_instantiate(), and hal::utils::vectors_have_same_content().
TEST_F() [22/41]
hal::TEST_F (VerilogParserTest , check_zero_padding)
Test zero parsing and (implicit) zero padding.
Functions: parse
Definition at line 918 of file verilog_parser.cpp.
References hal::Gate::get_fan_in_endpoints(), hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [23/41]
hal::TEST_F (VerilogWriterTest , check_data)
Test writing generic data.
Functions: write
Definition at line 287 of file verilog_writer.cpp.
References hal::DataContainer::get_data(), hal::DataContainer::get_data_map(), hal::NetlistParser::parse_and_instantiate(), hal::DataContainer::set_data(), and hal::VerilogWriter::write().
TEST_F() [24/41]
hal::TEST_F (VerilogWriterTest , check_global_nets)
Test writing global input and output nets.
Functions: write
Definition at line 113 of file verilog_writer.cpp.
References hal::Net::get_name(), hal::Module::get_pin_by_net(), net, hal::NetlistParser::parse_and_instantiate(), hal::Module::set_pin_name(), and hal::VerilogWriter::write().
TEST_F() [25/41]
hal::TEST_F (VerilogWriterTest , check_main)
Test writing a given netlist to file and subsequently parse it using the VerilogParser.
Functions: write
Definition at line 41 of file verilog_writer.cpp.
References hal::BasePin< T >::get_group(), hal::Net::get_name(), hal::Module::get_pin_by_net(), hal::Gate::mark_gnd_gate(), hal::Gate::mark_vcc_gate(), hal::NetlistParser::parse_and_instantiate(), hal::Module::set_pin_group_name(), hal::Module::set_pin_name(), hal::Module::set_type(), and hal::VerilogWriter::write().
TEST_F() [26/41]
hal::TEST_F (VerilogWriterTest , check_modules)
Test writing a modularized netlist.
Functions: write
Definition at line 187 of file verilog_writer.cpp.
References hal::ShortestPath::module(), hal::NetlistParser::parse_and_instantiate(), and hal::VerilogWriter::write().
TEST_F() [27/41]
hal::TEST_F (VerilogWriterTest , check_multi_bit_pins)
Test writing gates with multi-bit pins.
Functions: write
Definition at line 364 of file verilog_writer.cpp.
References hal::Gate::get_fan_in_endpoints(), hal::Gate::get_fan_in_net(), hal::Gate::get_fan_in_nets(), hal::Gate::get_fan_out_endpoints(), hal::Gate::get_fan_out_net(), hal::Gate::get_fan_out_nets(), hal::Net::get_name(), hal::Module::get_pin_by_net(), hal::NetlistParser::parse_and_instantiate(), hal::Module::set_pin_name(), nlohmann::to_string(), and hal::VerilogWriter::write().
TEST_F() [28/41]
hal::TEST_F (VHDLParserTest , check_attributes)
Testing the usage of user-defined attributes within the architecture and the entity header.
Functions: parse
Definition at line 2148 of file vhdl_parser.cpp.
References hal::DataContainer::get_data(), hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [29/41]
hal::TEST_F (VHDLParserTest , check_comments)
Testing the correct detection of single line comments (initiated with '–') within the vhdl file.
Functions: parse
Definition at line 2089 of file vhdl_parser.cpp.
References hal::DataContainer::get_data(), hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [30/41]
hal::TEST_F (VHDLParserTest , check_component)
NOTE: Currently Unsupported... Testing the usage of components, which should define new Gate types with custom input/output/inout pins. (currently unsupported...)
Functions: parse
Definition at line 2315 of file vhdl_parser.cpp.
TEST_F() [31/41]
hal::TEST_F (VHDLParserTest , check_direct_assignment)
NOTE: Are multi dim assignments supported? Testing the correct handling of direct assignment (e.g. 'net_slave = net_master;'), where two (signal-)identifiers address the same Net. The Net (signal) at the left side of the expression is mapped to the Net at the right side, so only the Net with the right identifier will be created.
However, logic expressions like 'A <= B*C' are NOT supported.
Functions: parse
Definition at line 1772 of file vhdl_parser.cpp.
References hal::DataContainer::get_data(), hal::Gate::get_fan_in_net(), hal::Gate::get_fan_out_net(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), hal::Net::is_global_input_net(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [32/41]
hal::TEST_F (VHDLParserTest , check_generic_map)
Testing the correct storage of data, passed by the "generic map" keyword
Functions: parse
Definition at line 876 of file vhdl_parser.cpp.
References hal::DataContainer::get_data(), hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [33/41]
hal::TEST_F (VHDLParserTest , check_invalid_input)
Testing the correct handling of invalid input
Functions: parse
Definition at line 2366 of file vhdl_parser.cpp.
References hal::DataContainer::get_data(), hal::Gate::get_fan_in_nets(), hal::Gate::get_fan_out_nets(), hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [34/41]
hal::TEST_F (VHDLParserTest , check_lib_prefix)
Testing the usage and the correct handling of library prefixes
Functions: parse
Definition at line 2278 of file vhdl_parser.cpp.
References hal::gate_library_manager::get_gate_library(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [35/41]
hal::TEST_F (VHDLParserTest , check_main_example)
Testing the correct usage of the vhdl parser by parse a small vhdl-format string, which describes the netlist shown above.
Functions: parse
Definition at line 40 of file vhdl_parser.cpp.
References hal::Net::get_destinations(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), hal::Gate::get_name(), hal::Net::get_sources(), hal::NetlistParser::parse_and_instantiate(), and hal::utils::vectors_have_same_content().
TEST_F() [36/41]
hal::TEST_F (VHDLParserTest , check_multiple_entities)
Testing the usage of additional entities. Entities that are used by the main entity (the last one) are recursively split in gates that are part of the Gate library, while the original entity hierarchy is represented by the Module- hierarchy of the netlist. Therefore, there can be multiple gates with the same name, so names that occur twice or more will be extended by a unique suffix.
Functions: parse
Definition at line 1235 of file vhdl_parser.cpp.
References test::g, hal::DataContainer::get_data(), hal::Net::get_destinations(), hal::Gate::get_fan_in_net(), hal::Gate::get_fan_out_net(), hal::Endpoint::get_gate(), hal::gate_library_manager::get_gate_library(), hal::Module::get_gates(), hal::Module::get_name(), hal::Gate::get_name(), hal::Module::get_output_nets(), hal::Module::get_submodules(), hal::Gate::get_successor(), hal::Module::get_type(), hal::Module::is_top_module(), hal::NetlistParser::parse_and_instantiate(), hal::utils::starts_with(), and hal::utils::vectors_have_same_content().
TEST_F() [37/41]
hal::TEST_F (VHDLParserTest , check_net_vectors)
Testing the handling of Net-vectors in dimension 1-3
Functions: parse
Definition at line 953 of file vhdl_parser.cpp.
References hal::Net::get_destinations(), hal::gate_library_manager::get_gate_library(), hal::Net::get_sources(), hal::NetlistParser::parse_and_instantiate(), and nlohmann::to_string().
TEST_F() [38/41]
hal::TEST_F (VHDLParserTest , check_pin_assignments)
Test different variants of pin assignments to modules and gates.
Functions: parse
Definition at line 264 of file vhdl_parser.cpp.
References hal::Gate::get_fan_in_endpoint(), hal::Gate::get_fan_out_endpoint(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), hal::Endpoint::get_net(), hal::Module::get_pins(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [39/41]
hal::TEST_F (VHDLParserTest , check_pin_group_port_assignment)
Testing the port assignment of multiple pins and nets using pin groups and signal vectors
Functions: parse
Definition at line 1916 of file vhdl_parser.cpp.
References hal::Gate::get_fan_in_net(), hal::Gate::get_fan_out_net(), hal::Gate::get_fan_out_nets(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [40/41]
hal::TEST_F (VHDLParserTest , check_special_nets)
Testing assignment of '0', '1', 'Z', and 'X'.
Functions: parse
Definition at line 1149 of file vhdl_parser.cpp.
References hal::Gate::get_fan_in_net(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), hal::Net::get_sources(), and hal::NetlistParser::parse_and_instantiate().
TEST_F() [41/41]
hal::TEST_F (VHDLParserTest , check_whitespace_chaos_)
The same test, as the main example, but use white spaces of different types (' ','
','\t') in various locations (or remove some unnecessary ones)
Functions: parse
Definition at line 161 of file vhdl_parser.cpp.
References hal::Net::get_destinations(), hal::gate_library_manager::get_gate_library(), hal::Net::get_name(), hal::Gate::get_name(), hal::Net::get_sources(), hal::NetlistParser::parse_and_instantiate(), and hal::utils::vectors_have_same_content().
toQColor()
QColor hal::toQColor (utils::Color c)
Definition at line 11 of file grouping_table_model.cpp.
References QColor::fromHsv(), hal::utils::Color::h, hal::utils::Color::s, and hal::utils::Color::v.
Referenced by hal::GroupingTableEntry::color(), and hal::GroupingTableModel::groupingColorChangedEvent().
Variable Documentation
gCommentManager
CommentManager * hal::gCommentManager = nullptr
The global CommentManager
Definition at line 59 of file plugin_gui.cpp.
Referenced by hal::CommentWidget::CommentWidget(), and hal::GraphLayouter::GraphLayouter().
gContentManager
ContentManager * hal::gContentManager = nullptr
The global ContentManager (see doc)
Definition at line 50 of file plugin_gui.cpp.
Referenced by hal::GraphicsScene::connectAll(), hal::GraphicsScene::disconnectAll(), hal::ActionDeleteObject::exec(), hal::ActionSetObjectColor::exec(), hal::ActionCreateObject::exec(), hal::ActionRenameObject::exec(), hal::ActionUnfoldModule::exec(), hal::ActionFoldModule::exec(), hal::GateSelectPicker::GateSelectPicker(), hal::GraphLayouter::GraphLayouter(), hal::GraphicsItem::groupingColor(), hal::GroupingsOfItemModel::GroupingsOfItemModel(), hal::AddToModuleReceiver::handleModulesPicked(), hal::MainWindow::handleSaveAsTriggered(), hal::MainWindow::handleSaveTriggered(), hal::SelectionDetailsWidget::handleSelectionUpdate(), hal::GraphTabWidget::handleTabChanged(), hal::ModuleSelectPicker::ModuleSelectPicker(), hal::ModuleWidget::openModuleInView(), hal::StandardGraphicsGate::paint(), hal::SelectionDetailsWidget::selectionToGroupingAction(), hal::GroupingColorSerializer::serialize(), hal::PythonSerializer::serialize(), hal::PythonSerializer::serialize_control(), hal::GateSelectPicker::terminatePicker(), hal::ModuleSelectPicker::terminatePicker(), and hal::GraphContext::writeToFile().
gFileStatusManager
FileStatusManager * hal::gFileStatusManager = nullptr
The global FileStatusManager (see doc)
Definition at line 56 of file plugin_gui.cpp.
Referenced by hal::PythonEditor::discardTab(), hal::UserAction::exec(), hal::PythonEditor::handleTabFileChanged(), hal::PythonEditor::handleTextChanged(), hal::FileManager::importFile(), hal::FileManager::newProject(), hal::PythonEditor::saveFile(), and hal::PythonEditor::tabLoadFile().
gGraphContextManager
GraphContextManager * hal::gGraphContextManager = nullptr
The global GraphContextManager (see doc)
Definition at line 57 of file plugin_gui.cpp.
Referenced by hal::ContextManagerWidget::ContextManagerWidget(), hal::ActionDeleteObject::exec(), hal::ActionSetObjectColor::exec(), hal::ActionCreateObject::exec(), hal::ActionRenameObject::exec(), hal::ActionUnfoldModule::exec(), hal::ActionFoldModule::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionAddItemsToObject::exec(), hal::ActionMoveNode::exec(), hal::GraphicsScene::GraphicsScene(), hal::GraphTabWidget::GraphTabWidget(), hal::PythonEditor::handleActionRun(), hal::ContentManager::handleOpenDocument(), hal::PythonEditor::handleThreadFinished(), hal::ModuleWidget::openModuleInView(), hal::StandardGraphicsGate::paint(), hal::GraphContextSerializer::restore(), hal::GraphContextManager::restoreFromFile(), and hal::GraphContextSerializer::serialize().
gGuiApi
GuiApi * hal::gGuiApi = nullptr
The global GuiApi (see doc)
Definition at line 58 of file plugin_gui.cpp.
Referenced by hal::GraphTabWidget::GraphTabWidget().
gGuiState
QSettings * hal::gGuiState = nullptr
Is used to persist the list of recent files and the previously opened file in the 'open file' dialog
Definition at line 49 of file plugin_gui.cpp.
Referenced by hal::MainWindow::handleActionImportNetlist().
gNetlist
Netlist * hal::gNetlist = nullptr
The netlist that is currently loaded. It is a pointer to the netlist owned by gNetlistOwner.
Definition at line 52 of file plugin_gui.cpp.
Referenced by hal::PluginParameterDialog::accept(), hal::PhysicalGraphLayouter::add(), hal::WaitToBeSeatedList::add(), hal::NodeBoxes::addBox(), hal::NetlistRelay::addChildModule(), hal::ModuleModel::addModule(), hal::ModuleSelectModel::appendEntries(), hal::ModuleItem::appendExistingChildIfAny(), hal::FileManager::autosave(), hal::SelectionTreeItemModule::boxType(), hal::SelectionTreeItemGate::boxType(), hal::NetlistRelay::changeModuleColor(), hal::NetlistRelay::changeModuleName(), hal::NetlistRelay::changeModuleType(), hal::FileManager::closeFile(), hal::GroupingTableModel::colorForItem(), hal::CommonSuccessorPredecessor::CommonSuccessorPredecessor(), hal::NetlistRelay::debugHandleFileOpened(), hal::FileManager::deprecatedOpenFile(), hal::GuiApi::deselectGate(), hal::GuiApi::deselectModule(), hal::GuiApi::deselectNet(), hal::ModulePinsTreeModel::dropMimeData(), hal::ActionSetObjectData::exec(), hal::ActionDeleteObject::exec(), hal::ActionAddBooleanFunction::exec(), hal::ActionSetObjectType::exec(), hal::ActionSetObjectColor::exec(), hal::ActionCreateObject::exec(), hal::ActionRenameObject::exec(), hal::ActionUnfoldModule::exec(), hal::ActionFoldModule::exec(), hal::ActionReorderObject::exec(), hal::ActionRemoveItemsFromObject::exec(), hal::ActionAddItemsToObject::exec(), hal::ExportRegisteredFormat::exportNetlist(), hal::GraphContext::foldModuleAction(), hal::CoordinateFromData::fromNode(), hal::GateSelectModel::GateSelectModel(), hal::SelectionDetailsIconProvider::getIcon(), hal::GraphContext::getModuleChildrenRecursively(), hal::ModulePinsTreeModel::getNetFromItem(), hal::GatePinsTreeModel::getNumberOfDisplayedPins(), hal::GuiApi::getSelectedGates(), hal::GuiApi::getSelectedModules(), hal::GuiApi::getSelectedNets(), hal::GroupingTableEntry::GroupingTableEntry(), hal::GroupingTableModel::GroupingTableModel(), hal::SelectionDetailsWidget::groupingUnassignActionFactory(), hal::MainWindow::handleActionExport(), hal::MainWindow::handleActionImportNetlist(), hal::MainWindow::handleActionNew(), hal::MainWindow::handleActionOpenProject(), hal::NetEndpointTable::handleContextMenuRequested(), hal::GatePinTree::handleContextMenuRequested(), hal::ModulePinsTree::handleContextMenuRequested(), hal::PythonGateSelectionReceiver::handleGatesPicked(), hal::ModuleTableModel::handleModulePortsChanged(), hal::ModuleTableModel::handleModuleRemoved(), hal::AddToModuleReceiver::handleModulesPicked(), hal::PythonModuleSelectionReceiver::handleModulesPicked(), hal::GateSelectPicker::handleSelectionChanged(), hal::ModuleSelectPicker::handleSelectionChanged(), hal::GraphGraphicsView::handleShortestPath(), hal::ModuleWidget::handleTreeViewContextMenuRequested(), hal::FileManager::importFile(), hal::ModuleModel::init(), hal::GraphContext::isModuleUnfolded(), hal::GraphContext::isShowingNetDestination(), hal::GraphContext::isShowingNetSource(), hal::NetlistElementsTreeModel::moduleGateAssigned(), hal::NetlistElementsTreeModel::moduleGateRemoved(), hal::ModulePinsTreeModel::ModulePinsTreeModel(), hal::NetlistElementsTreeModel::moduleSubmoduleAdded(), hal::NetlistElementsTreeModel::moduleSubmoduleRemoved(), hal::GatePinTree::mouseDoubleClickEvent(), hal::SelectionTreeItemModule::name(), hal::SelectionTreeItemGate::name(), hal::SelectionTreeItemNet::name(), hal::SelectionRelay::navigateDown(), hal::SelectionRelay::navigateUp(), hal::FileManager::newProject(), hal::NodeBox::NodeBox(), hal::GraphContext::nodeForGate(), hal::ModuleWidget::openModuleInView(), hal::FileManager::openProject(), hal::PyCodeProvider::pyCodeGateAsyncSetResetBehavior(), hal::GraphContext::readFromFile(), hal::NetlistRelay::registerNetlistCallbacks(), hal::ModuleModel::remove_module(), hal::GroupingTableModel::removeRows(), hal::GuiApi::selectGate(), hal::ModuleSelectExclude::selectionToString(), hal::GuiApi::selectModule(), hal::GuiApi::selectNet(), hal::NetlistElementsTreeModel::setContent(), hal::GateInfoTable::setGate(), hal::GatePinTree::setGate(), hal::ModuleInfoTable::setModule(), hal::ModuleElementsTree::setModule(), hal::ModulePinsTree::setModule(), hal::NetEndpointTable::setNet(), hal::NetModuleTable::setNet(), hal::NetInfoTable::setNet(), hal::ModuleTableModel::setNet(), hal::GraphNavigationWidget::setup(), hal::GraphContext::unfoldModule(), hal::NetlistRelay::unregisterNetlistCallbacks(), hal::ModuleShader::update(), hal::ModuleModel::updateModule(), and hal::GraphContext::updateNets().
gNetlistOwner
std::shared_ptr< Netlist > hal::gNetlistOwner = nullptr
This shared_ptr contains and owns the netlist after a file was opened. To access the Netlist data structure with its functions, it is intended to use the raw pointer gNetlist instead.
Definition at line 51 of file plugin_gui.cpp.
Referenced by hal::FileManager::closeFile(), hal::FileManager::deprecatedOpenFile(), hal::FileManager::newProject(), and hal::FileManager::openProject().
gNetlistRelay
NetlistRelay * hal::gNetlistRelay = nullptr
The global NetlistRelay (see doc)
Definition at line 53 of file plugin_gui.cpp.
Referenced by hal::FileManager::closeFile(), hal::GraphicsScene::connectAll(), hal::ModuleTreeModel::connectEvents(), hal::FileManager::deprecatedOpenFile(), hal::GraphicsScene::disconnectAll(), hal::ModuleTreeModel::disconnectEvents(), hal::ActionDeleteObject::exec(), hal::ActionSetObjectColor::exec(), hal::GateDetailsTabWidget::GateDetailsTabWidget(), hal::GateInfoTable::GateInfoTable(), hal::SelectionDetailsIconProvider::getIcon(), hal::GraphContext::GraphContext(), hal::GroupingsOfItemModel::GroupingsOfItemModel(), hal::GroupingTableModel::GroupingTableModel(), hal::ModuleWidget::handleSelectionChanged(), hal::ModuleWidget::handleTreeSelectionChanged(), hal::ModuleWidget::handleTreeViewContextMenuRequested(), hal::ModuleDialog::ModuleDialog(), hal::ModuleInfoTable::ModuleInfoTable(), hal::ModulePinsTreeModel::ModulePinsTreeModel(), hal::ModuleSelectEntry::ModuleSelectEntry(), hal::ModuleTableModel::ModuleTableModel(), hal::ModuleWidget::ModuleWidget(), hal::NetInfoTable::NetInfoTable(), hal::NetlistElementsTreeModel::NetlistElementsTreeModel(), hal::FileManager::newProject(), hal::FileManager::openProject(), hal::SelectionTreeModel::SelectionTreeModel(), hal::ModuleColorSerializer::serialize(), hal::ModuleShader::update(), and hal::ModuleModel::updateModule().
gPluginRelay
PluginRelay * hal::gPluginRelay = nullptr
The global PluginRelay. Plugin management is not available in this version. Therefore it is currently unused.
Definition at line 54 of file plugin_gui.cpp.
gPythonContext
PythonContext * hal::gPythonContext = nullptr
The global PythonContext (see doc)
Definition at line 60 of file plugin_gui.cpp.
Referenced by hal::FileManager::autosave(), hal::PythonEditor::handleActionRun(), hal::MainWindow::handleFileOpened(), hal::PythonConsole::handleTabKeyPressed(), hal::PythonConsole::interpretCommand(), hal::GraphWidget::pluginProgressIndicator(), PYBIND11_PLUGIN(), hal::PythonConsole::PythonConsole(), and hal::PythonConsole::~PythonConsole().
gSelectionRelay
SelectionRelay * hal::gSelectionRelay = nullptr
The global SelectionRelay (see doc)
Definition at line 55 of file plugin_gui.cpp.
Referenced by hal::NetlistRelay::addSelectionToModule(), hal::SelectionTreeProxyModel::applyFilterOnGraphics(), hal::GraphicsScene::connectAll(), hal::GuiApi::deselectAllItems(), hal::GuiApi::deselectGate(), hal::GuiApi::deselectModule(), hal::GuiApi::deselectNet(), hal::GraphicsScene::disconnectAll(), hal::GraphWidget::ensureSelectionVisible(), hal::ActionSetSelectionFocus::exec(), hal::SelectionTreeModel::fetchSelection(), hal::GateSelectPicker::GateSelectPicker(), hal::GuiApi::getSelectedGateIds(), hal::GuiApi::getSelectedGates(), hal::GuiApi::getSelectedModuleIds(), hal::GuiApi::getSelectedModules(), hal::GuiApi::getSelectedNetIds(), hal::GuiApi::getSelectedNets(), hal::GraphGraphicsView::GraphGraphicsView(), hal::GraphicsScene::GraphicsScene(), hal::GroupingManagerWidget::GroupingManagerWidget(), hal::GuiApi::GuiApi(), hal::NetEndpointTable::handleContextMenuRequested(), hal::NetModuleTable::handleContextMenuRequested(), hal::ModuleElementsTree::handleContextMenuRequested(), hal::GatePinTree::handleContextMenuRequested(), hal::ModulePinsTree::handleContextMenuRequested(), hal::GraphicsScene::handleExternSelectionChanged(), hal::GroupingManagerWidget::handleGraphSelectionChanged(), hal::GraphicsScene::handleInternSelectionChanged(), hal::AddToModuleReceiver::handleModulesPicked(), hal::GateSelectPicker::handleSelectionChanged(), hal::ModuleWidget::handleSelectionChanged(), hal::ModuleSelectPicker::handleSelectionChanged(), hal::SelectionDetailsWidget::handleSelectionUpdate(), hal::ModuleWidget::handleTreeSelectionChanged(), hal::ActionSetSelectionFocus::hasModifications(), hal::GraphWidget::keyPressEvent(), hal::ModuleSelectExclude::ModuleSelectExclude(), hal::ModuleSelectPicker::ModuleSelectPicker(), hal::ModuleWidget::ModuleWidget(), hal::StandardGraphicsGate::paint(), hal::StandardGraphicsModule::paint(), hal::GuiApi::select(), hal::GuiApi::selectGate(), hal::SelectionDetailsWidget::SelectionDetailsWidget(), hal::SelectionDetailsWidget::selectionToGroupingAction(), hal::GuiApi::selectModule(), hal::GuiApi::selectNet(), hal::GraphNavigationWidget::setup(), hal::GateSelectPicker::terminatePicker(), and hal::ModuleSelectPicker::terminatePicker().
mGSettings
QSettings* hal::mGSettings = nullptr
Definition at line 48 of file plugin_gui.cpp.
sOpenMethodsPersist
const char* hal::sOpenMethodsPersist[] = {"Undefined", "CreateNew", "ImportFile", "OpenProject", nullptr}
Definition at line 6 of file action_open_netlist_file.cpp.
Referenced by hal::ActionOpenNetlistFile::readFromXml(), and hal::ActionOpenNetlistFile::writeToXml().