HAL: hal::ShortestPath Namespace Reference
hal::ShortestPath Namespace Reference
Functions
const Net * net (const Gate *g0, const Gate *g1)
const Module * module (const Gate *g, const NodeBoxes &boxes)
Function Documentation
module()
const Module* hal::ShortestPath::module (const Gate * g, const NodeBoxes & boxes)
Definition at line 846 of file graph_graphics_view.cpp.
References hal::NodeBoxes::boxForNode(), hal::Module::get_id(), hal::Gate::get_module(), hal::Module::get_parent_module(), and hal::Node::Module.
Referenced by hal::Grouping::assign_module(), hal::Grouping::assign_module_by_id(), hal::SelectionTreeItemModule::boxType(), hal::Grouping::contains_module(), hal::netlist_utils::copy_netlist(), hal::Netlist::delete_module(), hal::GuiApi::deselect(), hal::GuiApi::deselectModule(), hal::GraphWidget::focusModule(), hal::Grouping::get_module_ids(), hal::Grouping::get_modules(), hal::Netlist::get_modules(), hal::Module::get_nets(), hal::event_log::handle_module_event(), hal::GateDetailsWidget::handleModuleGateAssigned(), hal::ModuleDetailsWidget::handleModuleGateAssigned(), hal::GateDetailsWidget::handleModuleGateRemoved(), hal::ModuleDetailsWidget::handleModuleGateRemoved(), hal::ModuleDetailsWidget::handleModuleInputPortNameChanged(), hal::SelectionTreeModel::handleModuleItemChanged(), hal::GateDetailsWidget::handleModuleNameChanged(), hal::ModuleDetailsWidget::handleModuleNameChanged(), hal::ModuleDetailsWidget::handleModuleOutputPortNameChanged(), hal::GateDetailsWidget::handleModuleRemoved(), hal::ModuleWidget::handleModuleRemoved(), hal::ModuleDetailsWidget::handleModuleTypeChanged(), hal::ModuleDetailsWidget::handleNetDestinationAdded(), hal::ModuleDetailsWidget::handleNetDestinationRemoved(), hal::ModuleDetailsWidget::handleNetlistMarkedGlobalInout(), hal::ModuleDetailsWidget::handleNetlistMarkedGlobalInput(), hal::ModuleDetailsWidget::handleNetlistMarkedGlobalOutput(), hal::ModuleDetailsWidget::handleNetlistUnmarkedGlobalInout(), hal::ModuleDetailsWidget::handleNetlistUnmarkedGlobalInput(), hal::ModuleDetailsWidget::handleNetlistUnmarkedGlobalOutput(), hal::ModuleDetailsWidget::handleNetNameChanged(), hal::ModuleDetailsWidget::handleNetSourceAdded(), hal::ModuleDetailsWidget::handleNetSourceRemoved(), hal::GraphGraphicsView::handleShortestPath(), hal::ModuleDetailsWidget::handleSubmoduleAdded(), hal::ModuleDetailsWidget::handleSubmoduleRemoved(), hal::ModuleWidget::handleTreeViewContextMenuRequested(), hal::Netlist::is_module_in_netlist(), hal::module_init(), hal::SelectionTreeItemModule::name(), hal::EventHandler::notify(), hal::ModuleWidget::openModuleInView(), hal::PYBIND11_PLUGIN(), hal::Grouping::remove_module(), hal::Grouping::remove_module_by_id(), hal::GuiApi::select(), and hal::GuiApi::selectModule().
net()
const Net* hal::ShortestPath::net (const Gate * g0, const Gate * g1)
Definition at line 837 of file graph_graphics_view.cpp.
References hal::Gate::get_fan_in_nets(), and hal::Gate::get_fan_out_nets().
Referenced by hal::Grouping::assign_net(), hal::Grouping::assign_net_by_id(), hal::Grouping::contains_net(), hal::netlist_utils::copy_netlist(), hal::GuiApi::deselect(), hal::GuiApi::deselectNet(), hal::ActionDeleteObject::exec(), hal::ActionRenameObject::exec(), hal::GraphWidget::focusNet(), hal::Module::get_input_nets(), hal::Module::get_input_port_name(), hal::Module::get_input_port_names(), hal::Module::get_input_port_net(), hal::Module::get_internal_nets(), hal::Grouping::get_net_ids(), hal::Module::get_nets(), hal::Grouping::get_nets(), hal::Netlist::get_nets(), hal::netlist_utils::get_nets_at_pins(), hal::netlist_utils::get_next_sequential_gates(), hal::Module::get_output_nets(), hal::Module::get_output_port_name(), hal::Module::get_output_port_names(), hal::Module::get_output_port_net(), hal::netlist_utils::get_partial_netlist(), hal::netlist_utils::get_path(), hal::netlist_utils::get_subgraph_function(), hal::SelectionDetailsWidget::groupingUnassignActionFactory(), hal::event_log::handle_grouping_event(), hal::event_log::handle_net_event(), hal::event_log::handle_netlist_event(), hal::GraphContextManager::handleModuleInputPortNameChanged(), hal::GraphContextManager::handleModuleOutputPortNameChanged(), hal::GateDetailsWidget::handleNetDestinationAdded(), hal::ModuleDetailsWidget::handleNetDestinationAdded(), hal::GateDetailsWidget::handleNetDestinationRemoved(), hal::ModuleDetailsWidget::handleNetDestinationRemoved(), hal::ModuleDetailsWidget::handleNetlistMarkedGlobalInout(), hal::ModuleDetailsWidget::handleNetlistMarkedGlobalInput(), hal::ModuleDetailsWidget::handleNetlistMarkedGlobalOutput(), hal::ModuleDetailsWidget::handleNetlistUnmarkedGlobalInout(), hal::ModuleDetailsWidget::handleNetlistUnmarkedGlobalInput(), hal::ModuleDetailsWidget::handleNetlistUnmarkedGlobalOutput(), hal::GateDetailsWidget::handleNetNameChanged(), hal::ModuleDetailsWidget::handleNetNameChanged(), hal::GateDetailsWidget::handleNetSourceAdded(), hal::ModuleDetailsWidget::handleNetSourceAdded(), hal::GateDetailsWidget::handleNetSourceRemoved(), hal::ModuleDetailsWidget::handleNetSourceRemoved(), hal::GraphGraphicsView::handleShortestPath(), hal::GraphContext::isShowingNetDestination(), hal::GraphContext::isShowingNetSource(), hal::SelectionTreeItemNet::name(), hal::net_init(), hal::EventHandler::notify(), hal::Module::operator==(), hal::Netlist::operator==(), hal::Grouping::remove_net(), hal::Grouping::remove_net_by_id(), hal::GuiApi::select(), hal::GuiApi::selectNet(), and hal::ModuleDetailsWidget::update().