HAL: subprocess Namespace Reference
subprocess Namespace Reference
Namespaces
detail
util
Classes
class Buffer
struct bufsize
class CalledProcessError
struct close_fds
struct cwd
struct defer_spawn
struct environment
struct error
struct executable
struct input
class OSError
struct output
class Popen
class preexec_func
struct session_leader
struct shell
struct string_arg
Typedefs
using env_string_t = std::string
using env_char_t = char
using env_map_t = std::map< env_string_t, env_string_t >
using env_vector_t = std::vector< env_char_t >
using OutBuffer = Buffer
using ErrBuffer = Buffer
Enumerations
enum IOTYPE { STDOUT = 1, STDERR, PIPE }
Functions
template<typename... Args>
int call (std::initializer_list< const char * > plist, Args &&... args)
template<typename... Args>
int call (const std::string &arg, Args &&... args)
template<typename... Args>
OutBuffer check_output (std::initializer_list< const char * > plist, Args &&... args)
template<typename... Args>
OutBuffer check_output (const std::string &arg, Args &&... args)
template<typename... Args>
OutBuffer check_output (std::vector< std::string > plist, Args &&... args)
template<typename... Args>
OutBuffer pipeline (Args &&... args)
Detailed Description
Documentation for C++ subprocessing libraray.
Copyright
The code is licensed under the MIT License:
Copyright © 2016-2018 Arun Muralidharan.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Author
[Arun Muralidharan]
See also
https://github.com/arun11299/cpp-subprocess to download the source code
Version
1.0.0
Getting started with reading this source code. The source is mainly divided into four parts:
Exception Classes: These are very basic exception classes derived from runtime_error exception. There are two types of exception thrown from subprocess library: OSError and CalledProcessError
Popen Class This is the main class the users will deal with. It provides with all the API's to deal with processes.
Util namespace It includes some helper functions to split/join a string, reading from file descriptors, waiting on a process, fcntl options on file descriptors etc.
Detail namespace This includes some metaprogramming and helper classes.
Typedef Documentation
env_char_t
using subprocess::env_char_t = typedef char
Definition at line 155 of file process.h.
env_map_t
using subprocess::env_map_t = typedef std::map<env_string_t, env_string_t>
Definition at line 160 of file process.h.
env_string_t
using subprocess::env_string_t = typedef std::string
Definition at line 154 of file process.h.
env_vector_t
using subprocess::env_vector_t = typedef std::vector<env_char_t>
Definition at line 161 of file process.h.
ErrBuffer
using subprocess::ErrBuffer = typedef Buffer
Definition at line 950 of file process.h.
OutBuffer
using subprocess::OutBuffer = typedef Buffer
Definition at line 948 of file process.h.
Enumeration Type Documentation
IOTYPE
enum subprocess::IOTYPE
Used for redirecting input/output/error
Enumerator
STDOUT
STDERR
PIPE
Definition at line 754 of file process.h.
Function Documentation
call() [1/2]
template<typename... Args> int subprocess::call (const std::string & arg, Args &&... args)
Definition at line 2038 of file process.h.
References control::args, and subprocess::detail::call_impl().
call() [2/2]
template<typename... Args> int subprocess::call (std::initializer_list< const char * > plist, Args &&... args)
Run the command with arguments and wait for it to complete. The parameters passed to the argument are exactly the same one would use for Popen constructors.
Definition at line 2032 of file process.h.
References control::args, and subprocess::detail::call_impl().
Referenced by hal::CallbackHook< R(ArgTypes...)>::call().
check_output() [1/3]
template<typename... Args> OutBuffer subprocess::check_output (const std::string & arg, Args &&... args)
Definition at line 2056 of file process.h.
References control::args, and subprocess::detail::check_output_impl().
check_output() [2/3]
template<typename... Args> OutBuffer subprocess::check_output (std::initializer_list< const char * > plist, Args &&... args)
Run the command with arguments and wait for it to complete. If the exit code was non-zero it raises a CalledProcessError. The arguments are the same as for the Popen constructor.
Definition at line 2050 of file process.h.
References control::args, and subprocess::detail::check_output_impl().
check_output() [3/3]
template<typename... Args> OutBuffer subprocess::check_output (std::vector< std::string > plist, Args &&... args)
Definition at line 2062 of file process.h.
References control::args, and subprocess::detail::check_output_impl().
pipeline()
template<typename... Args> OutBuffer subprocess::pipeline (Args &&... args)
An easy way to pipeline easy commands. Provide the commands that needs to be pipelined in the order they would appear in a regular command. It would wait for the last command provided in the pipeline to finish and then return the OutBuffer.
Definition at line 2077 of file process.h.
References control::args.