HAL: hal::core_strings Namespace Reference
hal::core_strings Namespace Reference
Classes
struct CaseInsensitiveCharTraits
Typedefs
using CaseInsensitiveString = std::basic_string< char, CaseInsensitiveCharTraits >
Functions
template<class S , class T >
S to (const T &str)
Typedef Documentation
CaseInsensitiveString
using hal::core_strings::CaseInsensitiveString = typedef std::basic_string<char, CaseInsensitiveCharTraits>
Definition at line 143 of file special_strings.h.
Function Documentation
to()
template<class S , class T > S hal::core_strings::to (const T & str) inline
Convert one kind of string into another kind of string.
Template Parameters
S - The output string type.
T - The input string type.
Parameters
str - The string to convert.
Returns
The converted string.
Definition at line 46 of file special_strings.h.
References control::str.
Referenced by hal::gui_utility::changeAllSvgColors(), hal::gui_utility::changeSvgColor(), hal::GraphContext::moveNodeAction(), hal::ArrowSeparatedNet::paint(), and hal::CircleSeparatedNet::paint().