HAL: hal::dataflow::utils Namespace Reference
hal::dataflow::utils Namespace Reference
Functions
template<typename R >
void parallel_for_each (u32 begin, u32 end, R func)
template<typename T , typename R >
void parallel_for_each (const std::vector< T > &elements, R func)
template<typename T , typename R >
void parallel_for_each (const std::set< T > &elements, R func)
template<typename T , typename R >
void parallel_for_each (const std::unordered_set< T > &elements, R func)
Function Documentation
parallel_for_each() [1/4]
template<typename T , typename R > void hal::dataflow::utils::parallel_for_each (const std::set< T > & elements, R func)
Definition at line 90 of file parallel_for_each.h.
References parallel_for_each().
parallel_for_each() [2/4]
template<typename T , typename R > void hal::dataflow::utils::parallel_for_each (const std::unordered_set< T > & elements, R func)
Definition at line 99 of file parallel_for_each.h.
References parallel_for_each().
parallel_for_each() [3/4]
template<typename T , typename R > void hal::dataflow::utils::parallel_for_each (const std::vector< T > & elements, R func)
Definition at line 84 of file parallel_for_each.h.
References parallel_for_each().
parallel_for_each() [4/4]
template<typename R > void hal::dataflow::utils::parallel_for_each (u32 begin, u32 end, R func)
Definition at line 42 of file parallel_for_each.h.
Referenced by parallel_for_each().