HAL: hal::hal_file_manager Namespace Reference
hal::hal_file_manager Namespace Reference
HAL Core » Utilities
Functions
bool serialize (const std::filesystem::path &file, Netlist *netlist, rapidjson::Document &document)
bool deserialize (const std::filesystem::path &file, Netlist *netlist, rapidjson::Document &document)
void register_on_serialize_callback (const std::string &identifier, std::function< bool(const std::filesystem::path &, Netlist *netlist, rapidjson::Document &)> callback)
void unregister_on_serialize_callback (const std::string &identifier)
void register_on_deserialize_callback (const std::string &identifier, std::function< bool(const std::filesystem::path &, Netlist *netlist, rapidjson::Document &)> callback)
void unregister_on_deserialize_callback (const std::string &identifier)
void register_on_serialize_callback (const std::string &identifier, std::function< bool(const std::filesystem::path &, Netlist *, rapidjson::Document &)> callback)
void register_on_deserialize_callback (const std::string &identifier, std::function< bool(const std::filesystem::path &, Netlist *, rapidjson::Document &)> callback)
Detailed Description
Plugin manager to load and unload plugins
Function Documentation
deserialize()
bool hal::hal_file_manager::deserialize (const std::filesystem::path & file, Netlist * netlist, rapidjson::Document & document)
Starts deserialization of a .hal file.
This fires all registered on_deserialize callbacks.
Parameters
[in] file - The file path.
[in,out] netlist - The netlist to be obtained
[in] document - The JSON document to deserialize from.
Returns
True if all registered callbacks succeed.
Definition at line 40 of file hal_file_manager.cpp.
References file, and log_error.
Referenced by hal::netlist_serializer::deserialize_from_file().
register_on_deserialize_callback() [1/2]
void hal::hal_file_manager::register_on_deserialize_callback (const std::string & identifier, std::function< bool(const std::filesystem::path &, Netlist *, rapidjson::Document &)> callback)
Add a callback to notify when a .hal file is being deserialized.
Parameters
[in] identifier - An identifier name that can be used to remove the callback later.
[in] callback - The callback function. Parameters are:
bool - Returns whether data was successfully read, loading is aborted if False.
const std::filesystem::path& - The hal file.
rapidjson::Document& - The content to fill.
register_on_deserialize_callback() [2/2]
void hal::hal_file_manager::register_on_deserialize_callback (const std::string & identifier, std::function< bool(const std::filesystem::path &, Netlist *netlist, rapidjson::Document &)> callback)
Definition at line 63 of file hal_file_manager.cpp.
Referenced by hal::PythonEditor::PythonEditor().
register_on_serialize_callback() [1/2]
void hal::hal_file_manager::register_on_serialize_callback (const std::string & identifier, std::function< bool(const std::filesystem::path &, Netlist *, rapidjson::Document &)> callback)
Add a callback to notify when a .hal file is being serialized.
Parameters
[in] identifier - An identifier name that can be used to remove the callback later.
[in] callback - The callback function. Parameters are:
bool - Returns whether data was successfully extended, saving is aborted if False.
const std::filesystem::path& - The hal file.
rapidjson::Document& - The content to fill.
register_on_serialize_callback() [2/2]
void hal::hal_file_manager::register_on_serialize_callback (const std::string & identifier, std::function< bool(const std::filesystem::path &, Netlist *netlist, rapidjson::Document &)> callback)
Definition at line 53 of file hal_file_manager.cpp.
Referenced by hal::PythonEditor::PythonEditor().
serialize()
bool hal::hal_file_manager::serialize (const std::filesystem::path & file, Netlist * netlist, rapidjson::Document & document)
Starts serialization to a .hal file.
This fires all registered on_serialize callbacks.
Parameters
[in] file - The file path.
[in] netlist - The netlist to be serialized
[in] document - The JSON document to serialize to.
Returns
True if all registered callbacks succeed.
Definition at line 27 of file hal_file_manager.cpp.
References file, and log_error.
Referenced by hal::netlist_serializer::serialize_to_file().
unregister_on_deserialize_callback()
void hal::hal_file_manager::unregister_on_deserialize_callback (const std::string & identifier)
Removes a callback to notify when a .hal file is being deserialized.
Parameters
[in] identifier - The identifier name given while registering
Definition at line 68 of file hal_file_manager.cpp.
Referenced by hal::PythonEditor::~PythonEditor().
unregister_on_serialize_callback()
void hal::hal_file_manager::unregister_on_serialize_callback (const std::string & identifier)
Removes a callback to notify when a .hal file is being serialized.
Parameters
[in] identifier - The identifier name given while registering
Definition at line 58 of file hal_file_manager.cpp.
Referenced by hal::PythonEditor::~PythonEditor().