HAL: hal::dataflow::pre_processing Namespace Reference
hal::dataflow::pre_processing Namespace Reference
Functions
NetlistAbstraction run (const dataflow::Configuration &config, std::shared_ptr< dataflow::Grouping > &initial_grouping)
void identify_register_stages (NetlistAbstraction &netlist_abstr)
Function Documentation
identify_register_stages()
void hal::dataflow::pre_processing::identify_register_stages (NetlistAbstraction & netlist_abstr)
Definition at line 24 of file register_stage_identification.cpp.
References hal::dataflow::ProgressPrinter::clear(), test_plugin::g, hal::dataflow::NetlistAbstraction::gate_to_predecessors, hal::dataflow::NetlistAbstraction::gate_to_register_stages, hal::dataflow::NetlistAbstraction::gate_to_successors, log_info, measure_block_time, name, hal::dataflow::ProgressPrinter::print_progress(), and hal::dataflow::NetlistAbstraction::target_gates.
Referenced by run().
run()
NetlistAbstraction hal::dataflow::pre_processing::run (const dataflow::Configuration & config, std::shared_ptr< dataflow::Grouping > & initial_grouping)
Definition at line 320 of file pre_processing.cpp.
References hal::dataflow::Configuration::enable_stages, identify_register_stages(), log_info, measure_block_time, and hal::dataflow::Configuration::netlist.
Referenced by hal::dataflow::analyze().