HAL: hal::event_log Namespace Reference
hal::event_log Namespace Reference
Functions
void enable_event_log (bool enable)
void handle_gate_event (GateEvent::event event, Gate *gate, u32 associated_data)
void handle_net_event (NetEvent::event event, Net *net, u32 associated_data)
void handle_netlist_event (NetlistEvent::event event, Netlist *netlist, u32 associated_data)
void handle_grouping_event (GroupingEvent::event event, Grouping *grp, u32 associated_data)
void handle_module_event (ModuleEvent::event event, Module *module, u32 associated_data)
Function Documentation
enable_event_log()
NETLIST_API void hal::event_log::enable_event_log (bool enable)
enable event log
Parameters
[in] enable - enable logging for all event types
Definition at line 20 of file event_log.cpp.
References hal::enable.
handle_gate_event()
NETLIST_API void hal::event_log::handle_gate_event (GateEvent::event event, Gate * gate, u32 associated_data)
dump gate events to hal log
Parameters
[in] event - gate event
[in] gate - pointer to gate
[in] associated_data - additional data
Definition at line 25 of file event_log.cpp.
References hal::GateEvent::created, hal::Gate::get_id(), hal::Gate::get_name(), hal::GateType::get_name(), hal::Gate::get_type(), log_error, log_info, hal::GateEvent::name_changed, hal::GateEvent::removed, and UNUSED.
Referenced by hal::EventHandler::notify().
handle_grouping_event()
NETLIST_API void hal::event_log::handle_grouping_event (GroupingEvent::event event, Grouping * grp, u32 associated_data)
dump grouping events to hal log
Parameters
[in] event - grouping event
[in] grp - pointer to grouping
[in] associated_data - additional data
Definition at line 156 of file event_log.cpp.
References hal::GroupingEvent::color_changed, hal::GroupingEvent::created, hal::GroupingEvent::gate_assigned, hal::GroupingEvent::gate_removed, hal::Grouping::get_color(), hal::Netlist::get_gate_by_id(), hal::Grouping::get_id(), hal::Net::get_id(), hal::Module::get_id(), hal::Gate::get_id(), hal::Netlist::get_module_by_id(), hal::Grouping::get_name(), hal::Module::get_name(), hal::Net::get_name(), hal::Gate::get_name(), hal::Netlist::get_net_by_id(), hal::Grouping::get_netlist(), log_error, log_info, hal::GroupingEvent::module_assigned, hal::GroupingEvent::module_removed, hal::GroupingEvent::name_changed, hal::ShortestPath::net(), hal::GroupingEvent::net_assigned, hal::GroupingEvent::net_removed, hal::GroupingEvent::removed, and hal::utils::Color::toString().
Referenced by hal::EventHandler::notify().
handle_module_event()
NETLIST_API void hal::event_log::handle_module_event (ModuleEvent::event event, Module * module, u32 associated_data)
dump module events to hal log
Parameters
[in] event - module event
[in] module - pointer to module
[in] associated_data - additional data
Definition at line 212 of file event_log.cpp.
References hal::ModuleEvent::created, hal::ModuleEvent::gate_assigned, hal::ModuleEvent::gate_removed, hal::Netlist::get_gate_by_id(), hal::Module::get_id(), hal::Netlist::get_module_by_id(), hal::Module::get_name(), hal::Module::get_netlist(), hal::Module::get_parent_module(), hal::Module::get_type(), hal::ModuleEvent::input_port_name_changed, log_error, log_info, hal::ShortestPath::module(), hal::ModuleEvent::name_changed, hal::ModuleEvent::output_port_name_changed, hal::ModuleEvent::parent_changed, hal::ModuleEvent::removed, hal::ModuleEvent::submodule_added, hal::ModuleEvent::submodule_removed, and hal::ModuleEvent::type_changed.
Referenced by hal::EventHandler::notify().
handle_net_event()
NETLIST_API void hal::event_log::handle_net_event (NetEvent::event event, Net * net, u32 associated_data)
dump net events to hal log
Parameters
[in] event - net event
[in] net - pointer to net
[in] associated_data - additional data
Definition at line 48 of file event_log.cpp.
References hal::NetEvent::created, hal::NetEvent::dst_added, hal::NetEvent::dst_removed, hal::Netlist::get_gate_by_id(), hal::Net::get_id(), hal::Net::get_name(), hal::Net::get_netlist(), log_error, log_info, hal::NetEvent::name_changed, hal::ShortestPath::net(), hal::NetEvent::removed, hal::NetEvent::src_added, and hal::NetEvent::src_removed.
Referenced by hal::EventHandler::notify().
handle_netlist_event()
NETLIST_API void hal::event_log::handle_netlist_event (NetlistEvent::event event, Netlist * netlist, u32 associated_data)
dump netlist events to hal log
Parameters
[in] event - netlist event
[in] netlist - pointer to netlist
[in] associated_data - additional data
Definition at line 90 of file event_log.cpp.
References hal::NetlistEvent::design_name_changed, hal::NetlistEvent::device_name_changed, hal::Net::get_id(), hal::Net::get_name(), hal::NetlistEvent::id_changed, hal::NetlistEvent::input_filename_changed, log_error, log_info, hal::NetlistEvent::marked_global_gnd, hal::NetlistEvent::marked_global_input, hal::NetlistEvent::marked_global_output, hal::NetlistEvent::marked_global_vcc, hal::ShortestPath::net(), test_plugin::netlist, hal::NetlistEvent::unmarked_global_gnd, hal::NetlistEvent::unmarked_global_input, hal::NetlistEvent::unmarked_global_output, and hal::NetlistEvent::unmarked_global_vcc.
Referenced by hal::EventHandler::notify().