HAL: hal::netlist_factory Namespace Reference
hal::netlist_factory Namespace Reference
Functions
std::unique_ptr< Netlist > create_netlist (const GateLibrary *gate_library)
std::unique_ptr< Netlist > load_netlist (const std::filesystem::path &netlist_file, const std::filesystem::path &gate_library_file)
std::unique_ptr< Netlist > load_hal_project (const std::filesystem::path &project_dir)
std::unique_ptr< Netlist > load_netlist (const ProjectDirectory &pdir, const ProgramArguments &args)
std::vector< std::unique_ptr< Netlist > > load_netlists (const std::filesystem::path &netlist_file)
Function Documentation
create_netlist()
NETLIST_API std::unique_ptr< Netlist > hal::netlist_factory::create_netlist (const GateLibrary * gate_library)
Create a new empty netlist using the specified gate library.
Parameters
[in] gate_library - The gate library.
Returns
The netlist on success, nullptr otherwise.
Definition at line 19 of file netlist_factory.cpp.
References log_critical.
Referenced by hal::SubgraphNetlistDecorator::copy_subgraph_netlist(), hal::VerilogParser::instantiate(), hal::VHDLParser::instantiate(), hal::netlist_factory_init(), and hal::FileManager::newProject().
load_hal_project()
NETLIST_API std::unique_ptr< Netlist > hal::netlist_factory::load_hal_project (const std::filesystem::path & project_dir)
Create a netlist from the given hal project.
Parameters
[in] project_dir - Path to the hal project directory.
Returns
The netlist on success, nullptr otherwise.
Definition at line 65 of file netlist_factory.cpp.
References hal::ProjectManager::get_netlist(), hal::ProjectManager::instance(), log_critical, and hal::ProjectManager::open_project().
Referenced by hal::netlist_factory_init().
load_netlist() [1/2]
NETLIST_API std::unique_ptr< Netlist > hal::netlist_factory::load_netlist (const ProjectDirectory & pdir, const ProgramArguments & args)
Create a netlist using information specified in command line arguments on startup.
Invokes parsers or serializers as needed.
Parameters
[in] pdir - The HAL project directory.
[in] args - Command line arguments.
Returns
The netlist on success, nullptr otherwise.
Definition at line 84 of file netlist_factory.cpp.
References control::args, hal::netlist_serializer::deserialize_from_file(), hal::ProjectDirectory::get_default_filename(), log_critical, and hal::netlist_parser_manager::parse().
load_netlist() [2/2]
NETLIST_API std::unique_ptr< Netlist > hal::netlist_factory::load_netlist (const std::filesystem::path & netlist_file, const std::filesystem::path & gate_library_file = std::filesystem::path())
Create a netlist from the given file. Will either deserialize '.hal' file or call parser plugin for other formats. In the latter case the specified gate library file is mandatory.
Parameters
[in] netlist_file - Path to the netlist file.
[in] gate_library_file - Path to the gate library file. Optional argument for '.hal' file.
Returns
The netlist on success, nullptr otherwise.
Definition at line 30 of file netlist_factory.cpp.
References hal::netlist_serializer::deserialize_from_file(), hal::gate_library_manager::load(), log_critical, and hal::netlist_parser_manager::parse().
Referenced by hal::FileManager::deprecatedOpenFile(), and hal::netlist_factory_init().
load_netlists()
NETLIST_API std::vector< std::unique_ptr< Netlist > > hal::netlist_factory::load_netlists (const std::filesystem::path & netlist_file)
Create a netlist from a given file for each matching pre-loaded gate library.
Parameters
[in] netlist_file - Path to the netlist file.
Returns
A vector of netlists.
Definition at line 106 of file netlist_factory.cpp.
References log_critical, and hal::netlist_parser_manager::parse_all().
Referenced by hal::FileManager::deprecatedOpenFile(), and hal::netlist_factory_init().