HAL: hal::netlist_utils Namespace Reference
hal::netlist_utils Namespace Reference
HAL Core » Netlist
Functions
BooleanFunction get_subgraph_function (const Net *net, const std::vector< const Gate * > &subgraph_gates, std::unordered_map< u32, BooleanFunction > &cache)
BooleanFunction get_subgraph_function (const Net *net, const std::vector< const Gate * > &subgraph_gates)
std::unique_ptr< Netlist > copy_netlist (const Netlist *nl)
std::pair< std::map< u32, Gate * >, std::vector< std::vector< int > > > get_ff_dependency_matrix (const Netlist *nl)
std::unique_ptr< Netlist > get_partial_netlist (const Netlist *nl, const std::vector< Gate * > &subgraph_gates)
std::vector< Gate * > get_next_gates (const Gate *gate, bool get_successors, int depth, const std::function< bool(const Gate *)> &filter)
std::vector< Gate * > get_shortest_path (Gate *start_gate, Gate *end_gate, bool search_both_directions)
std::vector< Gate * > get_next_sequential_gates (const Gate *gate, bool get_successors, std::unordered_map< u32, std::vector< Gate * >> &cache)
std::vector< Gate * > get_next_sequential_gates (const Net *net, bool get_successors, std::unordered_map< u32, std::vector< Gate * >> &cache)
std::vector< Gate * > get_next_sequential_gates (const Gate *gate, bool get_successors)
std::vector< Gate * > get_next_sequential_gates (const Net *net, bool get_successors)
std::vector< Gate * > get_path (const Gate *gate, bool get_successors, std::set< GateTypeProperty > stop_properties, std::unordered_map< u32, std::vector< Gate * >> &cache)
std::vector< Gate * > get_path (const Net *net, bool get_successors, std::set< GateTypeProperty > stop_properties, std::unordered_map< u32, std::vector< Gate * >> &cache)
std::vector< Gate * > get_path (const Gate *gate, bool get_successors, std::set< GateTypeProperty > stop_properties)
std::vector< Gate * > get_path (const Net *net, bool get_successors, std::set< GateTypeProperty > stop_properties)
std::unordered_set< Net * > get_nets_at_pins (Gate *gate, std::unordered_set< std::string > pins, bool is_inputs)
void remove_buffers (Netlist *netlist, bool analyze_inputs)
void remove_unused_lut_endpoints (Netlist *netlist)
void rename_luts_according_to_function (Netlist *netlist)
std::vector< Net * > get_common_inputs (const std::vector< Gate * > &gates, u32 threshold)
bool replace_gate (Gate *gate, GateType *target_type, std::map< std::string, std::string > pin_map)
std::vector< Gate * > get_gate_chain (Gate *start_gate, const std::set< std::string > &input_pins, const std::set< std::string > &output_pins, const std::function< bool(const Gate *)> &filter)
std::vector< Gate * > get_complex_gate_chain (Gate *start_gate, const std::vector< GateType * > &chain_types, const std::map< GateType *, std::set< std::string >> &input_pins, const std::map< GateType *, std::set< std::string >> &output_pins, const std::function< bool(const Gate *)> &filter)
Function Documentation
copy_netlist()
CORE_API std::unique_ptr< Netlist > hal::netlist_utils::copy_netlist (const Netlist * nl)
Get a deep copy of an entire netlist including all of its gates, nets, modules, and groupings.
Parameters
[in] nl - The netlist to copy.
Returns
The deep copy of the netlist.
Definition at line 170 of file netlist_utils.cpp.
References hal::Gate::add_boolean_function(), hal::Grouping::assign_gate_by_id(), hal::Grouping::assign_module_by_id(), hal::Grouping::assign_net_by_id(), hal::netlist_factory::create_netlist(), hal::DataContainer::get_data_map(), hal::Netlist::get_design_name(), hal::Netlist::get_device_name(), hal::Netlist::get_free_gate_ids(), hal::Netlist::get_free_grouping_ids(), hal::Netlist::get_free_module_ids(), hal::Netlist::get_free_net_ids(), hal::Netlist::get_gate_library(), hal::Netlist::get_gates(), hal::Module::get_gates(), hal::Netlist::get_global_input_nets(), hal::Netlist::get_global_output_nets(), hal::Netlist::get_gnd_gates(), hal::Netlist::get_groupings(), hal::Net::get_id(), hal::Module::get_id(), hal::Netlist::get_input_filename(), hal::Module::get_input_port_names(), hal::Netlist::get_modules(), hal::Module::get_name(), hal::Net::get_name(), hal::Netlist::get_nets(), hal::Netlist::get_next_gate_id(), hal::Netlist::get_next_grouping_id(), hal::Module::get_next_input_port_id(), hal::Netlist::get_next_module_id(), hal::Netlist::get_next_net_id(), hal::Module::get_next_output_port_id(), hal::Module::get_output_port_names(), hal::Module::get_parent_module(), hal::Module::get_type(), hal::Netlist::get_used_gate_ids(), hal::Netlist::get_used_grouping_ids(), hal::Netlist::get_used_module_ids(), hal::Netlist::get_used_net_ids(), hal::Netlist::get_vcc_gates(), hal::Net::mark_global_input_net(), hal::Net::mark_global_output_net(), hal::Gate::mark_gnd_gate(), hal::Gate::mark_vcc_gate(), hal::ShortestPath::module(), hal::ShortestPath::net(), hal::DataContainer::set_data_map(), hal::Module::set_input_port_name(), hal::Module::set_next_input_port_id(), hal::Module::set_next_output_port_id(), hal::Module::set_output_port_name(), hal::Module::set_parent_module(), and hal::Module::set_type().
Referenced by hal::plugin_dataflow::execute(), and hal::netlist_utils_init().
get_common_inputs()
std::vector< Net * > hal::netlist_utils::get_common_inputs (const std::vector< Gate * > & gates, u32 threshold = 0)
Returns all nets that are considered to be common inputs to the provided gates. A threshold value can be provided to specify the number of gates a net must be connected to in order to be classified as a common input. If the theshold value is set to 0, a net must be input to all gates to be considered a common input.
Parameters
[in] gates - The gates.
[in] threshold - The threshold value, defaults to 0.
Returns
The common input nets.
Definition at line 1015 of file netlist_utils.cpp.
References g.
Referenced by hal::netlist_utils_init().
get_complex_gate_chain()
std::vector< Gate * > hal::netlist_utils::get_complex_gate_chain (Gate * start_gate, const std::vector< GateType * > & chain_types, const std::map< GateType *, std::set< std::string >> & input_pins = {}, const std::map< GateType *, std::set< std::string >> & output_pins = {}, const std::function< bool(const Gate *)> & filter = nullptr)
TODO test Find a repeating sequence of gates that are of the specified gate types and connect through the specified pins. The start gate may be any gate within a chain of such sequences, it is not required to be the first or the last gate. However, the start gate must be of the first gate type of the repeating sequence. For every gate type, a pair of input and output pins can be specified through which the gates are interconnected. If a nullptr is given for a gate type, any gate fulfilling the other properties will be considered. If an empty set is given for input or output pins, every pin of the respective gate will be considered. Before adding a gate to the chain, an optional user-defined filter is evaluated on every candidate gate.
Parameters
[in] start_gate - The gate at which to start the chain detection.
[in] chain_types - The sequence of gate types that is expected to make up the gate chain.
[in] input_pins - The input pins through which the gates are allowed to be connected.
[in] output_pins - The output pins through which the gates are allowed to be connected.
[in] filter - A filter that is evaluated on all candidates.
Returns
A vector of gates that form a chain.
Definition at line 1276 of file netlist_utils.cpp.
References hal::Endpoint::get_gate(), hal::Gate::get_id(), hal::Netlist::get_id(), hal::Gate::get_name(), hal::Gate::get_netlist(), hal::Endpoint::get_pin(), hal::Gate::get_predecessors(), hal::Gate::get_successors(), hal::Gate::get_type(), and log_debug.
Referenced by hal::netlist_utils_init().
get_ff_dependency_matrix()
std::pair< std::map< u32, Gate * >, std::vector< std::vector< int > > > hal::netlist_utils::get_ff_dependency_matrix (const Netlist * nl)
Get the FF dependency matrix of a netlist.
Parameters
[in] nl - The netlist to extract the dependency matrix from.
Returns
A pair consisting of std::map<u32, Gate*>, which includes the mapping from the original gate IDs to the ones in the matrix, and a std::vector<std::vector<int>, which is the ff dependency matrix
Definition at line 348 of file netlist_utils.cpp.
References hal::ff, hal::Netlist::get_gates(), and get_next_sequential_gates().
Referenced by hal::netlist_utils_init().
get_gate_chain()
std::vector< Gate * > hal::netlist_utils::get_gate_chain (Gate * start_gate, const std::set< std::string > & input_pins = {}, const std::set< std::string > & output_pins = {}, const std::function< bool(const Gate *)> & filter = nullptr)
Find a repeating sequence of identical gates that connect through the specified pins. The start gate may be any gate within a chain of such sequences, it is not required to be the first or the last gate. A pair of input and output pins can be specified through which the gates are interconnected. If the connection pins are irrelevant, an empty string may be passed to the function. Before adding a gate to the chain, an optional user-defined filter is evaluated on every candidate gate.
Parameters
[in] start_gate - The gate at which to start the chain detection.
[in] input_pins - The input pins through which the gates are allowed to be connected.
[in] output_pins - The output pins through which the gates are allowed to be connected.
[in] filter - A filter that is evaluated on all candidates.
Returns
A vector of gates that form a chain.
Definition at line 1159 of file netlist_utils.cpp.
References hal::Endpoint::get_gate(), hal::Gate::get_id(), hal::Netlist::get_id(), hal::Gate::get_name(), hal::Gate::get_netlist(), hal::Gate::get_successors(), hal::Gate::get_type(), and log_debug.
Referenced by hal::netlist_utils_init().
get_nets_at_pins()
std::unordered_set< Net * > hal::netlist_utils::get_nets_at_pins (Gate * gate, std::unordered_set< std::string > pins, bool is_input)
Get the nets that are connected to a subset of pins of the specified gate.
Parameters
[in] gate - The gate.
[in] pins - The targeted pins.
[in] is_input - True to look for fan-in nets, false for fan-out.
Returns
The set of nets connected to the pins.
Definition at line 720 of file netlist_utils.cpp.
References hal::Gate::get_fan_in_net(), hal::Gate::get_fan_out_net(), hal::Gate::get_id(), hal::Gate::get_name(), log_error, and hal::ShortestPath::net().
Referenced by hal::netlist_utils_init().
get_next_gates()
CORE_API std::vector< Gate * > hal::netlist_utils::get_next_gates (const Gate * gate, bool get_successors, int depth = 0, const std::function< bool(const Gate *)> & filter = nullptr)
TODO test Find predecessors or successors of a gate. If depth is set to 1 only direct predecessors/successors will be returned. Higher number of depth causes as many steps of recursive calls. If depth is set to 0 there is no limitation and the loop continues until no more predecessors/succesors are found. If a filter function is given only gates matching the filter will be added to the result vector. The result will not include the provided gate itself.
Parameters
gate[in] - The initial gate.
get_successors[in] - True to return successors, false for Predecessors.
depth[in] - Depth of recursion.
filter[in] - User-defined filter function.
Returns
Vector of predecessor/successor gates.
Definition at line 509 of file netlist_utils.cpp.
Referenced by hal::CommonSuccessorPredecessorGateQueue::getNext(), and hal::netlist_utils_init().
get_next_sequential_gates() [1/4]
CORE_API std::vector< Gate * > hal::netlist_utils::get_next_sequential_gates (const Gate * gate, bool get_successors)
Find all sequential predecessors or successors of a gate. Traverses combinational logic of all input or output nets until sequential gates are found. The result may include the provided gate itself.
Parameters
[in] gate - The initial gate.
[in] get_successors - If true, sequential successors are returned, otherwise sequential predecessors are returned.
Returns
All sequential successors or predecessors of the gate.
Definition at line 623 of file netlist_utils.cpp.
References get_next_sequential_gates().
get_next_sequential_gates() [2/4]
CORE_API std::vector< Gate * > hal::netlist_utils::get_next_sequential_gates (const Gate * gate, bool get_successors, std::unordered_map< u32, std::vector< Gate * >> & cache)
Find all sequential predecessors or successors of a gate. Traverses combinational logic of all input or output nets until sequential gates are found. The result may include the provided gate itself. The use of the this cached version is recommended in case of extensive usage to improve performance. The cache will be filled by this function and should initially be provided empty. Different caches for different values of get_successors shall be used.
Parameters
[in] gate - The initial gate.
[in] get_successors - If true, sequential successors are returned, otherwise sequential predecessors are returned.
[in,out] cache - The cache.
Returns
All sequential successors or predecessors of the gate.
Definition at line 602 of file netlist_utils.cpp.
References hal::Gate::get_fan_in_nets(), and hal::Gate::get_fan_out_nets().
Referenced by hal::BooleanInfluencePlugin::get_ff_dependency_matrix(), get_ff_dependency_matrix(), get_next_sequential_gates(), and hal::netlist_utils_init().
get_next_sequential_gates() [3/4]
CORE_API std::vector< Gate * > hal::netlist_utils::get_next_sequential_gates (const Net * net, bool get_successors)
Find all sequential predecessors or successors of a net. Traverses combinational logic of all input or output nets until sequential gates are found.
Parameters
[in] net - The initial net.
[in] get_successors - If true, sequential successors are returned, otherwise sequential predecessors are returned.
Returns
All sequential successors or predecessors of the net.
Definition at line 629 of file netlist_utils.cpp.
References get_next_sequential_gates(), and hal::ShortestPath::net().
get_next_sequential_gates() [4/4]
CORE_API std::vector< Gate * > hal::netlist_utils::get_next_sequential_gates (const Net * net, bool get_successors, std::unordered_map< u32, std::vector< Gate * >> & cache)
Find all sequential predecessors or successors of a net. Traverses combinational logic of all input or output nets until sequential gates are found. The use of the cache is recommended in case of extensive usage of this function. The cache will be filled by this function and should initially be provided empty. Different caches for different values of get_successors shall be used.
Parameters
[in] net - The initial net.
[in] get_successors - If true, sequential successors are returned, otherwise sequential predecessors are returned.
[in,out] cache - The cache.
Returns
All sequential successors or predecessors of the net.
Definition at line 617 of file netlist_utils.cpp.
References hal::ShortestPath::net().
get_partial_netlist()
CORE_API std::unique_ptr< Netlist > hal::netlist_utils::get_partial_netlist (const Netlist * nl, const std::vector< Gate * > & subgraph_gates)
Get a deep copy of an entire partial netlist including all of its gates, nets, excluding modules and groupings.
Parameters
[in] nl - The netlist consisting of the subgraph.
[in] subgraph_gates - The gates the subgraph is supposed to consist of.
Returns
The deep copy of the netlist.
Definition at line 393 of file netlist_utils.cpp.
References hal::Gate::add_boolean_function(), hal::netlist_factory::create_netlist(), hal::DataContainer::get_data_map(), hal::Netlist::get_design_name(), hal::Netlist::get_device_name(), hal::Netlist::get_free_gate_ids(), hal::Netlist::get_free_grouping_ids(), hal::Netlist::get_free_module_ids(), hal::Netlist::get_free_net_ids(), hal::Netlist::get_gate_library(), hal::Netlist::get_gates(), hal::Net::get_id(), hal::Netlist::get_input_filename(), hal::Net::get_name(), hal::Netlist::get_net_by_id(), hal::Netlist::get_next_gate_id(), hal::Netlist::get_next_grouping_id(), hal::Netlist::get_next_module_id(), hal::Netlist::get_next_net_id(), hal::Net::get_num_of_destinations(), hal::Net::get_num_of_sources(), hal::Netlist::get_used_gate_ids(), hal::Netlist::get_used_grouping_ids(), hal::Netlist::get_used_module_ids(), hal::Netlist::get_used_net_ids(), hal::ShortestPath::net(), and hal::DataContainer::set_data_map().
get_path() [1/4]
CORE_API std::vector< Gate * > hal::netlist_utils::get_path (const Gate * gate, bool get_successors, std::set< GateTypeProperty > stop_properties)
Find all gates on the predeccessor or successor path of a gate. Traverses all input or output nets until gates of the specified base types are found. The result may include the provided gate itself.
Parameters
[in] gate - The initial gate.
[in] get_successors - If true, the successor path is returned, otherwise the predecessor path is returned.
[in] stop_properties - Stop recursion when reaching a gate of a type with one of the specified properties.
Returns
All gates on the predecessor or successor path of the gate.
Definition at line 708 of file netlist_utils.cpp.
References get_path().
get_path() [2/4]
CORE_API std::vector< Gate * > hal::netlist_utils::get_path (const Gate * gate, bool get_successors, std::set< GateTypeProperty > stop_properties, std::unordered_map< u32, std::vector< Gate * >> & cache)
Find all gates on the predecessor or successor path of a gate. Traverses all input or output nets until gates of the specified base types are found. The result may include the provided gate itself. The use of the this cached version is recommended in case of extensive usage to improve performance. The cache will be filled by this function and should initially be provided empty. Different caches for different values of get_successors shall be used.
Parameters
[in] gate - The initial gate.
[in] get_successors - If true, the successor path is returned, otherwise the predecessor path is returned.
[in] stop_properties - Stop recursion when reaching a gate of a type with one of the specified properties.
[in,out] cache - The cache.
Returns
All gates on the predecessor or successor path of the gate.
Definition at line 687 of file netlist_utils.cpp.
References hal::Gate::get_fan_in_nets(), and hal::Gate::get_fan_out_nets().
Referenced by get_path(), and hal::netlist_utils_init().
get_path() [3/4]
CORE_API std::vector< Gate * > hal::netlist_utils::get_path (const Net * net, bool get_successors, std::set< GateTypeProperty > stop_properties)
Find all gates on the predecessor or successor path of a net. Traverses all input or output nets until gates of the specified base types are found.
Parameters
[in] net - The initial net.
[in] get_successors - If true, the successor path is returned, otherwise the predecessor path is returned.
[in] stop_properties - Stop recursion when reaching a gate of a type with one of the specified properties.
Returns
All gates on the predecessor or successor path of the net.
Definition at line 714 of file netlist_utils.cpp.
References get_path(), and hal::ShortestPath::net().
get_path() [4/4]
CORE_API std::vector< Gate * > hal::netlist_utils::get_path (const Net * net, bool get_successors, std::set< GateTypeProperty > stop_properties, std::unordered_map< u32, std::vector< Gate * >> & cache)
Find all gates on the predecessor or successor path of a net. Traverses all input or output nets until gates of the specified base types are found. The use of the this cached version is recommended in case of extensive usage to improve performance. The cache will be filled by this function and should initially be provided empty. Different caches for different values of get_successors shall be used.
Parameters
[in] net - The initial net.
[in] get_successors - If true, the successor path is returned, otherwise the predecessor path is returned.
[in] stop_types - Stop recursion when reaching a gate of a type with one of the specified properties.
[in,out] cache - The cache.
Returns
All gates on the predecessor or successor path of the net.
Definition at line 702 of file netlist_utils.cpp.
References hal::ShortestPath::net().
get_shortest_path()
std::vector< Gate * > hal::netlist_utils::get_shortest_path (Gate * start_gate, Gate * end_gate, bool search_both_directions = false)
TODO test Find the shortest path (i.e., theresult set with the lowest number of gates) that connects the start gate with the end gate. The gate where the search started from will be the first in the result vector, the end gate will be the last. If there is no such path an empty vector is returned. If there is more than one path with the same length only the first one is returned.
Parameters
[in] start_gate - The gate to start from.
[in] end_gate - The gate to connect to.
[in] search_both_directions - True to additionally check whether a shorter path from end to start exists, false otherwise.
Returns
A vector of gates that connect the start with end gate (possibly in reverse order).
Definition at line 549 of file netlist_utils.cpp.
Referenced by hal::GraphGraphicsView::handleShortestPath(), and hal::netlist_utils_init().
get_subgraph_function() [1/2]
CORE_API BooleanFunction hal::netlist_utils::get_subgraph_function (const Net * net, const std::vector< const Gate * > & subgraph_gates)
Get the combined Boolean function of a specific net, considering an entire subgraph.
In other words, the Boolean functions of the subgraph gates that influence the target net are combined to one function.
The variables of the resulting Boolean function are the net IDs of the nets that influence the output. If this function is used extensively, consider using the above variant with a cache.
Parameters
[in] net - The net for which to generate the Boolean function.
[in] subgraph_gates - The gates making up the subgraph to consider.
Returns
The combined Boolean function of the subgraph.
Definition at line 164 of file netlist_utils.cpp.
References get_subgraph_function(), and hal::ShortestPath::net().
get_subgraph_function() [2/2]
CORE_API BooleanFunction hal::netlist_utils::get_subgraph_function (const Net * net, const std::vector< const Gate * > & subgraph_gates, std::unordered_map< u32, BooleanFunction > & cache)
Get the combined Boolean function of a specific net, considering an entire subgraph.
In other words, the Boolean functions of the subgraph gates that influence the target net are combined to one function.
The variables of the resulting Boolean function are the net IDs of the nets that influence the output. For high performance when used extensively, a cache is employed.
Parameters
[in] net - The net for which to generate the Boolean function.
[in] subgraph_gates - The gates making up the subgraph to consider.
[in,out] cache - Cache to speed up computations. The cache is filled by this function.
Returns
The combined Boolean function of the subgraph.
Definition at line 124 of file netlist_utils.cpp.
References g, hal::Gate::get_fan_in_nets(), hal::Net::get_id(), hal::Net::get_num_of_sources(), hal::Net::get_sources(), log_error, and hal::ShortestPath::net().
Referenced by get_subgraph_function(), hal::netlist_utils_init(), and hal::SolveFsmPlugin::solve_fsm_brute_force().
remove_buffers()
void hal::netlist_utils::remove_buffers (Netlist * netlist, bool analyze_inputs = false)
Remove all buffer gates from the netlist and connect their fan-in to their fan-out nets. If enabled, analyzes every gate's inputs and removes fixed '0' or '1' inputs from the Boolean function.
Parameters
[in] netlist - The target netlist.
[in] analyze_inputs - Set true to dynamically analyze the inputs, false otherwise.
Definition at line 755 of file netlist_utils.cpp.
References hal::Net::add_destination(), hal::combinational, hal::Gate::get_boolean_functions(), hal::Net::get_destinations(), hal::Gate::get_fan_in_endpoints(), hal::Gate::get_fan_out_endpoints(), hal::Endpoint::get_net(), hal::Endpoint::get_pin(), hal::GateType::get_pins_of_direction(), hal::Gate::get_type(), hal::ground, hal::GateType::has_property(), hal::input, log_info, test_multiple::netlist, hal::BooleanFunction::optimize_constants(), hal::power, hal::Net::remove_destination(), hal::BooleanFunction::substitute(), and hal::BooleanFunction::to_string().
Referenced by hal::netlist_utils_init().
remove_unused_lut_endpoints()
void hal::netlist_utils::remove_unused_lut_endpoints (Netlist * netlist)
Remove all LUT fan-in endpoints that are not present within the Boolean function of the output of a gate.
Parameters
[in] netlist - The target netlist.
Definition at line 899 of file netlist_utils.cpp.
References hal::Net::add_destination(), g, hal::Gate::get_boolean_functions(), hal::Gate::get_fan_in_endpoints(), log_error, log_info, and test_multiple::netlist.
Referenced by hal::netlist_utils_init().
rename_luts_according_to_function()
void hal::netlist_utils::rename_luts_according_to_function (Netlist * netlist)
Deprecated:
DEPRECATED
Rename LUTs that implement simple functions to better reflect their functionality.
Parameters
[in] netlist - The target netlist.
Definition at line 945 of file netlist_utils.cpp.
References g, hal::Gate::get_boolean_functions(), hal::Gate::get_id(), log_info, test_multiple::netlist, hal::Gate::set_name(), hal::BooleanFunction::to_string(), and nlohmann::to_string().
Referenced by hal::netlist_utils_init().
replace_gate()
bool hal::netlist_utils::replace_gate (Gate * gate, GateType * target_type, std::map< std::string, std::string > pin_map)
TODO test Replace the given gate with a gate of the specified gate type. A map from old to new pins must be provided in order to correctly connect the gates inputs and outputs. A pin can be omitted if no connection at that pin is desired.
Parameters
[in] gate - The gate to be replaced.
[in] target_type - The gate type of the replacement gate.
[in] pin_map - A map from old to new pin names.
Returns
True on success, false otherwise.
Definition at line 1059 of file netlist_utils.cpp.
References hal::Grouping::assign_gate(), hal::Module::assign_gate(), hal::DataContainer::get_data_map(), hal::Gate::get_fan_in_endpoints(), hal::Gate::get_fan_out_endpoints(), hal::Gate::get_grouping(), hal::Gate::get_id(), hal::Gate::get_location(), hal::Gate::get_module(), hal::Gate::get_name(), hal::GateType::get_name(), hal::Gate::get_netlist(), hal::Module::is_top_module(), log_error, test_multiple::netlist, and hal::DataContainer::set_data_map().
Referenced by hal::netlist_utils_init().