HAL: nlohmann Namespace Reference
nlohmann Namespace Reference
namespace for Niels Lohmann
Namespaces
detail
detail namespace with internal helper functions
Classes
struct adl_serializer
default JSONSerializer template argument
class basic_json
a class to store JSON values
class json_pointer
JSON Pointer.
struct json_sax
SAX interface.
Typedefs
using json = basic_json<>
default JSON class
Functions
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer>
std::string to_string (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > &j)
user-defined to_string function for JSON values
Detailed Description
namespace for Niels Lohmann
namespace to hold default to_json function
See also
https://github.com/nlohmann
Since
version 1.0.0
Typedef Documentation
json
using nlohmann::json = typedef basic_json<>
default JSON class
This type is the default specialization of the basic_json class which uses the standard template types.
Since
version 1.0.0
Definition at line 2445 of file json.hpp.
Function Documentation
to_string()
template<template< typename, typename, typename... > class ObjectType, template< typename, typename... > class ArrayType, class StringType , class BooleanType , class NumberIntegerType , class NumberUnsignedType , class NumberFloatType , template< typename > class AllocatorType, template< typename, typename=void > class JSONSerializer> std::string nlohmann::to_string (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & j)
user-defined to_string function for JSON values
This function implements a user-defined to_string for JSON objects.
Parameters
[in] j a JSON object
Returns
a std::string object
Definition at line 22620 of file json.hpp.
Referenced by hal::BooleanFunction::Add(), hal::BooleanFunction::And(), hal::PinGroup< T >::assign_pin(), hal::Module::assign_pin_to_group(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), hal::BooleanFunction::Concat(), nlohmann::detail::parse_error::create(), hal::dataflow::state_to_module::create_modules(), hal::GateType::create_pin(), hal::Module::create_pin(), hal::GateType::create_pin_group(), hal::Module::create_pin_group(), hal::Module::delete_pin_group(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), hal::enum_to_string(), hal::BooleanFunction::Eq(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::erase(), hal::BooleanFunction::evaluate(), hal::plugin_dataflow::execute(), hal::SolveFsmPlugin::generate_dot_graph(), hal::Gate::get_boolean_function(), hal::GateType::get_boolean_function(), hal::BooleanFunctionDecorator::get_boolean_function_from(), hal::BooleanInfluencePlugin::get_boolean_influence(), hal::BooleanInfluencePlugin::get_boolean_influences_of_gate(), hal::BooleanInfluencePlugin::get_boolean_influences_of_subcircuit(), hal::BooleanFunctionNetDecorator::get_boolean_variable_name(), hal::netlist_utils::get_complex_gate_chain(), hal::Gate::get_fan_in_endpoint(), hal::BooleanInfluencePlugin::get_ff_dependency_matrix(), hal::netlist_utils::get_gate_chain(), hal::PinGroup< T >::get_index(), hal::Gate::get_init_data(), hal::PinGroup< T >::get_pin_at_index(), hal::GateType::get_pin_by_id(), hal::GateType::get_pin_by_name(), hal::GateType::get_pin_group_by_id(), hal::GateType::get_pin_group_by_name(), hal::Gate::get_predecessor(), hal::Gate::get_resolved_boolean_function(), hal::SubgraphNetlistDecorator::get_subgraph_function(), hal::SubgraphNetlistDecorator::get_subgraph_function_inputs(), hal::Gate::get_successor(), hal::BooleanFunction::get_truth_table_as_string(), nlohmann::detail::int_to_string(), hal::BooleanFunction::Ite(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::meta(), hal::PinGroup< T >::move_pin(), hal::Module::move_pin_within_group(), hal::BooleanFunction::Mul(), nlohmann::detail::exception::name(), hal::BooleanFunction::Not(), nlohmann::json_pointer< BasicJsonType >::operator/=(), hal::BooleanFunction::Or(), hal::VerilogParser::parse(), hal::VHDLParser::parse(), hal::LibertyParser::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch(), hal::SMT::Z3::query_binary(), hal::SMT::Boolector::query_binary(), hal::SMT::Translator::reduce_to_smt2(), hal::netlist_utils::remove_buffers(), hal::PinGroup< T >::remove_pin(), hal::Module::remove_pin_from_group(), hal::netlist_utils::remove_unused_lut_endpoints(), hal::netlist_utils::replace_gate(), hal::dataflow::json_output::save_state_to_json(), hal::dataflow::svg_output::save_state_to_svg(), hal::BooleanFunction::Sdiv(), hal::Gate::set_init_data(), hal::BooleanFunction::Sext(), hal::BooleanFunction::Sle(), hal::BooleanFunction::Slice(), hal::BooleanFunction::Slt(), hal::SolveFsmPlugin::solve_fsm(), hal::SolveFsmPlugin::solve_fsm_brute_force(), hal::BooleanFunction::Srem(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_array(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::start_array(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_object(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::start_object(), hal::BooleanFunction::Sub(), hal::BooleanFunctionDecorator::substitute_power_ground_pins(), hal::TEST_F(), hal::BooleanFunction::to_string(), hal::BooleanFunction::Node::to_string(), hal::BooleanFunction::to_u64(), hal::utils::Color::toString(), hal::BooleanFunction::Udiv(), hal::BooleanFunction::Ule(), hal::BooleanFunction::Ult(), hal::BooleanFunction::Urem(), hal::dataflow::textual_output::write_register_output(), hal::BooleanFunction::Xor(), and hal::BooleanFunction::Zext().