HAL: /home/runner/work/hal/hal/plugins/gui/src/graph_widget/layouters/net_layout_point.cpp File Reference
net_layout_point.cpp File Reference
#include "gui/graph_widget/layouters/net_layout_point.h"
#include <QGraphicsEllipseItem>
#include <QGraphicsLineItem>
#include <QBrush>
#include <QPen>
#include <QSet>
#include <QMultiMap>
#include <stdlib.h>
#include <QDebug>
#include <QTextStream>
Namespaces
hal
Functions
QPointF scenePoint (const QPoint &p)
uint hal::qHash (const hal::NetLayoutPoint &p)
uint hal::qHash (const hal::NetLayoutWire &w)
Function Documentation
scenePoint()
QPointF scenePoint (const QPoint & p)
Definition at line 12 of file net_layout_point.cpp.
References QPoint::x(), and QPoint::y().
Referenced by hal::NetLayoutPoint::graphicsFactory(), and hal::NetLayoutWire::graphicsFactory().