HAL: /home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/layouters/net_layout_point.h File Reference
net_layout_point.h File Reference
#include <QPoint>
#include <QPointF>
#include <QList>
#include <QMap>
#include <QHash>
Classes
class hal::NetLayoutDirection
class hal::NetLayoutPoint
class hal::NetLayoutWire
class hal::NetLayoutConnection
class hal::NetLayoutMetric
class hal::NetLayoutConnectionFactory
class hal::NetLayoutConnectionMetric
Namespaces
hal
Typedefs
typedef quint32 u32
Functions
QPointF scenePoint (const QPoint &p)
uint hal::qHash (const hal::NetLayoutWire &w)
uint hal::qHash (const hal::NetLayoutPoint &p)
uint qHash (const QPoint &p)
Typedef Documentation
u32
typedef quint32 u32
Definition at line 40 of file net_layout_point.h.
Function Documentation
qHash()
uint qHash (const QPoint & p)
Definition at line 6 of file node_box.cpp.
scenePoint()
QPointF scenePoint (const QPoint & p)
Definition at line 12 of file net_layout_point.cpp.
References QPoint::x(), and QPoint::y().
Referenced by hal::NetLayoutPoint::graphicsFactory(), and hal::NetLayoutWire::graphicsFactory().