HAL: /home/runner/work/hal/hal/plugins/gui/CMakeLists.txt File Reference
/home/runner/work/hal/hal/plugins/gui/CMakeLists.txt File Reference
Functions
option (PL_GUI "PL_GUI" ON) if(PL_GUI OR BUILD_ALL_PLUGINS) cmake_minimum_required(VERSION 3.1.0) if(APPLE AND CMAKE_HOST_APPLE AND NOT Qt5_DIR) set(Qt5_DIR "/usr/local/opt/qt@5/lib/cmake") endif(APPLE AND CMAKE_HOST_APPLE AND NOT Qt5_DIR) find_package(Qt5 COMPONENTS Core REQUIRED) find_package(Qt5 COMPONENTS Widgets REQUIRED) if(Qt5Widgets_FOUND) message(VERBOSE "Qt5Widgets_INCLUDE_DIRS
message (VERBOSE "Qt5Widgets_LIBRARIES: ${Qt5Widgets_LIBRARIES}") elseif(NOT Qt5Widgets_FOUND) set(Missing_package "TRUE") if(APPLE AND CMAKE_HOST_APPLE) message(STATUS "To install qt5 on MacOS using homebrew run following command
message (VERBOSE "Qt5Concurrent_LIBRARIES: ${Qt5Concurrent_LIBRARIES}") elseif(NOT Qt5Concurrent_FOUND) set(Missing_package "TRUE") if(APPLE AND CMAKE_HOST_APPLE) message(STATUS "To install qt5 on MacOS using homebrew run following command
message (VERBOSE "Qt5Svg_LIBRARIES: ${Qt5Svg_LIBRARIES}") elseif(NOT Qt5Svg_FOUND) set(Missing_package "TRUE") endif(Qt5Svg_FOUND) set(INCROOT $
include set (SRCROOT ${CMAKE_CURRENT_SOURCE_DIR}/src) set(UIROOT $
ui set (RSRCROOT ${CMAKE_CURRENT_SOURCE_DIR}/resources) configure_file($
Function Documentation
message() [1/3]
message (VERBOSE "Qt5Concurrent_LIBRARIES: ${Qt5Concurrent_LIBRARIES}")
Definition at line 27 of file CMakeLists.txt.
message() [2/3]
message (VERBOSE "Qt5Svg_LIBRARIES: ${Qt5Svg_LIBRARIES}")
Definition at line 39 of file CMakeLists.txt.
message() [3/3]
message (VERBOSE "Qt5Widgets_LIBRARIES: ${Qt5Widgets_LIBRARIES}")
Definition at line 15 of file CMakeLists.txt.
Referenced by hal::FileManager::openProject(), hal::dataflow::ProgressPrinter::print_progress(), and hal::PYBIND11_PLUGIN().
option()
option (PL_GUI "PL_GUI" ON)
Definition at line 1 of file CMakeLists.txt.
Referenced by hal::CommentSpeechBubble::paint(), hal::GroupingColorDelegate::paint(), hal::CircleSeparatedNet::paint(), hal::ArrowSeparatedNet::paint(), hal::LabeledSeparatedNet::paint(), hal::NodeDragShadow::paint(), hal::StandardGraphicsGate::paint(), hal::StandardGraphicsModule::paint(), hal::StandardArrowNet::paint(), hal::StandardGraphicsNet::paint(), and hal::GroupingColorDelegate::sizeHint().
set() [1/2]
ui set (RSRCROOT ${CMAKE_CURRENT_SOURCE_DIR}/ resources)
Definition at line 47 of file CMakeLists.txt.
set() [2/2]
include set (SRCROOT ${CMAKE_CURRENT_SOURCE_DIR}/ src)
Definition at line 45 of file CMakeLists.txt.
Referenced by hal::dataflow::group_by_control_signals::process(), hal::dataflow::group_by_control_signals::pure_control_signals_process(), and hal::UserAction::setToText().