HAL: hal::dataflow::Result Struct Reference
hal::dataflow::Result Struct Reference
#include <result.h>
Public Member Functions
Result (Netlist *nl, const Grouping &grouping)
Netlist * get_netlist () const
const std::unordered_map< u32, std::unordered_set< Gate * > > & get_groups () const
std::vector< Gate * > get_gates () const
hal::Result< std::unordered_set< Gate * > > get_gates_of_group (const u32 group_id) const
hal::Result< u32 > get_group_id_of_gate (const Gate *gate) const
hal::Result< std::unordered_set< Net * > > get_group_control_nets (const u32 group_id, const PinType type) const
hal::Result< std::unordered_set< Net * > > get_gate_control_nets (const Gate *gate, const PinType type) const
hal::Result< std::unordered_set< u32 > > get_group_successors (const u32 group_id) const
hal::Result< std::unordered_set< Gate * > > get_gate_successors (const Gate *gate) const
hal::Result< std::unordered_set< u32 > > get_group_predecessors (const u32 group_id) const
hal::Result< std::unordered_set< Gate * > > get_gate_predecessors (const Gate *gate) const
hal::Result< std::monostate > write_dot (const std::filesystem::path &out_path, const std::unordered_set< u32 > &group_ids={}) const
hal::Result< std::monostate > write_txt (const std::filesystem::path &out_path, const std::unordered_set< u32 > &group_ids={}) const
hal::Result< std::unordered_map< u32, Module * > > create_modules (const std::unordered_set< u32 > &group_ids={}) const
std::vector< std::vector< Gate * > > get_groups_as_list (const std::unordered_set< u32 > &group_ids={}) const
hal::Result< u32 > merge_groups (const std::vector< u32 > &group_ids)
hal::Result< std::vector< u32 > > split_group (u32 group_id, const std::vector< std::unordered_set< Gate * >> &new_groups)
Detailed Description
The result of a dataflow analysis run containing the identified groups of sequential gates and their interconnections.
Definition at line 43 of file result.h.
Constructor & Destructor Documentation
Result()
hal::dataflow::Result::Result (Netlist * nl, const Grouping & grouping)
Definition at line 28 of file result.cpp.
References hal::clock, hal::enable, hal::dataflow::Grouping::gates_of_group, hal::dataflow::Grouping::get_clock_signals_of_group(), hal::dataflow::Grouping::get_control_signals_of_group(), hal::Netlist::get_gate_by_id(), hal::Netlist::get_net_by_id(), hal::dataflow::Grouping::get_predecessor_groups_of_group(), hal::dataflow::Grouping::get_reset_signals_of_group(), hal::dataflow::Grouping::get_set_signals_of_group(), hal::dataflow::Grouping::get_successor_groups_of_group(), hal::dataflow::Grouping::netlist_abstr, hal::reset, and hal::set.
Member Function Documentation
create_modules()
hal::Result< std::unordered_map< u32, Module * > > hal::dataflow::Result::create_modules (const std::unordered_set< u32 > & group_ids = {}) const
Create modules for the dataflow analysis result.
Parameters
[in] group_ids - The group IDs to consider. If no IDs are provided, all groups will be considered. Defaults to an empty set.
Returns
Ok() and a map from group IDs to Modules on success, an error otherwise.
Definition at line 449 of file result.cpp.
References hal::clock, hal::data, hal::enable, hal::Endpoint::get_gate(), hal::PinGroup< T >::get_index(), hal::input, log_info, log_warning, net, OK, hal::output, hal::reset, hal::set, and hal::state.
get_gate_control_nets()
hal::Result< std::unordered_set< Net * > > hal::dataflow::Result::get_gate_control_nets (const Gate * gate, const PinType type) const
Get the control nets of the given gate that are connected to a pin of the specified type.
Parameters
[in] gate - The gate.
[in] type - The pin type.
Returns
Ok() and a set of control nets of the gate on success, an error otherwise.
Definition at line 201 of file result.cpp.
References ERR, OK, and type.
get_gate_predecessors()
hal::Result< std::unordered_set< Gate * > > hal::dataflow::Result::get_gate_predecessors (const Gate * gate) const
Get the sequential predecessor gates of the given sequential gate.
Parameters
[in] gate - The gate.
Returns
Ok() and the predecessors of the gate as a set of gates on success, an error otherwise.
Definition at line 265 of file result.cpp.
References ERR, and OK.
get_gate_successors()
hal::Result< std::unordered_set< Gate * > > hal::dataflow::Result::get_gate_successors (const Gate * gate) const
Get the sequential successor gates of the given sequential gate.
Parameters
[in] gate - The gate.
Returns
Ok() and the successors of the gate as a set of gates on success, an error otherwise.
Definition at line 235 of file result.cpp.
References ERR, and OK.
get_gates()
std::vector< Gate * > hal::dataflow::Result::get_gates () const
Get all gates contained in any of the groups groups.
Returns
A vector of gates.
Definition at line 141 of file result.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_gates_of_group()
hal::Result< std::unordered_set< Gate * > > hal::dataflow::Result::get_gates_of_group (const u32 group_id) const
Get the gates of the specified group of sequential gates.
Parameters
[in] group_id - The ID of the group.
Returns
Ok() and the gates of the group as a set on success, an error otherwise.
Definition at line 153 of file result.cpp.
References ERR, and OK.
get_group_control_nets()
hal::Result< std::unordered_set< Net * > > hal::dataflow::Result::get_group_control_nets (const u32 group_id, const PinType type) const
Get the control nets of the group with the given group ID that are connected to a pin of the specified type.
Parameters
[in] group_id - The group ID.
[in] type - The pin type.
Returns
Ok() and a set of control nets of the group on success, an error otherwise.
Definition at line 182 of file result.cpp.
References ERR, OK, and type.
get_group_id_of_gate()
hal::Result< u32 > hal::dataflow::Result::get_group_id_of_gate (const Gate * gate) const
Get the group ID of the group that contains the given gate.
Parameters
[in] gate - The gate.
Returns
Ok() and the group ID on success, an error otherwise.
Definition at line 165 of file result.cpp.
References ERR, and OK.
get_group_predecessors()
hal::Result< std::unordered_set< u32 > > hal::dataflow::Result::get_group_predecessors (const u32 group_id) const
Get the predecessor groups of the group with the given ID.
Parameters
[in] group_id - The group ID.
Returns
Ok() and the predecessors of the group as a set of group IDs on success, an error otherwise.
Definition at line 250 of file result.cpp.
References ERR, and OK.
get_group_successors()
hal::Result< std::unordered_set< u32 > > hal::dataflow::Result::get_group_successors (const u32 group_id) const
Get the successor groups of the group with the given ID.
Parameters
[in] group_id - The group ID.
Returns
Ok() and the successors of the group as a set of group IDs on success, an error otherwise.
Definition at line 220 of file result.cpp.
References ERR, and OK.
get_groups()
const std::unordered_map< u32, std::unordered_set< Gate * > > & hal::dataflow::Result::get_groups () const
Get the groups of sequential gates resulting from dataflow analysis.
Returns
A map from group ID to a set of gates belonging to the respective group.
Definition at line 136 of file result.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_groups_as_list()
std::vector< std::vector< Gate * > > hal::dataflow::Result::get_groups_as_list (const std::unordered_set< u32 > & group_ids = {}) const
Get the groups of the dataflow analysis result as a list.
Parameters
[in] group_ids - The group IDs to consider. If no IDs are provided, all groups will be considered. Defaults to an empty set.
Returns
A vector of groups with each group being a vector of gates.
Definition at line 619 of file result.cpp.
Referenced by hal::PYBIND11_PLUGIN().
get_netlist()
Netlist * hal::dataflow::Result::get_netlist () const
Get the netlist on which dataflow analysis has been performed.
Returns
The netlist.
Definition at line 131 of file result.cpp.
Referenced by hal::PYBIND11_PLUGIN().
merge_groups()
hal::Result< u32 > hal::dataflow::Result::merge_groups (const std::vector< u32 > & group_ids)
Merge multiple groups specified by ID. All specified groups are merged into the first group of the provided vector and are subsequently deleted.
Parameters
[in] group_ids - The group IDs of the groups to merge.
Returns
The ID of the group that all over groups have been merged into on success, an error otherwise.
Definition at line 639 of file result.cpp.
References ERR, test_plugin::g, and OK.
split_group()
hal::Result< std::vector< u32 > > hal::dataflow::Result::split_group (u32 group_id, const std::vector< std::unordered_set< Gate * >> & new_groups)
Split a group into multiple smaller groups specified by sets of gates. All gates of the group to split must be contained in the sets exactly once and all gates in the sets must be contained in the group to split. The group that is being split is deleted in the process.
Parameters
[in] group_id - The group ID of the group to split.
[in] new_groups - A vector of groups specified as unordered sets of gates.
Returns
The group IDs of the newly created groups in the order of the provided sets.
Definition at line 712 of file result.cpp.
References hal::clock, hal::enable, ERR, test_plugin::g, OK, hal::reset, hal::set, and type.
write_dot()
hal::Result< std::monostate > hal::dataflow::Result::write_dot (const std::filesystem::path & out_path, const std::unordered_set< u32 > & group_ids = {}) const
Write the dataflow graph as a DOT graph to the specified location.
Parameters
[in] out_path - The output path.
[in] group_ids - The group IDs to consider. If no IDs are provided, all groups will be considered. Defaults to an empty set.
Returns
Ok() on success, an error otherwise.
Definition at line 280 of file result.cpp.
References ERR, log_info, and OK.
write_txt()
hal::Result< std::monostate > hal::dataflow::Result::write_txt (const std::filesystem::path & out_path, const std::unordered_set< u32 > & group_ids = {}) const
Write the groups resulting from dataflow analysis to a .txt file.
Parameters
[in] out_path - The output path.
[in] group_ids - The group IDs to consider. If no IDs are provided, all groups will be considered. Defaults to an empty set.
Returns
Ok() on success, an error otherwise.
Definition at line 353 of file result.cpp.
References hal::clock, hal::data, hal::enable, ERR, id, hal::utils::join(), log_info, name, OK, hal::reset, hal::set, and type.
The documentation for this struct was generated from the following files:
/home/runner/work/hal/hal/plugins/dataflow_analysis/include/dataflow_analysis/api/result.h
/home/runner/work/hal/hal/plugins/dataflow_analysis/src/api/result.cpp