HAL: hal::StandardGraphicsNet::Lines Struct Reference
hal::StandardGraphicsNet::Lines Struct Reference
#include <standard_graphics_net.h>
Public Member Functions
void appendHLine (const qreal mSmallX, const qreal mBigX, const qreal y)
void appendVLine (const qreal x, const qreal mSmallY, const qreal mBigY)
void mergeLines ()
int nLines ()
Detailed Description
Struct to store all lines of a StandardGraphicsNet.
Definition at line 76 of file standard_graphics_net.h.
Member Function Documentation
appendHLine()
void hal::StandardGraphicsNet::Lines::appendHLine (const qreal mSmallX, const qreal mBigX, const qreal y)
Adds a horizontal line.
Parameters
mSmallX - The x-coordinate of the starting point of the line (lower x-coord)
mBigX - The x-coordinate of the end point of the line (higher x-coord)
y - The y-coordinate of the horizontal line
Definition at line 194 of file standard_graphics_net.cpp.
References QGraphicsItem::y().
appendVLine()
void hal::StandardGraphicsNet::Lines::appendVLine (const qreal x, const qreal mSmallY, const qreal mBigY)
Adds a vertical line.
Parameters
x - The x-coordinate of the vertical line
mSmallY - The y-coordinate of the starting point of the line (lower y-coord)
mBigY - The y-coordinate of the end point of the line (higher y-coord)
Definition at line 201 of file standard_graphics_net.cpp.
References QGraphicsItem::x().
mergeLines()
void hal::StandardGraphicsNet::Lines::mergeLines ()
Merges all horizontal and vertical lines so that overlapping lines are replaced by only a single line.
Definition at line 208 of file standard_graphics_net.cpp.
References QVector::append(), QVector::at(), QVector::isEmpty(), QVector::remove(), QVector::size(), hal::StandardGraphicsNet::VLine::x, and hal::StandardGraphicsNet::HLine::y.
nLines()
int hal::StandardGraphicsNet::Lines::nLines () inline
Gets the total amount of lines (includes horizontal AND vertical lines).
Returns
the total amount of lines
Definition at line 106 of file standard_graphics_net.h.
The documentation for this struct was generated from the following files:
/home/runner/work/hal/hal/plugins/gui/include/gui/graph_widget/items/nets/standard_graphics_net.h
/home/runner/work/hal/hal/plugins/gui/src/graph_widget/items/nets/standard_graphics_net.cpp