HAL: hal::SMT::Result Struct Reference
hal::SMT::Result Struct Reference final
#include <types.h>
Public Member Functions
bool is (const ResultType &_type) const
bool is_sat () const
bool is_unsat () const
bool is_unknown () const
Static Public Member Functions
static Result Sat (const std::optional< Model > &model={})
static Result UnSat ()
static Result Unknown ()
Public Attributes
ResultType type
stores result of SMT query
std::optional< Model > model
stores optional model (only available if type == Sat) and model generation is enabled in SMTQueryConfig
Friends
std::ostream & operator<< (std::ostream &out, const Result &result)
Detailed Description
'Result' represents the result of an SMT query.
Definition at line 226 of file types.h.
Member Function Documentation
is()
bool hal::SMT::Result::is (const ResultType & _type) const
Checks whether result is of specific type.
Parameters
[in] _type - Type to check.
Returns
True in case result matches _type, false otherwise.
Definition at line 226 of file types.cpp.
References type.
Referenced by is_sat(), is_unknown(), and is_unsat().
is_sat()
bool hal::SMT::Result::is_sat () const
Checks whether result is of satisfiable type.
Returns
True in case result is satisfiable, false otherwise.
Definition at line 231 of file types.cpp.
References is(), and hal::SMT::Sat.
is_unknown()
bool hal::SMT::Result::is_unknown () const
Checks whether result is of unknown type.
Returns
True in case result is unknown, false otherwise.
Definition at line 241 of file types.cpp.
References is(), and hal::SMT::Unknown.
is_unsat()
bool hal::SMT::Result::is_unsat () const
Checks whether result is of unsatisfiable type.
Returns
True in case result is unsatisfiable, false otherwise.
Definition at line 236 of file types.cpp.
References is(), and hal::SMT::UnSat.
Sat()
Result hal::SMT::Result::Sat (const std::optional< Model > & model = {}) static
Creates a satisfiable result with an optional model.
Parameters
[in] model - Optional model for satisfiable formula.
Returns
Result.
Definition at line 211 of file types.cpp.
References model, and hal::SMT::Sat.
Unknown()
Result hal::SMT::Result::Unknown () static
Creates an unknown result.
Returns
Result.
Definition at line 221 of file types.cpp.
References hal::SMT::Unknown.
Referenced by hal::SMT::Solver::query_local(), and hal::SMT::Solver::query_remote().
UnSat()
Result hal::SMT::Result::UnSat () static
Creates an unsatisfiable result.
Returns
Result.
Definition at line 216 of file types.cpp.
References hal::SMT::UnSat.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Result & result) friend
Human-readable description of SMT result.
Parameters
[in] out - Stream to write to.
[in] result - SMT result.
Returns
A reference to output stream.
Definition at line 246 of file types.cpp.
Member Data Documentation
model
std::optional<Model> hal::SMT::Result::model
stores optional model (only available if type == Sat) and model generation is enabled in SMTQueryConfig
Definition at line 235 of file types.h.
Referenced by hal::SMT::operator<<(), and Sat().
type
ResultType hal::SMT::Result::type
stores result of SMT query
Definition at line 233 of file types.h.
Referenced by is(), and hal::SMT::operator<<().
The documentation for this struct was generated from the following files:
/home/runner/work/hal/hal/include/hal_core/netlist/boolean_function/types.h
/home/runner/work/hal/hal/src/netlist/boolean_function/types.cpp