hal: /home/runner/work/hal/hal/src/python-binding/python_definitions.cpp File Reference
python_definitions.cpp File Reference
#include "def.h"
#include "core/interface_gui.h"
#include "core/log.h"
#include "core/plugin_manager.h"
#include "core/utils.h"
#include "netlist/hdl_parser/hdl_parser_dispatcher.h"
#include "netlist/hdl_writer/hdl_writer_dispatcher.h"
#include "netlist/boolean_function.h"
#include "netlist/gate.h"
#include "netlist/gate_library/gate_library.h"
#include "netlist/gate_library/gate_type/gate_type.h"
#include "netlist/gate_library/gate_type/gate_type_lut.h"
#include "netlist/gate_library/gate_type/gate_type_sequential.h"
#include "netlist/module.h"
#include "netlist/net.h"
#include "netlist/netlist.h"
#include "netlist/netlist_factory.h"
#include "netlist/persistent/netlist_serializer.h"
#include "gui/gui_api/gui_api.h"
#include "pybind11/operators.h"
#include "pybind11/pybind11.h"
#include "pybind11/stl.h"
#include "pybind11/stl_bind.h"
#include "pybind11/functional.h"
Typedefs
using map_string_to_set_of_string = std::map< std::string, std::set< std::string > >
Functions
PYBIND11_PLUGIN (hal_py)
Typedef Documentation
map_string_to_set_of_string
using map_string_to_set_of_string = std::map<std::string, std::set<std::string> >
Function Documentation
PYBIND11_PLUGIN()
PYBIND11_PLUGIN (hal_py)
References gate_type::add_boolean_function(), gate::add_boolean_function(), net::add_dst(), gate_library::add_gate_type(), gate_library::add_include(), gate_type::add_input_pin(), gate_type::add_input_pins(), gate_type_sequential::add_inverted_state_output_pin(), gate_type_lut::add_output_from_init_string_pin(), gate_type::add_output_pin(), gate_type::add_output_pins(), gate_type_sequential::add_state_output_pin(), module::assign_gate(), gate_type::combinatorial, module::contains_gate(), module::contains_module(), netlist::create_gate(), netlist::create_module(), netlist::create_net(), netlist_factory::create_netlist(), data_container::delete_data(), netlist::delete_gate(), netlist::delete_module(), netlist::delete_net(), boolean_function::evaluate(), i_gui::exec(), gate_type::ff, boolean_function::from_string(), core_utils::get_base_directory(), gate_type::get_base_type(), core_utils::get_binary_directory(), gate::get_boolean_function(), gate_type::get_boolean_functions(), gate::get_boolean_functions(), hdl_writer_dispatcher::get_cli_options(), gate_type_lut::get_config_data_category(), gate_type_lut::get_config_data_identifier(), data_container::get_data(), data_container::get_data_by_key(), data_container::get_data_keys(), core_utils::get_default_log_directory(), netlist::get_design_name(), netlist::get_device_name(), net::get_dsts(), gate::get_fan_in_net(), gate::get_fan_in_nets(), gate::get_fan_out_net(), gate::get_fan_out_nets(), endpoint::get_gate(), module::get_gate_by_id(), netlist::get_gate_by_id(), netlist::get_gate_library(), core_utils::get_gate_library_directories(), gate_library::get_gate_types(), module::get_gates(), netlist::get_gates(), netlist::get_global_input_nets(), netlist::get_global_output_nets(), gate_library::get_gnd_gate_types(), netlist::get_gnd_gates(), net::get_id(), gate::get_id(), module::get_id(), netlist::get_id(), gate_library::get_includes(), gate_type_sequential::get_init_data_category(), gate_type_sequential::get_init_data_identifier(), netlist::get_input_filename(), module::get_input_nets(), gate_type::get_input_pins(), gate::get_input_pins(), module::get_internal_nets(), gate_type_sequential::get_inverted_state_output_pins(), core_utils::get_library_directory(), gate::get_location(), gate::get_location_x(), gate::get_location_y(), gate::get_module(), netlist::get_module_by_id(), netlist::get_modules(), gate_library::get_name(), module::get_name(), net::get_name(), gate::get_name(), i_base::get_name(), gate_type::get_name(), netlist::get_net_by_id(), gate::get_netlist(), module::get_netlist(), netlist::get_nets(), net::get_num_of_dsts(), gate_type_lut::get_output_from_init_string_pins(), module::get_output_nets(), gate_type::get_output_pins(), gate::get_output_pins(), module::get_parent_module(), endpoint::get_pin_type(), core_utils::get_plugin_directories(), plugin_manager::get_plugin_names(), gate::get_predecessor(), gate::get_predecessors(), gate_type_sequential::get_set_reset_behavior(), core_utils::get_share_directory(), net::get_src(), gate_type_sequential::get_state_output_pins(), module::get_submodules(), gate::get_successors(), netlist::get_top_module(), boolean_function::get_truth_table(), gate::get_type(), netlist::get_unique_gate_id(), netlist::get_unique_module_id(), netlist::get_unique_net_id(), gate::get_unique_predecessors(), gate::get_unique_successors(), core_utils::get_user_config_directory(), core_utils::get_user_share_directory(), boolean_function::get_variables(), gate_library::get_vcc_gate_types(), netlist::get_vcc_gates(), i_base::get_version(), gate_type_sequential::H, gate::has_location(), net::is_a_dst(), gate_type_lut::is_config_data_ascending_order(), boolean_function::is_constant_one(), boolean_function::is_constant_zero(), boolean_function::is_dnf(), boolean_function::is_empty(), netlist::is_gate_in_netlist(), net::is_global_input_net(), netlist::is_global_input_net(), net::is_global_output_net(), netlist::is_global_output_net(), gate::is_gnd_gate(), netlist::is_gnd_gate(), netlist::is_module_in_netlist(), netlist::is_net_in_netlist(), net::is_unrouted(), gate::is_vcc_gate(), netlist::is_vcc_gate(), gate_type_sequential::L, gate_type::latch, plugin_manager::load(), plugin_manager::load_all_plugins(), netlist_factory::load_netlist(), log_info, gate_type::lut, net::mark_global_input_net(), netlist::mark_global_input_net(), net::mark_global_output_net(), netlist::mark_global_output_net(), gate::mark_gnd_gate(), netlist::mark_gnd_gate(), gate::mark_vcc_gate(), netlist::mark_vcc_gate(), gate_type_sequential::N, boolean_function::optimize(), net::remove_dst(), module::remove_gate(), net::remove_src(), gate_type_lut::set_config_data_ascending_order(), gate_type_lut::set_config_data_category(), gate_type_lut::set_config_data_identifier(), data_container::set_data(), netlist::set_design_name(), netlist::set_device_name(), endpoint::set_gate(), netlist::set_id(), gate_type_sequential::set_init_data_category(), gate_type_sequential::set_init_data_identifier(), netlist::set_input_filename(), gate::set_location(), gate::set_location_x(), gate::set_location_y(), module::set_name(), net::set_name(), gate::set_name(), module::set_parent_module(), endpoint::set_pin_type(), gate_type_sequential::set_set_reset_behavior(), net::set_src(), boolean_function::substitute(), gate_type_sequential::T, boolean_function::to_dnf(), boolean_function::to_string(), gate_type::to_string(), gate_type_sequential::U, plugin_manager::unload_all_plugins(), net::unmark_global_input_net(), netlist::unmark_global_input_net(), net::unmark_global_output_net(), netlist::unmark_global_output_net(), gate::unmark_gnd_gate(), netlist::unmark_gnd_gate(), gate::unmark_vcc_gate(), netlist::unmark_vcc_gate(), hdl_writer_dispatcher::write(), and gate_type_sequential::X.