hal: /home/runner/work/hal/hal/src/netlist/boolean_function.cpp File Reference
boolean_function.cpp File Reference
#include "netlist/boolean_function.h"
#include "core/utils.h"
Functions
std::ostream & operator<< (std::ostream &os, const boolean_function::operation &op)
std::ostream & operator<< (std::ostream &os, const boolean_function::value &v)
std::ostream & operator<< (std::ostream &os, const boolean_function &f)
Function Documentation
operator<<() [1/3]
std::ostream& operator<< (std::ostream & os, const boolean_function::operation & op)
References boolean_function::to_string().
operator<<() [2/3]
std::ostream& operator<< (std::ostream & os, const boolean_function::value & v)
ostream operator that forwards to_string of a value.
Parameters
[in] os - the stream to write to.
[in] v - the value.
Returns
A reference to os.
References boolean_function::to_string().
operator<<() [3/3]
std::ostream& operator<< (std::ostream & os, const boolean_function & f)
ostream operator that forwards to_string of a boolean function.
Parameters
[in] os - the stream to write to.
[in] f - the function.
Returns
A reference to os.
References boolean_function::boolean_function(), boolean_function::is_empty(), boolean_function::operator &(), and boolean_function::to_string().