hal: hdl_parser_verilog Class Reference
hdl_parser_verilog Class Reference
HDL Interfaces » HDL Parsers
#include <hdl_parser_verilog.h>
Public Member Functions
hdl_parser_verilog (std::stringstream &stream)
~hdl_parser_verilog ()=default
std::shared_ptr< netlist > parse (const std::string &gate_library) override
Public Member Functions inherited from hdl_parser
hdl_parser (std::stringstream &stream)
virtual ~hdl_parser ()=default
Constructor & Destructor Documentation
hdl_parser_verilog()
hdl_parser_verilog::hdl_parser_verilog (std::stringstream & stream) explicit
Parameters
[in] stream - The string stream filled with the hdl code.
~hdl_parser_verilog()
hdl_parser_verilog::~hdl_parser_verilog () default
Member Function Documentation
parse()
std::shared_ptr< netlist > hdl_parser_verilog::parse (const std::string & gate_library) override virtual
Deserializes a netlist in Verilog format from the internal string stream into a netlist object.
Parameters
[in] gate_library - The gate library used in the serialized file.
Returns
The deserialized netlist.
Implements hdl_parser.
References token_stream::consume(), token_stream::consume_until(), netlist_factory::create_netlist(), token_stream::END_OF_STREAM, core_utils::ends_with(), token_stream::extract_until(), endpoint::gate, net::get_num_of_dsts(), net::get_src(), core_utils::is_floating_point(), net::is_global_input_net(), net::is_global_output_net(), core_utils::is_integer(), token_stream::token_stream_exception::line_number, log_error, log_warning, net::mark_global_input_net(), net::mark_global_output_net(), token_stream::token_stream_exception::message, token::number, token_stream::peek(), token_stream::remaining(), core_utils::replace(), data_container::set_data(), module::set_name(), core_utils::starts_with(), token::string, core_utils::to_lower(), core_utils::trim(), and UNUSED.
Referenced by hdl_parser_dispatcher::parse().
The documentation for this class was generated from the following files:
netlist/hdl_parser/hdl_parser_verilog.h
/home/runner/work/hal/hal/src/netlist/hdl_parser/hdl_parser_verilog.cpp