hal: hal::LibraryLoader Class Reference
hal::LibraryLoader Class Reference
HAL Core
#include <library_loader.h>
Public Member Functions
LibraryLoader ()
~LibraryLoader ()
bool load_library (const std::string &file_name)
std::string get_file_name () const
bool unload_library ()
lib_fn_ptr_t get_function (const std::string &function_name)
Constructor & Destructor Documentation
LibraryLoader()
hal::LibraryLoader::LibraryLoader ()
~LibraryLoader()
hal::LibraryLoader::~LibraryLoader ()
References unload_library().
Member Function Documentation
load_library()
bool hal::LibraryLoader::load_library (const std::string & file_name)
Loads a library.
Parameters
[in] file_name - Name of the library.
Returns
True on success.
References log_debug, and log_error.
Referenced by hal::plugin_manager::load().
get_file_name()
std::string hal::LibraryLoader::get_file_name () const
Gets the file name of the loaded library.
Returns
The file name.
unload_library()
bool hal::LibraryLoader::unload_library ()
Unloads the library.
Returns
True on success.
References log_debug, and log_error.
Referenced by ~LibraryLoader().
get_function()
lib_fn_ptr_t hal::LibraryLoader::get_function (const std::string & function_name)
Gets the function pointer to a function by name.
Parameters
[in] function_name - Name of the function.
Returns
The function pointer.
References log_debug, and log_error.
Referenced by hal::plugin_manager::load().
The documentation for this class was generated from the following files:
core/library_loader.h
/home/runner/work/hal/hal/src/core/library_loader.cpp