hal: hal::GateTypeSequential Class Reference
hal::GateTypeSequential Class Reference
HAL Core » Netlist » Gate Library
#include <gate_type_sequential.h>
Public Types
enum SetResetBehavior {
SetResetBehavior::U = 0, SetResetBehavior::L = 1, SetResetBehavior::H = 2, SetResetBehavior::N = 3,
SetResetBehavior::T = 4, SetResetBehavior::X = 5
}
Public Types inherited from hal::GateType
enum BaseType { BaseType::combinatorial, BaseType::lut, BaseType::ff, BaseType::latch }
Public Member Functions
GateTypeSequential (const std::string &name, BaseType base_type)
~GateTypeSequential () override=default
void add_state_output_pin (const std::string &pin_name)
std::unordered_set< std::string > get_state_output_pins () const
void add_inverted_state_output_pin (const std::string &pin_name)
std::unordered_set< std::string > get_inverted_state_output_pins () const
void add_clock_pin (const std::string &pin_name)
std::unordered_set< std::string > get_clock_pins () const
void set_set_reset_behavior (SetResetBehavior sb1, SetResetBehavior sb2)
std::pair< SetResetBehavior, SetResetBehavior > get_set_reset_behavior () const
void set_init_data_category (const std::string &category)
std::string get_init_data_category () const
void set_init_data_identifier (const std::string &identifier)
std::string get_init_data_identifier () const
Public Member Functions inherited from hal::GateType
GateType (const std::string &name)
virtual ~GateType ()=default
u32 get_id () const
std::string get_name () const
BaseType get_base_type () const
std::string to_string () const
bool operator== (const GateType &other) const
bool operator!= (const GateType &other) const
void add_input_pin (std::string pin_name)
void add_input_pins (const std::vector< std::string > &pin_names)
std::vector< std::string > get_input_pins () const
void add_output_pin (std::string pin_name)
void add_output_pins (const std::vector< std::string > &pin_names)
std::vector< std::string > get_output_pins () const
void assign_input_pin_group (const std::string &group_name, const std::map< u32, std::string > &index_to_pin)
void assign_input_pin_groups (const std::unordered_map< std::string, std::map< u32, std::string >> &pin_groups)
std::unordered_map< std::string, std::map< u32, std::string > > get_input_pin_groups () const
void assign_output_pin_group (const std::string &group_name, const std::map< u32, std::string > &index_to_pin)
void assign_output_pin_groups (const std::unordered_map< std::string, std::map< u32, std::string >> &pin_groups)
std::unordered_map< std::string, std::map< u32, std::string > > get_output_pin_groups () const
void add_boolean_function (std::string name, BooleanFunction function)
void add_boolean_functions (const std::unordered_map< std::string, BooleanFunction > &functions)
std::unordered_map< std::string, BooleanFunction > get_boolean_functions () const
Detailed Description
A sequential gate type contains information about its internals such as input and output pins as well as its Boolean functions.
In addition to the standard gate type functionality, it provides mechanisms to specify outputs that depend on the internal state of the sequential gate as well as clock pins.
Member Enumeration Documentation
SetResetBehavior
enum hal::GateTypeSequential::SetResetBehavior strong
Defines the behavior of the gate type in case both set and reset are active at the same time.
Enumerator
U
Default value when no behavior is specified.
L
Set the internal state to 0.
H
Set the internal state to 1.
N
Do not change the internal state.
T
Toggle, i.e., invert the internal state.
X
Set the internal state to X.
Constructor & Destructor Documentation
GateTypeSequential()
hal::GateTypeSequential::GateTypeSequential (const std::string & name, BaseType base_type)
Construct a new LUT gate type by specifying its name and base type. The base type must be either ff or latch .
Parameters
[in] name - The name of the sequential gate type.
[in] base_type - The base type of the sequential gate type.
References hal::GateType::ff, and hal::GateType::latch.
~GateTypeSequential()
hal::GateTypeSequential::~GateTypeSequential () override default
Member Function Documentation
add_state_output_pin()
void hal::GateTypeSequential::add_state_output_pin (const std::string & pin_name)
Add an existing output pin to the collection of output pins that generate their output from the internal state of the gate.
The pin has to be declared as an output pin beforehand.
Parameters
[in] pin_name - The name of the output pin to add.
References log_warning.
Referenced by hal::gate_type_sequential_init().
get_state_output_pins()
std::unordered_set< std::string > hal::GateTypeSequential::get_state_output_pins () const
Get the output pins that use the internal state of the gate to generate their output.
Returns
The set of output pin names.
Referenced by hal::gate_type_sequential_init().
add_inverted_state_output_pin()
void hal::GateTypeSequential::add_inverted_state_output_pin (const std::string & pin_name)
Add an existing output pin to the collection of output pins that generate their output from the inverted internal state of the gate.
The pin has to be declared as an output pin beforehand.
Parameters
[in] pin_name - The name of the output pin to add.
References log_warning.
Referenced by hal::gate_type_sequential_init().
get_inverted_state_output_pins()
std::unordered_set< std::string > hal::GateTypeSequential::get_inverted_state_output_pins () const
Get the output pins that use the inverted internal state of the gate to generate their output.
Returns
The set of output pin names.
Referenced by hal::gate_type_sequential_init().
add_clock_pin()
void hal::GateTypeSequential::add_clock_pin (const std::string & pin_name)
Add an existing input pin to the collection of input pins that are connected to a clock signal.
The pin has to be declared as an input pin beforehand.
Parameters
[in] pin_name - The name of the input pin to add.
References log_warning.
Referenced by hal::gate_type_sequential_init().
get_clock_pins()
std::unordered_set< std::string > hal::GateTypeSequential::get_clock_pins () const
Get the input pins that that are connected to a clock signal.
Returns
The set of input pin names.
Referenced by hal::gate_type_sequential_init().
set_set_reset_behavior()
void hal::GateTypeSequential::set_set_reset_behavior (SetResetBehavior sb1, SetResetBehavior sb2)
Set the behavior that describes the internal state when both set and reset are active at the same time.
Parameters
[in] sb1 - The value specifying the behavior for the internal state.
[in] sb2 - The value specifying the behavior for the inverted internal state.
Referenced by hal::gate_type_sequential_init().
get_set_reset_behavior()
std::pair< GateTypeSequential::SetResetBehavior, GateTypeSequential::SetResetBehavior > hal::GateTypeSequential::get_set_reset_behavior () const
Get the behavior of the internal state and the inverted internal state when both set and reset are active at the same time.
Returns
The values specifying the behavior for the internal and inverted internal state.
Referenced by hal::gate_type_sequential_init().
set_init_data_category()
void hal::GateTypeSequential::set_init_data_category (const std::string & category)
Set the data category in which to find the initialization value.
Parameters
[in] category - The data category.
Referenced by hal::gate_type_sequential_init().
get_init_data_category()
std::string hal::GateTypeSequential::get_init_data_category () const
Get the data category in which to find the initialization value.
Returns
The data category.
Referenced by hal::gate_type_sequential_init().
set_init_data_identifier()
void hal::GateTypeSequential::set_init_data_identifier (const std::string & identifier)
Set the data identifier used to specify the initialization value.
Parameters
[in] identifier - The data identifier.
Referenced by hal::gate_type_sequential_init().
get_init_data_identifier()
std::string hal::GateTypeSequential::get_init_data_identifier () const
Get the data identifier used to specify the initialization value.
Returns
The data identifier.
Referenced by hal::gate_type_sequential_init().
The documentation for this class was generated from the following files:
hal_core/netlist/gate_library/gate_type/gate_type_sequential.h
/home/runner/work/hal/hal/src/netlist/gate_library/gate_type/gate_type_sequential.cpp