hal: hal::core_utils Namespace Reference
hal::core_utils Namespace Reference
HAL Core
Classes
class DirectoryRange
class RecursiveDirectoryRange
Functions
CORE_API u64 get_bit (const u64 value, const u64 index)
CORE_API u64 set_bit (const u64 value, const u64 index)
CORE_API u64 clear_bit (const u64 value, const u64 index)
CORE_API u64 toggle_bit (const u64 value, const u64 index)
template<typename T >
CORE_API bool ends_with (const T &s, const T &end)
template<typename T >
CORE_API bool starts_with (const T &s, const T &start)
template<typename T >
CORE_API bool is_integer (const T &s)
template<typename T >
CORE_API bool is_floating_point (const T &s)
template<typename T >
CORE_API std::vector< T > split (const T &s, const char delim, bool obey_brackets=false)
template<typename T >
CORE_API T ltrim (const T &s, const char *to_remove=" \t\r\n")
template<typename T >
CORE_API T rtrim (const T &s, const char *to_remove=" \t\r\n")
template<typename T >
CORE_API T trim (const T &s, const char *to_remove=" \t\r\n")
template<typename T >
CORE_API T replace (const T &str, const T &search, const T &replace)
template<typename T , class Transform >
CORE_API std::string join (const std::string &joiner, const T &items, const Transform &transform)
template<typename T >
CORE_API std::string join (const std::string &joiner, const T &items)
template<typename T >
CORE_API T to_upper (const T &s)
template<typename T >
CORE_API T to_lower (const T &s)
template<typename T >
CORE_API u32 num_of_occurrences (const T &s, const T &substr)
CORE_API bool file_exists (const std::string &filename)
CORE_API bool folder_exists_and_is_accessible (const std::filesystem::path &folder)
CORE_API std::filesystem::path which (const std::string &name, const std::string &path="")
CORE_API std::filesystem::path get_binary_directory ()
CORE_API std::filesystem::path get_base_directory ()
CORE_API std::filesystem::path get_library_directory ()
CORE_API std::filesystem::path get_share_directory ()
CORE_API std::filesystem::path get_user_share_directory ()
CORE_API std::filesystem::path get_config_directory ()
CORE_API std::filesystem::path get_user_config_directory ()
CORE_API std::filesystem::path get_default_log_directory (std::filesystem::path source_file="")
CORE_API std::vector< std::filesystem::path > get_gate_library_directories ()
CORE_API std::vector< std::filesystem::path > get_plugin_directories ()
CORE_API std::filesystem::path get_first_directory_exists (std::vector< std::filesystem::path > path_hints)
CORE_API std::filesystem::path get_file (std::string file_name, std::vector< std::filesystem::path > path_hints)
CORE_API std::string get_open_source_licenses ()
Function Documentation
get_bit()
CORE_API u64 hal::core_utils::get_bit (const u64 value, const u64 index) inline
Returns a single bit of an integer value.
Parameters
[in] value - The integer.
[in] index - The bit's position.
Returns
The specified bit (0 or 1).
set_bit()
CORE_API u64 hal::core_utils::set_bit (const u64 value, const u64 index) inline
Sets a single bit of an integer to 1.
Parameters
[in] value - The integer.
[in] index - The bit's position.
Returns
The manipulated value.
clear_bit()
CORE_API u64 hal::core_utils::clear_bit (const u64 value, const u64 index) inline
Clears a single bit of an integer to 0.
Parameters
[in] value - The integer.
[in] index - The bit's position.
Returns
The manipulated value.
toggle_bit()
CORE_API u64 hal::core_utils::toggle_bit (const u64 value, const u64 index) inline
Toggles a single bit of an integer.
Parameters
[in] value - The integer.
[in] index - The bit's position.
Returns
The manipulated value.
ends_with()
template<typename T > CORE_API bool hal::core_utils::ends_with (const T & s, const T & end)
Checks whether a string ends with another string.
Parameters
[in] s - The string to analyze.
[in] end - The ending to check for.
Returns
True, if s ends with end.
Referenced by hal::gate_library_manager::load_file().
starts_with()
template<typename T > CORE_API bool hal::core_utils::starts_with (const T & s, const T & start)
Checks whether a string begins with another string.
Parameters
[in] s - The string to analyze.
[in] start - The beginning to check for.
Returns
True, if s begins with start.
is_integer()
template<typename T > CORE_API bool hal::core_utils::is_integer (const T & s)
Checks whether a string represents an integer.
Parameters
[in] s - The string to analyze.
Returns
True, if s contains an integer.
is_floating_point()
template<typename T > CORE_API bool hal::core_utils::is_floating_point (const T & s)
Checks whether a string represents a real number.
Parameters
[in] s - The string to analyze.
Returns
True, if s contains a real number.
split()
template<typename T > CORE_API std::vector<T> hal::core_utils::split (const T & s, const char delim, bool obey_brackets = false)
Splits a string into a vector of strings. The split delimiter can be specified. The delimiters are removed in the splitting process.
Parameters
[in] s - The string to split.
[in] delim - The delimiter, indicating where to split.
[in] obey_brackets - Flag to indicate whether brackets are obeyed.
Returns
The string parts.
Referenced by which().
ltrim()
template<typename T > CORE_API T hal::core_utils::ltrim (const T & s, const char * to_remove = " \t\r\n")
Removes any whitespace characters from the beginning of a string.
Parameters
[in] s - The string to trim.
[in] to_remove - All chars that should be removed.
Returns
The trimmed string.
rtrim()
template<typename T > CORE_API T hal::core_utils::rtrim (const T & s, const char * to_remove = " \t\r\n")
Removes any whitespace characters from the end of a string.
Parameters
[in] s - The string to trim.
[in] to_remove - All chars that should be removed.
Returns
The trimmed string.
trim()
template<typename T > CORE_API T hal::core_utils::trim (const T & s, const char * to_remove = " \t\r\n")
Removes any whitespace characters from the beginning and the end of a string.
Parameters
[in] s - The string to trim.
[in] to_remove - All chars that should be removed.
Returns
The trimmed string.
Referenced by hal::ProgramOptions::add(), hal::BooleanFunction::BooleanFunction(), hal::Module::set_name(), hal::Net::set_name(), and hal::Gate::set_name().
replace()
template<typename T > CORE_API T hal::core_utils::replace (const T & str, const T & search, const T & replace)
Replaces substring from begin to end of a string.
Parameters
[in] str - The string which is subject to replacement.
[in] search - The search substring which should be replaced.
[in] replace - The replacement string which replaces all occurrences of search.
Returns
String with replaced substring.
join() [1/2]
template<typename T , class Transform > CORE_API std::string hal::core_utils::join (const std::string & joiner, const T & items, const Transform & transform)
Joins all elements of a collection with a joiner-string. Every element is transformed before being printed.
Parameters
[in] joiner - The string to put between the elements.
[in] items - The collection of elements to join.
[in] transform - The transformation function for each element.
Returns
The combined string.
Referenced by join(), hal::ProgramOptions::parse(), and hal::ProgramArguments::set_option().
join() [2/2]
template<typename T > CORE_API std::string hal::core_utils::join (const std::string & joiner, const T & items)
Joins all elements of a collection with a joiner-string.
Parameters
[in] joiner - The string to put between the elements.
[in] items - The collection of elements to join.
Returns
The combined string.
References join().
to_upper()
template<typename T > CORE_API T hal::core_utils::to_upper (const T & s)
Convert a string to upper case.
Parameters
[in] s - The string to convert.
Returns
The converted string.
to_lower()
template<typename T > CORE_API T hal::core_utils::to_lower (const T & s)
Convert a string to lower case.
Parameters
[in] s - The string to convert.
Returns
The converted string.
Referenced by hal::HDLParserDispatcher::parse().
num_of_occurrences()
template<typename T > CORE_API u32 hal::core_utils::num_of_occurrences (const T & s, const T & substr)
Counts number of substring occurrences in a string.
Parameters
[in] s - String containing the substring.
[in] substr - Substring.
Returns
The number of occurrences.
file_exists()
bool hal::core_utils::file_exists (const std::string & filename)
Checks whether a file exists.
Parameters
[in] filename - The file to check.
Returns
True, if file exists
folder_exists_and_is_accessible()
bool hal::core_utils::folder_exists_and_is_accessible (const std::filesystem::path & folder)
Checks whether a directory exists and access rights are available.
Parameters
[in] folder - The directory to check.
Returns
True, if folder exists and is accessible.
which()
std::filesystem::path hal::core_utils::which (const std::string & name, const std::string & path = "")
Locate an executable in the given path environment
Parameters
[in] name - The executable name
[in] path - PATH to search (defaults to PATH environment variable)
Returns
path if executable is found else empty std::filesystem::path.
References split(), and UNUSED.
Referenced by get_base_directory().
get_binary_directory()
std::filesystem::path hal::core_utils::get_binary_directory ()
Get the path to the executable of HAL.
Returns
The path.
Referenced by hal::core_utils_init(), and get_base_directory().
get_base_directory()
std::filesystem::path hal::core_utils::get_base_directory ()
Get the base path to the HAL installation.
Use Environment Variable HAL_BASE_PATH
If current executable is hal (not e.g. python3 interpreter) use it's path to determine base path.
Try to find hal executable in path and use its base path.
Returns
The path.
References die, get_binary_directory(), and which().
Referenced by hal::core_utils_init(), get_config_directory(), get_library_directory(), and get_share_directory().
get_library_directory()
std::filesystem::path hal::core_utils::get_library_directory ()
Get the path to the shared and static libraries of HAL.
Relative to the binary directory.
Returns
The path.
References get_base_directory(), and get_first_directory_exists().
Referenced by hal::core_utils_init(), hal::PluginPythonShell::exec(), and get_plugin_directories().
get_share_directory()
std::filesystem::path hal::core_utils::get_share_directory ()
Get the path to the shared objects of HAL.
Relative to the binary directory.
Returns
The path.
References get_base_directory(), and get_first_directory_exists().
Referenced by hal::core_utils_init(), and get_gate_library_directories().
get_user_share_directory()
std::filesystem::path hal::core_utils::get_user_share_directory ()
Get the path to shared objects and files provided by the user.
home/.local/share for Unix
Returns
The path.
Referenced by hal::core_utils_init(), get_default_log_directory(), get_gate_library_directories(), and get_plugin_directories().
get_config_directory()
std::filesystem::path hal::core_utils::get_config_directory ()
Get the path to the read-only global configuration directory of HAL.
Relative to the binary directory.
Returns
The path.
References get_base_directory(), and get_first_directory_exists().
get_user_config_directory()
std::filesystem::path hal::core_utils::get_user_config_directory ()
Get the path to the configuration directory of the user.
home/.config/hal for Unix
Returns
The path.
Referenced by hal::core_utils_init().
get_default_log_directory()
std::filesystem::path hal::core_utils::get_default_log_directory (std::filesystem::path source_file = "")
Get the path to the default directory for log files.
If an hdl source file is provided, the function returns the parent directory, otherwise get_user_share_directory() / "log".
Parameters
[in] source_file - The hdl source file.
Returns
The path.
References get_user_share_directory().
Referenced by hal::core_utils_init().
get_gate_library_directories()
std::vector< std::filesystem::path > hal::core_utils::get_gate_library_directories ()
Get the paths where gate libraries are searched.
Contains the share and user share directories.
Returns
A vector of paths.
References get_share_directory(), and get_user_share_directory().
Referenced by hal::core_utils_init(), hal::gate_library_manager::get_gate_library(), and hal::gate_library_manager::load_all().
get_plugin_directories()
std::vector< std::filesystem::path > hal::core_utils::get_plugin_directories ()
Get the paths where plugins are searched.
Contains the library and user share directories.
Returns
A vector of paths.
References get_library_directory(), and get_user_share_directory().
Referenced by hal::core_utils_init().
get_first_directory_exists()
std::filesystem::path hal::core_utils::get_first_directory_exists (std::vector< std::filesystem::path > path_hints)
Returns the first directory of all path hints that exists.
Parameters
[in] path_hints - A vector of hints.
Returns
The first existing path. If none exists an empty string is returned.
Referenced by get_config_directory(), get_library_directory(), and get_share_directory().
get_file()
std::filesystem::path hal::core_utils::get_file (std::string file_name, std::vector< std::filesystem::path > path_hints)
Search in all paths provided by path hints (used in order) for a given filename.
Parameters
[in] file_name - The filename to search for.
[in] path_hints - A vector of hints.
Returns
The first to match. If none matches an empty string is returned.
Referenced by hal::gate_library_manager::get_gate_library().
get_open_source_licenses()
std::string hal::core_utils::get_open_source_licenses ()
Get all licenses of used OpenSource Projects.
Returns
All open source licenses;