hal: event_controls Namespace Reference
event_controls Namespace Reference
Netlist » Event Handler
Functions
NETLIST_API void enable_all (bool flag)
Function Documentation
enable_all()
void event_controls::enable_all (bool flag)
Enables/disables callbacks for all event handlers.
Enabled by default.
Parameters
[in] flag - True to enable, false to disable.
References netlist_event_handler::enable(), module_event_handler::enable(), net_event_handler::enable(), and gate_event_handler::enable().