hal: gate Class Reference
gate Class Reference
Netlist
#include <gate.h>
Public Member Functions
u32 get_id () const
std::shared_ptr< netlist > get_netlist () const
std::string get_name () const
void set_name (const std::string &name)
std::shared_ptr< const gate_type > get_type () const
bool has_location () const
void set_location_x (float x)
float get_location_x () const
void set_location_y (float y)
float get_location_y () const
void set_location (const std::pair< float, float > &location)
std::pair< float, float > get_location () const
std::shared_ptr< module > get_module () const
boolean_function get_boolean_function (const std::string &name="") const
std::unordered_map< std::string, boolean_function > get_boolean_functions (bool only_custom_functions=false) const
void add_boolean_function (const std::string &name, const boolean_function &func)
bool mark_vcc_gate ()
bool mark_gnd_gate ()
bool unmark_vcc_gate ()
bool unmark_gnd_gate ()
bool is_vcc_gate () const
bool is_gnd_gate () const
std::vector< std::string > get_input_pins () const
std::vector< std::string > get_output_pins () const
std::set< std::shared_ptr< net > > get_fan_in_nets () const
std::shared_ptr< net > get_fan_in_net (const std::string &pin_type) const
std::set< std::shared_ptr< net > > get_fan_out_nets () const
std::shared_ptr< net > get_fan_out_net (const std::string &pin_type) const
std::set< endpoint > get_unique_predecessors (const std::function< bool(const std::string &starting_pin, const endpoint &ep)> &filter=nullptr) const
std::vector< endpoint > get_predecessors (const std::function< bool(const std::string &starting_pin, const endpoint &ep)> &filter=nullptr) const
endpoint get_predecessor (const std::string &which_pin) const
std::set< endpoint > get_unique_successors (const std::function< bool(const std::string &starting_pin, const endpoint &ep)> &filter=nullptr) const
std::vector< endpoint > get_successors (const std::function< bool(const std::string &starting_pin, const endpoint &ep)> &filter=nullptr) const
Public Member Functions inherited from data_container
data_container ()=default
virtual ~data_container ()=default
bool set_data (const std::string &category, const std::string &key, const std::string &data_type, const std::string &value, const bool log_with_info_level=false)
bool delete_data (const std::string &category, const std::string &key, const bool log_with_info_level=false)
std::map< std::tuple< std::string, std::string >, std::tuple< std::string, std::string > > get_data () const
std::tuple< std::string, std::string > get_data_by_key (const std::string &category, const std::string &key) const
std::vector< std::tuple< std::string, std::string > > get_data_keys () const
Friends
class netlist_internal_manager
Detailed Description
Gate class containing information about a gate including its location, functions, and module.
Member Function Documentation
get_id()
u32 gate::get_id () const
Gets the unique id of the gate.
Returns
The gate's id.
Referenced by get_predecessors(), and PYBIND11_PLUGIN().
get_netlist()
std::shared_ptr< netlist > gate::get_netlist () const
Gets the parent netlist of the gate.
Returns
The netlist.
Referenced by PYBIND11_PLUGIN().
get_name()
std::string gate::get_name () const
Gets the gate's name.
Returns
The name.
Referenced by get_fan_in_net(), get_fan_out_net(), get_predecessor(), get_predecessors(), and PYBIND11_PLUGIN().
set_name()
void gate::set_name (const std::string & name)
Sets the gate's name.
Parameters
[in] name - The new name.
References log_error, log_info, gate_event_handler::name_changed, gate_event_handler::notify(), and core_utils::trim().
Referenced by PYBIND11_PLUGIN().
get_type()
std::shared_ptr< const gate_type > gate::get_type () const
Gets the type of the gate.
Returns
The gate's type.
Referenced by get_fan_in_net(), get_fan_out_net(), and PYBIND11_PLUGIN().
has_location()
bool gate::has_location () const
Checks whether the gate's location in the layout is available.
Returns
True if valid location data is available, false otherwise.
Referenced by PYBIND11_PLUGIN().
set_location_x()
void gate::set_location_x (float x)
Sets the physical location x-coordinate of the gate in the layout. Only positive values are valid, negative values will be regarded as no location assigned.
Parameters
[in] x - The gate's x-coordinate.
References gate_event_handler::location_changed, and gate_event_handler::notify().
Referenced by PYBIND11_PLUGIN(), and set_location().
get_location_x()
float gate::get_location_x () const
Gets the physical location x-coordinate of the gate in the layout.
Returns
The gate's x-coordinate.
Referenced by PYBIND11_PLUGIN().
set_location_y()
void gate::set_location_y (float y)
Sets the physical location y-coordinate of the gate in the layout. Only positive values are valid, negative values will be regarded as no location assigned.
Parameters
[in] y - The gate's y-coordinate.
References gate_event_handler::location_changed, and gate_event_handler::notify().
Referenced by PYBIND11_PLUGIN(), and set_location().
get_location_y()
float gate::get_location_y () const
Gets the physical location y-coordinate of the gate in the layout.
Returns
The gate's y-coordinate.
Referenced by PYBIND11_PLUGIN().
set_location()
void gate::set_location (const std::pair< float, float > & location)
Sets the physical location of the gate in the layout.
Parameters
[in] location - A pair <x-coordinate, y-coordinate>.
References set_location_x(), and set_location_y().
Referenced by PYBIND11_PLUGIN().
get_location()
std::pair< float, float > gate::get_location () const
Gets the physical location of the gate in the layout.
Returns
A pair <x-coordinate, y-coordinate>.
Referenced by PYBIND11_PLUGIN().
get_module()
std::shared_ptr< module > gate::get_module () const
Gets the module in which this gate is contained.
Returns
The module.
Referenced by PYBIND11_PLUGIN().
get_boolean_function()
boolean_function gate::get_boolean_function (const std::string & name = "") const
Get the boolean function associated with a specific name. This name can for example be an output pin of the gate or a defined functionality like "reset". If name is empty, the function of the first output pin is returned. If there is no function for the given name, an empty function is returned.
Parameters
[in] name - The function name.
Returns
The boolean function.
References gate_type::lut.
Referenced by PYBIND11_PLUGIN().
get_boolean_functions()
std::unordered_map< std::string, boolean_function > gate::get_boolean_functions (bool only_custom_functions = false) const
Get a map from function name to boolean function for all boolean functions associated with this gate.
Parameters
[in] only_custom_functions - If true, this returns only the functions which were set via add_boolean_function.
Returns
A map from function name to function.
References gate_type_lut::get_config_data_category(), data_container::get_data_by_key(), get_input_pins(), get_output_pins(), gate_type::lut, boolean_function::optimize(), and boolean_function::ZERO.
Referenced by PYBIND11_PLUGIN().
add_boolean_function()
void gate::add_boolean_function (const std::string & name, const boolean_function & func)
Add the boolean function with the specified name only for this gate.
Parameters
[in] name - The function name, usually an output port.
[in] func - The function.
References get_input_pins(), boolean_function::get_truth_table(), log_error, gate_type::lut, data_container::set_data(), and boolean_function::X.
Referenced by PYBIND11_PLUGIN().
mark_vcc_gate()
bool gate::mark_vcc_gate ()
Mark this gate as a global vcc gate.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
mark_gnd_gate()
bool gate::mark_gnd_gate ()
Mark this gate as a global gnd gate.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
unmark_vcc_gate()
bool gate::unmark_vcc_gate ()
Unmark this gate as a global vcc gate.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
unmark_gnd_gate()
bool gate::unmark_gnd_gate ()
Unmark this gate as a global gnd gate.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
is_vcc_gate()
bool gate::is_vcc_gate () const
Checks whether this gate is a global vcc gate.
Returns
True if the gate is a global vcc gate.
Referenced by PYBIND11_PLUGIN().
is_gnd_gate()
bool gate::is_gnd_gate () const
Checks whether this gate is a global gnd gate.
Returns
True if the gate is a global gnd gate.
Referenced by PYBIND11_PLUGIN().
get_input_pins()
std::vector< std::string > gate::get_input_pins () const
Get a list of all input pin types of the gate.
Returns
A vector of input pin types.
Referenced by add_boolean_function(), get_boolean_functions(), and PYBIND11_PLUGIN().
get_output_pins()
std::vector< std::string > gate::get_output_pins () const
Get a list of all output pin types of the gate.
Returns
A vector of output pin types.
Referenced by get_boolean_functions(), and PYBIND11_PLUGIN().
get_fan_in_nets()
std::set< std::shared_ptr< net > > gate::get_fan_in_nets () const
Get a set of all fan-in nets of the gate, i.e. all nets that are connected to one of the input pins.
Returns
A set of all connected input nets.
Referenced by module::get_input_nets(), and PYBIND11_PLUGIN().
get_fan_in_net()
std::shared_ptr< net > gate::get_fan_in_net (const std::string & pin_type) const
Get the fan-in net which is connected to a specific input pin.
Parameters
[in] pin_type - The input pin type.
Returns
The connected input net.
References get_name(), get_type(), and log_debug.
Referenced by PYBIND11_PLUGIN().
get_fan_out_nets()
std::set< std::shared_ptr< net > > gate::get_fan_out_nets () const
Get a set of all fan-out nets of the gate, i.e. all nets that are connected to one of the output pins.
Returns
A set of all connected output nets.
Referenced by module::get_internal_nets(), module::get_output_nets(), and PYBIND11_PLUGIN().
get_fan_out_net()
std::shared_ptr< net > gate::get_fan_out_net (const std::string & pin_type) const
Get the fan-out net which is connected to a specific output pin.
Parameters
[in] pin_type - The output pin type.
Returns
The connected output net.
References get_name(), get_type(), and log_debug.
Referenced by PYBIND11_PLUGIN().
get_unique_predecessors()
std::set< endpoint > gate::get_unique_predecessors (const std::function< bool(const std::string &starting_pin, const endpoint &ep)> & filter = nullptr) const
Get a set of all unique predecessor endpoints of the gate. A filter can be supplied which filters out all potential values that return false.
Parameters
[in] filter - a function to filter the output. Leave empty for no filtering.
Returns
A set of unique predecessor endpoints.
References get_predecessors().
Referenced by PYBIND11_PLUGIN().
get_predecessors()
std::vector< endpoint > gate::get_predecessors (const std::function< bool(const std::string &starting_pin, const endpoint &ep)> & filter = nullptr) const
Get a vector of all direct predecessor endpoints of the gate. A filter can be supplied which filters out all potential values that return false.
Parameters
[in] filter - a function to filter the output. Leave empty for no filtering.
Returns
A vector of predecessor endpoints.
References get_id(), get_name(), net::get_src(), and log_debug.
Referenced by get_predecessor(), get_unique_predecessors(), and PYBIND11_PLUGIN().
get_predecessor()
endpoint gate::get_predecessor (const std::string & which_pin) const
Get the direct predecessor endpoint of the gate connected to a specific input pin.
Parameters
[in] which_pin - the pin of this gate to get the predecessor from.
Returns
The predecessor endpoint.
References get_name(), get_predecessors(), and log_error.
Referenced by PYBIND11_PLUGIN().
get_unique_successors()
std::set< endpoint > gate::get_unique_successors (const std::function< bool(const std::string &starting_pin, const endpoint &ep)> & filter = nullptr) const
Get a set of all unique successor endpoints of the gate. A filter can be supplied which filters out all potential values that return false.
Parameters
[in] filter - a function to filter the output. Leave empty for no filtering.
Returns
A set of unique successor endpoints.
References get_successors().
Referenced by PYBIND11_PLUGIN().
get_successors()
std::vector< endpoint > gate::get_successors (const std::function< bool(const std::string &starting_pin, const endpoint &ep)> & filter = nullptr) const
Get a vector of all direct successor endpoints of the gate. A filter can be supplied which filters out all potential values that return false.
Parameters
[in] filter - a function to filter the output. Leave empty for no filtering.
Returns
A vector of successor endpoints.
References net::get_dsts().
Referenced by get_unique_successors(), and PYBIND11_PLUGIN().
Friends And Related Function Documentation
netlist_internal_manager
friend class netlist_internal_manager friend
The documentation for this class was generated from the following files:
netlist/gate.h
/home/runner/work/hal/hal/src/netlist/gate.cpp