hal: netlist_factory Namespace Reference
netlist_factory Namespace Reference
Netlist
Functions
NETLIST_API std::shared_ptr< netlist > create_netlist (const std::string &gate_library_name)
NETLIST_API std::shared_ptr< netlist > load_netlist (const hal::path &hdl_file, const std::string &language, const std::string &gate_library_name)
NETLIST_API std::shared_ptr< netlist > load_netlist (const hal::path &hal_file)
NETLIST_API std::shared_ptr< netlist > load_netlist (const program_arguments &args)
Function Documentation
create_netlist()
std::shared_ptr< netlist > netlist_factory::create_netlist (const std::string & gate_library_name)
Creates a new netlist for a specific gate library.
Parameters
[in] gate_library_name - Name of hardware gate library.
Returns
The new netlist.
References gate_library_manager::get_gate_library(), and log_critical.
Referenced by hdl_parser_verilog::parse(), hdl_parser_vhdl::parse(), and PYBIND11_PLUGIN().
load_netlist() [1/3]
std::shared_ptr< netlist > netlist_factory::load_netlist (const hal::path & hdl_file, const std::string & language, const std::string & gate_library_name)
Creates a new netlist for a specific file.
Parameters
[in] hdl_file - Name of the hdl file.
[in] language - Programming language used in file_name.
[in] gate_library_name - Name of hardware gate library.
Returns
The new netlist.
References log_critical, and hdl_parser_dispatcher::parse().
Referenced by PYBIND11_PLUGIN().
load_netlist() [2/3]
std::shared_ptr< netlist > netlist_factory::load_netlist (const hal::path & hal_file)
Creates a new netlist for a specific '.hal' file.
Parameters
[in] hal_file - Name of the '.hal' file. file.
Returns
The new netlist.
References netlist_serializer::deserialize_from_file(), and log_critical.
load_netlist() [3/3]
std::shared_ptr< netlist > netlist_factory::load_netlist (const program_arguments & args)
Creates a new netlist entirely from program options. Invokes parsers or serializers as needed.
Parameters
[in] args - Command line options.
Returns
The new netlist.
References netlist_serializer::deserialize_from_file(), program_arguments::get_parameter(), program_arguments::is_option_set(), log_critical, and hdl_parser_dispatcher::parse().