if(BUILD_TESTS)
    include_directories(${gtest_SOURCE_DIR}/include ${gtest_SOURCE_DIR} ${CMAKE_SOURCE_DIR}/include ${CMAKE_SOURCE_DIR}/tests ${CMAKE_SOURCE_DIR}/plugins/vhdl_parser/include)

    foreach(name vhdl_lexer vhdl_syntax vhdl_elaboration vhdl_parser)
        add_executable(runTest-${name} ${name}.cpp)
        target_link_libraries(runTest-${name} vhdl_parser pthread gtest hal::core hal::netlist test_utils)
        add_test(runTest-${name} ${CMAKE_BINARY_DIR}/bin/hal_plugins/runTest-${name} --gtest_output=xml:${CMAKE_BINARY_DIR}/gtestresults-runBasicTests.xml)
        if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
            add_sanitizers(runTest-${name})
        endif()
    endforeach()
endif()
