hal: netlist_event_handler Namespace Reference
netlist_event_handler Namespace Reference
Netlist » Event Handler
Enumerations
enum event {
id_changed, input_filename_changed, design_name_changed, device_name_changed,
marked_global_vcc, marked_global_gnd, unmarked_global_vcc, unmarked_global_gnd,
marked_global_input, marked_global_output, marked_global_inout, unmarked_global_input,
unmarked_global_output, unmarked_global_inout
}
Functions
NETLIST_API void enable (bool flag)
NETLIST_API void notify (event ev, std::shared_ptr< netlist > netlist, u32 associated_data=0xFFFFFFFF)
NETLIST_API void register_callback (const std::string &name, std::function< void(event e, std::shared_ptr< netlist > netlist, u32 associated_data)> function)
NETLIST_API void unregister_callback (const std::string &name)
void register_callback (const std::string &name, std::function< void(event, std::shared_ptr< netlist >, u32)> function)
Enumeration Type Documentation
event
enum netlist_event_handler::event
Enumerator
id_changed
associated_data = old id
input_filename_changed
no associated_data
design_name_changed
no associated_data
device_name_changed
no associated_data
marked_global_vcc
associated_data = id of gate
marked_global_gnd
associated_data = id of gate
unmarked_global_vcc
associated_data = id of gate
unmarked_global_gnd
associated_data = id of gate
marked_global_input
associated_data = id of net
marked_global_output
associated_data = id of net
marked_global_inout
associated_data = id of net
unmarked_global_input
associated_data = id of net
unmarked_global_output
associated_data = id of net
unmarked_global_inout
associated_data = id of net
Function Documentation
enable()
void netlist_event_handler::enable (bool flag)
Enables/disables callbacks for this handler.
Enabled by default.
Parameters
[in] flag - True to enable, false to disable.
Referenced by event_controls::enable_all().
notify()
void netlist_event_handler::notify (event ev, std::shared_ptr< netlist > netlist, u32 associated_data = 0xFFFFFFFF)
Executes all registered callbacks.
Parameters
[in] ev - the event which occured.
[in] netlist - The affected object.
[in] associated_data - may have a meaning depending on the event type.
Referenced by netlist::mark_global_input_net(), netlist::mark_global_output_net(), netlist::mark_gnd_gate(), netlist::mark_vcc_gate(), netlist::set_design_name(), netlist::set_device_name(), netlist::set_id(), netlist::set_input_filename(), netlist::unmark_global_input_net(), netlist::unmark_global_output_net(), netlist::unmark_gnd_gate(), and netlist::unmark_vcc_gate().
register_callback() [1/2]
NETLIST_API void netlist_event_handler::register_callback (const std::string & name, std::function< void(event e, std::shared_ptr< netlist > netlist, u32 associated_data)> function)
Registers a callback function.
Parameters
[in] name - name of the callback, used for callback removal.
[in] function - The callback function.
Referenced by event_log::initialize().
unregister_callback()
void netlist_event_handler::unregister_callback (const std::string & name)
Removes a callback function.
Parameters
[in] name - name of the callback.
register_callback() [2/2]
void netlist_event_handler::register_callback (const std::string & name, std::function< void(event, std::shared_ptr< netlist >, u32)> function)