hal: module Class Reference
module Class Reference
#include <module.h>
Public Member Functions
u32 get_id () const
std::string get_name () const
void set_name (const std::string &name)
std::shared_ptr< module > get_parent_module () const
bool set_parent_module (const std::shared_ptr< module > &new_parent)
std::set< std::shared_ptr< module > > get_submodules (const std::function< bool(const std::shared_ptr< module > &)> &filter=nullptr, bool recursive=false) const
bool contains_module (const std::shared_ptr< module > &other, bool recursive=false) const
std::shared_ptr< netlist > get_netlist () const
std::set< std::shared_ptr< net > > get_input_nets () const
std::set< std::shared_ptr< net > > get_output_nets () const
std::set< std::shared_ptr< net > > get_internal_nets () const
bool assign_gate (std::shared_ptr< gate > gate)
bool remove_gate (std::shared_ptr< gate > gate)
bool contains_gate (const std::shared_ptr< gate > gate, bool recursive=false) const
std::shared_ptr< gate > get_gate_by_id (const u32 id, bool recursive=false) const
std::set< std::shared_ptr< gate > > get_gates (const std::function< bool(const std::shared_ptr< gate > &)> &filter=nullptr, bool recursive=false) const
Public Member Functions inherited from data_container
data_container ()=default
virtual ~data_container ()=default
bool set_data (const std::string &category, const std::string &key, const std::string &data_type, const std::string &value, const bool log_with_info_level=false)
bool delete_data (const std::string &category, const std::string &key, const bool log_with_info_level=false)
std::map< std::tuple< std::string, std::string >, std::tuple< std::string, std::string > > get_data () const
std::tuple< std::string, std::string > get_data_by_key (const std::string &category, const std::string &key) const
std::vector< std::tuple< std::string, std::string > > get_data_keys () const
Friends
class netlist_internal_manager
class netlist
Detailed Description
Module class containing information about a module including its gates, submodules, and parent module.
Member Function Documentation
get_id()
u32 module::get_id () const
Get the module's id.
Returns
The module's id.
Referenced by PYBIND11_PLUGIN().
get_name()
std::string module::get_name () const
Get the module's name.
Returns
The module's name.
Referenced by PYBIND11_PLUGIN().
set_name()
void module::set_name (const std::string & name)
Set the module's name.
[in] name - The new name.
References log_error, gate_event_handler::name_changed, module_event_handler::notify(), and core_utils::trim().
Referenced by hdl_parser_verilog::parse(), and PYBIND11_PLUGIN().
get_parent_module()
std::shared_ptr< module > module::get_parent_module () const
Get the parent of this module.
This returns nullptr for the top module.
Returns
The parent module.
Referenced by PYBIND11_PLUGIN().
set_parent_module()
bool module::set_parent_module (const std::shared_ptr< module > & new_parent)
Sets a new parent for this module.
If the new parent is a submodule of this module, the new parent is added as a direct submodule to the old parent first.
Parameters
[in] new_parent - the new parent module
Returns
True if the parent was changed
References get_netlist(), get_submodules(), log_error, module_event_handler::notify(), module_event_handler::parent_changed, module_event_handler::submodule_added, and module_event_handler::submodule_removed.
Referenced by PYBIND11_PLUGIN().
get_submodules()
std::set< std::shared_ptr< module > > module::get_submodules (const std::function< bool(const std::shared_ptr< module > &)> & filter = nullptr, bool recursive = false) const
Get all direct submodules of this module.
If recursive is true, all indirect submodules are also included.
Parameters
[in] filter - Filter for the modules
[in] recursive - Look into submodules as well
Returns
The set of submodules
Referenced by PYBIND11_PLUGIN(), and set_parent_module().
contains_module()
bool module::contains_module (const std::shared_ptr< module > & other, bool recursive = false) const
Checks whether another module is a submodule of this module.
If recursive is true, all indirect submodules are also included.
Parameters
[in] other - Other module to check
[in] recursive - Look into submodules as well
Returns
True if the other module is a submodule
Referenced by PYBIND11_PLUGIN().
get_netlist()
std::shared_ptr< netlist > module::get_netlist () const
Get the netlist this module is associated with.
Returns
The netlist.
References netlist::get_shared().
Referenced by PYBIND11_PLUGIN(), and set_parent_module().
get_input_nets()
std::set< std::shared_ptr< net > > module::get_input_nets () const
Get the input nets to this module.
A module input net is either a global input to the netlist or has a source outside of the module.
Returns
The set of module input nets.
References endpoint::gate, gate::get_fan_in_nets(), get_gates(), net::get_src(), and netlist::is_global_input_net().
Referenced by PYBIND11_PLUGIN().
get_output_nets()
std::set< std::shared_ptr< net > > module::get_output_nets () const
Get the output nets of this module.
A module output net is either a global output of the netlist or has a destination outside of the module.
Returns
The set of module output nets.
References net::get_dsts(), gate::get_fan_out_nets(), get_gates(), and netlist::is_global_output_net().
Referenced by PYBIND11_PLUGIN().
get_internal_nets()
std::set< std::shared_ptr< net > > module::get_internal_nets () const
Get the internal nets of this module.
A net is internal if its source and at least one output are inside the module.
Therefore it may contain some nets that are also regarded as output nets.
Returns
The set of module input nets.
References net::get_dsts(), gate::get_fan_out_nets(), and get_gates().
Referenced by PYBIND11_PLUGIN().
assign_gate()
bool module::assign_gate (std::shared_ptr< gate > gate)
Moves a gate into this module.
The gate is removed from its previous module in the process.
Parameters
[in] gate - The gate to move.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
remove_gate()
bool module::remove_gate (std::shared_ptr< gate > gate)
Removes a gate from the module.
It is automatically moved to the netlist's top module.
Parameters
[in] gate - Pointer to the gate pointer.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
contains_gate()
bool module::contains_gate (const std::shared_ptr< gate > gate, bool recursive = false) const
Checks whether a gate is in the module.
If recursive is true, all submodules are searched as well.
Parameters
[in] gate - The gate to check.
[in] recursive - Look into submodules too
Returns
True if the gate is in module
Referenced by PYBIND11_PLUGIN().
get_gate_by_id()
std::shared_ptr< gate > module::get_gate_by_id (const u32 id, bool recursive = false) const
Get a gate specified by id.
If recursive is true, all submodules are searched as well.
Parameters
[in] id - The gate's id.
[in] recursive - Look into submodules too
Returns
The gate or a nullptr.
Referenced by PYBIND11_PLUGIN().
get_gates()
std::set< std::shared_ptr< gate > > module::get_gates (const std::function< bool(const std::shared_ptr< gate > &)> & filter = nullptr, bool recursive = false) const
Get all gates of the module.
You can filter the set before output with the optional parameters.
If recursive is true, all submodules are searched as well.
Parameters
[in] filter - Filter for the returned gates
[in] recursive - Look into submodules too
Returns
A set of gates.
Referenced by get_input_nets(), get_internal_nets(), get_output_nets(), and PYBIND11_PLUGIN().
Friends And Related Function Documentation
netlist_internal_manager
friend class netlist_internal_manager friend
netlist
friend class netlist friend
The documentation for this class was generated from the following files:
netlist/module.h
/home/runner/work/hal/hal/src/netlist/module.cpp