hal: hal_core/python_bindings/python_bindings.h File Reference
python_bindings.h File Reference
#include "hal_core/utilities/log.h"
#include "hal_core/plugin_system/plugin_interface_gui.h"
#include "hal_core/plugin_system/plugin_manager.h"
#include "hal_core/utilities/utils.h"
#include "hal_core/defines.h"
#include "hal_core/netlist/boolean_function.h"
#include "hal_core/netlist/gate.h"
#include "hal_core/netlist/gate_library/gate_library.h"
#include "hal_core/netlist/gate_library/gate_type/gate_type.h"
#include "hal_core/netlist/gate_library/gate_type/gate_type_lut.h"
#include "hal_core/netlist/gate_library/gate_type/gate_type_sequential.h"
#include "hal_core/netlist/hdl_writer/hdl_writer_manager.h"
#include "hal_core/netlist/module.h"
#include "hal_core/netlist/net.h"
#include "hal_core/netlist/netlist.h"
#include "hal_core/netlist/netlist_factory.h"
#include "hal_core/netlist/persistent/netlist_serializer.h"
#include "pybind11/functional.h"
#include "pybind11/operators.h"
#include "pybind11/pybind11.h"
#include "pybind11/stl.h"
#include "pybind11/stl_bind.h"
Classes
class RawPtrWrapper< T >
Functions
PYBIND11_DECLARE_HOLDER_TYPE (T, RawPtrWrapper< T >, true) namespace hal
Function Documentation
PYBIND11_DECLARE_HOLDER_TYPE()
PYBIND11_DECLARE_HOLDER_TYPE (T , RawPtrWrapper< T > , true)
Initializes Python bindings for the HAL path in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL data container in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL core utils in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL gate type in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL LUT gate type in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL sequential gate type in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL gate library in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL endpoint in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL netlist in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL gate in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL net in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL module in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL netlist factory in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL hdl writer manager in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL plugin manager in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL plugin interfaces in a python module.
Parameters
[in] m - the python module
Initializes Python bindings for the HAL Boolean function in a python module.
Parameters
[in] m - the python module
References hal::boolean_function_init(), hal::core_utils_init(), hal::data_container_init(), hal::endpoint_init(), hal::gate_init(), hal::gate_library_init(), hal::gate_type_init(), hal::gate_type_lut_init(), hal::gate_type_sequential_init(), hal::hdl_writer_manager_init(), hal::module_init(), hal::net_init(), hal::netlist_factory_init(), hal::netlist_init(), hal::path_init(), hal::plugin_interfaces_init(), and hal::plugin_manager_init().