hal: gate_type_lut Class Reference
gate_type_lut Class Reference
Netlist
#include <gate_type_lut.h>
Public Member Functions
gate_type_lut (const std::string &name)
~gate_type_lut () override=default
void add_output_from_init_string_pin (const std::string &output_pin)
std::unordered_set< std::string > get_output_from_init_string_pins () const
void set_config_data_category (const std::string &category)
std::string get_config_data_category () const
void set_config_data_identifier (const std::string &identifier)
std::string get_config_data_identifier () const
void set_config_data_ascending_order (bool ascending)
bool is_config_data_ascending_order () const
Public Member Functions inherited from gate_type
gate_type (const std::string &name)
virtual ~gate_type ()=default
std::string to_string () const
bool operator== (const gate_type &other) const
bool operator!= (const gate_type &other) const
std::string get_name () const
base_type get_base_type () const
void add_input_pin (std::string input_pin)
void add_input_pins (const std::vector< std::string > &input_pins)
std::vector< std::string > get_input_pins () const
void add_output_pin (std::string output_pin)
void add_output_pins (const std::vector< std::string > &output_pins)
std::vector< std::string > get_output_pins () const
void add_boolean_function (std::string name, boolean_function bf)
std::unordered_map< std::string, boolean_function > get_boolean_functions () const
Additional Inherited Members
Public Types inherited from gate_type
enum base_type { base_type::combinatorial, base_type::lut, base_type::ff, base_type::latch }
Detailed Description
LUT gate type class containing information about the internals of a specific LUT gate type.
Constructor & Destructor Documentation
gate_type_lut()
gate_type_lut::gate_type_lut (const std::string & name)
Constructor for a LUT gate type.
Parameters
[in] name - The name of the LUT gate type.
References get_config_data_category(), get_config_data_identifier(), is_config_data_ascending_order(), and gate_type::lut.
~gate_type_lut()
gate_type_lut::~gate_type_lut () override default
Member Function Documentation
add_output_from_init_string_pin()
void gate_type_lut::add_output_from_init_string_pin (const std::string & output_pin)
Adds an output pin to the collection of output pins that generate their output not from a boolean function but an initialization string.
Parameters
[in] output_pin - The name of the output string.
Referenced by PYBIND11_PLUGIN().
get_output_from_init_string_pins()
std::unordered_set< std::string > gate_type_lut::get_output_from_init_string_pins () const
Get the set of output pins that generate their output not from a boolean function but an initialization string.
Returns
Set of oputput pin names.
Referenced by PYBIND11_PLUGIN().
set_config_data_category()
void gate_type_lut::set_config_data_category (const std::string & category)
Set the category in which to find the INIT string.
Parameters
[in] category - The category as a string.
Referenced by PYBIND11_PLUGIN().
get_config_data_category()
std::string gate_type_lut::get_config_data_category () const
Get the category in which to find the INIT string.
Returns
The string describing the category.
Referenced by gate_type_lut(), gate::get_boolean_functions(), and PYBIND11_PLUGIN().
set_config_data_identifier()
void gate_type_lut::set_config_data_identifier (const std::string & identifier)
Set the identifier used to specify the INIT string.
Parameters
[in] identifier - The identifier as a string.
Referenced by PYBIND11_PLUGIN().
get_config_data_identifier()
std::string gate_type_lut::get_config_data_identifier () const
Get the identifier used to specify the INIT string.
Returns
The identifier as a string.
Referenced by gate_type_lut(), and PYBIND11_PLUGIN().
set_config_data_ascending_order()
void gate_type_lut::set_config_data_ascending_order (bool ascending)
Set the bit-order of the INIT string.
Parameters
[in] ascending - True if ascending bit-order, false otherwise.
Referenced by PYBIND11_PLUGIN().
is_config_data_ascending_order()
bool gate_type_lut::is_config_data_ascending_order () const
Get the bit-order of the INIT string.
Returns
True if ascending bit-order, false otherwise.
Referenced by gate_type_lut(), and PYBIND11_PLUGIN().
The documentation for this class was generated from the following files:
netlist/gate_library/gate_type/gate_type_lut.h
/home/runner/work/hal/hal/src/netlist/gate_library/gate_type/gate_type_lut.cpp