hal: net Class Reference
net Class Reference
Netlist
#include <net.h>
Public Member Functions
u32 get_id () const
std::shared_ptr< netlist > get_netlist () const
std::string get_name () const
void set_name (const std::string &name)
bool set_src (const std::shared_ptr< gate > &gate, const std::string &pin_type)
bool set_src (const endpoint &src)
bool remove_src ()
endpoint get_src () const
bool add_dst (const std::shared_ptr< gate > &gate, const std::string &pin_type)
bool add_dst (const endpoint &dst)
bool remove_dst (const std::shared_ptr< gate > &gate, const std::string &pin_type)
bool remove_dst (const endpoint &dst)
bool is_a_dst (const std::shared_ptr< gate > &gate) const
bool is_a_dst (const endpoint &ep) const
u32 get_num_of_dsts () const
std::vector< endpoint > get_dsts (const std::function< bool(const endpoint &ep)> &filter=nullptr) const
bool is_unrouted () const
bool mark_global_input_net ()
bool mark_global_output_net ()
bool unmark_global_input_net ()
bool unmark_global_output_net ()
bool is_global_input_net () const
bool is_global_output_net () const
Public Member Functions inherited from data_container
data_container ()=default
virtual ~data_container ()=default
bool set_data (const std::string &category, const std::string &key, const std::string &data_type, const std::string &value, const bool log_with_info_level=false)
bool delete_data (const std::string &category, const std::string &key, const bool log_with_info_level=false)
std::map< std::tuple< std::string, std::string >, std::tuple< std::string, std::string > > get_data () const
std::tuple< std::string, std::string > get_data_by_key (const std::string &category, const std::string &key) const
std::vector< std::tuple< std::string, std::string > > get_data_keys () const
Friends
class netlist_internal_manager
Detailed Description
Net class containing information about a net including its source and destination.
Member Function Documentation
get_id()
u32 net::get_id () const
Gets the unique id of the net.
Returns
The net's id.
Referenced by PYBIND11_PLUGIN().
get_netlist()
std::shared_ptr< netlist > net::get_netlist () const
Get the parent netlist of the net.
Returns
The netlist.
References netlist::get_shared().
Referenced by is_a_dst().
get_name()
std::string net::get_name () const
Get the name of the net.
Returns
The name.
Referenced by hdl_parser_vhdl::parse(), and PYBIND11_PLUGIN().
set_name()
void net::set_name (const std::string & name)
Set the name of the net.
Parameters
[in] name - The new name.
References log_error, log_info, gate_event_handler::name_changed, net_event_handler::notify(), and core_utils::trim().
Referenced by PYBIND11_PLUGIN().
set_src() [1/2]
bool net::set_src (const std::shared_ptr< gate > & gate, const std::string & pin_type)
src specific functions Set the source of this net to a gate's output pin.
Parameters
[in] gate - The source gate.
[in] pin_type - The pin of the source gate.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
set_src() [2/2]
bool net::set_src (const endpoint & src)
Set the source of this net to a gate's output pin.
Parameters
[in] src - The source endpoint.
Returns
True on success.
remove_src()
bool net::remove_src ()
Remove the source of the net.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
get_src()
endpoint net::get_src () const
Get the src of the net. If there was no src assigned, the gate element of the returned endpoint is a nullptr.
Returns
The source endpoint.
Referenced by module::get_input_nets(), gate::get_predecessors(), hdl_parser_verilog::parse(), hdl_parser_vhdl::parse(), and PYBIND11_PLUGIN().
add_dst() [1/2]
bool net::add_dst (const std::shared_ptr< gate > & gate, const std::string & pin_type)
dst specific functions Add a destination to this net.
Parameters
[in] gate - The destination gate.
[in] pin_type - The input pin of the gate.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
add_dst() [2/2]
bool net::add_dst (const endpoint & dst)
Add a destination to this net.
Parameters
[in] dst - The destination endpoint.
Returns
True on success.
remove_dst() [1/2]
bool net::remove_dst (const std::shared_ptr< gate > & gate, const std::string & pin_type)
Remove a destination from this net.
Parameters
[in] gate - The destination gate.
[in] pin_type - The input pin of the gate.
Returns
True on success.
Referenced by PYBIND11_PLUGIN().
remove_dst() [2/2]
bool net::remove_dst (const endpoint & dst)
Remove a destination from this net.
Parameters
[in] dst - The destination endpoint.
Returns
True on success.
is_a_dst() [1/2]
bool net::is_a_dst (const std::shared_ptr< gate > & gate) const
Check whether a gate is a destination of this net.
Parameters
[in] gate - The destination gate.
Returns
True if the input's pin is a destination.
References get_netlist(), and log_error.
Referenced by PYBIND11_PLUGIN().
is_a_dst() [2/2]
bool net::is_a_dst (const endpoint & ep) const
Check whether a gate's input pin is a destination of this net.
Parameters
[in] ep - The input endpoint.
Returns
True if the input's pin is a destination.
References endpoint::gate, get_netlist(), and log_error.
get_num_of_dsts()
u32 net::get_num_of_dsts () const
Get the number of destinations.
Faster than get_dsts().size().
Returns
The number of destinations of this net.
Referenced by hdl_parser_verilog::parse(), hdl_parser_vhdl::parse(), and PYBIND11_PLUGIN().
get_dsts()
std::vector< endpoint > net::get_dsts (const std::function< bool(const endpoint &ep)> & filter = nullptr) const
Get the vector of destinations of the net.
Parameters
[in] filter - a filter for endpoints.
Returns
A vector of destination endpoints.
Referenced by module::get_internal_nets(), module::get_output_nets(), gate::get_successors(), and PYBIND11_PLUGIN().
is_unrouted()
bool net::is_unrouted () const
Check whether the net is routed, i.e. it has no source or the no destinations.
Returns
True if the net is unrouted.
References endpoint::gate.
Referenced by PYBIND11_PLUGIN().
mark_global_input_net()
bool net::mark_global_input_net ()
Mark this net as a global input net.
Returns
True on success.
References netlist::mark_global_input_net().
Referenced by hdl_parser_verilog::parse(), and PYBIND11_PLUGIN().
mark_global_output_net()
bool net::mark_global_output_net ()
Mark this net as a global output net.
Returns
True on success.
References netlist::mark_global_output_net().
Referenced by hdl_parser_verilog::parse(), and PYBIND11_PLUGIN().
unmark_global_input_net()
bool net::unmark_global_input_net ()
Unmark this net as a global input net.
Returns
True on success.
References netlist::unmark_global_input_net().
Referenced by PYBIND11_PLUGIN().
unmark_global_output_net()
bool net::unmark_global_output_net ()
Unmark this net as a global output net.
Returns
True on success.
References netlist::unmark_global_output_net().
Referenced by PYBIND11_PLUGIN().
is_global_input_net()
bool net::is_global_input_net () const
Checks whether this net is a global input net.
Returns
True if the net is a global input net.
References netlist::is_global_input_net().
Referenced by hdl_parser_verilog::parse(), hdl_parser_vhdl::parse(), and PYBIND11_PLUGIN().
is_global_output_net()
bool net::is_global_output_net () const
Checks whether this net is a global output net.
Returns
True if the net is a global output net.
References netlist::is_global_output_net().
Referenced by hdl_parser_verilog::parse(), hdl_parser_vhdl::parse(), and PYBIND11_PLUGIN().
Friends And Related Function Documentation
netlist_internal_manager
friend class netlist_internal_manager friend
The documentation for this class was generated from the following files:
netlist/net.h
/home/runner/work/hal/hal/src/netlist/net.cpp