hal: hdl_parser_dispatcher Namespace Reference
hdl_parser_dispatcher Namespace Reference
HDL Interfaces » HDL Parsers
Functions
program_options get_cli_options ()
std::set< std::string > get_gui_option ()
std::shared_ptr< netlist > parse (const hal::path &file_name, const program_arguments &args)
std::shared_ptr< netlist > parse (const std::string &gate_library, const std::string &parser_name, const hal::path &file_name)
std::shared_ptr< netlist > parse (const std::string &gate_library, const std::string &parser_name, const std::string &file_name)
Function Documentation
get_cli_options()
program_options hdl_parser_dispatcher::get_cli_options ()
Returns the command line interface options of the hdl parser dispatcher
Returns
The options.
References program_options::add(), and program_options::REQUIRED_PARAM.
get_gui_option()
std::set< std::string > hdl_parser_dispatcher::get_gui_option ()
Returns the command language options for the parse() function.
Returns
The language options.
parse() [1/3]
std::shared_ptr< netlist > hdl_parser_dispatcher::parse (const hal::path & file_name, const program_arguments & args)
Returns the netlist for the file and specified command line options.
Parameters
[in] file_name - The input file.
[in] args - The command line options.
Returns
The netlist representation of the hdl code or a nullpointer on error.
References gate_library_manager::get_gate_libraries(), program_arguments::get_parameter(), program_arguments::is_option_set(), log_error, log_info, and log_warning.
Referenced by netlist_factory::load_netlist(), and parse().
parse() [2/3]
std::shared_ptr< netlist > hdl_parser_dispatcher::parse (const std::string & gate_library, const std::string & parser_name, const hal::path & file_name)
Returns the netlist for a file, parsed with a defined parser_name and gate library.
Parameters
[in] gate_library - The gate library used in the file.
[in] parser_name - The name of the parser to use, e.g. vhdl, verilog...
[in] file_name - The input file.
Returns
The netlist representation of the hdl code or a nullpointer on error.
References log_error, log_info, hdl_parser_vhdl::parse(), and hdl_parser_verilog::parse().
parse() [3/3]
std::shared_ptr< netlist > hdl_parser_dispatcher::parse (const std::string & gate_library, const std::string & parser_name, const std::string & file_name)
Returns the netlist for a file, parsed with a defined parser_name and gate library.
Parameters
[in] gate_library - The gate library used in the file.
[in] parser_name - The name of the parser to use, e.g. vhdl, verilog...
[in] file_name - The input file. (as std::string, used for python call)
Returns
The netlist representation of the hdl code or a nullpointer on error.
References parse().