hal: log_manager Class Reference
log_manager Class Reference
#include <log.h>
Classes
struct log_sink
Public Member Functions
void set_file_name (const hal::path &file_name)
void set_format_pattern (const std::string &format)
spdlog::logger * get_channel (const std::string &channel_name="stdout") const
std::set< std::string > get_channels () const
void add_channel (const std::string &channel_name, std::vector< std::shared_ptr< log_sink >> sinks, const std::string &level="info")
void remove_channel (const std::string &channel_name)
std::string get_level_of_channel (const std::string &channel_name) const
void set_level_of_channel (const std::string &channel_name, const std::string &level)
std::set< std::string > get_available_log_levels () const
void activate_channel (const std::string &channel_name)
void deactivate_channel (const std::string &channel_name)
callback_hook< void(const spdlog::level::level_enum &, const std::string &, const std::string &)> & get_gui_callback ()
program_options & get_option_descriptions ()
void handle_options (program_arguments &args)
Static Public Member Functions
static log_manager & get_instance (const hal::path &file_name="")
static std::shared_ptr< log_sink > create_stdout_sink (const bool colored=true)
static std::shared_ptr< log_sink > create_file_sink (const hal::path &file_name="", const bool truncate=false)
static std::shared_ptr< log_sink > create_gui_sink ()
Member Function Documentation
get_instance()
log_manager & log_manager::get_instance (const hal::path & file_name = "") static
Get the log manager instance.
If the desired log file is left empty, the default log path is used.
(Singleton pattern)
Parameters
[in] file_name - The file where the log is stored.
Returns
The log manager.
References add_channel(), create_file_sink(), create_gui_sink(), and create_stdout_sink().
Referenced by create_file_sink(), get_gui_callback(), event_log::initialize(), and i_base::initialize_logging().
set_file_name()
void log_manager::set_file_name (const hal::path & file_name)
Set the log file name.
If file_name is empty, the default log file will be used.
Parameters
[in] file_name - The desired log file.
References add_channel(), create_file_sink(), get_level_of_channel(), log_info, and remove_channel().
set_format_pattern()
void log_manager::set_format_pattern (const std::string & format)
Set the logging format pattern.
Look at the speedlog documentation to get details about the format string.
Parameters
[in] format - The format string.
get_channel()
spdlog::logger * log_manager::get_channel (const std::string & channel_name = "stdout") const
Get a channel specified by name.
Parameters
[in] channel_name - Name of the channel.
Returns
The channel.
References log_error.
get_channels()
std::set< std::string > log_manager::get_channels () const
Returns all channels' names.
Returns
A set of the names.
Referenced by get_option_descriptions(), and handle_options().
add_channel()
void log_manager::add_channel (const std::string & channel_name, std::vector< std::shared_ptr< log_sink >> sinks, const std::string & level = "info")
Add a channel to the log manager.
Parameters
[in] channel_name - Name of the channel.
[in] sinks - All sinks connected to this channel.
[in] level - The severity level of that channel.
References set_level_of_channel().
Referenced by get_instance(), event_log::initialize(), i_base::initialize_logging(), and set_file_name().
remove_channel()
void log_manager::remove_channel (const std::string & channel_name)
Remove a channel from the log manager.
Parameters
[in] channel_name - Name of the channel.
Referenced by set_file_name().
get_level_of_channel()
std::string log_manager::get_level_of_channel (const std::string & channel_name) const
Get a channel's severity level.
Parameters
[in] channel_name - Name of the channel.
Returns
The severity level of that channel.
Referenced by set_file_name().
set_level_of_channel()
void log_manager::set_level_of_channel (const std::string & channel_name, const std::string & level)
Set a channel's severity level.
Parameters
[in] channel_name - Name of the channel.
[in] level - The severity level.
Referenced by activate_channel(), add_channel(), deactivate_channel(), and handle_options().
get_available_log_levels()
std::set< std::string > log_manager::get_available_log_levels () const
Get all available severity levels.
Returns
A set of severity levels.
activate_channel()
void log_manager::activate_channel (const std::string & channel_name)
Activate a channel.
By default all channels are active.
Parameters
[in] channel_name - The name of the channel.
References set_level_of_channel().
Referenced by handle_options().
deactivate_channel()
void log_manager::deactivate_channel (const std::string & channel_name)
Deactivate a channel suppressing all output.
Parameters
[in] channel_name - The name of the channel.
References set_level_of_channel().
Referenced by handle_options().
get_gui_callback()
callback_hook< void(const spdlog::level::level_enum &, const std::string &, const std::string &)> & log_manager::get_gui_callback ()
Get the GUI callback hook for displaying log messages inside the GUI.
Returns
The GUI callback hook for (level, channel, message).
References get_gui_callback(), and get_instance().
Referenced by get_gui_callback().
get_option_descriptions()
program_options & log_manager::get_option_descriptions ()
Get the program options for the logging system.
Returns
The program options.
References program_options::add(), get_channels(), program_options::get_options(), and program_options::REQUIRED_PARAM.
handle_options()
void log_manager::handle_options (program_arguments & args)
Handle parsed program options for the logging system.
Parameters
[in] args - The parsed program options.
References activate_channel(), deactivate_channel(), get_channels(), program_arguments::get_parameter(), program_arguments::is_option_set(), log_warning, and set_level_of_channel().
create_stdout_sink()
std::shared_ptr< log_manager::log_sink > log_manager::create_stdout_sink (const bool colored = true) static
Create a new logging sink which prints to stdout.
Parameters
[in] colored - If true, the output will be colored depending on the severity.
Returns
The new sink.
References log_error.
Referenced by get_instance(), event_log::initialize(), and i_base::initialize_logging().
create_file_sink()
std::shared_ptr< log_manager::log_sink > log_manager::create_file_sink (const hal::path & file_name = "", const bool truncate = false) static
Create a new logging sink which prints to a file.
If a sink for that file already exists, no new sink will be created.
If file_name is empty, the default log file will be used.
Parameters
[in] file_name - The file name.
[in] truncate - Flag whether the file should be overwritten(true) or appended to(false).
Returns
The new sink or the already existing sink.
References get_instance().
Referenced by get_instance(), event_log::initialize(), i_base::initialize_logging(), and set_file_name().
create_gui_sink()
std::shared_ptr< log_manager::log_sink > log_manager::create_gui_sink () static
Create a new logging sink which prints to the GUI.
Returns
The new sink.
Referenced by get_instance(), event_log::initialize(), and i_base::initialize_logging().
The documentation for this class was generated from the following files:
core/log.h
/home/runner/work/hal/hal/src/core/log.cpp