hal: gate_type_sequential Class Reference
gate_type_sequential Class Reference
Netlist
#include <gate_type_sequential.h>
Public Types
enum set_reset_behavior {
set_reset_behavior::U = -1, set_reset_behavior::L = 0, set_reset_behavior::H = 1, set_reset_behavior::N = 2,
set_reset_behavior::T = 3, set_reset_behavior::X = 4
}
Public Types inherited from gate_type
enum base_type { base_type::combinatorial, base_type::lut, base_type::ff, base_type::latch }
Public Member Functions
gate_type_sequential (const std::string &name, base_type bt)
~gate_type_sequential () override=default
void add_state_output_pin (std::string output_pin)
std::unordered_set< std::string > get_state_output_pins () const
void add_inverted_state_output_pin (std::string output_pin)
std::unordered_set< std::string > get_inverted_state_output_pins () const
void set_set_reset_behavior (set_reset_behavior sb1, set_reset_behavior sb2)
std::pair< set_reset_behavior, set_reset_behavior > get_set_reset_behavior () const
void set_init_data_category (const std::string &category)
std::string get_init_data_category () const
void set_init_data_identifier (const std::string &identifier)
std::string get_init_data_identifier () const
Public Member Functions inherited from gate_type
gate_type (const std::string &name)
virtual ~gate_type ()=default
std::string to_string () const
bool operator== (const gate_type &other) const
bool operator!= (const gate_type &other) const
std::string get_name () const
base_type get_base_type () const
void add_input_pin (std::string input_pin)
void add_input_pins (const std::vector< std::string > &input_pins)
std::vector< std::string > get_input_pins () const
void add_output_pin (std::string output_pin)
void add_output_pins (const std::vector< std::string > &output_pins)
std::vector< std::string > get_output_pins () const
void add_boolean_function (std::string name, boolean_function bf)
std::unordered_map< std::string, boolean_function > get_boolean_functions () const
Detailed Description
Sequential gate type class containing information about the internals of a specific sequential gate type.
Member Enumeration Documentation
set_reset_behavior
enum gate_type_sequential::set_reset_behavior strong
Enumerator
U
L
H
N
T
X
Constructor & Destructor Documentation
gate_type_sequential()
gate_type_sequential::gate_type_sequential (const std::string & name, base_type bt)
Constructor for a sequential gate type.
Parameters
[in] name - The name of the sequential gate type.
[in] bt - The base type of the sequential gate type.
References gate_type::ff, and gate_type::latch.
~gate_type_sequential()
gate_type_sequential::~gate_type_sequential () override default
Member Function Documentation
add_state_output_pin()
void gate_type_sequential::add_state_output_pin (std::string output_pin)
Add an output pin to the collection of output pins that generate their output from the next_state function.
Parameters
[in] output_pin - Name of the output pin.
Referenced by PYBIND11_PLUGIN().
get_state_output_pins()
std::unordered_set< std::string > gate_type_sequential::get_state_output_pins () const
Get the output pins that use the next_state function to generate their output.
Returns
The set of output pin names.
Referenced by PYBIND11_PLUGIN().
add_inverted_state_output_pin()
void gate_type_sequential::add_inverted_state_output_pin (std::string output_pin)
Add an output pin to the collection of output pins that generate their output from the inverted next_state function.
Parameters
[in] output_pin - Name of the output pin.
Referenced by PYBIND11_PLUGIN().
get_inverted_state_output_pins()
std::unordered_set< std::string > gate_type_sequential::get_inverted_state_output_pins () const
Get the output pins that use the inverted next_state function to generate their output.
Returns
The set of output pin names.
Referenced by PYBIND11_PLUGIN().
set_set_reset_behavior()
void gate_type_sequential::set_set_reset_behavior (set_reset_behavior sb1, set_reset_behavior sb2)
Set the behavior that describes the internal state when both set and reset are active. Each may be one of the following:
U: not specified for this gate type
L: set internal state to 0
H: set internal state to 1
N: keep current internal state
T: toggle internal state
X: undefined behavior
Parameters
[in] sb1 - The value specifying the behavior for the internal state.
[in] sb2 - The value specifying the behavior for the inverted internal state.
Referenced by PYBIND11_PLUGIN().
get_set_reset_behavior()
std::pair< gate_type_sequential::set_reset_behavior, gate_type_sequential::set_reset_behavior > gate_type_sequential::get_set_reset_behavior () const
Get the behavior of the internal state and the inverted internal state when both set and reset are active. May be one of the following:
U: not specified for this gate type
L: set (inverted) internal state to 0
H: set (inverted) internal state to 1
N: keep current (inverted) internal state
T: toggle (inverted) internal state
X: undefined behavior
Returns
The boolean function.
Referenced by PYBIND11_PLUGIN().
set_init_data_category()
void gate_type_sequential::set_init_data_category (const std::string & category)
Set the category in which to find the INIT string.
Parameters
[in] category - The category as a string.
Referenced by PYBIND11_PLUGIN().
get_init_data_category()
std::string gate_type_sequential::get_init_data_category () const
Get the category in which to find the INIT string.
Returns
The string describing the category.
Referenced by PYBIND11_PLUGIN().
set_init_data_identifier()
void gate_type_sequential::set_init_data_identifier (const std::string & identifier)
Set the identifier used to specify the INIT string.
Parameters
[in] identifier - The identifier as a string.
Referenced by PYBIND11_PLUGIN().
get_init_data_identifier()
std::string gate_type_sequential::get_init_data_identifier () const
Get the identifier used to specify the INIT string.
Returns
The identifier as a string.
Referenced by PYBIND11_PLUGIN().
The documentation for this class was generated from the following files:
netlist/gate_library/gate_type/gate_type_sequential.h
/home/runner/work/hal/hal/src/netlist/gate_library/gate_type/gate_type_sequential.cpp