hal: hal::module_event_handler Namespace Reference
hal::module_event_handler Namespace Reference
Enumerations
enum event {
created, removed, name_changed, type_changed,
parent_changed, submodule_added, submodule_removed, gate_assigned,
gate_removed, input_port_name_changed, output_port_name_changed
}
Functions
NETLIST_API void enable (bool flag)
NETLIST_API void notify (event ev, Module *module, u32 associated_data=0xFFFFFFFF)
NETLIST_API void register_callback (const std::string &name, std::function< void(event e, Module *module, u32 associated_data)> function)
NETLIST_API void unregister_callback (const std::string &name)
void register_callback (const std::string &name, std::function< void(event, Module *, u32)> function)
Enumeration Type Documentation
event
enum hal::module_event_handler::event
Enumerator
created
no associated_data
removed
no associated_data
name_changed
no associated_data
type_changed
no associated_data
parent_changed
no associated_data
submodule_added
associated_data = id of added module
submodule_removed
associated_data = id of removed module
gate_assigned
associated_data = id of inserted gate
gate_removed
associated_data = id of removed gate
input_port_name_changed
associated_data = id of respective net
output_port_name_changed
associated_data = id of respective net
Function Documentation
enable()
void hal::module_event_handler::enable (bool flag)
Enables/disables callbacks for this handler.
Enabled by default.
Parameters
[in] flag - True to enable, false to disable.
Referenced by hal::event_controls::enable_all().
notify()
void hal::module_event_handler::notify (event ev, Module * module, u32 associated_data = 0xFFFFFFFF)
Executes all registered callbacks.
Parameters
[in] ev - the event which occured.
[in] module - The affected object.
[in] associated_data - may have a meaning depending on the event type.
Referenced by hal::Module::set_input_port_name(), hal::Module::set_name(), hal::Module::set_output_port_name(), hal::Module::set_parent_module(), and hal::Module::set_type().
register_callback() [1/2]
NETLIST_API void hal::module_event_handler::register_callback (const std::string & name, std::function< void(event e, Module *module, u32 associated_data)> function)
Registers a callback function.
Parameters
[in] name - name of the callback, used for callback removal.
[in] function - The callback function.
unregister_callback()
void hal::module_event_handler::unregister_callback (const std::string & name)
Removes a callback function.
Parameters
[in] name - name of the callback.
register_callback() [2/2]
void hal::module_event_handler::register_callback (const std::string & name, std::function< void(event, Module *, u32)> function)