hal: hal::HDLWriterDispatcher Namespace Reference
hal::HDLWriterDispatcher Namespace Reference
HDL Interfaces » HDL Writers
Functions
ProgramOptions get_cli_options ()
bool write (std::shared_ptr< Netlist > g, const ProgramArguments &args)
bool write (std::shared_ptr< Netlist > g, const std::string &format, const std::filesystem::path &file_name)
Function Documentation
get_cli_options()
ProgramOptions hal::HDLWriterDispatcher::get_cli_options ()
Returns the command line interface options of the hdl writer dispatcher
Returns
The options.
References hal::ProgramOptions::add().
Referenced by hal::hdl_writer_dispatcher_init().
write() [1/2]
bool hal::HDLWriterDispatcher::write (std::shared_ptr< Netlist > g, const ProgramArguments & args)
Writes the netlist into a file specified in command line options.
Parameters
[in] g - The netlist.
[in] args - The command line options.
Returns
True on success.
References hal::ProgramArguments::get_parameter(), and hal::ProgramArguments::is_option_set().
Referenced by hal::hdl_writer_dispatcher_init().
write() [2/2]
bool hal::HDLWriterDispatcher::write (std::shared_ptr< Netlist > g, const std::string & format, const std::filesystem::path & file_name)
Writes the netlist into a file with a defined format
Parameters
[in] g - The netlist.
[in] format - The target format of the file, e.g. vhdl, verilog...
[in] file_name - The input file.
Returns
True on success.
References log_error, log_info, hal::HDLWriterVerilog::write(), and hal::HDLWriterVHDL::write().