hal: netlist_serializer Namespace Reference
netlist_serializer Namespace Reference
Netlist » Persistency
Functions
NETLIST_API bool serialize_to_file (std::shared_ptr< netlist > nl, const hal::path &hal_file)
NETLIST_API std::shared_ptr< netlist > deserialize_from_file (const hal::path &hal_file)
Function Documentation
serialize_to_file()
bool netlist_serializer::serialize_to_file (std::shared_ptr< netlist > nl, const hal::path & hal_file)
Serializes a netlist into a .hal file.
Invokes the hal_file_manager and all associated callbacks.
Parameters
[in] nl - The netlist to serialize.
[in] hal_file - The file to serialize to.
Returns
True on success.
References DURATION, log_error, log_info, and hal_file_manager::serialize().
deserialize_from_file()
std::shared_ptr< netlist > netlist_serializer::deserialize_from_file (const hal::path & hal_file)
Deserializes a netlist from a .hal file.
Invokes the hal_file_manager and all associated callbacks.
Parameters
[in] hal_file - The file to deserialize from.
Returns
The deserialized netlist.
References hal_file_manager::deserialize(), DURATION, log_error, log_info, and log_warning.
Referenced by netlist_factory::load_netlist().