hal: hal::hdl_writer_manager Namespace Reference
hal::hdl_writer_manager Namespace Reference
HAL Core » Netlist » Netlist Writer
Typedefs
using WriterFactory = std::function< std::unique_ptr< HDLWriter >()>
Functions
ProgramOptions get_cli_options ()
NETLIST_API void register_writer (const std::string &name, const WriterFactory &writer_factory, const std::vector< std::string > &supported_file_extensions)
NETLIST_API void unregister_writer (const std::string &name)
bool write (Netlist *netlist, const ProgramArguments &args)
bool write (Netlist *netlist, const std::filesystem::path &file_name)
bool write (Netlist *netlist, const std::string &type_extension, std::stringstream &stream)
Typedef Documentation
WriterFactory
using hal::hdl_writer_manager::WriterFactory = typedef std::function<std::unique_ptr<HDLWriter>()>
Function Documentation
get_cli_options()
ProgramOptions hal::hdl_writer_manager::get_cli_options ()
Returns the command line interface options of the hdl writer dispatcher
Returns
The options.
References hal::ProgramOptions::A_REQUIRED_PARAMETER, and hal::ProgramOptions::add().
Referenced by hal::hdl_writer_manager_init().
register_writer()
void hal::hdl_writer_manager::register_writer (const std::string & name, const WriterFactory & writer_factory, const std::vector< std::string > & supported_file_extensions)
Registers a new HDL writer for a selection of file types. If writers for some of the extensions already exist, they are not changed, only the new ones are registered.
Parameters
[in] name - The name of the writer.
[in] writer_factory - A factory function that constructs a new writer instance.
[in] supported_file_extensions - The file extensions this writer can process.
References log_info, log_warning, hal::utils::to_lower(), and hal::utils::trim().
unregister_writer()
void hal::hdl_writer_manager::unregister_writer (const std::string & name)
Unregisters a specific writer.
Parameters
[in] name - The name of the writer.
References log_info.
write() [1/3]
bool hal::hdl_writer_manager::write (Netlist * netlist, const ProgramArguments & args)
Writes the netlist into a file specified in command line options.
Parameters
[in] netlist - The netlist.
[in] args - The command line options.
Returns
True on success.
References hal::ProgramArguments::get_parameter(), and hal::ProgramArguments::is_option_set().
Referenced by hal::hdl_writer_manager_init().
write() [2/3]
bool hal::hdl_writer_manager::write (Netlist * netlist, const std::filesystem::path & file_name)
Writes the netlist into a file with a defined format
Parameters
[in] netlist - The netlist.
[in] file_name - The output file name.
Returns
True on success.
References hal::Netlist::get_design_name(), log_error, and log_info.
write() [3/3]
bool hal::hdl_writer_manager::write (Netlist * netlist, const std::string & type_extension, std::stringstream & stream)
Writes the netlist into a stringstream with a defined format
Parameters
[in] netlist - The netlist.
[in] type_extension - The file extension of the output format
[out] stream - The output stream.
Returns
True on success.