hal: program_options Class Reference
program_options Class Reference
HAL Core
#include <program_options.h>
Public Member Functions
program_options (const std::string &name="")
~program_options ()=default
program_arguments parse (int argc, const char *argv[])
std::vector< std::string > get_unknown_arguments ()
bool is_registered (const std::string &flag) const
bool add (const std::string &flag, const std::string &description, const std::initializer_list< std::string > &parameters={})
bool add (const std::initializer_list< std::string > &flags, const std::string &description, const std::initializer_list< std::string > &parameters={})
bool add (const program_options &other_options, const std::string &category="")
std::string get_options_string () const
std::vector< std::tuple< std::set< std::string >, std::string > > get_options () const
Static Public Attributes
static const std::string REQUIRED_PARAM = "__REQUIRED_PARAM__"
constant to specify that a parameter is required and does not have a default value.
Constructor & Destructor Documentation
program_options()
program_options::program_options (const std::string & name = "") explicit
Constructor, optionally takes a name for grouping in get_options_string()
Parameters
[in] name - The name of this group of program options.
~program_options()
program_options::~program_options () default
Member Function Documentation
parse()
program_arguments program_options::parse (int argc, const char * argv[])
Parses the command line arguments into the internal structure.
Parameters
[in] argc - Number of arguments.
[in] argv - Array of arguments.
Returns
The parsed arguments.
References die, core_utils::join(), REQUIRED_PARAM, and program_arguments::set_option().
get_unknown_arguments()
std::vector< std::string > program_options::get_unknown_arguments ()
Returns the command line arguments which could not be parsed.
Only valid after parse() was called.
Returns
A vector containing all strings which could not be parsed.
is_registered()
bool program_options::is_registered (const std::string & flag) const
Checks whether a flag is already registered for an option.
No flag can be registered twice.
Parameters
[in] flag - The flag to check.
Returns
True if the flag is already registered.
Referenced by add().
add() [1/3]
bool program_options::add (const std::string & flag, const std::string & description, const std::initializer_list< std::string > & parameters = {})
Adds a new option with a single flag.
The size of parameters is the number of parameters this option gets.
Use program_options::REQUIRED_PARAM to set a parameter as required.
The values in parameters contain default values, which are returned by get_parameter_list() / get_parameter() if the user did not supply parameters himself.
Parameters
[in] flag - The flag activating the option.
[in] description - A description of the option.
[in] parameters - A list of default values for all parameters. [optional]
Returns
True on success.
Referenced by hdl_writer_dispatcher::get_cli_options(), hdl_parser_dispatcher::get_cli_options(), and log_manager::get_option_descriptions().
add() [2/3]
bool program_options::add (const std::initializer_list< std::string > & flags, const std::string & description, const std::initializer_list< std::string > & parameters = {})
Adds a new option with a multiple flags.
The size of parameters is the number of parameters this option gets.
Use program_options::REQUIRED_PARAM to set a parameter as required.
The values in parameters contain default values, which are returned by get_parameter_list() / get_parameter() if the user did not supply parameters himself.
Parameters
[in] flags - The flags activating the option.
[in] description - A description of the option.
[in] parameters - A list of default values for all parameters. [optional]
Returns
True on success.
References is_registered(), log_error, REQUIRED_PARAM, and core_utils::trim().
add() [3/3]
bool program_options::add (const program_options & other_options, const std::string & category = "")
Adds another set of options.
A category can be supplied for grouping in the get_options_string() function.
Parameters
[in] other_options - The set of options to add.
[in] category - A category for the added options. [optional]
Returns
True on success.
References log_error.
get_options_string()
std::string program_options::get_options_string () const
Returns a nicely formatted string of all options and description.
Includes categorys of added program_options for grouping.
Useful for "usage" messages.
Returns
The formatted string.
get_options()
std::vector< std::tuple< std::set< std::string >, std::string > > program_options::get_options () const
Returns all options' flags and their description.
Returns
A vector of ((1) a set with all flags of the option, (2) the description of the option).
References core_utils::join(), and REQUIRED_PARAM.
Referenced by log_manager::get_option_descriptions().
Member Data Documentation
REQUIRED_PARAM
const std::string program_options::REQUIRED_PARAM = "__REQUIRED_PARAM__" static
constant to specify that a parameter is required and does not have a default value.
Referenced by add(), hdl_parser_dispatcher::get_cli_options(), log_manager::get_option_descriptions(), get_options(), and parse().
The documentation for this class was generated from the following files:
core/program_options.h
/home/runner/work/hal/hal/src/core/program_options.cpp