hal: hdl_writer_dispatcher Namespace Reference
hdl_writer_dispatcher Namespace Reference
HDL Interfaces » HDL Writers
Functions
program_options get_cli_options ()
bool write (std::shared_ptr< netlist > g, const program_arguments &args)
bool write (std::shared_ptr< netlist > g, const std::string &format, const hal::path &file_name)
Function Documentation
get_cli_options()
program_options hdl_writer_dispatcher::get_cli_options ()
Returns the command line interface options of the hdl writer dispatcher
Returns
The options.
References program_options::add().
Referenced by PYBIND11_PLUGIN().
write() [1/2]
bool hdl_writer_dispatcher::write (std::shared_ptr< netlist > g, const program_arguments & args)
Writes the netlist into a file specified in command line options.
Parameters
[in] g - The netlist.
[in] args - The command line options.
Returns
True on success.
References program_arguments::get_parameter(), and program_arguments::is_option_set().
Referenced by PYBIND11_PLUGIN().
write() [2/2]
bool hdl_writer_dispatcher::write (std::shared_ptr< netlist > g, const std::string & format, const hal::path & file_name)
Writes the netlist into a file with a defined format
Parameters
[in] g - The netlist.
[in] format - The target format of the file, e.g. vhdl, verilog...
[in] file_name - The input file.
Returns
True on success.
References log_error, log_info, hdl_writer_verilog::write(), and hdl_writer_vhdl::write().