hal: plugin_manager Namespace Reference
plugin_manager Namespace Reference
HAL Core
Functions
void add_existing_options_description (const program_options &existing_options)
std::set< std::string > get_plugin_names ()
std::map< std::string, std::string > get_flag_to_plugin_mapping ()
program_options get_cli_plugin_options ()
bool load_all_plugins (const std::vector< hal::path > &directory_names={})
bool load (const std::string &plugin_name, const hal::path &file_name)
bool unload_all_plugins ()
bool unload (const std::string &plugin_name)
std::shared_ptr< i_base > get_plugin_instance (const std::string &plugin_name, bool initialize=true)
u64 add_model_changed_callback (std::function< void(bool, std::string const &, std::string const &)> callback)
void remove_model_changed_callback (u64 id)
Detailed Description
Plugin manager to load and unload plugins
Function Documentation
add_existing_options_description()
void plugin_manager::add_existing_options_description (const program_options & existing_options)
Add existing program options.
Required to detect whether a plugin reuses existing flags.
Parameters
[in] existing_options - The existing options.
get_plugin_names()
std::set< std::string > plugin_manager::get_plugin_names ()
Get the names of all loaded plugins.
Returns
The set of plugin names.
Referenced by PYBIND11_PLUGIN().
get_flag_to_plugin_mapping()
std::map< std::string, std::string > plugin_manager::get_flag_to_plugin_mapping ()
Get a mapping of flags pointing to their corresponding plugin.
Returns
A map from flag to plugin name.
get_cli_plugin_options()
program_options plugin_manager::get_cli_plugin_options ()
Returns command line interface options for all plugins
Returns
The program options
load_all_plugins()
bool plugin_manager::load_all_plugins (const std::vector< hal::path > & directory_names = {})
Load all plugins in the specified diretories.
If directory_names is empty, the default directories will be searched.
Parameters
[in] directory_names - A vector of directory paths.
Returns
True on success.
References load(), and log_debug.
Referenced by PYBIND11_PLUGIN().
load()
bool plugin_manager::load (const std::string & plugin_name, const hal::path & file_name)
Load a single plugin by specifying a name and the file path,.
Parameters
[in] plugin_name - The desired name, unique in the framework.
[in] file_name - The path to the plugin file.
Returns
True on success.
References cli, i_cli::get_cli_options(), library_loader::get_function(), library_loader::load_library(), log_debug, log_error, and log_info.
Referenced by gate_library_manager::get_gate_library(), gate_library_manager::load_all(), load_all_plugins(), and PYBIND11_PLUGIN().
unload_all_plugins()
bool plugin_manager::unload_all_plugins ()
Releases all plugins and associated resources.
Returns
True on success.
References log_debug, log_info, and unload().
Referenced by PYBIND11_PLUGIN().
unload()
bool plugin_manager::unload (const std::string & plugin_name)
Releases all associated resources related to one plugin.
Parameters
[in] plugin_name - The plugin to unload.
Returns
True on success.
References get_plugin_instance(), event_log::initialize(), log_debug, log_error, and log_info.
Referenced by unload_all_plugins().
get_plugin_instance()
std::shared_ptr< i_base > plugin_manager::get_plugin_instance (const std::string & plugin_name, bool initialize = true)
Gets the basic interface for a plugin specified by name. By default calls the initialize() function of the plugin.
Parameters
[in] plugin_name - The plugin name.
[in] initialize - If false, the plugin's initialize function is not called.
Returns
A plugin instance.
Gets a specific interface for a plugin specified by name. By default calls the initialize() function of the plugin.
Parameters
[in] plugin_name - The plugin name.
[in] initialize - If false, the plugin's initialize function is not called.
Returns
A plugin instance.
References add_model_changed_callback(), event_log::initialize(), and remove_model_changed_callback().
Referenced by unload().
add_model_changed_callback()
u64 plugin_manager::add_model_changed_callback (std::function< void(bool, std::string const &, std::string const &)> callback)
Add a callback to notify the GUI about loaded or unloaded plugins.
Parameters
[in] callback - The callback function. Parameters are:
bool:True = load, false = unload.
std::string - The plugin name.
std::string - The plugin path.
Returns
The id of the registered callback.
References log_error.
Referenced by get_plugin_instance().
remove_model_changed_callback()
void plugin_manager::remove_model_changed_callback (u64 id)
Remove a registered callback.
Parameters
[in] id - The id of the registered callback.
Referenced by get_plugin_instance().